### ISSUE TITLE
Heroku deployment - RuntimeError - ERR max number of clients reached

### ISSUE THREAD

**Issue by runlevel5** [mperham/sidekiq#117]
Hi there

Firstly, please excuse me for posting on GH Issues. Because I am not so sure if this is an issue of Sidekiq or just something I did wrong on my setup.

I've deployed a simple Rails 3.2.2 app with Sidekiq Monitor app mount to `/sidekiq`. I did not have any custom configuration, all are default Sidekiq.

My heroku has 2 worker processes:

```
$ heroku ps
192-168-1-3:spree-thurley macbookair$ heroku ps
Process   State            Command                               
--------  ---------------  ------------------------------------  
web.1     up for 9m        bundle exec puma -p $PORT -C ./con..  
worker.1  up for 45s   bundle exec sidekiq                   
worker.2  up for 13s       bundle exec sidekiq                   
```

Initially the both 2 sidekiq processes are up and running normally. When I browse `/sidekiq`, I got error in heroku logs:

```
2012-04-09T11:00:41+00:00 heroku[worker.2]: Starting process with command `bundle exec sidekiq`
2012-04-09T11:00:42+00:00 heroku[worker.2]: State changed from starting to up
2012-04-09T11:00:51+00:00 app[worker.2]: DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/01/04/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /app/config/environment.rb:5)
2012-04-09T11:00:51+00:00 app[worker.2]: DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/01/04/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /app/config/environment.rb:5)
2012-04-09T11:01:02+00:00 app[worker.2]: 2012-04-09T11:01:02Z 1 TID-ue0i8 INFO: Booting sidekiq 0.11.1 with Redis at guppy.redistogo.com:9366
2012-04-09T11:01:02+00:00 app[worker.2]: 2012-04-09T11:01:02Z 1 TID-ue0i8 INFO: Running in ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-linux]
2012-04-09T11:01:02+00:00 app[worker.2]: ERR max number of clients reached
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:47:in `call'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:24:in `connect'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:247:in `ensure_connected'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:137:in `block in process'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:206:in `logging'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:136:in `process'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:46:in `call'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis.rb:435:in `block in sadd'
2012-04-09T11:01:02+00:00 app[worker.2]: /usr/local/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis.rb:434:in `sadd'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/sidekiq-0.11.1/lib/sidekiq/processor.rb:27:in `block in initialize'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/connection_pool-0.9.1/lib/connection_pool.rb:47:in `with'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/sidekiq-0.11.1/lib/sidekiq.rb:60:in `redis'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/sidekiq-0.11.1/lib/sidekiq/util.rb:54:in `redis'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/sidekiq-0.11.1/lib/sidekiq/processor.rb:27:in `initialize'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.10.0/lib/celluloid/calls.rb:56:in `dispatch'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.10.0/lib/celluloid/actor.rb:212:in `block in handle_message'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.10.0/lib/celluloid/task.rb:45:in `block in initialize'
2012-04-09T11:01:02+00:00 app[worker.2]: 2012-04-09T11:01:02Z 1 TID-ue0i8 ERROR: Manager#processor_died died
2012-04-09T11:01:02+00:00 app[worker.2]: 2012-04-09T11:01:02Z 1 TID-ue0i8 ERROR: task was terminated
2012-04-09T11:01:02+00:00 app[worker.2]: 2012-04-09T11:01:02Z 1 TID-ue0i8 ERROR: /app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.10.0/lib/celluloid/task.rb:23:in `suspend'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.10.0/lib/celluloid/actor.rb:45:in `call'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.10.0/lib/celluloid/actor_proxy.rb:76:in `method_missing'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.10.0/lib/celluloid.rb:115:in `new_link'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/sidekiq-0.11.1/lib/sidekiq/manager.rb:95:in `block in processor_died'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/sidekiq-0.11.1/lib/sidekiq/util.rb:42:in `watchdog'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/sidekiq-0.11.1/lib/sidekiq/manager.rb:91:in `processor_died'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.10.0/lib/celluloid/actor.rb:225:in `handle_exit_event'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.10.0/lib/celluloid/actor.rb:146:in `block in run'
2012-04-09T11:01:02+00:00 app[worker.2]: /app/vendor/bundle/ruby/1.9.1/gems/celluloid-0.10.0/lib/celluloid/task.rb:45:in `block in initialize'
```

and my worker process status turn to `crashed`:

```
192-168-1-3:spree-thurley macbookair$ heroku ps
Process   State            Command                               
--------  ---------------  ------------------------------------  
web.1     up for 9m        bundle exec puma -p $PORT -C ./con..  
worker.1  crashed for 5m   bundle exec sidekiq                                     
worker.2  crashed for 34s  bundle exec sidekiq
```

and my web process complains about max number of clients reached:

```
2012-04-09T11:01:11+00:00 app[web.1]: 
2012-04-09T11:01:11+00:00 app[web.1]: 
2012-04-09T11:01:11+00:00 app[web.1]: Started GET "/sidekiq/queues/default" for 115.64.25.106 at 2012-04-09 11:01:11 +0000
2012-04-09T11:01:11+00:00 app[web.1]: RuntimeError - ERR max number of clients reached:
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:47:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:24:in `connect'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:247:in `ensure_connected'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:137:in `block in process'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:206:in `logging'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:136:in `process'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis/client.rb:46:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis.rb:308:in `block in lrange'
2012-04-09T11:01:11+00:00 app[web.1]:   /usr/local/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis.rb:307:in `lrange'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sidekiq-0.11.1/lib/sidekiq/web.rb:127:in `block (2 levels) in <class:Web>'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/connection_pool-0.9.1/lib/connection_pool.rb:47:in `with'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sidekiq-0.11.1/lib/sidekiq.rb:60:in `redis'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sidekiq-0.11.1/lib/sidekiq/web.rb:127:in `block in <class:Web>'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:1212:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:1212:in `block in compile!'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in `[]'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in `block (3 levels) in route!'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:801:in `route_eval'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in `block (2 levels) in route!'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:822:in `block in process_route'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:820:in `catch'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:820:in `process_route'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:784:in `block in route!'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:783:in `each'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:783:in `route!'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:886:in `dispatch!'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in `block in call!'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `block in invoke'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `catch'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `invoke'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in `call!'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:705:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sidekiq-0.11.1/lib/sidekiq/web.rb:26:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/nulllogger.rb:9:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/head.rb:9:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `block in call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:1416:in `synchronize'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/journey-1.0.3/lib/journey/router.rb:68:in `block in call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/journey-1.0.3/lib/journey/router.rb:56:in `each'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/journey-1.0.3/lib/journey/router.rb:56:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/routing/route_set.rb:594:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/warden-1.1.1/lib/warden/manager.rb:35:in `block in call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/warden-1.1.1/lib/warden/manager.rb:34:in `catch'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/warden-1.1.1/lib/warden/manager.rb:34:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/etag.rb:23:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/conditionalget.rb:25:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/middleware/head.rb:14:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/middleware/flash.rb:242:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in `context'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/middleware/cookies.rb:338:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.2/lib/active_record/query_cache.rb:64:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:443:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:405:in `_run__1803640746170885601__call__1928046963732201738__callbacks'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:405:in `__run_callback'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.2/lib/rails/rack/logger.rb:26:in `call_app'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.2/lib/rails/rack/logger.rb:16:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/middleware/request_id.rb:22:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/runtime.rb:17:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.2/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/lock.rb:15:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/middleware/static.rb:61:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:49:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.2/lib/rails/engine.rb:479:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.2/lib/rails/application.rb:220:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/commonlogger.rb:20:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/puma-1.1.1/lib/puma/server.rb:370:in `handle_request'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/puma-1.1.1/lib/puma/server.rb:243:in `process_client'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/puma-1.1.1/lib/puma/server.rb:157:in `block in run'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/puma-1.1.1/lib/puma/thread_pool.rb:92:in `call'
2012-04-09T11:01:11+00:00 app[web.1]:   /app/vendor/bundle/ruby/1.9.1/gems/puma-1.1.1/lib/puma/thread_pool.rb:92:in `block in spawn_thread'
2012-04-09T11:01:11+00:00 heroku[router]: GET smooth-leaf-8675.herokuapp.com/sidekiq/queues/default dyno=web.1 queue=0 wait=0ms service=65ms status=500 bytes=30
2012-04-09T11:01:11+00:00 app[web.1]: cache: [GET /sidekiq/queues/default] miss
2012-04-09T11:01:11+00:00 app[web.1]: 115.64.25.106 - - [09/Apr/2012 11:01:11] "GET /queues/default HTTP/1.1" 500 30 0.0585
2012-04-09T11:05:12+00:00 heroku[worker.1]: State changed from crashed to created
2012-04-09T11:05:12+00:00 heroku[worker.1]: State changed from created to starting
2012-04-09T11:05:23+00:00 heroku[worker.1]: Starting process with command `bundle exec sidekiq`
2012-04-09T11:05:24+00:00 heroku[worker.1]: State changed from starting to up
2012-04-09T11:05:34+00:00 app[worker.1]: DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/01/04/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /app/config/environment.rb:5)
2012-04-09T11:05:34+00:00 app[worker.1]: DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/01/04/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /app/config/environment.rb:5)
```

I am new to Sidekiq and Heroku so please let me know if I do something stupid here.

**Comment by benoittgt** [comment]
Hello

I've read few issues and wiki pages. I still don't get it. We had the error yesterday (`Redis::CommandError: ERR max number of clients reached`) using  Heroku Redis on Heroku with a **maximum connection of 80**.

What we have : 
`sidekiq.yml`
```
production:
  :concurrency: 10
```

`sidekiq.rb`
```
Sidekiq.configure_client do |config|
  config.redis = { size: 3 }
end
```

We have 5 dynos
+ `bundle exec puma -C config/puma.rb`
+ `worker bundle exec sidekiq -q default -q primary -q mailers -i ${DYNO:-1}`
+ `worker_primary bundle exec sidekiq -q primary -i ${DYNO:-1}`
+ `worker_stats bundle exec sidekiq -q aggregates_update -i ${DYNO:-1}`
+ `worker_visibility_and_notifications bundle exec sidekiq -q notifications -q visibility -i ${DYNO:-1}`

We use [Hirefire](https://www.hirefire.io/) to scale and yesterday it fails with 
+ Web at **4**
+ `worker` at **4**
+ `worker_primary` at **1**
+ `worker_stats` at **0**
+ `worker_visibility_and_notifications` at **1**

What is the way to calculate how to stay under 80 connections?

Thanks in advance

**Comment by benoittgt** [comment]
Heroku support told us to check also the timeout : 

> Redis' default behaviour is to never expire idle connections so you might want to [close connections properly](http://redis.io/commands/quit), or try [setting a timeout value](https://devcenter.heroku.com/articles/heroku-redis#configuring-your-instance) on your instance.

Don't know if it helps for me my issue. Any advices ?

**Comment by mperham** [comment]
Sidekiq 4 now takes up to concurrency + 5 connections.

Web = 4 * 3 = 12
Worker = 15 * (4 + 1 + 1) = 90

Sidekiq never closes connections.  It pools them so they can be reused when needed.  It only opens a connection if needed so a worker process will only use 15 connections if it is really busy.

**Comment by benoittgt** [comment]
Thanks a lot @mperham for the help. 

When you write `Web = 4 * 3 = 12` I also need to add the puma connections ?  On my `puma.rb` I have `MAX_THREADS = 20` and `WEB_CONCURRENCY = 2`

> A good formula for determining the number of connections each application will require is to multiply the MAX_THREADS by the WEB_CONCURRENCY. This will determine the number of connections each dyno will consume.[[1](https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#database-connections)]

So It means I have to add this **40** to my web count ? `Web = 4 * 3 + 40 = 52 ?

Sorry quite out of thread.

**Comment by mperham** [comment]
No, the 20 puma threads share the 3 client connections per process.  That's the point of a connection pool.

**Comment by benoittgt** [comment]
Great. Thanks @mperham

**Comment by adiakritos** [comment]
someone, please add this math to the docs on concurrency so it's easier to calculate the concurrencies required. 

    var web_connections   = (web_dynos * (client_conn * web_threads));
    var concurrency  = (max_connections - web_connections - (redis_reserved * worker_dynos)) / worker_dynos;
    var server_connections  = concurrency + redis_reserved;

[source](http://manuelvanrijn.nl/sidekiq-heroku-redis-calc/content/javascripts/app.js)

**Comment by benoittgt** [comment]
I added this info here https://github.com/mperham/sidekiq/wiki/FAQ#how-to-calcultate-the-number-or-redis-connection-used-by-sidekiq

Feel free to remove the link to the blog post if you think it should not be present on the wiki.

**Comment by adiakritos** [comment]
@mperham I would but I'm not entirely sure of what I'm talking about yet. 

Here's a possible draft to add into the wiki, otherwise feel free to leave it here for discussion.

Basically, this is my understanding of the whole setup and how to calculate concurrency in the simplest possible setup. 

------------------------

Use [this](http://manuelvanrijn.nl/sidekiq-heroku-redis-calc/) calculator to figure out how to tune concurrency for your specific configuration.

The different components to understand when setting up your config are the following:

1. The web process running your app's code
2. The Sidekiq process
3. The Redis storage

The first thing to get is that your web process is pushing things to the Redis storage, which is where your queue is physically located. 

Once that's clear, then it's easier to see that your Sidekiq process will also connect to Redis to pull things "off" the queue. 

So it's: 

[Web Process] ---> [REDIS] <---- [Sidekiq]

Ok, now lets assume that you're running one Dyno in Heroku for your web process with 5 threads. Each of those threads counts as a single connection to redis. So you'd have 1 *connection* per *thread* to the redis servier, just from the 1 Dyno / Web process. 

If you have 2 Dynos running your code, each process with 5 threads, now you have 10 threads, which is 10 connections to Redis. 

So, 

Web Process Connections To Redis = Web Dynos x Threads x Redis Connections (1)
Web Process Connections To Redis = 1 X 5 X 1 
Web Process Connections To Redis = 5

Boom. So now we're telling Redis, listen we're gonna need you to handle at least 5 connections total from me at any given time. 

Next, let's imagine the Redis service we're using only allows 20 total simultaneous connections. 

At this point we know we're using up 5 of that Redis plan's 20 total possible connections. So we only have 15 left to connect to Redis with. 

Ok, so now what about the Sidekiq process? 

Well, by default, the Sidekiq process will command 2 connections to Redis. That means that our Redis service with 20 total connections is giving 5 connections to Web Process, and 2 to Sidekiq process. That's 7 total connections used up on our 20 connection plan. So we have a remaining 13 available connections to Redis.

This means you can set your Sidekiq Concurrencies to 13 in this case. 

A formula for this situation is as follows: 

```
   max_connection  = 20 # this is our Redis plan's total allowed connections.
   web_dynos       = 1  # Running a single web dyno and web process for the app.
   web_threads     = 5  # I'm using puma with 5 threads so this is how many threads my Web process is using.
   client_conn     = 1  # The number of connections each web process thread makes to the Redis server.
   worker_dynos    = 1  # Processes running the sidekiq process.
   redis_reserved  = 2; # idk, just roll with it.

   web_connections     = (web_dynos * (client_conn * web_threads));
   concurrency         = (max_connections - web_connections - (redis_reserved * worker_dynos)) / worker_dynos;
```
