### ISSUE TITLE
Circular Dependency

### ISSUE THREAD

**Issue by PeteMichaud** [mperham/sidekiq#1281]
I'm upgrading an app from 3.2 to 4.0, and sidekiq won't run.

I have a model that uses concerns, and everything works fine in the application and on the console. 

When I try to run "bundle exec sidekiq -q reminder_queue -q scheduler_queue -q default"

It gives me this:

```
  Circular dependency detected while autoloading constant Contact::Avatarable
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:460:in `load_missing_constant'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:183:in `const_missing'
  /Users/pete/Projects/_Apps/contactio/app/models/contact.rb:3:in `<class:Contact>'
  /Users/pete/Projects/_Apps/contactio/app/models/contact.rb:1:in `<top (required)>'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:423:in `load'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:423:in `block in load_file'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:615:in `new_constants_in'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:422:in `load_file'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:323:in `require_or_load'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:462:in `load_missing_constant'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:183:in `const_missing'
  /Users/pete/Projects/_Apps/contactio/app/models/concerns/contact/avatarable.rb:1:in `<top (required)>'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:423:in `load'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:423:in `block in load_file'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:615:in `new_constants_in'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:422:in `load_file'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:323:in `require_or_load'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:288:in `depend_on'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:206:in `require_dependency'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/engine.rb:465:in `block (2 levels) in eager_load!'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/engine.rb:464:in `each'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/engine.rb:464:in `block in eager_load!'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/engine.rb:462:in `each'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/engine.rb:462:in `eager_load!'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/sidekiq-2.15.2/lib/sidekiq/cli.rb:199:in `boot_system'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/sidekiq-2.15.2/lib/sidekiq/cli.rb:42:in `parse'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/gems/sidekiq-2.15.2/bin/sidekiq:7:in `<top (required)>'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/bin/sidekiq:23:in `load'
  /Users/pete/.rvm/gems/ruby-2.0.0-p247/bin/sidekiq:23:in `<main>'
```

There's definitely no circular dependency, contact and avatarable are pretty basic. Not sure how to proceed.

**Comment by pratik60** [comment]
I initially changed this setting

    config/environments/development.rb

    config.eager_load = true

This didn't help though!

And I needed to add

    config/initializers/eager_load.rb:
    
    Rails.application.eager_load! unless Rails.env.test?

You also need to eager load the entire lib folder, if you are using one (autoload isn't enough).

    config/application.rb
    
    config.eager_load_paths += Dir["#{Rails.root}/lib/**/"]


Also, make sure that if devise is used in initializer it is renamed to 01_devise.rb or something, as initializers are loaded alphabetically, and your User or Admin, will reference it. 

Probably suggest that in tests eager_load is skipped as it is suboptimal, and if you are not using threads internally, skip it altogether!

**Comment by bf4** [comment]
@pratik60 that advice might be appropriate for Rails 3.x, but for modern Rails, it is sufficient to add to your `config/application.rb` something like

```ruby
    # http://blog.arkency.com/2014/11/dont-forget-about-eager-load-when-extending-autoload/
    # https://github.com/rails/rails/blob/4-2-stable/railties/lib/rails/engine/configuration.rb#L42-L51
    # Also:
    #    https://github.com/mperham/sidekiq/wiki/FAQ#why-doesnt-sidekiq-autoload-my-rails-application-code
    #    https://github.com/rails/rails/blob/4-2-stable/railties/lib/rails/engine.rb#L466-L475
    #    https://github.com/rails/rails/blob/4-2-stable/railties/lib/rails/paths.rb#L58-L61
    config.paths.add 'lib', load_path: true, eager_load: true
    config.paths.add 'app/workers', eager_load: true
    config.paths.add 'app/workers/concerns', eager_load: true
```

**Comment by mperham** [comment]
I would strongly urge people not to adjust their paths at all.  Stick with the Rails defaults and design your code to work with them.
