### ISSUE TITLE
NoMethodError: undefined method `new_attachment' for "Notifier":String

### ISSUE THREAD

**Issue by KensoDev** [mperham/sidekiq#152]
I have SideKiq enabled on a project, I am sending emails like so:

``` ruby
Notifier.delay.new_attachment(record.uploader, user, record)
```

The error I see is:
`NoMethodError: undefined method`new_attachment' for "Notifier":String`

This is the backtrace from Airbrake:

```
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/extensions/action_mailer.rb:15:in `perform'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/processor.rb:35:in `block (3 levels) in process'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/middleware/chain.rb:75:in `call'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/middleware/chain.rb:75:in `block in invoke'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/middleware/chain.rb:77:in `block in invoke'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/middleware/server/retry_jobs.rb:30:in `call'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/middleware/chain.rb:77:in `block in invoke'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/middleware/server/logging.rb:9:in `call'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/middleware/chain.rb:77:in `block in invoke'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/middleware/server/exception_handler.rb:9:in `call'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/middleware/chain.rb:77:in `block in invoke'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/middleware/chain.rb:80:in `call'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/middleware/chain.rb:80:in `invoke'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/processor.rb:34:in `block (2 levels) in process'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/processor.rb:64:in `stats'
[GEM_ROOT]/gems/sidekiq-1.1.3/lib/sidekiq/processor.rb:33:in `block in process'
[GEM_ROOT]/gems/celluloid-0.10.0/lib/celluloid/calls.rb:56:in `call'
[GEM_ROOT]/gems/celluloid-0.10.0/lib/celluloid/calls.rb:56:in `dispatch'
[GEM_ROOT]/gems/celluloid-0.10.0/lib/celluloid/future.rb:18:in `block in initialize'
[GEM_ROOT]/gems/celluloid-0.10.0/lib/celluloid/thread_pool.rb:46:in `call'
[GEM_ROOT]/gems/celluloid-0.10.0/lib/celluloid/thread_pool.rb:46:in `block in create'
```

From a quick look in the code, it seems that the `target` var is not being set with the class but with a string representation of the class somehow.

I am also looking into the issue, but thought I just might open up an issue, if you have any ideas.

**Comment by abrambailey** [comment]
Using `ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]` and `sidekiq 4.1.2` I am unable to call `Class.delay.method`
