### ISSUE TITLE
ASCII-8BIT to UTF-8 error inside sidekiq

### ISSUE THREAD

**Issue by ali-bugdayci** [mperham/sidekiq#1597]
Tried it with 2.15 and now updated to latest sidekiq if it changes anything.

I get the following error on sidekiq while internally processing the messages.

```
  "\xC3" from ASCII-8BIT to UTF-8
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/json-1.8.1/lib/json/common.rb:223:in `encode'

Possibly from:
  "757: unexpected token at 'INSERT INTO user \n(id,channel_id, presence_id,display_name) VALUES('60' , '-1', '1','Arcs Ond\xC3\xB6rt - 060014' ) '"
```

I already have utf-8 as the default language. I checked it in the rails console to see that the same string is different when to_json is used:

```
> echo $LANG
en_US.UTF-8
-------------------------
irb(main):017:0* "Arcs Ondört".encoding
=> #<Encoding:UTF-8>
irb(main):018:0> "Arcs Ondört".to_json
=> "\"Arcs Ond\\u00f6rt\""
```

The data I input is in the args section below:

```
  * data: {:message=>
    {"retry"=>true,
     "queue"=>"default",
     "failures"=>"all",
     "class"=>"BasKonusKullaniciContactWorker",
     "args"=>["sisteme_kullanici_ekleme", 60, "Arcs Ondört - 060014"],
     "jid"=>"bb7a4350da41278f2d2b3ee1",
     "enqueued_at"=>1395073168.1089876,
     "error_message"=>
      "757: unexpected token at 'INSERT INTO user \n(id,channel_id, presence_id,display_name) VALUES('60' , '-1', '1','Arcs Ond\xC3\xB6rt - 060014' ) '",
     "error_class"=>"JSON::ParserError",
     "failed_at"=>"2014-03-17T16:19:28Z",
     "retry_count"=>20,
     "retried_at"=>1395649704.8061812}}
```

---
## Backtrace:

```
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/json-1.8.1/lib/json/common.rb:223:in `encode'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/json-1.8.1/lib/json/common.rb:223:in `generate'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/json-1.8.1/lib/json/common.rb:223:in `generate'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq.rb:105:in `dump_json'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/retry_jobs.rb:97:in `rescue in call'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/logging.rb:22:in `with_context'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/logging.rb:7:in `call'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:127:in `call'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:127:in `invoke'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:108:in `stats'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:47:in `block in process'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `call'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/future.rb:14:in `block in new'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
  /home/biziz/sunucu/rails_sunucu/shared/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
```

```
rbenv versions
  system
  1.9.3-p429
  1.9.3-p484
* 1.9.3-p545
```

Any tips would be appriciated.

**Comment by GeminPatel** [comment]
**To reproduce:**
class A
def aa
@a = 194.chr
end
end

a = A.new
a.to_json() // will produce error.

______________________________________

class A
def aa
@a = 194.chr.force_encoding('UTF-8')
end
end

a = A.new
a.to_json() // will not produce error.
