### ISSUE TITLE
OpenSSL:SSL::SSLError

### ISSUE THREAD

**Issue by elaser** [mperham/sidekiq#1634]
Hi,
  I'm running Sidekiq 3.0 on heroku, and sidekiq works great, but every several hours, all the jobs fail and I see a message like

```
2014-04-04T18:55:23.765753+00:00 app[worker.1]: 2014-04-04T18:55:23Z 2 TID-oryehs3mg WARN: {"retry"=>true, "queue"=>"default", "unique"=>true, "class"=>"NotificationWorker", "args"=>[246, "0f3dd953f3f3986b6545eb38f24b5fd349425eaaf3b6373cf6371f04973fd97e"], "jid"=>"7855147642b146b79f3c7fdd", "enqueued_at"=>1396637669.1324072, "error_message"=>"SSL_write: bad write retry", "error_class"=>"OpenSSL::SSL::SSLError", "failed_at"=>1396637669.1603584, "retry_count"=>1, "retried_at"=>1396637723.7583897}
2014-04-04T18:55:23.766208+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/connection_pool-2.0.0/lib/connection_pool.rb:58:in `with'
2014-04-04T18:55:23.766208+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/processor.rb:50:in `block (2 levels) in process'
2014-04-04T18:55:23.766389+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2014-04-04T18:55:23.762110+00:00 app[worker.1]: /app/app/workers/notification_worker.rb:27:in `perform'
2014-04-04T18:55:23.766208+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
2014-04-04T18:55:23.766208+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.7.3.204/lib/new_relic/agent/instrumentation/sidekiq.rb:30:in `block in call'
2014-04-04T18:55:23.763013+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
2014-04-04T18:55:23.765931+00:00 app[worker.1]: 2014-04-04T18:55:23Z 2 TID-oryehs3mg WARN: SSL_write: bad write retry
2014-04-04T18:55:23.766208+00:00 app[worker.1]: 2014-04-04T18:55:23Z 2 TID-oryehs3mg WARN: /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/openssl/buffering.rb:319:in `syswrite'
2014-04-04T18:55:23.766389+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.7.3.204/lib/new_relic/agent/instrumentation/sidekiq.rb:21:in `call'
2014-04-04T18:55:23.766208+00:00 app[worker.1]: /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/openssl/buffering.rb:319:in `do_write'
2014-04-04T18:55:23.766389+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2014-04-04T18:55:23.766389+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/logging.rb:22:in `with_context'
2014-04-04T18:55:23.766389+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
2014-04-04T18:55:23.766553+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
2014-04-04T18:55:23.766553+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
2014-04-04T18:55:23.766553+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2014-04-04T18:55:23.766553+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/processor.rb:49:in `block in process'
2014-04-04T18:55:23.766553+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/processor.rb:92:in `stats'
2014-04-04T18:55:23.766389+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
2014-04-04T18:55:23.766389+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2014-04-04T18:55:23.766389+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
2014-04-04T18:55:23.766553+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/middleware/chain.rb:127:in `call'
2014-04-04T18:55:23.766553+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/middleware/chain.rb:127:in `invoke'
2014-04-04T18:55:23.766208+00:00 app[worker.1]: /app/app/workers/notification_worker.rb:43:in `block in perform'
2014-04-04T18:55:23.766208+00:00 app[worker.1]: /app/app/workers/notification_worker.rb:27:in `perform'
2014-04-04T18:55:23.766208+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/middleware/chain.rb:122:in `call'
2014-04-04T18:55:23.766389+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.7.3.204/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:335:in `perform_action_with_newrelic_trace'
2014-04-04T18:55:23.766389+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
2014-04-04T18:55:23.766553+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.0.0/lib/sidekiq/processor.rb:48:in `process'
2014-04-04T18:55:23.766553+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
2014-04-04T18:55:23.766553+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
2014-04-04T18:55:23.767110+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
2014-04-04T18:55:23.767110+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
2014-04-04T18:55:23.767110+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```

I've looked at #702 and tried the heroku-repo plugin and ran `repo:purge_cache` but I still see the same problem.

When I do heroku run bash and check the openssl version I see:

```
~ $ openssl version -a
OpenSSL 0.9.8k 25 Mar 2009
built on: Tue Jun  4 07:31:34 UTC 2013
platform: debian-amd64
options:  bn(64,64) md2(int) rc4(ptr,char) des(idx,cisc,16,int) blowfish(ptr2) 
compiler: cc -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -DTERMIO -O3 -Wa,--noexecstack -g -Wall -DMD32_REG_T=int -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM
OPENSSLDIR: "/usr/lib/ssl"
```

Is it possible that sidekiq is crashing because openssl should be 1.0.1?

My sidekiq.rb initializer file is:

``` ruby
Sidekiq.configure_server do |config|
    config.redis = {url: ENV["REDISCLOUD_URL"], namespace: 'sidekiq'}

    database_url = ENV['DATABASE_URL']
    if database_url
      ENV['DATABASE_URL'] = "#{database_url}?pool=25"
      ActiveRecord::Base.establish_connection
    end
end

Sidekiq.configure_client do |config|
  config.redis = {url: ENV["REDISCLOUD_URL"], namespace: 'sidekiq'}
end
```

and my NotificationWorker connection pool setup is:

``` ruby
APN_POOL = ConnectionPool.new(:size => 2, :timeout => 300) do
    uri, certificate = if Rails.env.development?
      [
        Houston::APPLE_DEVELOPMENT_GATEWAY_URI,
        File.read(ENV["APN_CERT"])
      ]
    else
      [
        Houston::APPLE_PRODUCTION_GATEWAY_URI,
        File.read(ENV["APN_CERT"])
      ]
    end

    connection = Houston::Connection.new(uri, certificate, "password")
    connection.open

    connection
  end
```

Thank you so much!
Anderthan

**Comment by bcackerman** [comment]
@elaser how did you solve it?

**Comment by mperham** [comment]
Folks, the way you fix it is by using the latest Ruby version on Heroku.
