### ISSUE TITLE
/sidekiq Redirects to RoutingError

### ISSUE THREAD

**Issue by natew** [mperham/sidekiq#167]
In my routes.rb:

```
require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
```

When attempting to reach /sidekiq I get a no route found error.  Using thin+rails3.2+ruby1.9.3.  I can see it actually is running the redirect, but then for some reason just not reaching the controller from there.

```
Started GET "/sidekiq" for 127.0.0.1 at 2012-04-29 01:52:03 -0700


Started GET "/sidekiq/" for 127.0.0.1 at 2012-04-29 01:52:03 -0700

ActionController::RoutingError (No route matches [GET] "/sidekiq"):
  actionpack (3.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.2) lib/rails/rack/logger.rb:26:in `call_app'
  railties (3.2.2) lib/rails/rack/logger.rb:16:in `call'
  quiet_assets (1.0.0) lib/quiet_assets.rb:20:in `call_with_quiet_assets'
  actionpack (3.2.2) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.2) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.1) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/static.rb:61:in `call'
  railties (3.2.2) lib/rails/engine.rb:479:in `call'
  railties (3.2.2) lib/rails/application.rb:220:in `call'
  rack (1.4.1) lib/rack/content_length.rb:14:in `call'
  railties (3.2.2) lib/rails/rack/log_tailer.rb:14:in `call'
  thin (1.2.11) lib/thin/connection.rb:84:in `block in pre_process'
  thin (1.2.11) lib/thin/connection.rb:82:in `catch'
  thin (1.2.11) lib/thin/connection.rb:82:in `pre_process'
  thin (1.2.11) lib/thin/connection.rb:57:in `process'
  thin (1.2.11) lib/thin/connection.rb:42:in `receive_data'
  eventmachine (0.12.10) lib/eventmachine.rb:256:in `run_machine'
  eventmachine (0.12.10) lib/eventmachine.rb:256:in `run'
  thin (1.2.11) lib/thin/backends/base.rb:61:in `start'
  thin (1.2.11) lib/thin/server.rb:159:in `start'
  rack (1.4.1) lib/rack/handler/thin.rb:13:in `run'
  rack (1.4.1) lib/rack/server.rb:265:in `start'
  railties (3.2.2) lib/rails/commands/server.rb:70:in `start'
  railties (3.2.2) lib/rails/commands.rb:55:in `block in <top (required)>'
  railties (3.2.2) lib/rails/commands.rb:50:in `tap'
  railties (3.2.2) lib/rails/commands.rb:50:in `<top (required)>'
  script/rails:6:in `require'
  script/rails:6:in `<main>'
```

**Comment by joshuairl** [comment]
For what it's worth...
I had in my gem file:
```
group :production do
  gem 'dalli'                   # memcached
  gem 'memcachier'              # heroku add-on for auto config of dalli
  gem 'unicorn'
  gem 'rails_12factor'          # https://devcenter.heroku.com/articles/rails4
end
```

I commented out `gem 'unicorn'` and it started working... but obviously not necessarily a "fix" per say but wanted to share this finding for now.

**Comment by kristenhazard** [comment]
```
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.superuser? } do
    mount Sidekiq::Web, at: '/sidekiq'
  end

```
This happened to me when my user didn't pass the authenticate code above: u.superuser?. This might help people understand what's happening for them even though I don't think it's the same issue.

**Comment by Pg-promisewindowless12** [comment]
> Yes, have them both. Still poking around, emptying application controller was no help.
> 
> Tried removing this from web.rb:
> 
> ```
> return [301, { 'Location' => "#{env['SCRIPT_NAME']}/" }, ['redirecting']] if env['SCRIPT_NAME'] == env['REQUEST_PATH']
> ```
> 
> Now it doesn't redirect, but still return the error from either url.





https://jqcode.space/questions/ruby-on-rails-automatically-redirecting-to-a-new-page
