### ISSUE TITLE
(ActiveRecord::StatementInvalid) "Errno::EBADF: Bad file descriptor

### ISSUE THREAD

**Issue by ghost** [mperham/sidekiq#1945]
Hi,

We are using exception_notification gem integrated with sidekiq, we get weird exception like this

```
An ActiveRecord::StatementInvalid occurred in background at 2014-09-11 15:07:26 UTC :

  Errno::EBADF: Bad file descriptor: SELECT  `sidekiq_jobs`.* FROM `sidekiq_jobs`  WHERE `sidekiq_jobs`.`thread_id` = 'f1b6822c' AND `sidekiq_jobs`.`kind` = 1 LIMIT 1
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'

  -------------------------------
Backtrace:
-------------------------------

  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/mysql2_adapter.rb:232:in `exec_query'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/mysql2_adapter.rb:240:in `select'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/querying.rb:39:in `find_by_sql'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/relation.rb:604:in `exec_queries'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/relation.rb:486:in `load'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/relation.rb:231:in `to_a'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/relation/finder_methods.rb:451:in `find_take'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/relation/finder_methods.rb:98:in `take'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/relation/finder_methods.rb:81:in `find_by'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/querying.rb:7:in `find_by'
  /opt/railsapp/releases/20140911105234/app/services/sidekiq_service.rb:25:in `working!'
  /opt/railsapp/releases/20140911105234/app/workers/email_service.rb:23:in `perform'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:122:in `call'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/exception_notification-4.0.1/lib/exception_notification/sidekiq.rb:8:in `call'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.7.3.204/lib/new_relic/agent/instrumentation/sidekiq.rb:30:in `block in call'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.7.3.204/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:335:in `perform_action_with_newrelic_trace'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.7.3.204/lib/new_relic/agent/instrumentation/sidekiq.rb:21:in `call'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/server/retry_jobs.rb:73:in `call'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/logging.rb:22:in `with_context'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/server/logging.rb:7:in `call'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:127:in `call'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/middleware/chain.rb:127:in `invoke'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/processor.rb:51:in `block in process'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/processor.rb:94:in `stats'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.2/lib/sidekiq/processor.rb:50:in `process'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```

sidekiq_service (line 25)

```
sidekiq_job = SidekiqJob.find_by(thread_id: thread_id, kind: kind)
```

Besides that exception, we also received 2 others errors on the same line (sidekiq_service: 25)

```
 undefined method `fields' for nil:NilClass
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/mysql2_adapter.rb:233:in `exec_query'
```

```
An ActiveRecord::StatementInvalid occurred in background at 2014-09-11 15:38:47 UTC :

  Mysql2::Error: Malformed packet: SELECT  `sidekiq_jobs`.* FROM `sidekiq_jobs`  WHERE `sidekiq_jobs`.`thread_id` = '11a4ab17' AND `sidekiq_jobs`.`kind` = 0 LIMIT 1
  /opt/railsapp/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
```

What's wrong with this? Activerecord related?

**Comment by dougfarre** [comment]
I'm having this issue with the pg gem.

**Comment by mperham** [comment]
My only advice is to ensure your Ruby VM and native gems are up to date ([see here](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#my-sidekiq-process-is-crashing-what-do-i-do)).  If you find any more information on a cause, please open a new issue.  I'm going to lock this issue so it doesn't fill up with further +1s.

**Comment by mperham** [comment]
Please see brianmario/mysql2#547 for current status of this bug.
