### ISSUE TITLE
Sidekiq Web: TypeError - can't convert String into an exact number

### ISSUE THREAD

**Issue by thibaudgg** [mperham/sidekiq#1949]
I got this issue when I try to access a specific retry job `/retries/1410861402.471819-48b24ff19fc4402baa79f87e`:

```
2014-09-16T08:49:45.496692+00:00 app[web.1]: App 99 stderr: TypeError - can't convert String into an exact number:
2014-09-16T08:49:45.496701+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/core_ext/time/calculations.rb:44:in `at'
2014-09-16T08:49:45.496703+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/core_ext/time/calculations.rb:44:in `at_with_coercion'
2014-09-16T08:49:45.496705+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.2.5/lib/sidekiq/api.rb:242:in `enqueued_at'
2014-09-16T08:49:45.496706+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.2.5/web/views/_job_info.erb:36:in `block in singleton class'
2014-09-16T08:49:45.496708+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.2.5/web/views/_job_info.erb:-6:in `instance_eval'
2014-09-16T08:49:45.496709+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.2.5/web/views/_job_info.erb:-6:in `singleton class'
2014-09-16T08:49:45.496710+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.2.5/web/views/_job_info.erb:-8:in `__tilt_70184343847440'
2014-09-16T08:49:45.496711+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
2014-09-16T08:49:45.496713+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
2014-09-16T08:49:45.496716+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
2014-09-16T08:49:45.496717+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:814:in `render'
2014-09-16T08:49:45.496718+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:665:in `erb'
2014-09-16T08:49:45.496720+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.2.5/web/views/retry.erb:1:in `block in singleton class'
2014-09-16T08:49:45.496722+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.2.5/web/views/retry.erb:-5:in `instance_eval'
2014-09-16T08:49:45.496723+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.2.5/web/views/retry.erb:-5:in `singleton class'
2014-09-16T08:49:45.496726+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.2.5/web/views/retry.erb:-7:in `__tilt_70184343847440'
2014-09-16T08:49:45.496727+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
2014-09-16T08:49:45.496729+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
2014-09-16T08:49:45.496731+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
2014-09-16T08:49:45.496733+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:814:in `render'
2014-09-16T08:49:45.496763+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:665:in `erb'
2014-09-16T08:49:45.496765+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.2.5/lib/sidekiq/web.rb:139:in `block in <class:Web>'
2014-09-16T08:49:45.496766+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
2014-09-16T08:49:45.496767+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
2014-09-16T08:49:45.496768+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
2014-09-16T08:49:45.496770+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
2014-09-16T08:49:45.496771+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
2014-09-16T08:49:45.496772+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
2014-09-16T08:49:45.496774+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
2014-09-16T08:49:45.496775+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
2014-09-16T08:49:45.496778+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
2014-09-16T08:49:45.496779+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
2014-09-16T08:49:45.496780+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
2014-09-16T08:49:45.496781+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
2014-09-16T08:49:45.496783+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
2014-09-16T08:49:45.496786+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
2014-09-16T08:49:45.496809+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
2014-09-16T08:49:45.496811+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
2014-09-16T08:49:45.496814+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
2014-09-16T08:49:45.496815+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
2014-09-16T08:49:45.496829+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
2014-09-16T08:49:45.496831+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
2014-09-16T08:49:45.496832+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
2014-09-16T08:49:45.496834+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems
2014-09-16T08:49:45.496835+00:00 app[web.1]: App 99 stderr: /sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
2014-09-16T08:49:45.496839+00:00 app[web.1]: App 99 stderr:     /app/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
```

**Comment by kapso** [comment]
@mperham I am seeing this too on 

- Rails 7.1.3.2
- Sidekiq v7.2.4 / Pro v7.2.0
- Ruby 3.3.1
- Redis 6.2.8

This happens when I try to click on a retry - eg: `sidekiq/retries/1714694009.406673-114bc6736276e28b7fcc90fd` on `sidekiq/retries`

```
4124baeaa770f3caac681" for 12.10.42.10 at 2024-05-02 23:19:26 +0000
2024-05-02T23:19:26.247920+00:00 app[web.1]: F, [2024-05-02T23:19:26.247823 #80] FATAL -- : [0d57b5c3-ec06-4369-95c5-61120e7991a8]
2024-05-02T23:19:26.247922+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] TypeError (can't convert String into an exact number):
2024-05-02T23:19:26.247923+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8]
2024-05-02T23:19:26.247924+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] <internal:timev>:286:in `at'
2024-05-02T23:19:26.247926+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] activesupport (7.1.3.2) lib/active_support/core_ext/time/calculations.rb:56:in `at_with_coercion'
2024-05-02T23:19:26.247926+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/api.rb:425:in `enqueued_at'
2024-05-02T23:19:26.247927+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/web/action.rb:103:in `_erb__job_info'
2024-05-02T23:19:26.247927+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/web/action.rb:94:in `_erb'
2024-05-02T23:19:26.247928+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/web/action.rb:60:in `erb'
2024-05-02T23:19:26.247928+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/web/action.rb:54:in `_erb_retry'
2024-05-02T23:19:26.247929+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/web/action.rb:94:in `_erb'
2024-05-02T23:19:26.247929+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/web/action.rb:63:in `erb'
2024-05-02T23:19:26.247929+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/web/application.rb:223:in `block in <class:WebApplication>'
2024-05-02T23:19:26.247930+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/web/application.rb:416:in `instance_exec'
2024-05-02T23:19:26.247930+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/web/application.rb:416:in `block in call'
2024-05-02T23:19:26.247930+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/web/application.rb:414:in `catch'
2024-05-02T23:19:26.247931+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/web/application.rb:414:in `call'
2024-05-02T23:19:26.247931+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/web/csrf_protection.rb:51:in `admit'
2024-05-02T23:19:26.247931+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/web/csrf_protection.rb:40:in `call'
2024-05-02T23:19:26.247931+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack (2.2.9) lib/rack/auth/basic.rb:28:in `call'
2024-05-02T23:19:26.247932+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack (2.2.9) lib/rack/static.rb:161:in `call'
2024-05-02T23:19:26.247932+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack (2.2.9) lib/rack/static.rb:161:in `call'
2024-05-02T23:19:26.247932+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack (2.2.9) lib/rack/builder.rb:244:in `call'
2024-05-02T23:19:26.247933+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/web.rb:117:in `call'
2024-05-02T23:19:26.247933+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sidekiq (7.2.4) lib/sidekiq/web.rb:122:in `call'
2024-05-02T23:19:26.247933+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/routing/mapper.rb:22:in `block in <class:Constraints>'
2024-05-02T23:19:26.247933+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/routing/mapper.rb:51:in `serve'
2024-05-02T23:19:26.247933+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:51:in `block in serve'
2024-05-02T23:19:26.247933+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
2024-05-02T23:19:26.247934+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:124:in `each'
2024-05-02T23:19:26.247934+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:124:in `find_routes'
2024-05-02T23:19:26.247934+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:32:in `serve'
2024-05-02T23:19:26.247934+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/routing/route_set.rb:882:in `call'
2024-05-02T23:19:26.247935+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] skylight (6.0.4) lib/skylight/probes/action_dispatch/routing/route_set.rb:10:in `block in call'
2024-05-02T23:19:26.247935+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] activesupport (7.1.3.2) lib/active_support/notifications.rb:206:in `block in instrument'
2024-05-02T23:19:26.247935+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] activesupport (7.1.3.2) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
2024-05-02T23:19:26.247935+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sentry-rails (5.17.3) lib/sentry/rails/tracing.rb:54:in `instrument'
2024-05-02T23:19:26.247935+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] activesupport (7.1.3.2) lib/active_support/notifications.rb:206:in `instrument'
2024-05-02T23:19:26.247935+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] skylight (6.0.4) lib/skylight/probes/action_dispatch/routing/route_set.rb:10:in `call'
2024-05-02T23:19:26.247945+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'
2024-05-02T23:19:26.247945+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
2024-05-02T23:19:26.247945+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] omniauth (2.1.2) lib/omniauth/builder.rb:44:in `call'
2024-05-02T23:19:26.247946+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack-attack (6.7.0) lib/rack/attack.rb:127:in `call'
2024-05-02T23:19:26.247946+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack-brotli (1.2.0) lib/rack/brotli/deflater.rb:34:in `call'
2024-05-02T23:19:26.247946+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack (2.2.9) lib/rack/deflater.rb:44:in `call'
2024-05-02T23:19:26.247946+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack (2.2.9) lib/rack/tempfile_reaper.rb:15:in `call'
2024-05-02T23:19:26.247947+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack (2.2.9) lib/rack/etag.rb:27:in `call'
2024-05-02T23:19:26.247947+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack (2.2.9) lib/rack/conditional_get.rb:27:in `call'
2024-05-02T23:19:26.247947+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack (2.2.9) lib/rack/head.rb:12:in `call'
2024-05-02T23:19:26.247948+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/http/permissions_policy.rb:36:in `call'
2024-05-02T23:19:26.247948+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/http/content_security_policy.rb:33:in `call'
2024-05-02T23:19:26.247948+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack (2.2.9) lib/rack/session/abstract/id.rb:266:in `context'
2024-05-02T23:19:26.247949+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack (2.2.9) lib/rack/session/abstract/id.rb:260:in `call'
2024-05-02T23:19:26.247950+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/middleware/cookies.rb:689:in `call'
2024-05-02T23:19:26.247951+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2024-05-02T23:19:26.247951+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] activesupport (7.1.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
2024-05-02T23:19:26.247951+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
2024-05-02T23:19:26.247951+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sentry-rails (5.17.3) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
2024-05-02T23:19:26.247951+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
2024-05-02T23:19:26.247952+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sentry-ruby (5.17.3) lib/sentry/rack/capture_exceptions.rb:29:in `block (2 levels) in call'
2024-05-02T23:19:26.247952+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sentry-ruby (5.17.3) lib/sentry/hub.rb:251:in `with_session_tracking'
2024-05-02T23:19:26.247952+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sentry-ruby (5.17.3) lib/sentry-ruby.rb:403:in `with_session_tracking'
2024-05-02T23:19:26.247952+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sentry-ruby (5.17.3) lib/sentry/rack/capture_exceptions.rb:20:in `block in call'
2024-05-02T23:19:26.247952+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sentry-ruby (5.17.3) lib/sentry/hub.rb:59:in `with_scope'
2024-05-02T23:19:26.247952+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sentry-ruby (5.17.3) lib/sentry-ruby.rb:383:in `with_scope'
2024-05-02T23:19:26.247953+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] sentry-ruby (5.17.3) lib/sentry/rack/capture_exceptions.rb:19:in `call'
2024-05-02T23:19:26.247953+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
2024-05-02T23:19:26.247953+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] railties (7.1.3.2) lib/rails/rack/logger.rb:37:in `call_app'
2024-05-02T23:19:26.247953+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] railties (7.1.3.2) lib/rails/rack/logger.rb:24:in `block in call'
2024-05-02T23:19:26.247953+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] activesupport (7.1.3.2) lib/active_support/tagged_logging.rb:135:in `block in tagged'
2024-05-02T23:19:26.247953+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] activesupport (7.1.3.2) lib/active_support/tagged_logging.rb:39:in `tagged'
2024-05-02T23:19:26.247953+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] activesupport (7.1.3.2) lib/active_support/tagged_logging.rb:135:in `tagged'
2024-05-02T23:19:26.247954+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] activesupport (7.1.3.2) lib/active_support/broadcast_logger.rb:240:in `method_missing'
2024-05-02T23:19:26.247954+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] railties (7.1.3.2) lib/rails/rack/logger.rb:24:in `call'
2024-05-02T23:19:26.247954+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
2024-05-02T23:19:26.247954+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] request_store (1.7.0) lib/request_store/middleware.rb:19:in `call'
2024-05-02T23:19:26.247958+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/middleware/request_id.rb:28:in `call'
2024-05-02T23:19:26.247958+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] skylight (6.0.4) lib/skylight/probes/action_dispatch/request_id.rb:8:in `call'
2024-05-02T23:19:26.247958+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack (2.2.9) lib/rack/method_override.rb:24:in `call'
2024-05-02T23:19:26.247958+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack (2.2.9) lib/rack/runtime.rb:22:in `call'
2024-05-02T23:19:26.247959+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] activesupport (7.1.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
2024-05-02T23:19:26.247959+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
2024-05-02T23:19:26.247959+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/middleware/static.rb:25:in `call'
2024-05-02T23:19:26.247959+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack (2.2.9) lib/rack/sendfile.rb:110:in `call'
2024-05-02T23:19:26.247959+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] actionpack (7.1.3.2) lib/action_dispatch/middleware/ssl.rb:79:in `call'
2024-05-02T23:19:26.247960+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] rack-heartbeat (1.1.0) lib/rack/heartbeat.rb:45:in `call'
2024-05-02T23:19:26.247960+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] railties (7.1.3.2) lib/rails/engine.rb:536:in `call'
2024-05-02T23:19:26.247960+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] puma (6.4.2) lib/puma/configuration.rb:272:in `call'
2024-05-02T23:19:26.247960+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
2024-05-02T23:19:26.247961+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
2024-05-02T23:19:26.247961+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
2024-05-02T23:19:26.247961+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] puma (6.4.2) lib/puma/server.rb:464:in `process_client'
2024-05-02T23:19:26.247961+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] puma (6.4.2) lib/puma/server.rb:245:in `block in run'
2024-05-02T23:19:26.247962+00:00 app[web.1]: [0d57b5c3-ec06-4369-95c5-61120e7991a8] puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

**Comment by mperham** [comment]
@kapso Do not resurrect old issues. Open your own new issue.
