### ISSUE TITLE
uninitialized constant RefreshCacheWorker

### ISSUE THREAD

**Issue by pkoltermann** [mperham/sidekiq#1958]
I'm working on some retro app. I've recently added a pernament caching for some objects, tht are being refreshed after editing. The refreshing operiation is being called by sidekiq task. In dev and staging env everythind is ok (no errors). On production en error is generated, but the data are being refreshed (sic). Workers are in `app/workers` and my config has included following paths:

```
config.autoload_paths += %W(#{config.root}/app/workers)
config.eager_load_paths += %W(#{config.root}/app/workers)
```

Have you got any idea where can be the issue?

Here is the error log:

```
2014-09-18T09:43:24Z 18773 TID-14bz2c ERROR: Sidekiq::Processor crashed!
NameError: uninitialized constant RefreshCacheWorker
shared/bundle/ruby/1.9.1/gems/activesupport-3.2.8/lib/active_support/inflector/methods.rb:230:in `block in constantize'
shared/bundle/ruby/1.9.1/gems/activesupport-3.2.8/lib/active_support/inflector/methods.rb:229:in `each'
shared/bundle/ruby/1.9.1/gems/activesupport-3.2.8/lib/active_support/inflector/methods.rb:229:in `constantize'
shared/bundle/ruby/1.9.1/gems/activesupport-3.2.8/lib/active_support/core_ext/string/inflections.rb:54:in `constantize'
shared/bundle/ruby/1.9.1/gems/sidekiq-2.12.1/lib/sidekiq/processor.rb:43:in `process'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `public_send'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `dispatch'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/calls.rb:125:in `dispatch'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/actor.rb:326:in `block in handle_message'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/tasks.rb:42:in `block in initialize'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/tasks/task_thread.rb:21:in `block in create'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/internal_pool.rb:59:in `call'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/internal_pool.rb:59:in `block in create'
2014-09-18T09:43:24Z 18773 TID-14bz2c WARN: {"retry"=>1, "queue"=>"default", "backtrace"=>true, "class"=>"RefreshCacheWorker", "args"=>[], "jid"=>"78c09560e4b8e83a555428e9", "enqueued_at"=>1411033404.9619699}
2014-09-18T09:43:24Z 18773 TID-14bz2c WARN: uninitialized constant RefreshCacheWorker
2014-09-18T09:43:24Z 18773 TID-14bz2c WARN: shared/bundle/ruby/1.9.1/gems/activesupport-3.2.8/lib/active_support/inflector/methods.rb:230:in `block in constantize'
shared/bundle/ruby/1.9.1/gems/activesupport-3.2.8/lib/active_support/inflector/methods.rb:229:in `each'
shared/bundle/ruby/1.9.1/gems/activesupport-3.2.8/lib/active_support/inflector/methods.rb:229:in `constantize'
shared/bundle/ruby/1.9.1/gems/activesupport-3.2.8/lib/active_support/core_ext/string/inflections.rb:54:in `constantize'
shared/bundle/ruby/1.9.1/gems/sidekiq-2.12.1/lib/sidekiq/processor.rb:43:in `process'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `public_send'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `dispatch'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/calls.rb:125:in `dispatch'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/actor.rb:326:in `block in handle_message'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/tasks.rb:42:in `block in initialize'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/tasks/task_thread.rb:21:in `block in create'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/internal_pool.rb:59:in `call'
shared/bundle/ruby/1.9.1/gems/celluloid-0.14.1/lib/celluloid/internal_pool.rb:59:in `block in create'

```

**Comment by bobzhen** [comment]
sometimes, just "kill" those processes, job done.
