### ISSUE TITLE
segfaults

### ISSUE THREAD

**Issue by whistlerbrk** [mperham/sidekiq#2118]
I've been battling this all day and have been eliminating gems as a method of pinning down the source. The stack trace here is a very bit confusing however. I'm posting because perhaps others are experiencing my issue as well and (again, perhaps) it's a genuine bug in sidekiq and not my code or my library code.

```
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rubyzip-1.1.6/lib/zip/inflater.rb:18: [BUG] Segmentation fault at 0x007fea54000078
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0038 p:---- s:0142 e:000166 CFUNC  :backtrace
c:0037 p:---- s:0148 e:000138 CFUNC  :current
c:0036 p:0019 s:0146 e:000145 BLOCK  /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:214
c:0035 p:0083 s:0144 e:000143 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:340
c:0034 p:0007 s:0140 e:000139 BLOCK  /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:204
c:0033 p:0020 s:0138 e:000137 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:286
c:0032 p:0009 s:0133 e:000132 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:203
c:0031 p:0011 s:0129 e:000128 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:109
c:0030 p:0085 s:0123 e:000122 BLOCK  /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis.rb:1421
c:0029 p:0009 s:0120 e:000119 BLOCK  /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis.rb:37
c:0028 p:0019 s:0108 2015-01-06T21:48:44.495Z 28575 TID-oxe2j4tz0 ImportFactset JID-0d9108f005b27ed84cece8f9 INFO: fail: 0.233 sec
e:000117 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/2.1.0/monitor.rb:213
c:0027 p:0009 s:0107 e:000106 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:203
c:0026 p:0050 s:0103 e:000102 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:174
c:0025 p:0015 s:0097 e:000095 BLOCK  /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:146
c:0024 p:0026 s:0093 e:000092 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:273
c:0023 p:0011 s:0088 e:000087 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:144
c:0022 p:0064 s:0084 e:000083 BLOCK  /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis.rb:2147
c:0021 p:0009 s:0079 e:000078 BLOCK  /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis.rb:37
c:0020 p:0014 s:0077 e:000076 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/2.1.0/monitor.rb:211
c:0019 p:0007 s:0074 e:000073 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis.rb:37
c:0018 p:0007 s:0071 e:000070 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis.rb:2139
c:0017 p:0030 s:0068 e:000067 BLOCK  /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:103
c:0016 p:0023 s:0063 e:000062 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.0/lib/connection_pool.rb:58
c:0015 p:0030 s:0058 e:000057 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq.rb:72
c:0014 p:0013 s:0054 E:0017c8 BLOCK  /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:101
c:0013 p:0017 s:0052 e:000051 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:138
c:0012 p:0020 s:0046 E:000ac0 RESCUE /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:100
c:0011 p:0017 s:0043 E:001490 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:123
c:0010 p:0107 s:0037 E:000648 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:50 [FINISH]
c:0009 p:---- s:0026 e:000025 CFUNC  :public_send
c:0008 p:0040 s:0021 e:000020 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26
c:0007 p:0031 s:0016 e:000015 METHOD /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122
c:0006 p:0011 s:0011 e:000010 BLOCK  /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60
c:0005 p:0041 s:0009 e:000008 BLOCK  /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71
c:0004 p:0026 s:0007 e:000006 BLOCK  /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357
c:0003 p:0073 s:0005 e:000004 BLOCK  /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57
c:0002 p:0060 s:0003 e:000002 BLOCK  /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15 [FINISH]
c:0001 p:---- s:0001 e:000000 ------

-- Ruby level backtrace information ----------------------------------------
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:50:in `process'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:98:in `stats'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:51:in `block in process'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/logging.rb:22:in `with_context'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `call'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:75:in `execute_job'
/home/deploy/capp/app/workers/import_factset.rb:18:in `perform'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/deploy/capp/app/workers/import_factset.rb:107:in `block in perform'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/upsert-2.0.3/lib/upsert.rb:72:in `batch'
/home/deploy/capp/app/workers/import_factset.rb:110:in `block (2 levels) in perform'
/home/deploy/capp/app/workers/import_factset.rb:110:in `foreach'
/home/deploy/capp/app/workers/import_factset.rb:138:in `block (3 levels) in perform'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/upsert-2.0.3/lib/upsert.rb:216:in `row'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/upsert-2.0.3/lib/upsert/merge_function.rb:13:in `execute'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/upsert-2.0.3/lib/upsert/merge_function/PG_Connection.rb:21:in `execute'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/upsert-2.0.3/lib/upsert/connection/PG_Connection.rb:10:in `execute'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/upsert-2.0.3/lib/upsert/connection/PG_Connection.rb:10:in `exec'

-- C level backtrace information -------------------------------------------
sidekiq 3.3.0 capp [18 of 25 busy](+02015-01-06T21:48:44.509Z 28575 TID-oxe2j4tz0 WARN: {"retry"=>true, "queue"=>"imports", {foo: 'app specific stuff here ommited'}, "jid"=>"0d9108f005b27ed84cece8f9", "enqueued_at"=>1420580670.3082597, "error_message"=>"lost synchronization with server: got message type \"\u0018\", length -893857616\n", "error_class"=>"PG::UnableToSend", "failed_at"=>1420580881.2774422, "retry_count"=>1, "retried_at"=>1420580924.4920886}
2015-01-06T21:48:44.509Z 28575 TID-oxe2j4tz0 WARN: lost synchronization with server: got message type "", length -893857616

2015-01-06T21:48:44.509Z 28575 TID-oxe2j4tz0 WARN: /home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/upsert-2.0.3/lib/upsert/connection/PG_Connection.rb:10:in `exec'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/upsert-2.0.3/lib/upsert/connection/PG_Connection.rb:10:in `execute'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/upsert-2.0.3/lib/upsert/merge_function/PG_Connection.rb:21:in `execute'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/upsert-2.0.3/lib/upsert/merge_function.rb:13:in `execute'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/upsert-2.0.3/lib/upsert.rb:216:in `row'
/home/deploy/capp/app/workers/import_factset.rb:138:in `block (3 levels) in perform'
/home/deploy/capp/app/workers/import_factset.rb:110:in `foreach'
/home/deploy/capp/app/workers/import_factset.rb:110:in `block (2 levels) in perform'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/upsert-2.0.3/lib/upsert.rb:72:in `batch'
/home/deploy/capp/app/workers/import_factset.rb:107:in `block in perform'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/deploy/capp/app/workers/import_factset.rb:18:in `perform'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:75:in `execute_job'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `call'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/logging.rb:22:in `with_context'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:51:in `block in process'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:98:in `stats'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:50:in `process'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/home/deploy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
x188dac) [0x7fead2fa9dac]
sidekiq 3.*** Error in `sidekiq 3.3.0 capp [18 of 25 busy]': malloc(): memory corruption: 0x00007feaa803ffc0 ***
```

**Comment by mperham** [comment]
Any update?

**Comment by whistlerbrk** [comment]
Yes, not sidekiq's fault
