### ISSUE TITLE
ERROR:

### ISSUE THREAD

**Issue by drexed** [mperham/sidekiq#2134]
Hey,

Ruby 2.2.0
Rails 4.2.0
Redis 3.2.0
Sidekiq 3.3.0

I get the following error when I boot up sidekiq:

```
2015-01-12T21:52:44.853Z 6967 TID-ovzdrvz0o INFO: Booting Sidekiq 3.3.0 with redis options {:url=>"redis://192.168.1.71:6379", :network_timeout=>3}
2015-01-12T21:52:45.712Z 6967 TID-ovzdrvz0o INFO: Running in ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
2015-01-12T21:52:45.712Z 6967 TID-ovzdrvz0o INFO: See LICENSE and the LGPL-3.0 for licensing details.
2015-01-12T21:52:45.712Z 6967 TID-ovzdrvz0o INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org/pro
2015-01-12T21:52:45.712Z 6967 TID-ovzdrvz0o INFO: Starting processing, hit Ctrl-C to stop
2015-01-12T21:52:45.773Z 6967 TID-ovzeormvw ERROR: heartbeat: undefined method `connect' for "ruby":String
2015-01-12T21:52:45.773Z 6967 TID-ovzerlb20 ERROR: Error fetching message: undefined method `connect' for "ruby":String
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:316:in `establish_connection'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:91:in `block in connect'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:273:in `with_reconnect'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:90:in `connect'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:256:in `with_socket_timeout'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:191:in `call_with_timeout'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis.rb:1059:in `block in _bpop'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis.rb:37:in `block in synchronize'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis.rb:37:in `synchronize'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis.rb:1056:in `_bpop'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis.rb:1101:in `brpop'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/fetch.rb:102:in `block in retrieve_work'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/connection_pool-2.1.0/lib/connection_pool.rb:58:in `with'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq.rb:72:in `redis'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/fetch.rb:102:in `retrieve_work'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/fetch.rb:37:in `block in fetch'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/util.rb:15:in `watchdog'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/fetch.rb:33:in `fetch'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
2015-01-12T21:52:45.774Z 6967 TID-ovzerlb20 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
2015-01-12T21:52:50.775Z 6967 TID-ovzeormvw ERROR: heartbeat: undefined method `connect' for "ruby":String
2015-01-12T21:52:55.777Z 6967 TID-ovzeormvw ERROR: heartbeat: undefined method `connect' for "ruby":String
2015-01-12T21:53:00.571Z 6967 TID-ovzerlee0 ERROR: undefined method `connect' for "ruby":String
2015-01-12T21:53:00.571Z 6967 TID-ovzerlee0 ERROR: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:316:in `establish_connection'
2015-01-12T21:53:00.572Z 6967 TID-ovzerlee0 WARN: {:context=>"scheduling poller thread died!"}
2015-01-12T21:53:00.572Z 6967 TID-ovzerlee0 WARN: undefined method `connect' for "ruby":String
2015-01-12T21:53:00.572Z 6967 TID-ovzerlee0 WARN: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:316:in `establish_connection'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:91:in `block in connect'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:273:in `with_reconnect'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:90:in `connect'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:337:in `ensure_connected'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:204:in `block in process'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:286:in `logging'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:203:in `process'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:109:in `call'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis.rb:1315:in `block in smembers'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis.rb:37:in `block in synchronize'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis.rb:37:in `synchronize'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis.rb:1314:in `smembers'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/api.rb:557:in `block in cleanup'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/connection_pool-2.1.0/lib/connection_pool.rb:58:in `with'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq.rb:72:in `redis'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/api.rb:556:in `cleanup'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/api.rb:549:in `initialize'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/scheduled.rb:79:in `new'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/scheduled.rb:79:in `poll_interval'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/scheduled.rb:58:in `block in poll'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/util.rb:15:in `watchdog'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/scheduled.rb:23:in `poll'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
2015-01-12T21:53:00.573Z 6967 TID-ovzeopha0 WARN: Sidekiq died due to the following error, cannot recover, process exiting
2015-01-12T21:53:00.573Z 6967 TID-ovzeopha0 WARN: undefined method `connect' for "ruby":String
2015-01-12T21:53:00.573Z 6967 TID-ovzeopha0 WARN: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:316:in `establish_connection'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:91:in `block in connect'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:273:in `with_reconnect'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:90:in `connect'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:337:in `ensure_connected'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:204:in `block in process'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:286:in `logging'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:203:in `process'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:109:in `call'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis.rb:1315:in `block in smembers'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis.rb:37:in `block in synchronize'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis.rb:37:in `synchronize'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.0/lib/redis.rb:1314:in `smembers'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/api.rb:557:in `block in cleanup'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/connection_pool-2.1.0/lib/connection_pool.rb:58:in `with'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq.rb:72:in `redis'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/api.rb:556:in `cleanup'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/api.rb:549:in `initialize'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/scheduled.rb:79:in `new'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/scheduled.rb:79:in `poll_interval'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/scheduled.rb:58:in `block in poll'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/util.rb:15:in `watchdog'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/scheduled.rb:23:in `poll'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
2015-01-12T21:53:00.578Z 6967 TID-ovzeormvw WARN: {:context=>"Manager#processor_died died"}
2015-01-12T21:53:00.578Z 6967 TID-ovzeormvw WARN: task was terminated
2015-01-12T21:53:00.578Z 6967 TID-ovzeormvw WARN: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:34:in `terminate'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:164:in `run'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
2015-01-12T21:53:00.579Z 6967 TID-ovzeormvw WARN: {:context=>"Manager#processor_died died"}
2015-01-12T21:53:00.579Z 6967 TID-ovzeormvw WARN: task was terminated
2015-01-12T21:53:00.579Z 6967 TID-ovzeormvw WARN: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:34:in `terminate'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:164:in `run'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
2015-01-12T21:53:00.579Z 6967 TID-ovzeormvw WARN: {:context=>"Manager#processor_died died"}
2015-01-12T21:53:00.579Z 6967 TID-ovzeormvw WARN: task was terminated
2015-01-12T21:53:00.579Z 6967 TID-ovzeormvw WARN: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:34:in `terminate'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:164:in `run'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
2015-01-12T21:53:00.579Z 6967 TID-ovzeormvw WARN: {:context=>"Manager#processor_died died"}
2015-01-12T21:53:00.579Z 6967 TID-ovzeormvw WARN: task was terminated
2015-01-12T21:53:00.579Z 6967 TID-ovzeormvw WARN: /Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:34:in `terminate'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:164:in `run'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
/Users/juangomez/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
```

Any thought on whats going on and how I can resolve this issue?

**Comment by mperham** [comment]
You're configuring the Redis connection wrong.
