### ISSUE TITLE
if it is feasible to substitute "multi" with "pipelined" while sending heartbeat pack

### ISSUE THREAD

**Issue by lujiajing1126** [mperham/sidekiq#2179]
I use twemproxy in our servers
but twemproxy does not support transaction feature at all
so when sending heartbeat, it will receive RST flag
I wonder if it is feasible to substitute "MULTI" with "PIPELINED" so that make it work in such env
```ruby
irb(main):001:0> require 'redis'
=> true
irb(main):002:0> Redis
=> Redis
irb(main):003:0> conn = Redis.new :url => 'redis://192.168.1.6:90/0'
=> #<Redis client v3.2.0 for redis://192.168.1.6:90/0>
irb(main):004:0> conn.multi do
irb(main):005:1* conn.add('process',"hahha")
irb(main):006:1> conn.hmset('hahaha','info','aaa','bbb')
irb(main):007:1> conn.expire('hahaha',60)
irb(main):008:1> conn.rpop('hahaha-signals')
irb(main):009:1> end
Redis::ConnectionError: Connection lost (ECONNRESET)
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:240:in `rescue in io'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:233:in `io'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:244:in `read'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:175:in `block in call_pipelined'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:214:in `block (2 levels) in process'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:340:in `ensure_connected'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:204:in `block in process'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:286:in `logging'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:203:in `process'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:174:in `call_pipelined'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:146:in `block in call_pipeline'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:273:in `with_reconnect'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis/client.rb:144:in `call_pipeline'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis.rb:2147:in `block in multi'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis.rb:37:in `block in synchronize'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis.rb:37:in `synchronize'
	from /home/megrez/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-3.2.0/lib/redis.rb:2139:in `multi'
	from (irb):4
	from /home/megrez/.rbenv/versions/2.1.0/bin/irb:11:in 
```

but with pipelined
```ruby
irb(main):001:0> require 'redis'
=> true
irb(main):002:0> redis = Redis.new :url => "redis://192.168.1.6:90/0"
=> #<Redis client v3.2.0 for redis://192.168.1.6:90/0>
irb(main):003:0> redis.pipelined do
irb(main):004:1* redis.sadd("processes",'hahaha')
irb(main):005:1> redis.hmset('hahaha','info','eee')
irb(main):006:1> redis.expire('hahaha',60)
irb(main):007:1> redis.rpop('hahaha-signals')
irb(main):008:1> end
=> [true, "OK", true, nil]
```

**Comment by mperham** [comment]
Sidekiq requires MULTI support.  That command is used in a number of places and I don't think it is feasible to remove it everywhere.

Any idea why twemproxy doesn't support MULTI?

**Comment by lujiajing1126** [comment]
Multi is a primitive of atomic transaction
If the transaction contains actions concerning different KEYS, it may cause the situation of distributed transaction
some thing like 2PC or 3PC may have to be used in such situations...

Or they are a little bit lazy simply
