### ISSUE TITLE
deprecation warnings with namespaces

### ISSUE THREAD

**Issue by stakach** [mperham/sidekiq#2226]
Using Sidekiq Pro + Namespace

```
2015-03-10T14:13:27.990Z 880 TID-9dtyc INFO: Booting Sidekiq 3.3.2 with redis options {:url=>"redis://10.71.1.248:6379/12", :namespace=>"quaypay"}
Signal USR1 not supported
Signal USR2 not supported
Signal TTIN not supported
2015-03-10T14:13:29.756Z 880 TID-9dtyc INFO: Running in ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]
2015-03-10T14:13:29.756Z 880 TID-9dtyc INFO: Sidekiq Pro 2.0.0, commercially licensed.  Thanks for your support!
2015-03-10T14:13:29.756Z 880 TID-9dtyc INFO: Starting processing, hit Ctrl-C tostop
2015-03-10T14:13:29.772Z 880 TID-15kwoo INFO: ReliableFetch activated
Passing 'disconnect!' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at C:/Ruby21/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.2/lib/connection_pool/timed_stack.rb:133:in `block indiscard!')
Passing 'disconnect!' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at C:/Ruby21/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.2/lib/connection_pool/timed_stack.rb:133:in `block indiscard!')
Passing 'disconnect!' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at C:/Ruby21/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.2/lib/connection_pool/timed_stack.rb:133:in `block indiscard!')
Passing 'disconnect!' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at C:/Ruby21/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.2/lib/connection_pool/timed_stack.rb:133:in `block indiscard!')
...
...
```

**Comment by mperham** [comment]
https://github.com/resque/redis-namespace/issues/98
