### ISSUE TITLE
Batches failing with Sidekiq::Batch::NoSuchBatch

### ISSUE THREAD

**Issue by webandtech** [mperham/sidekiq#2283]
I just refactored several long running workers to use batches, and intermittently I am seeing some batches fail to complete, with 0, 1, or 2 pending jobs showing in the UI.

No jobs from the batches are seen in the dead queue or retry queue and all of them are configured to retry at least 3 times.

In my logs I see  Sidekiq::Batch::NoSuchBatch: Couldn't find Batch 0GNIyWTb96hyIg along with a failed batch callback job in the retry queue.

I am running Sidekiq Pro on Heroku with Redis Cloud.

Any ideas?

```
Stacktrace (most recent call first):

  sidekiq/batch/status.rb:46:in `load_data'
    raise NoSuchBatch, "Couldn't find Batch #{bid} in redis" if @props.empty?
  sidekiq/batch/status.rb:20:in `initialize'
    load_data(bid)
  sidekiq/batch/callback.rb:11:in `new'
    status = Status.new(bid)
  sidekiq/batch/callback.rb:11:in `perform'
    status = Status.new(bid)
  sidekiq/processor.rb:75:in `execute_job'
    worker.perform(*cloned_args)
  sidekiq/processor.rb:52:in `block (2 levels) in process'
    execute_job(worker, cloned(msg['args']))
  sidekiq/middleware/chain.rb:127:in `block in invoke'
    yield
  sidekiq/pro/expiry.rb:29:in `call'
    yield
  sidekiq/middleware/chain.rb:129:in `block in invoke'
    chain.shift.call(*args, &traverse_chain)
  new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
    yield
  new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
    yield
  new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
    perform_action_with_newrelic_trace(trace_args) do
  sidekiq/middleware/chain.rb:129:in `block in invoke'
    chain.shift.call(*args, &traverse_chain)
  sidekiq_unique_jobs/middleware/server/unique_jobs.rb:17:in `call'
    yield
  sidekiq/middleware/chain.rb:129:in `block in invoke'
    chain.shift.call(*args, &traverse_chain)
  sidekiq/batch/middleware.rb:22:in `call'
    yield
  sidekiq/middleware/chain.rb:129:in `block in invoke'
    chain.shift.call(*args, &traverse_chain)
  sidekiq/middleware/server/active_record.rb:6:in `call'
    yield
  sidekiq/middleware/chain.rb:129:in `block in invoke'
    chain.shift.call(*args, &traverse_chain)
  sidekiq/middleware/server/retry_jobs.rb:74:in `call'
    yield
  sidekiq/middleware/chain.rb:129:in `block in invoke'
    chain.shift.call(*args, &traverse_chain)
  sidekiq/middleware/server/logging.rb:11:in `block in call'
    yield
  sidekiq/logging.rb:24:in `with_context'
    yield
  sidekiq/middleware/server/logging.rb:7:in `call'
    Sidekiq::Logging.with_context("#{worker.class.to_s} JID-#{item['jid']}#{" BID-#{item['bid']}" if item['bid']}") do
  sidekiq/middleware/chain.rb:129:in `block in invoke'
    chain.shift.call(*args, &traverse_chain)
  sidekiq/middleware/chain.rb:132:in `call'
    traverse_chain.call
  sidekiq/middleware/chain.rb:132:in `invoke'
    traverse_chain.call
  sidekiq/processor.rb:51:in `block in process'
    Sidekiq.server_middleware.invoke(worker, msg, queue) do
  sidekiq/processor.rb:98:in `stats'
    yield
  sidekiq/processor.rb:50:in `process'
    stats(worker, msg, queue) do
  celluloid/calls.rb:26:in `public_send'
    obj.public_send(@method, *@arguments, &_block)
  celluloid/calls.rb:26:in `dispatch'
    obj.public_send(@method, *@arguments, &_block)
  celluloid/calls.rb:122:in `dispatch'
    super(obj)
  celluloid/cell.rb:60:in `block in invoke'
    call.dispatch(@subject)
  celluloid/cell.rb:71:in `block in task'
    yield
  celluloid/actor.rb:357:in `block in task'
    yield
  celluloid/tasks.rb:57:in `block in initialize'
    yield
  celluloid/tasks/task_fiber.rb:15:in `block in create'
    yield
```

**Comment by mperham** [comment]
Ugh, sorry to hear that.  This type of problem is nearly impossible to diagnose without much more info.  It looks like you're on Pro 2.x and no one else has reported similar problems so far.  Can you share your worker code, especially any code that interacts with any Sidekiq APIs?

**Comment by webandtech** [comment]
I do have a sidekiq-unique-jobs middleware installed as well as sidekiq/pro/expiry, reliable push, and reliable fetch activated.

The unique jobs middleware is disabled for the workers in question.

This is the code in the worker that creates the batch. It is essentially splitting up some input data array of hashes into multiple jobs over a date range.

The data for each job is just passed in as an argument. I assume that should be fine... it is not going to be huge. Should I serialize/deserialize it in my workers instead of relying on sidekiq to do it? Just grasping at straws here.

```
batch = Sidekiq::Batch.new
      batch.description = "Import #{import_id}"
      batch.on(:success, BatchCallbackHandler, type: 'Import', id: import_id)
      batch.jobs do
        marker = import.start_at
        while marker <= import.end_at
          start_of_day = marker.beginning_of_day
          end_of_day = marker.end_of_day
          data_in_range = data.select{|a| a['start_at'] >= start_of_day && a['start_at'] <= end_of_day}
          ImportWorker.perform_async(start_of_day.to_s, end_of_day.to_s, data_in_range)
          marker += 1.day
        end
      end
```

**Comment by mperham** [comment]
Your worker code looks fine / typical.  Client-side unique middleware can lead to bad batches so I'd be very careful in using that plugin with any batch jobs.  No other custom middleware?

**Comment by webandtech** [comment]
Nope.

**Comment by webandtech** [comment]
I also just noticed this on my staging environment.

![screen shot 2015-04-02 at 2 02 06 pm](https://cloud.githubusercontent.com/assets/760867/6973641/01144784-d941-11e4-8ca9-9bb339f5cec6.png)

**Comment by mperham** [comment]
What did you do 45 years ago?  :-)  I can't imagine how the batch data can get corrupted like that.  I've seen one other person report negative pending counts.

Do you see poor Redis connection performance regularly?  High latency?  Timeouts?  That's the only thing that I can think which might cause this type of behavior.

**Comment by seuros** [comment]
We found the time machine. :smile_cat: 

I'm not sure but i suspect some custom date formatting override.

**Comment by webandtech** [comment]
I'm hosing the unique jobs middleware just in case... will report back if I keep seeing this. I have not seen any redis issues lately.

**Comment by webandtech** [comment]
I haven't seen this come back after removing sidekiq-unique-jobs... weird... closing for now!

**Comment by pixelate** [comment]
I've had the same problem since upgrading to Pro 2.0. Some batches show up as "45 years ago" and fail to run the complete callback.

**Comment by natehershey** [comment]
I'm also seeing batches from 45 years ago, using Sidekiq Pro 2.0.0, and failures with Sidekiq::Batch::NoSuchBatch: Couldn't find Batch.  We have unique: true set for for some of our workers but not for the jobs that are failing.

**Comment by mperham** [comment]
I suspect that the unique jobs middleware is interfering with the batch code.

**Comment by pixelate** [comment]
I'm not using the unique jobs middleware in my project, so the "45 years ago" bug is likely coming from somewhere else.

**Comment by mperham** [comment]
Any other 3rd party plugins?

**Comment by jonhyman** [comment]
Also, can you pull the batch up from a `rails console` and paste what its contents are to see what's in Redis? You can access it with `Sidekiq.redis {|r| r.get("b-#{bid}")}

**Comment by pixelate** [comment]
No, I don't use any 3rd party plugins.

```
> Sidekiq.redis {|r| r.get("b-rNyiLjJ4UKaBtQ")}
Redis::CommandError: WRONGTYPE Operation against a key holding the wrong kind of value
```

**Comment by mperham** [comment]
`Sidekiq::Batch::Status.new("b-rNyiLjJ4UKaBtQ").data`

**Comment by pixelate** [comment]
```
> Sidekiq::Batch::Status.new("b-rNyiLjJ4UKaBtQ").data
Sidekiq::Batch::NoSuchBatch: Couldn't find Batch b-rNyiLjJ4UKaBtQ in redis
```

**Comment by jonhyman** [comment]
Ah right, they're hashes now. You could use `hgetall`. Remove the `b-` in the `Status.new`

**Comment by pixelate** [comment]
```
> Sidekiq::Batch::Status.new("rNyiLjJ4UKaBtQ").data
=> {:is_complete=>false, :bid=>"rNyiLjJ4UKaBtQ", :total=>0, :pending=>-1864, :description=>nil, :failures=>0, :created_at=>0.0, :fail_info=>[]}
```

**Comment by mperham** [comment]
That's really bizarre.  I have no idea how a batch could get into that state unless it was deleted while jobs were still pending (maybe in the retry queue?)  Do you ever manually delete batches or reschedule jobs?  Any homemade middleware?

**Comment by pixelate** [comment]
This is the class that creates the batches:

```
require 'stathat'

class FeedsManagerWorker
  include Sidekiq::Worker
  sidekiq_options queue: "feeds_manager"
  sidekiq_options retry: false
  
  def perform    
    stats = Sidekiq::Stats.new
    exisiting_feed_jobs = stats.queues["feeds"]

    if exisiting_feed_jobs == 0 || exisiting_feed_jobs.nil?
      batch = Sidekiq::Batch.new
      batch.on(:complete, BatchCallbacks, batch_id: batch.bid)
      batch.description = "Parsing RSS feeds"
      batch.jobs do
        job_args = Feed.pluck(:id).map { |feed_id|
          [nil, feed_id, false]
        }

        Sidekiq::Client.push_bulk({'class' => FeedsWorker, 'args' => job_args})        
      end
    end
  end      
end
```

The callback posts stats about the duration of each batch to a 3rd party service:

```
class BatchCallbacks
  def on_complete(status, options)
    duration = ((Time.now - status.created_at)/60).round(2)
    StatHat::API.ez_post_value("batch duration", "credentials", duration)
  end
end
```

The FeedsManagerWorker is invoked from a rake task:

```
task :parse_feeds => :environment do
  (1..10).each do |num|
    FeedsManagerWorker.perform_in(num.minutes)
  end  
end
```

**Comment by mperham** [comment]
Can you show us FeedsWorker?

**Comment by pixelate** [comment]
Sure.

```
class FeedsWorker
  
  include Sidekiq::Worker
  sidekiq_options queue: "feeds", retry: false, backtrace: true
  
  def perform(product_id, feed_id, force)
    f = Feed.find_by_id(feed_id)

    if f     
      feed = Feedjira::Feed.fetch_and_parse(f.url, {
        :on_success => lambda {|url, feed| 

          if force == false && feed.last_modified == f.last_modified
            return
          end
      
          if product_id.nil?
            selected_products = Product.pluck_all(Product.where(auto_detect_enabled: true), :id, :excluding_terms, :including_terms)            
          else
            selected_products = Product.pluck_all(Product.where(id: product_id), :id, :excluding_terms, :including_terms) 
          end                    
          
          feed.entries.each do |entry|
            if entry.title
              entry.sanitize!
                        
              if f.archive
                post = Post.new(
                  :author => entry.author,
                  :content => entry.content,
                  :published => entry.published,
                  :summary => entry.summary,
                  :title => entry.title,
                  :url => entry.url,
                  :feed_id => f.id
                )
                post.save
              end
                        
              downcased_title = entry.title.downcase
                    
              selected_products.each do |product_attributes|
                if Product::search_terms_match?(product_attributes['excluding_terms'], product_attributes['including_terms'], downcased_title)
                  product = Product.find(product_attributes['id'])
                  Review::create_review_from_entry(product, entry, f.site)
                end
              end
            end
          end  
                
        },
        :on_failure => lambda {|curl, error|
          puts "#{error}: #{curl.url.sub('http://', '')} (Could not parse)"
        },
        :timeout => 30}
      )  
      f.update_attribute(:last_modified, feed.last_modified) if feed.respond_to?(:last_modified)    
    end    
  end  
    
end
```

**Comment by mperham** [comment]
`retry: false` is dangerous to use with batched jobs.  If the job throws an error, the batch will consider the job still pending but the retry handler will simply discard the job.  If you don't really care about success/failure, you should rescue all exceptions and return cleanly from the `perform` method so the job is considered a success and any batch callbacks will fire.

**Comment by pixelate** [comment]
Ok, I wasn't aware of that. Thanks for pointing that out.

**Comment by pixelate** [comment]
I made sure now to rescue all exceptions in FeedsWorker and flushed my redis database, but the "45 years ago" batches keep showing up. Anything else I can do to debug this?

**Comment by mperham** [comment]
Is it possible you are mixing old 1.x Batches and new 2.x Batches?  Maybe you have an older Sidekiq Pro 1.x process still running?

**Comment by mperham** [comment]
BTW, "45 years ago" means that the batch's created_at attribute is "0", which is 1970.

**Comment by pixelate** [comment]
@mperham No, that should not be the case. In my case, Sidekiq runs on a single Heroku Dyno that has been restarted after I flushed the Redis database.

**Comment by pixelate** [comment]
Below are the logs at the time when a batch with the "0" created_at attribute is created.
The app uses Redis To Go and should have enough memory and number of connections.

```
[]: EXECABORT Transaction discarded because of previous errors. 
app/sidekiq.1:  []: /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/pipeline.rb:79:in `finish' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:149:in `block in call_pipeline' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:147:in `call_pipeline' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis.rb:2182:in `block in multi' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize' 
app/sidekiq.1:  /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis.rb:2174:in `multi' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-pro-2.0.3/lib/sidekiq/batch/middleware.rb:120:in `block in add_failure' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.4/lib/sidekiq.rb:79:in `redis' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-pro-2.0.3/lib/sidekiq/batch/middleware.rb:119:in `add_failure' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-pro-2.0.3/lib/sidekiq/batch/middleware.rb:25:in `rescue in call' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-pro-2.0.3/lib/sidekiq/batch/middleware.rb:21:in `call' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/active_record.rb:6:in `call' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/logging.rb:15:in `block in call' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.4/lib/sidekiq/logging.rb:24:in `with_context' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/logging.rb:11:in `call' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:132:in `call' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:132:in `invoke' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:51:in `block in process' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:98:in `stats' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:50:in `process' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize' 
app/sidekiq.1:  /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create' 
```

**Comment by mperham** [comment]
Can you tell me your RedisToGo plan and show me the output of INFO?  EXECABORT is what you'd see if you were out of memory.  I don't know of any other reason you'd see this error.

**Comment by pixelate** [comment]
After I upgraded to Pro 2.0, I did downgrade to the Micro plan because of the memory savings. Usage on the Micro plan was generally around 10% on Pro 2.0 according to the Redis To Go dashboard. Of course it could go over the limit when it creates a batch (especially using push_bulk?), which I just realized now.

I upgraded to Mini to see if that helps, here's the INFO from that:

```
# Server
redis_version:2.8.21
redis_git_sha1:7f8b865a
redis_git_dirty:0
redis_build_id:2a94bd3a6ccd43dc
redis_mode:standalone
os:Linux 2.6.32-318-ec2 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.4.3
process_id:5733
run_id:de34b3c0ed3ad67e391cb53b1ac025a347596249
tcp_port:9713
uptime_in_seconds:329444
uptime_in_days:3
hz:10
lru_clock:7823214
config_file:/home/redis/9713/rtg.conf

# Clients
connected_clients:26
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:1

# Memory
used_memory:1741984
used_memory_human:1.66M
used_memory_rss:3342336
used_memory_peak:15100232
used_memory_peak_human:14.40M
used_memory_lua:36864
mem_fragmentation_ratio:1.92
mem_allocator:jemalloc-3.6.0

# Persistence
loading:0
rdb_changes_since_last_save:9662
rdb_bgsave_in_progress:0
rdb_last_save_time:1433886532
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:0
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_current_size:50131057
aof_base_size:196105
aof_pending_rewrite:0
aof_buffer_length:0
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:7694
total_commands_processed:146812938
instantaneous_ops_per_sec:0
total_net_input_bytes:10739483428
total_net_output_bytes:2710146812
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:14
evicted_keys:1029
keyspace_hits:20493507
keyspace_misses:25170313
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:765

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:1538.81
used_cpu_user:998.86
used_cpu_sys_children:0.20
used_cpu_user_children:1.09

# Keyspace
db0:keys=19,expires=11,avg_ttl=36000948010
```

**Comment by mperham** [comment]
Hmmm, your `used_memory_peak_human` shows 14MB, over the Micro limit of 10MB.

**Comment by pixelate** [comment]
Yes, that must the problem. I didn't think about the spike in memory when a new batch is created. My mistake. Thanks a lot for your quick support and troubleshooting help!
