### ISSUE TITLE
Error: undefined class/module ActiveRecord::Attribute::

### ISSUE THREAD

**Issue by miksago** [mperham/sidekiq#2298]
From twitter. I have a stacktrace captured in Sentry; I've also posted the package versions I'm using. I haven't posted the "additional data" from Sentry, as it includes some stuff I can't release publicly — via private email I can disclose it.

### Stacktrace (most recent call first):

```
  psych/class_loader.rb:53:in `path2class'
    path2class(name)
  psych/class_loader.rb:53:in `resolve'
    path2class(name)
  psych/class_loader.rb:45:in `find'
    @cache[klassname] ||= resolve(klassname)
  psych/class_loader.rb:27:in `load'
    find klassname
  psych/visitors/to_ruby.rb:379:in `resolve_class'
    class_loader.load klassname
  psych/visitors/to_ruby.rb:207:in `visit_Psych_Nodes_Mapping'
    obj = revive((resolve_class(name) || class_loader.object), o)
  psych/visitors/visitor.rb:15:in `visit'
    send DISPATCH[target.class], target
  psych/visitors/visitor.rb:5:in `accept'
    visit target
  psych/visitors/to_ruby.rb:31:in `accept'
    result = super
  psych/visitors/to_ruby.rb:321:in `block in revive_hash'
    val = accept(v)
  psych/visitors/to_ruby.rb:319:in `each'
    o.children.each_slice(2) { |k,v|
  psych/visitors/to_ruby.rb:319:in `each_slice'
    o.children.each_slice(2) { |k,v|
  psych/visitors/to_ruby.rb:319:in `revive_hash'
    o.children.each_slice(2) { |k,v|
  psych/visitors/to_ruby.rb:161:in `visit_Psych_Nodes_Mapping'
    return revive_hash(register(o, {}), o) unless o.tag
  psych/visitors/visitor.rb:15:in `visit'
    send DISPATCH[target.class], target
  psych/visitors/visitor.rb:5:in `accept'
    visit target
  psych/visitors/to_ruby.rb:31:in `accept'
    result = super
  psych/visitors/to_ruby.rb:321:in `block in revive_hash'
    val = accept(v)
  psych/visitors/to_ruby.rb:319:in `each'
    o.children.each_slice(2) { |k,v|
  psych/visitors/to_ruby.rb:319:in `each_slice'
    o.children.each_slice(2) { |k,v|
  psych/visitors/to_ruby.rb:319:in `revive_hash'
    o.children.each_slice(2) { |k,v|
  psych/visitors/to_ruby.rb:357:in `revive'
    init_with(s, revive_hash({}, node), node)
  psych/visitors/to_ruby.rb:207:in `visit_Psych_Nodes_Mapping'
    obj = revive((resolve_class(name) || class_loader.object), o)
  psych/visitors/visitor.rb:15:in `visit'
    send DISPATCH[target.class], target
  psych/visitors/visitor.rb:5:in `accept'
    visit target
  psych/visitors/to_ruby.rb:31:in `accept'
    result = super
  psych/visitors/to_ruby.rb:321:in `block in revive_hash'
    val = accept(v)
  psych/visitors/to_ruby.rb:319:in `each'
    o.children.each_slice(2) { |k,v|
  psych/visitors/to_ruby.rb:319:in `each_slice'
    o.children.each_slice(2) { |k,v|
  psych/visitors/to_ruby.rb:319:in `revive_hash'
    o.children.each_slice(2) { |k,v|
  psych/visitors/to_ruby.rb:357:in `revive'
    init_with(s, revive_hash({}, node), node)
  psych/visitors/to_ruby.rb:207:in `visit_Psych_Nodes_Mapping'
    obj = revive((resolve_class(name) || class_loader.object), o)
  psych/visitors/visitor.rb:15:in `visit'
    send DISPATCH[target.class], target
  psych/visitors/visitor.rb:5:in `accept'
    visit target
  psych/visitors/to_ruby.rb:31:in `accept'
    result = super
  psych/visitors/to_ruby.rb:321:in `block in revive_hash'
    val = accept(v)
  psych/visitors/to_ruby.rb:319:in `each'
    o.children.each_slice(2) { |k,v|
  psych/visitors/to_ruby.rb:319:in `each_slice'
    o.children.each_slice(2) { |k,v|
  psych/visitors/to_ruby.rb:319:in `revive_hash'
    o.children.each_slice(2) { |k,v|
  psych/visitors/to_ruby.rb:357:in `revive'
    init_with(s, revive_hash({}, node), node)
  psych/visitors/to_ruby.rb:207:in `visit_Psych_Nodes_Mapping'
    obj = revive((resolve_class(name) || class_loader.object), o)
  psych/visitors/visitor.rb:15:in `visit'
    send DISPATCH[target.class], target
  psych/visitors/visitor.rb:5:in `accept'
    visit target
  psych/visitors/to_ruby.rb:31:in `accept'
    result = super
  psych/visitors/to_ruby.rb:314:in `block in register_empty'
    object.children.each { |c| list.push accept c }
  psych/visitors/to_ruby.rb:314:in `each'
    object.children.each { |c| list.push accept c }
  psych/visitors/to_ruby.rb:314:in `register_empty'
    object.children.each { |c| list.push accept c }
  psych/visitors/to_ruby.rb:140:in `visit_Psych_Nodes_Sequence'
    register_empty(o)
  psych/visitors/visitor.rb:15:in `visit'
    send DISPATCH[target.class], target
  psych/visitors/visitor.rb:5:in `accept'
    visit target
  psych/visitors/to_ruby.rb:31:in `accept'
    result = super
  psych/visitors/to_ruby.rb:314:in `block in register_empty'
    object.children.each { |c| list.push accept c }
  psych/visitors/to_ruby.rb:314:in `each'
    object.children.each { |c| list.push accept c }
  psych/visitors/to_ruby.rb:314:in `register_empty'
    object.children.each { |c| list.push accept c }
  psych/visitors/to_ruby.rb:140:in `visit_Psych_Nodes_Sequence'
    register_empty(o)
  psych/visitors/visitor.rb:15:in `visit'
    send DISPATCH[target.class], target
  psych/visitors/visitor.rb:5:in `accept'
    visit target
  psych/visitors/to_ruby.rb:31:in `accept'
    result = super
  psych/visitors/to_ruby.rb:295:in `visit_Psych_Nodes_Document'
    accept o.root
  psych/visitors/visitor.rb:15:in `visit'
    send DISPATCH[target.class], target
  psych/visitors/visitor.rb:5:in `accept'
    visit target
  psych/visitors/to_ruby.rb:31:in `accept'
    result = super
  psych/nodes/node.rb:37:in `to_ruby'
    Visitors::ToRuby.create.accept(self)
  psych.rb:246:in `load'
    result ? result.to_ruby : result
  sidekiq/extensions/action_mailer.rb:16:in `perform'
    (target, method_name, args) = YAML.load(yml)
  sidekiq/processor.rb:75:in `execute_job'
    worker.perform(*cloned_args)
  sidekiq/processor.rb:52:in `block (2 levels) in process'
    execute_job(worker, cloned(msg['args']))
  sidekiq/middleware/chain.rb:127:in `block in invoke'
    yield
  sidekiq/middleware/server/active_record.rb:6:in `call'
    yield
  sidekiq/middleware/chain.rb:129:in `block in invoke'
    chain.shift.call(*args, &traverse_chain)
  sidekiq/middleware/server/retry_jobs.rb:74:in `call'
    yield
  sidekiq/middleware/chain.rb:129:in `block in invoke'
    chain.shift.call(*args, &traverse_chain)
  sidekiq/middleware/server/logging.rb:11:in `block in call'
    yield
  sidekiq/logging.rb:24:in `with_context'
    yield
  sidekiq/middleware/server/logging.rb:7:in `call'
    Sidekiq::Logging.with_context("#{worker.class.to_s} JID-#{item['jid']}#{" BID-#{item['bid']}" if item['bid']}") do
  sidekiq/middleware/chain.rb:129:in `block in invoke'
    chain.shift.call(*args, &traverse_chain)
  sidekiq/middleware/chain.rb:132:in `call'
    traverse_chain.call
  sidekiq/middleware/chain.rb:132:in `invoke'
    traverse_chain.call
  sidekiq/processor.rb:51:in `block in process'
    Sidekiq.server_middleware.invoke(worker, msg, queue) do
  sidekiq/processor.rb:98:in `stats'
    yield
  sidekiq/processor.rb:50:in `process'
    stats(worker, msg, queue) do
  celluloid/calls.rb:26:in `public_send'
    obj.public_send(@method, *@arguments, &_block)
  celluloid/calls.rb:26:in `dispatch'
    obj.public_send(@method, *@arguments, &_block)
  celluloid/calls.rb:122:in `dispatch'
    super(obj)
  celluloid/cell.rb:60:in `block in invoke'
    call.dispatch(@subject)
  celluloid/cell.rb:71:in `block in task'
    yield
  celluloid/actor.rb:357:in `block in task'
    yield
  celluloid/tasks.rb:57:in `block in initialize'
    yield
  celluloid/tasks/task_fiber.rb:15:in `block in create'
    yield
```

### Package Versions
```
actionmailer	4.2.0
actionpack	4.2.0
actionview	4.2.0
activejob	4.2.0
activemodel	4.2.0
activerecord	4.2.0
activesupport	4.2.0
arel	6.0.0
aws-sdk	2.0.31
aws-sdk-core	2.0.31
aws-sdk-resources	2.0.31
axiom-types	0.1.1
bcrypt	3.1.10
builder	3.2.2
bundler	1.7.12
celluloid	0.16.0
coercible	1.0.0
connection_pool	2.2.0
descendants_tracker	0.0.4
diffy	3.0.7
dotenv	1.0.2
equalizer	0.0.10
erubis	2.7.0
execjs	2.3.0
faker	1.4.3
faraday	0.9.1
foreman	0.76.0
friendly_id	5.1.0
globalid	0.3.0
grape	0.11.0
grape-entity	0.4.5
grape-swagger	0.10.1
grape-swagger-rails	0.1.0
hashie	3.4.0
hike	1.2.3
hitimes	1.2.2
hstore_flags	0.4.0
i18n	0.7.0
ice_nine	0.11.1
jmespath	1.0.2
jquery-rails	4.0.3
json	1.8.2
jwt	1.4.0
loofah	2.0.1
mail	2.6.3
mime-types	2.4.3
mini_portile	0.6.2
minitest	5.5.1
multi_json	1.10.1
multi_xml	0.5.5
multipart-post	2.0.0
nokogiri	1.6.6.2
oauth	0.4.7
oauth2	1.0.0
pg	0.18.1
pg_array_parser	0.0.9
postgres_ext	2.4.1
puma	2.11.0
rack	1.6.0
rack-accept	0.4.5
rack-contrib	1.2.0
rack-cors	0.3.1
rack-mount	0.8.3
rack-policy	0.4.1
rack-protection	1.5.3
rack-test	0.6.3
rack-utf8_sanitizer	1.3.0
rails	4.2.0
rails-deprecated_sanitizer	1.0.3
rails-dom-testing	1.0.5
rails-html-sanitizer	1.0.1
rails_12factor	0.0.3
rails_safe_tasks	1.0.0
rails_serve_static_assets	0.0.4
rails_stdout_logging	0.0.3
railties	4.2.0
rake	10.4.2
redis	3.2.1
redis-namespace	1.5.2
representable	2.1.5
responders	2.1.0
roar	1.0.1
roar-rails	1.0.1
sass	3.4.11
sass-rails	5.0.1
sentry-raven	0.12.3
sidekiq	3.3.3
sinatra	1.4.6
sorcery	0.9.0
sprockets	2.12.3
sprockets-rails	2.2.4
test_xml	0.1.7
thor	0.19.1
thread_safe	0.3.4
tilt	1.4.1
timers	4.0.1
tzinfo	1.2.2
uber	0.0.13
uglifier	2.7.0
virtus	1.0.5
```

**Comment by miksago** [comment]
This turned out to be because of the passing of an entire activerecord object

**Comment by jmccartie** [comment]
I started getting this error after upgrading to Rails 4.2.  I made no changes to my code otherwise.

```
ArgumentError: undefined class/module Struct::ActiveRecord::
... 95 non-project frames
ArgumentError: undefined class/module ActiveRecord::Attribute::
... 95 non-project frames
```

When I go to the Sidekiq dashboard and "Retry All", they succeed with no issue.  

Offending code:

```ruby
ReportMailer.delay.due(user, :tomorrow)
```

Any idea on what changed where passing the object into the mailer no longer works? (but magically works on a Retry All?)

**Comment by ryansch** [comment]
It appears that you're trying to serialize an instance of an AR model like the original poster.  Your mailers should all accept ids.  Example:

```ruby
ReportMailer.delay.due(user_id, :tomorrow)
```
