### ISSUE TITLE
NoMethodError: undefined method `sidekiq_options_hash'

### ISSUE THREAD

**Issue by mockdeep** [mperham/sidekiq#2302]
We're seeing an intermittent issue with our Sidekiq workers. The error is:

```
NoMethodError: undefined method `sidekiq_options_hash' for CampaignPdfWorker:Class
```

Here is our code:

```ruby
class CampaignPdfWorker

  include Sidekiq::Worker
  sidekiq_options queue: :slow

  RETRY_DELAY = 10.seconds

  def perform(campaign_id)
    return if already_queued_or_scheduled?(args: [campaign_id])

    campaign = Campaign.find(campaign_id)
    CampaignPdfGenerator.new(campaign).generate_pdf

  rescue PdfMerger::SignaledError
    CampaignPdfWorker.perform_in(RETRY_DELAY, campaign_id)
  end

private

  def already_queued_or_scheduled?(args: [])
    queue.any? { |job| matches?(job, args) } ||
      schedule.any? { |job| matches?(job, args) }
  end

  def matches?(job, args)
    job.klass == self.class.to_s && job.args == args
  end

  def queue
    Sidekiq::Queue.new(queue_name)
  end

  def schedule
    Sidekiq::ScheduledSet.new
  end

  def queue_name
    self.class.sidekiq_options['queue']
  end

end
```

Full stack trace:

```
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/worker.rb:79 :in `get_sidekiq_options`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/worker.rb:67 :in `sidekiq_options`
    [PROJECT_ROOT]/app/workers/campaign_pdf_worker.rb:38 :in `queue_name`
    [PROJECT_ROOT]/app/workers/campaign_pdf_worker.rb:30 :in `queue`
    [PROJECT_ROOT]/app/workers/campaign_pdf_worker.rb:21 :in `already_queued_or_scheduled?`
    [PROJECT_ROOT]/app/workers/campaign_pdf_worker.rb:9 :in `perform`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:75 :in `execute_job`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:52 :in `block (2 levels) in process`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:127 :in `block in invoke`
    [GEM_ROOT]/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/sidekiq.rb:33 :in `block in call`
    [GEM_ROOT]/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353 :in `perform_action_with_newrelic_trace`
    [GEM_ROOT]/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/sidekiq.rb:29 :in `call`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129 :in `block in invoke`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129 :in `block in invoke`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/active_record.rb:6 :in `call`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129 :in `block in invoke`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/retry_jobs.rb:74 :in `call`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129 :in `block in invoke`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/logging.rb:11 :in `block in call`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/logging.rb:24 :in `with_context`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/middleware/server/logging.rb:7 :in `call`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:129 :in `block in invoke`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:132 :in `call`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/middleware/chain.rb:132 :in `invoke`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:51 :in `block in process`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:98 :in `stats`
    [GEM_ROOT]/gems/sidekiq-3.3.3/lib/sidekiq/processor.rb:50 :in `process`
    [GEM_ROOT]/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26 :in `public_send`
    [GEM_ROOT]/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26 :in `dispatch`
    [GEM_ROOT]/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122 :in `dispatch`
    [GEM_ROOT]/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60 :in `block in invoke`
    [GEM_ROOT]/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71 :in `block in task`
    [GEM_ROOT]/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357 :in `block in task`
    [GEM_ROOT]/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57 :in `block in initialize`
    [GEM_ROOT]/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15 :in `block in create`
```

**Comment by mperham** [comment]
I can't explain that trace.  Maybe you edited that class and need to restart Sidekiq to pick up the changes?

**Comment by mockdeep** [comment]
We did make a change to the worker adding the `queue_name` method that refers to `sidekiq_options`, but this error happened 3 hours after the change had been deployed. It only happened once, though, and the workers seem to be working fine aside from the one hiccup. I looked at the Sidekiq source and the error didn't make any sense to me either. All I could guess is that maybe it happened when a worker was first loading or maybe in the process of being killed.

**Comment by mockdeep** [comment]
I'll close this for now. It might just be one of those things that happens once and never again.

**Comment by mockdeep** [comment]
Nope, it just happened again...

**Comment by mperham** [comment]
No other reports of this behavior, assuming it is app-specific.

**Comment by mockdeep** [comment]
It's been extremely rare. I think it's only happened 3-4 times, and seems to be when we change a worker to reference the options.

**Comment by bobmaerten** [comment]
We sometimes have this kind of error too. Our base worker class implements a dedup-system exactly like @mockdeep 's one, accessing correct queue via `self`:

```ruby
  def queue_entries
    Sidekiq::Queue.new(self.class.sidekiq_options['queue']).entries
  end
```

Running Sidekiq 4.0.1 on ruby 2.3.0, we have a more detailed error message:

```
app/workers/base_worker.rb:21:in `queue_entries'
undefined method `sidekiq_options_hash' for OrderStateWorker:Class
Did you mean?  sidekiq_options_hash?
               sidekiq_options_hash=
               sidekiq_options
```

My 2 cents.

**Comment by mockdeep** [comment]
Yeah, we continue to see it once every week or two.

**Comment by mockdeep** [comment]
Continuing to see these errors with greater frequency.

**Comment by mperham** [comment]
Couple of things:

1. That scanning of queues is **extremely** inefficient and slow.  You're much better off using a unique plugin, either Sidekiq Enterprise's or a 3rd party.
2. `sidekiq_options` is a setter.  To get the queue, you must use `get_sidekiq_options['queue']`.

**Comment by mockdeep** [comment]
Thanks for the feedback. Will give `get_sidekiq_options` a try. While it may be inefficient to scan the queues, it's still an improvement on the extra work we'd be doing otherwise. Waiting on a good opportunity to ask for Enterprise, though.

**Comment by mdehoog** [comment]
We're seeing this too, in approximately 1 in 20,000,000 jobs processed. Noticed that `sidekiq_options_hash` is defined using a `class_attribute`. Might it be possible that something is hitting the getter method while the method is removed by this: https://github.com/rails/rails/blob/450889d1464431a04ef5c8a0f6a45b877aafe506/activesupport/lib/active_support/core_ext/class/attribute.rb#L89... possibly a race condition?

Here's our stacktrace if helpful.

```
vendor/bundle/ruby/2.3.0/gems/attr_encrypted-1.4.0/lib/attr_encrypted.rb:259:in `method_missing': undefined method `sidekiq_options_hash' for PusherJob:Class
Did you mean?  sidekiq_options_hash?
               sidekiq_options_hash=
               sidekiq_options (NoMethodError)
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/worker.rb:105:in `get_sidekiq_options'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/options_with_fallback.rb:58:in `options'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/options_with_fallback.rb:10:in `unique_enabled?'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/logging.rb:10:in `call'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-failures-0.4.5/lib/sidekiq/failures/middleware.rb:9:in `call'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `invoke'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:134:in `block (3 levels) in process'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:183:in `stats'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'
    from config/initializers/sidekiq.rb:22:in `block in <top (required)>'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
    from vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

**Comment by betesh** [comment]
I get this error about once a month.  I can't find any incorrect uses of `siekiq_options` in my code.  It only comes from 2 of our worker classes.  Here's an approximate version of one of those classes:

```
class MyWorker
  include Sidekiq::Worker

  def perform(id)
    # Do stuff
  end

  def self.do_or_enqueue(id)
    if Sidekiq.server? && !some_condition
      perform_async id # This line is in the NoMethodError stacktrace
    else
      # Do the same stuff as in the perform method
    end
  end
end
```
