### ISSUE TITLE
EXECABORT Transaction discarded because of previous errors.:

### ISSUE THREAD

**Issue by maccman** [mperham/sidekiq#2326]
Getting quite a lot of these errors:

```
Redis::CommandError - EXECABORT Transaction discarded because of previous errors.:
2015-04-27T19:14:33.628123+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/pipeline.rb:79:in `finish'
2015-04-27T19:14:33.628124+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:133:in `block in call_pipeline'
2015-04-27T19:14:33.628126+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
2015-04-27T19:14:33.628128+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:131:in `call_pipeline'
2015-04-27T19:14:33.628130+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis.rb:2094:in `block in multi'
2015-04-27T19:14:33.628131+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
2015-04-27T19:14:33.628133+00:00 app[web.1]: 	/app/vendor/ruby-2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
2015-04-27T19:14:33.628135+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
2015-04-27T19:14:33.628136+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis.rb:2086:in `multi'
2015-04-27T19:14:33.628138+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/client.rb:179:in `block in raw_push'
2015-04-27T19:14:33.628140+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
2015-04-27T19:14:33.628141+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
2015-04-27T19:14:33.628143+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
2015-04-27T19:14:33.628154+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
2015-04-27T19:14:33.628155+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
2015-04-27T19:14:33.628157+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/client.rb:178:in `raw_push'
2015-04-27T19:14:33.628159+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sidekiq-pro-2.0.1/lib/sidekiq/batch/client.rb:36:in `raw_push_with_batch'
2015-04-27T19:14:33.628160+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/client.rb:68:in `push'
2015-04-27T19:14:19.368796+00:00 heroku[router]: at=info method=POST path="/v2/callbacks/clearbit" host=closeio-clearbit.herokuapp.com request_id=d499b82d-6841-4ba4-8c2e-f4f928462c90 fwd="54.153.75.75" dyno=web.1 connect=2ms service=11ms status=500 bytes=911
2015-04-27T19:14:33.628162+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/worker.rb:84:in `client_push'
2015-04-27T19:14:33.628163+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.3/lib/sidekiq/worker.rb:40:in `perform_async'
2015-04-27T19:14:33.628165+00:00 app[web.1]: 	/app/app/routes/callbacks.rb:8:in `block in <class:Callbacks>'
2015-04-27T19:14:33.628167+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/bundler/gems/sinatra-29c51d12fdd9/lib/sinatra/base.rb:1610:in `call'
2015-04-27T19:14:33.628169+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.1.0/bundler/gems/sinatra-29c51d12fdd9/lib/sinatra/base.rb:1610:in `block in compile!'
```

**Comment by mperham** [comment]
Is it possible you're out of Redis space?

**Comment by davydovanton** [comment]
@maccman you can check your redis memory stats with `INFO` command in redis-cli:
```
~ » redis-cli
127.0.0.1:6379> INFO
....
# Memory
used_memory:10587608
....
maxmemory:3221225472
....
```

**Comment by mperham** [comment]
I've never seen an EXECABORT error before so I'm not sure what else can cause it but I suspect an operational problem, not a bug.

**Comment by guinslym** [comment]
hi! I have quite the same error but I don't have a `maxmemory`

```
# Memory
used_memory:137116816
used_memory_human:130.76M
used_memory_rss:145559552
used_memory_peak:137116816
used_memory_peak_human:130.76M
used_memory_lua:33792
mem_fragmentation_ratio:1.06
mem_allocator:jemalloc-3.6.0
```
[gist](https://gist.github.com/guinslym/ab877162f389660acceb)

my error (sidekiq.log; wich is now 1GB of logs)
```
2015-09-29T01:54:10.878Z 25299 TID-12lb28 ERROR: heartbeat: EXECABORT Transaction discarded because of previous errors.
2015-09-29T01:54:11.200Z 25299 TID-80nk4 ERROR: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
2015-09-29T01:54:11.200Z 25299 TID-80nk4 ERROR: /var/www/pkpaud/shared/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:113:in `call'
2015-09-29T01:54:15.894Z 25299 TID-12lb28 ERROR: heartbeat: EXECABORT Transaction discarded because of previous errors.
2015-09-29T01:54:20.898Z 25299 TID-12lb28 ERROR: heartbeat: EXECABORT Transaction discarded because of previous errors.
2015-09-29T01:54:25.912Z 25299 TID-12lb28 ERROR: heartbeat: EXECABORT Transaction discarded because of previous errors.
2015-09-29T01:54:30.929Z 25299 TID-12lb28 ERROR: heartbeat: EXECABORT Transaction discarded because of previous errors.
```

**Comment by mperham** [comment]
@guinslym Did you read this:

ERROR: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.

**Comment by guinslym** [comment]
Ok thanks @mperham :+1: 
I followed the answer of this post
[stackoverflow](https://stackoverflow.com/questions/19581059/misconf-redis-is-configured-to-save-rdb-snapshots)
