### ISSUE TITLE
Database configuration does not specify adapter in 3.3.4

### ISSUE THREAD

**Issue by carlosbrb** [mperham/sidekiq#2329]
Hi, I have this problem on sidekiq start. 

Environment:
Ruby: 2.1.2p95
Rails: 4.0.1
Sidekiq: 3.3.4
my database.yml (all parameters are correct)

```yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ****
  password: ****
  host: localhost

development:
  <<: *default
  database: "trazeable4_development"

test:
  <<: *default
  database: "test_database_name"

production:
  <<: *default
  database: "trazeable4_development"
```

initialize command: RAILS_ENV=production bundle exec sidekiq 
or just: bundle exec sidekiq 

Backtrace:
```
database configuration does not specify adapter
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/activerecord-4.0.1/lib/active_record/connection_adapters/connection_specification.rb:52:in `resolve_hash_connection'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/activerecord-4.0.1/lib/active_record/connection_adapters/connection_specification.rb:46:in `resolve_string_connection'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/activerecord-4.0.1/lib/active_record/connection_adapters/connection_specification.rb:32:in `spec'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/activerecord-4.0.1/lib/active_record/connection_handling.rb:39:in `establish_connection'
/home/carlos/Work/trazeable4/app/models/trz_agente.rb:2:in `<class:TrzAgente>'
/home/carlos/Work/trazeable4/app/models/trz_agente.rb:1:in `<top (required)>'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `block in require'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:330:in `require_or_load'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:289:in `depend_on'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:207:in `require_dependency'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/railties-4.0.1/lib/rails/engine.rb:465:in `block (2 levels) in eager_load!'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/railties-4.0.1/lib/rails/engine.rb:464:in `each'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/railties-4.0.1/lib/rails/engine.rb:464:in `block in eager_load!'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/railties-4.0.1/lib/rails/engine.rb:462:in `each'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/railties-4.0.1/lib/rails/engine.rb:462:in `eager_load!'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/railties-4.0.1/lib/rails/engine.rb:347:in `eager_load!'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/railties-4.0.1/lib/rails/application/finisher.rb:56:in `each'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/railties-4.0.1/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/railties-4.0.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/railties-4.0.1/lib/rails/initializable.rb:30:in `run'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/railties-4.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/carlos/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/home/carlos/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/home/carlos/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/home/carlos/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/home/carlos/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each'
/home/carlos/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `call'
/home/carlos/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/home/carlos/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/home/carlos/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/railties-4.0.1/lib/rails/initializable.rb:54:in `run_initializers'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/railties-4.0.1/lib/rails/application.rb:215:in `initialize!'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/railties-4.0.1/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/carlos/Work/trazeable4/config/environment.rb:5:in `<top (required)>'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/sidekiq-3.0.2/lib/sidekiq/cli.rb:214:in `require'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/sidekiq-3.0.2/lib/sidekiq/cli.rb:214:in `boot_system'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/sidekiq-3.0.2/lib/sidekiq/cli.rb:43:in `parse'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/gems/sidekiq-3.0.2/bin/sidekiq:7:in `<top (required)>'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/bin/sidekiq:23:in `load'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/bin/sidekiq:23:in `<main>'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/bin/ruby_executable_hooks:15:in `eval'
/home/carlos/.rvm/gems/ruby-2.1.2@trazeable4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mperham** [comment]
Use `-e`.

```
bundle exec sidekiq -e production
```

You don't have the proper db config for the TrzAgente model.

**Comment by carlosbrb** [comment]
thanks @mperham
