### ISSUE TITLE
newrelic_rpm breaks pro web UI

### ISSUE THREAD

**Issue by substars** [mperham/sidekiq#2345]
Not sure whose problem this is (other than mine), but something about New Relic middleware is breaking sidekiq-pro 2.0.2; 2.0.1 worked. Reverting to 2.0.1 or removing newrelic_rpm from the Gemfile both serve as workarounds.

sinatra 1.4.6 (1.4.5 also doesn't work)
rack 1.5.3 (1.5.2 also doesn't work)
newrelic_rpm 3.12.0.288  (3.9.5.251 also doesn't work)

edit: this is on JRuby 1.7.19 FWIW

dev mode:
```
NoMethodError (undefined method `settings' for #<NewRelic::Rack::BrowserMonitoring:0x40289de>):
  vendor/bundle/jruby/1.9/gems/sidekiq-pro-2.0.2/lib/sidekiq/pro/web.rb:60:in `call'
  vendor/bundle/jruby/1.9/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/jruby/1.9/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
  vendor/bundle/jruby/1.9/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/jruby/1.9/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
  vendor/bundle/jruby/1.9/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/jruby/1.9/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
  vendor/bundle/jruby/1.9/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
```

looks a bit different in production mode:
```
NoMethodError (undefined method `settings' for #<NewRelic::Rack::AgentHooks:0x6996cc33>):
  sidekiq-pro (2.0.2) lib/sidekiq/pro/web.rb:60:in `call'
  newrelic_rpm (3.9.5.251) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  newrelic_rpm (3.9.5.251) lib/new_relic/agent/instrumentation/middleware_tracing.rb:52:in `call'
  rack-protection (1.5.3) lib/rack/protection/xss_header.rb:18:in `call'
  newrelic_rpm (3.9.5.251) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  newrelic_rpm (3.9.5.251) lib/new_relic/agent/instrumentation/middleware_tracing.rb:52:in `call'
```

**Comment by substars** [comment]
dupe, my bad

**Comment by mperham** [comment]
Thanks for the stacks.  That might critical.

Your RPM versions are pretty different between dev and production.

**Comment by mperham** [comment]
See #2344
