### ISSUE TITLE
NoMethodError: undefined method `each_pair' for nil:NilClass

### ISSUE THREAD

**Issue by palexvs** [mperham/sidekiq#2353]
sidekiq-3.3.4
ruby-2.2.0
rails-4.1.10

Error:
```
NoMethodError: undefined method `each_pair' for nil:NilClass
"/Users/palexvs/.rvm/gems/ruby-2.2.0@talkable/gems/activesupport-4.1.10/lib/active_support/core_ext/hash/deep_merge.rb:22:in `deep_merge!'",
 "/Users/palexvs/.rvm/gems/ruby-2.2.0@talkable/gems/sidekiq-3.3.4/lib/sidekiq/web_helpers.rb:15:in `block (2 levels) in strings'",
 "/Users/palexvs/.rvm/gems/ruby-2.2.0@talkable/gems/sidekiq-3.3.4/lib/sidekiq/web_helpers.rb:12:in `each'",
 "/Users/palexvs/.rvm/gems/ruby-2.2.0@talkable/gems/sidekiq-3.3.4/lib/sidekiq/web_helpers.rb:12:in `block in strings'",
 "/Users/palexvs/.rvm/gems/ruby-2.2.0@talkable/gems/sidekiq-3.3.4/lib/sidekiq/web_helpers.rb:11:in `each'",
 "/Users/palexvs/.rvm/gems/ruby-2.2.0@talkable/gems/sidekiq-3.3.4/lib/sidekiq/web_helpers.rb:11:in `each_with_object'",
 "/Users/palexvs/.rvm/gems/ruby-2.2.0@talkable/gems/sidekiq-3.3.4/lib/sidekiq/web_helpers.rb:11:in `strings'",
 "/Users/palexvs/.rvm/gems/ruby-2.2.0@talkable/gems/sidekiq-3.3.4/lib/sidekiq/web_helpers.rb:77:in `get_locale'",
 "/Users/palexvs/.rvm/gems/ruby-2.2.0@talkable/gems/sidekiq-3.3.4/lib/sidekiq/web_helpers.rb:81:in `t'",
....
```

Method where exception is happened::
```
  module WebHelpers
    def strings(lang)
      @@strings ||= {}
      @@strings[lang] ||= begin
        # Allow sidekiq-web extensions to add locale paths
        # so extensions can be localized
        settings.locales.each_with_object({}) do |path, global|
          find_locale_files(lang).each do |file|
            strs = YAML.load(File.open(file))
            global.deep_merge!(strs[lang]) <------ strs[lang] == nil
```

Debug:
```
> file                                                                                                                                                                             
=> "/Users/palexvs/.rvm/gems/ruby-2.2.0@talkable/gems/sidekiq-3.3.4/web/locales/cs.yml"

> strs                                                                                                                                                                             
=> {"cs"=>
  {"Dashboard"=>"Kontrolní panel",
   "Status"=>"Stav",
....

> lang                                                                                                                                                                             
=> "*"

> strs[lang]
=> nil
```

**Comment by davydovanton** [comment]
This bug is happen only for cs locale? I will check this on my local machine a couple of hours.

**Comment by palexvs** [comment]
Local or lang is "*"

**Comment by mperham** [comment]
How are you calling the Web UI?  Are you using some unusual http client?  I ask because a request header of `Accept-Lang: *` seems really odd.

**Comment by mperham** [comment]
Oh, nevermind.

**Comment by palexvs** [comment]
It happened during tests (rspec), lang header contains: 'en-us; *'

**Comment by mperham** [comment]
Ok, that's valid so we'll get it fixed.

**Comment by palexvs** [comment]
Thanks.
sidekiq-3.3.3 - works in this situation properly

**Comment by mperham** [comment]
Can you try master and see if it fixes your issue?

**Comment by palexvs** [comment]
It works, Thanks!
