### ISSUE TITLE
Role does not exist issue with Rolify

### ISSUE THREAD

**Issue by mdere** [mperham/sidekiq#2386]
Hello Sidekiq Community! So my sidekiq implementation works on localhost - I am pretty new with this...so when I try to deploy this badboy to staging on an AWS EC2 instance. I get the following in the logs:
```
FATAL:  role "deployer" does not exist
Run `$ bin/rake db:create db:migrate` to create your database
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:898:in `rescue in connect'
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `connect'
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:568:in `initialize'
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection'
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
/home/deployer/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/home/deployer/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_handling.rb:87:in `connection'
/var/www/revv/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/model_schema.rb:209:in `table_exists?'
/var/www/revv/shared/bundle/ruby/2.1.0/bundler/gems/rolify-749a07abee11/lib/rolify/configure.rb:69:in `role_table_missing?'
/var/www/revv/shared/bundle/ruby/2.1.0/bundler/gems/rolify-749a07abee11/lib/rolify/configure.rb:60:in `block in sanity_check'
/var/www/revv/shared/bundle/ruby/2.1.0/bundler/gems/rolify-749a07abee11/lib/rolify/configure.rb:58:in `each'
/var/www/revv/shared/bundle/ruby/2.1.0/bundler/gems/rolify-749a07abee11/lib/rolify/configure.rb:58:in `sanity_check'
/var/www/revv/shared/bundle/ruby/2.1.0/bundler/gems/rolify-749a07abee11/lib/rolify/configure.rb:8:in `configure'
/var/www/revv/releases/20150614204127/config/initializers/rolify.rb:1:in `<top (required)>'
```

I looked around and found that people had this issue. I updated my Rolify gem / did some random monkey patching, but it did not fix the issue. 

I am using capistrano for deployment
```
namespace :deploy do
  task :start, :roles => :app do
    run "touch #{current_path}/tmp/restart.txt"
    run "touch #{current_path}/log/sidekiq.log"
    run "cd #{current_path}; bundle exec sidekiq -d -L log/sidekiq.log -C './config/sidekiq.yml'"
  end
```
YML file - config/sidekiq.yml
```
:verbose: false
:logfile: ./log/sidekiq.log
:concurrency: 25
:queues:
  - [high, 5]
  - [default, 1]
```
Example of the worker file:
```
class EmailSender
  include Sidekiq::Worker
  sidekiq_options retry: true, queue: "high"
  def perform(email_hash)
    do stuff and send email
  end
end
```
Anythoughts what I can do here? Thanks!

**Comment by mperham** [comment]
This means that you have not created a "deployer" user in postgresql.
