### ISSUE TITLE
Sidekiqs Dashboard issues with Rack middlewares

### ISSUE THREAD

**Issue by mkubik8080** [mperham/sidekiq#2453]
After updating to 3.4.2 Dashboard stopped working with such stacktrace:

```ruby
2015-07-24 14:32:27 +0200: Rack app error: #<RuntimeError: you need to set up a session middleware *before* Rack::Protection::AuthenticityToken>
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:85:in `session'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/authenticity_token.rb:23:in `accepts?'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:45:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/auth/basic.rb:25:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/puma-2.12.2/lib/puma/rack/urlmap.rb:66:in `block in call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/puma-2.12.2/lib/puma/rack/urlmap.rb:50:in `each'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/puma-2.12.2/lib/puma/rack/urlmap.rb:50:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/puma-2.12.2/lib/puma/configuration.rb:53:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/puma-2.12.2/lib/puma/server.rb:539:in `handle_request'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/puma-2.12.2/lib/puma/server.rb:386:in `process_client'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/puma-2.12.2/lib/puma/server.rb:269:in `block in run'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/puma-2.12.2/lib/puma/thread_pool.rb:106:in `call'
/home/app/splitter_web/shared/bundle/ruby/2.2.0/gems/puma-2.12.2/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```
I'm enabling dashboard in config.ru like described here: https://github.com/mperham/sidekiq/wiki/Monitoring#standalone-with-basic-auth
and I use Puma to serve application.

**Comment by jonhyman** [comment]
You need to add a session store, something like `use Rack::Session::Cookie, :secret => ENV['RACK_SESSION_COOKIE']`. I'll update the wiki.

**Comment by mkubik8080** [comment]
thx, with secret it is working fine

**Comment by jonhyman** [comment]
Great! You need the session store now because of CSRF protections that were added.

**Comment by mperham** [comment]
Look carefully here: 

https://github.com/mperham/sidekiq/wiki/Monitoring#standalone
