### ISSUE TITLE
RuntimeError (you need to set up a session middleware *before* Rack::Protection::AuthenticityToken)

### ISSUE THREAD

**Issue by mhuggins** [mperham/sidekiq#2459]
I've followed the [Rails HTTP Basic Auth from Routes ](https://github.com/mperham/sidekiq/wiki/Monitoring#rails-http-basic-auth-from-routes) instructions.  After upgrading from Sidekiq 3.3.4 to 3.4.2, this functionality broke.

My implementation:

```ruby
require 'sidekiq/web'

Sidekiq::Web.use(Rack::Auth::Basic) do |username, password|
  ENV['ADMIN_USERNAME'].present? && ENV['ADMIN_PASSWORD'].present? &&
    username == ENV['ADMIN_USERNAME'] &&
    password == ENV['ADMIN_PASSWORD']
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/admin'
end
```

And the stack trace:

```
Started GET "/admin" for 174.149.206.31 at 2015-07-25 00:02:26 +0000
RuntimeError (you need to set up a session middleware *before* Rack::Protection::AuthenticityToken): 
  vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:85:in `session'
  vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:45:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/authenticity_token.rb:23:in `accepts?'
  vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
  vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
  vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
  vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
  vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/mapper.rb:51:in `serve'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:84:in `run_callbacks'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/static.rb:116:in `call'
  vendor/bundle/ruby/2.2.0/gems/honeybadger-2.1.1/lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/honeybadger-2.1.1/lib/honeybadger/config.rb:190:in `with_request'
  vendor/bundle/ruby/2.2.0/gems/honeybadger-2.1.1/lib/honeybadger/rack/user_feedback.rb:28:in `call'
  vendor/bundle/ruby/2.2.0/gems/honeybadger-2.1.1/lib/honeybadger/rack/error_notifier.rb:30:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.2.0/gems/honeybadger-2.1.1/lib/honeybadger/rack/user_informer.rb:18:in `call'
  vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in `process_client'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in `worker_loop'
  vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
  vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
  vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
  vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `load'
  vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>'
```

**Comment by mhuggins** [comment]
FWIW downgrading to 3.3.4 fixes the problem.  It'd be nice to get it fixed in the 3.4 series though.

**Comment by mperham** [comment]
Have you searched the issues?

**Comment by jonhyman** [comment]
You need to add a session store. That example in the documentation is out of date. Check the other ones which have rack session cookie.

**Comment by mhuggins** [comment]
@mperham Yes I've searched the issues.  You locked the other issue that I commented on immediately after I commented.

@jonhyman Yes, I have a session store.  Per my `session_store.rb` initializer:

```ruby
Rails.application.config.session_store :cookie_store, key: '_appname_session'
```

**Comment by jonhyman** [comment]
That's for your rails app. Sidekiq needs its own session store.

**Comment by mperham** [comment]
I locked it because my answer linked directly to the wiki code which solves the issue.  Any further commentary would add noise.

**Comment by mhuggins** [comment]
I tried including the `Rack::Session::Cookie` middleware as well, and it makes no difference.

```ruby
require 'sidekiq/web'

Sidekiq::Web.use(Rack::Session::Cookie, secret: Rails.application.config.secret_key_base)

Sidekiq::Web.use(Rack::Auth::Basic) do |username, password|
  ENV['ADMIN_USERNAME'].present? && ENV['ADMIN_PASSWORD'].present? &&
    username == ENV['ADMIN_USERNAME'] &&
    password == ENV['ADMIN_PASSWORD']
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/admin'
end
```

**Comment by pchaganti** [comment]
Having the same error mounting sidekiq web in a padrino app. Followed the wiki instructions for mounting sidekiq web in a rack app.

```Ruby
require File.expand_path("../config/boot.rb", __FILE__)

require 'sidekiq/web'

Sidekiq::Web.use Rack::Session::Cookie, :secret => ENV['RACK_SESSION_COOKIE']

run Rack::URLMap.new("/" => Padrino.application, "/sidekiq" => Sidekiq::Web)
```

**Comment by rubyconvict** [comment]
Upgraded sidekiq from 3.4.1 to 3.4.2, and I have the same problem.

**Comment by jasonneylon** [comment]
I’m coming across the same problem. Its look like its not possible to add the Session::Cookie middleware to the SideKiq web app before the Rack authentication_token middleware.

```ruby
Sidekiq::Web.use Rack::Session::Cookie, secret: "mysecret"
puts Sidekiq::Web.middleware.inspect
[[Rack::Protection, [{:use=>:authenticity_token}], nil], [Rack::Session::Cookie, [{:secret=>"```
"}], nil]]
```

**Comment by jonhyman** [comment]
Can you use some kind of insert before? Not sure if Rack supports this but rails does. http://api.rubyonrails.org/classes/Rails/Configuration/MiddlewareStackProxy.html#method-i-insert_before

**Comment by pchaganti** [comment]
@jasonneylon @jonhyman  There is a workaround to getting this to work in padrino posted by @ujifgc - https://github.com/padrino/padrino-framework/issues/1944

**Comment by sci-phi** [comment]
I am using Sidekiq in a Sinatra app, and it was broken by the 3.4.2 upgrade as well. The workaround from the Padrino issue @pchaganti mentioned resolved this for me also. 

In my "config.ru" file : 

```ruby
Sidekiq::Web.instance_eval { @middleware.reverse! } # Last added, First Run

run Rack::URLMap.new({
  "/" => WelcomeApp,
  "/admin" => AdminApp,
  '/admin/sidekiq' => Sidekiq::Web
})
```

**Comment by mperham** [comment]
Thank you for posting your workarounds.  I hope everyone understands this was a painful upgrade but necessary due to a pretty major security issue.  I can't control the Rack setup so I couldn't make this a seamless upgrade for all, or I would have.

**Comment by pda** [comment]
@sci-phi: Thanks for the tip, I've iterated on it; rather than reversing the entire middleware stack with `@middleware.reverse!`, it's possible to just bump the last-added middleware to the front:

```ruby
Sidekiq::Web.use Rack::Session::Cookie, :secret => "SOMETHING SECRET"
Sidekiq::Web.instance_eval { @middleware.rotate!(-1) }
```

They're equivalent when there's only the two items total, but perhaps handles larger middleware stacks better. (This remains an ugly workaround, not a good solution.)

**Comment by tommyalvarez** [comment]
None of the above worked for me for rails 5.1 api mode. I needed to add this to application.rb:

```
config.middleware.use ActionDispatch::Cookies
config.middleware.use ActionDispatch::Session::CookieStore, key: '_namespace_key'
```

**Comment by dbackeus** [comment]
Another workaround for Rails api mode: `Sidekiq::Web.use Rack::Protection`

This will make Sidekiq not re-add the middleware including the authenticity token check: https://github.com/mperham/sidekiq/blob/v6.0.5/lib/sidekiq/web.rb#L157

**Comment by zormandi** [comment]
Thanks @dbackeus , that was exactly what I needed. For future reference, here's our full Sidekiq UI setup for a Rails API app with HTTP Basic Auth:

`
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end
  Sidekiq::Web.use Rack::Session::Cookie, key: 'sidekiq.session', secret: ENV['SECRET_KEY_BASE']
  Sidekiq::Web.use Rack::Protection, use: :authenticity_token
  mount Sidekiq::Web => '/sidekiq'
`

**Comment by dbackeus** [comment]
Heads up that Sidekiq 6.1.0 removed the `rack-protection` dependency and now instead checks for `CsrfProtection` middleware: https://github.com/mperham/sidekiq/blob/v6.1.0/lib/sidekiq/web.rb#L161-L163

I'm on vacation so won't have time to investigate how this affects the underlying issue and workarounds. If anyone else has input feel free to share.

**Comment by mcmire** [comment]
I just tested out Sidekiq 6.1.0 and it doesn't seem like you have to do anything extra to get HTTP basic auth to work. This is essentially what I have in my `routes.rb`:

``` ruby
Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  ActiveSupport::SecurityUtils.secure_compare(Digest::SHA256.hexdigest(username), Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
    ActiveSupport::SecurityUtils.secure_compare(Digest::SHA256.hexdigest(password), Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
end
