### ISSUE TITLE
Cannot define multiple 'included' blocks for a Concern

### ISSUE THREAD

**Issue by andreydeineko** [mperham/sidekiq#2466]
When I run
```ruby
sidekiq # or bundle exec sidekiq
```
I get the following error:

```ruby
    Cannot define multiple 'included' blocks for a Concern
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/activesupport-4.1.9/lib/active_support/concern.rb:126:in `included'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/high_voltage-2.1.0/app/controllers/concerns/high_voltage/static_page.rb:4:in `<module:StaticPage>'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/high_voltage-2.1.0/app/controllers/concerns/high_voltage/static_page.rb:1:in `<top (required)>'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:443:in `load'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:443:in `block in load_file'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:633:in `new_constants_in'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:442:in `load_file'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:342:in `require_or_load'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:307:in `depend_on'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:225:in `require_dependency'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/railties-4.1.9/lib/rails/engine.rb:468:in `block (2 levels) in eager_load!'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/railties-4.1.9/lib/rails/engine.rb:467:in `each'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/railties-4.1.9/lib/rails/engine.rb:467:in `block in eager_load!'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/railties-4.1.9/lib/rails/engine.rb:465:in `each'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/railties-4.1.9/lib/rails/engine.rb:465:in `eager_load!'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/railties-4.1.9/lib/rails/engine.rb:346:in `eager_load!'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/railties-4.1.9/lib/rails/application/finisher.rb:58:in `each'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/railties-4.1.9/lib/rails/application/finisher.rb:58:in `block in <module:Finisher>'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `instance_exec'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `run'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/railties-4.1.9/lib/rails/initializable.rb:55:in `block in run_initializers'
    /home/andreydeineko/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
    /home/andreydeineko/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
    /home/andreydeineko/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
    /home/andreydeineko/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
    /home/andreydeineko/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:180:in `each'
    /home/andreydeineko/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
    /home/andreydeineko/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/railties-4.1.9/lib/rails/initializable.rb:54:in `run_initializers'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/railties-4.1.9/lib/rails/application.rb:300:in `initialize!'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
    /home/andreydeineko/partner-plus/config/environment.rb:5:in `<top (required)>'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/sidekiq-3.3.4/lib/sidekiq/cli.rb:241:in `boot_system'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/sidekiq-3.3.4/lib/sidekiq/cli.rb:50:in `run'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/gems/sidekiq-3.3.4/bin/sidekiq:8:in `<top (required)>'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/bin/sidekiq:23:in `load'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/bin/sidekiq:23:in `<main>'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/bin/ruby_executable_hooks:15:in `eval'
    /home/andreydeineko/.rvm/gems/ruby-2.0.0-p643@app_name/bin/ruby_executable_hooks:15:in `<main>'
```

Any thoughts on how to proceed?

**Comment by andreydeineko** [comment]
http://stackoverflow.com/questions/31721222/sidekiq-cannot-define-multiple-included-blocks-for-a-concern

Issue solved.
Updating the ```high_voltage``` gem did the trick.
