### ISSUE TITLE
timeout: 0 is not a valid value

### ISSUE THREAD

**Issue by NielsKSchjoedt** [mperham/sidekiq#2476]
Trying to start sidekiq in development I get:

```
timeout: 0 is not a valid value
/Users/NK/.rvm/gems/ruby-2.2.1@au_rails41/gems/sidekiq-3.4.2/lib/sidekiq/cli.rb:274:in `block in validate!'
/Users/NK/.rvm/gems/ruby-2.2.1@au_rails41/gems/sidekiq-3.4.2/lib/sidekiq/cli.rb:273:in `each'
/Users/NK/.rvm/gems/ruby-2.2.1@au_rails41/gems/sidekiq-3.4.2/lib/sidekiq/cli.rb:273:in `validate!'
/Users/NK/.rvm/gems/ruby-2.2.1@au_rails41/gems/sidekiq-3.4.2/lib/sidekiq/cli.rb:40:in `parse'
/Users/NK/.rvm/gems/ruby-2.2.1@au_rails41/gems/sidekiq-3.4.2/bin/sidekiq:12:in `<top (required)>'
/Users/NK/.rvm/gems/ruby-2.2.1@au_rails41/bin/sidekiq:23:in `load'
/Users/NK/.rvm/gems/ruby-2.2.1@au_rails41/bin/sidekiq:23:in `<main>'
/Users/NK/.rvm/gems/ruby-2.2.1@au_rails41/bin/ruby_executable_hooks:15:in `eval'
/Users/NK/.rvm/gems/ruby-2.2.1@au_rails41/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mperham** [comment]
Check your config/sidekiq.yml.

**Comment by NielsKSchjoedt** [comment]
Ahh that's where it was. Sorry :-)
