### ISSUE TITLE
Unknown command 't' at sidekiq/extensions/action_mailer.rb:17

### ISSUE THREAD

**Issue by mariohmol** [mperham/sidekiq#2511]
Guys,

cant send email at all!! Was working a few days ago, after i changed some things on config like this:
 (not sure if is related with this or others changes)

  config.action_mailer.default_url_options  = { host: 'http://localhost:3000', only_path: false } 
  routes.default_url_options = { host: 'http://localhost:3000' }
  config.action_controller.asset_host = 'http://localhost:3000' 
  config.action_mailer.asset_host = config.action_controller.asset_host

The mailer method is:
class UserMailer < ApplicationMailer
   def test(msg)
     @msg=msg
    mail to: "mmm**@gmail.com", subject: 'Teste de Email' 
  end
end

Started showing the error:

2015-08-26T23:23:01Z 20148 TID-owwr5iuaw Sidekiq::Extensions::DelayedMailer JID-027221ac3f8cfda5a490ab27 INFO: start
2015-08-26T23:23:01Z 20148 TID-owwr5iuaw Sidekiq::Extensions::DelayedMailer JID-027221ac3f8cfda5a490ab27 INFO: fail: 0.002 sec
2015-08-26T23:23:01Z 20148 TID-owwr5iuaw WARN: {"retry"=>true, "queue"=>"default", "class"=>"Sidekiq::Extensions::DelayedMailer", "args"=>["-
--\n- !ruby/class 'UserMailer'\n- :test\n- - testmail\n"], "jid"=>"027221ac3f8cfda5a490ab27", "enqueued_at"=>1440630676.137921, "error_messag
e"=>"unknown command 't'", "error_class"=>"ArgumentError", "failed_at"=>"2015-08-26T23:19:45Z", "retry_count"=>3, "retried_at"=>2015-08-26 23
:23:01 UTC}
2015-08-26T23:23:01Z 20148 TID-owwr5iuaw WARN: unknown command 't'
2015-08-26T23:23:01Z 20148 TID-owwr5iuaw WARN: /Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/extensions/action_m
ailer.rb:17:in `test'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/extensions/action_mailer.rb:17:in `perform'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `call'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/logging.rb:22:in `with_context'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `call'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `invoke'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:105:in `stats'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:47:in `block in process'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:86:in `do_defer'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:37:in `process'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
/Users/mariohmol/.rvm/gems/ruby-2.0.0-p598/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'

**Comment by mariohmol** [comment]
I changed the name of the method to test2 and changed the html to test2 as well, and worked... is anything in cache that can do it? even in development where i'm not using any class cache?
