### ISSUE TITLE
Identifying issues using ttin?

### ISSUE THREAD

**Issue by pratik60** [mperham/sidekiq#2524]
Hey Mike

We are scaling much better, thanks to sidekiq but there are a few things that I can't understand.

Some of my workers get stuck some time, and I think their timing is suspicious to when I restart them. Could that be possible?
 
Here's the TTIN output where 4-5 of the jobs are stuck -: https://gist.github.com/pratik60/ad93d6cab59f28592362

How do you debug this TTIN output? Any pointers will be enough....

Thanks

**Comment by jonhyman** [comment]
Take a look here: looks like things are hanging connecting to postgres?

```
2015-08-31T21:53:35.538Z 26886 TID-5tfns WARN: /webapps/myapp/shared/bundle/ruby/2.2.0/gems/rack-mini-profiler-0.9.6/lib/patches/db/pg.rb:90:in `exec'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/rack-mini-profiler-0.9.6/lib/patches/db/pg.rb:90:in `async_exec'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `block in exec_no_cache'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/ar-octopus-0.8.4/lib/octopus/abstract_adapter.rb:15:in `instrument'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `exec_no_cache'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:588:in `execute_and_clear'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:351:in `select'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/ar-octopus-0.8.4/lib/octopus/proxy.rb:404:in `block in send_queries_to_slave'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/ar-octopus-0.8.4/lib/octopus/proxy.rb:429:in `using_shard'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/ar-octopus-0.8.4/lib/octopus/proxy.rb:403:in `send_queries_to_slave'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/ar-octopus-0.8.4/lib/octopus/proxy.rb:374:in `send_queries_to_selected_slave'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/ar-octopus-0.8.4/lib/octopus/proxy.rb:268:in `method_missing'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/querying.rb:39:in `find_by_sql'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation.rb:638:in `exec_queries'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation.rb:514:in `load'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation.rb:243:in `to_a'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:132:in `method_missing'
/webapps/myapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:99:in `method_missing'
/webapps/myapp/releases/20150831173832/app/models/ad_account.rb:1266:in `get_historic_exchange_rates'
/webapps/myapp/releases/20150831173832/app/models/ad_account.rb:1453:in `compute_time_and_exchange_rates_for_backfill'
/webapps/myapp/releases/20150831173832/app/models/ad_account.rb:1354:in `block (2 levels) in update_ad_set_reports_preset'
/webapps/myapp/releases/20150831173832/app/models/ad_account.rb:1350:in `each'
/webapps/myapp/releases/20150831173832/app/models/ad_account.rb:1350:in `block in update_ad_set_reports_preset'
/webapps/myapp/releases/20150831173832/app/models/ad_account.rb:1341:in `each'
/webapps/myapp/releases/20150831173832/app/models/ad_account.rb:1341:in `update_ad_set_reports_preset'
/webapps/myapp/releases/20150831173832/app/jobs/fb_backfill_adset_stats_job.rb:12:in `perform'
```

**Comment by mperham** [comment]
All of your worker threads are blocked on postgres operations and I see two gems in the mix: rack-mini-profiler and octopus.

1. Make sure you have connection timeouts configured for your postgres shard connections.
2. Make sure you are running the latest version of each gem.
3. You might try removing one or both of these gems if possible and see if the system becomes more stable.

**Comment by pratik60** [comment]
Hmmm....No timeout set in database.yml or shards.yml. I will update this by the end of day. 

I was thinking its an external api call, but was unable to make sense of the TTIN output. Thanks to both of you for getting back so quick.

**Comment by pratik60** [comment]
Looks a lot better for me now...Closing this. Thanks
