### ISSUE TITLE
Sidekiq "getaddrinfo: Name or service not known" error

### ISSUE THREAD

**Issue by madca03** [mperham/sidekiq#2536]
Hi. I'm having this error whenever I try to start sidekiq using "bundle exec sidekiq". Could someone help me determine the solution to this problem?

```
getaddrinfo: Name or service not known
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `open'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/net/http.rb:878:in `connect'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/net/http.rb:852:in `start'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/net/http.rb:1374:in `request'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:190:in `call'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:190:in `perform_request'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/client.rb:119:in `perform_request'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/bulk.rb:80:in `bulk'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/elasticsearch-model-0.1.7/lib/elasticsearch/model/importing.rb:120:in `block in import'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/elasticsearch-model-0.1.7/lib/elasticsearch/model/adapters/active_record.rb:96:in `block in __find_in_batches'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:9:in `find_in_batches'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/elasticsearch-model-0.1.7/lib/elasticsearch/model/proxy.rb:80:in `method_missing'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/elasticsearch-model-0.1.7/lib/elasticsearch/model/adapters/active_record.rb:95:in `__find_in_batches'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/elasticsearch-model-0.1.7/lib/elasticsearch/model/importing.rb:119:in `import'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/elasticsearch-model-0.1.7/lib/elasticsearch/model.rb:115:in `import'
/home/mark/Documents/whatsup/app/models/question.rb:433:in `<top (required)>'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:457:in `load'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:457:in `block in load_file'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:647:in `new_constants_in'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:456:in `load_file'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:354:in `require_or_load'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:317:in `depend_on'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:233:in `require_dependency'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:471:in `each'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:471:in `block in eager_load!'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:469:in `each'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:469:in `eager_load!'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:346:in `eager_load!'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/application/finisher.rb:56:in `each'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/home/mark/Documents/whatsup/config/environment.rb:5:in `<top (required)>'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/cli.rb:241:in `boot_system'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/cli.rb:50:in `run'
/home/mark/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.4.1/bin/sidekiq:8:in `<top (required)>'
/home/mark/.rbenv/versions/2.2.0/bin/sidekiq:23:in `load'
/home/mark/.rbenv/versions/2.2.0/bin/sidekiq:23:in `<main>'
```

**Comment by jonhyman** [comment]
Look at 

```
/home/mark/Documents/whatsup/app/models/question.rb:433:in `<top (required)>'
```

it seems like here your app is querying ElasticSearch, and that my guess is you can't resolve the IP address of the cluster.
