### ISSUE TITLE
stack level too deep when calling worker with Enumerator/invalid argument

### ISSUE THREAD

**Issue by frobichaud** [mperham/sidekiq#2631]
```
MyWorker.perform_async Enumerator.new('random')
```
causes the following stack:
```
SystemStackError: stack level too deep
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:32:in `to_json_with_active_support_encoder'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
... 9313 levels...
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sidekiq-3.5.1/lib/sidekiq/client.rb:179:in `raw_push'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sidekiq-pro-2.1.1/lib/sidekiq/batch/client.rb:36:in `raw_push_with_batch'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sidekiq-pro-2.1.1/lib/sidekiq/pro/push.rb:41:in `push_initial'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sidekiq-pro-2.1.1/lib/sidekiq/pro/push.rb:32:in `raw_push_with_backup'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sidekiq-3.5.1/lib/sidekiq/client.rb:68:in `push'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sidekiq-3.5.1/lib/sidekiq/worker.rb:86:in `client_push'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sidekiq-3.5.1/lib/sidekiq/worker.rb:42:in `perform_async'
	from (irb):63
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/console.rb:110:in `start'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/console.rb:9:in `start'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/frobichaud/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
```

I'm aware my parameter is invalid, but it'd be nice to have some parameter sanitizer protection to avoid the stack level too deep problem.

**Comment by mperham** [comment]
I believe the best practices are clear enough. Simple types only.
