### ISSUE TITLE
Sidekiq 4.0.1 jobs getting stuck on `read_from_socket`

### ISSUE THREAD

**Issue by keithpitt** [mperham/sidekiq#2667]
I deployed `sidekiq-pro v4.0.1` today to production, but had a hiccup with it finishing jobs. When my 4 sidekiq processes came online, they processed around 100 jobs or so, then after that they just got stuck and didn't process anything more. I reverted back to `v3.5.3` and the queue would process again as normal.

I was able to replicate it locally. I just send 10,000 jobs at Sidekiq, ran 4 workers to see what happened, and I got some stuck jobs:

![image](https://cloud.githubusercontent.com/assets/25882/11234003/e64a6d84-8e17-11e5-9792-a59208db9edb.png)

You can see here that there are a few stuck jobs (they usually take like 50ms to run, but here they've been running for a few minutes)

I did a backtrace and I got this:

```
17:10:21 sidekiq.1     | 2015-11-18T06:10:21.671Z 74417 TID-oxex3xon8 WARN: Thread TID-oxexwr3b8
17:10:21 sidekiq.1     | 2015-11-18T06:10:21.672Z 74417 TID-oxex3xon8 WARN: /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:52:in `select'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:52:in `rescue in _read_from_socket'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:48:in `_read_from_socket'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:41:in `gets'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:273:in `read'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:249:in `block in read'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:237:in `io'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:248:in `read'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:113:in `block in call'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:218:in `block (2 levels) in process'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:354:in `ensure_connected'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:208:in `block in process'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:293:in `logging'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:207:in `process'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:113:in `call'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/newrelic-redis-2.0.2/lib/newrelic_redis/instrumentation.rb:36:in `block in call_with_newrelic_trace'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/datastores.rb:111:in `block in wrap'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/datastores.rb:108:in `wrap'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/newrelic-redis-2.0.2/lib/newrelic_redis/instrumentation.rb:35:in `call_with_newrelic_trace'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:196:in `block in call_with_timeout'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:267:in `with_socket_timeout'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:195:in `call_with_timeout'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis.rb:1097:in `block in _bpop'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis.rb:1094:in `_bpop'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis.rb:1139:in `brpop'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:393:in `call_with_namespace'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:290:in `method_missing'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/fetch.rb:35:in `block in retrieve_work'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq.rb:84:in `block in redis'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq.rb:81:in `redis'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/fetch.rb:35:in `retrieve_work'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:85:in `get_one'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:95:in `fetch'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:78:in `process_one'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
17:10:21 sidekiq.1     | /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

Is there anything else I can provide to help debug this issue? Thanks!

**Comment by dziulius** [comment]
Sidekiq 4.0 requires more connections, maybe your redis does not provide enough of them?

**Comment by keithpitt** [comment]
I did think of that, but I wasn't sure how to tell if that was the case. How could I tell? When I locally replicated the problem, I install redis via (so I got what ever the defaults were) `brew install redis`

**Comment by dziulius** [comment]
You can check [redis](http://redis.io/topics/clients) website for info. It says that redis 2.6 has 10k clients limit. So it might not be your issue.

**Comment by mperham** [comment]
That backtrace is totally normal: that's a Processor thread blocked on Redis, waiting for a job to process.  Gist the full TTIN output please.

**Comment by keithpitt** [comment]
```

**Comment by keithpitt** [comment]
Such backtrace!

**Comment by keithpitt** [comment]
So the line: `/workers/websocket_publisher_worker.rb` is calling out to `$redis.setnx`(I'm using the same redis database to store some other information), and it looks like it's getting blocked on a redis lock? If it was something in my code, I probably would have expected it to also break in `3.x`?

**Comment by keithpitt** [comment]
I should also mention `$redis` is:

```ruby
$redis = Sidekiq.redis do |namespaced_redis|
  Redis::Namespace.new("", redis: namespaced_redis.redis)
end
```

**Comment by mperham** [comment]
You cannot steal a connection from sidekiq like that. Unsafe. Create your own connection.
