### ISSUE TITLE
4.0.1 error with Airbrake integration

### ISSUE THREAD

**Issue by sauronnikko** [mperham/sidekiq#2671]
Hi. I updated to the latest sidekiq, `4.0.1` and I'm given the following error when trying to run `bundle exec sidekiq`:

```
/ruby-2.2.2@global/gems/bundler-1.9.9/lib/bundler/rubygems_integration.rb:273:in `block in replace_gem': can't activate sidekiq (~> 3.0), already activated sidekiq-4.0.1. Make sure all dependencies are added to Gemfile. (Gem::LoadError)
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/airbrake-4.3.3/lib/airbrake/sidekiq.rb:1:in `<top (required)>'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/akdemia15/Daniel/api-akdemia-2.0/config/initializers/airbrake.rb:1:in `<top (required)>'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/engine.rb:651:in `load_config_initializer'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/engine.rb:615:in `each'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/akdemia15/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/akdemia15/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/akdemia15/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/akdemia15/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/akdemia15/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/akdemia15/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /Users/akdemia15/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /Users/akdemia15/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/akdemia15/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/akdemia15/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/akdemia15/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/akdemia15/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/akdemia15/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `public_send'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `method_missing'
	from /Users/akdemia15/Daniel/api-akdemia-2.0/config/environment.rb:5:in `<top (required)>'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/sidekiq-4.0.1/lib/sidekiq/cli.rb:236:in `boot_system'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/sidekiq-4.0.1/lib/sidekiq/cli.rb:49:in `run'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/gems/sidekiq-4.0.1/bin/sidekiq:13:in `<top (required)>'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/bin/sidekiq:23:in `load'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/bin/sidekiq:23:in `<main>'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/akdemia15/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

It seems the error is caused by the Airbrake integration. The line that is giving the error is this one:

```
require 'airbrake/sidekiq'
```

My airbrake version is gem ```4.3.3```. Is this a sidekiq issue or an airbrake issue? With sidekiq ```3.5.3``` I get no errors.

**Comment by mperham** [comment]
https://github.com/airbrake/airbrake/blob/master/lib/airbrake/sidekiq.rb#L1
