### ISSUE TITLE
How to prevent sidekiq to establish redis connection on assets:precompile?

### ISSUE THREAD

**Issue by NOX73** [mperham/sidekiq#2673]
I need this because there is no redis when I compile assets.

**Comment by mperham** [comment]
Please give a full backtrace.

**Comment by Andrew8xx8** [comment]
```
Step 23 : RUN RAILS_ASSETS=true RAILS_ENV=production rake assets:precompile
 ---> Running in f81a9fbe3366
I, [2015-11-23T14:36:46.935923 #5]  INFO -- : Celluloid 0.17.2 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
rake aborted!
Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:332:in `rescue in establish_connection'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:318:in `establish_connection'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:94:in `block in connect'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:280:in `with_reconnect'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:93:in `connect'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:351:in `ensure_connected'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:208:in `block in process'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:293:in `logging'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:207:in `process'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:113:in `call'
/usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:1964:in `block in hget'
/usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
/usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
/usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:1963:in `hget'
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:67:in `block in get_schedule'
/usr/local/bundle/gems/sidekiq-3.5.3/lib/sidekiq.rb:84:in `block in redis'
/usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
/usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
/usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/usr/local/bundle/gems/sidekiq-3.5.3/lib/sidekiq.rb:81:in `redis'
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:67:in `get_schedule'
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:98:in `set_schedule'
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:42:in `block in schedule='
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:41:in `each'
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:41:in `schedule='
/apps/zabava-backend/config/initializers/sidekiq.rb:13:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/engine.rb:615:in `each'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/apps/zabava-backend/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/bundle/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:6379
/usr/local/bundle/gems/redis-3.2.2/lib/redis/connection/ruby.rb:129:in `connect_nonblock'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/connection/ruby.rb:129:in `rescue in connect_addrinfo'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/connection/ruby.rb:121:in `connect_addrinfo'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/connection/ruby.rb:162:in `block in connect'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/connection/ruby.rb:160:in `each'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/connection/ruby.rb:160:in `each_with_index'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/connection/ruby.rb:160:in `connect'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/connection/ruby.rb:211:in `connect'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:323:in `establish_connection'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:94:in `block in connect'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:280:in `with_reconnect'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:93:in `connect'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:351:in `ensure_connected'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:208:in `block in process'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:293:in `logging'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:207:in `process'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:113:in `call'
/usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:1964:in `block in hget'
/usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
/usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
/usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:1963:in `hget'
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:67:in `block in get_schedule'
/usr/local/bundle/gems/sidekiq-3.5.3/lib/sidekiq.rb:84:in `block in redis'
/usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
/usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
/usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/usr/local/bundle/gems/sidekiq-3.5.3/lib/sidekiq.rb:81:in `redis'
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:67:in `get_schedule'
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:98:in `set_schedule'
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:42:in `block in schedule='
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:41:in `each'
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:41:in `schedule='
/apps/zabava-backend/config/initializers/sidekiq.rb:13:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/engine.rb:615:in `each'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/apps/zabava-backend/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/bundle/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
IO::EINPROGRESSWaitWritable: Operation now in progress - connect(2) would block
/usr/local/bundle/gems/redis-3.2.2/lib/redis/connection/ruby.rb:122:in `connect_nonblock'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/connection/ruby.rb:122:in `connect_addrinfo'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/connection/ruby.rb:162:in `block in connect'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/connection/ruby.rb:160:in `each'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/connection/ruby.rb:160:in `each_with_index'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/connection/ruby.rb:160:in `connect'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/connection/ruby.rb:211:in `connect'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:323:in `establish_connection'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:94:in `block in connect'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:280:in `with_reconnect'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:93:in `connect'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:351:in `ensure_connected'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:208:in `block in process'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:293:in `logging'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:207:in `process'
/usr/local/bundle/gems/redis-3.2.2/lib/redis/client.rb:113:in `call'
/usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:1964:in `block in hget'
/usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
/usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
/usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:1963:in `hget'
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:67:in `block in get_schedule'
/usr/local/bundle/gems/sidekiq-3.5.3/lib/sidekiq.rb:84:in `block in redis'
/usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
/usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
/usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/usr/local/bundle/gems/sidekiq-3.5.3/lib/sidekiq.rb:81:in `redis'
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:67:in `get_schedule'
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:98:in `set_schedule'
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:42:in `block in schedule='
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:41:in `each'
/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:41:in `schedule='
/apps/zabava-backend/config/initializers/sidekiq.rb:13:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/engine.rb:615:in `each'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/apps/zabava-backend/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/usr/local/bundle/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/bundle/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
Tasks: TOP => environment
(See full trace by running task with --trace)
Service 'web' failed to build: The command '/bin/sh -c RAILS_ASSETS=true RAILS_ENV=production rake assets:precompile' returned a non-zero code: 1
```

**Comment by mperham** [comment]
Bug in sidekiq-scheduler-1.2.4

/usr/local/bundle/gems/sidekiq-scheduler-1.2.4/lib/sidekiq-scheduler/schedule.rb:67:in `block in get_schedule'
