### ISSUE TITLE
error with ActiveJob

### ISSUE THREAD

**Issue by pacuna** [mperham/sidekiq#2696]
This is pretty weird.
My initializer:

```
if Rails.env.production?
  redis_url = ENV['REDIS_PORT_6379_TCP_ADDR']
else
  redis_url = 'ket_redis_1'
end

Sidekiq.configure_server do |config|
  config.redis = { url: "redis://#{redis_url}:6379/12" }
end

Sidekiq.configure_client do |config|
  config.redis = { url: "redis://#{redis_url}:6379/12" }
end

```
I have redis and the app running inside of containers.

Now, when I start sidekiq everything's ok:

```
$ bundle exec sidekiq -e production
2015-12-07T14:40:18.289Z 312 TID-bt84s INFO: Booting Sidekiq 4.0.1 with redis options {:url=>"redis://172.17.0.123:6379/12"}
2015-12-07T14:40:18.643Z 312 TID-bt84s INFO: Running in ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux-gnu]
2015-12-07T14:40:18.643Z 312 TID-bt84s INFO: See LICENSE and the LGPL-3.0 for licensing details.
2015-12-07T14:40:18.643Z 312 TID-bt84s INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2015-12-07T14:40:18.645Z 312 TID-bt84s INFO: Starting processing, hit Ctrl-C to stop
```

But then when I try to run some Job (or visit the webUI url) I'm getting this error:

```
App 263 stderr: Started GET "/sidekiq" for 186.103.140.234 at 2015-12-07 14:39:32 +0000
App 263 stderr: 2015-12-07 14:39:32 - Redis::CannotConnectError - Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED):
App 263 stderr: 	/var/lib/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:332:in `rescue in establish_connection'
App 263 stderr: 	/var/lib/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:318:in `establish_connection'
App 263 stderr: 	/var/lib/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:94:in `block in connect'
App 263 stderr: 	/var/lib/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:280:in `with_reconnect'
App 263 stderr: 	/var/lib/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:93:in `connect'
App 263 stderr: 	/var/lib/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:351:in `ensure_connected'
App 263 stderr: 	/var/lib/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:208:in `block in process'
App 263 stderr: 	/var/lib/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:293:in `logging'
App 263 stderr: 	/var/lib/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:207:in `process'
App 263 stderr: 	/var/lib/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:113:in `call'
```

In my config/application.rb I have this line:

```
config.active_job.queue_adapter = :sidekiq
```

What could it be?
Thanks.

**Comment by pacuna** [comment]
I think it was an issue with the container non being initialised in time. I created an Elasticache cluster and everything worked ok.
