### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass - retry_jobs.rb:99 attempt_retry

### ISSUE THREAD

**Issue by Nowaker** [mperham/sidekiq#2707]
While this is my fault (custom Exception class and having forgotten about `message` method), Sidekiq should be extremely cautious. Any exception in `attempt_retry` shouldn't prevent the job from being scheduled again. I guess. :-)

Sidekiq 3.4.2.

```
[sidekiq] 2015-12-10T19:39:40.348Z 25586 TID-19yc7c MachineCreateJob JID-469afc0cf18866bd884e2cd6 INFO: fail: 1.506 sec
[sidekiq] 2015-12-10T19:39:40.349Z 25586 TID-19yc7c WARN: {"class"=>"MachineCreateJob", "args"=>[116, 96, nil], "retry"=>0, "queue"=>"default", "jid"=>"469afc0cf18866bd884e2cd6", "created_at"=>1449776378.8404996, "enqueued_at"=>1449776378.840913}
[sidekiq] 2015-12-10T19:39:40.349Z 25586 TID-19yc7c WARN: NoMethodError: undefined method `[]' for nil:NilClass
[sidekiq] 2015-12-10T19:39:40.349Z 25586 TID-19yc7c WARN: /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.4.2/lib/sidekiq/middleware/server/retry_jobs.rb:99:in `attempt_retry'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.4.2/lib/sidekiq/middleware/server/retry_jobs.rb:83:in `rescue in call'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.4.2/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.4.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.4.2/lib/sidekiq/middleware/server/logging.rb:15:in `block in call'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.4.2/lib/sidekiq/logging.rb:30:in `with_context'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.4.2/lib/sidekiq/middleware/server/logging.rb:11:in `call'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.4.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.4.2/lib/sidekiq/middleware/chain.rb:132:in `call'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.4.2/lib/sidekiq/middleware/chain.rb:132:in `invoke'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.4.2/lib/sidekiq/processor.rb:51:in `block in process'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.4.2/lib/sidekiq/processor.rb:98:in `stats'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.4.2/lib/sidekiq/processor.rb:50:in `process'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
[sidekiq] /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

**Comment by mperham** [comment]
Can you show me your exception class so I can see what you mean?  What would you suggest I do?

**Comment by mikegee** [comment]
I think it's this line that truncates huge error messages: 

https://github.com/mperham/sidekiq/blob/3_x/lib/sidekiq/middleware/server/retry_jobs.rb#L99

```ruby
m = exception.message[0..10_000]
```

The particular error encountered by @Nowaker would be solved by a `#to_s`:

```ruby
m = exception.message.to_s[0..10_000]
```

It would be nice to see that custom exception to be sure, though.

**Comment by Nowaker** [comment]
Thank y'all. I'll recreate this custom exception class (I never committed it as it was work in progress).
