### ISSUE TITLE
ConnectionPool::connected with lock

### ISSUE THREAD

**Issue by zhouguangming** [mperham/sidekiq#2731]
I get this when my Sidekiq jobs:

```ruby
2015-12-22T02:25:59.331Z 32013 TID-ork5rj81o WARN: Thread TID-ork74yol4 
2015-12-22T02:25:59.331Z 32013 TID-ork5rj81o WARN: /usr/localb/ruby/2.0.0/monitor.rb:185:in `lock'
/usr/localb/ruby/2.0.0/monitor.rb:185:in `mon_enter'
/usr/localb/ruby/2.0.0/monitor.rb:209:in `mon_synchronize'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/connection_handling.rb:113:in `retrieve_connection'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/connection_handling.rb:87:in `connection'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/relation/merger.rb:121:in `merge_multi_values'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/relation/merger.rb:76:in `merge'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/relation/spawn_methods.rb:44:in `merge!'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/relation/spawn_methods.rb:33:in `merge'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/scoping/default.rb:103:in `block (2 levels) in build_default_scope'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/scoping/default.rb:102:in `each'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/scoping/default.rb:102:in `inject'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/scoping/default.rb:102:in `block in build_default_scope'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/scoping/default.rb:125:in `evaluate_default_scope'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/scoping/default.rb:101:in `build_default_scope'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/scoping/named.rb:33:in `default_scoped'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/scoping/named.rb:28:in `all'
ar/apps/gitlabdndle/ruby/2.0.0/gems/activerecord-4.1.12b/active_record/querying.rb:3:in `find'
ar/apps/gitlab/releases/20150826054122/app/workers/repository_archive_worker.rb:9:in `perform'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/processor.rb:75:in `execute_job'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/processor.rb:52:in `block (2 levels) in process'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/middlewareain.rb:127:in `block in invoke'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidetiq-0.6.3b/sidetiq/middleware/history.rb:8:in `call'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/middlewareain.rb:129:in `block in invoke'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/middlewarerver/active_record.rb:6:in `call'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/middlewareain.rb:129:in `block in invoke'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/middlewarerver/retry_jobs.rb:74:in `call'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/middlewareain.rb:129:in `block in invoke'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/middlewarerver/logging.rb:15:in `block in call'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/logging.rb:30:in `with_context'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/middlewarerver/logging.rb:11:in `call'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/middlewareain.rb:129:in `block in invoke'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/middlewareain.rb:132:in `call'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/middlewareain.rb:132:in `invoke'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/processor.rb:51:in `block in process'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/processor.rb:98:in `stats'
ar/apps/gitlabdndle/ruby/2.0.0/gems/sidekiq-3.4.1b/sidekiq/processor.rb:50:in `process'
ar/apps/gitlabdndle/ruby/2.0.0/gems/celluloid-0.16.0b/celluloid/calls.rb:26:in `public_send'
ar/apps/gitlabdndle/ruby/2.0.0/gems/celluloid-0.16.0b/celluloid/calls.rb:26:in `dispatch'
```
Here is my database.yml configuration:

```ruby
production:
  adapter: mysql2
  encoding: utf8
  host: host
  port: port
  database: database
  reconnect: false
  pool: 128
  username: username
  password: password
```
Gemfile.lock
```ruby
   ...
    activerecord (4.1.12)
      activemodel (= 4.1.12)
      activesupport (= 4.1.12)
      arel (~> 5.0.0)
   ...
   sidekiq (3.4.1)
      celluloid (~> 0.16.0)
      connection_pool (>= 2.1.1)
      json
      redis (>= 3.0.6)
      redis-namespace (>= 1.3.1)
   ...
```
It happened very often in Sidekiq job but never happend in Rails process.

**Comment by mperham** [comment]
That's the AR pool; it has nothing to do with Sidekiq.  There's something in your codebase that is not handling connections properly when threaded.

**Comment by zhouguangming** [comment]
So, Should I submit this issue to Rails?

**Comment by mperham** [comment]
No, the bug is in your app code.

**Comment by zhouguangming** [comment]
What condition would cause this problem?

**Comment by mikegee** [comment]
We would have to see your app code to diagnose. StackOverflow is a better forum than here, though.
