### ISSUE TITLE
redis pub/sub error when a batched job fails with an ActiveRecord connection pool error

### ISSUE THREAD

**Issue by kreynolds** [mperham/sidekiq#2732]
The surrounding code is pretty normal, but the error was an ActiveRecord connection pool error where it timed out waiting for a connection for 5 seconds.
Once that happened, something caused a cascading error in the retry mechanism which resulted in the sidekiq worker crashing. When this happens (as you can probably guess), the job is lost. Also potentially of note, this error was raised inside a separate thread inside the worker with abort_on_exception set to true.

Here is the trace:

```
could not obtain a database connection within 5.000 seconds (waited 5.001 seconds)
2015-12-22T18:11:16.704Z 53715 TID-ouj6nou5o Worker JID-4cd6132afbb420ff9e5fe63e BID-P4BgzVtL9D9aWQ INFO: fail: 69.912 sec
2015-12-22T18:11:16.705Z 53715 TID-ouj6nou5o WARN: {"class"=>"Worker", "args"=>[2578214957], "retry"=>true, "queue"=>"default", "jid"=>"4cd6132afbb420ff9e5fe63e", "created_at"=>1450804638.977232, "bid"=>"P4BgzVtL9D9aWQ", "enqueued_at"=>1450804638.97875, "error_message"=>"ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context", "error_class"=>"Redis::CommandError", "failed_at"=>1450807876.7043781, "retry_count"=>0}
2015-12-22T18:11:16.705Z 53715 TID-ouj6nou5o WARN: Redis::CommandError: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context
2015-12-22T18:11:16.705Z 53715 TID-ouj6nou5o WARN: /Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:114:in `call'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis.rb:1489:in `block in zadd'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis.rb:1483:in `zadd'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:393:in `call_with_namespace'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:290:in `method_missing'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:129:in `block in attempt_retry'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq.rb:84:in `block in redis'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq.rb:81:in `redis'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:128:in `attempt_retry'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:83:in `rescue in call'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
2015-12-22T18:11:16.705Z 53715 TID-ouj6nou5o WARN: {:context=>"processor"}
2015-12-22T18:11:16.705Z 53715 TID-ouj6nou5o WARN: ThreadError: can't alloc thread
2015-12-22T18:11:16.705Z 53715 TID-ouj6nou5o WARN: /Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:23:in `new'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:23:in `safe_thread'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:59:in `start'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/manager.rb:92:in `block in processor_died'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/manager.rb:87:in `synchronize'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/manager.rb:87:in `processor_died'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:73:in `rescue in run'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:65:in `run'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
/Users/kreynolds/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by mperham** [comment]
`ThreadError: can't alloc thread` is a scary error.  That generally means you're out of some resource, possibly memory.

`ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context` implies that the original error occurred while your worker was doing some Redis pubsub stuff, possibly incorrectly blocking the worker thread for a long time, which can lead to connection pool exhaustion.

**Comment by kreynolds** [comment]
There was no resource exhaustion other than the ActiveRecord pool was out of connections and it wanted another one, and it looks to me like a redis connection set up as a subscriber was being used to send normal redis commands, which is pretty far away from an ActiveRecord error. I will try to make a simple worker that replicates this explosion.

**Comment by mperham** [comment]
That pubsub error can also occur if you are sharing a global Redis connection or using Sidekiq's connection pool incorrectly, e.g.

```ruby
# extremely unsafe, do not do this
conn = Sidekiq.redis { |c| c }
conn.lpush ...
```

**Comment by kreynolds** [comment]
Hrm, I do make use of the sidekiq connection pool but completely inside the enclosure. For example:

```
      Sidekiq.redis { |r|
        r.pipelined do
          r.redis.hmset "batch_progress:#{parent.bid}", 'job_status', 'pending'
          r.redis.expire "batch_progress:#{parent.bid}", 86400*7
        end
      }
```

This is safe usage yes?

**Comment by mperham** [comment]
Yes, that's perfectly safe.

**Comment by kreynolds** [comment]
While working this up into an example, I think I discovered the problem which is obvious in retrospect. `abort_on_exception` is true for that thread and it shouldn't be. With that changed, the failures behave as one would expect.
