### ISSUE TITLE
sidekiq accidentally died

### ISSUE THREAD

**Issue by sandish2222** [mperham/sidekiq#2739]
We use sidekiq for gitlab community  Edition.  
  
And accidentally  sidekiq died for some times.   
Sidekiq version is:
```
gem 'sidekiq', '3.3.0'
gem 'sidetiq', '~> 0.6.3'
```

exception log:
```
2015-12-10T14:22:02.304Z 98694 TID-ouvaee8k4 WARN: Sidekiq died due to the following error, cannot recover, process exiting
2015-12-10T14:22:02.305Z 98694 TID-ouv8rg3kg INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125572790960 shutting down ...
2015-12-10T14:22:03.131Z 98694 TID-ouvaefoac Sidekiq::Extensions::DelayedMailer JID-0327c69d77d8037b7ec81bb0 INFO: done: 67.276 sec
2015-12-10T14:22:03.330Z 98694 TID-ouv99be84 INFO: [Sidetiq] Sidetiq::Actor::Clock id: 70113105530980 initialize
2015-12-10T14:22:03.530Z 98694 TID-ouv996xn0 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119252050960 initialize
2015-12-10T14:22:03.627Z 98694 TID-ouv99aycg INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120643447680 initialize
2015-12-10T14:22:03.733Z 98694 TID-ouv8smea8 Sidekiq::Extensions::DelayedMailer JID-2947f66f81b63abecf83fe8d INFO: done: 67.43 sec
2015-12-10T14:22:04.032Z 98694 TID-ouv996rhc INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125570954760 initialize
2015-12-10T14:22:04.229Z 98694 TID-ouv8t4nmo Sidekiq::Extensions::DelayedMailer JID-c05824794f32f503226a33fa INFO: done: 68.882 sec
2015-12-10T14:22:04.530Z 98694 TID-ouv996mz4 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70116259390800 initialize
2015-12-10T14:22:04.653Z 98694 TID-ouv99areg INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119275055920 initialize
2015-12-10T14:22:05.040Z 98694 TID-ouv996i9o INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119253587800 initialize
2015-12-10T14:22:05.231Z 98694 TID-ouv8r4ryk Sidekiq::Extensions::DelayedMailer JID-b9d5bad78e70eb6d9b91ba92 INFO: done: 69.027 sec
2015-12-10T14:22:05.373Z 98694 TID-ouvaei8hs Sidekiq::Extensions::DelayedMailer JID-5d626a3ed0049b85507b683a INFO: done: 53.858 sec
2015-12-10T14:22:05.745Z 98694 TID-ouv996dn0 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119589058200 initialize
2015-12-10T14:22:06.973Z 98694 TID-ouv8lm00o INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120687170200 initialize
2015-12-10T14:22:06.975Z 98694 TID-ouv8sy6bs Sidekiq::Extensions::DelayedMailer JID-427576d60d162aafa351fe5f INFO: done: 42.654 sec
2015-12-10T14:22:07.735Z 98694 TID-ouv8maqa4 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125674383640 initialize
2015-12-10T14:22:08.036Z 98694 TID-ouvaef9zc Sidekiq::Extensions::DelayedMailer JID-585cb8b369d4f9dac4a0b1e7 INFO: done: 41.624 sec
2015-12-10T14:22:08.036Z 98694 TID-ouv8ln1bg INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70117488910420 initialize
2015-12-10T14:22:08.635Z 98694 TID-ouv8r5s5c INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119272936300 initialize
2015-12-10T14:22:08.846Z 98694 TID-ouv8qd3yg INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70117493919800 initialize
2015-12-10T14:22:09.035Z 98694 TID-ouvaeh2pw Sidekiq::Extensions::DelayedMailer JID-ec2b370987823226d6a820eb INFO: done: 42.896 sec
2015-12-10T14:22:09.305Z 98694 TID-ouv8r1c48 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70117485993040 initialize
2015-12-10T14:22:09.536Z 98694 TID-ouv8q9tnk INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70117485499160 initialize
2015-12-10T14:22:09.536Z 98694 TID-ouv8qdhv0 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125564237240 initialize
2015-12-10T14:22:09.935Z 98694 TID-ouv8mzfr8 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120985818420 initialize
2015-12-10T14:22:10.238Z 98694 TID-ouv8qyk2k INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120285589240 initialize
2015-12-10T14:22:10.538Z 98694 TID-ouv8qecq4 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119279897500 initialize
2015-12-10T14:22:11.139Z 98694 TID-ouv8qz8bc INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120643453780 initialize
2015-12-10T14:22:11.448Z 98694 TID-ouv8pap0c INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125572535500 initialize
2015-12-10T14:22:11.645Z 98694 TID-ouv8oryh0 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125593240260 initialize
2015-12-10T14:22:11.645Z 98694 TID-ouv8p6218 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120175682840 initialize
2015-12-10T14:22:26.467Z 98694 TID-ouvaeg4ew Sidekiq::Extensions::DelayedMailer JID-57eaaca02b4b5ac834c67675 INFO: done: 60.061 sec
2015-12-10T14:22:33.753Z 98694 TID-ouv8t1y9o Sidekiq::Extensions::DelayedMailer JID-bff9b8f17ab9c0d5f20e2e97 INFO: done: 65.156 sec
2015-12-10T14:22:55.943Z 98694 TID-ouv8qypac INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70113120945700 initialize
2015-12-10T14:24:06.680Z 98694 TID-ouv8rgmzw MergeWorker JID-fc9a7b93dcb27959fe77ca2f INFO: done: 252.16 sec
2015-12-10T14:24:53.725Z 98694 TID-ouv8shp48 WARN: /usr/local/lib/ruby/2.1.0/net/protocol.rb:211:in `write'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:211:in `write0'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:270:in `block in write_message_0'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:330:in `block in each_crlf_line'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:340:in `block in buffer_filling'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:338:in `step'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:338:in `buffer_filling'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:328:in `each_crlf_line'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:269:in `write_message_0'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:284:in `block (2 levels) in write_message'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:317:in `using_each_crlf_line'
...skipping...
2015-12-10T14:22:02.304Z 98694 TID-ouvaee8k4 WARN: Sidekiq died due to the following error, cannot recover, process exiting
2015-12-10T14:22:02.305Z 98694 TID-ouv8rg3kg INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125572790960 shutting down ...
2015-12-10T14:22:03.131Z 98694 TID-ouvaefoac Sidekiq::Extensions::DelayedMailer JID-0327c69d77d8037b7ec81bb0 INFO: done: 67.276 sec
2015-12-10T14:22:03.330Z 98694 TID-ouv99be84 INFO: [Sidetiq] Sidetiq::Actor::Clock id: 70113105530980 initialize
2015-12-10T14:22:03.530Z 98694 TID-ouv996xn0 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119252050960 initialize
2015-12-10T14:22:03.627Z 98694 TID-ouv99aycg INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120643447680 initialize
2015-12-10T14:22:03.733Z 98694 TID-ouv8smea8 Sidekiq::Extensions::DelayedMailer JID-2947f66f81b63abecf83fe8d INFO: done: 67.43 sec
2015-12-10T14:22:04.032Z 98694 TID-ouv996rhc INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125570954760 initialize
2015-12-10T14:22:04.229Z 98694 TID-ouv8t4nmo Sidekiq::Extensions::DelayedMailer JID-c05824794f32f503226a33fa INFO: done: 68.882 sec
2015-12-10T14:22:04.530Z 98694 TID-ouv996mz4 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70116259390800 initialize
2015-12-10T14:22:04.653Z 98694 TID-ouv99areg INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119275055920 initialize
2015-12-10T14:22:05.040Z 98694 TID-ouv996i9o INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119253587800 initialize
2015-12-10T14:22:05.231Z 98694 TID-ouv8r4ryk Sidekiq::Extensions::DelayedMailer JID-b9d5bad78e70eb6d9b91ba92 INFO: done: 69.027 sec
2015-12-10T14:22:05.373Z 98694 TID-ouvaei8hs Sidekiq::Extensions::DelayedMailer JID-5d626a3ed0049b85507b683a INFO: done: 53.858 sec
2015-12-10T14:22:05.745Z 98694 TID-ouv996dn0 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119589058200 initialize
2015-12-10T14:22:06.973Z 98694 TID-ouv8lm00o INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120687170200 initialize
2015-12-10T14:22:06.975Z 98694 TID-ouv8sy6bs Sidekiq::Extensions::DelayedMailer JID-427576d60d162aafa351fe5f INFO: done: 42.654 sec
2015-12-10T14:22:07.735Z 98694 TID-ouv8maqa4 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125674383640 initialize
2015-12-10T14:22:08.036Z 98694 TID-ouvaef9zc Sidekiq::Extensions::DelayedMailer JID-585cb8b369d4f9dac4a0b1e7 INFO: done: 41.624 sec
2015-12-10T14:22:08.036Z 98694 TID-ouv8ln1bg INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70117488910420 initialize
2015-12-10T14:22:08.635Z 98694 TID-ouv8r5s5c INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119272936300 initialize
2015-12-10T14:22:08.846Z 98694 TID-ouv8qd3yg INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70117493919800 initialize
2015-12-10T14:22:09.035Z 98694 TID-ouvaeh2pw Sidekiq::Extensions::DelayedMailer JID-ec2b370987823226d6a820eb INFO: done: 42.896 sec
2015-12-10T14:22:09.305Z 98694 TID-ouv8r1c48 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70117485993040 initialize
2015-12-10T14:22:09.536Z 98694 TID-ouv8q9tnk INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70117485499160 initialize
2015-12-10T14:22:09.536Z 98694 TID-ouv8qdhv0 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125564237240 initialize
2015-12-10T14:22:09.935Z 98694 TID-ouv8mzfr8 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120985818420 initialize
2015-12-10T14:22:10.238Z 98694 TID-ouv8qyk2k INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120285589240 initialize
2015-12-10T14:22:10.538Z 98694 TID-ouv8qecq4 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119279897500 initialize
2015-12-10T14:22:11.139Z 98694 TID-ouv8qz8bc INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120643453780 initialize
2015-12-10T14:22:11.448Z 98694 TID-ouv8pap0c INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125572535500 initialize
2015-12-10T14:22:11.645Z 98694 TID-ouv8oryh0 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125593240260 initialize
2015-12-10T14:22:11.645Z 98694 TID-ouv8p6218 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120175682840 initialize
2015-12-10T14:22:26.467Z 98694 TID-ouvaeg4ew Sidekiq::Extensions::DelayedMailer JID-57eaaca02b4b5ac834c67675 INFO: done: 60.061 sec
2015-12-10T14:22:33.753Z 98694 TID-ouv8t1y9o Sidekiq::Extensions::DelayedMailer JID-bff9b8f17ab9c0d5f20e2e97 INFO: done: 65.156 sec
2015-12-10T14:22:55.943Z 98694 TID-ouv8qypac INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70113120945700 initialize
2015-12-10T14:24:06.680Z 98694 TID-ouv8rgmzw MergeWorker JID-fc9a7b93dcb27959fe77ca2f INFO: done: 252.16 sec
2015-12-10T14:24:53.725Z 98694 TID-ouv8shp48 WARN: /usr/local/lib/ruby/2.1.0/net/protocol.rb:211:in `write'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:211:in `write0'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:270:in `block in write_message_0'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:330:in `block in each_crlf_line'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:340:in `block in buffer_filling'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:338:in `step'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:338:in `buffer_filling'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:328:in `each_crlf_line'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:269:in `write_message_0'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:284:in `block (2 levels) in write_message'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:317:in `using_each_crlf_line'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:283:in `block in write_message'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:202:in `writing'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:282:in `write_message'
/usr/local/lib/ruby/2.1.0/net/smtp.rb:905:in `block in data'
/usr/local/lib/ruby/2.1.0/net/smtp.rb:948:in `critical'
/usr/local/lib/ruby/2.1.0/net/smtp.rb:902:in `data'
/usr/local/lib/ruby/2.1.0/net/smtp.rb:663:in `block in send_message'
/usr/local/lib/ruby/2.1.0/net/smtp.rb:858:in `rcptto_list'
/usr/local/lib/ruby/2.1.0/net/smtp.rb:663:in `send_message'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:113:in `block in deliver!'
/usr/local/lib/ruby/2.1.0/net/smtp.rb:521:in `start'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `block in deliver'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.12/lib/action_mailer/base.rb:527:in `block in deliver_mail'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/notifications.rb:159:in `block in instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/notifications.rb:159:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.12/lib/action_mailer/base.rb:525:in `deliver_mail'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `deliver'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/extensions/action_mailer.rb:32:in `deliver'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/extensions/action_mailer.rb:20:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:75:in `execute_job'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidetiq-0.6.3/lib/sidetiq/middleware/history.rb:8:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/logging.rb:22:in `with_context'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:51:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:98:in `stats'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:50:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
2015-12-10T14:24:53.850Z 98694 TID-ouvaee8k4 WARN: linking timeout of 5 seconds exceeded
2015-12-10T14:24:54.944Z 98694 TID-ouv996xn0 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119252050960 shutting down ...
2015-12-10T14:24:55.338Z 98694 TID-ouv99aycg INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120643447680 shutting down ...
2015-12-10T14:24:55.856Z 98694 TID-ouv996rhc INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125570954760 shutting down ...
2015-12-10T14:24:56.676Z 98694 TID-ouv996mz4 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70116259390800 shutting down ...
2015-12-10T14:24:57.655Z 98694 TID-ouv99areg INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119275055920 shutting down ...
2015-12-10T14:24:58.440Z 98694 TID-ouv996i9o INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119253587800 shutting down ...
2015-12-10T14:24:59.240Z 98694 TID-ouv996dn0 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119589058200 shutting down ...
2015-12-10T14:24:59.641Z 98694 TID-ouv8lm00o INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120687170200 shutting down ...
2015-12-10T14:25:00.341Z 98694 TID-ouv8maqa4 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125674383640 shutting down ...
2015-12-10T14:25:01.345Z 98694 TID-ouv8ln1bg INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70117488910420 shutting down ...
2015-12-10T14:25:01.560Z 98694 TID-ouv8r5s5c INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119272936300 shutting down ...
2015-12-10T14:25:01.943Z 98694 TID-ouv8qd3yg INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70117493919800 shutting down ...
2015-12-10T14:25:02.445Z 98694 TID-ouv8r1c48 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70117485993040 shutting down ...
2015-12-10T14:25:02.645Z 98694 TID-ouv8q9tnk INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70117485499160 shutting down ...
2015-12-10T14:25:02.853Z 98694 TID-ouv8qdhv0 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125564237240 shutting down ...
2015-12-10T14:25:03.445Z 98694 TID-ouv8mzfr8 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120985818420 shutting down ...
2015-12-10T14:25:03.745Z 98694 TID-ouv8qyk2k INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120285589240 shutting down ...
2015-12-10T14:25:04.048Z 98694 TID-ouv8qecq4 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119279897500 shutting down ...
2015-12-10T14:25:04.446Z 98694 TID-ouv8qz8bc INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120643453780 shutting down ...
2015-12-10T14:25:04.847Z 98694 TID-ouv8pap0c INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125572535500 shutting down ...
2015-12-10T14:25:05.161Z 98694 TID-ouv8oryh0 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70125593240260 shutting down ...
2015-12-10T14:25:05.754Z 98694 TID-ouv8p6218 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70120175682840 shutting down ...
2015-12-10T14:25:26.477Z 98694 TID-ouv8qypac INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70113120945700 shutting down ...
2015-12-10T14:25:31.383Z 98694 TID-ouv99be84 INFO: [Sidetiq] Sidetiq::Actor::Clock id: 70113105530980 shutting down ...
2015-12-10T14:25:31.679Z 98694 TID-ouvaee8k4 WARN: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:206:in `block in linking_re
quest'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:107:in `exclusive'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid.rb:414:in `exclusive'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:177:in `linking_request'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:57:in `monitor'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:68:in `link'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid.rb:179:in `new_link'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/manager.rb:101:in `block in processor_died'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/util.rb:15:in `watchdog'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/manager.rb:95:in `processor_died'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:15:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
2015-12-10T14:25:57.457Z 98694 TID-ouv8qdvuw INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70119084796600 shutting down ...
2015-12-10T22:05:42.489Z 111781 TID-orbhypmb4 INFO: [Sidetiq] Sidetiq v0.6.3 - Copyright (c) 2012-2013, Tobias Svensson <tob@tobiassvensson.co.uk>
2015-12-10T22:05:42.489Z 111781 TID-orbhypmb4 INFO: [Sidetiq] Sidetiq is covered by the 3-clause BSD license.
2015-12-10T22:05:42.489Z 111781 TID-orbhypmb4 INFO: [Sidetiq] See LICENSE and http://opensource.org/licenses/BSD-3-Clause for licensing details.
```

**Comment by mperham** [comment]
This is a Sidetiq problem, not a Sidekiq bug.

**Comment by mperham** [comment]
https://github.com/tobiassvn/sidetiq/issues/48

**Comment by sandish2222** [comment]
@mperham thanks
