### ISSUE TITLE
Ruby 2.3.0 segfaults when running Sidekiq

### ISSUE THREAD

**Issue by peteygao** [mperham/sidekiq#2749]
Let me preface this by saying that I've been able to reproduce this on 2 machines (one running Mac OSX Yosemite, and the second running CentOS 7). What little evidence I gathered seems to point towards Sidekiq triggering some sort of bug in Ruby in my particular setup (when I run the Rails app _without_ running the Sidekiq workers, things are fine).

That said, I'm also well aware that the vast majority of people running Sidekiq with 2.3.0 aren't having any problems (including my coworkers whom I showed this problem to).

I'll provide stack traces for both machines:
### CentOS Box
```
$ uname -a
Linux centos7 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274: [BUG] Segmentation fault at 0x00000000000088
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0024 p:---- s:0085 e:000084 CFUNC  :require
c:0023 p:0012 s:0081 e:000080 BLOCK  /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274
c:0022 p:0059 s:0079 e:000078 METHOD /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240
c:0021 p:0017 s:0074 e:000073 METHOD /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274 [FINISH]
c:0020 p:0490 s:0069 e:000067 CLASS  /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.4/lib/active_record/base.rb:306
c:0019 p:0011 s:0066 e:000065 CLASS  /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.4/lib/active_record/base.rb:269
c:0018 p:0225 s:0064 e:000063 TOP    /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.4/lib/active_record/base.rb:26 [FINISH]
c:0017 p:---- s:0062 e:000061 CFUNC  :require
c:0016 p:0014 s:0060 e:000059 TOP    /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-import-0.7.0/lib/activerecord-import.rb:1 [FINISH]
c:0015 p:---- s:0058 e:000057 CFUNC  :require
c:0014 p:0042 s:0054 e:000053 BLOCK  /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77 [FINISH]
c:0013 p:---- s:0050 e:000049 CFUNC  :each
c:0012 p:0062 s:0047 e:000046 BLOCK  /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72 [FINISH]
c:0011 p:---- s:0041 e:000040 CFUNC  :each
c:0010 p:0038 s:0038 e:000037 METHOD /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61
c:0009 p:0019 s:0034 e:000033 METHOD /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99
c:0008 p:0102 s:0030 e:000029 TOP    /home/user/everlane/everlane.com/config/application.rb:17 [FINISH]
c:0007 p:---- s:0028 e:000027 CFUNC  :require
c:0006 p:0230 s:0024 e:000023 METHOD /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.1/lib/sidekiq/cli.rb:242
c:0005 p:0008 s:0021 e:000020 METHOD /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.1/lib/sidekiq/cli.rb:50
c:0004 p:0054 s:0014 e:000013 TOP    /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.1/bin/sidekiq:13 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :load
c:0002 p:0147 s:0006 E:000260 EVAL   /home/user/.rbenv/versions/2.3.0/bin/sidekiq:23 [FINISH]
c:0001 p:0000 s:0002 E:002070 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/home/user/.rbenv/versions/2.3.0/bin/sidekiq:23:in `<main>'
/home/user/.rbenv/versions/2.3.0/bin/sidekiq:23:in `load'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.1/bin/sidekiq:13:in `<top (required)>'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.1/lib/sidekiq/cli.rb:50:in `run'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.1/lib/sidekiq/cli.rb:242:in `boot_system'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.1/lib/sidekiq/cli.rb:242:in `require'
/home/user/everlane/everlane.com/config/application.rb:17:in `<top (required)>'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-import-0.7.0/lib/activerecord-import.rb:1:in `<top (required)>'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-import-0.7.0/lib/activerecord-import.rb:1:in `require'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.4/lib/active_record/base.rb:26:in `<top (required)>'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.4/lib/active_record/base.rb:269:in `<module:ActiveRecord>'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.4/lib/active_record/base.rb:306:in `<class:Base>'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
```

### Mac Box
```
$ uname -a
Darwin localuser 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
```
```
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274: [BUG] Segmentation fault at 0x00000100000000
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]

-- Control frame information -----------------------------------------------
c:0025 p:---- s:0094 e:000093 CFUNC  :require
c:0024 p:0012 s:0090 e:000089 BLOCK  /Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274
c:0023 p:0059 s:0088 e:000087 METHOD /Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240
c:0022 p:0017 s:0083 e:000082 METHOD /Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274
c:0021 p:0028 s:0078 e:000077 TOP    /Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/carrierwave-0.10.0/lib/carrierwave/storage.rb:5 [FINISH]
c:0020 p:---- s:0076 e:000075 CFUNC  :require
c:0019 p:0012 s:0072 e:000071 BLOCK  /Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274
c:0018 p:0059 s:0070 e:000069 METHOD /Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240
c:0017 p:0017 s:0065 e:000064 METHOD /Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274
c:0016 p:0310 s:0060 e:000059 TOP    /Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/carrierwave-0.10.0/lib/carrierwave.rb:78 [FINISH]
c:0015 p:---- s:0058 e:000057 CFUNC  :require
c:0014 p:0042 s:0054 e:000053 BLOCK  /Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77 [FINISH]
c:0013 p:---- s:0050 e:000049 CFUNC  :each
c:0012 p:0062 s:0047 e:000046 BLOCK  /Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72 [FINISH]
c:0011 p:---- s:0041 e:000040 CFUNC  :each
c:0010 p:0038 s:0038 e:000037 METHOD /Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61
c:0009 p:0019 s:0034 e:000033 METHOD /Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99
c:0008 p:0102 s:0030 e:000029 TOP    /Users/localuser/Development/everlane.com/config/application.rb:17 [FINISH]
c:0007 p:---- s:0028 e:000027 CFUNC  :require
c:0006 p:0230 s:0024 e:000023 METHOD /Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.1/lib/sidekiq/cli.rb:242
c:0005 p:0008 s:0021 e:000020 METHOD /Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.1/lib/sidekiq/cli.rb:50
c:0004 p:0054 s:0014 e:000013 TOP    /Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.1/bin/sidekiq:13 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :load
c:0002 p:0147 s:0006 E:000560 EVAL   /Users/localuser/.rbenv/versions/2.3.0/bin/sidekiq:23 [FINISH]
c:0001 p:0000 s:0002 E:000610 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/Users/localuser/.rbenv/versions/2.3.0/bin/sidekiq:23:in `<main>'
/Users/localuser/.rbenv/versions/2.3.0/bin/sidekiq:23:in `load'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.1/bin/sidekiq:13:in `<top (required)>'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.1/lib/sidekiq/cli.rb:50:in `run'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.1/lib/sidekiq/cli.rb:242:in `boot_system'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.1/lib/sidekiq/cli.rb:242:in `require'
/Users/localuser/Development/everlane.com/config/application.rb:17:in `<top (required)>'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/carrierwave-0.10.0/lib/carrierwave.rb:78:in `<top (required)>'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/carrierwave-0.10.0/lib/carrierwave/storage.rb:5:in `<top (required)>'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/Users/localuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
```

**Comment by mperham** [comment]
How are you installing MRI 2.3?  I've seen lots of crashes due to a bad RVM install.  Try using ruby-install or ruby-build or build manually.

**Comment by peteygao** [comment]
@mperham Just resolved the issue, was going to update/close this issue.

I _was_ using rbenv:
```
(cd ~/.rbenv/plugins/ruby-build; git pull) # to update ruby-build to include 2.3.0
rbenv install 2.3.0
gem install bundle
bundle install
foreman start
# Crash ensues
```

Then I blew away `rbenv`, installed `chruby` and built Ruby 2.3.0 from scratch and things worked fine:
```
brew install gdbm libffi libyaml openssl readline
wget http://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
tar -xjvf ruby-2.3.0.tar.bz2
cd ruby-2.3.0
./configure --prefix="$HOME/.rubies/ruby-2.3.0" --with-opt-dir="$(brew --prefix openssl):$(brew --prefix readline):$(brew --prefix libyaml):$(brew --prefix gdbm):$(brew --prefix libffi)"
make
make install
```

**Comment by peteygao** [comment]
I already closed the ticket, but for those following from home (a.k.a. somehow googled their way here), here's where the issue is being tracked upstream with Ruby itself:
https://bugs.ruby-lang.org/issues/11930

It's a problem with the GC, apparently.
