### ISSUE TITLE
Sidekiq Pro notifications absent from version 3 

### ISSUE THREAD

**Issue by sdeframond** [mperham/sidekiq#2767]
Hi there,

I am surprised to find that `sidekiq/pro/notifications` is not in the version 3 of the gem. The upgrade notes say "The old 'sidekiq/notifications' features have been removed" but it is not mentioned in [the wiki page](https://github.com/mperham/sidekiq/wiki/Notifications). 

Here is my initializer

```ruby
Sidekiq::Mailer.excluded_environments= 'test'

require 'sidekiq/pro/notifications'
Sidekiq::Client.reliable_push! unless Rails.env.test?
Sidekiq.configure_server do |config|
  config.reliable_fetch!
  config.reliable_scheduler!

  via_options = if Rails.env.development?
                  {
                    :user_name => 'redacted',
                    :password => 'redacted',
                    :address => 'redactedo',
                    :domain => 'redacted',
                    :port => '2525',
                    :authentication => :cram_md5,
                    :enable_starttls_auto => true
                  }
                else
                  {
                    port:           '587',
                    address:        'smtp.mandrillapp.com',
                    user_name:      ENV['MANDRILL_USERNAME'],
                    password:       ENV['MANDRILL_APIKEY'],
                    domain:         'heroku.com',
                    authentication: :plain
                  }
                end
  config.options[:notifications][:email] = {
    to: 'redacted',
    via: :smtp,
    via_options: via_options
  }
end
```
and the error I see

```
/home/mumu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- sidekiq/pro/notifications (LoadError)
	from /home/mumu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/mumu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/mumu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /home/mumu/Repo/3mundi/AirRefund/config/initializers/sidekiq.rb:3:in `<top (required)>'
[...]
```
And the relevant part of my gemfile

```ruby
gem 'sidekiq'
gem 'sidekiq_mailer'
source 'https://redacted' do
  gem 'sidekiq-pro', '< 4'
end
gem 'pony' # Required to send notifications from Sidekiq Pro.
```

Did I miss something? Is there a way to keep using this notification feature?

**Comment by mperham** [comment]
Someone resurrected that wiki page, it was deleted months ago.

Notifications was deprecated like any feature: the latest 2.x prints a warning message and it was removed in 3.x.

You can continue using Pro 2.x if you need the notifications for some reason but note the actual feature is really easy to reproduce using batch callbacks.  This is the entire code which you are welcome to use in your app:

```ruby
module Sidekiq
  module Notifications
    class Email
      attr_reader :options

      def initialize(provider=Pony)
        @provider = provider
      end

      def on_complete(status, opts)
        @options = Sidekiq.options[:notifications][:email].merge(opts.symbolize_keys)

        subject = "[sidekiq] Your work has finished"
        template = Tilt.new("#{File.dirname(__FILE__)}/templates/email.html.erb")
        body = template.render(self, :status => status, :subject => subject)
        email = { :subject => subject, :html_body => body }.merge(options)
        @provider.mail(email)
        email
      end

    end
  end
end
```

**Comment by sdeframond** [comment]
Excellent! Thanks a lot!

**Comment by ryanfox1985** [comment]
Hi,

@mperham, you missed the template file:
`template = Tilt.new("#{File.dirname(__FILE__)}/templates/email.html.erb")`

Regards.

**Comment by mperham** [comment]
Odd, I don't see it in my repo. It's probably gone in the latest version.

**Comment by ecdemis123** [comment]
FYI - The Notification wiki page is still up.  Spent forever trying to figure out how to access the Sidekiq::Notification class before I came across this issue.

**Comment by mperham** [comment]
You are welcome to delete the page.

**Comment by ecdemis123** [comment]
Done.

**Comment by mperham** [comment]
thank you and sorry for the frustration. i left it there for older customers but should have removed it by now.
