### ISSUE TITLE
Rails enum conflict in sidekiq

### ISSUE THREAD

**Issue by krzysiek1507** [mperham/sidekiq#2789]
I have got enum and everything works ok (rails server, console, rpsec tests) except sidekiq
```ruby
Spree::User.class_eval do
  enum kind: [:manufacturer, :student, :practitioner, :business]
end
```
Sidekiq throws error on startup
```You tried to define an enum named "kind" on the model "Spree::User", but this will generate a instance method "kind=", which is already defined by another enum.```

ruby 2.2.4
rails 4.2.5
spree branch: '3-0-stable'
sidekiq 4.0.2

```
Instance method "open" is already defined in Object, use generic helper instead or set StateMachines::Machine.ignore_method_conflicts = true.
  You tried to define an enum named "kind" on the model "Spree::User", but this will generate a instance method "kind=", which is already defined by another enum.
  /Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activerecord-4.2.5/lib/active_record/enum.rb:187:in `detect_enum_conflict!'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activerecord-4.2.5/lib/active_record/enum.rb:94:in `block (2 levels) in enum'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activerecord-4.2.5/lib/active_record/enum.rb:92:in `module_eval'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activerecord-4.2.5/lib/active_record/enum.rb:92:in `block in enum'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activerecord-4.2.5/lib/active_record/enum.rb:83:in `each'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activerecord-4.2.5/lib/active_record/enum.rb:83:in `enum'
/Users/krzysiek1507/Documents/workspace/project/app/models/spree/user_decorator.rb:2:in `block in <top (required)>'
/Users/krzysiek1507/Documents/workspace/project/app/models/spree/user_decorator.rb:1:in `class_eval'
/Users/krzysiek1507/Documents/workspace/project/app/models/spree/user_decorator.rb:1:in `<top (required)>'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:457:in `load'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:457:in `block in load_file'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:647:in `new_constants_in'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:456:in `load_file'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:354:in `require_or_load'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:317:in `depend_on'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:233:in `require_dependency'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/railties-4.2.5/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/railties-4.2.5/lib/rails/engine.rb:471:in `each'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/railties-4.2.5/lib/rails/engine.rb:471:in `block in eager_load!'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/railties-4.2.5/lib/rails/engine.rb:469:in `each'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/railties-4.2.5/lib/rails/engine.rb:469:in `eager_load!'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/railties-4.2.5/lib/rails/engine.rb:346:in `eager_load!'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/railties-4.2.5/lib/rails/application/finisher.rb:56:in `each'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/railties-4.2.5/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/krzysiek1507/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/Users/krzysiek1507/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/Users/krzysiek1507/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/Users/krzysiek1507/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/Users/krzysiek1507/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each'
/Users/krzysiek1507/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `call'
/Users/krzysiek1507/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/Users/krzysiek1507/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/Users/krzysiek1507/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
/Users/krzysiek1507/Documents/workspace/project/config/environment.rb:5:in `<top (required)>'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/sidekiq-4.0.2/lib/sidekiq/cli.rb:236:in `boot_system'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/sidekiq-4.0.2/lib/sidekiq/cli.rb:49:in `run'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/gems/sidekiq-4.0.2/bin/sidekiq:12:in `<top (required)>'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/bin/sidekiq:23:in `load'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/bin/sidekiq:23:in `<main>'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/Users/krzysiek1507/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by mperham** [comment]
This has nothing to do with Sidekiq but is due to Rails eager loading. Run in production and the rails console will fail there too.

**Comment by krzysiek1507** [comment]
@mperham Production works ok.

**Comment by Yoshyn** [comment]
You can find this rails error here : https://github.com/rails/rails/blob/master/activerecord/lib/active_record/enum.rb#L209

**Comment by eozaki** [comment]
found this https://github.com/ctran/annotate_models/issues/170
worked for me just fine
