### ISSUE TITLE
fetch_stats! error makes Web UI inaccessible 

### ISSUE THREAD

**Issue by ivanovv** [mperham/sidekiq#2801]
When I open Sidekiq Web UI (any link) I see a 500 page.
`TypeError - nil can't be coerced into Float`

Details:

Sidekiq versions:
```
sidekiq (3.5.4)
sidekiq-ent (0.7.9)
sidekiq-pro (2.0.5)
```

Stack Trace: 
```
gems/sidekiq-3.5.4/lib/sidekiq/api.rb:77:in '-'
gems/sidekiq-3.5.4/lib/sidekiq/api.rb:77:in 'fetch_stats!'
gems/sidekiq-3.5.4/lib/sidekiq/api.rb:7:in 'initialize'
gems/sidekiq-3.5.4/lib/sidekiq/web_helpers.rb:98:in 'new'
gems/sidekiq-3.5.4/lib/sidekiq/web_helpers.rb:98:in 'stats'
gems/sidekiq-3.5.4/web/views/_summary.erb:3:in 'block in singleton class'
gems/sidekiq-3.5.4/web/views/_summary.erb:131067:in 'instance_eval'
gems/sidekiq-3.5.4/web/views/_summary.erb:131067:in 'singleton class'
gems/sidekiq-3.5.4/web/views/_summary.erb:131065:in '__tilt_604009238'
gems/tilt-1.4.1/lib/tilt/template.rb:170:in 'call'
gems/tilt-1.4.1/lib/tilt/template.rb:170:in 'evaluate'
gems/tilt-1.4.1/lib/tilt/template.rb:103:in 'render'
gems/sinatra-1.4.5/lib/sinatra/base.rb:814:in 'render'
gems/sinatra-1.4.5/lib/sinatra/base.rb:665:in 'erb'
gems/sidekiq-3.5.4/web/views/layout.erb:20:in 'block in singleton class'
gems/sidekiq-3.5.4/web/views/layout.erb:131067:in 'instance_eval'
gems/sidekiq-3.5.4/web/views/layout.erb:131067:in 'singleton class'
gems/sidekiq-3.5.4/web/views/layout.erb:131065:in '__tilt_604009238'
gems/tilt-1.4.1/lib/tilt/template.rb:170:in 'call'
gems/tilt-1.4.1/lib/tilt/template.rb:170:in 'evaluate'
gems/tilt-1.4.1/lib/tilt/template.rb:103:in 'render'
gems/sinatra-1.4.5/lib/sinatra/base.rb:814:in 'render'

[more here, but I think it is irrelevant]
```

So this is a step by step through this method (`fetch_stats!`), with some classes in output renamed:
```
pipe1_res = Sidekiq.redis do |conn|
  conn.pipelined do
    conn.get('stat:processed'.freeze)
    [...]
  end
end
```
gives
```
["1023384", "9334", 7, 20, 2, 1, ["{\"class\":\"SomeWorker\",\"args\":[1453986900.0,1453987800.0],\"retry\":true,\"queue\":\"default\",\"backtrace\":10,\"jid\":\"ddab04f67ad51847c540de11\",\"created_at\":1453986900.1418352}"], ["betastaging:1687:155fb21dff0c"], ["webhooks", "csv", "metadata", "customer_import", "default"]]
```

```
pipe2_res = ["0", 0, 0, 0, 0, 2211]

s = pipe1_res[7].size
=> 1
irb(main):021:0> workers_size = pipe2_res[0...s].map(&:to_i).inject(0, &:+)
=> 0
irb(main):022:0> enqueued     = pipe2_res[s..-1].map(&:to_i).inject(0, &:+)
=> 2211
```
Calculating `default_queue_latency` throws subj error.

```
irb(main):028:0> Sidekiq.load_json(entry)['enqueued_at'.freeze]
=> nil
irb(main):029:0> Sidekiq.load_json(entry)
=> {"class"=>"SomeWorker", "args"=>[1453986900.0, 1453987800.0], "retry"=>true, "queue"=>"default", "backtrace"=>10, "jid"=>"ddab04f67ad51847c540de11", "created_at"=>1453986900.1418352}
```

`enqueued_at` is missing

**Comment by mperham** [comment]
How did you enqueue that job?

You need to upgrade Sidekiq Pro.

**Comment by ivanovv** [comment]
> How did you enqueue that job?

Not sure, I was asked to take a look what was happening with the sidekiq UI.

> You need to upgrade Sidekiq Pro.

This error is fixed in new versions?

**Comment by mperham** [comment]
No, 2.0.5 is just pretty old, about a year.

**Comment by mperham** [comment]
And your issue is definitely because the job payload is missing the enqueued_at element, typically because someone is pushing the job to Redis by hand instead of using the Sidekiq::Client API.

**Comment by ivanovv** [comment]
Ok, guess we can close then. Maybe it was due to a version change from `3.3.4` to `3.5.4`
