### ISSUE TITLE
"Error fetching job: Concurrent::RejectedExecutionError" during shut down

### ISSUE THREAD

**Issue by jonhyman** [mperham/sidekiq#2827]
This happened to one of about 500 of my worker processes during a restart. Any thoughts on where to troubleshoot?

```
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.473424132] (11797) [INFO] Shutting down
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.473544664] (11797) [INFO] Terminating quiet workers
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.473948382] (11797) [INFO] Scheduler exiting...
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.477610629] (11797) [ERROR] Error fetching job: Concurrent::RejectedExecutionError
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478215769] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/abstract_executor_service.rb:76:in `handle_fallback'
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478270580] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_executor_service.rb:21:in `block in post'
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478365030] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478410517] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478451911] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478499401] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_executor_service.rb:19:in `post'
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478544970] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/future.rb:52:in `execute'
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478591640] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/future.rb:75:in `execute'
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478638695] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/pro/fetch.rb:148:in `retrieve_work'
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478684176] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/pro/fetch.rb:22:in `retrieve_work'
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478730195] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:85:in `get_one'
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478774402] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:95:in `fetch'
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478818061] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:78:in `process_one'
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478898239] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:67:in `run'
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478944486] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:16:in `watchdog'
Feb 08 17:31:00 worker-prd-iad-onmetal-09 production.log:  [10:31:00.478991384] (11797) [ERROR] /var/www/platform/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by mperham** [comment]
See if that helps.

**Comment by jonhyman** [comment]
Thanks, I rolled back after still seeing some of the "recovering work" messages (though oddly our logs do not show any "Processing recovered job" log statements, so whatever the race I don't think we're having double-runs). But tomorrow I'm going to spend more time hunting down the race, and will keep an eye on this too.

**Comment by jonhyman** [comment]
Can you release 3.0.6 so I can point at it since the repo is private?

**Comment by mperham** [comment]
I'd rather not push new versions to test each change. Can you test changes locally?

**Comment by jonhyman** [comment]
Ok I'll monkey patch it locally. 

Btw, I'm pretty sure I found out why the "recovering work" messages were occurring even after 3.0.5 where we added that if check. From my logs, the check does fix it in general. But I have another part of my code where we tweak the fetchers and I was double-calling start in a very narrow case, which is why I saw it again. So going to close the case on that one.

**Comment by jonhyman** [comment]
It's been running for almost a day, and no issues, so I'm assuming this has helped.

**Comment by jonhyman** [comment]
Okay it happened again now.

In my file, appboy/sidekiq_job.rb, I have the monkey patch to do this, but it still errored out.

```ruby
def retrieve_work
  return nil if @done

  # THIS IS LINE 312
  super
end
```

```
Feb 19 13:53:06 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.903533088] (26470) [INFO] Shutting down
Feb 19 13:53:06 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.903626770] (26470) [INFO] Terminating quiet workers
Feb 19 13:53:06 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.904097375] (26470) [INFO] Scheduler exiting...
Feb 19 13:53:06 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.908810647] (26470) [ERROR] Error fetching job: Concurrent::RejectedExecutionError
Feb 19 13:53:06 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.908960593] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/abstract_executor_service.rb:76:in `handle_fallback'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.909187433] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_executor_service.rb:21:in `block in post'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.909424200] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.909637870] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.909751632] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.909994236] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_executor_service.rb:19:in `post'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.910048288] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/future.rb:52:in `execute'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.910243337] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/future.rb:75:in `execute'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.910337927] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/pro/fetch.rb:148:in `retrieve_work'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.910542540] (26470) [ERROR] /var/www/platform/releases/20160219185050/shared_code/lib/shared/appboy/sidekiq_job.rb:312:in `retrieve_work'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.910624575] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/pro/fetch.rb:22:in `retrieve_work'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.910680964] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:85:in `get_one'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.910710199] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:95:in `fetch'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.910734847] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:78:in `process_one'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.910759182] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:67:in `run'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.910783086] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:16:in `watchdog'
Feb 19 13:53:07 worker-prd-iad-onmetal-03 production.log:  [ 6:53:06.910807531] (26470) [ERROR] /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by mperham** [comment]
My initial thought is, because no one else has reported an issue and you have some serious brain surgery to the reliable fetch impl, that you've introduced a race condition somehow.  I don't want to "blame" you but how much confidence do you have in your changes?  Is it possible to use the stock version on some small percentage of processes and see if they see a similar error?

**Comment by jonhyman** [comment]
So I would usually tend to agree with you except that this is the Fetcher that has thrown the issues, it just forces a `Weighted` algorithm (so the queue list gets processed randomly).

```ruby
class SidekiqReliableFetchForceWeighted < ::Sidekiq::Pro::ReliableFetch
  def initialize(*args)
    super(*args)
    @retriever = Appboy::SidekiqJob::SidekiqReliableFetchForceWeighted::Retriever.instance
  end

  class Retriever < ::Sidekiq::Pro::ReliableFetch::Retriever
    def start(options)
      super(options)
      @algo = Weighted
    end

    def retrieve_work
      return nil if @done
      super
    end
  end
end
```

Since I re-opened earlier today, I have updated `retrieve_work` to be this

```ruby
def retrieve_work
  return nil if @done
  begin
    return super
  rescue Concurrent::RejectedExecutionError => e
    AppboyLogger.warn {"#{self.class} got #{e.class}, done is #{@done}, returning nil: #{e.backtrace()}"}
    return nil
  end
end
```

and so it'll email me on if it happens again, I'll see what `@done` is. I'll let you know when it happens. So far it happened twice today and that's it.

It may be due to the extreme number of jobs each worker processes (most jobs are under 50ms, and they're running non-stop).

**Comment by mperham** [comment]
You can force weighted by using weight of 1 for each queue.

**Comment by mperham** [comment]
As implied, random fetch can be implemented by using 1 as the weight for each queue: `-q foo,1 -q bar,1`.  This was fixed/implemented in [2.1.3](https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md#213)

**Comment by jonhyman** [comment]
Nice, that's good to know that was fixed.

**Comment by jonhyman** [comment]
So this is weird, I got two of these under heavy load yesterday:

```
[WARN] Appboy::SidekiqJob::SidekiqReliableFetchForceWeighted::Retriever got Concurrent::RejectedExecutionError, done is true, returning nil:

"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/abstract_executor_service.rb:76:in `handle_fallback'",
"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_executor_service.rb:21:in `block in post'",
"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'",
"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'",
"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'",
"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_executor_service.rb:19:in `post'",
"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/future.rb:52:in `execute'",
"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.0/lib/concurrent/future.rb:75:in `execute'",
"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/pro/fetch.rb:148:in `retrieve_work'",
"/var/www/platform/releases/20160223195740/shared_code/lib/shared/appboy/sidekiq_job.rb:313:in `retrieve_work'",
"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/pro/fetch.rb:22:in `retrieve_work'",
"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:85:in `get_one'",
"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:95:in `fetch'",
"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:78:in `process_one'",
"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:67:in `run'",
"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:16:in `watchdog'",
"/var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:24:in `block in safe_thread'"
```

where that Retriever again is just this

```ruby
class SidekiqReliableFetchForceWeighted < ::Sidekiq::Pro::ReliableFetch
  def initialize(*args)
    super(*args)
    @retriever = Appboy::SidekiqJob::SidekiqReliableFetchForceWeighted::Retriever.instance
  end

  class Retriever < ::Sidekiq::Pro::ReliableFetch::Retriever
    def start(options)
      super(options)
      @algo = Weighted
    end

    def retrieve_work
      return nil if @done
      begin
        return super
      rescue Concurrent::RejectedExecutionError => e
        AppboyLogger.warn {"#{self.class} got #{e.class}, done is #{@done}, returning nil: #{e.backtrace()}"}
        return nil
      end
    end
  end
end
```

The crazy thing is that `@done` was true in the `rescue` but not at the top of the function. I imagine there's a race condition with setting `@done` that is not atomic everywhere? This is MRI Ruby.

**Comment by mperham** [comment]
Ok, I see the issue is a race condition on \@done and the pool shutdown.  Can't do that without a mutex.  You're hitting it because your scale is higher than most.  I'll get it fixed.

**Comment by jonhyman** [comment]
Thanks.
