### ISSUE TITLE
redis timeout with sidekiq-pro 3.0.5

### ISSUE THREAD

**Issue by mathieujobin** [mperham/sidekiq#2838]
we're currently using sidekiq-pro 1.7.6 with sidekiq 4.1.0
and I tried to upgrade sidekiq-pro to 3.0.5 and we experienced timeouts every minutes with our redis server ( 2.8.10 )

the stacktrace shows it''s related to the new config subsystem in sidekiq-pro 3.x

** …2.2.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/pro/config.rb:  63:in `block in listen'

which is doing a psubscribe

```ruby
conn.psubscribe(CHANNEL) 
```

any idea what that could be caused by ?

thanks

```
…by/2.2.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:  55:in `rescue in _read_from_socket'
…by/2.2.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:  48:in `_read_from_socket'
…by/2.2.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:  41:in `gets'
…by/2.2.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb: 273:in `read'
…bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb: 249:in `block in read'
…bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb: 237:in `io'
…bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb: 248:in `read'
…bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb: 129:in `block (3 levels) in call_loop'
…bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb: 128:in `loop'
…bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb: 128:in `block (2 levels) in call_loop'
…bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb: 218:in `block (2 levels) in process'
…bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb: 354:in `ensure_connected'
…bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb: 208:in `block in process'
…bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb: 293:in `logging'
…bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb: 207:in `process'
…bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb: 127:in `block in call_loop'
…bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb: 267:in `with_socket_timeout'
…bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb: 274:in `without_socket_timeout'
…bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb: 126:in `call_loop'
…dle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/subscribe.rb:  35:in `subscription'
…dle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/subscribe.rb:  16:in `psubscribe'
…shared/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis.rb:2718:in `_subscription'
…shared/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis.rb:2113:in `block in psubscribe'
…shared/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis.rb:  57:in `block in synchronize'
…/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/monitor.rb: 211:in `mon_synchronize'
…shared/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis.rb:  57:in `synchronize'
…shared/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis.rb:2112:in `psubscribe'
…ms/redis-namespace-4c580ee38d09/lib/redis/namespace.rb: 362:in `call_with_namespace'
…ms/redis-namespace-4c580ee38d09/lib/redis/namespace.rb: 274:in `method_missing'
…2.2.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/pro/config.rb:  63:in `block in listen'
…ed/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq.rb:  84:in `block in redis'
….2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:  64:in `block (2 levels) in with'
….2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:  63:in `handle_interrupt'
….2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:  63:in `block in with'
….2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:  60:in `handle_interrupt'
….2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:  60:in `with'
…ed/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq.rb:  81:in `redis'
…2.2.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/pro/config.rb:  62:in `listen'
…ndle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:  16:in `watchdog'
…ndle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:  24:in `block in safe_thread'
```

**Comment by mathieujobin** [comment]
CC: @ethnext

**Comment by mathieujobin** [comment]
very constant during the time 3.0.5 was deployed

![spectacle tt3917](https://cloud.githubusercontent.com/assets/99191/13131292/7ca7b204-d5b8-11e5-8c82-bfc81657a5e2.png)

about 3 errors every minute

![spectacle mn3917](https://cloud.githubusercontent.com/assets/99191/13131317/b00e58fa-d5b8-11e5-9653-bae58d20ae5a.png)

**Comment by mperham** [comment]
You've included everything but the actual error message. I need that to diagnose.

**Comment by mperham** [comment]
Do you have a global setting to set a timeout for all Redis connections?

**Comment by mathieujobin** [comment]
Exception is Redis::TimeoutError
Message is Connection timed out

there is a 15s timeout at the load balancer level, but 15s is quite long, isn't it ?
4s to establish connection

**Comment by mperham** [comment]
That connection is persistent.  It's not req/resp. You need to disable timeouts for it.

**Comment by mathieujobin** [comment]
i see
makes sense... so we cannot upgrade to 3.x under these settings.

**Comment by mperham** [comment]
That's a performance hit.  You're not allowing Sidekiq to use persistent TCP connections but forcing it to reestablish TCP connections every 15 seconds.  Can you share why the environment is designed this way?

**Comment by mathieujobin** [comment]
just saw your last comment, I'll try t find out what was the reason behind this setting

**Comment by mperham** [comment]
No problem, comment if you can.
