### ISSUE TITLE
Sidekiq::Queue#pause! raises error in Sidekiq Pro 3.0.3

### ISSUE THREAD

**Issue by jcarlson** [mperham/sidekiq#2854]
```
irb(main):009:0* q = Sidekiq::Queue.new('default')
=> #<Sidekiq::Queue:0x005584d706de28 @name="default", @rname="queue:default">
irb(main):010:0> q.pause!
NameError: uninitialized constant Sidekiq::Pro::Config
	from /usr/local/bundle/gems/sidekiq-pro-3.0.3/lib/sidekiq/pro/api.rb:105:in `block (2 levels) in pause!'
	from /usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:2244:in `block in multi'
	from /usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
	from /usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
	from /usr/local/bundle/gems/redis-3.2.2/lib/redis.rb:2237:in `multi'
	from /usr/local/bundle/gems/sidekiq-pro-3.0.3/lib/sidekiq/pro/api.rb:103:in `block in pause!'
	from /usr/local/bundle/gems/sidekiq-4.1.0/lib/sidekiq.rb:84:in `block in redis'
	from /usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
	from /usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
	from /usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
	from /usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
	from /usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
	from /usr/local/bundle/gems/sidekiq-4.1.0/lib/sidekiq.rb:81:in `redis'
	from /usr/local/bundle/gems/sidekiq-pro-3.0.3/lib/sidekiq/pro/api.rb:102:in `pause!'
	from (irb):10
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/bundle/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'irb(main):011:0>
```

**Comment by mperham** [comment]
It's not noted in the [changelog](https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md) but this was already fixed.
