### ISSUE TITLE
Sidekiq threads increasing until out of threads on heroku

### ISSUE THREAD

**Issue by jeremyhaile** [mperham/sidekiq#2862]
After upgrading from Sidekiq 3.x to Sidekiq 4.1.0, I started receiving the following error: `Error: ThreadError: can't create Thread: Resource temporarily unavailable` from my sidekiq process.

I tried downgrading to Sidekiq 4.0.2 but I still see the same issue.

To test further, I opened a sidekiq process on a manual heroku instance and ran top. Sure enough, after processing some jobs, the number of threads increased from 23 to 83. It appears that my instances are hitting the limit of 512 threads and then failing.

Here is the output of top when it was at 83 threads:
```
top - 14:08:30 up 21:15,  0 users,  load average: 1.08, 1.94, 2.33
Threads:  83 total,   1 running,  82 sleeping,   0 stopped,   0 zombie
%Cpu(s):  6.5 us,  2.4 sy,  0.0 ni, 88.3 id,  0.3 wa,  0.0 hi,  2.4 si,  0.1 st
KiB Mem:  62916388 total, 60334584 used,  2581804 free,  3221888 buffers
KiB Swap: 63963132 total,  1077760 used, 62885372 free. 25627764 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
   29 u12269    20   0 4789664 247276   9336 S  0.3  0.4   0:00.15 sidekiq 4.0.2 app [0 of 10 busy]
    1 nobody    20   0   21096   1540   1312 S  0.0  0.0   0:00.00 ps-run
    3 u12269    20   0  109116   2028   1540 S  0.0  0.0   0:00.00 bash
    4 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:08.09 sidekiq 4.0.2 app [0 of 10 busy]
    6 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.01 sidekiq 4.0.2 app [0 of 10 busy]
    9 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
   10 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
   11 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
   12 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
   13 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.05 sidekiq 4.0.2 app [0 of 10 busy]
   15 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
   18 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.07 sidekiq 4.0.2 app [0 of 10 busy]
   19 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
   20 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.15 sidekiq 4.0.2 app [0 of 10 busy]
   21 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.45 sidekiq 4.0.2 app [0 of 10 busy]
   22 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.15 sidekiq 4.0.2 app [0 of 10 busy]
   24 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.32 sidekiq 4.0.2 app [0 of 10 busy]
   25 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.28 sidekiq 4.0.2 app [0 of 10 busy]
   26 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.22 sidekiq 4.0.2 app [0 of 10 busy]
   27 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.12 sidekiq 4.0.2 app [0 of 10 busy]
   28 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.19 sidekiq 4.0.2 app [0 of 10 busy]
  183 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  184 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  185 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  187 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  188 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  189 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  191 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  192 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  193 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  196 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  197 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  198 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  200 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  201 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  202 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  205 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  206 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  207 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  209 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  210 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  211 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  213 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]                                                                                                                                               214 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  215 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  221 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
  222 u12269    20   0 4789664 247276   9336 S  0.0  0.4   0:00.00 sidekiq 4.0.2 app [0 of 10 busy]
<snipped because it just continues>
```

**Comment by mperham** [comment]
You likely have a thread leak in your application.

https://github.com/mperham/sidekiq/wiki/Signals#ttin

**Comment by jeremyhaile** [comment]
@mperham thanks - yeah I figured if this was default sidekiq behavior there'd be more people complaining. Thanks for the ttin tip - I'll try that and see what I can figure out.

**Comment by jeremyhaile** [comment]
@mperham so, I haven't been able to reproduce an increasing number of threads locally. When I run the TTIN, I see the following threads:

- 1 sidekiq/cli thread
- 4 celluloid mailbox threads
- 1 puma_worker_killer auto_reap thread
- 1 sidekiq/launcher thread
- 1 connection_pool/timed_stack thread from sidekiq/scheduled
- 5 redis/connection/ruby threads from sidekiq's brpop call

Of these, celluloid seems like the most likely culprit. I use a gem (pubnub) that uses celluloid (they used to use eventmachine but an upgrade switched to celluloid.  However, I tried using that gem a lot in jobs and I can't get it to increase the number of threads I'm seeing in the TTIN dump.

Let me know if any of this rings a bell of something that could leak threads when used within sidekiq. Thanks!

**Comment by mperham** [comment]
That sounds totally normal, except the puma killer, which is spinning up an
unnecessary thread.

**Comment by jeremyhaile** [comment]
Yeah - puma killer is in a rails initializer...I'm sure I can find some way to disable it when it's sidekiq.  I'll see if I can spin up a worker in production and TTIN it.

**Comment by mperham** [comment]
Wrap anything that **shouldn't** run inside Sidekiq like so:

```ruby
Sidekiq.configure_client do
  require 'puma_killer'
end
```

The 'client' is any process that is not a Sidekiq process.

**Comment by mperham** [comment]
or `require 'puma_stuff' unless Sidekiq.server?`

**Comment by jeremyhaile** [comment]
Thanks for the tip. I just was able to reproduce the thread growth on production. Worker went from 23 threads to 63 when I ran some jobs.

Lots of these in the TTIN dump:
```
4 TID-ouexthv9s WARN: /app/vendor/bundle/ruby/2.2.0/gems/mongo-2.0.6/lib/mongo/server/monitor.rb:123:in `sleep'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.0.6/lib/mongo/server/monitor.rb:123:in `block (2 levels) in run!'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.0.6/lib/mongo/server/monitor.rb:122:in `loop'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.0.6/lib/mongo/server/monitor.rb:122:in `block in run!'
```

I can't find anything in their release notes that make me think the mongo driver leaks threads, but we are a few versions behind, so I'm going to try upgrading and try repeating my test.

**Comment by jeremyhaile** [comment]
Those are definitely the leaking threads, but still happening with the latest driver: 
```
4 TID-oxcnl2bv8 WARN: /app/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.2/lib/mongo/server/monitor.rb:127:in `sleep'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.2/lib/mongo/server/monitor.rb:127:in `block (2 levels) in run!'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.2/lib/mongo/server/monitor.rb:126:in `loop'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.2/lib/mongo/server/monitor.rb:126:in `block in run!'
```

**Comment by mperham** [comment]
Sounds like you should open a mongo issue.
