### ISSUE TITLE
`comparison with Fixnum with nil failed` in sidekiq-ent/periodic/manager

### ISSUE THREAD

**Issue by rdallasgray** [mperham/sidekiq#2872]
Hi, we recently had an issue with periodic workers failing to process jobs, giving the following backtrace:
```
2016-03-07T07:52:00.000Z 22498 TID-owqaqsxkg WARN: ArgumentError: comparison of Fixnum with nil failed
2016-03-07T07:52:00.000Z 22498 TID-owqaqsxkg WARN: /sanitised/releases/70067f3edcb2f47b49ffb66b08597f507a4c92db/vendor/bundle/ruby/2.1.0/gems/sidekiq-ent-1.0.1/lib/sidekiq-ent/periodic/manager.rb:127:in `>='
/sanitised/releases/70067f3edcb2f47b49ffb66b08597f507a4c92db/vendor/bundle/ruby/2.1.0/gems/sidekiq-ent-1.0.1/lib/sidekiq-ent/periodic/manager.rb:127:in `job_due'
/sanitised/releases/70067f3edcb2f47b49ffb66b08597f507a4c92db/vendor/bundle/ruby/2.1.0/gems/sidekiq-ent-1.0.1/lib/sidekiq-ent/periodic/manager.rb:88:in `process'
/sanitised/releases/70067f3edcb2f47b49ffb66b08597f507a4c92db/vendor/bundle/ruby/2.1.0/gems/sidekiq-ent-1.0.1/lib/sidekiq-ent/periodic/manager.rb:69:in `cycle'
/sanitised/releases/70067f3edcb2f47b49ffb66b08597f507a4c92db/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
/sanitised/releases/70067f3edcb2f47b49ffb66b08597f507a4c92db/vendor/bundle/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

Initializer:
```ruby
Sidekiq.configure_server do |config|
  config.redis = <sanitised>
  config.periodic do |mgr|
    mgr.register("* * * * *", SanitisedWorker)
  end
end
Sidekiq.configure_client do |config|
  config.redis = <sanitised>
end
```

- Sidekiq ent version 1.0.1
- Rails version 3.2.22
- Ruby version 2.1.5p273
- Ubuntu 12.04

I searched for an issue matching this but couldn't find one; if it's already been dealt with in a more recent release please feel free to close.

**Comment by mperham** [comment]
It looks like this might happen if you have a periodic block that doesn't register any jobs, maybe you commented out the `register`?  Anyways, it's a bug and I'll get it fixed.

**Comment by mperham** [comment]
Workaround is to register a job, even if that job does nothing.  Will be fixed in 1.2.2.

**Comment by rdallasgray** [comment]
Not sure I understand -- we do register a job. See the initializer above:
```ruby
  config.periodic do |mgr|
    mgr.register("* * * * *", SanitisedWorker)
  end
```

**Comment by mperham** [comment]
Then I can't explain why you'd see that bug.  That bug should only surface if the manager is active but there are no jobs to manage.

**Comment by rdallasgray** [comment]
OK, we'll upgrade and keep an eye on it. Thanks.
