### ISSUE TITLE
Naive deployment to heroku results in crash on worker

### ISSUE THREAD

**Issue by knewter** [mperham/sidekiq#2875]
A naive deployment of a very basic rails app using sidekiq results in the following errors in Heroku's logs when starting the worker process:

```
2016-03-07T22:37:26.713684+00:00 heroku[worker.1]: Starting process with command `bundle exec sidekiq -e production`
2016-03-07T22:37:27.333680+00:00 heroku[worker.1]: State changed from starting to up
2016-03-07T22:37:29.489541+00:00 app[worker.1]: Your Redis connection pool is too small for Sidekiq to work, your pool has 3 connections but really needs to have at least 5
2016-03-07T22:37:29.489557+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/redis_connection.rb:35:in `verify_sizing'
2016-03-07T22:37:29.489558+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/redis_connection.rb:14:in `create'
2016-03-07T22:37:29.489559+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq.rb:102:in `redis='
2016-03-07T22:37:29.489560+00:00 app[worker.1]: /app/config/initializers/sidekiq.rb:8:in `block in <top (required)>'
2016-03-07T22:37:29.489560+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq.rb:62:in `configure_server'
2016-03-07T22:37:29.489561+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
```

The code I'm using for this is here: https://www.dropbox.com/s/0stkjgekappq8sk/sidekiq_rails_demo.tar.gz?dl=0

Steps to reproduce:

```
tar zxvf sidekiq_rails_demo.tar.gz
cd sidekiq_rails_demo
git init .
git add .
git commit -m"initial commit"
heroku create
heroku ps:scale web=1
heroku addons:create redistogo:nano
heroku config:set REDIS_PROVIDER=REDISTOGO_URL
heroku config:set EMAIL_RECIPIENT="you@example.com"
vim Procfile
```

(Procfile as follows)
```
web: bundle exec rails server -p $PORT
worker: bundle exec sidekiq -e production
```

```
heroku restart
heroku ps:scale worker=1
```

Check the heroku logs, you'll get the error mentioned above.

**Comment by mperham** [comment]
The error message seems clear to me?  You are doing this:

```ruby
Sidekiq.configure_server do |config|
  config.redis = { :size => 3 }
end
```

That must be a minimum of 5.  Sidekiq needs several connections for its internal use.  Suggestions for improvement are welcome.

**Comment by knewter** [comment]
Argh.  This is in fact extremely clear, and I can't recall why I ended up with that in the first place.  I'm working through it and if I find an easier way of warning, I'll do that.  I really don't know how this made its way into my setup to be honest :-\  I think I was trying to reduce connections because of the nano redistogo instance.
