### ISSUE TITLE
Pro - Batch success handler clean up in Pro v3

### ISSUE THREAD

**Issue by yads** [mperham/sidekiq#2877]
We have attempted an upgrade of Sidekiq and Sidekiq pro from version 3.x/1.7 to 4.1/3.0. One major difference we have noticed in the way batches are handled is that when a batch is deemed to be 'successful' it cleans up all redis keys associated with that branch. Is there a way to turn off this default behaviour?

The reason we are looking to do this, is because we have a custom batch event handler called all_complete that we are using with custom middleware. By the time this callback is run, the batch information has been removed and the callback fails with the following stack trace:

``` bash
2016-03-08T18:02:09.367Z 258 TID-oritkr1p4 WARN: {"class"=>"Sidekiq::Batch::Callback", "queue"=>"low_priority", "args"=>["all_complete", "edluMiuKQsr2TA"], "retry"=>true, "jid"=>"17274bffbd7ba251284aceaf", "created_at"=>1457459527.7037177, "enqueued_at"=>1457460129.3630471, "error_message"=>"Couldn't find Batch edluMiuKQsr2TA in redis", "error_class"=>"Sidekiq::Batch::NoSuchBatch", "failed_at"=>1457459530.0280514, "retry_count"=>5, "retried_at"=>1457460129.3671525}
2016-03-08T18:02:09.367Z 258 TID-oritkr1p4 WARN: Sidekiq::Batch::NoSuchBatch: Couldn't find Batch edluMiuKQsr2TA in redis
2016-03-08T18:02:09.367Z 258 TID-oritkr1p4 WARN: /opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/batch/status.rb:45:in `load_data'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/batch/status.rb:19:in `initialize'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/batch/callback.rb:11:in `new'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/batch/callback.rb:11:in `perform'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:150:in `execute_job'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/opt/kudos/current/lib/sidekiq/middleware/sidekiq_job_limiter_middleware.rb:50:in `call'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/batch/middleware.rb:33:in `call'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/opt/kudos/current/lib/sidekiq/middleware/sidekiq_batch_count_middleware.rb:25:in `call'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/logging.rb:30:in `with_context'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:132:in `call'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:127:in `block in process'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:166:in `stats'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:126:in `process'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:79:in `process_one'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:67:in `run'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:16:in `watchdog'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:24:in `block in safe_thread'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `call'
/opt/shared/bundle/kudos/ruby/2.2.0/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `block in create_with_logging_context'
```

**Comment by mperham** [comment]
There's no way to disable this.  What is `all_complete`?

**Comment by yads** [comment]
It's a custom callback that we created when we were using the old version. It was using the old Sidekiq::Batch::Lifecycle class. Since that old code was far less strict with what the event was called we were able to do

```
        Sidekiq::Client.push('class' => Sidekiq::Batch::Lifecycle,
                             'queue' => queue,
                             'args' => ['all_complete', bid])
```

**Comment by mperham** [comment]
I understand it's a callback.  **Why do you need it?**

**Comment by yads** [comment]
See issue #2250 Basically the existing callbacks are too limited and we needed a way to find out if all the jobs in a batch had completed (whether through retry exhaustion or success). We felt this was a good way to hook into the existing batch infrastructure at the time.

**Comment by mperham** [comment]
Ok, thanks.  Sidekiq's policy is that jobs which expire due to retry exhaustion are bugs which need manual intervention by a developer (these jobs go to the Dead queue and must be executed manually).  This might include manually cleaning up an associated batch.  There's no provision for automating this or adding additional callbacks.
