### ISSUE TITLE
NoMethodError: undefined method `[]' for false:FalseClass

### ISSUE THREAD

**Issue by NielsKSchjoedt** [mperham/sidekiq#2887]
After the last update of sidekiq, where I also started using the unique jobs feature (I'm running sidekiq-ent) I started to see the following errors from time to time. I have no clue what it is:

```
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/client.rb:179:in `atomic_push'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/client.rb:172:in `block (2 levels) in raw_push'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/redis-3.2.2/lib/redis.rb:2244:in `block in multi'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
/home/dep_user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/redis-3.2.2/lib/redis.rb:2237:in `multi'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/client.rb:171:in `block in raw_push'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/client.rb:170:in `raw_push'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/batch/client.rb:36:in `raw_push_with_batch'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/client.rb:91:in `push_bulk'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/client.rb:123:in `push_bulk'
/home/dep_user/au/shared/bundle/ruby/2.3.0/bundler/gems/dc-d41b8538e33e/lib/dc/ac_policy.rb:202:in `push_jobs'
/home/dep_user/au/shared/bundle/ruby/2.3.0/bundler/gems/dc-d41b8538e33e/lib/dc/ac_policy.rb:139:in `block in enqueue_scraper_jobs'
/home/dep_user/au/shared/bundle/ruby/2.3.0/bundler/gems/dc-d41b8538e33e/lib/dc/ac_policy.rb:138:in `each'
/home/dep_user/au/shared/bundle/ruby/2.3.0/bundler/gems/dc-d41b8538e33e/lib/dc/ac_policy.rb:138:in `enqueue_scraper_jobs'
/home/dep_user/au/shared/bundle/ruby/2.3.0/bundler/gems/dc-d41b8538e33e/lib/dc/ac_policy.rb:127:in `enqueue_jobs!'
/home/dep_user/au/shared/bundle/ruby/2.3.0/bundler/gems/dc-d41b8538e33e/lib/dc/ac_policy.rb:38:in `handle!'
/home/dep_user/au/shared/bundle/ruby/2.3.0/bundler/gems/dc-d41b8538e33e/lib/dc/indexing_templates/collectors/bc.rb:73:in `handle_advert_candidates!'
/home/dep_user/au/shared/bundle/ruby/2.3.0/bundler/gems/dc-d41b8538e33e/lib/dc/indexing_templates/collectors/bc.rb:33:in `handle_current_advert_candidate_slice'
/home/dep_user/au/shared/bundle/ruby/2.3.0/bundler/gems/dc-d41b8538e33e/lib/dc/indexing_templates/collectors/mc/bmc.rb:38:in `block in run_it!'
/home/dep_user/au/shared/bundle/ruby/2.3.0/bundler/gems/dc-d41b8538e33e/lib/dc/indexing_templates/collectors/mc/bmc.rb:33:in `loop'
/home/dep_user/au/shared/bundle/ruby/2.3.0/bundler/gems/dc-d41b8538e33e/lib/dc/indexing_templates/collectors/mc/bmc.rb:33:in `run_it!'
/home/dep_user/au/shared/bundle/ruby/2.3.0/bundler/gems/dc-d41b8538e33e/lib/dc/worker_jobs/ac_collector_job.rb:62:in `run_collector!'
/home/dep_user/au/shared/bundle/ruby/2.3.0/bundler/gems/dc-d41b8538e33e/lib/dc/worker_jobs/ac_collector_job.rb:36:in `perform'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:150:in `execute_job'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/dep_user/au/releases/20160315155502/config/initializers/sidekiq.rb:75:in `call'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/dep_user/au/releases/20160315155502/config/initializers/sidekiq.rb:39:in `call'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/honeybadger-2.0.12/lib/honeybadger/plugins/sidekiq.rb:11:in `block in call'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/honeybadger-2.0.12/lib/honeybadger/trace.rb:62:in `instrument'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/honeybadger-2.0.12/lib/honeybadger/trace.rb:18:in `instrument'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/honeybadger-2.0.12/lib/honeybadger/plugins/sidekiq.rb:10:in `call'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-pro-3.0.5/lib/sidekiq/batch/middleware.rb:33:in `call'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-ent-1.2.0/lib/sidekiq-ent/unique.rb:103:in `call'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-ent-1.2.0/lib/sidekiq-ent/limiter/middleware.rb:38:in `call'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/logging.rb:30:in `with_context'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:127:in `block in process'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:166:in `stats'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:126:in `process'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:79:in `process_one'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:67:in `run'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:16:in `watchdog'
/home/dep_user/au/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

Similar errors are also raised from: 
```
/gems/sidekiq-4.1.0/lib/sidekiq/client.rb:188 :in `block in atomic_push`
```

Versions:
sidekiq (4.1.0)
sidekiq-ent (1.2.0)
sidekiq-pro (3.0.5)

My middleware setup looks like this:

```ruby
module CountryBased
  module Sidekiq
    module Middleware

      class Client
        def call(_worker_class, item, _queue, _redis_pool=nil)
          set_country(item)
          yield
        end

        private

        def set_country item
          item["au_country"] ||= CountryManager.country.to_s
          # Used for sidekiq unique jobs extension
          item["args"] << "au_country_#{item['au_country']}" unless item["args"].last == "au_country_#{item['au_country']}"
        end
      end

      class Server
        def call(_worker_class, item, queue)
          read_country(item)

          if is_localized_queue?(queue)
            I18n.locale = CountryManager.default_locale_for_current_country
          else
            I18n.locale = CountryManager.default_locale
          end

          yield

        ensure
          RequestStore.clear!
        end

        private

        def read_country item
          CountryManager.country = item['au_country'].to_sym
          item["args"].delete("au_country_#{item['au_country']}") # Remove before actually calling #perform with arguments
        end

        def is_localized_queue? queue
          ['critical_jobs', 'mailer_jobs'].include?(queue)
        end
      end

    end
  end
end


module MemoryManagement
  module Sidekiq
    module Middleware
      class Server
        def call(_worker_class, _item, _queue)
          verify_memory_below_limit!
          yield
        end

        def verify_memory_below_limit!
          current_memory = NewRelic::Agent::Samplers::MemorySampler.new.sampler.get_sample
          return :all_ok if current_memory < 3000.0 #MB

          Rails.logger.warn "Killing sidekiq process with #{Process.pid}. " \
            "Current memory size: #{current_memory} MB"
          Process.kill("TERM", Process.pid)
        end
      end
    end
  end
end

Sidekiq::Logging.logger.level = Logger::WARN if Rails.env.production?

Sidekiq.configure_client do |config|
  config.redis = {:url => Rails.application.secrets.redis_sidekiq_url}
  config.client_middleware{|chain| chain.add CountryBased::Sidekiq::Middleware::Client}
end

Sidekiq.configure_server do |config|
  config.redis = {:url => Rails.application.secrets.redis_sidekiq_url}

  config.client_middleware{|chain| chain.add CountryBased::Sidekiq::Middleware::Client}
  config.server_middleware{|chain| chain.add CountryBased::Sidekiq::Middleware::Server}

  config.server_middleware{|chain| chain.add MemoryManagement::Sidekiq::Middleware::Server}
end

Sidekiq::Limiter.configure do |config|
  config.redis = {url: Rails.application.secrets.redis_ratelimit_url }
end

# Disable uniqueness in testing, this has the potential to cause much head scratching...
Sidekiq::Enterprise.unique! unless Rails.env.test?

```

**Comment by mperham** [comment]
You have a middleware which is preventing a job from pushing to Redis, likely the unique jobs middleware.  `push_bulk` doesn't handle this case right now.

**Comment by mperham** [comment]
Side note: your memory management middleware can be removed if you use the [multi process](https://github.com/mperham/sidekiq/wiki/Ent-Multi-Process#memory-monitoring) feature.

**Comment by NielsKSchjoedt** [comment]
So in other words, `push_bulk` cannot be used with unique jobs? Are there other calls which currently is not support by unique jobs?

**Comment by mperham** [comment]
If you run master, it will work fine.  Explicit limitations are documented in the wiki but bugs will happen.
