### ISSUE TITLE
Getting randomly Redis connection timeout error while using Sidekiq (RunAsAsync.perform_async)

### ISSUE THREAD

**Issue by frenkelor** [mperham/sidekiq#2935]
I'm getting a random time out connection error while we try to push an async job.
I'm staggering with it a bit since last week but i can't reproduce it, so it's hard to tell if i fixed the issue or not.
We are using this redis server also to store data from our platform beside running sidekiq.

until now i have 2 assumptions:
1. this is a connections issue 
2. i need to remove this line from our async class - sidekiq_options retry: false and every thing will work again :(

I'm using Heroku as our hosting platform
1. redis connection limit:128 (Redis To go)
2. unicorn processes:10
3. web dynos:2
4. worker dynos (sidekiq):2
5. client poll size 5 (default)
6. server poll size 5 (default)
7. concurrency: 5
8. ruby 2.1.2
9. rails 3.2.19
10. redis_version 2.8.21 

sidekiq gems 
sidekiq (3.4.1)
sidekiq-delay (1.0.5)
sidekiq-status (0.6.0)

**backtrace:**
```
IO::EAGAINWaitReadable: Resource temporarily unavailable - read would block
  from redis/connection/ruby.rb:49:in `read_nonblock'
  from redis/connection/ruby.rb:49:in `_read_from_socket'
  from redis/connection/ruby.rb:41:in `gets'
  from redis/connection/ruby.rb:273:in `read'
  from redis/client.rb:229:in `block in read'
  from redis/client.rb:220:in `io'
  from redis/client.rb:228:in `read'
  from redis/client.rb:162:in `block in call_pipelined'
  from redis/client.rb:201:in `block (2 levels) in process'
  from redis/client.rb:309:in `ensure_connected'
  from redis/client.rb:191:in `block in process'
  from redis/client.rb:270:in `logging'
  from redis/client.rb:190:in `process'
  from redis/client.rb:161:in `call_pipelined'
  from redis/client.rb:133:in `block in call_pipeline'
  from redis/client.rb:257:in `with_reconnect'
  from redis/client.rb:131:in `call_pipeline'
  from new_relic/agent/instrumentation/redis.rb:58:in `block in call_pipeline'
  from new_relic/agent/datastores.rb:111:in `block in wrap'
  from new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
  from new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
  from new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
  from new_relic/agent/datastores.rb:108:in `wrap'
  from new_relic/agent/instrumentation/redis.rb:57:in `call_pipeline'
  from redis.rb:2094:in `block in multi'
  from redis.rb:37:in `block in synchronize'
  from monitor.rb:211:in `mon_synchronize'
  from redis.rb:37:in `synchronize'
  from redis.rb:2086:in `multi'
  from sidekiq-status/storage.rb:16:in `block in store_for_id'
  from sidekiq-status/storage.rb:102:in `block in redis_connection'
  from connection_pool.rb:64:in `block (2 levels) in with'
  from connection_pool.rb:63:in `handle_interrupt'
  from connection_pool.rb:63:in `block in with'
  from connection_pool.rb:60:in `handle_interrupt'
  from connection_pool.rb:60:in `with'
  from sidekiq-status/storage.rb:101:in `redis_connection'
  from sidekiq-status/storage.rb:15:in `store_for_id'
  from sidekiq-status/client_middleware.rb:26:in `call'
  from sidekiq/middleware/chain.rb:129:in `block in invoke'
  from sidekiq/middleware/chain.rb:132:in `call'
  from sidekiq/middleware/chain.rb:132:in `invoke'
  from sidekiq/client.rb:207:in `process_single'
  from sidekiq/client.rb:65:in `push'
  from sidekiq/worker.rb:84:in `client_push'
  from sidekiq/worker.rb:40:in `perform_async'
   APPLICATION_LEVEL_CODE
  from bundle/ruby/2.1.0/bin/unicorn:23:in `load'
  from bundle/ruby/2.1.0/bin/unicorn:23:in `<main>'
Redis::TimeoutError: Redis::TimeoutError
  from redis/connection/ruby.rb:55:in `rescue in _read_from_socket'
  from redis/connection/ruby.rb:48:in `_read_from_socket'
  from redis/connection/ruby.rb:41:in `gets'
  from redis/connection/ruby.rb:273:in `read'
  from redis/client.rb:229:in `block in read'
  from redis/client.rb:220:in `io'
  from redis/client.rb:228:in `read'
  from redis/client.rb:162:in `block in call_pipelined'
  from redis/client.rb:201:in `block (2 levels) in process'
  from redis/client.rb:309:in `ensure_connected'
  from redis/client.rb:191:in `block in process'
  from redis/client.rb:270:in `logging'
  from redis/client.rb:190:in `process'
  from redis/client.rb:161:in `call_pipelined'
  from redis/client.rb:133:in `block in call_pipeline'
  from redis/client.rb:257:in `with_reconnect'
  from redis/client.rb:131:in `call_pipeline'
  from new_relic/agent/instrumentation/redis.rb:58:in `block in call_pipeline'
  from new_relic/agent/datastores.rb:111:in `block in wrap'
  from new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
  from new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
  from new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
  from new_relic/agent/datastores.rb:108:in `wrap'
  from new_relic/agent/instrumentation/redis.rb:57:in `call_pipeline'
  from redis.rb:2094:in `block in multi'
  from redis.rb:37:in `block in synchronize'
  from monitor.rb:211:in `mon_synchronize'
  from redis.rb:37:in `synchronize'
  from redis.rb:2086:in `multi'
  from sidekiq-status/storage.rb:16:in `block in store_for_id'
  from sidekiq-status/storage.rb:102:in `block in redis_connection'
  from connection_pool.rb:64:in `block (2 levels) in with'
  from connection_pool.rb:63:in `handle_interrupt'
  from connection_pool.rb:63:in `block in with'
  from connection_pool.rb:60:in `handle_interrupt'
  from connection_pool.rb:60:in `with'
  from sidekiq-status/storage.rb:101:in `redis_connection'
  from sidekiq-status/storage.rb:15:in `store_for_id'
  from sidekiq-status/client_middleware.rb:26:in `call'
  from sidekiq/middleware/chain.rb:129:in `block in invoke'
  from sidekiq/middleware/chain.rb:132:in `call'
  from sidekiq/middleware/chain.rb:132:in `invoke'
  from sidekiq/client.rb:207:in `process_single'
  from sidekiq/client.rb:65:in `push'
  from sidekiq/worker.rb:84:in `client_push'
  from sidekiq/worker.rb:40:in `perform_async'
  APPLICATION_LEVEL_CODE
  from bundle/ruby/2.1.0/bin/unicorn:23:in `<main>'

Redis::TimeoutError: Connection timed out
  from redis/client.rb:222:in `rescue in io'
  from redis/client.rb:220:in `io'
  from redis/client.rb:228:in `read'
  from redis/client.rb:162:in `block in call_pipelined'
  from redis/client.rb:201:in `block (2 levels) in process'
  from redis/client.rb:309:in `ensure_connected'
  from redis/client.rb:191:in `block in process'
  from redis/client.rb:270:in `logging'
  from redis/client.rb:190:in `process'
  from redis/client.rb:161:in `call_pipelined'
  from redis/client.rb:133:in `block in call_pipeline'
  from redis/client.rb:257:in `with_reconnect'
  from redis/client.rb:131:in `call_pipeline'
  from new_relic/agent/instrumentation/redis.rb:58:in `block in call_pipeline'
  from new_relic/agent/datastores.rb:111:in `block in wrap'
  from new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
  from new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
  from new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
  from new_relic/agent/datastores.rb:108:in `wrap'
  from new_relic/agent/instrumentation/redis.rb:57:in `call_pipeline'
  from redis.rb:2094:in `block in multi'
  from redis.rb:37:in `block in synchronize'
  from monitor.rb:211:in `mon_synchronize'
  from redis.rb:37:in `synchronize'
  from redis.rb:2086:in `multi'
  from sidekiq-status/storage.rb:16:in `block in store_for_id'
  from sidekiq-status/storage.rb:102:in `block in redis_connection'
  from connection_pool.rb:64:in `block (2 levels) in with'
  from connection_pool.rb:63:in `handle_interrupt'
  from connection_pool.rb:63:in `block in with'
  from connection_pool.rb:60:in `handle_interrupt'
  from connection_pool.rb:60:in `with'
  from sidekiq-status/storage.rb:101:in `redis_connection'
  from sidekiq-status/storage.rb:15:in `store_for_id'
  from sidekiq-status/client_middleware.rb:26:in `call'
  from sidekiq/middleware/chain.rb:129:in `block in invoke'
  from sidekiq/middleware/chain.rb:132:in `call'
  from sidekiq/middleware/chain.rb:132:in `invoke'
  from sidekiq/client.rb:207:in `process_single'
  from sidekiq/client.rb:65:in `push'
  from sidekiq/worker.rb:84:in `client_push'
  from sidekiq/worker.rb:40:in `perform_async'
   APPLICATION_LEVEL_CODE
  from bundle/ruby/2.1.0/bin/unicorn:23:in `load'
  from bundle/ruby/2.1.0/bin/unicorn:23:in `<main>'
```
**sidekiq.rb**

```
require 'sidekiq'
require 'sidekiq-status'

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware
  end
end

  Sidekiq.configure_server do |config|
    config.server_middleware do |chain|
      chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes # default
    end
    config.client_middleware do |chain|
      chain.add Sidekiq::Status::ClientMiddleware
    end
  end

```

**runAsAsync.rb**
objects that wants to perform async jobs inherits from this class.

```

class RunAsAsync

  include Sidekiq::Worker
  include Sidekiq::Status::Worker

  sidekiq_options retry: false

   def perform(method, *args)
    begin
      class_name = args.pop

      class_obj = Object.const_get(class_name)

      if class_obj.respond_to?('instance'.to_sym) #if this is singletone class
        class_obj = class_obj.instance
      else
        class_obj = class_obj.new
      end

      class_obj.send(method.to_sym, *args) if class_obj.respond_to?(method.to_sym)

    rescue Exception => e
#     log error
    end
  end


  def method_missing(method_name, *arguments, &block)
    method_name = method_name.to_s

    if method_name.downcase.end_with? '_async'       
      method = method_name.gsub('_async', '').to_sym      
        arguments.push self.class.name
        RunAsAsync.perform_async(method, *arguments)      
    else
      super(method_name.to_sym, *arguments)
    end
  end

end
```

Thank you.

**Comment by mperham** [comment]
Show your initializer

**Comment by frenkelor** [comment]
bundle exec sidekiq -c 5

**Comment by mperham** [comment]
Everything looks fine to me.  Make sure you aren't swapping and monitor your latency:

https://github.com/mperham/sidekiq/wiki/Using-Redis#life-in-the-cloud

**Comment by frenkelor** [comment]
`redis-cli --latency and --latency-history` looks ok
regarding to redis initialization i can't find network_timeout property inside redis client is it should be `timeout` ? (the default is 5.0 already)

https://github.com/redis/redis-rb/blob/master/lib/redis/client.rb#L14

**Comment by mperham** [comment]
See https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/redis_connection.rb

**Comment by frenkelor** [comment]
Ok I'll try that,
Thanks

**Comment by rgaufman** [comment]
What's the correct way to increase the timeout that is 1 second by default? 

Is it like this? 

```ruby
Sidekiq.configure_server do |config|
  config.redis = { url: ENV.fetch('SIDEKIQ_REDIS_URL', 'redis://127.0.0.1:6379/1'), pool_timeout: 5 }
end
```

**Comment by mperham** [comment]
@rgaufman Please review https://github.com/mperham/sidekiq/wiki/Using-Redis, which documents that option.
