### ISSUE TITLE
Rails 5beta2 errors on load when I require sidekiq/web

### ISSUE THREAD

**Issue by hmistry** [mperham/sidekiq#2960]
Hi

In my Rails app, the app gives the following error on load and fails to start when I tried to add the Sidekiq web ui to monitor it. I isolated the line to `require 'sidekiq/web'` in routes.rb! I couldn't find any hints online for this. Any suggestions on how I can solve this?

Thanks,
Hiren

Using Ruby 2.3.0, Rails 5.0.0.beta2 and Sidekiq 4.1.1.

```
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require': cannot load such file -- rack/showexceptions (LoadError)
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `block in require'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:268:in `load_dependency'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
  from /Users/hm/.rvm/gems/ruby-2.3.0@loop_server/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `block in require'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:268:in `load_dependency'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
  from /Users/hm/.rvm/gems/ruby-2.3.0@loop_server/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `block in require'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:268:in `load_dependency'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
  from /Users/hm/.rvm/gems/ruby-2.3.0@loop_server/gems/sidekiq-4.1.1/lib/sidekiq/web.rb:3:in `<top (required)>'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `block in require'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:268:in `load_dependency'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
  from /Users/hm/Documents/Loop/Server/Rails Projects/loop_server/config/routes.rb:1:in `<top (required)>'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:296:in `load'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:296:in `block in load'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:268:in `load_dependency'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:296:in `load'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:40:in `each'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:16:in `reload!'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:26:in `block in updater'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/file_update_checker.rb:75:in `execute'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:27:in `updater'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/initializable.rb:30:in `instance_exec'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/initializable.rb:30:in `run'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  from /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  from /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  from /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  from /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
  from /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
  from /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  from /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  from /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/initializable.rb:54:in `run_initializers'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/application.rb:350:in `initialize!'
  from /Users/hm/Documents/Loop/Server/Rails Projects/loop_server/config/environment.rb:5:in `<top (required)>'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `block in require'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:268:in `load_dependency'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
  from /Users/hm/Documents/Loop/Server/Rails Projects/loop_server/config.ru:3:in `block in <main>'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `instance_eval'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `initialize'
  from /Users/hm/Documents/Loop/Server/Rails Projects/loop_server/config.ru:in `new'
  from /Users/hm/Documents/Loop/Server/Rails Projects/loop_server/config.ru:in `<main>'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `eval'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `new_from_string'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.0.alpha/lib/rack/builder.rb:40:in `parse_file'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.0.alpha/lib/rack/server.rb:318:in `build_app_and_options_from_config'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.0.alpha/lib/rack/server.rb:218:in `app'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/commands/server.rb:58:in `app'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.0.alpha/lib/rack/server.rb:353:in `wrapped_app'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/commands/server.rb:136:in `log_to_stdout'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/commands/server.rb:76:in `start'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:90:in `block in server'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:85:in `tap'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:85:in `server'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/command.rb:20:in `run'
  from /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.beta2/lib/rails/commands.rb:19:in `<top (required)>'
  from /Users/hm/Documents/Loop/Server/Rails Projects/loop_server/bin/rails:9:in `require'
  from /Users/hm/Documents/Loop/Server/Rails Projects/loop_server/bin/rails:9:in `<top (required)>'
  from /Users/hm/.rvm/gems/ruby-2.3.0@loop_server/gems/spring-1.6.3/lib/spring/client/rails.rb:28:in `load'
  from /Users/hm/.rvm/gems/ruby-2.3.0@loop_server/gems/spring-1.6.3/lib/spring/client/rails.rb:28:in `call'
  from /Users/hm/.rvm/gems/ruby-2.3.0@loop_server/gems/spring-1.6.3/lib/spring/client/command.rb:7:in `call'
  from /Users/hm/.rvm/gems/ruby-2.3.0@loop_server/gems/spring-1.6.3/lib/spring/client.rb:28:in `run'
  from /Users/hm/.rvm/gems/ruby-2.3.0@loop_server/gems/spring-1.6.3/bin/spring:49:in `<top (required)>'
  from /Users/hm/.rvm/gems/ruby-2.3.0@loop_server/gems/spring-1.6.3/lib/spring/binstub.rb:11:in `load'
  from /Users/hm/.rvm/gems/ruby-2.3.0@loop_server/gems/spring-1.6.3/lib/spring/binstub.rb:11:in `<top (required)>'
  from /Users/hm/Documents/Loop/Server/Rails Projects/loop_server/bin/spring:13:in `require'
  from /Users/hm/Documents/Loop/Server/Rails Projects/loop_server/bin/spring:13:in `<top (required)>'
  from bin/rails:3:in `load'
  from bin/rails:3:in `<main>'

```

**Comment by mperham** [comment]
Upgrade to rails 5rc1.

**Comment by hmistry** [comment]
@mperham Can we reopen this issue? I updated my Rails app to 5rc1 and all my gems to the latest ones bundler resolves to. However it's still failing with the same error.

I also tried creating a fresh new rails project with default settings, edited the Gemfile and added sidekiq and sinatra to it. Ran bundle and then add the `require 'sidekiq/web` and `mount Sidekiq::Web => '/sidekiq'` in routes and still same error. This is a clean fresh project with nothing inside. Rails works if I comment those 2 lines out.

I also noticed Sinatra v1.0 is being installed by bundler while the new version is 1.4.7. Is that causing the issue?

**Comment by mperham** [comment]
This is because you aren't using the proper rack version.  You need 2.0.alpha.

**Comment by ujh** [comment]
But Sinatra has a dependency on rack `~> 1.5` so until they release a new version that allows usage of rack 2 it's not possible to use the Sidekiq web, isn't it?

**Comment by mperham** [comment]
You need Sinatra master. They have not released a prerelease gem.

**Comment by ujh** [comment]
I see, thank you! 👍

**Comment by hmistry** [comment]
@mperham I was using Rack 2.0.0.rc1, which I assume is ok. The correct answer is forcing Sinatra to use master. 

Thanks for your help and quick responses!

**Comment by chrisnicola** [comment]
This is still a problem with the Rails release and Rack 2.0.1 without both `sinatra` and `sinatra/rack-protection` installed from master.

```
  # Required for Sidekiq::Web
  gem 'sinatra', github: 'sinatra', require: false 
  gem 'rack-protection', github: 'sinatra/rack-protection', require: false
  # Required for Sidekiq::Web
```

Works.
