### ISSUE TITLE
cant find Schema on the Worker class

### ISSUE THREAD

**Issue by Frank004** [mperham/sidekiq#3005]
I have a multi-tenant app with apartment gem.
when I run my worker with sidekiq can't find the tenant so the task is done on the correct tenant. 
I'm trying to filter the task by the correct tenant.
if I run the code in the terminal I get the correct result. 
There's a problem with the apartment-sidekiq gem so I was trying it without the gem and still get the same  error.

any help will be appreciated.

info about problem using the apartment-sidekiq gem:
[https://github.com/influitive/apartment-sidekiq/issues/11](url)

```
class MyWorker
  include Sidekiq::Worker
  def perform(subdomain, name, number)
    Apartment::Tenant.switch(subdomain) do
      tenant = Apartment::Tenant.current
      TestMailer.test_email(tenant, subdomain, name, number).deliver_now
    end
  end
end
```

```
rails c
irb(main):081:0*   def perform(subdomain, name, number)
irb(main):082:1>     Apartment::Tenant.switch(subdomain) do
irb(main):083:2*       tenant = Apartment::Tenant.current
irb(main):084:2>       TestMailer.test_email(tenant, subdomain, name, number).deliver_now
irb(main):085:2>     end
irb(main):086:1>   end
=> :perform
irb(main):087:0> perform("companydemo", "Pepe", 3)
  Rendered test_mailer/test_email.html.erb (0.7ms)

TestMailer#test_email: processed outbound mail in 17.5ms

Sent mail to xxxxxxxx@gmail.com (6.3ms)
Date: Tue, 07 Jun 2016 16:15:02 -0400
From: xxxxxxxxxxx@gmail.com
To: xxxxxxxx@gmail.com
Subject: =?UTF-8?Q?HBM_Registraci=C3=B3n?=
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Test</h1>
    <p>
     the subdoamin is  companydemo,
     <br>the schema is companydemo
     <br>,Pepe
     <br>,3
     <br>
    </p>
  </body>
</html>
```
```
the error 

16:21:00 worker.1  | 2016-06-07T20:21:00.289Z 6973 TID-owaevv4ao MyWorker JID-c59c6dd1513384f4a9fcaf77 INFO: fail: 0.006 sec
16:21:00 worker.1  | 2016-06-07T20:21:00.289Z 6973 TID-owaevv4ao WARN: {"class"=>"MyWorker", "args"=>["companydemo", "Juan", 1], "retry"=>true, "queue"=>"default", "jid"=>"c59c6dd1513384f4a9fcaf77", "created_at"=>1465330555.1693819, "enqueued_at"=>1465330860.27119, "error_message"=>"One of the following schema(s) is invalid: \"companydemo\" \"public\"", "error_class"=>"Apartment::TenantNotFound", "failed_at"=>1465330569.770862, "retry_count"=>4, "retried_at"=>1465330860.2888288}
16:21:00 worker.1  | 2016-06-07T20:21:00.289Z 6973 TID-owaevv4ao WARN: Apartment::TenantNotFound: One of the following schema(s) is invalid: "companydemo" "public"
16:21:00 worker.1  | 2016-06-07T20:21:00.289Z 6973 TID-owaevv4ao WARN: /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/apartment-1.1.0/lib/apartment/adapters/postgresql_adapter.rb:72:in `rescue in connect_to_new'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/apartment-1.1.0/lib/apartment/adapters/postgresql_adapter.rb:65:in `connect_to_new'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/apartment-1.1.0/lib/apartment/adapters/abstract_adapter.rb:85:in `switch!'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/apartment-1.1.0/lib/apartment/adapters/abstract_adapter.rb:98:in `switch'
16:21:00 worker.1  | /Users/IFrank/Documents/HBQuality/hbquality/app/workers/my_worker.rb:4:in `perform'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/processor.rb:80:in `execute_job'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/processor.rb:56:in `block (2 levels) in process'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:366:in `perform_action_with_newrelic_trace'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/logging.rb:30:in `with_context'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/server/logging.rb:7:in `call'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/chain.rb:132:in `invoke'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/processor.rb:51:in `block in process'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/processor.rb:104:in `stats'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/processor.rb:50:in `process'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
16:21:00 worker.1  | /Users/IFrank/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'

```

**Comment by ryansch** [comment]
There's a gem for this: https://github.com/influitive/apartment-sidekiq

**Comment by Frank004** [comment]
@ryansch is having the same problem. so Im looking for a way to do this without the gem as is not working at the moment.  check my post again plis :)

**Comment by mperham** [comment]
Just as a side note, passing the tenant as a job argument is a hack.  The correct way to implement a cross-cutting concern (like tenant) is with client and server middleware.  You just need to copy and configure the two bits of code here:

https://github.com/influitive/apartment-sidekiq/tree/master/lib/apartment/sidekiq/middleware

**Comment by Frank004** [comment]
@mperham  Thank yes I'm just trying to find a way by doing this type of thing I'm learning some new stuff. I will read your link maybe get the apartement-sidekiq gem running again. will update this post with the progress or solución. thank you.  any other comment are very welcome.

**Comment by ryansch** [comment]
We're not using apartment to do this and we're just loading the server side middleware towards the end of the stack.  I'd recommend using `chain.add` instead of `chain.insert_before`.

This is almost certainly not a bug in sidekiq as we've been using our own middleware to do this since sidekiq 2.x without any changes (now on 4.x).

**Comment by Frank004** [comment]
@ryansch  Thanx for your time. I was looking some light on this matter. now I have some info. I will close this and update the post for future dev. in my shoes.

**Comment by typeoneerror** [comment]
FYI, @Frank004 and I resolved this issue [here](http://stackoverflow.com/a/41471241/53653) in case anyone was experiencing a similar issue.
