### ISSUE TITLE
LoadError: cannot load such file -- sidekiq/url

### ISSUE THREAD

**Issue by SendOTP** [mperham/sidekiq#3009]
```
(in /Users/sameer/Documents/Projects/thesearch)
rake aborted!
LoadError: cannot load such file -- sidekiq/url
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/Users/sameer/Documents/Projects/thesearch/lib/assets/commonutility.rb:1:in `<top (required)>'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/Users/sameer/Documents/Projects/thesearch/jobs/v2/csvprocessor.rb:3:in `<top (required)>'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/Users/sameer/Documents/Projects/thesearch/lib/tasks/worker.rake:1:in `<top (required)>'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/railties-4.2.5/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/railties-4.2.5/lib/rails/engine.rb:658:in `each'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/railties-4.2.5/lib/rails/engine.rb:658:in `run_tasks_blocks'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/railties-4.2.5/lib/rails/application.rb:452:in `run_tasks_blocks'
/Users/sameer/.rvm/gems/ruby-2.2.4@global/gems/railties-4.2.5/lib/rails/engine.rb:453:in `load_tasks'
/Users/sameer/Documents/Projects/thesearch/Rakefile:5:in `<top (required)>'
/Users/sameer/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/Users/sameer/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

```

M getting this error don't know why

**Comment by mperham** [comment]
Looks like it is being required in `thesearch/lib/assets/commonutility.rb`.
