### ISSUE TITLE
Sidekiq jobs stuck in Enqueued after Redis goes away and comes back

### ISSUE THREAD

**Issue by jcrispw** [mperham/sidekiq#3057]
Ruby version: ruby 2.2.4p230
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.1.4

After stopping and starting Redis while Sidekiq is running, most (not all) jobs are stuck for ever in Enqueued and never get to Busy. After restarting Sidekiq (without touching Redis), they all get processed quickly. We had this problem in production after AWS retired and 'transparently' replaced our Redis instance with a new one with the same data. We can duplicate it locally also by stopping and starting Redis.

Gemfile.lock: https://gist.github.com/jcrispw/2e1a7c5b8e2bd2915d8ffd070d1cf278
Sidekiq.yml: https://gist.github.com/jcrispw/e6a13d30d21127ad0fd1c56a77fdb797
(we do use "sidekiq-limit_fetch")

To reproduce,

Stop Redis, get lots of:
```13:59:36 sidekiq.1 | 2016-07-11T03:59:36.722Z 84711 TID-oxj560z30 ERROR: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)```

wait a minute or two

Start redis, get lots of:
```14:00:35 sidekiq.1 | 2016-07-11T04:00:35.801Z 84711 TID-oxj5riqeo INFO: Redis is online, 95.317722 sec downtime```

Enqueued is full of jobs, but busy is 0. Our highest priority queue still seems to process ok but all other jobs in other queues just mount up in Enqueued and never enter Busy.

kill -TTIN  shows:
```bash
14:32:02 sidekiq.1 | 2016-07-11T04:32:01.955Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:267:in `with_socket_timeout'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:195:in `call_with_timeout'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis.rb:1097:in `block in _bpop'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis.rb:1094:in `_bpop'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/redis-3.2.2/lib/redis.rb:1139:in `brpop'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-limit_fetch-3.3.0/lib/sidekiq/limit_fetch.rb:49:in `block in redis_brpop'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq.rb:92:in `block in redis'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq.rb:89:in `redis'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-limit_fetch-3.3.0/lib/sidekiq/limit_fetch.rb:49:in `redis_brpop'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-limit_fetch-3.3.0/lib/sidekiq/limit_fetch.rb:24:in `retrieve_work'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:86:in `get_one'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:96:in `fetch'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.003Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:79:in `process_one'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.004Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:68:in `run'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.004Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:17:in `watchdog'
14:32:02 sidekiq.1 | 2016-07-11T04:32:02.004Z 84986 TID-owtrucee8 ERROR: /Users/james/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by mperham** [comment]
Can't reproduce it with stock Sidekiq.  You'll need to reproduce this without limit-fetch.  You've replaced Sidekiq's core fetch logic with a 3rd party plugin so I can't support that.
