### ISSUE TITLE
Sidekiq lost redis connection

### ISSUE THREAD

**Issue by lesnka** [mperham/sidekiq#3058]
Ruby version: 2.2.1
Sidekiq / Pro / Enterprise version(s): 3.5.4
I have this error
```
NoMethodError
Sidekiq::Web/GET /

Jul 6, '16 1:48 am
TIME
'web.1'(puma:customers-zone)
INSTANCE
1
COUNT
19 similar errors to this
in 30 minutes ending 07/06 01:57
Next error
Error message
NoMethodError: undefined method `info' for nil:NilClass

Stack trace (show Rails)
…by/2.2.0/gems/sidekiq-3.5.4/lib/sidekiq/
web_helpers.rb: 126:in `block in redis_info'
…or/bundle/ruby/2.2.0/gems/sidekiq-3.5.4/lib/
sidekiq.rb:  84:in `block in redis'
….2.0/gems/connection_pool-2.2.0/lib/
connection_pool.rb:  64:in `block (2 levels) in with'
….2.0/gems/connection_pool-2.2.0/lib/
connection_pool.rb:  63:in `handle_interrupt'
….2.0/gems/connection_pool-2.2.0/lib/
connection_pool.rb:  63:in `block in with'
….2.0/gems/connection_pool-2.2.0/lib/
connection_pool.rb:  60:in `handle_interrupt'
….2.0/gems/connection_pool-2.2.0/lib/
connection_pool.rb:  60:in `with'
…or/bundle/ruby/2.2.0/gems/sidekiq-3.5.4/lib/
sidekiq.rb:  81:in `redis'
…by/2.2.0/gems/sidekiq-3.5.4/lib/sidekiq/
web_helpers.rb: 120:in `redis_info'
…undle/ruby/2.2.0/gems/sidekiq-3.5.4/lib/sidekiq/
web.rb: 201:in `block in <class:Web>'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1611:in `call'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1611:in `block in compile!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 975:in `[]'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 975:in `block (3 levels) in route!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 994:in `route_eval'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 975:in `block (2 levels) in route!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1015:in `block in process_route'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1013:in `catch'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1013:in `process_route'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 973:in `block in route!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 972:in `each'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 972:in `route!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1085:in `block in dispatch!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1067:in `block in invoke'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1067:in `catch'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1067:in `invoke'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1082:in `dispatch!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 907:in `block in call!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1067:in `block in invoke'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1067:in `catch'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1067:in `invoke'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 907:in `call!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 895:in `call'
…ack-protection-1.5.3/lib/rack/protection/
xss_header.rb:  18:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…protection-1.5.3/lib/rack/protection/
path_traversal.rb:  16:in `call'
…rack-protection-1.5.3/lib/rack/protection/
json_csrf.rb:  18:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…-protection-1.5.3/lib/rack/protection/
frame_options.rb:  31:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…ack-protection-1.5.3/lib/rack/protection/
xss_header.rb:  18:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…protection-1.5.3/lib/rack/protection/
path_traversal.rb:  16:in `call'
…rack-protection-1.5.3/lib/rack/protection/
json_csrf.rb:  18:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…-protection-1.5.3/lib/rack/protection/
frame_options.rb:  31:in `call'
…/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/
id.rb: 225:in `context'
…/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/
id.rb: 220:in `call'
…ndle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/
nulllogger.rb:   9:in `call'
…dor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/
head.rb:  13:in `call'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 182:in `call'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:2013:in `call'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1487:in `block in call'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1787:in `synchronize'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1487:in `call'
…dle/ruby/2.2.0/gems/warden-1.2.6/lib/warden/
manager.rb:  35:in `block in call'
…dle/ruby/2.2.0/gems/warden-1.2.6/lib/warden/
manager.rb:  34:in `catch'
…dle/ruby/2.2.0/gems/warden-1.2.6/lib/warden/
manager.rb:  34:in `call'
…dor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/
etag.rb:  24:in `call'
…/ruby/2.2.0/gems/rack-1.6.4/lib/rack/
conditionalget.rb:  25:in `call'
…dor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/
head.rb:  13:in `call'
…/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/
id.rb: 225:in `context'
…/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/
id.rb: 220:in `call'
…/ruby/2.2.0/gems/rack-1.6.4/lib/rack/
methodoverride.rb:  22:in `call'
…/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/
runtime.rb:  18:in `call'
…r/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/
static.rb: 124:in `call'
…bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/
sendfile.rb: 113:in `call'
…/ruby/2.2.0/gems/puma-2.16.0/lib/puma/
configuration.rb:  81:in `call'
…/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/
server.rb: 557:in `handle_request'
…/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/
server.rb: 404:in `process_client'
…/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/
server.rb: 270:in `block in run'
…le/ruby/2.2.0/gems/puma-2.16.0/lib/puma/
thread_pool.rb: 106:in `call'
…le/ruby/2.2.0/gems/puma-2.16.0/lib/puma/
thread_pool.rb: 106:in `block in spawn_thread'
```
And this error
```
Error message
NoMethodError: undefined method `multi' for nil:NilClass

Sample stack trace (show Rails)
…ems/sidekiq-status-0.5.4/lib/sidekiq-status/
storage.rb:  16:in `block in store_for_id'
…ems/sidekiq-status-0.5.4/lib/sidekiq-status/
storage.rb: 103:in `block in redis_connection'
….2.0/gems/connection_pool-2.2.0/lib/
connection_pool.rb:  64:in `block (2 levels) in with'
….2.0/gems/connection_pool-2.2.0/lib/
connection_pool.rb:  63:in `handle_interrupt'
….2.0/gems/connection_pool-2.2.0/lib/
connection_pool.rb:  63:in `block in with'
….2.0/gems/connection_pool-2.2.0/lib/
connection_pool.rb:  60:in `handle_interrupt'
….2.0/gems/connection_pool-2.2.0/lib/
connection_pool.rb:  60:in `with'
…ems/sidekiq-status-0.5.4/lib/sidekiq-status/
storage.rb: 102:in `redis_connection'
…ems/sidekiq-status-0.5.4/lib/sidekiq-status/storage.rb:  15:in `store_for_id'
…ems/sidekiq-status-0.5.4/lib/sidekiq-status/
storage.rb:  32:in `store_status'
…q-status-0.5.4/lib/sidekiq-status/client_middleware.rb:  11:in `call'
…2.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/
chain.rb: 129:in `block in invoke'
…2.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/chain.rb: 132:in `call'
…2.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/chain.rb: 132:in `invoke'
…le/ruby/2.2.0/gems/sidekiq-3.5.4/lib/sidekiq/client.rb: 208:in `process_single'
…le/ruby/2.2.0/gems/sidekiq-3.5.4/lib/sidekiq/client.rb:  65:in `push'
…le/ruby/2.2.0/gems/sidekiq-3.5.4/lib/sidekiq/worker.rb:  98:in `client_push'
…le/ruby/2.2.0/gems/sidekiq-3.5.4/lib/sidekiq/worker.rb:  54:in `perform_async'
/app/app/controllers/reports/report_items_controller.rb:  90:in `params_to_session'
…0/gems/actionview-4.2.5.1/lib/action_view/rendering.rb:  30:in `process'
```

This is my puma.rb
```
workers Integer(ENV['PUMA_WORKERS'] || 2)
threads Integer(ENV['MIN_THREADS']  || 1), Integer(ENV['MAX_THREADS'] || 32)

preload_app!

rackup DefaultRackup
port ENV['PORT'] || 3000
environment ENV['RACK_ENV'] || 'development'

prune_bundler

on_worker_boot do
  if defined?(ActiveRecord::Base)
    ActiveSupport.on_load(:active_record) do
      ActiveRecord::Base.establish_connection
    end
    Rails.logger.info('Connected to ActiveRecord')
  end

  if defined?(REDIS)
    uri = URI.parse(App.redis)
    REDIS = Redis.new(host: uri.host, port: uri.port, password: uri.password)
    Rails.logger.info('Connected to Redis')
  end

  sidekiq_redis = { :url => ENV["REDIS_URL"] }
  Sidekiq.configure_server do |config|
    config.redis = sidekiq_redis
  end
  Sidekiq.configure_client do |config|
    config.redis = ConnectionPool.new(size: (Sidekiq.server? ? 15 : 1), timeout: 5) do
      uri = URI.parse(App.redis)
      Redis.new(host: uri.host, port: uri.port, password: uri.password)
    end
  end
end

```

This is my sidekiq.rb

```
require 'sidekiq'
require 'sidekiq/web'
require 'sidekiq-cron'
require 'sidekiq-status'

Sidekiq.default_worker_options = { backtrace: true, retry: false }

Sidekiq.configure_server do |config|
  config.redis = { url: App.redis }
  if ENV['DATABASE_URL'].present?
    database_url = "#{ENV['DATABASE_URL']}?pool=25"
    ActiveRecord::Base.establish_connection(database_url)
  else
    ActiveRecord::Base.establish_connection
  end
   config.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes # default
  end
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware
  end
  Sidekiq::Cron::Job.load_from_hash YAML.load_file(Rails.root.join('config', 'sidekiq_cron.yml'))
end

Sidekiq.configure_client do |config|
  config.redis = { url: App.redis }
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware
  end
end
```

**Comment by mperham** [comment]
No clue.
