### ISSUE TITLE
ActiveRecord connection timeout when using AR in sidekiq_retries_exhausted

### ISSUE THREAD

**Issue by cubicme** [mperham/sidekiq#3126]
Ruby version: 2.3
Sidekiq version: 4.1.1

When using active record in sidekiq_retries_exhausted block, the connection is not autoamatically released and eventually all the jobs in the process encounter ActiveRecord::ConnectionTimeoutError.

I tried to isolate the problem with a worker like this:
```
class FailingWorker
  include Sidekiq::Worker

  sidekiq_options queue: :failing_queue, retry: 1

  sidekiq_retries_exhausted do |_|
    ARModel.count
  end

  sidekiq_retry_in do |count|
    3
  end

  def perform
    raise 'error'
  end
end
```

of course connection_pool.with_connection can work around this.

backtrace:
```
2016-09-07_03:22:10.94354 2016-09-07T03:22:10.943Z 9614 TID-gnofc4fis WARN: {"class"=>"FailingWorker", "args"=>[], "retry"=>1, "queue"=>"failing_queue", "jid"=>"060a5589f770cfc14930
85c2", "created_at"=>1473217854.5579226, "enqueued_at"=>1473218459.1340067, "error_message"=>"could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)", "e
rror_class"=>"ActiveRecord::ConnectionTimeoutError", "failed_at"=>1473218451.9996374, "retry_count"=>1, "retried_at"=>1473218525.9343078}
2016-09-07_03:22:10.94361 2016-09-07T03:22:10.943Z 9614 TID-gnofc4fis WARN: ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds (waited
 5.000 seconds)
2016-09-07_03:22:10.94374 2016-09-07T03:22:10.943Z 9614 TID-gnofc4fis WARN: /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/connec
tion_adapters/abstract/connection_pool.rb:190:in `block in wait_poll'
2016-09-07_03:22:10.94376 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `
loop'
2016-09-07_03:22:10.94378 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `
wait_poll'
2016-09-07_03:22:10.94379 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:136:in `
block in poll'
2016-09-07_03:22:10.94380 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
2016-09-07_03:22:10.94382 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:146:in `
synchronize'
2016-09-07_03:22:10.94383 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:134:in `
poll'
2016-09-07_03:22:10.94384 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:418:in `
acquire_connection'
2016-09-07_03:22:10.94385 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `
block in checkout'
2016-09-07_03:22:10.94386 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
2016-09-07_03:22:10.94387 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `
checkout'
2016-09-07_03:22:10.94388 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `
block in connection'
2016-09-07_03:22:10.94389 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
2016-09-07_03:22:10.94391 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
2016-09-07_03:22:10.94392 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
2016-09-07_03:22:10.94393 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
2016-09-07_03:22:10.94394 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/connection_handling.rb:87:in `connection'
2016-09-07_03:22:10.94395 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/relation/calculations.rb:265:in `execute_simple_calculat
ion'
2016-09-07_03:22:10.94396 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/relation/calculations.rb:227:in `perform_calculation'
2016-09-07_03:22:10.94398 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/relation/calculations.rb:119:in `calculate'
2016-09-07_03:22:10.94399 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/relation/calculations.rb:34:in `count'
2016-09-07_03:22:10.94400 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.1.14/lib/active_record/querying.rb:13:in `count'
2016-09-07_03:22:10.94401 /vagrant/app/workers/failing_worker.rb:17:in `perform'
2016-09-07_03:22:10.94402 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:151:in `execute_job'
2016-09-07_03:22:10.94403 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:133:in `block (2 levels) in process'
2016-09-07_03:22:10.94404 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
2016-09-07_03:22:10.94406 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-statistic-1.2.0/lib/sidekiq/statistic/middleware.rb:10:in `call'
2016-09-07_03:22:10.94407 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
2016-09-07_03:22:10.94408 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
2016-09-07_03:22:10.94409 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
2016-09-07_03:22:10.94410 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
2016-09-07_03:22:10.94411 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
2016-09-07_03:22:10.94412 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
2016-09-07_03:22:10.94413 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/logging.rb:31:in `with_context'
2016-09-07_03:22:10.94414 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
2016-09-07_03:22:10.94415 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
2016-09-07_03:22:10.94416 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
2016-09-07_03:22:10.94417 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:128:in `block in process'
2016-09-07_03:22:10.94418 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:167:in `stats'
2016-09-07_03:22:10.94420 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:127:in `process'
2016-09-07_03:22:10.94421 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:79:in `process_one'
2016-09-07_03:22:10.94422 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:67:in `run'
2016-09-07_03:22:10.94423 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:16:in `watchdog'
2016-09-07_03:22:10.94424 /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by mperham** [comment]
Yes this would be a nice edge case to fix.

**Comment by mperham** [comment]
Ok, I played with your FailingWorker code (thanks!) and used `ActiveRecord::Base.connection_pool.connections.select { |c| c.in_use? }.length` to inspect the connection pool.  After running a bunch of jobs, there are a few connections still checked out but they are reclaimed when I run further jobs.

I feel like the current behavior isn't perfect but acceptable.  The RetryJobs middleware runs the exhausted block and that middleware runs **after** the ActiveRecord middleware, so the connection is not released immediately.  **BUT** Sidekiq discards any thread which ran a job that threw an error and Rails will reclaim any connection associated with a thread that has been garbage collected.  So while the connection will be checked out longer than necessary, the connection will be reclaimed when a job runs and finishes after that GC cycle.

Unfortunately I can't think of a good way to clean up the connection immediately.  As you said, if you want to avoid this, you can use the `with_connection` block form so that the connection can be reclaimed immediately.
