### ISSUE TITLE
Sidekiq not launching: No such file to load -- command_line_reporter (LoadError)

### ISSUE THREAD

**Issue by charlesdg** [mperham/sidekiq#3129]
Hello all,

Ruby version: 2.3.1
Sidekiq version: 4.1.4

Not able to launch sidekiq anymore:
`require': No such file to load -- command_line_reporter (LoadError)`

Here is the backtrace:

```
/Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require': No such file to load -- command_line_reporter (LoadError)
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:238:in `block in load_dependency'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:238:in `load_dependency'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/charlesdegroote/dev/sortlist/app/assets/javascripts/node_modules/node-sass/test/fixtures/spec/lib/sass_spec/annotate/cli.rb:4:in `<top (required)>'
	from /Users/charlesdegroote/dev/sortlist/app/assets/javascripts/node_modules/node-sass/test/fixtures/spec/lib/sass_spec/annotate.rb:6:in `require_relative'
	from /Users/charlesdegroote/dev/sortlist/app/assets/javascripts/node_modules/node-sass/test/fixtures/spec/lib/sass_spec/annotate.rb:6:in `<top (required)>'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:457:in `load'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:456:in `load_file'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:317:in `depend_on'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:233:in `require_dependency'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:471:in `each'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:471:in `block in eager_load!'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:469:in `each'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:469:in `eager_load!'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:346:in `eager_load!'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/application/finisher.rb:56:in `each'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `public_send'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `method_missing'
	from /Users/charlesdegroote/dev/sortlist/config/environment.rb:7:in `<top (required)>'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/cli.rb:237:in `boot_system'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/cli.rb:50:in `run'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.4/bin/sidekiq:12:in `<top (required)>'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/bin/sidekiq:23:in `load'
	from /Users/charlesdegroote/.rbenv/versions/2.3.1/bin/sidekiq:23:in `<main>'
```

Thanks!

**Comment by mperham** [comment]
You are missing the command_line_reporter gem.

**Comment by mperham** [comment]
It should be noted that this error has nothing to do with Sidekiq but is required by this thing:

app/assets/javascripts/node_modules/node-sass/test/fixtures/spec/lib/sass_spec/annotate/cli.rb:4:in `<top (required)>'
