### ISSUE TITLE
uninitialized constant MyWorker sometimes

### ISSUE THREAD

**Issue by zhangliwen** [mperham/sidekiq#3131]
Ruby version:2, Rails version: 4.0.9
Sidekiq  version(s): 4.0.0

It has a single job 

```ruby
class CacheColorSizeStorageWorker
  include Sidekiq::Worker

  def perform ids
    color_sizes = ColorSize.where(id: ids)
    color_sizes.each { |cs| cs.reset_sum_storage }
  end
end
```

And then I perform the code twice : 

```ruby
CacheColorSizeStorageWorker.perform_async([3769, 3774, 3779, 3770, 3775, 3780, 3771, 3776, 3781, 3772, 3777, 3782, 3773, 3778, 3783])
```

Finally, I'm getting the following:

```
2016-09-12T00:55:38.487Z 10848 TID-1fmnng CacheColorSizeStorageWorker JID-77880d63264d5be296e7b5d9 INFO: start
2016-09-12T00:55:39.248Z 10848 TID-1fmnng CacheColorSizeStorageWorker JID-77880d63264d5be296e7b5d9 INFO: done: 0.761 sec
2016-09-12T00:55:54.049Z 27664 TID-ouwg6osu0 WARN: {"class"=>"CacheColorSizeStorageWorker", "args"=>[[3769, 3774, 3779, 3770, 3775, 3780, 3771, 3776, 3781, 3772, 3777, 3782, 3773, 3778, 3783]], "retry"=>true, "queue"=>"default", "jid"=>"76d85f0aaca0138ead2a2677", "created_at"=>1473641754.0475354, "enqueued_at"=>1473641754.0476172}
2016-09-12T00:55:54.049Z 27664 TID-ouwg6osu0 WARN: NameError: uninitialized constant CacheColorSizeStorageWorker
2016-09-12T00:55:54.049Z 27664 TID-ouwg6osu0 WARN: /alidata/app/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.9/lib/active_support/inflector/methods.rb:226:in `const_get'
/alidata/app/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.9/lib/active_support/inflector/methods.rb:226:in `block in constantize'
/alidata/app/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.9/lib/active_support/inflector/methods.rb:224:in `each'
/alidata/app/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.9/lib/active_support/inflector/methods.rb:224:in `inject'
/alidata/app/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.9/lib/active_support/inflector/methods.rb:224:in `constantize'
/alidata/app/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.9/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/alidata/app/shared/bundle/ruby/2.0.0/gems/sidekiq-4.0.0/lib/sidekiq/processor.rb:122:in `process'
/alidata/app/shared/bundle/ruby/2.0.0/gems/sidekiq-4.0.0/lib/sidekiq/processor.rb:79:in `process_one'
/alidata/app/shared/bundle/ruby/2.0.0/gems/sidekiq-4.0.0/lib/sidekiq/processor.rb:67:in `run'
/alidata/app/shared/bundle/ruby/2.0.0/gems/sidekiq-4.0.0/lib/sidekiq/util.rb:16:in `watchdog'
/alidata/app/shared/bundle/ruby/2.0.0/gems/sidekiq-4.0.0/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

It`s say : uninitialized constant CacheColorSizeStorageWorker
why uninitialized Worker sometimes?
what can I do for it?

Thanks for sidekiq! :)

**Comment by seuros** [comment]
The worker is not in a autoloading path probably.

Also update your sidekiq version.

**Comment by zhangliwen** [comment]
the first time is init:
```
2016-09-12T00:55:38.487Z 10848 TID-1fmnng CacheColorSizeStorageWorker JID-77880d63264d5be296e7b5d9 INFO: start
2016-09-12T00:55:39.248Z 10848 TID-1fmnng CacheColorSizeStorageWorker JID-77880d63264d5be296e7b5d9 INFO: done: 0.761 sec
```

if it is because autoloading path, why it could perform in first time?

**Comment by seuros** [comment]
Please provide a sample app that reproduce the bug after upgrading sidekiq version and rails patch version.

**Comment by zhangliwen** [comment]
ok, I will upgrade version now, thanks!

**Comment by mperham** [comment]
@seuros is right, you'll need to provide us with a minimal rails app which reproduces your problem.  It's most likely the problem is in the app code or configuration.
