### ISSUE TITLE
uninitialized constant error (pure Ruby)

### ISSUE THREAD

**Issue by tommybstitch** [mperham/sidekiq#3156]
Ruby version: 2.0.0
Sidekiq version: 3.3.4

I'm working on implementing Sidekiq in a pure Ruby project (no Rails) with my workers located in `./app/workers`. 

I am running the following command to start my workers:

```
bundle exec sidekiq -C ../config/sidekiq.yml -r ../config/development.rb -L log/sidekiq.log
```

The `development.rb` file includes all of the necessary `require` statements as follows: 

```
Dir.glob('./app/*').each do |folder|
  Dir.glob(folder +"/*.rb").each do |file|
    require file
  end
end
```

When a worker is picked up from the Sidekiq queue, I am getting an `uninitialized constant FooBarWorker`. 

The Sidekiq log backtrace is as follows: 

```
2016-09-22T00:01:15.406Z 65461 TID-ovl9c02tc WARN: {"class"=>"FooBarWorker", "args"=>[9, 9], "retry"=>1, "queue"=>"project", "backtrace"=>true, "jid"=>"25a88721ffb1d4c918acbeb9", "enqueued_at"=>1474502475.404654}
2016-09-22T00:01:15.407Z 65461 TID-ovl9c02tc WARN: uninitialized constant FooBarWorker
2016-09-22T00:01:15.407Z 65461 TID-ovl9c02tc WARN: /Users/user/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:261:in `const_get'
/Users/user/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:261:in `block in constantize'
/Users/user/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `each'
/Users/user/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `inject'
/Users/user/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `constantize'
/Users/user/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.2.7.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/Users/user/.rvm/gems/ruby-2.0.0-p598/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:46:in `process'
/Users/user/.rvm/gems/ruby-2.0.0-p598/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/Users/user/.rvm/gems/ruby-2.0.0-p598/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/Users/user/.rvm/gems/ruby-2.0.0-p598/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
/Users/user/.rvm/gems/ruby-2.0.0-p598/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/Users/user/.rvm/gems/ruby-2.0.0-p598/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/Users/user/.rvm/gems/ruby-2.0.0-p598/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/Users/user/.rvm/gems/ruby-2.0.0-p598/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/Users/user/.rvm/gems/ruby-2.0.0-p598/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by mperham** [comment]
You aren't requiring a class with that name.

**Comment by tommybstitch** [comment]
@mperham The follow block recursively requires all the workers:

```
Dir.glob('./app/*').each do |folder|
  Dir.glob(folder +"/*.rb").each do |file|
    require file
  end
end
```

**Comment by mperham** [comment]
I realize that but you require a file; that doesn't mean the class matches that filename.  Perhaps you have FoobarWorker?

**Comment by tommybstitch** [comment]
Yes, I just verified that the classname matches the filename.

**Comment by mikegee** [comment]
Stick some debugging statements while you iterate over those files:

```ruby
puts "requiring #{file}"
require file
puts defined?(FooBarWorker)
```
