### ISSUE TITLE
heartbeat: When assigning attributes, you must pass a hash as an argument

### ISSUE THREAD

**Issue by brutus333** [mperham/sidekiq#3167]
Ruby version: ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
Sidekiq / Pro / Enterprise version(s): Sikekiq 4.2.1
Problem description: I implemented a json processor which uploads data in a database. It is based on sinatra and Sidekiq: the client posts a json payload which is written in a file locally and a Sidekiq worker is called with file path as argument. The worker processes the file when called and write rows in the database.
The loader worked pretty well for some time. Now, when I added a slightly different payload I got the following error and the jobs remain in enqueued state. If I restart Sidekiq the jobs will be processed immediately.

```
2016-09-28T12:19:53.858Z 9 TID-oqzimcpe4 INFO: Booting Sidekiq 4.2.1 with redis options {:url=>"redis://redis:6379"}
2016-09-28T12:19:53.858Z 9 TID-oqzimcpe4 INFO: Running in ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
2016-09-28T12:19:53.858Z 9 TID-oqzimcpe4 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2016-09-28T12:19:53.858Z 9 TID-oqzimcpe4 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2016-09-28T12:19:53.943Z 9 TID-oqzimcpe4 DEBUG: Client Middleware:
2016-09-28T12:19:53.943Z 9 TID-oqzimcpe4 DEBUG: Server Middleware: Sidekiq::Middleware::Server::Logging, Sidekiq::Middleware::Server::RetryJobs, Sidekiq::Middleware::Server::ActiveRecord
2016-09-28T12:19:53.943Z 9 TID-oqzimcpe4 INFO: Starting processing, hit Ctrl-C to stop
2016-09-28T12:19:54.061Z 9 TID-oqzimcpe4 DEBUG: {:queues=>["default"], :labels=>[], :concurrency=>5, :require=>"./lib/some_worker.rb", :environment=>nil, :timeout=>8, :poll_interval_average=>nil, :average_scheduled_poll_interval=>15, :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x007f0122a25740>], :lifecycle_events=>{:startup=>[], :quiet=>[], :shutdown=>[], :heartbeat=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :reloader=>#<Proc:0x007f0122a663d0@/usr/local/bundle/gems/sidekiq-4.2.1/lib/sidekiq.rb:35>, :verbose=>true, :pidfile=>"/var/run/sidekiq.pid", :logfile=>"/var/log/sidekiq.log", :config_file=>"./config/sidekiq.yml", :strict=>true, :identity=>"49ab292dca10:9:03bc4d8e4d59"}
2016-09-28T12:21:03.695Z 9 TID-oqzixtcas SomeWorker JID-3825396ee1d5f3ba40be0659 INFO: start
2016-09-28T12:21:03.735Z 9 TID-oqzixtbxg SomeWorker JID-ba6e66cc9ccdd7c913d45be8 INFO: start
2016-09-28T12:21:14.104Z 9 TID-oqzixtbxg SomeWorker JID-ba6e66cc9ccdd7c913d45be8 INFO: done: 10.369 sec
2016-09-28T12:21:14.342Z 9 TID-oqzixtcas SomeWorker JID-3825396ee1d5f3ba40be0659 INFO: done: 10.647 sec
2016-09-28T12:21:32.056Z 9 TID-oqzixtbxg SomeWorker JID-ff148bd8275d5c9d5c6e7860 INFO: start
2016-09-28T12:21:34.123Z 9 TID-oqzixtcus ERROR: heartbeat: When assigning attributes, you must pass a hash as an argument.
2016-09-28T12:21:39.124Z 9 TID-oqzixtcus ERROR: heartbeat: When assigning attributes, you must pass a hash as an argument.
2016-09-28T12:21:43.071Z 9 TID-oqzixtbxg SomeWorker JID-ff148bd8275d5c9d5c6e7860 INFO: done: 11.016 sec
2016-09-28T12:21:44.125Z 9 TID-oqzixtcus ERROR: heartbeat: When assigning attributes, you must pass a hash as an argument.
2016-09-28T12:21:49.126Z 9 TID-oqzixtcus ERROR: heartbeat: When assigning attributes, you must pass a hash as an argument.
2016-09-28T12:21:50.129Z 9 TID-oqzixtcp8 ERROR: When assigning attributes, you must pass a hash as an argument.
2016-09-28T12:21:50.129Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:25:in `assign_attributes'
2016-09-28T12:21:50.129Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/core.rb:566:in `init_attributes'
2016-09-28T12:21:50.129Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/core.rb:281:in `initialize'
2016-09-28T12:21:50.129Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/inheritance.rb:61:in `new'
2016-09-28T12:21:50.130Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/inheritance.rb:61:in `new'
2016-09-28T12:21:50.130Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis/connection/ruby.rb:405:in `format_multi_bulk_reply'
2016-09-28T12:21:50.130Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis/connection/ruby.rb:376:in `format_reply'
2016-09-28T12:21:50.130Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis/connection/ruby.rb:364:in `read'
2016-09-28T12:21:50.130Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:262:in `block in read'
2016-09-28T12:21:50.130Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:250:in `io'
2016-09-28T12:21:50.130Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:261:in `read'
2016-09-28T12:21:50.130Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:120:in `block in call'
2016-09-28T12:21:50.131Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:231:in `block (2 levels) in process'
2016-09-28T12:21:50.131Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:367:in `ensure_connected'
2016-09-28T12:21:50.131Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:221:in `block in process'
2016-09-28T12:21:50.131Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:306:in `logging'
2016-09-28T12:21:50.131Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:220:in `process'
2016-09-28T12:21:50.131Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:120:in `call'
2016-09-28T12:21:50.131Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis.rb:1794:in `block in zrangebyscore'
2016-09-28T12:21:50.132Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis.rb:58:in `block in synchronize'
2016-09-28T12:21:50.132Z 9 TID-oqzixtcp8 ERROR: /usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
2016-09-28T12:21:50.132Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis.rb:58:in `synchronize'
2016-09-28T12:21:50.132Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/redis-3.3.1/lib/redis.rb:1793:in `zrangebyscore'
2016-09-28T12:21:50.132Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/sidekiq-4.2.1/lib/sidekiq/scheduled.rb:20:in `block (2 levels) in enqueue_jobs'
2016-09-28T12:21:50.132Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/sidekiq-4.2.1/lib/sidekiq/scheduled.rb:15:in `each'
2016-09-28T12:21:50.133Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/sidekiq-4.2.1/lib/sidekiq/scheduled.rb:15:in `block in enqueue_jobs'
2016-09-28T12:21:50.133Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/sidekiq-4.2.1/lib/sidekiq.rb:94:in `block in redis'
2016-09-28T12:21:50.133Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
2016-09-28T12:21:50.133Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
2016-09-28T12:21:50.133Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
2016-09-28T12:21:50.133Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
2016-09-28T12:21:50.133Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
2016-09-28T12:21:50.133Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/sidekiq-4.2.1/lib/sidekiq.rb:91:in `redis'
2016-09-28T12:21:50.133Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/sidekiq-4.2.1/lib/sidekiq/scheduled.rb:14:in `enqueue_jobs'
2016-09-28T12:21:50.133Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/sidekiq-4.2.1/lib/sidekiq/scheduled.rb:77:in `enqueue'
2016-09-28T12:21:50.133Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/sidekiq-4.2.1/lib/sidekiq/scheduled.rb:68:in `block in start'
2016-09-28T12:21:50.133Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/sidekiq-4.2.1/lib/sidekiq/util.rb:17:in `watchdog'
2016-09-28T12:21:50.134Z 9 TID-oqzixtcp8 ERROR: /usr/local/bundle/gems/sidekiq-4.2.1/lib/sidekiq/util.rb:25:in `block in safe_thread'
2016-09-28T12:21:54.129Z 9 TID-oqzixtcus ERROR: heartbeat: When assigning attributes, you must pass a hash as an argument.
2016-09-28T12:21:59.131Z 9 TID-oqzixtcus ERROR: heartbeat: When assigning attributes, you must pass a hash as an argument.
2016-09-28T12:22:04.132Z 9 TID-oqzixtcus ERROR: heartbeat: When assigning attributes, you must pass a hash as an argument.
2016-09-28T12:22:09.133Z 9 TID-oqzixtcus ERROR: heartbeat: When assigning attributes, you must pass a hash as an argument.
2016-09-28T12:22:09.702Z 9 TID-oqzixtcp8 ERROR: When assigning attributes, you must pass a hash as an argument.
```

Not sure if it's a Sidekiq issue but please give me some troubleshooting hints. I tried to find something relevant on the net but I could find nothing.

Thank you,
Virgil

**Comment by mperham** [comment]
> when I added a slightly different payload

Show us this different payload.

**Comment by brutus333** [comment]
ok, let me tell you a bit about the JSON payload.
Let's assume that I want to update several tables in the database. The JSON will be a hash with two keys: 'data' & 'common'. The value of the 'data' key is another hash with table names as keys and corresponding rows as arrays in the value of "table name" key. In the 'common' key we are keeping value for columns that are applicable on all tables.
The different payload only has different tables in the data hash.
You can find bellow one example of failed payload. The weird thing is that the heartbeat error is occurring immediately after processing the payload - all processing steps finish successfully but other jobs get stuck in the enqueued state.
{
    "common": {
        "assettype": "3PARdata",
        "collectedattime": 1475132555,
        "entityid": "127.0.0.1"
    },
    "data": {
        "arrays": [
            {
                "allocatedcapacitymb": 4318208.0,
                "capacitymb": 35549184.0,
                "firmwareversion": "3.2.2.390",
                "freecapacitymb": 31230976.0,
                "ipaddress": "10.10.10.10",
                "name": "Flask",
                "nodenumber": 2,
                "serialnumber": "1234567",
                "uniqueid": 12345
            }
        ],
        "luns": [
            {
                "adminused": 131072,
                "baseid": 1,
                "createdat": 1348524733,
                "name": "UnitTestVolume",
                "provtype": "FULL",
                "serialnumber": "2AC00001383D",
                "sizekb": 104857600,
                "snapused": 524288,
                "state": "NORMAL",
                "tier": "UnitTestAOCFG",
                "uniqueid": 91,
                "used": 104857600
            },
            {
                "adminused": 131072,
                "baseid": 41,
                "createdat": 1348780316,
                "name": "UnitTestVolume2",
                "provtype": "FULL",
                "serialnumber": "2AC00029383D",
                "sizekb": 10485760,
                "snapused": 524288,
                "state": "NORMAL",
                "tier": "UnitTestAOCFG",
                "uniqueid": 92,
                "used": 10485760
            }
        ],
        "tieringpolicies": [
            {
                "mode": 3,
                "name": "UnitTestAOCFG",
                "tier0": "UnitTestCPG",
                "tier1": "UnitTestCPG1",
                "tier2": null,
                "uniqueid": 1
            }
        ],
        "tiers": [
            {
                "diskrpm": "",
                "disktype": "FC",
                "ha": "",
                "name": "UnitTestCPG",
                "raidtype": "",
                "uniqueid": 0
            },
            {
                "diskrpm": "",
                "disktype": "FC",
                "ha": "",
                "name": "UnitTestCPG2",
                "raidtype": "",
                "uniqueid": 0
            }
        ]
    }
}

**Comment by mperham** [comment]
I mean you said it worked with one payload and then failed with another, slightly different payload.  Show us this diff.  Show us the code for the Worker.

It feels like you've got a problem due to unexpected monkeypatching as your backtrace makes no sense.  The Redis gem should not ever call ActiveRecord directly.

**Comment by mperham** [comment]
Yeah, line 405 of ruby.rb in the redis gem does this:

```
       Array.new(n) { read }
 ```

Notice it doesn't put `::` before Array.  I bet you have a gem or code adding `Redis::Array` which is getting instantiated inadvertently.  I will open a Redis issue.

**Comment by brutus333** [comment]
Thank you so much, you saved the day.
Now, I must confess that I used meta-programming techniques a bit too much for my level of Ruby knowledge. My code was the culprit for redefining Array from redis code.
Here is the wrong code I wrote before:

```
  # Validate JSON structure
  # The transaction should rollback if any table insert fails
    begin
    ActiveRecord::Base.transaction do
      json['data'].keys.each do |name|
        p "Parsing #{name} object"
  ### Validate table existence
        raise "Table #{name} is missing" unless ActiveRecord::Base.connection.table_exists? name
        klass ||= Object.const_set camelize(singularize(name)), Class.new(ActiveRecord::Base)
          json['data'][name].each do |input|
            json['common'].keys.each do |key|
              input.merge!( key.to_sym => json['common'][key])
            end
            p "Updating DB with input #{input}"
            klass.create!(input)
          end
      end
    end
    rescue
      print "Failed database transaction"
      raise
    end

```


The error was in the fact that I was using Object.const_set without checking if the constant was already defined. That's why I was redefining Array (table name is arrays but in active record the object name becomes Array).

I rewritten quickly the code like this:


```
  # Validate JSON structure
  # The transaction should rollback if any table insert fails
    begin
    ActiveRecord::Base.transaction do
      json['data'].keys.each do |name|
        p "Parsing #{name} object"
  ### Validate table existence
        raise "Table #{name} is missing" unless ActiveRecord::Base.connection.table_exists? name
        begin
          Object.const_get camelize(singularize(name))
        rescue NameError
          klass ||= Object.const_set camelize(singularize(name)), Class.new(ActiveRecord::Base)
        end
          json['data'][name].each do |input|
            json['common'].keys.each do |key|
              input.merge!( key.to_sym => json['common'][key])
            end
            p "Updating DB with input #{input}"
            if klass
              klass.create!(input)
            else
              raise "Tried to override program constants. Name of the table #{name} conflicts with defined constants"
            end

          end
      end
    end
    rescue
      print "Failed database transaction"
      raise
    end

```

Now it capture the error and if by mistake one collector is sending a payload with a wrong name for the DB the Sidekiq will not be affected.

Thank you very much once again.

Virgil

**Comment by brutus333** [comment]
Sorry, I'm quite tired. After testing this was the right solution:

```
  # Validate JSON structure
  # The transaction should rollback if any table insert fails
    begin
    ActiveRecord::Base.transaction do
      json['data'].keys.each do |name|
        p "Parsing #{name} object"
  ### Validate table existence
        raise "Table #{name} is missing" unless ActiveRecord::Base.connection.table_exists? name
        begin
          klass = Object.const_get camelize(singularize(name))
        rescue NameError
          klass ||= Object.const_set camelize(singularize(name)), Class.new(ActiveRecord::Base)
        end
          json['data'][name].each do |input|
            json['common'].keys.each do |key|
              input.merge!( key.to_sym => json['common'][key])
            end
            p "Updating DB with input #{input}"
            if klass < ActiveRecord::Base
              klass.create!(input)
            else
              raise "Tried to override program constants. Name of the table #{name} conflicts with defined constants"
            end

          end
      end
    end
    rescue
      print "Failed database transaction"
      raise
    end

```
