### ISSUE TITLE
Pro Web UI not working after 4.2.2 upgrade

### ISSUE THREAD

**Issue by rufusroflpunch** [mperham/sidekiq#3169]
Ruby version: 2.1.9
Sidekiq / Pro / Enterprise version(s): 4.2.2 / 3.3.3 / 1.3.2

We are using Redis sharding, and the UI for the second shard is returning the following exception after upgrading:

```
> RuntimeError - can't modify frozen Hash:
  rack-protection (1.5.3) lib/rack/protection/xss_header.rb:20:in `call'
  rack-protection (1.5.3) lib/rack/protection/base.rb:49:in `call'
  rack-protection (1.5.3) lib/rack/protection/base.rb:49:in `call'
  rack-protection (1.5.3) lib/rack/protection/path_traversal.rb:16:in `call'
  rack-protection (1.5.3) lib/rack/protection/json_csrf.rb:18:in `call'
  rack-protection (1.5.3) lib/rack/protection/base.rb:49:in `call'
  rack-protection (1.5.3) lib/rack/protection/base.rb:49:in `call'
  rack-protection (1.5.3) lib/rack/protection/frame_options.rb:31:in `call'
  rack-protection (1.5.3) lib/rack/protection/base.rb:49:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  rack (1.6.4) lib/rack/urlmap.rb:66:in `block in call'
  rack (1.6.4) lib/rack/urlmap.rb:50:in `each'
  rack (1.6.4) lib/rack/urlmap.rb:50:in `call'
  rack (1.6.4) lib/rack/builder.rb:153:in `call'
  sidekiq (4.2.2) lib/sidekiq/web.rb:88:in `call'
  sidekiq (4.2.2) lib/sidekiq/web.rb:93:in `call'
  actionpack (4.2.7) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.7) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.7) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.7) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.7) lib/action_dispatch/routing/route_set.rb:817:in `call'
  browsernizer (0.2.4) lib/browsernizer/router.rb:19:in `call'
  bullet (5.1.1) lib/bullet/rack.rb:12:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `catch'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.7) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.7) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.7) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.7) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  wash_out (0.10.0) lib/wash_out/middleware.rb:8:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.7) lib/rails/engine.rb:518:in `call'
  railties (4.2.7) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
  thin (1.5.1) lib/thin/connection.rb:79:in `catch'
  thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
  thin (1.5.1) lib/thin/connection.rb:54:in `process'
  thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
  eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
  thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
  thin (1.5.1) lib/thin/server.rb:159:in `start'
  rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.7) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.7) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.7) lib/rails/commands/commands_tasks.rb:75:in `tap'
  railties (4.2.7) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.7) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.7) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `require'
  bin/rails:4:in `<main>'
```

Here is how we are mounting the UIs in our routes.rb:

```ruby
mount Sidekiq::Web => '/admin/sidekiq'
mount Sidekiq::Pro::Web.with(redis_pool: SECONDARY_REDIS_POOL), at: '/admin/sidekiq_secondary', as: 'sidekiq_secondary'
```

According to the Sharding wiki page, only the Pro UI supports multiple Web UIs, so I did what the Pro UI wiki page recommended and attempted to mount them like this:

```ruby
mount Sidekiq::Pro::Web => '/admin/sidekiq'
mount Sidekiq::Pro::Web.with(redis_pool: SECONDARY_REDIS_POOL), at: '/admin/sidekiq_secondary', as: 'sidekiq_secondary'`
```

But then we get the following exception + stacktrace:

```
> RuntimeError - A rack application must be specified:
  actionpack (4.2.7) lib/action_dispatch/routing/mapper.rb:580:in `mount'
  config/routes.rb:9:in `block (2 levels) in <top (required)>'
  devise (3.5.10) lib/devise/rails/routes.rb:287:in `block in authenticate'
  devise (3.5.10) lib/devise/rails/routes.rb:473:in `block in constraints_for'
  actionpack (4.2.7) lib/action_dispatch/routing/mapper.rb:941:in `block in constraints'
  actionpack (4.2.7) lib/action_dispatch/routing/mapper.rb:817:in `scope'
  actionpack (4.2.7) lib/action_dispatch/routing/mapper.rb:941:in `constraints'
  devise (3.5.10) lib/devise/rails/routes.rb:472:in `constraints_for'
  devise (3.5.10) lib/devise/rails/routes.rb:286:in `authenticate'
  config/routes.rb:8:in `block in <top (required)>'
  actionpack (4.2.7) lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
  actionpack (4.2.7) lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
  actionpack (4.2.7) lib/action_dispatch/routing/route_set.rb:410:in `draw'
  config/routes.rb:4:in `<top (required)>'
  activesupport (4.2.7) lib/active_support/dependencies.rb:268:in `load'
  activesupport (4.2.7) lib/active_support/dependencies.rb:268:in `block in load'
  activesupport (4.2.7) lib/active_support/dependencies.rb:240:in `load_dependency'
  activesupport (4.2.7) lib/active_support/dependencies.rb:268:in `load'
  railties (4.2.7) lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
  railties (4.2.7) lib/rails/application/routes_reloader.rb:40:in `each'
  railties (4.2.7) lib/rails/application/routes_reloader.rb:40:in `load_paths'
  railties (4.2.7) lib/rails/application/routes_reloader.rb:16:in `reload!'
  railties (4.2.7) lib/rails/application/routes_reloader.rb:26:in `block in updater'
  activesupport (4.2.7) lib/active_support/file_update_checker.rb:75:in `call'
  activesupport (4.2.7) lib/active_support/file_update_checker.rb:75:in `execute'
  railties (4.2.7) lib/rails/application/routes_reloader.rb:7:in `execute'
  railties (4.2.7) lib/rails/application/finisher.rb:81:in `block (2 levels) in <module:Finisher>'
  activesupport (4.2.7) lib/active_support/callbacks.rb:446:in `instance_exec'
  activesupport (4.2.7) lib/active_support/callbacks.rb:446:in `block in make_lambda'
  activesupport (4.2.7) lib/active_support/callbacks.rb:192:in `call'
  activesupport (4.2.7) lib/active_support/callbacks.rb:192:in `block in simple'
  activesupport (4.2.7) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.7) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.7) lib/active_support/callbacks.rb:504:in `each'
  activesupport (4.2.7) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.7) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.7) lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
  activesupport (4.2.7) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7) lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
  actionpack (4.2.7) lib/action_dispatch/middleware/reloader.rb:71:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  wash_out (0.10.0) lib/wash_out/middleware.rb:8:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.7) lib/rails/engine.rb:518:in `call'
  railties (4.2.7) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
  thin (1.5.1) lib/thin/connection.rb:79:in `catch'
  thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
  thin (1.5.1) lib/thin/connection.rb:54:in `process'
  thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
  eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
  thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
  thin (1.5.1) lib/thin/server.rb:159:in `start'
  rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.7) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.7) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.7) lib/rails/commands/commands_tasks.rb:75:in `tap'
  railties (4.2.7) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.7) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.7) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `require'
  bin/rails:4:in `<main>'
```

**Comment by mperham** [comment]
I suspect this was broken by https://github.com/mperham/sidekiq/commit/ba3037d63e4fe8558b3c6f5b345017beea8509eb
