### ISSUE TITLE
Mailer classes cannot be found with sidekiq 4.2.1

### ISSUE THREAD

**Issue by fschwahn** [mperham/sidekiq#3171]
I'm having trouble with sidekiq 4.2.1 not finding mailer classes. The error is: `ArgumentError: undefined class/module InvitationMailer` (see stacktrace below). My guess is that it has to do with the new autoloading in sidekiq 4.2.0 - when I downgrade to sidekiq 4.1.2 without changing anything else, the class can be found again. 

I'm using the i18n middleware, and it happens with the `DelayedMailer` extension. This error occurs with every Mailer-class I tried. This does not happen with workers I created myself.

Ruby version:
Sidekiq / Pro / Enterprise version(s):
Sidekiq 4.2.1
Rails 5.0.0.1

If relevant, please include your initializer and any error message with the full backtrace.
initializer:
```
require "sidekiq/middleware/i18n"

unless Rails.env.production?
  Sidekiq.configure_client do |config|
    config.redis = { namespace: "app" }
  end
  Sidekiq.configure_server do |config|
    config.redis = { namespace: "app" }
  end
end

# require "sidekiq/web"
```

stacktrace:
```
2016-09-30T09:32:31.679Z 98863 TID-oukn3icrs WARN: {"class":"Sidekiq::Extensions::DelayedMailer","args":["---\n- !ruby/class 'InvitationMailer'\n- :invitation\n- - 17\n  - 70\n  - 15\n"],"retry":true,"queue":"default","jid":"f5e1f8f351589bb75614944a","created_at":1475227911.949454,"locale":"de","enqueued_at":1475227951.658134,"error_message":"undefined class/module InvitationMailer","error_class":"ArgumentError","failed_at":1475227912.383342,"retry_count":1,"retried_at":1475227951.678529}
2016-09-30T09:32:31.679Z 98863 TID-oukn3icrs WARN: ArgumentError: undefined class/module InvitationMailer
2016-09-30T09:32:31.679Z 98863 TID-oukn3icrs WARN: /Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/class_loader.rb:54:in `path2class'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/class_loader.rb:54:in `resolve'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/class_loader.rb:46:in `find'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/class_loader.rb:28:in `load'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:396:in `resolve_class'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:88:in `deserialize'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:123:in `visit_Psych_Nodes_Scalar'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `block in register_empty'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `each'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `register_empty'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:141:in `visit_Psych_Nodes_Sequence'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/nodes/node.rb:38:in `to_ruby'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych.rb:253:in `load'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/extensions/action_mailer.rb:17:in `perform'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:155:in `execute_job'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:136:in `block (3 levels) in process'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/i18n.rb:22:in `call'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rollbar-2.11.5/lib/rollbar/plugins/sidekiq/plugin.rb:9:in `call'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/logging.rb:32:in `with_context'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:131:in `block (2 levels) in process'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:171:in `stats'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:130:in `block in process'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/rails.rb:47:in `block in call'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:76:in `wrap'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/reloader.rb:68:in `block in wrap'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:76:in `wrap'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/reloader.rb:67:in `wrap'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/rails.rb:46:in `call'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:122:in `process'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:81:in `process_one'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:69:in `run'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/util.rb:17:in `watchdog'
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by mperham** [comment]
In development, production or both?

**Comment by fschwahn** [comment]
Happens only in development.

**Comment by mperham** [comment]
Yep, in retrospect that's to be expected.  Now that we don't eager load classes, YAML can't look up class names successfully anymore - it doesn't know to use `constantize` to activate Rails's constant autoloading.  I'm not sure what to do here.

**Comment by fschwahn** [comment]
Hmm, that doesn't sound good. Is there any workaround for the time being (like somehow enabling eager loading in the `Sidekiq.configure_server`-block ?), or do you suggest downgrading to 4.1.2 until this is resolved?

**Comment by mperham** [comment]
I can't think of a resolution here - the functionality will not work with autoloading enabled.  You can enable eager loading or move away from the delay APIs.  The delay APIs were meant to be useful for people migrating from delayed_job to Sidekiq and not core functionality that should be used all the time.  You can update your `config/environment/development.rb` to disable autoloading like so:

```ruby
config.cache_classes = Sidekiq.server?
```

**Comment by fschwahn** [comment]
I just moved away from the delay APIs and I'm now using active_job to send the emails via sidekiq. I never even thought about the extension, because I always sent mails like that in all my projects. I didn't even know that you are not really supposed to use the extension - maybe the Wiki page should reflect that fact better. I even went ahead and put `Sidekiq.remove_delay!` in the initializer, so I don't accidentally use it again.

I think the documentation around this problem needs to be improved, and maybe the user should be shown a warning when starting sidekiq with the delay extensions enabled, and running Rails >= 5 in development. I'd imagine more and more people hitting this issue as they are upgrading rails and sidekiq.

**Comment by mperham** [comment]
Updated wiki with a warning.

**Comment by che-burashco** [comment]
I'm looking at the code in lib/sidekiq/cli.rb, and it looks like the Rails 4 in development environment will have the same issue. I was wondering whether it was intentional or not, and whether it would cause any issues related to multiple loading, if multi-threads processess are used?

**Comment by mperham** [comment]
The latest 4.2.6 should fix this.  Please report if it doesn't.

**Comment by che-burashco** [comment]
@mperham , I was experiencing the issue with not being able to use the delay extension using rails 4.2.6 and sidekiq 4.2.6.

From here: https://github.com/mperham/sidekiq/blob/v4.2.6/lib/sidekiq/cli.rb

```ruby
        elsif ::Rails::VERSION::MAJOR >= 4 && environment != 'development'
          # Painful contortions, see 1791 for discussion
          # No autoloading, we want to force eager load for everything.
          require File.expand_path("#{options[:require]}/config/application.rb")
          ::Rails::Application.initializer "sidekiq.eager_load" do
            ::Rails.application.config.eager_load = true
          end
          require 'sidekiq/rails'
          require File.expand_path("#{options[:require]}/config/environment.rb")
        else
          # Rails 5+ && development mode, use Reloader
          require 'sidekiq/rails'
          require File.expand_path("#{options[:require]}/config/environment.rb")
        end
```

An easy solution would be to modify the ::Rails::VERSION::MAJOR >= 4 to ::Rails::VERSION::MAJOR >= 5, if that was an original intention as per one of the comments

**Comment by mperham** [comment]
I've reproduced the problem with #3241 and will get a release out soon that fixes the delay functionality.
