### ISSUE TITLE
Broken pipe @ io_write - <STDERR> on sidekiq

### ISSUE THREAD

**Issue by siva3395** [mperham/sidekiq#3198]
Ruby version: 2.3.1p112
Sidekiq: 4.2.2

If relevant, please include your initializer and any error message with the full backtrace.

```
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: Broken pipe @ io_write - <STDERR>
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/options_with_fallback.rb:31:in `write'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/options_with_fallback.rb:31:in `warn'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/options_with_fallback.rb:31:in `unique_lock'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/options_with_fallback.rb:25:in `lock_class'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/options_with_fallback.rb:21:in `lock'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/client/middleware.rb:30:in `acquire_lock'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/client/middleware.rb:26:in `disabled_or_successfully_locked?'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-4.0.18/lib/sidekiq_unique_jobs/client/middleware.rb:18:in `call'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq/client.rb:206:in `process_single'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq/client.rb:65:in `push'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq/client.rb:126:in `push'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq/scheduled.rb:26:in `block (2 levels) in enqueue_jobs'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq/scheduled.rb:15:in `each'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq/scheduled.rb:15:in `block in enqueue_jobs'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq.rb:94:in `block in redis'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
2016-10-20T12:00:09.512Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
2016-10-20T12:00:09.513Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq.rb:91:in `redis'
2016-10-20T12:00:09.513Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq/scheduled.rb:14:in `enqueue_jobs'
2016-10-20T12:00:09.513Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq/scheduled.rb:77:in `enqueue'
2016-10-20T12:00:09.513Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq/scheduled.rb:68:in `block in start'
2016-10-20T12:00:09.513Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq/util.rb:17:in `watchdog'
2016-10-20T12:00:09.513Z 3236 TID-1hsiv0 ERROR: /home/ubuntu/app/ts_gds_app/shared/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.2/lib/sidekiq/util.rb:25:in `block in safe_thread'
^C
You have new mail in /var/mail/ubuntu
```

Hi, We are facing above issue. When ever we restart sidekiq it runs for 10 mins after that we are facing above issue. Could you please help us to solve this?

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/issues/3188
