### ISSUE TITLE
Bundle locked to hitimes (1.2.4)

### ISSUE THREAD

**Issue by bgvo** [mperham/sidekiq#3200]
Not sure is Sidekiq is responsible of this, but after executing `bundle update sidekiq` this error comes out when I try to run Sidekiq:

```
/var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/definition.rb:179:in `rescue in specs': Your bundle is locked to hitimes (1.2.4), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of hitimes (1.2.4) has removed it. You'll need to update your bundle to a different version of hitimes (1.2.4) that hasn't been removed in order to install. (Bundler::GemNotFound)
	from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/definition.rb:173:in `specs'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/definition.rb:233:in `specs_for'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/definition.rb:222:in `requested_specs'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/runtime.rb:118:in `block in definition_method'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/runtime.rb:19:in `setup'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler.rb:99:in `setup'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/setup.rb:20:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

I tried running `bundle update hitimes` but nothing changes.

Thank you.

**Comment by mperham** [comment]
Sidekiq does not use hitimes.  Most likely you are using a 3rd party Sidekiq extension which uses hitimes.  You need to tell Bundler it can update hitimes too: `bundle update sidekiq hitimes`
