### ISSUE TITLE
Ent: sidekiqswarm won't start with any value for SIDEKIQ_PRELOAD

### ISSUE THREAD

**Issue by jelder** [mperham/sidekiq#3217]
Ruby version: 2.2.4p230
Sidekiq / Pro / Enterprise version(s): sidekiq-4.2.3, sidekiq-pro-3.4.0, sidekiq-ent-1.3.2

This command line will start a swarm, but apparently without any memory savings from shared gems.
```
SIDEKIQ_PRELOAD= bundle exec sidekiqswarm
```

Without `SIDEKIQ_PRELOAD=`, or with `default,production` as suggested in the wiki, it fails with this stacktrace:
```
SIDEKIQ_PRELOAD=default,production bundle exec sidekiqswarm
[swarm] Preloading Bundler groups ["default", "production"]
/Users/jacob/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-action_caching-1.1.1/lib/action_controller/caching/actions.rb:104:in `<module:Actions>': uninitialized constant ActiveSupport::Concern (NameError)
        from /Users/jacob/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-action_caching-1.1.1/lib/action_controller/caching/actions.rb:103:in `<module:Caching>'
        from /Users/jacob/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-action_caching-1.1.1/lib/action_controller/caching/actions.rb:4:in `<module:ActionController>'
        from /Users/jacob/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-action_caching-1.1.1/lib/action_controller/caching/actions.rb:3:in `<top (required)>'
        from /Users/jacob/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-action_caching-1.1.1/lib/action_controller/action_caching.rb:1:in `require'
        from /Users/jacob/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-action_caching-1.1.1/lib/action_controller/action_caching.rb:1:in `<top (required)>'
        from /Users/jacob/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-action_caching-1.1.1/lib/actionpack/action_caching.rb:1:in `require'
        from /Users/jacob/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-action_caching-1.1.1/lib/actionpack/action_caching.rb:1:in `<top (required)>'
        from /Users/jacob/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:85:in `require'
        from /Users/jacob/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:85:in `rescue in block in require'
        from /Users/jacob/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:68:in `block in require'
        from /Users/jacob/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `each'
        from /Users/jacob/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `require'
        from /Users/jacob/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.9.7/lib/bundler.rb:134:in `require'
        from /Users/jacob/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-ent-1.3.2/bin/sidekiqswarm:42:in `<top (required)>'
        from /Users/jacob/.rbenv/versions/2.2.4/bin/sidekiqswarm:23:in `load'
        from /Users/jacob/.rbenv/versions/2.2.4/bin/sidekiqswarm:23:in `<main>'
```

**Comment by mperham** [comment]
You have the `actionpack-action_caching` gem in the wrong group.  It has a dependency on activesupport which is not being loaded.

**Comment by jelder** [comment]
That gem was at the top level, so I would have expected it to be loaded by `default`. Removing it just causes the stack trace to fail on the next top-level dependency in our Gemfile.

**Comment by mperham** [comment]
I don't know the inner details of Bundler preloading exactly so that surprises me.  Make sure you're on a recent version.  As for your Gemfile, the web of dependencies between gems can get complex and painful to configure correctly.  This is why I allow the preload to be turned off completely: some people just don't want to go through that trouble for what is typically modest memory savings.

**Comment by lazyatom** [comment]
In case it's useful to anyone else who finds this issue, another workaround is to ensure that Rails is loaded before invoking `sidekiqswarm`, by running something like

```ruby
rails runner bin/sidekiqswarm
```

This loads all the parts of Rails that gems assume are already in place (e.g. active support, action view and so on).
