### ISSUE TITLE
ArgumentError: undefined class/module Package

### ISSUE THREAD

**Issue by pezholio** [mperham/sidekiq#3238]
I've been using Sidekiq on a Rails project and it worked fine last week, and is working perfectly in production. I've come back to do some more work in development, and all of a sudden, the worker is throwing up a `ArgumentError: undefined class/module Package` error (Package is an ActiveRecord model). I'm running the job like so:

    @package = Package.create
    Package.delay.process(@package.id, params)

And the backtrace is thus:

```
2016-11-14T14:35:35.024Z 8972 TID-ouot0gtik WARN: {"context":"Job raised exception","job":{"queue":"queue:default","job":"{\"class\":\"Sidekiq::Extensions::DelayedClass\",\"args\":[\"---\\n- !ruby/class 'Package'\\n- :process\\n- - !ruby/object:BSON::ObjectId\\n    raw_data: !binary |-\\n      WCnGbU1hYxusAAAF\\n  - !ruby/hash-with-ivars:ActionController::Parameters\\n    elements:\\n      file_ids: \u00261\\n      - 1479132711-tpsgc-pwgsc_ao-t_a.csv,7\\n      schema: '0'\\n      schema_url: ''\\n      authenticity_token: au7RFZpR8D8uUgV7RWKP/3i3SnEoQtlJLTGpxnkNz+U=\\n      action: create\\n      controller: package\\n      format: json\\n    ivars:\\n      :@permitted: false\\n      :@converted_arrays: !ruby/object:Set\\n        hash:\\n          *1: true\\n\"],\"retry\":true,\"queue\":\"default\",\"jid\":\"a4ac01d4367feb91b7b62772\",\"created_at\":1479132781.399363,\"enqueued_at\":1479134135.022366,\"error_message\":\"undefined class/module Package\",\"error_class\":\"ArgumentError\",\"failed_at\":1479132781.4009652,\"retry_count\":5,\"retried_at\":1479133456.847669}"},"jobstr":"{\"class\":\"Sidekiq::Extensions::DelayedClass\",\"args\":[\"---\\n- !ruby/class 'Package'\\n- :process\\n- - !ruby/object:BSON::ObjectId\\n    raw_data: !binary |-\\n      WCnGbU1hYxusAAAF\\n  - !ruby/hash-with-ivars:ActionController::Parameters\\n    elements:\\n      file_ids: &1\\n      - 1479132711-tpsgc-pwgsc_ao-t_a.csv,7\\n      schema: '0'\\n      schema_url: ''\\n      authenticity_token: au7RFZpR8D8uUgV7RWKP/3i3SnEoQtlJLTGpxnkNz+U=\\n      action: create\\n      controller: package\\n      format: json\\n    ivars:\\n      :@permitted: false\\n      :@converted_arrays: !ruby/object:Set\\n        hash:\\n          *1: true\\n\"],\"retry\":true,\"queue\":\"default\",\"jid\":\"a4ac01d4367feb91b7b62772\",\"created_at\":1479132781.399363,\"enqueued_at\":1479134135.022366,\"error_message\":\"undefined class/module Package\",\"error_class\":\"ArgumentError\",\"failed_at\":1479132781.4009652,\"retry_count\":5,\"retried_at\":1479133456.847669}"}
2016-11-14T14:35:35.025Z 8972 TID-ouot0gtik WARN: ArgumentError: undefined class/module Package
2016-11-14T14:35:35.025Z 8972 TID-ouot0gtik WARN: /Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/class_loader.rb:54:in `path2class'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/class_loader.rb:54:in `resolve'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/class_loader.rb:46:in `find'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/class_loader.rb:28:in `load'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:396:in `resolve_class'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:88:in `deserialize'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:123:in `visit_Psych_Nodes_Scalar'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `block in register_empty'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `each'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `register_empty'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:141:in `visit_Psych_Nodes_Sequence'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/nodes/node.rb:38:in `to_ruby'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych.rb:253:in `load'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/extensions/class_methods.rb:17:in `perform'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/processor.rb:155:in `execute_job'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/processor.rb:136:in `block (3 levels) in process'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/logging.rb:32:in `with_context'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/processor.rb:131:in `block (2 levels) in process'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/processor.rb:171:in `stats'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/processor.rb:130:in `block in process'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/processor.rb:124:in `process'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/processor.rb:81:in `process_one'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/processor.rb:69:in `run'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/util.rb:17:in `watchdog'
/Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

It's almost as if my Rails environment isn't getting loaded. Any ideas?

Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.2.5

If relevant, please include your initializer and any error message with the full backtrace.

**Comment by pezholio** [comment]
I think I've sorted this by downgrading to 4.2.4 - are there any known issues with 4.2.5?

**Comment by mperham** [comment]
Try master, it might fix this.

**Comment by mperham** [comment]
4.2.6 is out which should fix this.
