### ISSUE TITLE
Sidekiq Web UI does not starts

### ISSUE THREAD

**Issue by USvER** [mperham/sidekiq#3248]
Ruby version:  ruby 2.2.3p173
Sidekiq / Pro / Enterprise version(s):  4.2.6

I try to start task for sidekiq web ui
```
namespace :sidekiq do
  desc "Sidekiq web"
  task web: :environment do
    require 'sidekiq/web'
    require 'sidekiq-status/web'
    require 'sidekiq/cron/web'
    app = Sidekiq::Web
    app.set :environment, :production
    app.set :bind, '0.0.0.0'
    app.set :port, 8080
    app.run!
  end
end
```

And get this
```
** Invoke sidekiq:web (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute sidekiq:web
rails aborted!
NoMethodError: undefined method `environment=' for Sidekiq::Web:Class
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-4.2.3/lib/sidekiq/web.rb:76:in `set'
/media/sf_dilitio/lib/tasks/sidekiq.rake:8:in `block (2 levels) in <top (required)>'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `call'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/root/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
/media/sf_dilitio/bin/rails:9:in `require'
/media/sf_dilitio/bin/rails:9:in `<top (required)>'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
/root/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
/root/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
/media/sf_dilitio/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => sidekiq:web
```

**Comment by USvER** [comment]
Sidekiq 4.1.4 does not have this issue.

**Comment by mperham** [comment]
That way of running Sidekiq::Web is no longer supported.  The easiest way to run Sidekiq::Web is with rackup:

https://github.com/mperham/sidekiq/blob/master/myapp/simple.ru#L2

**Comment by USvER** [comment]
I'm stumbled on this issue while debuging some weird bug with sidekiq that was not executing some of the tasks.
Reverted to 4.1.4 and everything working fine.
I want to read about this radical changes in 4.2.x, is there a document i can look into?

**Comment by mperham** [comment]
[Changelog](https://github.com/mperham/sidekiq/blob/master/Changes.md#420) points to #3075.
