### ISSUE TITLE
ActiveRecord times out even when not used in a job if the connection pool is empty

### ISSUE THREAD

**Issue by kreynolds** [mperham/sidekiq#3254]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.2.6 / 3.4.0 / 1.4.0

If relevant, please include your initializer and any error message with the full backtrace.
I've triple checked that there are no AR calls in this job and while I could be missing something still, it looks like it tries to get a connection even if it doesn't need one according to the backtrace.

```
2016-11-23T02:22:34.607Z 27199 TID-7ykv36o WARN: ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.145 seconds); all pooled connections were in use
```

```
activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `loop'
activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `wait_poll'
activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:154:in `internal_poll'
activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:278:in `internal_poll'
activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `block in poll'
/home/rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:158:in `synchronize'
activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `poll'
activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:709:in `acquire_connection'
activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:501:in `checkout'
activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:875:in `retrieve_connection'
activerecord-5.0.0.1/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord-5.0.0.1/lib/active_record/connection_handling.rb:91:in `connection'
activerecord-5.0.0.1/lib/active_record/query_cache.rb:27:in `run'
activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:39:in `block in register_hook'
activesupport-5.0.0.1/lib/active_support/callbacks.rb:396:in `instance_exec'
activesupport-5.0.0.1/lib/active_support/callbacks.rb:396:in `block in make_lambda'
activesupport-5.0.0.1/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
activesupport-5.0.0.1/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
activesupport-5.0.0.1/lib/active_support/callbacks.rb:546:in `catch'
activesupport-5.0.0.1/lib/active_support/callbacks.rb:546:in `block in default_terminator'
activesupport-5.0.0.1/lib/active_support/callbacks.rb:170:in `block in halting'
activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `block in call'
activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `each'
activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `call'
activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_run_callbacks'
activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:99:in `run!'
activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:61:in `block in run!'
activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:58:in `tap'
activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:58:in `run!'
activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:74:in `wrap'
sidekiq-4.2.6/lib/sidekiq/rails.rb:84:in `call'
sidekiq-4.2.6/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
sidekiq-4.2.6/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
sidekiq-pro-3.4.0/lib/sidekiq/batch/middleware.rb:33:in `call'
sidekiq-4.2.6/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
sidekiq-ent-1.4.0/lib/sidekiq-ent/unique.rb:124:in `call'
sidekiq-4.2.6/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
sidekiq-ent-1.4.0/lib/sidekiq-ent/limiter/middleware.rb:38:in `call'
sidekiq-4.2.6/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
sidekiq-4.2.6/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
sidekiq-4.2.6/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
sidekiq-4.2.6/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
sidekiq-4.2.6/lib/sidekiq/logging.rb:32:in `with_context'
sidekiq-4.2.6/lib/sidekiq/middleware/server/logging.rb:7:in `call'
sidekiq-4.2.6/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
sidekiq-4.2.6/lib/sidekiq/middleware/chain.rb:133:in `invoke'
sidekiq-4.2.6/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
sidekiq-4.2.6/lib/sidekiq/processor.rb:174:in `stats'
sidekiq-4.2.6/lib/sidekiq/processor.rb:131:in `block in process'
sidekiq-4.2.6/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
sidekiq-4.2.6/lib/sidekiq/processor.rb:126:in `process'
sidekiq-4.2.6/lib/sidekiq/processor.rb:82:in `process_one'
sidekiq-4.2.6/lib/sidekiq/processor.rb:70:in `run'
sidekiq-4.2.6/lib/sidekiq/util.rb:17:in `watchdog'
sidekiq-4.2.6/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by mperham** [comment]
This looks like a Rails 5 issue.

**Comment by kreynolds** [comment]
Alright well, I'll handle it with an external connection pooler then. I took a quick look at it and it doesn't look convenient to try to fix.

**Comment by mperham** [comment]
Well, you should open a Rails issue and see what the core team say.
