### ISSUE TITLE
sidekiq queue stuck in `safe_thread`

### ISSUE THREAD

**Issue by dymk** [mperham/sidekiq#3259]
Ruby version: 2.3.0
Sidekiq / Pro / Enterprise version(s): 4.2.6

`cat Gemfile.lock | grep sidekiq`:
```
    sidekiq (4.2.6)
    sidekiq-failures (0.4.5)
      sidekiq (>= 2.16.0)
    sidekiq-unique-jobs (4.0.18)
      sidekiq (>= 2.6)
  sidekiq
  sidekiq-failures
  sidekiq-unique-jobs
```

About once every few hours, Sidekiq will get stuck on a job, and no longer make any forward progress. Attaching `gdb` to the stuck process and dumping a backtrace shows that it's stuck in `safe_thread`: 

```
(gdb) call (void)rb_backtrace()
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.6/lib/sidekiq/util.rb:25:in `block in safe_thread'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.6/lib/sidekiq/util.rb:17:in `watchdog'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.6/lib/sidekiq/scheduled.rb:68:in `block in start'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.6/lib/sidekiq/scheduled.rb:77:in `enqueue'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.6/lib/sidekiq/scheduled.rb:14:in `enqueue_jobs'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.6/lib/sidekiq.rb:92:in `redis'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.6/lib/sidekiq.rb:95:in `block in redis'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.6/lib/sidekiq/scheduled.rb:15:in `block in enqueue_jobs'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.6/lib/sidekiq/scheduled.rb:15:in `each'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.6/lib/sidekiq/scheduled.rb:20:in `block (2 levels) in enqueue_jobs'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis.rb:1798:in `zrangebyscore'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis.rb:58:in `synchronize'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis.rb:58:in `block in synchronize'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis.rb:1799:in `block in zrangebyscore'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:120:in `call'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:220:in `process'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:306:in `logging'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:221:in `block in process'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:367:in `ensure_connected'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:231:in `block (2 levels) in process'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:120:in `block in call'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:261:in `read'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:250:in `io'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:262:in `block in read'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis/connection/ruby.rb:378:in `read'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis/connection/ruby.rb:74:in `gets'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis/connection/ruby.rb:82:in `_read_from_socket'
        from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.2/lib/redis/connection/ruby.rb:85:in `rescue in _read_from_socket'
```

Initializer: 

```ruby
    Sidekiq.default_worker_options = { 'backtrace' => true }
    Sidekiq.configure_server do |config|
      config.redis = { url: 'redis://localhost:6379', concurrency: 1,  }
      config.failures_max_count = 50000
    end

    Sidekiq.configure_server do |config|
      config.redis = { url: 'redis://localhost:6379', concurrency: 1,  }
    end
```

The web dashboard will show these workers as busy with a job, started X minutes ago, e.g. "48 minutes ago". This could be similar to #3134, but I'm not using any custom fetch gems.

**Comment by mperham** [comment]
That backtrace is likely a red herring.  You skipped the more important part, I need the gist of gdb_output.txt, as explained here:

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#frozen-processes
