### ISSUE TITLE
NameError: `@' is not allowed as an instance variable name - sidekiq_delay 

### ISSUE THREAD

**Issue by ak15** [mperham/sidekiq#3260]
Ruby version:
ruby 2.2.2p95 
Sidekiq / Pro / Enterprise version(s):
sidekiq (3.3.3)

Suppose we have service file
```
class AbcService
  def self.some_method
    # get some dynamic values such as v1 v2 which can be null or contain ActiveRecord object
    # call mailer with sidekiq_delay
    # suppose if v1 is (ActiveRecord_AssociationRelation )and we call Mailer method with sidekiq_delay 
    # Got following error NameError: `@' is not allowed as an instance variable name - sidekiq_delay error
    AbcMailer.sidekiq_delay.send_mail_to_user(v1, v2)

  end
end
```

**Comment by ak15** [comment]
This issue is when we pass ActiveRecord_AssociationRelation object 
AbcMailer.sidekiq_delay.send_mail_to_user(association_relation_object)
If we use to_a to association_relation_object(convert to array) everything works fine . Please can anyone help me with exact cause of the issue.

**Comment by mikegee** [comment]
Perhaps the ActiveRecord association object hasn't actually pulls records from the database yet? ActiveRecord is lazy like that.

More importantly, you should not be sending arrays of ActiveRecord instances as Sidekiq params. [The first item in Sidekiq's Best Practices](https://github.com/mperham/sidekiq/wiki/Best-Practices#1-make-your-job-parameters-small-and-simple) speaks to this.

**Comment by ak15** [comment]
ActiveRecord had pulled object actually even if we pass empty ActiveRecord_AssociationRelation object it gives the same error, and I was just eager to know reason for  such kind of behaviour. I totally agree with the Best practices.
Thanks a lot

**Comment by ak15** [comment]
Just FYI came across the issue https://github.com/rails/rails/issues/5303, so I think I was using Rails -v 4.1.5, so I got the error due to YAML not because of sidekiq, I would test it completely once I get free, would be happy if anyone corrects me if I am wrong
```
 =  {a: User.where(email: 'ak@gmail.com')}.to_yaml
  User Load (0.7ms)  SELECT "users".* FROM "users"  WHERE "users"."email" = 'ak@gmail.com'
 => "---\n:a: !ruby/object:ActiveRecord::Relation\n  klass: &1 !ruby/class 'User'\n  table: &2 !ruby/object:Arel::Table\n    name: users\n    engine: *1\n    columns: \n    aliases: []\n    table_alias: \n    primary_key: \n  values:\n    :references: []\n    :where:\n    - &3 !ruby/object:Arel::Nodes::Equality\n      left: !ruby/struct:Arel::Attributes::Attribute\n        relation: *2\n        name: email\n      right: ak@gmail.com\n  offsets: {}\n  loaded: true\n  arel: !ruby/object:Arel::SelectManager\n    engine: *1\n    ctx: &4 !ruby/object:Arel::Nodes::SelectCore\n      source: !ruby/object:Arel::Nodes::JoinSource\n        left: *2\n        right: []\n      top: \n      set_quantifier: \n      projections:\n      - !ruby/struct:Arel::Attributes::Attribute\n        relation: *2\n        name: !ruby/object:Arel::Nodes::SqlLiteral '*'\n      wheres:\n      - !ruby/object:Arel::Nodes::And\n        children:\n        - *3\n      groups: []\n      having: \n      windows: []\n    bind_values: []\n    ast: !ruby/object:Arel::Nodes::SelectStatement\n      cores:\n      - *4\n      orders: []\n      limit: \n      lock: \n      offset: \n      with: \n  scope_for_create: \n  order_clause: \n  to_sql: \n  last: \n  join_dependency: \n  should_eager_load: false\n  records: []\n" 

 = YAML.load(l)
NoMethodError: undefined method `engine' for nil:NilClass
	from /home/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.5/lib/active_record/relation/query_methods.rb:848:in `build_arel'
	from /home/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.5/lib/active_record/relation/query_methods.rb:842:in `arel'
	from /home/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.5/lib/active_record/relation/delegation.rb:119:in `respond_to?'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/to_ruby.rb:364:in `init_with'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/to_ruby.rb:357:in `revive'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/to_ruby.rb:207:in `visit_Psych_Nodes_Mapping'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/visitor.rb:15:in `visit'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/visitor.rb:5:in `accept'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/to_ruby.rb:31:in `accept'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/to_ruby.rb:321:in `block in revive_hash'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/to_ruby.rb:319:in `each'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/to_ruby.rb:319:in `each_slice'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/to_ruby.rb:319:in `revive_hash'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/to_ruby.rb:161:in `visit_Psych_Nodes_Mapping'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/visitor.rb:15:in `visit'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/visitor.rb:5:in `accept'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/to_ruby.rb:31:in `accept'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/to_ruby.rb:295:in `visit_Psych_Nodes_Document'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/visitor.rb:15:in `visit'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/visitor.rb:5:in `accept'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/visitors/to_ruby.rb:31:in `accept'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/nodes/node.rb:37:in `to_ruby'
	from /home/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych.rb:246:in `load'
	from (irb):77
	from /home/.rvm/gems/ruby-2.2.2/gems/railties-4.1.5/lib/rails/commands/console.rb:90:in `start'
	from /home/.rvm/gems/ruby-2.2.2/gems/railties-4.1.5/lib/rails/commands/console.rb:9:in `start'
	from /home/.rvm/gems/ruby-2.2.2/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /home/.rvm/gems/ruby-2.2.2/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/.rvm/gems/ruby-2.2.2/gems/railties-4.1.5/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'2.2.2 :078 > 
`
```

In Rails -v 5.0.0.1
its working completely fine
