### ISSUE TITLE
`Redis::TimeoutError: Connection timed out` after updating redis gem

### ISSUE THREAD

**Issue by tsujigiri** [mperham/sidekiq#3264]
After updating the redis gem from 3.3.1 to 3.3.2 Sidekiq doesn't seem to be able to connect to Redis anymore, raising `Redis::TimeoutError`. Downgrading the redis gem *fixed* it. Using plain `Redis.new` from the rails console within the environment works, I didn't notice anything unusual doing that.

Ruby version: 2.3.1
Sidekiq version: 4.2.6

Backtrace:
```
vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/connection/ruby.rb:111:in `rescue in _write_to_socket': Connection timed out (Redis::TimeoutError)
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/connection/ruby.rb:104:in `_write_to_socket'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/connection/ruby.rb:131:in `block in write'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/connection/ruby.rb:130:in `loop'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/connection/ruby.rb:130:in `write'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/connection/ruby.rb:374:in `write'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:271:in `block in write'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:250:in `io'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:269:in `write'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:228:in `block (3 levels) in process'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:222:in `each'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:222:in `block (2 levels) in process'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:367:in `ensure_connected'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:221:in `block in process'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:306:in `logging'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:220:in `process'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis/client.rb:120:in `call'
    from vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/redis.rb:68:in `call'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis.rb:769:in `block in setex'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis.rb:58:in `block in synchronize'
    from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis.rb:58:in `synchronize'
    from vendor/bundle/ruby/2.3.0/gems/redis-3.3.2/lib/redis.rb:768:in `setex'
    from vendor/bundle/ruby/2.3.0/gems/redis-store-1.2.0/lib/redis/store/interface.rb:17:in `setex'
    from vendor/bundle/ruby/2.3.0/gems/redis-store-1.2.0/lib/redis/store/marshalling.rb:13:in `block in setex'
    from vendor/bundle/ruby/2.3.0/gems/redis-store-1.2.0/lib/redis/store/marshalling.rb:29:in `_marshal'
    from vendor/bundle/ruby/2.3.0/gems/redis-store-1.2.0/lib/redis/store/marshalling.rb:13:in `setex'
    from vendor/bundle/ruby/2.3.0/gems/redis-store-1.2.0/lib/redis/store/namespace.rb:11:in `block in setex'
    from vendor/bundle/ruby/2.3.0/gems/redis-store-1.2.0/lib/redis/store/namespace.rb:84:in `namespace'
    from vendor/bundle/ruby/2.3.0/gems/redis-store-1.2.0/lib/redis/store/namespace.rb:11:in `setex'
    from vendor/bundle/ruby/2.3.0/gems/redis-store-1.2.0/lib/redis/store/ttl.rb:6:in `set'
    from vendor/bundle/ruby/2.3.0/gems/redis-store-1.2.0/lib/redis/store/marshalling.rb:5:in `block in set'
    from vendor/bundle/ruby/2.3.0/gems/redis-store-1.2.0/lib/redis/store/marshalling.rb:29:in `_marshal'
    from vendor/bundle/ruby/2.3.0/gems/redis-store-1.2.0/lib/redis/store/marshalling.rb:5:in `set'
    from vendor/bundle/ruby/2.3.0/gems/redis-store-1.2.0/lib/redis/store/namespace.rb:7:in `block in set'
    from vendor/bundle/ruby/2.3.0/gems/redis-store-1.2.0/lib/redis/store/namespace.rb:84:in `namespace'
    from vendor/bundle/ruby/2.3.0/gems/redis-store-1.2.0/lib/redis/store/namespace.rb:7:in `set'
    from vendor/bundle/ruby/2.3.0/gems/redis-activesupport-5.0.1/lib/active_support/cache/redis_store.rb:231:in `block in write_entry'
    from vendor/bundle/ruby/2.3.0/gems/redis-activesupport-5.0.1/lib/active_support/cache/redis_store.rb:220:in `with'
    from vendor/bundle/ruby/2.3.0/gems/redis-activesupport-5.0.1/lib/active_support/cache/redis_store.rb:231:in `write_entry'
    from vendor/bundle/ruby/2.3.0/gems/redis-activesupport-5.0.1/lib/active_support/cache/redis_store.rb:60:in `block in write'
    from vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:547:in `block in instrument'
    from vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
    from vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:547:in `instrument'
    from vendor/bundle/ruby/2.3.0/gems/redis-activesupport-5.0.1/lib/active_support/cache/redis_store.rb:58:in `write'
    from vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:588:in `save_block_result_to_cache'
    from vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:299:in `fetch'
```

**Comment by webandtech** [comment]
Are you using Sidekiq pro with timed fetch? We ran into this error recently as well... curious if it is the same issue. What version of Redis are you on?

**Comment by tsujigiri** [comment]
The Redis version is 2.8.19. I also just noticed, that it is only happening on one of two environments. The Environment where there is no issue runs Redis 2.8.24. We are running regular Sidekiq without any special configuration. I'll try if upgrading Redis indeed solves the issue.

**Comment by mperham** [comment]
Is it possible one of the servers is swapping?  Sudden timeout problems are often due to memory pressure.

**Comment by tsujigiri** [comment]
It was indeed the Redis version. Updated to 3.2.4 and now it's working again.

**Comment by tsujigiri** [comment]
After some time the errors start popping up again, now. No swapping involved. :thinking: It's also two of four environments now. Both staging environments on EC2, using Redis via ElastiCache.

**Comment by tsujigiri** [comment]
Seems to be related to this:
https://github.com/redis/redis-rb/pull/644#issuecomment-261636657
