### ISSUE TITLE
NoMethodError: undefined method `reloader'

### ISSUE THREAD

**Issue by dbaker24** [mperham/sidekiq#3270]
#Rails: Rails 5.0.0.beta3
Ruby version: ruby-2.3.0
Sidekiq / Pro / Enterprise version(s): 4.2.7

Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://127.0.0.1:6379/0' }
end

/gems/sidekiq-4.2.7/lib/sidekiq/rails.rb:101:in `call'

[ActiveJob] Enqueued TransactionProcessingJob (Job ID: 12e3b3e2-f097-4029-8fb8-bc173ee97c38) to Sidekiq(default) with arguments: "test"

```
2016-12-06T20:22:39.800Z 7421 TID-oulelhf80 WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"TransactionProcessingJob","queue":"default","args":[{"job_class":"TransactionProcessingJob","job_id":"6beb9a18-6f08-4851-ae25-af149b94d541","queue_name":"default","priority":null,"arguments":["test"],"locale":"en"}],"retry":true,"jid":"b193fe3dbcaf81117b3e22ff","created_at":1481055759.799221,"enqueued_at":1481055759.79926},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"TransactionProcessingJob\",\"queue\":\"default\",\"args\":[{\"job_class\":\"TransactionProcessingJob\",\"job_id\":\"6beb9a18-6f08-4851-ae25-af149b94d541\",\"queue_name\":\"default\",\"priority\":null,\"arguments\":[\"test\"],\"locale\":\"en\"}],\"retry\":true,\"jid\":\"b193fe3dbcaf81117b3e22ff\",\"created_at\":1481055759.799221,\"enqueued_at\":1481055759.79926}"}
2016-12-06T20:22:39.813Z 7421 TID-oulelhf80 WARN: NoMethodError: undefined method `reloader' for #<Dev::Application:0x007f84ca3004c0>
Did you mean?  reloaders

2016-12-06T22:26:14.670Z 7600 TID-owaf1t644 WARN: /.rvm/gems/ruby-2.3.0@RGI-dev/gems/sidekiq-4.2.7/lib/sidekiq/rails.rb:101:in `call'
/Users/.rvm/gems/ruby-2.3.0@R-dev/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:126:in `process'
/.rvm/gems/ruby-2.3.0@RGI-dev/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:82:in `process_one'
/Users/.rvm/gems/ruby-2.3.0@R-dev/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:70:in `run'
/Users/.rvm/gems/ruby-2.3.0@R-dev/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:17:in `watchdog'
/Users/.rvm/gems/ruby-2.3.0@R-dev/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by mperham** [comment]
Please give the full backtrace

**Comment by dbaker24** [comment]
updated original posting. Thank you.....

**Comment by mperham** [comment]
Again I need the full stack trace.

**Comment by dbaker24** [comment]
added more to original post. thank you...

**Comment by mperham** [comment]
You have included the error text but not the full backtrace.

**Comment by dbaker24** [comment]
i apologize for not providing what you requested. this is the only output logging that comes from the sidekiq service. it is running in a terminal, invoked from Rails and Rails only shows that it added to the queue process successfully.

is there some other location i should be examining to provide more information?

**Comment by mperham** [comment]
I must have missed something - I see the full backtrace now, thanks.

Could you post your initializer and contents of config/application.rb and config/environments/development.rb?  There's something odd about your Rails app.

**Comment by mperham** [comment]
Oh, Rails 5b3.  Update to a GA version.

**Comment by anushamummina** [comment]
@dbaker24  Have you solved the issue by upgrading rails version?
