### ISSUE TITLE
Connection Timed out. Please suggest us regarding the configuration

### ISSUE THREAD

**Issue by rajcybage** [mperham/sidekiq#3271]
We are using heroku redistogo lite plan

which has

````
# = Limits ===================================================================
maxmemory 52428800
maxmemory-policy volatile-lru
maxmemory-samples 3

maxclients 128
timeout 150

`````

in procfile 

```
worker: bundle exec sidekiq -c 3 -v -q default -q medium

```

My configuration:

```
require 'sidekiq'
require 'sidekiq/web'
require 'log4r'

Sidekiq.configure_server do |config|
Sidekiq::Logging.logger = Log4r::Logger.new 'sidekiq'
Sidekiq::Logging.logger.level = Log4r::INFO
Sidekiq::Logging.logger.level = Logger::WARN
Rails.logger = Sidekiq::Logging.logger
  # config.redis = { db: 1 }
  config.redis = { url: ENV['REDISTOGO_URL'] }
  config.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 90.minutes # default
  end
end

Sidekiq.configure_client do |config|
  config.redis = { size: 1, url: ENV['REDISTOGO_URL'] }
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 90.minutes # default
  end
end

# ActiveRecord::Base.logger = Sidekiq::Logging.logger
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_token]
Sidekiq::Web.set :sessions, Rails.application.config.session_options

`````

Error:
`````
Error message
Errno::ETIMEDOUT: Connection timed out

Stack trace (show Rails)
…by/2.2.0/gems/redis-3.3.2/lib/redis/connection/
ruby.rb: 105:in `write_nonblock'
…by/2.2.0/gems/redis-3.3.2/lib/redis/connection/
ruby.rb: 105:in `_write_to_socket'
…by/2.2.0/gems/redis-3.3.2/lib/redis/connection/
ruby.rb: 131:in `block in write'
…by/2.2.0/gems/redis-3.3.2/lib/redis/connection/
ruby.rb: 130:in `loop'
…by/2.2.0/gems/redis-3.3.2/lib/redis/connection/
ruby.rb: 130:in `write'
…by/2.2.0/gems/redis-3.3.2/lib/redis/connection/
ruby.rb: 374:in `write'
…bundle/ruby/2.2.0/gems/redis-3.3.2/lib/redis/
client.rb: 271:in `block in write'
…bundle/ruby/2.2.0/gems/redis-3.3.2/lib/redis/
client.rb: 250:in `io'
…bundle/ruby/2.2.0/gems/redis-3.3.2/lib/redis/
client.rb: 269:in `write'
…bundle/ruby/2.2.0/gems/redis-3.3.2/lib/redis/
client.rb: 228:in `block (3 levels) in process'
…bundle/ruby/2.2.0/gems/redis-3.3.2/lib/redis/
client.rb: 222:in `each'
…bundle/ruby/2.2.0/gems/redis-3.3.2/lib/redis/
client.rb: 222:in `block (2 levels) in process'
…bundle/ruby/2.2.0/gems/redis-3.3.2/lib/redis/
client.rb: 367:in `ensure_connected'
…bundle/ruby/2.2.0/gems/redis-3.3.2/lib/redis/
client.rb: 221:in `block in process'
…bundle/ruby/2.2.0/gems/redis-3.3.2/lib/redis/
client.rb: 306:in `logging'
…bundle/ruby/2.2.0/gems/redis-3.3.2/lib/redis/
client.rb: 220:in `process'
…bundle/ruby/2.2.0/gems/redis-3.3.2/lib/redis/
client.rb: 187:in `call_pipelined'
…bundle/ruby/2.2.0/gems/redis-3.3.2/lib/redis/
client.rb: 157:in `block in call_pipeline'
…bundle/ruby/2.2.0/gems/redis-3.3.2/lib/redis/
client.rb: 293:in `with_reconnect'
…bundle/ruby/2.2.0/gems/redis-3.3.2/lib/redis/
client.rb: 155:in `call_pipeline'
…vendor/bundle/ruby/2.2.0/gems/redis-3.3.2/lib/
redis.rb:2304:in `block in multi'
…vendor/bundle/ruby/2.2.0/gems/redis-3.3.2/lib/
redis.rb:  58:in `block in synchronize'
       /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/
monitor.rb: 211:in `mon_synchronize'
…vendor/bundle/ruby/2.2.0/gems/redis-3.3.2/lib/
redis.rb:  58:in `synchronize'
…vendor/bundle/ruby/2.2.0/gems/redis-3.3.2/lib/
redis.rb:2296:in `multi'
…ems/sidekiq-status-0.6.0/lib/sidekiq-status/
storage.rb:  16:in `block in store_for_id'
…ems/sidekiq-status-0.6.0/lib/sidekiq-status/
storage.rb: 102:in `block in redis_connection'
….2.0/gems/connection_pool-2.2.1/lib/
connection_pool.rb:  64:in `block (2 levels) in with'
….2.0/gems/connection_pool-2.2.1/lib/
connection_pool.rb:  63:in `handle_interrupt'
….2.0/gems/connection_pool-2.2.1/lib/
connection_pool.rb:  63:in `block in with'
….2.0/gems/connection_pool-2.2.1/lib/
connection_pool.rb:  60:in `handle_interrupt'
….2.0/gems/connection_pool-2.2.1/lib/
connection_pool.rb:  60:in `with'
…ems/sidekiq-status-0.6.0/lib/sidekiq-status/
storage.rb: 101:in `redis_connection'
…ems/sidekiq-status-0.6.0/lib/sidekiq-status/
storage.rb:  15:in `store_for_id'
…q-status-0.6.0/lib/sidekiq-status/
client_middleware.rb:  26:in `call'
…2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/
chain.rb: 130:in `block in invoke'
…2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/
chain.rb: 133:in `call'
…2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/
chain.rb: 133:in `invoke'
…le/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/
client.rb: 206:in `process_single'
…le/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/
client.rb:  65:in `push'
…le/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/
worker.rb: 116:in `client_push'
…le/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/
worker.rb:  60:in `perform_async'









**Please suggest us.**

Ruby version: 2.2.1
Sidekiq / Pro / Enterprise version(s): 4.1.4

If relevant, please include your initializer and any error message with the full backtrace.

**Comment by rajcybage** [comment]
Hi, is the configuration ok?

If it is ok but I got still connection timed out error. cn you please suggest. 

Many thanks

**Comment by rajcybage** [comment]
We have followed exactly what have you told on https://stackoverflow.com/questions/41041194/connection-timed-out-please-suggest-us-regarding-the-configuration  but still getting error .

Please suggest should we upgrade redis plan?

should we took redis pro?

Please advice us
