### ISSUE TITLE
NameError: uninitialized constant RateDownloaderJob

### ISSUE THREAD

**Issue by tomkra** [mperham/sidekiq#3307]
Ruby version: 2.3.1
Sidekiq version: 4.2.3 
environment: production

Hello I'm facing problem with sidekiq. I keep getting warning about unitialized constant RateDownloaderJob. I have my workers placed in `app/workers` and I added `config.eager_load_paths += %W(#{config.root}/app/workers)` to `application.rb` and `production.rb` but still without result. Thank you for your help.

Here is the error log: 
```
NameError: uninitialized constant RateDownloaderJob
  from active_support/inflector/methods.rb:268:in `const_get'
  from active_support/inflector/methods.rb:268:in `block in constantize'
  from active_support/inflector/methods.rb:266:in `each'
  from active_support/inflector/methods.rb:266:in `inject'
  from active_support/inflector/methods.rb:266:in `constantize'
  from active_support/core_ext/string/inflections.rb:66:in `constantize'
  from active_job/core.rb:36:in `deserialize'
  from active_job/execution.rb:21:in `block in execute'
  from active_support/callbacks.rb:126:in `call'
  from active_support/callbacks.rb:506:in `block (2 levels) in compile'
  from active_support/callbacks.rb:455:in `call'
  from active_support/callbacks.rb:448:in `block (2 levels) in around'
  from active_support/callbacks.rb:286:in `block (2 levels) in halting'
  from active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
  from active_support/execution_wrapper.rb:76:in `wrap'
  from active_support/reloader.rb:68:in `block in wrap'
  from active_support/execution_wrapper.rb:76:in `wrap'
  from active_support/reloader.rb:67:in `wrap'
  from active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
  from active_support/callbacks.rb:391:in `instance_exec'
  from active_support/callbacks.rb:391:in `block in make_lambda'
  from active_support/callbacks.rb:285:in `block in halting'
  from active_support/callbacks.rb:447:in `block in around'
  from active_support/callbacks.rb:455:in `call'
  from active_support/callbacks.rb:101:in `__run_callbacks__'
  from active_support/callbacks.rb:750:in `_run_execute_callbacks'
  from active_support/callbacks.rb:90:in `run_callbacks'
  from active_job/execution.rb:20:in `execute'
  from active_job/queue_adapters/sidekiq_adapter.rb:40:in `perform'
  from sidekiq/processor.rb:155:in `execute_job'
  from sidekiq/processor.rb:136:in `block (3 levels) in process'
  from sidekiq/middleware/chain.rb:128:in `block in invoke'
  from sidekiq_unique_jobs/server/middleware.rb:15:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/server/retry_jobs.rb:74:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/server/logging.rb:11:in `block in call'
  from sidekiq/logging.rb:32:in `with_context'
  from sidekiq/middleware/server/logging.rb:7:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/chain.rb:133:in `invoke'
  from sidekiq/processor.rb:131:in `block (2 levels) in process'
  from sidekiq/processor.rb:171:in `stats'
  from sidekiq/processor.rb:130:in `block in process'
  from sidekiq.rb:35:in `block in <module:Sidekiq>'
  from sidekiq/processor.rb:122:in `process'
  from sidekiq/processor.rb:81:in `process_one'
  from sidekiq/processor.rb:69:in `run'
  from sidekiq/util.rb:17:in `watchdog'
  from sidekiq/util.rb:25:in `block in safe_thread'
```
And here are my workers:

```ruby
#app/workers/general_worker.rb
class GeneralWorker
  include Sidekiq::Worker

  protected
    def get_date_diff(time)
      Time.now - time
    end

    def get_emails
      User.where(information_email: true, company_id: @cert.company_id).map {|user| user.email}
    end
end
```

```ruby
#app/workers/urls_worker.rb
require 'open_uri_redirections'
require 'net/http'

class UrlsWorker < GeneralWorker
  sidekiq_options retry: false
  sidekiq_options unique: :until_executing

  def perform(url_id)
    Raven.capture do
      @url = Url.find_by_id(url_id)
      if !@url.nil? && @url.company.active
        ...
      end
    end
  end
```

**Comment by mikegee** [comment]
`general_worker.rb` defines `GeneralWorker` and `urls_worker.rb` defines `UrlsWorker`. Where's `RateDownloaderJob`?

**Comment by tomkra** [comment]
That's it `RateDownloaderJob` is not my class or job or worker. I have absolutely no idea where this class came from. It must be inside some library or something like that but I didn't created or worked with this class.

**Comment by mperham** [comment]
Pro tip: Do not change config.eager_load ever.  Fix your code to work with Rails's default loading.

That class name is not on GitHub so I suspect it is an application job that was defined and has been removed.  Delete those jobs from Redis.

https://github.com/search?utf8=%E2%9C%93&q=RateDownloaderJob+language%3ARuby&type=Repositories&ref=advsearch&l=Ruby&l=
