### ISSUE TITLE
Loading sidekiq with large queue fails (stack level too deep)

### ISSUE THREAD

**Issue by stephan-roolvink** [mperham/sidekiq#3314]
Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s): 3.5.4, 2.1.3, 0.7.10

We are running sidekiq loadbalanced on four server, which ran smoothly. Last monday however, after a reboot on one of the servers decided it did not want to start anymore.

It was spitting out the following output.

```
2017-01-11T05:43:35.231Z 26797 TID-ctkj0 WARN: Sidekiq died due to the following error, cannot recover, process exiting
2017-01-11T05:43:35.232Z 26797 TID-ctkj0 WARN: Celluloid::Task::Fibered::StackError: stack level too deep @initialize (see https://github.com/celluloid/celluloid/wiki/Fiber-stack-errors)
2017-01-11T05:43:35.234Z 26797 TID-ctkj0 WARN: /srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:28:in `rescue in deliver'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:26:in `deliver'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:83:in `resume'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/responses.rb:12:in `dispatch'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:40:in `block in initialize'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/handlers.rb:38:in `call'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/handlers.rb:20:in `handle_message'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:283:in `handle_message'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:156:in `block in run'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/timers-4.1.1/lib/timers/group.rb:66:in `wait'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:152:in `run'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
bundler: failed to load command: sidekiq (/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/bin/sidekiq)
2017-01-11T05:43:36.251Z 26797 TID-8btx4 WARN: {:context=>"Manager#processor_died died"}
2017-01-11T05:43:36.254Z 26797 TID-8btx4 WARN: NoMethodError: undefined method `async' for nil:NilClass
2017-01-11T05:43:36.254Z 26797 TID-8btx4 WARN: /srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/manager.rb:217:in `dispatch'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/manager.rb:106:in `block in processor_died'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/util.rb:16:in `watchdog'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/manager.rb:97:in `processor_died'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:15:in `block in call'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task' 
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/srv/healthcare/ons_taken_s/shared/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

After some digging we found the following in redis:

```
LLEN "task_monitor_deployment:queue:default_<server_name>_0"
(integer) 483580
```

If we leave out this queue Sidekiq starts normally. Is there way you we can fix this issue without loosing the jobs?

We are running both staging and production on the same server in the same setup, and coincidentally on the same server the staging environment has the same issue.

```
LLEN "task_monitor_deployment:queue:default_nl14s0041_0"
(integer) 251736
```

Is there an explanation why this could happen on the same server?

**Comment by stephan-roolvink** [comment]
I got my sidekiq process running again by renaming the queue and then starting it.
I also managed to get the jobs that where in the queue to execute using the script below.

```
queue = Sidekiq::Queue.new("default_<server_name>_ORIG")
begin
  Sidekiq.redis do |conn|
    conn.rpoplpush("queue:default_<server_name>_0_ORIG", "queue:default")
  end
end while (queue.size > 0)
```

It only takes a shit load of time to move all these jobs from one queue to the other :(

**Comment by mperham** [comment]
Something is wrong with your system.  You've got a reliable fetch private queue with 400k jobs, which doesn't make sense.  I would switch to the new super_fetch scheme but that does require an upgrade to Sidekiq 4.

This should halve the time it takes:

```ruby
queue = Sidekiq::Queue.new("default_<server_name>_ORIG")
Sidekiq.redis do |conn|
  while conn.rpoplpush("queue:default_<server_name>_0_ORIG", "queue:default");
end
```

**Comment by stephan-roolvink** [comment]
I totally agree that the 400k jobs is weird I have never seen it elsewhere. I was hoping you would have an idea where this might be coming from.

Migrating our infrastructure gem to sidekiq 4 is still on the todo list.

Thanks for the improved script, with the previous script I already got the jobs done 👍

**Comment by mperham** [comment]
No clue how all those jobs are getting stuck but make sure you are shutting down the process with the standard USR1 / TERM signalling, not using kill -9.  Unfinished jobs are generally pushed back to the public queue when shutting down.  Finished jobs are removed from the private queue when acknowledging the job.
