### ISSUE TITLE
Can not require gem from initialization

### ISSUE THREAD

**Issue by olegsobchuk** [mperham/sidekiq#3358]
Ruby version: ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.2.9

issue was added to stackoverflow [http://stackoverflow.com/q/42234293/3884750](http://stackoverflow.com/q/42234293/3884750)

I try to write microservice on pure ruby. So I need Postgres in my job. But I get error.

sidekiq.rb

```
require 'sidekiq'
require 'pg'

# If your client is single-threaded, we just need a single connection in our Redis connection pool
Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://localhost:6379/0', namespace: 'settings', size: 5 }
end

# Sidekiq server is multi-threaded so our Redis connection pool size defaults to concurrency (-c)
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://localhost:6379/0', namespace: 'settings' }
end

```

sidekiq.yml

```
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:queues:
  - ['default', 1]
  - ['settings', 1]
```

run sidekiq: `bundle exec sidekiq -r ./config/sidekiq.rb -C ./config/sidekiq.yml`

and get error: 

```
$ bundle exec sidekiq -r ./config/sidekiq.rb -C ./config/sidekiq.yml
/home/oleg/work/fit/fit_settings_service/config/sidekiq.rb:2:in `require': cannot load such file -- pg (LoadError)
	from /home/oleg/work/fit/fit_settings_service/config/sidekiq.rb:2:in `<top (required)>'
	from /home/oleg/.rvm/gems/ruby-2.3.3/gems/sidekiq-4.2.9/lib/sidekiq/cli.rb:255:in `require'
	from /home/oleg/.rvm/gems/ruby-2.3.3/gems/sidekiq-4.2.9/lib/sidekiq/cli.rb:255:in `boot_system'
	from /home/oleg/.rvm/gems/ruby-2.3.3/gems/sidekiq-4.2.9/lib/sidekiq/cli.rb:50:in `run'
	from /home/oleg/.rvm/gems/ruby-2.3.3/gems/sidekiq-4.2.9/bin/sidekiq:12:in `<top (required)>'
	from /home/oleg/.rvm/gems/ruby-2.3.3/bin/sidekiq:22:in `load'
	from /home/oleg/.rvm/gems/ruby-2.3.3/bin/sidekiq:22:in `<main>'
	from /home/oleg/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/oleg/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

```

pg gem installed and works with Rails and with ruby-script

**Comment by mikegee** [comment]
I posted a possible answer on your SO post. I'm having a hard time imagining how this could be a bug in Sidekiq, since `require 'sidekiq'` succeeded. Let's keep the conversation over there.
