### ISSUE TITLE
Sidekiq can't assign to redis

### ISSUE THREAD

**Issue by w-zengtao** [mperham/sidekiq#3364]
Ruby version: 2.3.3
Sidekiq  version(s): 4.2.9
Redis: 3.2.8 (Homebrew install )

connection_pool-2.2.1

Mac Sierra (New System)

`
➜  ~ tcping 127.0.0.1 6379
`

`
127.0.0.1 port 6379 open.
`

full backtrace.

```

Can't assign requested address - connect(2) for 127.0.0.1
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/2.3.0/socket.rb:1207:in `__connect_nonblock'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/2.3.0/socket.rb:1207:in `connect_nonblock'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/connection/ruby.rb:199:in `connect_addrinfo'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/connection/ruby.rb:239:in `block in connect'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/connection/ruby.rb:237:in `each'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/connection/ruby.rb:237:in `each_with_index'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/connection/ruby.rb:237:in `connect'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/connection/ruby.rb:313:in `connect'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:336:in `establish_connection'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:101:in `block in connect'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:293:in `with_reconnect'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:100:in `connect'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:364:in `ensure_connected'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:221:in `block in process'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:306:in `logging'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:220:in `process'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:120:in `call'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis.rb:251:in `block in info'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis.rb:250:in `info'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:113:in `block in redis_info'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:95:in `block in redis'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:92:in `redis'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:106:in `redis_info'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/cli.rb:71:in `run'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/bin/sidekiq:12:in `<top (required)>'
/Users/ztao/.rbenv/versions/2.3.3/bin/sidekiq:22:in `load'
/Users/ztao/.rbenv/versions/2.3.3/bin/sidekiq:22:in `<top (required)>'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli/exec.rb:74:in `load'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli/exec.rb:27:in `run'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli.rb:335:in `exec'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli.rb:20:in `dispatch'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli.rb:11:in `start'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/exe/bundle:32:in `block in <top (required)>'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/Users/ztao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/exe/bundle:24:in `<top (required)>'
/Users/ztao/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
/Users/ztao/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'

```

**Comment by w-zengtao** [comment]
`connection_pool` cause this problem
