### ISSUE TITLE
Weird Issue In Retry Tab With Possible Invalid Job Parameters

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#3389]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.2.9

If relevant, please include your initializer and any error message with the full backtrace.

For a long time the retries  queue would simply say there is a low level plumbing error.
We never really had the time to dig deep in to see why, but today we did!

We're occasionally posting some arguments to a worker where the ID property is occasionally null.

Other times it's not. When it's null and I load up the retry queue (I'm assuming it's in the retry queue for a similar reason it's failing to display in the Web UI) I get the following error in the sidekiq-web.log file

We've worked to not enqueue this job anymore but I'm curious why sidekiq is trying to call map on a string?

```
#<NoMethodError: undefined method `map' for "{\"id\":null,\"type\":\"hashtag\"}":String
Did you mean?  tap>
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/web/helpers.rb:173:in `display_args'
(eval):51:in `block in _erb_retries'
(eval):35:in `each'
(eval):35:in `_erb_retries'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/web/action.rb:89:in `_erb'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/web/action.rb:58:in `erb'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/web/application.rb:148:in `block in <class:WebApplication>'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/web/application.rb:266:in `instance_exec'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/web/application.rb:266:in `block in call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/web/application.rb:262:in `catch'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/web/application.rb:262:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:66:in `block in call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `each'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:153:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/web.rb:103:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/web.rb:108:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/auth/basic.rb:25:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:66:in `block in call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `each'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/configuration.rb:226:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/server.rb:578:in `handle_request'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/server.rb:415:in `process_client'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/server.rb:275:in `block in run'
```

**Comment by bobber205** [comment]
You're right! :D

**Comment by mperham** [comment]
Please open a new issue with relevant details so I can fix it.
