### ISSUE TITLE
Sidekiq Multiple Batch Steps - wrong constant name

### ISSUE THREAD

**Issue by ACPK** [mperham/sidekiq#3410]
How would I be able to multiple steps in a batch? My current code is below and the error I hit is "wrong constant name" when the first batch successfully completes.

    class DailyWorkflowJob
      include Sidekiq::Worker

      def perform(date)
        step_1(date)
      end

      def step_1(date)
        download_stock_prices_batch = Sidekiq::Batch.new
        download_stock_prices_batch.description = 'Download Daily Stock Prices' 
        # download_stock_prices_batch.on(:complete, self)
        download_stock_prices_batch.on(:success, 'DailyWorkflowJob#step2', 'date' => date)
        
        download_stock_prices_batch.jobs do
          UpdateStockPrices.perform_async(date)
        end
      end

      def self.step2(status, options)
         # Second Step Code Goes Here
      end
    end

**Comment by mperham** [comment]
Can you give the full error message and backtrace?

If you haven't seen them already, the wiki has two pages devoted to complex batch workflows.

**Comment by ACPK** [comment]
@mperham - Yes,  and I was following along https://github.com/mperham/sidekiq/wiki/Batches.

**Comment by ACPK** [comment]
@mperham  - I've removed the complete line and edited the code to include "self.step2" but receive the error:

    {
    context: Job raised exception, 
    job: {
    args: [
    success, 
    u_KxxOWaFiuKrQ, 
    default
    ], 
    class: Sidekiq::Batch::Callback, 
    created_at: 1490503659.5103257, 
    enqueued_at: 1490503678.3210003, 
    error_class: NameError, 
    error_message: wrong constant name DailyWorkflowJob.step2, 
    failed_at: 1490503659.5157926, 
    jid: 8976694c6a4ee7b2fc0e340f, 
    queue: default, 
    retried_at: 1490503678.3260722, 
    retry: True, 
    retry_count: 1
    }, 
    jobstr: {"class":"Sidekiq::Batch::Callback","queue":"default","args":["success","u_KxxOWaFiuKrQ","default"],"retry":true,"jid":"8976694c6a4ee7b2fc0e340f","created_at":1490503659.5103257,"enqueued_at":1490503678.3210003,"error_message":"wrong constant name DailyWorkflowJob.step2","error_class":"NameError","failed_at":1490503659.5157926,"retry_count":0}
    }

**Comment by mperham** [comment]
It has to be an instance method.

**Comment by ACPK** [comment]
@mperham When I removed the .self, I get "wrong constant name DailyWorkflowJob.step2"

**Comment by mperham** [comment]
Is the class located within a module?

**Comment by myfitment** [comment]
Getting the exact same error here. Implemented the "batch of batches" 2-step process you outlined on my other thread. If I don't specify the callback on ```:complete``` then this error doesn't fire.

The code:

```
class ProductParentWorker

  include Sidekiq::Worker
  sidekiq_options :retry => 3, :queue =>  :bulk, :backtrace => true

  def perform(background_process_id)
    
    bp = BackgroundProcess.find(background_process_id)
    bp.status = "Running"
    bp.message = nil
    bp.save!
    subscription = bp.subscription
    @flog = bp.logfile
    @flog.puts "Running update for all active eBay listings in myFitment for #{subscription.name}..."

    cnt = subscription.listings.active.with_fitment.count
    return if cnt == 0
    batch_size = 1000

    batch = Sidekiq::Batch.new
    batch.on(:complete, self, 'background_process_id' => background_process_id)
    batch.jobs do

      amt = [cnt / batch_size,1].max
      amt.times do |idx|
        ProductChildWorker.perform_async(background_process_id, idx, batch_size)
      end
    end

    @flog.close
    bp.log.try(:destroy)
    bp.create_log(log_file_name: File.open(bp.log_file_name))
  end

  def on_complete(status, options)
    bp = BackgroundProcess.find(options['background_process_id'])
    subscription = bp.subscription
    subscription.generate_statistics
    bp.message = ""
    bp.status = 'Complete'
    bp.save!
    subscription.user.inform("Validation complete.")
  end

end

```

The error fires on this Parent worker, here's the stacktrace:

```
2017-03-27T00:35:30.017Z 32130 TID-oxdxdzyh8 WARN: NameError: wrong constant name 
2017-03-27T00:35:30.017Z 32130 TID-oxdxdzyh8 WARN: /Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/activesupport-4.2.7/lib/active_support/inflector/methods.rb:254:in `const_get'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/activesupport-4.2.7/lib/active_support/inflector/methods.rb:254:in `constantize'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/activesupport-4.2.7/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-pro-3.4.5/lib/sidekiq/batch/callback.rb:19:in `execute_callback'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-pro-3.4.5/lib/sidekiq/batch/callback.rb:80:in `block (2 levels) in complete'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-pro-3.4.5/lib/sidekiq/batch/callback.rb:79:in `each_pair'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-pro-3.4.5/lib/sidekiq/batch/callback.rb:79:in `block in complete'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-pro-3.4.5/lib/sidekiq/batch/callback.rb:78:in `each'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-pro-3.4.5/lib/sidekiq/batch/callback.rb:78:in `complete'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-pro-3.4.5/lib/sidekiq/batch/callback.rb:12:in `perform'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:158:in `execute_job'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:36:in `call'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:133:in `call'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-pro-3.4.5/lib/sidekiq/batch/middleware.rb:33:in `call'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-ent-1.5.2/lib/sidekiq-ent/unique.rb:124:in `call'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-ent-1.5.2/lib/sidekiq-ent/limiter/middleware.rb:38:in `call'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/logging.rb:32:in `with_context'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:133:in `call'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:174:in `stats'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:131:in `block in process'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:35:in `call'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:126:in `call'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:126:in `process'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:82:in `process_one'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:70:in `run'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:17:in `watchdog'
/Users/me/myapp/code/myapp/.gems/ruby/2.1.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:26:in `block in safe_thread'
2017-03-27T00:35:30.045Z 32130 TID-oxduuwup8 AcesValidatorParentWorker JID-5dafc8e74ad72497715a6d07 INFO: done: 4.323 sec
2017-03-27T00:35:30.192Z 32130 TID-oxdxd54pk AcesValidator JID-77341f8a131d047d0855e7a0 BID-J0ZusJS2Z4Q_hA INFO: done: 0.283 sec
2017-03-27T00:35:30.193Z 32130 TID-oxdxd54pk Sidekiq::Batch::Callback JID-696398a8b73a9f8a0feac08d INFO: start
2017-03-27T00:35:30.195Z 32130 TID-oxdxd54pk Sidekiq::Batch::Callback JID-696398a8b73a9f8a0feac08d INFO: done: 0.002 sec
2017-03-27T00:35:30.196Z 32130 TID-oxdxd54pk Sidekiq::Batch::Callback JID-fe3fd71e07db06ccd4feb4e5 INFO: start
2017-03-27T00:35:30.197Z 32130 TID-oxdxd54pk Sidekiq::Batch::Callback JID-fe3fd71e07db06ccd4feb4e5 INFO: done: 0.001 sec
2017-03-27T00:35:34.701Z 32130 TID-oxdyj6j84 Sidekiq::Batch::Callback JID-dea1fff09b262a365257f546 INFO: start
2017-03-27T00:35:34.702Z 32130 TID-oxdyj6j84 Sidekiq::Batch::Callback JID-dea1fff09b262a365257f546 INFO: fail: 0.001 sec
```

I'm also curious why that callback is firing so many times.

**Comment by ACPK** [comment]
@mperham @myfitment - I got it working by changing ".on(:complete, self)" to ".on(:complete, self.class)".

**Comment by mperham** [comment]
That's right, you pass the class name, not an actual instance to `on`.
