### ISSUE TITLE
Add create folder for pidfile

### ISSUE THREAD

**Issue by Neodelf** [mperham/sidekiq#3412]
Ruby version: 2.1.1
Sidekiq / Pro / Enterprise version(s): 3.0.2

```
~/custom$ sidekiq -C config/sidekiq.yml
No such file or directory @ rb_sysopen - /custom/tmp/pids/sidekiq.pid
/custom/.rvm/gems/ruby-2.1.1@custom/gems/sidekiq-3.0.2/lib/sidekiq/cli.rb:325:in `initialize'
/custom/.rvm/gems/ruby-2.1.1@rcustom/gems/sidekiq-3.0.2/lib/sidekiq/cli.rb:325:in `open'
/custom/.rvm/gems/ruby-2.1.1@custom/gems/sidekiq-3.0.2/lib/sidekiq/cli.rb:325:in `write_pid'
/custom/.rvm/gems/ruby-2.1.1@custom/gems/sidekiq-3.0.2/lib/sidekiq/cli.rb:41:in `parse'
/custom/.rvm/gems/ruby-2.1.1@custom/gems/sidekiq-3.0.2/bin/sidekiq:7:in `<top (required)>'
/custom/.rvm/gems/ruby-2.1.1@rcustom/bin/sidekiq:23:in `load'
/custom/.rvm/gems/ruby-2.1.1@custom/bin/sidekiq:23:in `<main>'
```
I propose to create default folder `tmp/pids/`. In latest version this not doing.

**Comment by mperham** [comment]
Nope, Sidekiq will not create directories.
