### ISSUE TITLE
NoMethodError when cloning args w/ ActiveSupport 5.0.2

### ISSUE THREAD

**Issue by lardcanoe** [mperham/sidekiq#3421]
Ruby version: JRuby 9.1.7.0, Ruby 2.3.0
Sidekiq / Pro / Enterprise version(s): Free

Please include your initializer and any error message with the full backtrace.

```
2017-04-04T15:29:41.167Z 12288 TID-1jo WARN: {"context":"Job raised exception","job":{"class":"DoSomething","args":[42],"retry":true,"queue":"default","jid":"0f8029f9ff2166c2b0a4ab2c","created_at":1491319781.05,"enqueued_at":1491319781.055},"jobstr":"{\"class\":\"DoSomething\",\"args\":[42],\"retry\":true,\"queue\":\"default\",\"jid\":\"0f8029f9ff2166c2b0a4ab2c\",\"created_at\":1491319781.05,\"enqueued_at\":1491319781.055}"}
2017-04-04T15:29:41.168Z 12288 TID-1jo WARN: NoMethodError: undefined method `call' for nil:NilClass
Did you mean?  caller
2017-04-04T15:29:41.168Z 12288 TID-1jo WARN: org/jruby/RubyMarshal.java:145:in `load'
experiment/vendor/jruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/marshal.rb:5:in `load'
experiment/vendor/jruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:197:in `cloned'
experiment/vendor/jruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:180:in `stats'
experiment/vendor/jruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'
experiment/vendor/jruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:35:in `block in Sidekiq'
experiment/vendor/jruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'
experiment/vendor/jruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:83:in `process_one'
experiment/vendor/jruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'
experiment/vendor/jruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
experiment/vendor/jruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

Are you using an old version? `4.2.10`

If I revert the change from https://github.com/rails/rails/commit/a72498f776b2e67b7e3a074423181defcd06fc56 manually then the code works fine. I don't understand what the code is doing to tell if this is a problem with sidekiq or activesupport.

Attached is a very basic code to reproduce. Comment out `require 'active_support/all'` to see it work.

[reproduce.zip](https://github.com/mperham/sidekiq/files/893665/reproduce.zip)

`jruby -G --dev -J-XX:+PrintGCTimeStamps ./bin/sidekiq -r ./reproduce.rb`

**Comment by mperham** [comment]
Looks like a JRuby bug?

**Comment by lardcanoe** [comment]
Closing this.

Opened: https://github.com/jruby/jruby/issues/4557
