### ISSUE TITLE
NoMethodError: undefined method `delay' for Class

### ISSUE THREAD

**Issue by newdark** [mperham/sidekiq#3444]
Ruby version: `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]`
Sidekiq Version: `(5.0.0)`
Rails Version: `(5.0.2)`

```ruby
# frozen_string_literal: true
require 'sidekiq/api'
require 'erb_yaml'
require 'sidekiq_queue_manager'
file_path = Rails.root.join('config', 'sidekiq.yml')
# Load the config
configuration = ERBYAML.load_file(file_path)
# NOTE: The :namespace parameter is optional, but recommended if Sidekiq is
# sharing access to a Redis database, also specify which database
# in the url default is 0 url: redis://localhost:6379/0
SidekiqQueueManager::MiddleWare.new # Run the initializers to get things setup for settings

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add(SidekiqQueueManager::MiddleWare)
  end
  config.redis = {
    url: configuration[:url],
    port: configuration[:port],
    namespace: configuration[:namespace],
    password: configuration[:password]
  }
  # config.error_handlers << proc do |exception, options|
  #   # Send unless it is in the ignore list
  #   Airbrake.notify_or_ignore(exception, parameters: options)
  # end
end

Sidekiq.configure_client do |config|
  config.redis = {
    host: configuration[:host],
    port: configuration[:port],
    namespace: configuration[:namespace],
    password: configuration[:password]
  }
end

Sidekiq.default_worker_options = { backtrace: Rails.env.development? }

```
```ruby
>> User.delay.update_with_ldap(User.first.id)
NoMethodError: undefined method `delay' for #<Class:0x007fbecc61f9f8>
Did you mean?  delegate
	from /Users/newdark/.rvm/gems/ruby-2.3.1@default/gems/activerecord-5.0.2/lib/active_record/dynamic_matchers.rb:21:in `method_missing'
	from (irb):2
	from /Users/newdark/.rvm/gems/ruby-2.3.1@default/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /Users/newdark/.rvm/gems/ruby-2.3.1@default/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/newdark/.rvm/gems/ruby-2.3.1@default/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/newdark/.rvm/gems/ruby-2.3.1@default/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/newdark/.rvm/gems/ruby-2.3.1@default/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:5:in `require'
	from bin/rails:5:in `<main>'
```

Some more background on this is after I go back to using `4.2.9` version of sidekiq everything is ok. This error only started happening with the upgrade to sidekiq `5.0.0`.  I did not see any code in the repo that was changed that could've made this happen. I also did not see anyone else report this issue so I might be the lucky first to find it.

**Comment by dsexton** [comment]
https://github.com/mperham/sidekiq/blob/master/5.0-Upgrade.md

> The Delayed Extensions delay, delay_in and delay_until APIs are no longer available by default. The extensions allow you to marshal job arguments as YAML, leading to cases where job payloads could be many 100s of KB or larger if not careful, leading to Redis networking timeouts or other problems. As noted in the Best Practices wiki page, Sidekiq is designed for jobs with small, simple arguments.

The upgrade guide says add `Sidekiq::Extensions.enable_delay!`

**Comment by newdark** [comment]
Thanks @dsextom I was having problems finding that upgrade guided. I figured that was the case as it has been hinted at in other issues.

**Comment by Liu-XiaoDao** [comment]
Is that right ?

config/initializers/sidekiq.rb
Sidekiq::Extensions.enable_delay!

**Comment by Liu-XiaoDao** [comment]
@newdark

**Comment by newdark** [comment]
Yes, it is correct. The solution fixed the problem and bound the `.delay` method to the classes again.
