### ISSUE TITLE
Bizzare concurrency issues on w/ Rails 5.0.1 and JRuby 9.1.8.0 and serialized attributes

### ISSUE THREAD

**Issue by hobodave** [mperham/sidekiq#3455]
Ruby version: JRuby-9.1.8.0
Sidekiq: 5.0.0
Rails: 5.0.1

Minimal Demo: https://github.com/hobodave/sandbox

Steps to reproduce can be found in README of above project.

Backtrace:

```
2017-05-03T20:02:42.632Z 16270 TID-1ks WARN: TypeError: no implicit conversion of Hash into String
2017-05-03T20:02:42.632Z 16270 TID-1ks WARN: json/ext/Parser.java:174:in `initialize'
json/ext/Parser.java:151:in `new'
/Users/davida/.rvm/rubies/jruby-9.1.8.0/lib/ruby/stdlib/json/common.rb:155:in `parse'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/json/decoding.rb:21:in `decode'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activerecord-5.0.1/lib/active_record/coders/json.rb:9:in `load'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activerecord-5.0.1/lib/active_record/type/serialized.rb:18:in `deserialize'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activerecord-5.0.1/lib/active_record/attribute.rb:140:in `type_cast'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activerecord-5.0.1/lib/active_record/attribute.rb:38:in `value'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/core_ext/hash/transform_values.rb:16:in `block in transform_values'
org/jruby/RubyHash.java:1343:in `each'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/core_ext/hash/transform_values.rb:15:in `transform_values'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activerecord-5.0.1/lib/active_record/attribute_set.rb:24:in `to_hash'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activerecord-5.0.1/lib/active_record/attribute_methods.rb:276:in `attributes'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activemodel-5.0.1/lib/active_model/serialization.rb:127:in `serializable_hash'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activerecord-5.0.1/lib/active_record/serialization.rb:17:in `serializable_hash'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activemodel-5.0.1/lib/active_model/serializers/json.rb:99:in `as_json'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/json/encoding.rb:33:in `encode'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/json/encoding.rb:20:in `encode'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/core_ext/object/json.rb:37:in `to_json'
com/jrjackson/JrJacksonBase.java:70:in `generate'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/jrjackson-0.4.2-java/lib/jrjackson/jrjackson.rb:60:in `dump'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/multi_json-1.12.1/lib/multi_json/adapters/jr_jackson.rb:20:in `dump'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/multi_json-1.12.1/lib/multi_json/adapter.rb:25:in `dump'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/multi_json-1.12.1/lib/multi_json.rb:139:in `dump'
/Users/davida/Developer/sandbox/app/lib/instrument.rb:37:in `log'
/Users/davida/Developer/sandbox/app/lib/instrument.rb:14:in `handle_exception'
/Users/davida/Developer/sandbox/app/lib/instrument.rb:9:in `instrument'
/Users/davida/Developer/sandbox/app/workers/async_worker.rb:15:in `do_perform'
/Users/davida/Developer/sandbox/app/workers/async_worker.rb:8:in `perform'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:204:in `execute_job'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:175:in `block in process'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:174:in `block in process'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:146:in `block in dispatch'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/job_retry.rb:97:in `local'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:145:in `block in dispatch'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/rails.rb:43:in `block in call'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/reloader.rb:68:in `block in wrap'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/reloader.rb:67:in `wrap'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/rails.rb:42:in `call'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:141:in `block in dispatch'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:220:in `stats'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:136:in `block in dispatch'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/job_logger.rb:8:in `call'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:135:in `block in dispatch'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/job_retry.rb:72:in `global'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:134:in `block in dispatch'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/logging.rb:32:in `with_context'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:133:in `dispatch'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:173:in `process'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:86:in `process_one'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:73:in `run'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/util.rb:17:in `watchdog'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

**Comment by mperham** [comment]
1. Have you tried Rails 5.0.2?
2. Your JSON setup is complex.  I'd simplify it by ripping out multi_json and jrjackson and just using `json`.

**Comment by hobodave** [comment]
@mperham Rails 5.0.2 does not work with JRuby 9.1.8.0, waiting on 9.1.9.0 for that. 

Simplifying JSON was actually next on my list.

**Comment by mperham** [comment]
Good to hear.  The days of `json` being slow are years past.  There's not as much reason to run various "native" gems like oj, yajl, etc especially now that it's built into Ruby.  Stick with the stdlib.

**Comment by hobodave** [comment]
@mperham stack with stdlib JSON (pushed to sandbox repo)

```
2017-05-03T21:26:57.450Z 19825 TID-1m0 WARN: TypeError: no implicit conversion of Hash into String
2017-05-03T21:26:57.458Z 19825 TID-1m0 WARN: json/ext/Parser.java:174:in `initialize'
json/ext/Parser.java:151:in `new'
/Users/davida/.rvm/rubies/jruby-9.1.8.0/lib/ruby/stdlib/json/common.rb:155:in `parse'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/json/decoding.rb:21:in `decode'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activerecord-5.0.1/lib/active_record/coders/json.rb:9:in `load'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activerecord-5.0.1/lib/active_record/type/serialized.rb:18:in `deserialize'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activerecord-5.0.1/lib/active_record/attribute.rb:140:in `type_cast'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activerecord-5.0.1/lib/active_record/attribute.rb:38:in `value'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/core_ext/hash/transform_values.rb:16:in `block in transform_values'
org/jruby/RubyHash.java:1343:in `each'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/core_ext/hash/transform_values.rb:15:in `transform_values'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activerecord-5.0.1/lib/active_record/attribute_set.rb:24:in `to_hash'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activerecord-5.0.1/lib/active_record/attribute_methods.rb:276:in `attributes'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activemodel-5.0.1/lib/active_model/serialization.rb:127:in `serializable_hash'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activerecord-5.0.1/lib/active_record/serialization.rb:17:in `serializable_hash'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activemodel-5.0.1/lib/active_model/serializers/json.rb:99:in `as_json'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/core_ext/object/json.rb:161:in `block in as_json'
org/jruby/RubyHash.java:1343:in `each'
org/jruby/RubyEnumerable.java:830:in `map'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/core_ext/object/json.rb:161:in `as_json'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/core_ext/object/json.rb:142:in `block in as_json'
org/jruby/RubyArray.java:2486:in `map'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/core_ext/object/json.rb:142:in `as_json'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/core_ext/object/json.rb:161:in `block in as_json'
org/jruby/RubyHash.java:1343:in `each'
org/jruby/RubyEnumerable.java:830:in `map'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/core_ext/object/json.rb:161:in `as_json'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/core_ext/object/json.rb:161:in `block in as_json'
org/jruby/RubyHash.java:1343:in `each'
org/jruby/RubyEnumerable.java:830:in `map'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/core_ext/object/json.rb:161:in `as_json'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/json/encoding.rb:33:in `encode'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/json/encoding.rb:20:in `encode'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/core_ext/object/json.rb:37:in `to_json'
/Users/davida/Developer/sandbox/app/lib/instrument.rb:37:in `log'
/Users/davida/Developer/sandbox/app/lib/instrument.rb:14:in `handle_exception'
/Users/davida/Developer/sandbox/app/lib/instrument.rb:9:in `instrument'
/Users/davida/Developer/sandbox/app/workers/async_worker.rb:15:in `do_perform'
/Users/davida/Developer/sandbox/app/workers/async_worker.rb:8:in `perform'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:204:in `execute_job'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:175:in `block in process'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:174:in `block in process'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:146:in `block in dispatch'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/job_retry.rb:97:in `local'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:145:in `block in dispatch'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/rails.rb:43:in `block in call'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/reloader.rb:68:in `block in wrap'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/activesupport-5.0.1/lib/active_support/reloader.rb:67:in `wrap'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/rails.rb:42:in `call'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:141:in `block in dispatch'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:220:in `stats'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:136:in `block in dispatch'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/job_logger.rb:8:in `call'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:135:in `block in dispatch'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/job_retry.rb:72:in `global'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:134:in `block in dispatch'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/logging.rb:32:in `with_context'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:133:in `dispatch'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:173:in `process'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:86:in `process_one'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:73:in `run'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/util.rb:17:in `watchdog'
/Users/davida/.rvm/gems/jruby-9.1.8.0@rails5/gems/sidekiq-5.0.0/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

**Comment by hobodave** [comment]
Some of those lines may be from multiple threads, unsure.

**Comment by mperham** [comment]
This is the app code with the problem:

```
/Users/davida/Developer/sandbox/app/lib/instrument.rb:37:in `log'
/Users/davida/Developer/sandbox/app/lib/instrument.rb:14:in `handle_exception'
/Users/davida/Developer/sandbox/app/lib/instrument.rb:9:in `instrument'
/Users/davida/Developer/sandbox/app/workers/async_worker.rb:15:in `do_perform'
```

You need to inspect the actual thing you are converting to json.

**Comment by hobodave** [comment]
@mperham Yes, that line is this one:

```
    print "#{log_line.to_json}\n"
```

`log_line` here is a `Hash` within which is an instance of an `ActiveRecord` model.

I opened the issue here with Sidekiq, because I've encountered this *only* in Sidekiq. I cannot reproduce this bug in either rails console, or in a multi-threaded application server (Puma) under highly concurrent load. 

Don't get me wrong. I'm not saying this "proves" that the bug lies within Sidekiq. It could certainly be a Rails bug that is somehow only exposed due to how Sidekiq uses Rails. It does seem autoloading related because, if I enqueue a single job and wait for it to finish, then I can enqueue thousands of jobs without experiencing the bug.

**Comment by mperham** [comment]
You'll need to debug more yourself, there's no way to tell what's happening.  Please open an issue if you do find a problem with Sidekiq.

**Comment by mperham** [comment]
https://github.com/rails/rails/issues/28589

**Comment by hobodave** [comment]
@mperham Wow, thanks for that find in rails!

**Comment by nasa42** [comment]
@hobodave You're welcome :wink:.
