### ISSUE TITLE
[Sidekiq-web] 5.0.2 is missing stringify_keys

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#3517]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 5.0.2 standard

Please include your initializer and any error message with the full backtrace.

Are you using an old version? No
Have you checked the changelog to see if your issue has been fixed in a later version? Yes, using latest

https://github.com/mperham/sidekiq/blob/master/Changes.md

Good afternoon!

I recently upgraded our Sidekiq installation to 5.0.2 to find out our sidekiq cron plugin (https://rubygems.org/gems/sidekiq-cron) was broken. I've pasted the full stack trace for the error below.

I tried updating the cron gem and it didn't help. The only thing that ended up fixing this (error taken from sidekiq-web.log fwiw) was downgrading sidekiq to 5.0.0

As far as I can tell this function is typically found in a active support libraries? Not too familiar with the whole rails ecosystem.

Not sure if this is the best place to submit this issue, but since the breaking change came from sidekiq first, I figured maybe I should start here.

Thanks again Mike!

```
#<NoMethodError: undefined method `stringify_keys' for #<Hash:0x007f9e6b003e88>>
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-cron-0.6.0/lib/sidekiq/cron/job.rb:259:in `initialize'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-cron-0.6.0/lib/sidekiq/cron/job.rb:213:in `new'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-cron-0.6.0/lib/sidekiq/cron/job.rb:213:in `block in all'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-cron-0.6.0/lib/sidekiq/cron/job.rb:211:in `collect'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-cron-0.6.0/lib/sidekiq/cron/job.rb:211:in `all'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-cron-0.6.0/lib/sidekiq/cron/web_extension.rb:13:in `block in registered'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.2/lib/sidekiq/web/application.rb:266:in `instance_exec'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.2/lib/sidekiq/web/application.rb:266:in `block in call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.2/lib/sidekiq/web/application.rb:262:in `catch'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.2/lib/sidekiq/web/application.rb:262:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:153:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.2/lib/sidekiq/web.rb:103:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.2/lib/sidekiq/web.rb:108:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/auth/basic.rb:25:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by mperham** [comment]
that is a bug in sidekiq-cron and needs to be fixed there.

**Comment by bobber205** [comment]
Do you have any insights I could pass onto the sidekiq-cron dev(s)?

**Comment by mperham** [comment]
They were relying on a Sidekiq monkeypatch which was removed in 5.0.1.
