### ISSUE TITLE
Zip::Error: File /tmp/RackMultipart20170623-15768-ev7uga.zip not found

### ISSUE THREAD

**Issue by JohnMerlino2** [mperham/sidekiq#3526]
Ruby version: ruby 2.1.2p95
Sidekiq / Pro / Enterprise version(s):  4.2.3

Please include your initializer and any error message with the full backtrace.

```
2017-06-23T23:45:05.307Z 15948 TID-15l300 DocketPlusWorker JID-059c683009a5832d8e7522af INFO: start
2017-06-23T23:45:05.313Z 15948 TID-15l300 DocketPlusWorker JID-059c683009a5832d8e7522af INFO: fail: 0.006 sec
2017-06-23T23:45:05.313Z 15948 TID-15l300 WARN: {"context":"Job raised exception","job":{"class":"DocketPlusWorker","args":[16],"retry":true,"queue":"docket_plus","jid":"059c683009a5832d8e7522af","created_at":1498261313.885231,"enqueued_at":1498261505.305978,"error_message":"File /tmp/RackMultipart20170623-15768-ev7uga.zip not found","error_class":"Zip::Error","failed_at":1498261313.961126,"retry_count":3,"retried_at":1498261505.3126674},"jobstr":"{\"class\":\"DocketPlusWorker\",\"args\":[16],\"retry\":true,\"queue\":\"docket_plus\",\"jid\":\"059c683009a5832d8e7522af\",\"created_at\":1498261313.885231,\"enqueued_at\":1498261505.305978,\"error_message\":\"File /tmp/RackMultipart20170623-15768-ev7uga.zip not found\",\"error_class\":\"Zip::Error\",\"failed_at\":1498261313.961126,\"retry_count\":2,\"retried_at\":1498261415.9474726}"}
2017-06-23T23:45:05.313Z 15948 TID-15l300 WARN: Zip::Error: File /tmp/RackMultipart20170623-15768-ev7uga.zip not found
2017-06-23T23:45:05.313Z 15948 TID-15l300 WARN: /usr/local/rvm/gems/ruby-2.1.2@core/gems/rubyzip-1.2.0/lib/zip/file.rb:85:in `initialize'
/usr/local/rvm/gems/ruby-2.1.2@core/gems/rubyzip-1.2.0/lib/zip/file.rb:99:in `new'
/usr/local/rvm/gems/ruby-2.1.2@core/gems/rubyzip-1.2.0/lib/zip/file.rb:99:in `open'
/home/core/core/lib/file_parser/parsers/practice.rb:13:in `read'
```
Error occurs here:

zip = Zip::File.open(@file)

However, this line of code was running file before I started using sidekiq to process it. Furthermore, when i run rails console production and run that line of code, the file unzips without any issue. This error only occurs when I try running it within sidekiq. What could be the issue here?

**Comment by mperham** [comment]
I suspect you are relying on a tempfile to exist across processes.  Not safe.  You need to copy that RackMultipart file to somewhere more permanent for Sidekiq to process it.

**Comment by maximbond** [comment]
@JohnMerlino2 did you get it working?
