### ISSUE TITLE
Processing jobs in queue

### ISSUE THREAD

**Issue by Rubioli** [mperham/sidekiq#3549]
Im new to background-jobs in Rails and `Sidekiq`. I have set everything up and I can see my workers in queue, but how can I process list in queue and set them to database?

One of workers is for `Ahoy gem` and I'm adding events to the queue.

*app/workers/visit_worker.rb*
```
class VisitWorker
  include Sidekiq::Worker
  sidekiq_options retry: false
  sidekiq_options queue: 'events'

  def perform(post_id)
    post = Post.find(post_id)
    ahoy.track "with sidekiq", id: post.id
  end
end
```

*app/controller/posts_controller.rb*
```
def show
    VisitWorker.perform_async(@post.id)
end
```

As said, I can see my events in Sidekiq WebUI in queues, but how can I make them so that they will be set to my `ahoy_events` table in database?

**My other settings:**
*app/config/application.rb*
`config.active_job.queue_adapter = :sidekiq`

*app/config/routes.rb*
```
require 'sidekiq/web'
mount Sidekiq::Web => '/sidekiq'
```

*app/config/sidekiq.yml (I found this from one of examples)*
```
:concurrency: 1
#:pidfile: tmp/pids/sidekiq.pid
#:logfile: log/sidekiq.log
development:
  :concurrency: 1
staging:
  :concurrency: 2
production:
  :concurrency: 10
:queues:
  - events

tasks: &tasks
  NotifierJob:
    every: ["2s"]
    queue: notifier
    description: 'Send pending notifications'

:schedule:
  <<: *tasks
```

*gem 'sidekiq', '~> 4.2', '>= 4.2.10'*
*gem 'redis', '~> 3.3', '>= 3.3.3'*
*Rails Version: 4.2.4*
*Ruby Version: 2.2.1*

**Comment by mperham** [comment]
You need to start Sidekiq. Bundle exec sidekiq

**Comment by Rubioli** [comment]
Thanks for your reply @mperham. When I run `Bundle exec sidekiq` I get error for one my workers.

I have a `UserBalance` which for each impression, it needs to `increment` a price.

*app/workers/balance_worker.rb*
```
class BalanceWorker
  include Sidekiq::Worker
  sidekiq_options queue: 'balances'

  def perform(publisher, amount)
    a = UserBalance.find_by_user_id(publisher).decrement(:balance, amount * 100)
    a.save
  end
end
```

*app/models/visit.rb*
```
class Visit < ActiveRecord::Base
    after_create :take_form_balance
    private
    def take_form_balance
      BalanceWorker.perform_async(self.publisher, self.price)
    end
```

When I ran `Bundle exec sidekiq`, I got this error:
```
2017-07-14T12:11:59.145Z 11829 TID-ovvlfzwis BalanceWorker JID-75ecb21175266f0ddef59016 INFO: start
2017-07-14T12:11:59.174Z 11829 TID-ovvlfzwis BalanceWorker JID-75ecb21175266f0ddef59016 INFO: fail: 0.029 sec
2017-07-14T12:11:59.175Z 11829 TID-ovvlfzwis WARN: {"context":"Job raised exception","job":{"class":"BalanceWorker","args":[1,"0.008"],"retry":true,"queue":"balances","jid":"75ecb21175266f0ddef59016","created_at":1500034293.493824,"enqueued_at":1500034293.4952629,"error_message":"String can't be coerced into BigDecimal","error_class":"TypeError","failed_at":1500034319.174428,"retry_count":0},"jobstr":"{\"class\":\"BalanceWorker\",\"args\":[1,\"0.008\"],\"retry\":true,\"queue\":\"balances\",\"jid\":\"75ecb21175266f0ddef59016\",\"created_at\":1500034293.493824,\"enqueued_at\":1500034293.4952629}"}
2017-07-14T12:11:59.175Z 11829 TID-ovvlfzwis WARN: TypeError: String can't be coerced into BigDecimal
2017-07-14T12:11:59.175Z 11829 TID-ovvlfzwis WARN: /Users/David/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/persistence.rb:330:in `-'
/Users/David/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/persistence.rb:330:in `decrement'
/Users/David/Desktop/_RUBY/projects/social/app/workers/balance_worker.rb:7:in `perform'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:167:in `execute_job'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:139:in `block (5 levels) in process'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq.rb:36:in `call'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:135:in `call'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:135:in `block (4 levels) in process'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/logging.rb:10:in `call'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `call'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:134:in `block (3 levels) in process'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:183:in `stats'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq.rb:35:in `call'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `call'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
/Users/David/.rvm/gems/ruby-2.2.1/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

Any help is very appreciated!

**Comment by mperham** [comment]
Please read the wiki, esp the Best Practices page which talks about the underlying cause of you problem.
