### ISSUE TITLE
Parameterized mailers compatibility?

### ISSUE THREAD

**Issue by ydakuka** [mperham/sidekiq#3552]
Ruby version: 2.3.1
Rails 5.1.2
Sidekiq version: 5.0.4

Is Sidekiq working with parameterized mailers?

```
[38] pry(#<Dashboard::PaymentsController>)> NotificationsMailer.with(user: current_user).new_payment_for_mentor
OK!

But the following code does not work:

[39] pry(#<Dashboard::PaymentsController>)> NotificationsMailer.delay.with(user: current_user).new_payment_for_mentor
NoMethodError: undefined method `new_payment_for_mentor' for "0c02e8468c08fe344f3264aa":String
from (pry):17:in `create'

[40] pry(#<Dashboard::PaymentsController>)> NotificationsMailer.with(user: current_user).delay.new_payment_for_mentor
NoMethodError: undefined method `delay' for #<ActionMailer::Parameterized::Mailer:0x00000009edc390>
from /home/ydakuka/.rvm/gems/ruby-2.3.1@myproject/gems/actionmailer-5.1.2/lib/action_mailer/parameterized.rb:113:in `method_missing'

[41] pry(#<Dashboard::PaymentsController>)> NotificationsMailer.with(user: current_user).new_payment_for_mentor.delay
NotificationsMailer#new_payment_for_mentor: processed outbound mail in 70.9ms
NameError: undefined method `delay' for module `Kernel'
Did you mean?  delay
from /home/ydakuka/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/delegate.rb:85:in `instance_method'
```

**Comment by mperham** [comment]
Nope, try using ActiveJob's deliver_later instead of the delayed extensions.

**Comment by kapso** [comment]
@mperham  
So does that mean parameterized mailers will work with `deliver_later` or mailer parameters are not supported at all?

So will the below work as long as Sidekiq is used as the adapter for active_job?

`OrderMailer.with(id: 20).send_details.deliver_later`

```ruby
class OrderMailer < ApplicationMailer
  def send_details
    @order = Order.find(params[:id])
  end
end
```

**Comment by ydakuka** [comment]
Yes.
