### ISSUE TITLE
trouble with Batch jobs while main thread is still running

### ISSUE THREAD

**Issue by jakeonfire** [mperham/sidekiq#3563]
Ruby version: 2.4.1
Sidekiq / Pro / Enterprise version(s): 4.2.10 / Sidekiq Pro 3.5.1 / Sidekiq Enterprise 1.6.0

I'm attempting to make a processing "pipeline" more performant by breaking a loop of work from a big job out into a batch, then process the output from that batch as it is available (with `Redis#brpop`) back in the main job. The problem is, as long as the main job is still running - whether blocking on `brpop`, sleeping, or doing some pointless loop - all of the batch jobs (which are mostly doing DB lookups) get stuck on a monitor. As soon as the main job errors out, the batch jobs thunder to completion.

Any ideas @mperham ?

main worker thread:
```
2017-07-28T01:36:56.969Z 5754 TID-owjghxhi4 WARN: Thread TID-owjgq621o processor
2017-07-28T01:36:56.969Z 5754 TID-owjghxhi4 WARN: /Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/connection/ruby.rb:87:in `select'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/connection/ruby.rb:87:in `rescue in _read_from_socket'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/connection/ruby.rb:83:in `_read_from_socket'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/connection/ruby.rb:75:in `gets'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/connection/ruby.rb:380:in `read'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/client.rb:262:in `block in read'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/client.rb:250:in `io'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/client.rb:261:in `read'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/client.rb:120:in `block in call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/client.rb:231:in `block (2 levels) in process'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/client.rb:367:in `ensure_connected'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/client.rb:221:in `block in process'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/client.rb:306:in `logging'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/client.rb:220:in `process'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/client.rb:120:in `call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/client.rb:209:in `block in call_with_timeout'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/client.rb:280:in `with_socket_timeout'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis/client.rb:208:in `call_with_timeout'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis.rb:1205:in `block in brpoplpush'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
/Users/x/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/redis-3.3.3/lib/redis.rb:1202:in `brpoplpush'
/Users/x/workspace/orange/app/models/coverage_mergers/base.rb:43:in `block in for_each_row'
/Users/x/workspace/orange/app/models/coverage_mergers/base.rb:44:in `for_each_row'
/Users/x/workspace/orange/app/models/coverage_mergers/base.rb:72:in `analyze_file'
/Users/x/workspace/orange/app/models/coverage_mergers/synchronize.rb:16:in `analyze_file'
/Users/x/workspace/orange/app/models/coverage_mergers/base.rb:19:in `initialize'
/Users/x/workspace/orange/app/services/file_processor.rb:188:in `new'
/Users/x/workspace/orange/app/services/file_processor.rb:188:in `coverage_merger'
/Users/x/workspace/orange/app/services/file_processor.rb:194:in `validation_errors'
/Users/x/workspace/orange/app/services/file_processor.rb:100:in `adapt_and_validate'
/Users/x/workspace/orange/app/services/file_processor.rb:22:in `process'
/Users/x/workspace/orange/app/workers/file_processor_worker.rb:34:in `block (2 levels) in perform'
/Users/x/workspace/orange/app/workers/batch_job.rb:3:in `perform'
/Users/x/workspace/orange/app/workers/file_processor_worker.rb:11:in `block in perform'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-ent-1.6.0/lib/sidekiq-ent/limiter/concurrent.rb:59:in `within_limit'
/Users/x/workspace/orange/app/workers/file_processor_worker.rb:10:in `perform'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq_status-1.2.0/lib/sidekiq_status/worker.rb:23:in `block in perform'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq_status-1.2.0/lib/sidekiq_status/worker.rb:21:in `catch'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq_status-1.2.0/lib/sidekiq_status/worker.rb:21:in `perform'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:167:in `execute_job'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:139:in `block (5 levels) in process'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:135:in `block (4 levels) in process'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-pro-3.5.1/lib/sidekiq/batch/middleware.rb:33:in `call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-ent-1.6.0/lib/sidekiq-ent/limiter/middleware.rb:38:in `call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/logging.rb:10:in `call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/bugsnag-5.3.3/lib/bugsnag/sidekiq.rb:16:in `call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:134:in `block (3 levels) in process'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:183:in `stats'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/rails.rb:106:in `block in call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/reloader.rb:68:in `block in wrap'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/reloader.rb:67:in `wrap'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/rails.rb:105:in `call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

and 19 batch worker threads (out of many more) b/c 20:
```
2017-07-28T01:36:56.959Z 5754 TID-owjghxhi4 WARN: Thread TID-owjgq6evc processor
2017-07-28T01:36:56.959Z 5754 TID-owjghxhi4 WARN: /Users/x/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:111:in `sleep'
/Users/x/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:111:in `wait'
/Users/x/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:111:in `wait'
/Users/x/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:123:in `wait_while'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/concurrency/share_lock.rb:219:in `wait_for'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/concurrency/share_lock.rb:81:in `block (2 levels) in start_exclusive'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/concurrency/share_lock.rb:80:in `block in start_exclusive'
/Users/x/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/concurrency/share_lock.rb:75:in `start_exclusive'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/concurrency/share_lock.rb:147:in `exclusive'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/dependencies/interlock.rb:11:in `loading'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:36:in `load_interlock'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:357:in `require_or_load'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:510:in `load_missing_constant'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:6:in `with_bootsnap_fallback'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `load_missing_constant'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:202:in `const_missing'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:542:in `load_missing_constant'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:6:in `with_bootsnap_fallback'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/bootsnap-1.1.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `load_missing_constant'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:202:in `const_missing'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/inflector/methods.rb:271:in `const_get'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/inflector/methods.rb:271:in `block in constantize'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/inflector/methods.rb:267:in `each'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/inflector/methods.rb:267:in `inject'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/inflector/methods.rb:267:in `constantize'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/inflector/methods.rb:312:in `safe_constantize'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:588:in `safe_get'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:619:in `safe_constantize'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activerecord-5.1.2/lib/active_record/inheritance.rb:159:in `block in compute_type'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activerecord-5.1.2/lib/active_record/inheritance.rb:158:in `each'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activerecord-5.1.2/lib/active_record/inheritance.rb:158:in `compute_type'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activerecord-5.1.2/lib/active_record/reflection.rb:403:in `compute_class'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activerecord-5.1.2/lib/active_record/reflection.rb:399:in `klass'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activerecord-5.1.2/lib/active_record/associations/association.rb:127:in `klass'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activerecord-5.1.2/lib/active_record/associations/belongs_to_association.rb:58:in `find_target?'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activerecord-5.1.2/lib/active_record/associations/association.rb:157:in `load_target'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activerecord-5.1.2/lib/active_record/associations/association.rb:53:in `reload'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activerecord-5.1.2/lib/active_record/associations/singular_association.rb:7:in `reader'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activerecord-5.1.2/lib/active_record/associations/builder/association.rb:111:in `person'
/Users/x/workspace/orange/app/models/coverage_mergers/row.rb:19:in `initialize'
/Users/x/workspace/orange/app/models/coverage_mergers/base.rb:127:in `new'
/Users/x/workspace/orange/app/models/coverage_mergers/base.rb:127:in `perform'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:167:in `execute_job'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:139:in `block (5 levels) in process'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:135:in `block (4 levels) in process'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-pro-3.5.1/lib/sidekiq/batch/middleware.rb:26:in `call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-ent-1.6.0/lib/sidekiq-ent/limiter/middleware.rb:38:in `call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/logging.rb:10:in `call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/bugsnag-5.3.3/lib/bugsnag/sidekiq.rb:16:in `call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:134:in `block (3 levels) in process'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:183:in `stats'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/rails.rb:106:in `block in call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/reloader.rb:68:in `block in wrap'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/activesupport-5.1.2/lib/active_support/reloader.rb:67:in `wrap'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/rails.rb:105:in `call'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
/Users/x/.rvm/gems/ruby-2.4.1@orange/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

**Comment by jakeonfire** [comment]
uh, development's `config.eager_load = true` fixed it. n/m!
