### ISSUE TITLE
NoMethodError: undefined method members for #<Object> in Psych.load

### ISSUE THREAD

**Issue by james2m** [mperham/sidekiq#3565]
In lib/delay.rb:13 Psych::Visitors::ToRuby.resolve_class is prepended with the following; 

```ruby
      def resolve_class(klass_name)
        return klass_name unless klass_name
        # constantize
        names = klass_name.split('::')
        names.shift if names.empty? || names.first.empty?

        names.inject(Object) do |constant, name|
          constant.const_defined?(name) ? constant.const_get(name) : constant.const_missing(name)
        end
      rescue NameError
        super
      end
```

Given an empty string this version of resolve class always returns Object from names.inject(Object). Psych depends on nil being returned in order to de-serialize a serialized Struct.

```
Loading development environment (Rails 4.2.8)
2.3.3 :001 > struct = Struct.new(:attributes)
 => #<Class:0x007fcea8651ac0> 
2.3.3 :002 > obj = struct.new(Hash[this: 1, that: 2])
 => #<struct attributes={:this=>1, :that=>2}> 
2.3.3 :003 > Psych.load(Psych.dump(obj))
NoMethodError: undefined method `members' for #<Object:0x007fcea86599f0>
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/psych-2.2.4/lib/psych/visitors/to_ruby.rb:172:in `visit_Psych_Nodes_Mapping'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/psych-2.2.4/lib/psych/visitors/visitor.rb:16:in `visit'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/psych-2.2.4/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/psych-2.2.4/lib/psych/visitors/to_ruby.rb:32:in `accept'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/psych-2.2.4/lib/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/psych-2.2.4/lib/psych/visitors/visitor.rb:16:in `visit'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/psych-2.2.4/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/psych-2.2.4/lib/psych/visitors/to_ruby.rb:32:in `accept'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/psych-2.2.4/lib/psych/nodes/node.rb:38:in `to_ruby'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/psych-2.2.4/lib/psych.rb:253:in `load'
	from (irb):6
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
... 5 levels...
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/spring-2.0.1/lib/spring/commands/rails.rb:6:in `call'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/spring-2.0.1/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/spring-2.0.1/lib/spring/application.rb:191:in `block in serve'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/spring-2.0.1/lib/spring/application.rb:161:in `fork'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/spring-2.0.1/lib/spring/application.rb:161:in `serve'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
	from /Users/james/.rvm/gems/ruby-2.3.3@my-app/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/james/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/james/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s): 5.0.4 

The correct behaviour without the monkey patch to Psych;

```
Loading development environment (Rails 4.2.8)
2.3.3 :001 >  struct = Struct.new(:attributes)
 => #<Class:0x007fb9eca28070> 
2.3.3 :002 > obj = struct.new(Hash[this: 1, that: 2])
 => #<struct attributes={:this=>1, :that=>2}> 
2.3.3 :003 > Psych.load(Psych.dump(obj))
 => #<struct attributes={:this=>1, :that=>2}> 
```

The fix, which is the exact same behaviour as Psych::ClassLoader.load;
```ruby
      def resolve_class(klass_name)
        return nil if !klass_name || klass_name.empty?
        # constantize
        names = klass_name.split('::')
        names.shift if names.empty? || names.first.empty?

        names.inject(Object) do |constant, name|
          constant.const_defined?(name) ? constant.const_get(name) : constant.const_missing(name)
        end
      rescue NameError
        super
      end

**Comment by mperham** [comment]
Please send a PR?

**Comment by mperham** [comment]
I think empty? requires ActiveSupport.

**Comment by james2m** [comment]
It's a method on String since 2.0.0, not checked back further than that.

**Comment by mperham** [comment]
:+1:

**Comment by mperham** [comment]
Oh I'm thinking of blank?
