### ISSUE TITLE
Enqueuing Jobs with API causes queue tab to throw an error

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#3581]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 5.0.4

Please include your initializer and any error message with the full backtrace.

Are you using an old version? No
Have you checked the changelog to see if your issue has been fixed in a later version? Yes, on recent

Sometimes when checking the "enqueued jobs" section of the sidekiq-web I get a strange error.

I usually ignore because it isn't usually too important but today it was so I looked into the logs.

```
2017-08-14 19:28:42 +0000: Rack app error handling request { GET /queues/workers }
#<NoMethodError: undefined method `map' for "{\"id\":251358,\"type\":\"oauth\"}":String
Did you mean?  tap>
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.4/lib/sidekiq/web/helpers.rb:207:in `display_args'
(eval):33:in `block in _erb_queue'
(eval):23:in `each'
(eval):23:in `each_with_index'
(eval):23:in `_erb_queue'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.4/lib/sidekiq/web/action.rb:85:in `_erb'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.4/lib/sidekiq/web/action.rb:54:in `erb'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.4/lib/sidekiq/web/application.rb:75:in `block in <class:WebApplication>'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.4/lib/sidekiq/web/application.rb:266:in `instance_exec'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.4/lib/sidekiq/web/application.rb:266:in `block in call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.4/lib/sidekiq/web/application.rb:262:in `catch'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.4/lib/sidekiq/web/application.rb:262:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:153:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.4/lib/sidekiq/web.rb:103:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.4/lib/sidekiq/web.rb:108:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/auth/basic.rb:25:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

Could this be a plugin issue or something?
This job was enqueued using the API and not a class reference (perform_async)

Here's another example

```
#<NoMethodError: undefined method `map' for "{\"id\":2081146,\"type\":\"hashtag\"}":String
Did you mean?  tap>
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-5.0.4/lib/sidekiq/web/helpers.rb:207:in `display_args'
(eval):33:in `block in _erb_queue'
(eval):23:in `each'
(eval):23:in `each_with_index'
(eval):23:in `_erb_queue'
/home/ubuntu/.rbenv/versions/2.3.1/l
```

**Comment by mperham** [comment]
Show us the enqueuing code

**Comment by bobber205** [comment]
Something like this

```
        Sidekiq::Client.new.push(
        'queue' => 'default',
        'class' => 'Chirpify::AnalyzerWorker',
        'args' => [{:msg => msg, :hashtags => [] }])
```

**Comment by mperham** [comment]
You'll need to give the exact code so I can reproduce the problem.  Something like that works fine for me.
