### ISSUE TITLE
Sidekiq::Limiter doesn't use the default pool

### ISSUE THREAD

**Issue by harmdewit** [mperham/sidekiq#3583]
[The wiki says](https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#redis):

> By default, the Sidekiq::Limiter API uses Sidekiq's default Redis pool so you don't need to configure anything.

In my config I have the port configured to 6384, but when Passenger tries to start the application it fails on connecting to the default port 6379. Does this mean that Sidekiq doesn't use the default config?

Ruby version: ruby 2.3.3p222
Sidekiq / Pro / Enterprise version(s): 5.0.0 / 3.5.0 / 1.5.2

Please include your initializer and any error message with the full backtrace.

```ruby
# config/redis.yml
production:
  host: localhost
  port: 6384
  database: 0
```

``` ruby
# config/initializers/sidekiq.rb
redis_yml        = "#{Rails.root}/config/redis.yml"
redis_config   = YAML.load(ERB.new(File.read(redis_yml)).result)[Rails.env]
redis_uri = "redis://#{redis_config['host']}:#{redis_config['port']}/#{redis_config['database']}"

redis_config = {
  url:                   redis_uri,
  concurrency:  15
}

Sidekiq::Extensions.enable_delay!

Sidekiq.configure_server do |config|
  config.redis = redis_config
end

if defined?(PhusionPassenger)
  PhusionPassenger.on_event(:starting_worker_process) do |forked|
    Rails.logger.info "Sidekiq client configured with: #{redis_config}"
    Sidekiq.configure_client do |config|
      config.redis = redis_config
    end
  end
else
  Rails.logger.info "Sidekiq client configured with: #{redis_config}"
  Sidekiq.configure_client do |config|
    config.redis = redis_config
  end
end
```

When I add limiter configuration then it seems to work:

```ruby
# config/initializers/sidekiq.rb
...
Sidekiq::Limiter.configure do |config|
  config.redis = redis_config
end
...
```

Traceback:

```
# passenger.log
18136 [ 2017-08-22 16:34:00.5756 14545/7f8bd013c700 age/Cor/Con/CheckoutSession.cpp:273 ]: [Client 5-1] Cannot checkout session because a spawning error occurred. The identifier of the error is b60ee92f. Please see earlier logs for details about the error.
18137 App 19252 stdout:
18138 App 19252 stdout:
18139 [ 2017-08-22 16:34:20.2131 14545/7f8bcceb1700 age/Cor/App/Implementation.cpp:289 ]: Could not spawn process for application /srv/healthcare/mdwp_d/current: An error occurred while starting up the preloader.
18140   Error ID: bbd6f02d
18141   Error details saved to: /tmp/passenger-error-WH6q8D.html
18142   Message from application: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)
18143   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:345:in `rescue in establish_connection'
18144   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:331:in `establish_connection'
18145   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:101:in `block in connect'
18146   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:293:in `with_reconnect'
18147   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:100:in `connect'
18148   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:364:in `ensure_connected'
18149   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:221:in `block in process'
18150   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:306:in `logging'
18151   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:220:in `process'
18152   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:120:in `call'
18153   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/newrelic-redis-2.0.2/lib/newrelic_redis/instrumentation.rb:36:in `block in call_with_newrelic_trace'
18154   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/datastores.rb:111:in `wrap'
18155   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/newrelic-redis-2.0.2/lib/newrelic_redis/instrumentation.rb:35:in `call_with_newrelic_trace'
18156   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis.rb:2385:in `block in script'
18157   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
18158   /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
18159   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
18160   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis.rb:2384:in `script'
18161   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/sidekiq-ent-1.5.2/lib/sidekiq-ent/scripting.rb:13:in `block (2 levels) in bootstrap'
18162   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/sidekiq-ent-1.5.2/lib/sidekiq-ent/scripting.rb:12:in `each'
18163   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/sidekiq-ent-1.5.2/lib/sidekiq-ent/scripting.rb:12:in `each_with_object'
18164   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/sidekiq-ent-1.5.2/lib/sidekiq-ent/scripting.rb:12:in `block in bootstrap'
18165   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
18166   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
18167   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
18168   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
18169   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
18170   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/sidekiq-ent-1.5.2/lib/sidekiq-ent/scripting.rb:11:in `bootstrap'
18171   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/sidekiq-ent-1.5.2/lib/sidekiq-ent/scripting.rb:20:in `call'
18172   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/sidekiq-ent-1.5.2/lib/sidekiq-ent/limiter/concurrent.rb:39:in `initialize'
18173   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/sidekiq-ent-1.5.2/lib/sidekiq-ent/limiter.rb:124:in `new'
18174   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/sidekiq-ent-1.5.2/lib/sidekiq-ent/limiter.rb:124:in `concurrent'
18175   /srv/healthcare/mdwp_d/releases/20170822142826/app/workers/cupido_sync_worker.rb:5:in `<class:CupidoSyncWorker>'
18176   /srv/healthcare/mdwp_d/releases/20170822142826/app/workers/cupido_sync_worker.rb:1:in `<top (required)>'
18177   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
18178   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
18179   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
18180   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
18181   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:360:in `require_or_load'
18182   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:317:in `depend_on'
18183   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:233:in `require_dependency'
18184   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
18185   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:471:in `each'
18186   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:471:in `block in eager_load!'
18187   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:469:in `each'
18188   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:469:in `eager_load!'
18189   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:346:in `eager_load!'
18190   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application/finisher.rb:56:in `each'
18191   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
18192   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
18193   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
18194   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
18195   /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
18196   /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
18197   /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
18198   /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
18199   /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
18200   /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
18201   /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
18202   /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
18203   /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
18204   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
18205   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
18206   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
18207   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
18208   /srv/healthcare/mdwp_d/releases/20170822142826/config/environment.rb:5:in `<top (required)>'
18209   config.ru:3:in `require'
18210   config.ru:3:in `block in <main>'
18211   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
18212   /srv/healthcare/mdwp_d/shared/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
18213   config.ru:1:in `new'
18214   config.ru:1:in `<main>'
18215   /usr/local/rvm/gems/ruby-2.3.3@global/gems/passenger-enterprise-server-5.0.30/src/helper-scripts/rack-preloader.rb:94:in `eval'
18216   /usr/local/rvm/gems/ruby-2.3.3@global/gems/passenger-enterprise-server-5.0.30/src/helper-scripts/rack-preloader.rb:94:in `preload_app'
18217   /usr/local/rvm/gems/ruby-2.3.3@global/gems/passenger-enterprise-server-5.0.30/src/helper-scripts/rack-preloader.rb:140:in `<module:App>'
18218   /usr/local/rvm/gems/ruby-2.3.3@global/gems/passenger-enterprise-server-5.0.30/src/helper-scripts/rack-preloader.rb:14:in `<module:PhusionPassenger>'
18219   /usr/local/rvm/gems/ruby-2.3.3@global/gems/passenger-enterprise-server-5.0.30/src/helper-scripts/rack-preloader.rb:13:in `<main>'
18220 
18221 
18222 [ 2017-08-22 16:34:20.3181 14545/7f8bcf8ba700 age/Cor/Con/CheckoutSession.cpp:273 ]: [Client 6-1] Cannot checkout session because a spawning error occurred. The identifier of the error is bbd6f02d. Please see earlier logs for details about the error.
```

**Comment by mperham** [comment]
Change your initializer to this and see if it works.  Rails is eager loading your code and touching the limiters before the Passenger callback is invoked.

```ruby
# config/initializers/sidekiq.rb
redis_yml        = "#{Rails.root}/config/redis.yml"
redis_config   = YAML.load(ERB.new(File.read(redis_yml)).result)[Rails.env]
redis_uri = "redis://#{redis_config['host']}:#{redis_config['port']}/#{redis_config['database']}"

redis_config = {
  url:                   redis_uri,
  concurrency:  15
}

Sidekiq.configure_server do |config|
  config.redis = redis_config
end
Sidekiq.configure_client do |config|
  config.redis = redis_config
end
Sidekiq::Extensions.enable_delay!
```

**Comment by harmdewit** [comment]
Ah, of course. Tried it with the code below and it works. Thanks 👍 

```ruby
Sidekiq.configure_client do |config|
  config.redis = redis_config
end
if defined?(PhusionPassenger)
  PhusionPassenger.on_event(:starting_worker_process) do |forked|
    Sidekiq.configure_client do |config|
      config.redis = redis_config
    end
  end
end
```
