### ISSUE TITLE
Sidekiq 5 breaks non Rails apps that use middleware/server/active_record.rb

### ISSUE THREAD

**Issue by lolownia** [mperham/sidekiq#3588]
Ruby version: 2.2.6
Sidekiq / Pro / Enterprise version(s): 5.0.4

We usa Padrino (Sinatra based framework) with ActiveRecord, but we do not use Rails themselves. We use Sidekiq::Middleware::Server::ActiveRecord to auto-close connections to DB.
This is broken because on line 22 of middleware/server/active_record.rb Rails module is referenced.
Backtrace:

Please include your initializer and any error message with the full backtrace.
```
16:17:34 sidekiq.1 | 2017-08-30T14:17:34.533Z 5884 TID-1ek4yc WARN: NameError: uninitialized constant Rails
16:17:34 sidekiq.1 | 2017-08-30T14:17:34.533Z 5884 TID-1ek4yc WARN: /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/middleware/server/active_record.rb:9:in `initialize'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:146:in `new'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:146:in `make_new'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:76:in `each'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:76:in `each'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:117:in `map'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:117:in `retrieve'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:125:in `invoke'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:169:in `block in process'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:141:in `block (6 levels) in dispatch'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/job_retry.rb:97:in `local'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:140:in `block (5 levels) in dispatch'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq.rb:36:in `call'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:136:in `call'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:136:in `block (4 levels) in dispatch'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:215:in `stats'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:131:in `block (3 levels) in dispatch'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/job_logger.rb:7:in `call'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:130:in `block (2 levels) in dispatch'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/job_retry.rb:72:in `global'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:129:in `block in dispatch'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/logging.rb:44:in `with_context'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/logging.rb:38:in `with_job_hash_context'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:128:in `dispatch'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:168:in `process'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:85:in `process_one'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:73:in `run'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/util.rb:16:in `watchdog'
16:17:34 sidekiq.1 | /home/marcin/.rvm/gems/ruby-2.2.6/gems/sidekiq-5.0.4/lib/sidekiq/util.rb:25:in `block in safe_thread'
16:17:35 clock.1   | I, [2017-08-30T16:17:35.001206 #5883]  INFO -- : Triggering 'Update mailing send progress'
```

**Comment by mperham** [comment]
I'd suggest you fork and maintain your own middleware. That's not a common use case.
