### ISSUE TITLE
Dealing with Active Job 'NoMethodError'

### ISSUE THREAD

**Issue by abebraham** [mperham/sidekiq#3593]
### Environment 
Rails 5.0.3
Sidekiq Free 5.0.4
Also using simple_scheduler as well.

### Context
Currently, I am trying to integrate emailing to my scheduler rails application. 
I am having trouble with my SendEmailLaterJob. It seems that the user argument works when initially called in one of my controllers: `SendEmailLaterJob.perform_later(@user)` however, the argument changes in the second go to a number. (Example of this can be viewed in the Error Logs ctrl-f "noteworthy:")

#### SendEmailLaterJob
```ruby
class SendEmailLaterJob < ApplicationJob
  queue_as :mailers

  def perform(user)
  	FlagupMailer.flagup_test(user).deliver_later
  end
end
```
#### Error Logs
```
2017-09-04T01:39:56.566Z 39963 TID-ov6orso88 INFO: Booting Sidekiq 5.0.4 with redis options {:url=>"redis://localhost:6379/0", :id=>"Sidekiq-server-PID-39963"}


         m,
         `$b
    .ss,  $$:         .,d$
    `$$P,d$P'    .,md$P"'
     ,$$$$$bmmd$$$P^'
   .d$$$$$$$$$$P'
   $$^' `"^$$$'       ____  _     _      _    _
   $:     ,$$:       / ___|(_) __| | ___| | _(_) __ _
   `b     :$$        \___ \| |/ _` |/ _ \ |/ / |/ _` |
          $$:         ___) | | (_| |  __/   <| | (_| |
          $$         |____/|_|\__,_|\___|_|\_\_|\__, |
        .d$$                                       |_|

2017-09-04T01:39:56.721Z 39963 TID-ov6orso88 INFO: Running in ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
2017-09-04T01:39:56.721Z 39963 TID-ov6orso88 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2017-09-04T01:39:56.722Z 39963 TID-ov6orso88 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2017-09-04T01:39:56.764Z 39963 TID-ov6orso88 INFO: Starting processing, hit Ctrl-C to stop
2017-09-04T01:40:19.329Z 39963 TID-ov6otwhkc SendEmailLaterJob JID-59b6c628008fcfb1158eb06c INFO: start
Newtext: 18:40:20!!!

[2, 11] in /Users/AbeBook/Dropbox/coding/flagupmail/app/mailers/flagup_mailer.rb
    2: 	default from: "notify.text@flagupmail.com"
    3: 
    4: 	def flagup_test(user)
    5: 		
    6: 		@user = user
    7: 		@url = "https://google.com"
    8: 		debugger
=>  9: 		mail to: @user.email, subject: "Welcome to your recurring email!"
   10: 	end
   11: end
(byebug) @user
#<User id: 102, name: "gomezja", email: "gomezja@test.com", .... more info>
(byebug) @user.email
noteworthy: 1 --> "gomezja@test.com"
(byebug) continue
2017-09-04T01:40:49.556Z 39963 TID-ov6otwhkc SendEmailLaterJob JID-59b6c628008fcfb1158eb06c INFO: done: 30.227 sec
2017-09-04T01:43:17.928Z 39963 TID-ov6otweeg SimpleScheduler::FutureJob JID-7c644473fed5953f4e63f7af INFO: start
2017-09-04T01:43:17.936Z 39963 TID-ov6otweeg SimpleScheduler::FutureJob JID-7c644473fed5953f4e63f7af INFO: done: 0.008 sec
2017-09-04T01:43:17.937Z 39963 TID-ov6otlo2o SendEmailLaterJob JID-e51c180fda044d3f9a3d6440 INFO: start
Newtext: 18:43:17!!!

[2, 11] in /Users/AbeBook/Dropbox/coding/flagupmail/app/mailers/flagup_mailer.rb
    2: 	default from: "notify.text@flagupmail.com"
    3: 
    4: 	def flagup_test(user)
    5: 		
    6: 		@user = user
    7: 		@url = "https://google.com"
    8: 		debugger
=>  9: 		mail to: @user.email, subject: "Welcome to your recurring email!"
   10: 	end
   11: end
(byebug) @user
noteworthy: 2 --> 1504489380 
(byebug) user
1504489380
(byebug) continue
2017-09-04T01:44:22.977Z 39963 TID-ov6otlo2o SendEmailLaterJob JID-e51c180fda044d3f9a3d6440 INFO: fail: 65.041 sec
2017-09-04T01:44:22.978Z 39963 TID-ov6otlo2o WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"SendEmailLaterJob","queue":"default","args":[{"job_class":"SendEmailLaterJob","job_id":"57c1e2a7-4ddd-4058-8a92-2bd66ba2f58c","queue_name":"default","priority":null,"arguments":[1504489380],"locale":"en"}],"retry":true,"jid":"e51c180fda044d3f9a3d6440","created_at":1504489397.9355352,"enqueued_at":1504489397.935581,"error_message":"undefined method `email' for 1504489380:Integer","error_class":"NoMethodError","failed_at":1504489462.9770648,"retry_count":0},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"SendEmailLaterJob\",\"queue\":\"default\",\"args\":[{\"job_class\":\"SendEmailLaterJob\",\"job_id\":\"57c1e2a7-4ddd-4058-8a92-2bd66ba2f58c\",\"queue_name\":\"default\",\"priority\":null,\"arguments\":[1504489380],\"locale\":\"en\"}],\"retry\":true,\"jid\":\"e51c180fda044d3f9a3d6440\",\"created_at\":1504489397.9355352,\"enqueued_at\":1504489397.935581}"}
noteworthy: 3 ---> 2017-09-04T01:44:22.981Z 39963 TID-ov6otlo2o WARN: NoMethodError: undefined method `email' for 1504489380:Integer 
2017-09-04T01:44:22.982Z 39963 TID-ov6otlo2o WARN: /Users/AbeBook/Dropbox/coding/flagupmail/app/mailers/flagup_mailer.rb:9:in `flagup_test'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/actionpack-5.0.3/lib/abstract_controller/base.rb:188:in `process_action'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/actionpack-5.0.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:90:in `run_callbacks'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/actionpack-5.0.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/actionpack-5.0.3/lib/abstract_controller/base.rb:126:in `process'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.0.3/lib/action_mailer/rescuable.rb:23:in `block in process'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.0.3/lib/action_mailer/rescuable.rb:15:in `handle_exceptions'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.0.3/lib/action_mailer/rescuable.rb:22:in `process'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/actionview-5.0.3/lib/action_view/rendering.rb:30:in `process'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.0.3/lib/action_mailer/base.rb:595:in `block in process'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/notifications.rb:164:in `instrument'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.0.3/lib/action_mailer/base.rb:594:in `process'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.0.3/lib/action_mailer/message_delivery.rb:105:in `block in processed_mailer'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.0.3/lib/action_mailer/message_delivery.rb:104:in `tap'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.0.3/lib/action_mailer/message_delivery.rb:104:in `processed_mailer'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.0.3/lib/action_mailer/message_delivery.rb:27:in `__getobj__'
/Users/AbeBook/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/delegate.rb:80:in `method_missing'
/Users/AbeBook/Dropbox/coding/flagupmail/app/jobs/send_email_later_job.rb:8:in `perform'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.3/lib/active_job/execution.rb:34:in `block in perform_now'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:126:in `call'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:455:in `call'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/i18n-0.8.6/lib/i18n.rb:257:in `with_locale'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.3/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:391:in `instance_exec'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:285:in `block in halting'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:447:in `block in around'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:455:in `call'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.3/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/notifications.rb:164:in `instrument'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.3/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.3/lib/active_job/logging.rb:44:in `block in tag_logger'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/tagged_logging.rb:69:in `tagged'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.3/lib/active_job/logging.rb:44:in `tag_logger'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.3/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:391:in `instance_exec'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:285:in `block in halting'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:447:in `block in around'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:455:in `call'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:750:in `_run_perform_callbacks'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:90:in `run_callbacks'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.3/lib/active_job/execution.rb:33:in `perform_now'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.3/lib/active_job/execution.rb:22:in `block in execute'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:126:in `call'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:455:in `call'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.3/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/reloader.rb:68:in `block in wrap'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/execution_wrapper.rb:81:in `wrap'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/reloader.rb:67:in `wrap'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.3/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:391:in `instance_exec'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:285:in `block in halting'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:447:in `block in around'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:455:in `call'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:750:in `_run_execute_callbacks'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:90:in `run_callbacks'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.3/lib/active_job/execution.rb:20:in `execute'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.3/lib/active_job/queue_adapters/sidekiq_adapter.rb:40:in `perform'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:199:in `execute_job'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:169:in `block in process'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:141:in `block (6 levels) in dispatch'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/job_retry.rb:97:in `local'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:140:in `block (5 levels) in dispatch'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/rails.rb:42:in `block in call'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/reloader.rb:68:in `block in wrap'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.3/lib/active_support/reloader.rb:67:in `wrap'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/rails.rb:41:in `call'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:136:in `block (4 levels) in dispatch'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:215:in `stats'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:131:in `block (3 levels) in dispatch'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/job_logger.rb:7:in `call'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:130:in `block (2 levels) in dispatch'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/job_retry.rb:72:in `global'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:129:in `block in dispatch'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/logging.rb:44:in `with_context'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/logging.rb:38:in `with_job_hash_context'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:128:in `dispatch'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:168:in `process'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:85:in `process_one'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:73:in `run'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/util.rb:16:in `watchdog'
/Users/AbeBook/.rvm/gems/ruby-2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/util.rb:25:in `block in safe_thread'
2017-09-04T01:45:09.589Z 39963 TID-ov6otle24 SendEmailLaterJob JID-e51c180fda044d3f9a3d6440 INFO: start
Newtext: 18:45:09!!!

```

##### sidekiq.yml
``` yaml
# Configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.

:concurrency: 25
:timeout: 8
```
##### sidekiq.rb
``` ruby
if Rails.env == "development"
	
	Sidekiq.configure_server do |config|
	  config.redis = { url: 'redis://localhost:6379/0'  }
	end

	Sidekiq.configure_client do |config|
	  config.redis = { url: 'redis://localhost:6379/0'  }
	end
end
```

**Comment by mperham** [comment]
No idea why it would do this.

**Comment by pragashonlink** [comment]
I think the problem could be that you are trying to pass an instance of the User model into the worker method perform. It is recommended that you only pass primitive data to worker method. Try to replace the perform method with the following,

```
  def perform(user_id)
        user = User.find(user_id)
  	FlagupMailer.flagup_test(user).deliver_later
  end

```
Also, use the following method to trigger sidekiq from the app process,

`SendEmailLaterJob.perform_later(@user.id)`

**Comment by Joseen** [comment]
I have same issue like this, and I solved it.

```
{"context":"Job raised exception","job":{"class":"Schedules::SalesOrderSyncCreateJob","args":[],"retry":true,"queue":"default","jid":"fc7f2205d8a92e1475092b9a","created_at":1541741221.4967968,"enqueued_at":1541741359.528716,"error_message":"undefined method `jid=' for #<Schedules::SalesOrderSyncCreateJob:0x00007fa4549a3dc8>","error_class":"NoMethodError","failed_at":1541741221.501993,"retry_count":2,"retried_at":1541741277.4800909},"jobstr":"{\"class\":\"Schedules::SalesOrderSyncCreateJob\",\"args\":[],\"retry\":true,\"queue\":\"default\",\"jid\":\"fc7f2205d8a92e1475092b9a\",\"created_at\":1541741221.4967968,\"enqueued_at\":1541741359.528716,\"error_message\":\"undefined method `jid=' for #<Schedules::SalesOrderSyncCreateJob:0x00007fa4549a3dc8>\",\"error_class\":\"NoMethodError\",\"failed_at\":1541741221.501993,\"retry_count\":2,\"retried_at\":1541741277.4800909}"}
NoMethodError: undefined method `jid=' for #<Schedules::SalesOrderSyncCreateJob:0x00007fe2c315de90>
```

I found that reason is this Job file have incorrect file name with the class name:

- filename: `sales_order_create_job.rb`
- class name: `SalesOrderSyncCreateJob`

This may Sidekiq autoload the class from file not found it, so raise the error. After I change the filename to `sales_order_sync_create_job.rb` the job work will.

**Comment by guicassolato** [comment]
We've run into a similar case of ``NoMethodError: undefined method `jid=' for #<WhateverWorker>`` in https://github.com/3scale/porta. Our issue had nothing to do with file name and class name mismatch though. Rather, it was because we were migrating the worker definition from Sidekiq-based to Active Job (with Sidekiq adapter). It turns out that, at the exact moment we were deploying the new code, a few jobs got concurrently enqueued based on the old code, and processed right after, based on the new code.

Make sure that you never get producers and consumers running simultaneously based on different versions of your code. (Actually a quite obvious advice.) If needed, define a the new class that inherits from `ApplicationJob`, make sure all clients use only this new class, wait until there's no job in the queue that has been generated based on the old code (nor scheduled, nor expected to be retried), and only then remove the old code.
