### ISSUE TITLE
The same email is sent and received multiple times even though Sidekiq job failed

### ISSUE THREAD

**Issue by monfresh** [mperham/sidekiq#3613]
Ruby version:
Sidekiq: 5.0.4

Please include your initializer and any error message with the full backtrace.
**initializer**:
```ruby
require 'encrypted_sidekiq_redis'
require 'sidekiq_logger_formatter'

Sidekiq::Logging.logger.level = Logger::WARN
Sidekiq::Logging.logger.formatter = SidekiqLoggerFormatter.new

redis_connection = proc do
  EncryptedSidekiqRedis.new(url: Figaro.env.redis_url)
end

size = (Sidekiq.server? ? (Sidekiq.options[:concurrency] + 2) : 5)

Sidekiq.configure_server do |config|
  config.redis = ConnectionPool.new(size: size, &redis_connection)

  # NOTE: Sidekiq does not run middleware in tests by default. Make sure to also add
  # middleware to spec/rails_helper.rb to run in tests as well
  config.server_middleware do |chain|
    chain.add WorkerHealthChecker::Middleware
  end
end

Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(size: size, &redis_connection)
end
```
**backtrace**:
```
D, [2017-09-22T18:18:19.071519 #78077] DEBUG -- : Failure! Retry 0 in 38 seconds
I, [2017-09-22T18:18:19.175996 #78077]  INFO -- : fail: 1.521 sec
W, [2017-09-22T18:18:19.176805 #78077]  WARN -- : {"context"=>"Job raised exception", "job"=>{"class"=>"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper", "wrapped"=>"ActionMailer::DeliveryJob", "queue"=>"mailers", "args"=>[{"job_class"=>"ActionMailer::DeliveryJob", "job_id"=>"40e53851-2611-47cf-975c-8727ba802e40", "provider_job_id"=>nil, "queue_name"=>"mailers", "priority"=>nil, "arguments"=>"[redacted]", "executions"=>0, "locale"=>"en"}], "retry"=>true, "jid"=>"f1f721a614654a6ab15ac8e7", "created_at"=>1506118697.450603, "enqueued_at"=>1506118697.4507499, "error_message"=>"A copy of WorkerHealthChecker::Middleware has been removed from the module tree but is still active!", "error_class"=>"ArgumentError", "failed_at"=>1506118699.0714629, "retry_count"=>0}, "jobstr"=>"[redacted]"}
W, [2017-09-22T18:18:19.177149 #78077]  WARN -- : ArgumentError: A copy of WorkerHealthChecker::Middleware has been removed from the module tree but is still active!
W, [2017-09-22T18:18:19.177469 #78077]  WARN -- : /Users/moncefbelyamani/.gem/ruby/2.3.5/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:495:in `load_missing_constant'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:202:in `const_missing'
/Users/moncefbelyamani/projects/18f/identity/app/services/worker_health_checker.rb:14:in `call'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:169:in `block in process'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:141:in `block (6 levels) in dispatch'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/job_retry.rb:97:in `local'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:140:in `block (5 levels) in dispatch'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/rails.rb:42:in `block in call'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/activesupport-5.1.4/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/activesupport-5.1.4/lib/active_support/reloader.rb:68:in `block in wrap'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/activesupport-5.1.4/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/activesupport-5.1.4/lib/active_support/reloader.rb:67:in `wrap'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/rails.rb:41:in `call'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:136:in `block (4 levels) in dispatch'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:215:in `stats'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:131:in `block (3 levels) in dispatch'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/job_logger.rb:7:in `call'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:130:in `block (2 levels) in dispatch'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/job_retry.rb:72:in `global'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:129:in `block in dispatch'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/logging.rb:44:in `with_context'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/logging.rb:38:in `with_job_hash_context'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:128:in `dispatch'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:168:in `process'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:85:in `process_one'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:73:in `run'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/util.rb:16:in `watchdog'
/Users/moncefbelyamani/.gem/ruby/2.3.5/gems/sidekiq-5.0.4/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

In our Sidekiq initializer above, we are calling the `WorkerHealthChecker` module which lives in a path that Rails autoloads.

This results in the error above when triggering a background job (such as sending an email), then making a change to a file that Rails reloads automatically, then sending another email.

The strange thing is that even though Sidekiq considers this a failed job, the email does get sent successfully. The end result is that I keep getting the same email over and over because Sidekiq thinks the job has failed and so it keeps retrying. In production, we have had a few reports of people getting the same message sent to their phone via SMS, and I'm suspecting it's due to this issue.

We can fix this by moving the `WorkerHealthChecker` module from `app/services` to `lib`, which isn't in Rails autoload paths, but I'm curious as to why emails/SMS are successfully sent if the Sidekiq job failed.

Thoughts?

**Comment by mperham** [comment]
It’s happening because the error is raised after the email/sms is sent at the end of the job when rails is trying to cleanup and unload the code. Don’t auto load middleware. Middleware is effectively a global variable and can’t be reloaded.

**Comment by ACPK** [comment]
@mperham - So what's the fix?

**Comment by mperham** [comment]
Move it to /lib, require it in the initializer. If that doesn't work, let me know.

**Comment by monfresh** [comment]
It works for me. I had identified the issue and fix before, but wasn't clear as to the timing of the events. Thanks for the explanation.
