### ISSUE TITLE
Redis Connection Timed out 

### ISSUE THREAD

**Issue by rajcybage** [mperham/sidekiq#3669]
Hi Team,

We got time out

````
Error message
Redis::TimeoutError: Connection timed out

Sample stack trace (show Rails)
…by/2.2.0/gems/redis-3.3.3/lib/redis/connection/
ruby.rb:  90:in `rescue in _read_from_socket'
…by/2.2.0/gems/redis-3.3.3/lib/redis/connection/
ruby.rb:  83:in `_read_from_socket'
…by/2.2.0/gems/redis-3.3.3/lib/redis/connection/
ruby.rb:  75:in `gets'
…by/2.2.0/gems/redis-3.3.3/lib/redis/connection/
ruby.rb: 380:in `read'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 262:in `block in read'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 250:in `io'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 261:in `read'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 120:in `block in call'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 231:in `block (2 levels) in process'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 367:in `ensure_connected'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 221:in `block in process'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 306:in `logging'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 220:in `process'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 120:in `call'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 102:in `block in connect'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 293:in `with_reconnect'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 100:in `connect'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 364:in `ensure_connected'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 221:in `block in process'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 306:in `logging'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 220:in `process'
…bundle/ruby/2.2.0/gems/redis-3.3.3/lib/redis/
client.rb: 120:in `call'
…vendor/bundle/ruby/2.2.0/gems/redis-3.3.3/lib/
redis.rb:2399:in `block in _eval'
…vendor/bundle/ruby/2.2.0/gems/redis-3.3.3/lib/
redis.rb:  58:in `block in synchronize'
       /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/
monitor.rb: 211:in `mon_synchronize'
…vendor/bundle/ruby/2.2.0/gems/redis-3.3.3/lib/
redis.rb:  58:in `synchronize'
…vendor/bundle/ruby/2.2.0/gems/redis-3.3.3/lib/
redis.rb:2398:in `_eval'
…vendor/bundle/ruby/2.2.0/gems/redis-3.3.3/lib/
redis.rb:2450:in `evalsha'
….0/gems/sidekiq-ent-1.5.1/lib/sidekiq-ent/
scripting.rb:  23:in `block in call'
….2.0/gems/connection_pool-2.2.1/lib/
connection_pool.rb:  64:in `block (2 levels) in with'
….2.0/gems/connection_pool-2.2.1/lib/
connection_pool.rb:  63:in `handle_interrupt'
….2.0/gems/connection_pool-2.2.1/lib/
connection_pool.rb:  63:in `block in with'
….2.0/gems/connection_pool-2.2.1/lib/
connection_pool.rb:  60:in `handle_interrupt'
….2.0/gems/connection_pool-2.2.1/lib/
connection_pool.rb:  60:in `with'
….0/gems/sidekiq-ent-1.5.1/lib/sidekiq-ent/
scripting.rb:  22:in `call'
…2.2.0/gems/sidekiq-ent-1.5.1/lib/sidekiq-ent/
senate.rb: 141:in `update_leader'
…2.2.0/gems/sidekiq-ent-1.5.1/lib/sidekiq-ent/
senate.rb: 123:in `election'
…2.2.0/gems/sidekiq-ent-1.5.1/lib/sidekiq-ent/
senate.rb: 107:in `cycle'
…ndle/ruby/2.2.0/gems/sidekiq-4.2.4/lib/sidekiq/
util.rb:  17:in `watchdog'
…ndle/ruby/2.2.0/gems/sidekiq-4.2.4/lib/sidekiq/
util.rb:  25:in `block in safe_thread'
`````

Ruby version: 2.2.6
Sidekiq / Pro / Enterprise version(s): Enterprise 1.5.1

Please include your initializer and any error message with the full backtrace.

Are you using an old version? No
Have you checked the changelog to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md

**Comment by mperham** [comment]
That means Redis or the network is too slow, one of them is having problems.  There's nothing more I can tell from the backtrace.

**Comment by rajcybage** [comment]
YEs Mike you are right It was Redis to go Issue
