### ISSUE TITLE
0 busy workers with full queue after redis outage

### ISSUE THREAD

**Issue by MarkyMarkMcDonald** [mperham/sidekiq#3690]
We're having an issue where 0 threads out of 4 are busy for most workers after a redis outage. I noticed https://github.com/mperham/sidekiq/issues/3684 exists, this may be a duplicate issue - hopefully I can add details.
To consistently reproduce, I spun up 5 workers for 5 different queues and ran `redis-cli debug sleep 61`. The logs show sidekiq failing to connect, then reconnecting, but not picking up jobs again. 
We've worked around this by rebooting sidekiq workers when paged by our alerts, but I'd rather it reconnect successfully and not have to be woken up early in the morning. 

Ruby version: ruby 2.4.2p198
Sidekiq / Pro / Enterprise version(s): 
sidekiq (5.0.4)
sidekiq-ent (1.6.0)
sidekiq-pro (3.5.1)

Please include your initializer and any error message with the full backtrace.
Here's a stacktrace after our redis instances goes does for a bit (I reproduced this with `redis-cli debug sleep 61`).
```
[#88798]  WARN -- : [] TID-ovy7jsbb0 Redis::TimeoutError: Connection timed out
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/connection/hiredis.rb:58:in `rescue in read'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/connection/hiredis.rb:54:in `read'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:262:in `block in read'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:250:in `io'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:261:in `read'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:120:in `block in call'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:231:in `block (2 levels) in process'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:367:in `ensure_connected'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:221:in `block in process'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:306:in `logging'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:220:in `process'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:120:in `call'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis.rb:752:in `block in set'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis.rb:750:in `set'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sidekiq-pro-3.5.1/lib/sidekiq/pro/super_fetch.rb:60:in `block in orphan_check?'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq.rb:95:in `block in redis'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq.rb:92:in `redis'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sidekiq-pro-3.5.1/lib/sidekiq/pro/super_fetch.rb:59:in `orphan_check?'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sidekiq-pro-3.5.1/lib/sidekiq/pro/super_fetch.rb:20:in `initialize'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:40:in `new'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:40:in `initialize'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/manager.rb:95:in `new'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/manager.rb:95:in `block in processor_died'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/manager.rb:92:in `synchronize'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/manager.rb:92:in `processor_died'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:79:in `rescue in run'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:71:in `run'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/util.rb:16:in `watchdog'
[#88976]  WARN -- : [] TID-ox4b7y3l8 /Users/mark.mcdonald/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.4/lib/sidekiq/util.rb:25:in `block in safe_thread'
[#88976]  INFO -- : [] TID-ox4b7y3l8 [Rollbar] Scheduling payload
[#88976]  INFO -- : [] TID-ox4b7y2r8 [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=1f44ff7a-514b-446f-99fc-e02e8b49c6cb (only available if report was successful)
[#88976] ERROR -- : [] TID-ox4b7y46w heartbeat: Connection timed out
[#88728]  INFO -- : [] TID-owa6snl8s [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=3b976495-6d5e-45b6-a993-e44e4491f37b (only available if report was successful)
[#88728]  INFO -- : [] TID-owa6f50u8 [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=3434897e-b0cf-4a01-9c50-b182cf53eee8 (only available if report was successful)
[#88774]  INFO -- : [] TID-owjbigc30 [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=18340845-d900-4693-bb1e-3e31bdb11cea (only available if report was successful)
[#88728]  WARN -- : [] TID-owa6xaldg Unable to take periodic lock!
[#88798] ERROR -- : [] TID-ovy7b8kzk heartbeat: Error connecting to Redis on 127.0.0.1:6379 (Redis::TimeoutError)
[#88798]  INFO -- : [] TID-ovy7k31c8 [ReliablePush] Connectivity restored, draining local queue
[#88798]  INFO -- : [] TID-ovy7k31c8 [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=c671f635-acd0-47ef-ab8e-9d5ef8946ce3 (only available if report was successful)
[#88798]  WARN -- : [] TID-ovy7jscnc [ReliablePush] Enqueueing job locally due to Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Redis::TimeoutError)
[#88798]  INFO -- : [] TID-ovy7jscnc [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=01dc8d89-d202-49b4-a275-a1807d6e46cb (only available if report was successful)
[#88976]  INFO -- : [] TID-ox4b7y3l8 [ReliablePush] Connectivity restored, draining local queue
```

Are you using an old version? We're using 5.0.4, I don't see anything in the changelog related to redis reconnections.
Have you checked the changelog to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md

**Comment by mperham** [comment]
Yep, the fix is in Pro 3.5.4, upgrade.

https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md#354
