### ISSUE TITLE
Sidekiq Pro 3.6.0 breaks when using dogstatsd

### ISSUE THREAD

**Issue by sj26** [mperham/sidekiq#3699]
Ruby 2.4.2, Sidekiq Pro 3.6.0, [dogstatsd-ruby](https://github.com/DataDog/dogstatsd-ruby) 3.1.0

Switching to the suggested new metrics gear no longer works with a Datadog statsd instance:

```ruby
Sidekiq.statsd = ->{ Datadog::Statsd.new }
```

```
NoMethodError:
  undefined method `fetch' for 1:Integer
/usr/local/bundle/gems/dogstatsd-ruby-3.1.0/lib/datadog/statsd.rb:129:in `increment'
/usr/local/bundle/gems/sidekiq-pro-3.6.0/lib/sidekiq/pro/metrics.rb:44:in `block in increment'
/usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
/usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
/usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
/usr/local/bundle/gems/sidekiq-pro-3.6.0/lib/sidekiq/pro/metrics.rb:44:in `increment'
/usr/local/bundle/gems/sidekiq-pro-3.6.0/lib/sidekiq/batch.rb:211:in `jobs'
./app/workers/my_fancy_worker.rb:16:in `perform'
```

This seems to be because of the new Metrics wrapper class which replicates the statsd-ruby methods signatures including optional arguments which the two gems treat slightly different, but which sidekiq never uses:

```ruby
      def increment(name, rate=1)
        @statsd.with{|c| c.increment(name, rate) } if @statsd
      end
```

It would probably be fixed by passing through a splat instead:

```ruby
      def increment(*args)
        @statsd.with{|c| c.increment(*args) } if @statsd
      end
```

I've also submitted a patch upstream to dogstatsd-ruby to accept a statsd-ruby style sample_rate argument:

https://github.com/DataDog/dogstatsd-ruby/pull/67

**Comment by mperham** [comment]
Yeah, I need to add support for it.  Statsd and Dogstatsd are just different enough to be a huge PITA.

**Comment by mperham** [comment]
3.6.1 is now out.

**Comment by sj26** [comment]
🙇
