### ISSUE TITLE
Connection lost (ECONNRESET) directly after start

### ISSUE THREAD

**Issue by rpbaptist** [mperham/sidekiq#3712]
Ruby version: 2.4.2
Sidekiq version: 5.0.5

Please include your initializer and any error message with the full backtrace.

Using `capistrano-sidekiq`

`cap production sidekiq:start`

Are you using an old version? No

Sidekiq is working on my staging environment, but not on production. I can connect through redis-cli on the port and connection which I defined in my configuration.

I am mostly submitting this because I am looking for a way to start Sidekiq from the console and debug it there to get to the root of the problem. Any pointers are welcome.

Full log with stack trace below:

```
2018-01-04T11:05:29.279Z 6107 TID-grucadaac INFO: Booting Sidekiq 5.0.5 with redis options {:url=>"redis://example.com:6379/0", :network_timeout=>5, :id=>"Sidekiq-server-PID-6107"}
2018-01-04T11:05:30.257Z 6107 TID-grucadaac INFO: Running in ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
2018-01-04T11:05:30.258Z 6107 TID-grucadaac INFO: See LICENSE and the LGPL-3.0 for licensing details.
2018-01-04T11:05:30.258Z 6107 TID-grucadaac INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
Connection lost (ECONNRESET)
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:255:in `rescue in io'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:248:in `io'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:259:in `read'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:118:in `block in call'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:229:in `block (2 levels) in process'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:366:in `ensure_connected'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:219:in `block in process'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:304:in `logging'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:218:in `process'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/appsignal-2.4.3/lib/appsignal/hooks/redis.rb:23:in `block in process'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/appsignal-2.4.3/lib/appsignal.rb:567:in `instrument'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/appsignal-2.4.3/lib/appsignal/hooks/redis.rb:22:in `process'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:118:in `call'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:102:in `block in connect'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:291:in `with_reconnect'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:98:in `connect'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:363:in `ensure_connected'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:219:in `block in process'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:304:in `logging'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:218:in `process'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/appsignal-2.4.3/lib/appsignal/hooks/redis.rb:23:in `block in process'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/appsignal-2.4.3/lib/appsignal.rb:567:in `instrument'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/appsignal-2.4.3/lib/appsignal/hooks/redis.rb:22:in `process'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:118:in `call'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:274:in `block in info'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
/home/ubuntu/.rbenv/versions/2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:273:in `info'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq.rb:113:in `block in redis_info'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq.rb:95:in `block in redis'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq.rb:92:in `redis'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq.rb:106:in `redis_info'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/cli.rb:81:in `run'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/bin/sidekiq:12:in `<top (required)>'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/bin/sidekiq:23:in `load'
/home/ubuntu/deploy/backoffice/shared/bundle/ruby/2.4.0/bin/sidekiq:23:in `<top (required)>'
/home/ubuntu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/home/ubuntu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/ubuntu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/home/ubuntu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/home/ubuntu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/ubuntu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/ubuntu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/ubuntu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/home/ubuntu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/ubuntu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/home/ubuntu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/home/ubuntu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/ubuntu/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/home/ubuntu/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/home/ubuntu/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
```

**Comment by rpbaptist** [comment]
Well, this was definitely a AWS Elasticache redis issue. I changed settings in the parameter group and it got stuck on "Applying". I figured it out because I couldn't use `select 1` or any other database in the CLI without getting the same error.
