### ISSUE TITLE
ERROR: heartbeat: MOVED 15458 10.0.1.59:6379

### ISSUE THREAD

**Issue by fernandomcunha** [mperham/sidekiq#3728]
Ruby version: 2.1.3
Sidekiq / Pro / Enterprise version(s): Enterprise

Please include your initializer and any error message with the full backtrace.

```
uri = Rails.env.production? ? ENV['REDISTOGO_URL'] : 'redis://localhost:6379'

Sidekiq.configure_server do |config|
 config.redis = { url: uri, size: 9 }
end

Sidekiq.configure_client do |config|
 config.redis = { url: uri, size: 1 }
end
```

```
ERROR: heartbeat: MOVED 15458 10.0.1.59:6379
ERROR: heartbeat: MOVED 15458 10.0.1.59:6379
ERROR: heartbeat: MOVED 15458 10.0.1.59:6379
ERROR: heartbeat: MOVED 15458 10.0.1.59:6379
ERROR: MOVED 14815 10.0.1.59:6379
ERROR: /pathto/bundle/ruby/2.1.0/gems/redis-3.3.5/lib/redis/client.rb:121:in `call'
ERROR: /pathto/bundle/ruby/2.1.0/gems/redis-3.3.5/lib/redis.rb:1799:in `block in zrangebyscore'
ERROR: /pathto/bundle/ruby/2.1.0/gems/redis-3.3.5/lib/redis.rb:58:in `block in synchronize'
ERROR: /pathto/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
ERROR: /pathto/bundle/ruby/2.1.0/gems/redis-3.3.5/lib/redis.rb:58:in `synchronize'
ERROR: /pathto/bundle/ruby/2.1.0/gems/redis-3.3.5/lib/redis.rb:1798:in `zrangebyscore'
ERROR: /pathto/bundle/ruby/2.1.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:20:in `block (2 levels) in enqueue_jobs'
ERROR: /pathto/bundle/ruby/2.1.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:15:in `each'
ERROR: /pathto/bundle/ruby/2.1.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:15:in `block in enqueue_jobs'
ERROR: /pathto/bundle/ruby/2.1.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:95:in `block in redis'
ERROR: /pathto/bundle/ruby/2.1.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
ERROR: /pathto/bundle/ruby/2.1.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
ERROR: /pathto/bundle/ruby/2.1.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
ERROR: /pathto/bundle/ruby/2.1.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
ERROR: /pathto/bundle/ruby/2.1.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
ERROR: /pathto/bundle/ruby/2.1.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:92:in `redis'
ERROR: /pathto/bundle/ruby/2.1.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:14:in `enqueue_jobs'
ERROR: /pathto/bundle/ruby/2.1.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:77:in `enqueue'
ERROR: /pathto/bundle/ruby/2.1.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:68:in `block in start'
ERROR: /pathto/bundle/ruby/2.1.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
ERROR: /pathto/bundle/ruby/2.1.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

Openning an issue cause I`m getting this error only on production mode. There I have 2 servers running same app and a load balancer. I use `capistrano-sidekiq` to deploy the app and here is my config file:

```
set :sidekiq_role, [:sidekiq_small, :sidekiq_big]
set :sidekiq_small_processes, 1
set :sidekiq_big_processes, 4
server "server_address", user: "user", roles: %w{app db web sidekiq_small}
server "server_address", user: "user", roles: %w{app db web sidekiq_big}
```

Am I doing something wrong ?

Regards

**Comment by mperham** [comment]
That's a Redis Cluster redirect.  Don't use Redis Cluster as Sidekiq is not designed to work with it.

**Comment by fernandomcunha** [comment]
@mperham Thanks for reply, I have an AWS ElastiCache with REDIS, so I have to change some config there ?

**Comment by mperham** [comment]
I have no idea, I don't know much about Elasticache.  Have you tried restarting Sidekiq?

**Comment by fernandomcunha** [comment]
On AWS ElastCache when you create a Redis there is an option called `Cluster Mode enabled` that I disabled and restart sidekiq so I'm not getting the error anymore, but when I tried to access the `/sidekiq` route it give me another error:

```
Redis::CommandError (CROSSSLOT Keys in request don't hash to the same slot)
```

I think I might be missing some sidekiq or rails config or am I wrong ?

**Comment by mperham** [comment]
Restart unicorn/puma too.

**Comment by fernandomcunha** [comment]
Now I'm getting:

```
SocketError (getaddrinfo: Name or service not known)
```

**Comment by mperham** [comment]
If I were you, I would completely remove your Sidekiq initializer.  It is only going to break things.  Sidekiq will auto-size the pool for you.

You are currently using REDISTOGO_URL as your URL in production.  Set REDIS_PROVIDER=REDISTOGO_URL and Sidekiq will automatically pick up the new URL.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Using-Redis#using-an-env-variable
