### ISSUE TITLE
I get max number of client reached error as soon I start the sidekiq worker on Heroku

### ISSUE THREAD

**Issue by abhishek77in** [mperham/sidekiq#3762]
Ruby version: 2.3.0
Sidekiq / Pro / Enterprise version(s): Sidekiq-5.1.1

Please include your initializer and any error message with the full backtrace.

2018-02-19T12:52:21.542398+00:00 app[api]: Scaled to console@0:Free rake@0:Free web@1:Free worker@1:Free by user *****
2018-02-19T12:52:27.258888+00:00 heroku[worker.1]: Starting process with command `bundle exec sidekiq -e production`
2018-02-19T12:52:27.987942+00:00 heroku[worker.1]: State changed from starting to up
2018-02-19T12:52:33.934427+00:00 app[worker.1]: 4 TID-ajizw INFO: Running in ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
2018-02-19T12:52:33.934450+00:00 app[worker.1]: 4 TID-ajizw INFO: See LICENSE and the LGPL-3.0 for licensing details.
2018-02-19T12:52:33.934487+00:00 app[worker.1]: 4 TID-ajizw INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2018-02-19T12:52:33.934790+00:00 app[worker.1]: 4 TID-ajizw INFO: Booting Sidekiq 5.1.1 with redis options {:id=>"Sidekiq-server-PID-4", :url=>"redis://redistogo:REDACTED@soldierfish.redistogo.com:11383/"}
2018-02-19T12:52:33.945085+00:00 app[worker.1]: 4 TID-ajizw INFO: Starting processing, hit Ctrl-C to stop
2018-02-19T12:52:34.000516+00:00 app[worker.1]: 4 TID-10fun0 ERROR: Error fetching job: ERR max number of clients reached
2018-02-19T12:52:34.004795+00:00 app[worker.1]: 4 TID-10fun0 WARN: Redis::CommandError: ERR max number of clients reached
2018-02-19T12:52:34.011329+00:00 app[worker.1]: 4 TID-10fun0 WARN: /app/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:119:in `call'
2018-02-19T12:52:34.011332+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:100:in `block in connect'
2018-02-19T12:52:34.011333+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:291:in `with_reconnect'
2018-02-19T12:52:34.011335+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:98:in `connect'
2018-02-19T12:52:34.011337+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:274:in `with_socket_timeout'
2018-02-19T12:52:34.011338+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:206:in `call_with_timeout'
2018-02-19T12:52:34.011340+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:1162:in `block in _bpop'
2018-02-19T12:52:34.011341+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
2018-02-19T12:52:34.011343+00:00 app[worker.1]: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
2018-02-19T12:52:34.011344+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
2018-02-19T12:52:34.011346+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:1159:in `_bpop'
2018-02-19T12:52:34.011347+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:1204:in `brpop'
2018-02-19T12:52:34.011349+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.1.1/lib/sidekiq/fetch.rb:36:in `block in retrieve_work'
2018-02-19T12:52:34.011350+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.1.1/lib/sidekiq.rb:96:in `block in redis'
2018-02-19T12:52:34.011352+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
2018-02-19T12:52:34.011354+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
2018-02-19T12:52:34.011356+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
2018-02-19T12:52:34.011357+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
2018-02-19T12:52:34.011359+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
2018-02-19T12:52:34.011360+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.1.1/lib/sidekiq.rb:93:in `redis'
2018-02-19T12:52:34.011362+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.1.1/lib/sidekiq/fetch.rb:36:in `retrieve_work'
2018-02-19T12:52:34.011363+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:91:in `get_one'
2018-02-19T12:52:34.011365+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:101:in `fetch'
2018-02-19T12:52:34.011366+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:84:in `process_one'
2018-02-19T12:52:34.011368+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:73:in `run'
2018-02-19T12:52:34.011370+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.1.1/lib/sidekiq/util.rb:16:in `watchdog'
2018-02-19T12:52:34.011372+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.1.1/lib/sidekiq/util.rb:25:in `block in safe_thread'
2018-02-19T12:52:34.012552+00:00 app[worker.1]: 4 TID-10fvko ERROR: Error fetching job: ERR max number of clients reached
2018-02-19T12:52:34.014801+00:00 app[worker.1]: 4 TID-10fu8w ERROR: Error fetching job: ERR max number of clients reached
2018-02-19T12:52:34.016882+00:00 app[worker.1]: 4 TID-10ffd0 ERROR: Error fetching job: ERR max number of clients reached
2018-02-19T12:52:34.016942+00:00 app[worker.1]: 4 TID-10fxf0 ERROR: Error fetching job: ERR max number of clients reached
2018-02-19T12:52:34.017005+00:00 app[worker.1]: 4 TID-10fvwk ERROR: Error fetching job: ERR max number of clients reached

Are you using an old version? - No
Have you checked the changelogs to see if your issue has been fixed in a later version? - Checked, I don't think change changelogs address my issue.

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
http://manuelvanrijn.nl/sidekiq-heroku-redis-calc/
