### ISSUE TITLE
Requiring and Configuring Service from /lib

### ISSUE THREAD

**Issue by spinlock99** [mperham/sidekiq#3766]
Ruby version: 2.3.1
Sidekiq: 5.0.5

I'm working on a Rails/Sidekiq app and I'm trying to move the configuration out of the source code and into environment variables stored in /etc/environment on each server.

One problem I have is making sure that each server has all of the environment variables that it should. So, I've started creating initializers like this:

```
# config/initializers/tracking.rb

Tracking.configure do |config|
  config.slack_application_channel = ENV['SLACK_APPLICATION_CHANNEL']
end
```
and then I'll have the Tracking Service validate the configuration:

```
# lib/tracking.rb

require 'net/http'
require 'ostruct'
require 'uri'

module Tracking
  class << self
    def configure
      yield @config = OpenStruct.new
      throw 'Tracking Error: Invalid Configuration' unless configured?
    end

    def slack_application_channel(text:)
      uri = URI(@config.slack_application_channel)
      payload = {"text": text}.to_json

      connection = Net::HTTP.new(uri.host, uri.port)
      connection.use_ssl = true
      connection.verify_mode = OpenSSL::SSL::VERIFY_NONE

      request = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
      request.body = payload

      response = connection.start do |http|
        http.request(request)
      end
    end

    private

    def configured?
      @config.slack_application_channel
    end
  end
end
```
I'll then run the Tracking Service from a Sidekiq worker (so it doesn't block a web thread in Rails):
```

# app/workers/tracking_worker.rb

require Rails.root.join('lib', 'tracking.rb')

class TrackingWorker
  include Sidekiq::Worker

  def perform(text)
    Tracking.slack_application_channel(text: text)
  end
end
```

That works well and an error is thrown if SLACK_APPLICATION_CHANNEL isn't configured on a server.

The problem is that, in development, Sidekiq will reload itself when a worker changes but it doesn't reload the initializer that configures the Tracking Service.

Does anyone know how to get Sidekiq it re-run the initializers in Sidekiq?

Also, any comments/ideas on this approach would be greatly appreciated. I'm not a huge fan of storing all environment variables in /etc/environment and I'd like to move that to a single s3 bucket. Any advice on that change would be greatly appreciated.

**Comment by spinlock99** [comment]
Here is the error I get in the logs:

```
2018-02-20T20:28:48.012Z 82536 TID-oxtsu4j1c TrackingWorker JID-19076d5574f1fbc2877d191a INFO: start
2018-02-20T20:28:50.028Z 82536 TID-oxtsu4j1c TrackingWorker JID-19076d5574f1fbc2877d191a INFO: fail: 2.016 sec
2018-02-20T20:28:50.028Z 82536 TID-oxtsu4j1c WARN: {"context":"Job raised exception","job":{"class":"TrackingWorker","args":["Contract: 37 -- application_submitted"],"retry":true,"queue":"default","jid":"19076d5574f1fbc2877d191a","created_at":1519155272.9442718,"enqueued_at":1519158528.012306,"error_message":"undefined method `slack_application_channel' for nil:NilClass","error_class":"NoMethodError","failed_at":1519155273.0276768,"retry_count":5,"retried_at":1519157430.8113549},"jobstr":"{\"class\":\"TrackingWorker\",\"args\":[\"Contract: 37 -- application_submitted\"],\"retry\":true,\"queue\":\"default\",\"jid\":\"19076d5574f1fbc2877d191a\",\"created_at\":1519155272.9442718,\"enqueued_at\":1519158528.012306,\"error_message\":\"undefined method `slack_application_channel' for nil:NilClass\",\"error_class\":\"NoMethodError\",\"failed_at\":1519155273.0276768,\"retry_count\":5,\"retried_at\":1519157430.8113549}"}
2018-02-20T20:28:50.028Z 82536 TID-oxtsu4j1c WARN: NoMethodError: undefined method `slack_application_channel' for nil:NilClass
2018-02-20T20:28:50.029Z 82536 TID-oxtsu4j1c WARN: /Users/spinlock/src/lendstreet.com/lib/tracking.rb:13:in `slack_application_channel'
/Users/spinlock/src/lendstreet.com/app/workers/tracking_worker.rb:7:in `perform'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:188:in `execute_job'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:169:in `block in process'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:141:in `block (6 levels) in dispatch'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/job_retry.rb:97:in `local'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:140:in `block (5 levels) in dispatch'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/rails.rb:42:in `block in call'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/activesupport-5.1.4/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/activesupport-5.1.4/lib/active_support/reloader.rb:68:in `block in wrap'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/activesupport-5.1.4/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/activesupport-5.1.4/lib/active_support/reloader.rb:67:in `wrap'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/rails.rb:41:in `call'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:136:in `block (4 levels) in dispatch'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:204:in `stats'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:131:in `block (3 levels) in dispatch'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/job_logger.rb:7:in `call'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:130:in `block (2 levels) in dispatch'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/job_retry.rb:72:in `global'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:129:in `block in dispatch'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/logging.rb:44:in `with_context'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/logging.rb:38:in `with_job_hash_context'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:128:in `dispatch'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:168:in `process'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:85:in `process_one'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:73:in `run'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:16:in `watchdog'
/Users/spinlock/.rvm/gems/ruby-2.3.1/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

Note: stopping and restarting Sidekiq does let the job go through the next time.

**Comment by mperham** [comment]
Sidekiq has nothing to do with initializers.  Rails runs the initializers when it boots; it never reloads them.  Process restart is your only solution afaik.

**Comment by spinlock99** [comment]
OK. Thanks for the response.
