### ISSUE TITLE
Upgrade from Pro 1 to 2 breaks because of Celluloid

### ISSUE THREAD

**Issue by florrain** [mperham/sidekiq#3798]
Ruby version:
Latest Sidekiq Pro 2 (2.1.5), Ruby 2.1.10

I'm trying to upgrade from 1.9.2 to 2.1.5 and seeing this error when starting Sidekiq. I'll precise the application doesn't need Celluloid outside of Sidekiq.
```
> $ sidekiq -c 1 -e development -q default                                                                           
uninitialized constant Celluloid::EventedMailbox
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/celluloid-io-0.15.0/lib/celluloid/io/mailbox.rb:4:in `<module:IO>'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/celluloid-io-0.15.0/lib/celluloid/io/mailbox.rb:2:in `<module:Celluloid>'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/celluloid-io-0.15.0/lib/celluloid/io/mailbox.rb:1:in `<top (required)>'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/celluloid-io-0.15.0/lib/celluloid/io.rb:5:in `<top (required)>'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/listen-2.7.4/lib/listen/adapter/tcp.rb:1:in `<top (required)>'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/listen-2.7.4/lib/listen/adapter.rb:6:in `<top (required)>'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/listen-2.7.4/lib/listen/listener.rb:2:in `<top (required)>'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/listen-2.7.4/lib/listen.rb:2:in `<top (required)>'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/guard-2.6.0/lib/guard/setuper.rb:2:in `<top (required)>'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/guard-2.6.0/lib/guard.rb:13:in `<top (required)>'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/guard-haml-1.1.2/lib/guard/haml.rb:1:in `<top (required)>'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/bundler-1.16.1/lib/bundler/runtime.rb:95:in `require'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/bundler-1.16.1/lib/bundler/runtime.rb:95:in `rescue in block in require'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/bundler-1.16.1/lib/bundler/runtime.rb:72:in `block in require'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/Users/flo/dev/apps/my_app/config/application.rb:14:in `<top (required)>'
/Users/flo/dev/apps/my_app/config/environment.rb:2:in `require'
/Users/flo/dev/apps/my_app/config/environment.rb:2:in `<top (required)>'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/sidekiq-3.5.4/lib/sidekiq/cli.rb:237:in `require'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/sidekiq-3.5.4/lib/sidekiq/cli.rb:237:in `boot_system'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/sidekiq-3.5.4/lib/sidekiq/cli.rb:50:in `run'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/gems/sidekiq-3.5.4/bin/sidekiq:13:in `<top (required)>'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/bin/sidekiq:22:in `load'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/bin/sidekiq:22:in `<main>'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/bin/ruby_executable_hooks:15:in `eval'
/Users/flo/.rvm/gems/ruby-2.1.10@my_gemset/bin/ruby_executable_hooks:15:in `<main>'
```

The Gemfile.lock mentions Celluloid 0.17.0, should I use an older version? They seem to have deprecated some functionalities recently. I don't want to make assumptions here on the appropriate version to use or any specific Celluloid configuration, so I would appreciate your feedback here.
```
    celluloid (0.17.3)
      celluloid-essentials
      celluloid-extras
      celluloid-fsm
      celluloid-pool
      celluloid-supervision
      timers (>= 4.1.1)
    celluloid-essentials (0.20.5)
      timers (>= 4.1.1)
    celluloid-extras (0.20.5)
      timers (>= 4.1.1)
    celluloid-fsm (0.20.5)
      timers (>= 4.1.1)
    celluloid-io (0.15.0)
      celluloid (>= 0.15.0)
      nio4r (>= 0.5.0)
    celluloid-pool (0.20.5)
      timers (>= 4.1.1)
    celluloid-supervision (0.20.6)
      timers (>= 4.1.1)
```

```
    sidekiq (3.5.4)
      celluloid (~> 0.17.2)
      connection_pool (~> 2.2, >= 2.2.0)
      json (~> 1.0)
      redis (~> 3.2, >= 3.2.1)
      redis-namespace (~> 1.5, >= 1.5.2)
```

```
    sidekiq-pro (2.1.5)
      sidekiq (~> 3, >= 3.4.2)
```

Thanks,
Florian Lorrain

**Comment by mperham** [comment]
Haml is requiring celluloid there. Maybe upgrade it too?

**Comment by florrain** [comment]
It was actually `guard` having celluloid as a loose dependency (>= 0.15). We don't need it anymore in our project so I removed it and sidekiq could start. 

![screen shot 2018-03-21 at 10 23 02 pm](https://user-images.githubusercontent.com/2470945/37738265-bc055792-2d56-11e8-865b-077569b749b7.png)
![screen shot 2018-03-21 at 10 23 06 pm](https://user-images.githubusercontent.com/2470945/37738268-bd4d2d96-2d56-11e8-95fa-6898e539cc64.png)


I'll close 🔒 and thanks for the quick support as always Mike.
