### ISSUE TITLE
uninitialized constant Sidekiq::Middleware::Server::ActiveRecordCache in v5.1.2

### ISSUE THREAD

**Issue by alexanderpetkov** [mperham/sidekiq#3809]
Ruby version: 2.4.0
Sidekiq v5.1.2, Sidekiq Pro v4.0.2
Rails v4.2.8

Initializer includes:
```Ruby
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.remove Sidekiq::Middleware::Server::ActiveRecordCache
  end
end
```

And Sidekiq fails to start with:
```
uninitialized constant Sidekiq::Middleware::Server::ActiveRecordCache
/project/config/initializers/sidekiq.rb:16:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/sidekiq-5.1.2/lib/sidekiq.rb:143:in `server_middleware'
/project/config/initializers/sidekiq.rb:10:in `block in <top (required)>'
/usr/local/bundle/gems/sidekiq-5.1.2/lib/sidekiq.rb:73:in `configure_server'
/project/config/initializers/sidekiq.rb:5:in `<top (required)>'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/lib/ruby/2.4.0/tsort.rb:415:in `call'
/usr/local/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.4.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/project/config/environment.rb:8:in `<top (required)>'
/usr/local/bundle/gems/sidekiq-5.1.2/lib/sidekiq/cli.rb:269:in `boot_system'
/usr/local/bundle/gems/sidekiq-5.1.2/lib/sidekiq/cli.rb:53:in `run'
/usr/local/bundle/gems/sidekiq-5.1.2/bin/sidekiq:12:in `<top (required)>'
/usr/local/bundle/bin/sidekiq:17:in `load'
/usr/local/bundle/bin/sidekiq:17:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

Possibly introduced after fixing https://github.com/mperham/sidekiq/issues/3787

**Comment by mperham** [comment]
That’s not a middleware that Sidekiq provides, wrong name.

**Comment by alexanderpetkov** [comment]
Looks like the middleware was deleted between 5.1.1 and 5.1.2 with https://github.com/mperham/sidekiq/pull/3756. Is this expected?

**Comment by mperham** [comment]
As I said, ActiveRecordCache is not the name of any middleware Sidekiq provides.

**Comment by alexanderpetkov** [comment]
Yep, did that. Thanks
