### ISSUE TITLE
Ruby 2.5.1 Cannot load such file -- concurrent/map (LoadError)

### ISSUE THREAD

**Issue by prutya** [mperham/sidekiq#3816]
Ruby 2.5.1, Sidekiq 5.1.3

```
bundle exec sidekiq -r ./app/update_handler.rb

2018-04-05T06:09:50.641Z 43011 TID-oxhqg8roz INFO: Running in ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
2018-04-05T06:09:50.641Z 43011 TID-oxhqg8roz INFO: See LICENSE and the LGPL-3.0 for licensing details.
2018-04-05T06:09:50.641Z 43011 TID-oxhqg8roz INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2018-04-05T06:09:50.641Z 43011 TID-oxhqg8roz INFO: Booting Sidekiq 5.1.3 with redis options {:id=>"Sidekiq-server-PID-43011", :url=>nil}
2018-04-05T06:09:50.643Z 43011 TID-oxhqg8roz INFO: Starting processing, hit Ctrl-C to stop
Traceback (most recent call last):
	12: from /Users/prutya/.rvm/gems/ruby-2.5.1@tg_booking/bin/ruby_executable_hooks:15:in `<main>'
	11: from /Users/prutya/.rvm/gems/ruby-2.5.1@tg_booking/bin/ruby_executable_hooks:15:in `eval'
	10: from /Users/prutya/.rvm/gems/ruby-2.5.1@tg_booking/bin/sidekiq:23:in `<main>'
	 9: from /Users/prutya/.rvm/gems/ruby-2.5.1@tg_booking/bin/sidekiq:23:in `load'
	 8: from /Users/prutya/.rvm/gems/ruby-2.5.1@tg_booking/gems/sidekiq-5.1.3/bin/sidekiq:12:in `<top (required)>'
	 7: from /Users/prutya/.rvm/gems/ruby-2.5.1@tg_booking/gems/sidekiq-5.1.3/lib/sidekiq/cli.rb:100:in `run'
	 6: from /Users/prutya/.rvm/gems/ruby-2.5.1@tg_booking/gems/sidekiq-5.1.3/lib/sidekiq/cli.rb:100:in `require'
	 5: from /Users/prutya/.rvm/gems/ruby-2.5.1@tg_booking/gems/sidekiq-5.1.3/lib/sidekiq/launcher.rb:2:in `<top (required)>'
	 4: from /Users/prutya/.rvm/gems/ruby-2.5.1@tg_booking/gems/sidekiq-5.1.3/lib/sidekiq/launcher.rb:2:in `require'
	 3: from /Users/prutya/.rvm/gems/ruby-2.5.1@tg_booking/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:3:in `<top (required)>'
	 2: from /Users/prutya/.rvm/gems/ruby-2.5.1@tg_booking/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:3:in `require'
	 1: from /Users/prutya/.rvm/gems/ruby-2.5.1@tg_booking/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:7:in `<top (required)>'
/Users/prutya/.rvm/gems/ruby-2.5.1@tg_booking/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:7:in `require': cannot load such file -- concurrent/map (LoadError)
```

Still ok on Ruby 2.5.0 though

```
2018-04-05T06:14:13.949Z 43875 TID-ownb0rsov INFO: Running in ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]
2018-04-05T06:14:13.950Z 43875 TID-ownb0rsov INFO: See LICENSE and the LGPL-3.0 for licensing details.
2018-04-05T06:14:13.950Z 43875 TID-ownb0rsov INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2018-04-05T06:14:13.950Z 43875 TID-ownb0rsov INFO: Booting Sidekiq 5.1.3 with redis options {:id=>"Sidekiq-server-PID-43875", :url=>nil}
2018-04-05T06:14:13.951Z 43875 TID-ownb0rsov INFO: Starting processing, hit Ctrl-C to stop
2018-04-05T06:14:13.983Z 43875 TID-ownbfz17j App::UpdateHandler JID-ea6b24887ca35735480ea5a4 INFO: start
...
```

Please find source code [here](https://github.com/Prutya/booking-bot) if needed

**Comment by mperham** [comment]
Works just fine for me.  Did you uninstall the concurrent-ruby gem somehow?

```
$ bundle exec sidekiq
2018-04-05T16:28:42.330Z 89521 TID-ovcxslpch INFO: Running in ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
2018-04-05T16:28:42.330Z 89521 TID-ovcxslpch INFO: See LICENSE and the LGPL-3.0 for licensing details.
2018-04-05T16:28:42.330Z 89521 TID-ovcxslpch INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2018-04-05T16:28:42.330Z 89521 TID-ovcxslpch INFO: Booting Sidekiq 5.1.3 with redis options {:id=>"Sidekiq-server-PID-89521", :url=>nil}
2018-04-05T16:28:42.332Z 89521 TID-ovcxslpch INFO: Starting processing, hit Ctrl-C to stop
```

**Comment by Prutya** [comment]
No, I did not 🤔

**Comment by Prutya** [comment]
I have just reinstalled ruby 2.5.1, and it seems to be working fine.
Thank you
