### ISSUE TITLE
NoMethodError: undefined method map' for <Redis::Future [:hgetall]

### ISSUE THREAD

**Issue by scottrobertson** [mperham/sidekiq#3821]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s):  5.1.3 / 4.0.2 / 1.7.1

```
15:54:14 sidekiq.1 | 2018-04-09T14:54:14.448Z 18533 TID-ouhkm20jh WARN: NoMethodError: undefined method `map' for <Redis::Future [:hgetall, "b-KAMvR7awGK6Nng-failinfo"]>:Redis::Future
15:54:14 sidekiq.1 | 2018-04-09T14:54:14.448Z 18533 TID-ouhkm20jh WARN: /.rvm/gems/ruby-2.5.1/gems/sidekiq-pro-4.0.2/lib/sidekiq/batch/status.rb:179:in `failure_info'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-pro-4.0.2/lib/sidekiq/batch/status.rb:191:in `data'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-pro-4.0.2/lib/sidekiq/batch/status.rb:198:in `to_json'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq.rb:182:in `generate'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq.rb:182:in `dump_json'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/client.rb:201:in `block in atomic_push'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/client.rb:199:in `map'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/client.rb:199:in `atomic_push'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/client.rb:184:in `block (2 levels) in raw_push'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/redis-4.0.1/lib/redis.rb:2352:in `block in multi'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
15:54:14 sidekiq.1 | /.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/redis-4.0.1/lib/redis.rb:2345:in `multi'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/client.rb:183:in `block in raw_push'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/bundler/gems/connection_pool-4aabf28e75df/lib/connection_pool.rb:73:in `block (2 levels) in with'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/bundler/gems/connection_pool-4aabf28e75df/lib/connection_pool.rb:72:in `handle_interrupt'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/bundler/gems/connection_pool-4aabf28e75df/lib/connection_pool.rb:72:in `block in with'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/bundler/gems/connection_pool-4aabf28e75df/lib/connection_pool.rb:69:in `handle_interrupt'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/bundler/gems/connection_pool-4aabf28e75df/lib/connection_pool.rb:69:in `with'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/client.rb:182:in `raw_push'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-pro-4.0.2/lib/sidekiq/batch/client.rb:41:in `raw_push_with_batch'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-pro-4.0.2/lib/sidekiq/pro/push.rb:41:in `push_initial'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-pro-4.0.2/lib/sidekiq/pro/push.rb:32:in `raw_push_with_backup'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/client.rb:74:in `push'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/worker.rb:143:in `client_push'
15:54:14 sidekiq.1 | /.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/worker.rb:87:in `perform_async'
```

**Comment by scottrobertson** [comment]
We are using Redis 3.x, but i tried 4.x too and it had the same issue

**Comment by mperham** [comment]
From that trace, it looks like you are trying to pass a Sidekiq::Batch::Status to a worker as an argument.  Is this right?  Why do this?  Status objects are a snapshot in time and not meant to be passed around in job arguments.  Pass the BID and create a new Status when that job executes.

**Comment by mperham** [comment]
It would help if you could share your code which is using the batch api.

**Comment by scottrobertson** [comment]
Hey @mperham, thanks for looking into this. Sorry for the slow reply, been dealing with some db fires! I will get you some code to replicate this asap
