### ISSUE TITLE
Sidekiq start and crash with cannot create thread error

### ISSUE THREAD

**Issue by Guymestef** [mperham/sidekiq#3856]
Ruby version: 2.3.7p456
Sidekiq: 5.0.5

I'm having this issue with Sidekiq used by my Gitlab. I created an issue on Gitlab too: https://gitlab.com/gitlab-org/gitlab-ce/issues/46850

But I guess it's more a Sidekiq issue rather than a Gitlab one?

For info, I tried starting Sidekiq with only 1 queue, and the result was the same. So I don't think it's a ressources issue...

Any idea?

```
2018-05-26T17:41:45.524Z 1708 TID--9sci7o INFO: Booting Sidekiq 5.0.5 with redis options {:path=>"/var/run/redis/redis.sock", :namespace=>"resque:gitlab", :id=>"Sidekiq-server-PID-1708", :url=>nil}

2018-05-26T17:41:45.704Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: stuck_ci_jobs_worker

2018-05-26T17:41:45.707Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: pipeline_schedule_worker

2018-05-26T17:41:45.707Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: expire_build_artifacts_worker

2018-05-26T17:41:45.710Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: repository_check_worker

2018-05-26T17:41:45.711Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: admin_email_worker

2018-05-26T17:41:45.713Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: repository_archive_cache_worker

2018-05-26T17:41:45.715Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: pages_domain_verification_cron_worker

2018-05-26T17:41:45.716Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: import_export_project_cleanup_worker

2018-05-26T17:41:45.717Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: requests_profiles_worker

2018-05-26T17:41:45.719Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: remove_expired_members_worker

2018-05-26T17:41:45.721Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: remove_expired_group_links_worker

2018-05-26T17:41:45.722Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: prune_old_events_worker

2018-05-26T17:41:45.723Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: trending_projects_worker

2018-05-26T17:41:45.726Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: remove_unreferenced_lfs_objects_worker

2018-05-26T17:41:45.728Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: stuck_import_jobs_worker

2018-05-26T17:41:45.730Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: gitlab_usage_ping_worker

2018-05-26T17:41:45.733Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: schedule_update_user_activity_worker

2018-05-26T17:41:45.735Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: remove_old_web_hook_logs_worker

2018-05-26T17:41:45.736Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: stuck_merge_jobs_worker

2018-05-26T17:41:45.774Z 1708 TID--9sci7o INFO: Cron Jobs - add job with name: issue_due_scheduler_worker

2018-05-26T17:42:12.382Z 1708 TID--9sci7o INFO: Running in ruby 2.3.7p456 (2018-03-28 revision 63024) [i686-linux]

2018-05-26T17:42:12.383Z 1708 TID--9sci7o INFO: See LICENSE and the LGPL-3.0 for licensing details.

2018-05-26T17:42:12.383Z 1708 TID--9sci7o INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org

2018-05-26T17:42:12.388Z 1708 TID--9sci7o INFO: Listening on queues ["authorized_projects", "background_migration", "create_gpg_signature", "cronjob", "cronjob:admin_email", "cronjob:expire_build_artifacts", "cronjob:gitlab_usage_ping", "cronjob:import_export_project_cleanup", "cronjob:issue_due_scheduler", "cronjob:pages_domain_verification_cron", "cronjob:pipeline_schedule", "cronjob:prune_old_events", "cronjob:remove_expired_group_links", "cronjob:remove_expired_members", "cronjob:remove_old_web_hook_logs", "cronjob:remove_unreferenced_lfs_objects", "cronjob:repository_archive_cache", "cronjob:repository_check_batch", "cronjob:requests_profiles", "cronjob:schedule_update_user_activity", "cronjob:stuck_ci_jobs", "cronjob:stuck_import_jobs", "cronjob:stuck_merge_jobs", "cronjob:trending_projects", "default", "delete_merged_branches", "delete_user", "email_receiver", "emails_on_push", "expire_build_instance_artifacts", "gcp_cluster", "gcp_cluster:check_gcp_project_billing", "gcp_cluster:cluster_install_app", "gcp_cluster:cluster_provision", "gcp_cluster:cluster_wait_for_app_installation", "gcp_cluster:cluster_wait_for_ingress_ip_address", "gcp_cluster:wait_for_cluster_creation", "git_garbage_collect", "github_import_advance_stage", "github_importer", "github_importer:github_import_import_diff_note", "github_importer:github_import_import_issue", "github_importer:github_import_import_note", "github_importer:github_import_import_pull_request", "github_importer:github_import_refresh_import_jid", "github_importer:github_import_stage_finish_import", "github_importer:github_import_stage_import_base_data", "github_importer:github_import_stage_import_issues_and_diff_notes", "github_importer:github_import_stage_import_notes", "github_importer:github_import_stage_import_pull_requests", "github_importer:github_import_stage_import_repository", "gitlab_shell", "group_destroy", "invalid_gpg_signature_update", "irker", "mail_scheduler", "mail_scheduler:mail_scheduler_issue_due", "mail_scheduler:mail_scheduler_notification_service", "mailers", "merge", "namespaceless_project_destroy", "new_issue", "new_merge_request", "new_note", "object_storage", "object_storage:object_storage_background_move", "object_storage:object_storage_migrate_uploads", "object_storage_upload", "pages", "pages_domain_verification", "pipeline_background", "pipeline_background:archive_trace", "pipeline_background:ci_build_trace_chunk_flush", "pipeline_cache", "pipeline_cache:expire_job_cache", "pipeline_cache:expire_pipeline_cache", "pipeline_creation", "pipeline_creation:create_pipeline", "pipeline_creation:run_pipeline_schedule", "pipeline_default", "pipeline_default:build_coverage", "pipeline_default:build_trace_sections", "pipeline_default:pipeline_metrics", "pipeline_default:pipeline_notification", "pipeline_hooks", "pipeline_hooks:build_hooks", "pipeline_hooks:pipeline_hooks", "pipeline_processing", "pipeline_processing:build_finished", "pipeline_processing:build_queue", "pipeline_processing:build_success", "pipeline_processing:pipeline_process", "pipeline_processing:pipeline_success", "pipeline_processing:pipeline_update", "pipeline_processing:stage_update", "pipeline_processing:update_head_pipeline_for_merge_request", "plugin", "post_receive", "process_commit", "project_cache", "project_destroy", "project_export", "project_migrate_hashed_storage", "project_service", "propagate_service_template", "reactive_caching", "rebase", "repository_check", "repository_check:repository_check_clear", "repository_check:repository_check_single_repository", "repository_fork", "repository_import", "repository_remove_remote", "repository_update_remote_mirror", "storage_migrator", "system_hook_push", "update_merge_requests", "update_user_activity", "upload_checksum", "web_hook"]

can't create Thread: Resource temporarily unavailable

/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:23:in `initialize'

/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:23:in `new'

/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:23:in `safe_thread'

/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:65:in `start'

/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/manager.rb:47:in `block in start'

/usr/local/lib/ruby/2.3.0/set.rb:306:in `each_key'

/usr/local/lib/ruby/2.3.0/set.rb:306:in `each'

/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/manager.rb:46:in `start'

/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/launcher.rb:27:in `run'

/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-cron-0.6.0/lib/sidekiq/cron/launcher.rb:31:in `run'

/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/cli.rb:105:in `run'

/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/bin/sidekiq:12:in `<top (required)>'

/home/git/gitlab/vendor/bundle/ruby/2.3.0/bin/sidekiq:23:in `load'

/home/git/gitlab/vendor/bundle/ruby/2.3.0/bin/sidekiq:23:in `<top (required)>'

/usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli/exec.rb:74:in `load'

/usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli/exec.rb:74:in `kernel_load'

/usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli/exec.rb:28:in `run'

/usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:424:in `exec'

/usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

/usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'

/usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'

/usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:27:in `dispatch'

/usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'

/usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:18:in `start'

/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/exe/bundle:30:in `block in <top (required)>'

/usr/local/lib/ruby/site_ruby/2.3.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'

/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/exe/bundle:22:in `<top (required)>'

/usr/local/bin/bundle:23:in `load'

/usr/local/bin/bundle:23:in `<main>'

```

**Comment by mperham** [comment]
Wow, that's an very large number of queues but that shouldn't matter in this case.

`can't create Thread: Resource temporarily unavailable`

I can't debug that.  This is a GitLab/environment issue, possibly you are running it in a container/instance that is too small or resource constrained.
