### ISSUE TITLE
Sidekiq becomes stuck if job enqueued while app is reloading

### ISSUE THREAD

**Issue by DimitriosLisenko** [mperham/sidekiq#3865]
Hi there!

I'm not entirely sure whether to post this to the Rails or Sidekiq project, but I can reliably reproduce it on Sidekiq (my Puma has a slightly different issue where the threads seem to be concurrently reloading code, which shouldn't be happening - may be related), so I will post it here. It looks like it has to do with the new Rails executor/reloader framework.

# Version Information
Ruby: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]`
Rails: `Rails 5.2.0`
Sidekiq: `Sidekiq 5.1.3`
Sidekiq Pro (not necessary for reproduction): `Sidekiq Pro 4.0.3`

# Reproduction steps
- Create brand new Rails app using `rails new rails_sidekiq_reproduce_bug`
- Add Sidekiq 5.1.3 to the Gemfile
- Create a Sidekiq job that spawns threads (similar to what http://guides.rubyonrails.org/threading_and_code_execution.html recommends)
```
class ReproduceBugJob
	include Sidekiq::Worker
	sidekiq_options :queue => :default
	sidekiq_options :retry => false

	def perform(sleep_seconds, threads_to_spawn)
		threads = []
		threads_to_spawn.times do
			threads << Thread.new do
				Rails.application.executor.wrap do
					puts "begin #{sleep_seconds} second sleep"
					sleep sleep_seconds
					puts "end #{sleep_seconds} second sleep"
				end
			end
		end

		ActiveSupport::Dependencies.interlock.permit_concurrent_loads do
			threads.map(&:join)
		end
	end
end
```
- open up the rails console and quickly enqueue a few jobs via `ReproduceBugJob.perform_async(1, 1)` - all works as expected
- open and save a file and quickly enqueue a few more jobs via `ReproduceBugJob.perform_async(1, 1)` - all still works as expected
- now the secret sauce: simulate a longer app reload time by adding the following to your `config/application.rb` file:
```
config.to_prepare do
	sleep_seconds = 5
	puts "Simulating longer application reload time of #{sleep_seconds} seconds"
	sleep sleep_seconds
end
```
- open up the rails console and enqueue a few jobs via `ReproduceBugJob.perform_async(1, 1)` - all works as expected
- open and save a file and enqueue a **single** `ReproduceBugJob.perform_async(1, 1)` job - app will reload for 5 seconds, and then run the job. If you enqueue more jobs after this point, everything works as expected.
- open and save a file and then enqueue a **single** `ReproduceBugJob.perform_async(1, 1)` job, and then **while the app is reloading** enqueue another one - BOOM - the application is stuck. Jobs are continued to be enqueued, but never execute after this point.

# Other information
Via a fairly nasty process I hooked up the `ActionDispatch::DebugLocks` middleware to run in Sidekiq like this (man there must be a better way...):
```
Signal.trap('TTOU') do
	Thread.new do
		puts ActionDispatch::DebugLocks.new(Rails.application, nil).send(:render_details, nil)[2][0]
	end
end
```

which gives me the following output when the application is stuck:
```
Thread 0 [0x3ff72e160a0c sleep]  No lock (yielded share)
  Waiting in start_exclusive to "unload"
  may be pre-empted for: "load", "unload"
  blocked by: 2
  blocking: 1

.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:109:in `sleep'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:109:in `wait'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:109:in `wait'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:121:in `wait_while'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:221:in `wait_for'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:83:in `block (2 levels) in start_exclusive'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:82:in `block in start_exclusive'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:77:in `start_exclusive'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:25:in `start_unloading'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:101:in `require_unload_lock!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:120:in `class_unload!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/railties-5.2.0/lib/rails/application/finisher.rb:177:in `block (2 levels) in <module:Finisher>'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:426:in `instance_exec'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:426:in `block in make_lambda'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:605:in `catch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:605:in `block in default_terminator'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:199:in `block in halting'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `block in invoke_before'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `each'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `invoke_before'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:131:in `run_callbacks'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:110:in `run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:115:in `run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:72:in `block in run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:69:in `tap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:69:in `run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:64:in `run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:85:in `wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:73:in `block in wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:72:in `wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'


---


Thread 1 [0x3ff72e1cfac4 sleep]  No lock
  Waiting in start_sharing
  blocked by: 0

.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:109:in `sleep'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:109:in `wait'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:109:in `wait'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:121:in `wait_while'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:221:in `wait_for'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:125:in `block in start_sharing'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:115:in `start_sharing'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:33:in `start_running'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/railties-5.2.0/lib/rails/application/finisher.rb:94:in `run'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:27:in `before'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:426:in `block in make_lambda'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:605:in `catch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:605:in `block in default_terminator'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:199:in `block in halting'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `block in invoke_before'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `each'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `invoke_before'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:131:in `run_callbacks'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:110:in `run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:72:in `block in run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:69:in `tap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:69:in `run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:85:in `wrap'
.../rails_sidekiq_reproduce_bug/app/jobs/reproduce_bug_job.rb:10:in `block (2 levels) in perform'


---


Thread 2 [0x3ff72e161ab0 sleep]  No lock (yielded share)
  blocking: 0

.../rails_sidekiq_reproduce_bug/app/jobs/reproduce_bug_job.rb:19:in `join'
.../rails_sidekiq_reproduce_bug/app/jobs/reproduce_bug_job.rb:19:in `map'
.../rails_sidekiq_reproduce_bug/app/jobs/reproduce_bug_job.rb:19:in `block in perform'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
.../rails_sidekiq_reproduce_bug/app/jobs/reproduce_bug_job.rb:18:in `perform'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:168:in `block in process'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:98:in `local'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:73:in `block in wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:72:in `wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

This is kinda weird because `thread 2` is blocking `thread 0`, but is itself holding no lock. Also there seems to be two reloaders running, though I haven't yet dug deeper to know what the expected behaviour is.

Thanks, let me know if you think I should instead post this to the Rails project!

**Comment by DimitriosLisenko** [comment]
Thanks Mike - I have posted it there too (https://github.com/rails/rails/issues/33133).
