### ISSUE TITLE
[ENT] Sidekiq::Limiter.concurrent raising redis error in test / Connecting to redis despite Testing.fake!

### ISSUE THREAD

**Issue by dhempy** [mperham/sidekiq#3870]
Ruby version: ruby 2.1.9p490
Sidekiq / Pro / Enterprise version(s): sidekiq-ent (1.5.2)

It seems that Sidekiq is trying to connect to Redis during Sidekiq::Limiter.concurrent(), despite being in fake mode. If that's accurate, that is a blocker for our test suite.

Rspec examples that hit code including Sidekiq::Limiter.concurrent are raising this error:

```
  1) ExporterWorker.perform calls .export
     Failure/Error:
       throttle = Sidekiq::Limiter.concurrent("client-api-#{product.client}",
                                              Setting['sidekiq.concurrency'],
                                              wait_timeout: Setting['sidekiq.wait_timeout'],
                                              lock_timeout: Setting['sidekiq.lock_timeout'])

     Redis::CommandError:
       ERR unknown command 'script'
```

I've searched extensively on this error, and searched on rpsec strategies/limitations regarding testing Sidekiq::Limiter.concurrent, without finding anything relevant. We are not running the latest version (1.5 vs. 1.71.), but I don't see anything in the changelog that seems relevant.

I have confirmed that Sidekiq::Testing.fake? is true in these examples. 

In `spec_helper.rb`, we've got this:

```
  config.before(:each) do |e|
    Sidekiq.redis = ConnectionPool.new(size: 5, timeout: 5) { Redis.new } if e.metadata[:redis].present?
  end
```

The error above (Redis::CommandError) appears when I have `redis: true` on my example. If I remove that flag (hence, not setting Sidekiq.redis), it attempts to connect to a non-existent redis server:

```
  1) ExporterWorker.perform calls .export
     Failure/Error:
       throttle = Sidekiq::Limiter.concurrent("client-api-#{product.client}",
                                              Setting['sidekiq.concurrency'],
                                              wait_timeout: Setting['sidekiq.wait_timeout'],
                                              lock_timeout: Setting['sidekiq.lock_timeout'])

     Redis::CannotConnectError:
       Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
     # ./app/workers/exporter_worker.rb:8:in `perform'
     # ./spec/workers/exporter_worker_spec.rb:17:in `block (3 levels) in <top (required)>'
```

We have other tests that exercise Sidekiq calls with no trouble. This new code (and new test) is our first code that uses Sidekiq::Limiter, and the first one to show this error in rspec. 

If I have redis running locally, all tests succeed. This is handy in development, but falls over in our CI environment (Jenkins) where there is no redis server. 

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

Here are the relevant tests. The first two fail as above. The third passes, as it never reaches the Sidekiq::Limiter code.

```
  describe '.perform' do
    it 'calls .export' do
      expect(subject).to receive(:export)
      subject.perform(product.id, 'anything')
    end

    it 'is concurrent per client' do
      expect(Sidekiq::Limiter).to receive(:concurrent)
        .with("client-api-#{product.client}", anything, anything).and_call_original
      subject.perform(product.id, 'anything')
    end

    context 'with invalid product' do
      it {expect { subject.perform('-1', :valid) }.to raise_error(ActiveRecord::RecordNotFound) }
    end
  end
```

And here is most of the worker class:
```

class ExporterWorker
  include Sidekiq::Worker
  sidekiq_options queue: :export, unique_for: 20.minutes

  def perform(product_id, export_type)
    product = Product.find(product_id)
    throttle = Sidekiq::Limiter.concurrent("client-api-#{product.client}",
                                           Setting['sidekiq.client-api.concurrency'],
                                           wait_timeout: Setting['sidekiq.client-api.wait_timeout'],
                                           lock_timeout: Setting['sidekiq.client-api.lock_timeout'])

    throttle.within_limit do
      export(product, export_type)
    end
  end
end

```

Initializer: (lightly redacted)

```
REDIS_URL = defined?(ReadyOps::REDIS_URL) ? ReadyOps::REDIS_URL : ENV['REDIS_URL']
require 'datadog/statsd'

statsd_addr = '127.0.0.1'
statsd_ns = 'readygo'
statsd = Datadog::Statsd.new(statsd_addr, 8125, namespace: statsd_ns)
Sidekiq::Pro.dogstatsd = -> { statsd }

Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!

  config.redis = { url: REDIS_URL, network_timeout: 5 }

  config.server_middleware do |chain|
    # Pro Metrics https://github.com/mperham/sidekiq/wiki/Pro-Metrics
    require 'sidekiq/middleware/server/statsd'
    chain.add Sidekiq::Middleware::Server::Statsd
  end

  # Ent Historical Metrics https://github.com/mperham/sidekiq/wiki/Ent-Historical-Metrics
  # yes, it's two entirely separate config items
  config.save_history(statsd, 30)
  
  config.periodic do |mgr|
    p = proc { |c| mgr.register(Setting[c.to_s.split('::').last.underscore + '.periodicity'], c) }
    p.call(Periodic::UnapprovedJobWorker)
    p.call(Periodic::DeleteJobWorker)
    p.call(Periodic::DeleteApprovalJobWorker)
    p.call(Periodic::ReprocessJobWorker)
    p.call(Periodic::ErrorReportJobWorker)
    p.call(Periodic::ReadyGoTimedValidationsWorker)
    # redacted
  end

  # Use an ActiveRecord connection pool size equal to Sidekiq's concurrency.
  database_config = Rails.application.config.database_configuration[Rails.env]
  database_config['pool'] = config.options[:concurrency] + 2
  ActiveRecord::Base.establish_connection(database_config)
end

Sidekiq.configure_client do |config|
  config.redis = { url: REDIS_URL, network_timeout: 5 }
end

# Disable uniqueness in testing, this has the potential to cause much head scratching...
Sidekiq::Enterprise.unique! unless Rails.env.test? || Rails.env.development?

```

**Comment by mperham** [comment]
The concurrent rate limiter requires Redis; it does not have a fake mode.  You can use an unlimited limiter in test mode. See the rate limiting wiki page for detail.

**Comment by dhempy** [comment]
That looks like a reasonable workaround. Unfortunately, we're version locked by ruby 2.1 so can't get to sidekiq-ent 1.7.0 to get .unlimited(). But, I'll mark this test as pending for when we upgrade our versions. 

Thanks for the quick response, Mike! :)

**Comment by mperham** [comment]
The concurrent limiter calls Redis when it is created so you'd make two round trips per call to `throttle`. Since `test?` does not change dynamically, it is better to do something like this:

```ruby
def self.throttle
  ...
end
LIMITER = throttle() # note throttle is now a class method
```

and then call `LIMITER.within_limit` in your job.

**Comment by jnarowski** [comment]
I see, thanks for the optimization. So is this what you meant:

```
class Reports::Jobs::ColdStoreJob < ApplicationJob
  queue_as :cold_store

  def self.throttle
    return Sidekiq::Limiter.unlimited if Rails.env.test?

    Sidekiq::Limiter.concurrent(
      'report_cold_store',
      SpectoraConfig.env_fetch('SIDEKIQ_LIMITER_COLD_STORE', 5),
      wait_timeout: 5,
      lock_timeout: 60
    )
  end

  LIMITER = throttle

  # Reports::Jobs::ColdStoreJob.perform_later(report_id: '851c623e-5132-446a-a938-e42fd4349b7a')
  def perform(report_id:)
    return if SpectoraConfig.env_var_is_true?('DISABLE_REPORT_COLD_STORE')
    return if cancelled?

    LIMITER.within_limit do
      Report.with_deleted.find(report_id).colder_store!
    end
  end
end
```

**Comment by ashortt** [comment]
I've tried the above example, but the test is still failing:
```ruby
Failures:

  1) Op::QueueProcessing#perform concurrency is concurrent per client
     Failure/Error: expect(Sidekiq::Limiter).to have_received(:unlimited)
     
       (Sidekiq::Limiter).unlimited(*(any args))
           expected: 1 time with any arguments
           received: 0 times with any arguments
     # ./spec/workers/op/queue_processing_spec.rb:24:in `block (4 levels) in <top (required)>'
     # ./spec/support/timezone.rb:9:in `block (3 levels) in <top (required)>'
     # ./spec/support/timezone.rb:9:in `block (2 levels) in <top (required)>'
```

Worker Class:
```ruby
# frozen_string_literal: true

module Op
  class QueueProcessing
    include Sidekiq::Worker

    def self.throttle
      return Sidekiq::Limiter.unlimited if Rails.env.test?

      Sidekiq::Limiter.concurrent(
        'analytics',
        1,
        wait_timeout: 5,
        lock_timeout: 120
      )
    end

    LIMITER = throttle

    def perform
      uploaded_submissions = OnClaimsSubmission.uploaded_submissions
      uploaded_submissions.each do |submission|
        LIMITER.within_limit do
          Op::ProcessDownloadedFiles.perform_async(*submission)
        end
      end
    end
  end
end

```

Test:

```ruby
# frozen_string_literal: true

require 'rails_helper'

describe Op::QueueProcessing do
  describe '#perform' do
    let(:job) { described_class.new }

    context 'concurrency' do
      before do
        allow(Sidekiq::Limiter).to receive(:unlimited)
        job.perform
      end

      it 'is concurrent per client' do
        expect(Sidekiq::Limiter).to have_received(:unlimited)
      end
    end
  end
end

```
