### ISSUE TITLE
NameError: uninitialized constant ActiveJob::QueueAdapters::SidekiqAdapter

### ISSUE THREAD

**Issue by LuckyScott** [mperham/sidekiq#3909]
Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s): 5.1.3
Rails version: 5.0.7

Use Sidekiq with ActiveJob, when retry the job, I got the error:

2018-08-01T17:33:34.052Z 17782 TID-ov7ar504q WARN: NameError: uninitialized constant ActiveJob::QueueAdapters::SidekiqAdapter
2018-08-01T17:43:54.231Z 17782 TID-ov7a56agu WARN: Work still in progress [#<struct Sidekiq::BasicFetch::UnitOfWork queue="queue:development_eastmoney_qa", job="{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"EastmoneyAnswerListJob\",\"queue\":\"development_eastmoney_qa\",\"args\":[{\"job_class\":\"EastmoneyAnswerListJob\",\"job_id\":\"0609efd2-080b-4ec5-91b1-d777c6124cd5\",\"provider_job_id\":null,\"queue_name\":\"development_eastmoney_qa\",\"priority\":null,\"arguments\":[\"180233956355084288\",\"20180801234909\"],\"locale\":\"zh-CN\"}],\"retry\":true,\"jid\":\"a94534114791405a095a1b42\",\"created_at\":1533139111.3031485,\"enqueued_at\":1533139111.303278}">, #<struct Sidekiq::BasicFetch::UnitOfWork queue="queue:development_eastmoney_qa", job="{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"EastmoneyAnswerListJob\",\"queue\":\"development_eastmoney_qa\",\"args\":[{\"job_class\":\"EastmoneyAnswerListJob\",\"job_id\":\"ba119f07-9dc1-4f4e-867f-eb9a5e8887e3\",\"provider_job_id\":null,\"queue_name\":\"development_eastmoney_qa\",\"priority\":null,\"arguments\":[\"180173261240406016\",\"20180801234909\"],\"locale\":\"zh-CN\"}],\"retry\":true,\"jid\":\"22f2bd38e96a82099346582a\",\"created_at\":1533139091.2713497,\"enqueued_at\":1533139091.2714798}">, #<struct Sidekiq::BasicFetch::UnitOfWork queue="queue:development_eastmoney_qa", job="{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"EastmoneyAnswerListJob\",\"queue\":\"development_eastmoney_qa\",\"args\":[{\"job_class\":\"EastmoneyAnswerListJob\",\"job_id\":\"a7531931-644d-463e-8492-498f4551568c\",\"provider_job_id\":null,\"queue_name\":\"development_eastmoney_qa\",\"priority\":null,\"arguments\":[\"180545874957570048\",\"20180801234909\"],\"locale\":\"zh-CN\"}],\"retry\":true,\"jid\":\"c7bf7b2e6e2a8cfdf85cfe59\",\"created_at\":1533139151.3947227,\"enqueued_at\":1533139151.3948486}">, #<struct Sidekiq::BasicFetch::UnitOfWork queue="queue:development_eastmoney_qa", job="{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"EastmoneyAnswerListJob\",\"queue\":\"development_eastmoney_qa\",\"args\":[{\"job_class\":\"EastmoneyAnswerListJob\",\"job_id\":\"2647b722-c44b-4e16-95aa-df2419c7555b\",\"queue_name\":\"development_eastmoney_qa\",\"priority\":null,\"arguments\":[\"177585634494517248\",\"20180801154603\"],\"locale\":\"zh-CN\"}],\"retry\":true,\"jid\":\"eb14df832d56c8c60a0ea97b\",\"created_at\":1533109733.8490372,\"enqueued_at\":1533138974.049545,\"error_message\":\"uninitialized constant ActiveJob::QueueAdapters\",\"error_class\":\"NameError\",\"failed_at\":1533122085.7299082,\"retry_count\":4,\"retried_at\":1533138590.882204}">, #<struct Sidekiq::BasicFetch::UnitOfWork queue="queue:development_eastmoney_qa", job="{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"EastmoneyAnswerListJob\",\"queue\":\"development_eastmoney_qa\",\"args\":[{\"job_class\":\"EastmoneyAnswerListJob\",\"job_id\":\"54bf1ee4-6979-4b9d-9d68-accaddb48760\",\"provider_job_id\":null,\"queue_name\":\"development_eastmoney_qa\",\"priority\":null,\"arguments\":[\"180130516958318592\",\"20180801234909\"],\"locale\":\"zh-CN\"}],\"retry\":true,\"jid\":\"bdfa7c3d251874d488fdcb63\",\"created_at\":1533139081.1917799,\"enqueued_at\":1533139081.1919153}">, #<struct Sidekiq::BasicFetch::UnitOfWork queue="queue:development_eastmoney_qa", job="{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"EastmoneyAnswerListJob\",\"queue\":\"development_eastmoney_qa\",\"args\":[{\"job_class\":\"EastmoneyAnswerListJob\",\"job_id\":\"a55c7699-652e-41cc-ae6a-799e80ed492f\",\"provider_job_id\":null,\"queue_name\":\"development_eastmoney_qa\",\"priority\":null,\"arguments\":[\"180499058006298624\",\"20180801234909\"],\"locale\":\"zh-CN\"}],\"retry\":true,\"jid\":\"77f8ae72ff952c07ee4ba239\",\"created_at\":1533139141.3629365,\"enqueued_at\":1533139141.3631258}">, #<struct Sidekiq::BasicFetch::UnitOfWork queue="queue:development_eastmoney_qa", job="{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"EastmoneyAnswerListJob\",\"queue\":\"development_eastmoney_qa\",\"args\":[{\"job_class\":\"EastmoneyAnswerListJob\",\"job_id\":\"a52ba620-e5a9-45d0-ac62-39cfb53b9091\",\"provider_job_id\":null,\"queue_name\":\"development_eastmoney_qa\",\"priority\":null,\"arguments\":[\"180112467618304000\",\"20180801234909\"],\"locale\":\"zh-CN\"}],\"retry\":true,\"jid\":\"88bce89989d80033219a4882\",\"created_at\":1533139071.1690612,\"enqueued_at\":1533139071.169185}">, #<struct Sidekiq::BasicFetch::UnitOfWork queue="queue:development_eastmoney_qa", job="{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"EastmoneyAnswerListJob\",\"queue\":\"development_eastmoney_qa\",\"args\":[{\"job_class\":\"EastmoneyAnswerListJob\",\"job_id\":\"0728d42e-2c3a-4478-972c-ce1fe4a3c1d0\",\"provider_job_id\":null,\"queue_name\":\"development_eastmoney_qa\",\"priority\":null,\"arguments\":[\"180497459510906880\",\"20180801234909\"],\"locale\":\"zh-CN\"}],\"retry\":true,\"jid\":\"11a8f01efd706b6b7ff8defc\",\"created_at\":1533139141.3783782,\"enqueued_at\":1533139141.3785043}">, #<struct Sidekiq::BasicFetch::UnitOfWork queue="queue:development_eastmoney_qa", job="{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"EastmoneyAnswerListJob\",\"queue\":\"development_eastmoney_qa\",\"args\":[{\"job_class\":\"EastmoneyAnswerListJob\",\"job_id\":\"8605a223-011b-4c6f-b94a-596ad18af1f1\",\"provider_job_id\":null,\"queue_name\":\"development_eastmoney_qa\",\"priority\":null,\"arguments\":[\"180155019562192896\",\"20180801234909\"],\"locale\":\"zh-CN\"}],\"retry\":true,\"jid\":\"f150c15985c8c333a0ddaa49\",\"created_at\":1533139101.2834082,\"enqueued_at\":1533139101.283536}">, #<struct Sidekiq::BasicFetch::UnitOfWork queue="queue:development_eastmoney_qa", job="{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"EastmoneyAnswerListJob\",\"queue\":\"development_eastmoney_qa\",\"args\":[{\"job_class\":\"EastmoneyAnswerListJob\",\"job_id\":\"8fb073b4-2b9b-4d95-b5d8-b30aed2cc0e4\",\"provider_job_id\":null,\"queue_name\":\"development_eastmoney_qa\",\"priority\":null,\"arguments\":[\"180548711615696896\",\"20180801234909\"],\"locale\":\"zh-CN\"}],\"retry\":true,\"jid\":\"5c6814ce75353bc6e43de4b1\",\"created_at\":1533139151.3891945,\"enqueued_at\":1533139151.3893228}">]
2018-08-01T17:44:10.180Z 18047 TID-orohnmz3v WARN: NameError: uninitialized constant ActiveJob::QueueAdapters
2018-08-01T17:44:10.184Z 18047 TID-orohnmxgr WARN: NameError: uninitialized constant ActiveJob::QueueAdapters
2018-08-01T17:44:10.186Z 18047 TID-orohnmwe7 WARN: NameError: uninitialized constant ActiveJob::QueueAdapters
2018-08-01T17:44:10.190Z 18047 TID-orohnmx3r WARN: NameError: uninitialized constant ActiveJob::QueueAdapters
2018-08-01T17:44:10.195Z 18047 TID-orohnmuu3 WARN: NameError: uninitialized constant ActiveJob::QueueAdapters::SidekiqAdapter
2018-08-01T17:44:10.193Z 18047 TID-orohnmywf WARN: NameError: uninitialized constant ActiveJob::QueueAdapters::SidekiqAdapter
2018-08-01T17:48:47.251Z 18253 TID-orz2kieit WARN: NameError: uninitialized constant ActiveJob::QueueAdapters::SidekiqAdapter
2018-08-01T17:48:47.248Z 18253 TID-orz2kigd5 WARN: NameError: uninitialized constant ActiveJob::QueueAdapters
2018-08-01T17:48:47.253Z 18253 TID-orz2kidr5 WARN: NameError: uninitialized constant ActiveJob::QueueAdapters::SidekiqAdapter
2018-08-01T17:48:47.244Z 18253 TID-orz2kidj9 WARN: NameError: uninitialized constant ActiveJob::QueueAdapters
2018-08-01T17:48:47.259Z 18253 TID-orz2kie3h WARN: NameError: uninitialized constant ActiveJob::QueueAdapters::SidekiqAdapter
2018-08-01T17:48:47.260Z 18253 TID-orz2kig75 WARN: NameError: uninitialized constant ActiveJob::QueueAdapters

**Comment by mperham** [comment]
🤷‍♂️ Never seen that error before.  Looks like ActiveJob is not initialized somehow.

**Comment by lucascharlesz** [comment]
Same issue here.

Ruby Version > 2.5.1
Rails Version > 5.2.0
Sidekiq Standard

`2018-08-28T17:12:56.737Z 3028 TID-gqwqknpb4 ProcessEventJob JID-27ac8797369e4213b9e0d112 INFO: fail: 0.037 sec
2018-08-28T17:12:56.739Z 3028 TID-gqwqknpb4 WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ProcessEventJob","queue":"low_priority","args":[{"job_class":"ProcessEventJob","job_id":"c5a75403-3d29-49cc-a44c-a1df12519919","provider_job_id":"802377bf75d2759e0ee3ae5a","queue_name":"low_priority","priority":null,"arguments":["3f9465ff-2c75-4f7b-99ce-78e5987464fe"],"executions":24,"locale":"pt-BR"}],"retry":true,"jid":"27ac8797369e4213b9e0d112","created_at":1535476346.169731,"enqueued_at":1535476376.6985261},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ProcessEventJob\",\"queue\":\"low_priority\",\"args\":[{\"job_class\":\"ProcessEventJob\",\"job_id\":\"c5a75403-3d29-49cc-a44c-a1df12519919\",\"provider_job_id\":\"802377bf75d2759e0ee3ae5a\",\"queue_name\":\"low_priority\",\"priority\":null,\"arguments\":[\"3f9465ff-2c75-4f7b-99ce-78e5987464fe\"],\"executions\":24,\"locale\":\"pt-BR\"}],\"retry\":true,\"jid\":\"27ac8797369e4213b9e0d112\",\"created_at\":1535476346.169731,\"enqueued_at\":1535476376.6985261}"}
2018-08-28T17:12:56.739Z 3028 TID-gqwqknpb4 WARN: NameError: uninitialized constant ActiveJob::QueueAdapters
2018-08-28T17:12:56.739Z 3028 TID-gqwqknpb4 WARN: /home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:223:in `block in constantize'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:220:in `each'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:220:in `inject'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:220:in `constantize'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/reloader.rb:73:in `block in wrap'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/reloader.rb:72:in `wrap'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
2018-08-28T17:12:56.738Z 3028 TID-gqwqknpz4 ProcessEventJob JID-d3fdc74bebb09e4b1a878da4 INFO: fail: 0.032 sec
2018-08-28T17:12:56.741Z 3028 TID-gqwqknpz4 WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ProcessEventJob","queue":"low_priority","args":[{"job_class":"ProcessEventJob","job_id":"1a0ff059-c311-4883-9c83-6f0b6e02fdd1","provider_job_id":"412dc3da7650b070c4224921","queue_name":"low_priority","priority":null,"arguments":["6bca4d83-7dde-4a62-8366-bb76508a39ad"],"executions":58,"locale":"pt-BR"}],"retry":true,"jid":"d3fdc74bebb09e4b1a878da4","created_at":1535476346.1719508,"enqueued_at":1535476376.702507},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ProcessEventJob\",\"queue\":\"low_priority\",\"args\":[{\"job_class\":\"ProcessEventJob\",\"job_id\":\"1a0ff059-c311-4883-9c83-6f0b6e02fdd1\",\"provider_job_id\":\"412dc3da7650b070c4224921\",\"queue_name\":\"low_priority\",\"priority\":null,\"arguments\":[\"6bca4d83-7dde-4a62-8366-bb76508a39ad\"],\"executions\":58,\"locale\":\"pt-BR\"}],\"retry\":true,\"jid\":\"d3fdc74bebb09e4b1a878da4\",\"created_at\":1535476346.1719508,\"enqueued_at\":1535476376.702507}"}
2018-08-28T17:12:56.742Z 3028 TID-gqwqknpz4 WARN: NameError: uninitialized constant ActiveJob::QueueAdapters
2018-08-28T17:12:56.742Z 3028 TID-gqwqknpz4 WARN: /home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:223:in `block in constantize'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:220:in `each'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:220:in `inject'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:220:in `constantize'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/reloader.rb:73:in `block in wrap'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/reloader.rb:72:in `wrap'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
/home/fr0sty/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'`

**Comment by mperham** [comment]
Please follow up if you determine the issue.  Otherwise, supply an app which reproduces the problem and I would be happy to debug the issue.

**Comment by Fishy49** [comment]
Sorry to bump this but Google led me here and I thought I'd share for future seekers.

In my case - I had a sneaky non-rails application running that was pointing to the same Redis DB. Check that you aren't double-dipping in your job queue!
