### ISSUE TITLE
(multi thread) NameError: uninitialized constant

### ISSUE THREAD

**Issue by excosy** [mperham/sidekiq#3939]
Ruby version: 2.4.1
Rails version: 5.0.5
Sidekiq version: 5.2.1 

backtrace:
```
2018-08-28T02:47:08.357Z 7842 TID-rvsva SalesSubscriptionCreateCycleResource JID-54f2a3baa5f284fcd6a2a786 INFO: start
2018-08-28T02:47:08.877Z 6816 TID-qwpso WARN: {"queue":"dev_v2_default","args":[],"class":"CrmActiveCustomerStatisticCreateEveryWeek","retry":false,"backtrace":true,"jid":"f190730a98ba21327ef2d05d","created_at":1535424412.9140818,"enqueued_at":1535424412.9141066}
2018-08-28T02:47:08.901Z 6816 TID-qwpso WARN: NameError: uninitialized constant CrmActiveCustomerStatisticCreateEveryWeek
Did you mean?  CrmActiveCustomerStatistic
2018-08-28T02:47:08.901Z 6816 TID-qwpso WARN: /home/kuban/.bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/inflector/methods.rb:268:in `const_get'
/home/kuban/.bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/inflector/methods.rb:268:in `block in constantize'
/home/kuban/.bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/inflector/methods.rb:266:in `each'
/home/kuban/.bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/inflector/methods.rb:266:in `inject'
/home/kuban/.bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/inflector/methods.rb:266:in `constantize'
/home/kuban/.bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/home/kuban/.bundle/ruby/2.4.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:124:in `process'
/home/kuban/.bundle/ruby/2.4.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:80:in `process_one'
/home/kuban/.bundle/ruby/2.4.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:68:in `run'
/home/kuban/.bundle/ruby/2.4.0/gems/sidekiq-4.1.2/lib/sidekiq/util.rb:17:in `watchdog'
/home/kuban/.bundle/ruby/2.4.0/gems/sidekiq-4.1.2/lib/sidekiq/util.rb:25:in `block in safe_thread'
2018-08-28T02:47:09.292Z 7842 TID-rvsva SalesSubscriptionCreateCycleResource JID-54f2a3baa5f284fcd6a2a786 INFO: done: 0.934 sec
2018-08-28T02:47:09.292Z 7842 TID-rvsva AdminSendDailyReport JID-487e7a52b408b08ab6510c06 INFO: start
2018-08-28T02:47:09.293Z 7842 TID-rvsva AdminSendDailyReport JID-487e7a52b408b08ab6510c06 INFO: done: 0.001 sec
2018-08-28T02:47:09.294Z 7842 TID-rvsva SmartPlugGroupBatchOff JID-d196912ed0625aeb4b417a97 INFO: start
2018-08-28T02:47:09.302Z 7842 TID-rvsva SmartPlugGroupBatchOff JID-d196912ed0625aeb4b417a97 INFO: done: 0.008 sec
2018-08-28T02:47:09.302Z 7842 TID-rvsva CrmSourceStatisticCreateEveryDay JID-f108c51baa72f56d68da817f INFO: start
2018-08-28T02:47:09.526Z 7842 TID-rvsva CrmSourceStatisticCreateEveryDay JID-f108c51baa72f56d68da817f INFO: done: 0.223 sec
2018-08-28T02:50:15.772Z 7842 TID-rvsva PgHeroCaptureQueryStats JID-ff9ef62a19bdffbacb4f0d5f INFO: start
2018-08-28T02:50:15.773Z 7842 TID-rvsva PgHeroCaptureQueryStats JID-ff9ef62a19bdffbacb4f0d5f INFO: done: 0.001 sec
```
It seems like thread `TID-rvsva` has loaded these classes but `TID-qwpso` hasn't. How to avoid it?

I have defined these classes at `app/workers/cron_jobs` and eager_load them at `config/application.rb`:
```
config.eager_load_paths += %W[#{Rails.root}/app/workers/cron_jobs]
```
and this is my `config/initializers/sidekiq.rb`:
```
# postfix could be: high, default, low
def Sidekiq.get_queue_name(postfix)
  "#{Settings['sidekiq_env'] || Settings['app_env'] || Rails.env}_#{postfix}"
end

Sidekiq.default_worker_options = { retry: false, backtrace: true, queue: Sidekiq.get_queue_name('default') }

# delay several seconds to waiting for DB sync, otherwise ActiveRecord::RecordNotFound may occur
Sidekiq::PERFOM_DELAY = 20.seconds

if Settings['sidekiq'].present? && Settings['sidekiq']['url'].present?
  Sidekiq.configure_server do |config|
    config.redis = { url: "redis://#{Settings['sidekiq']['url']}:6379", password: Settings['sidekiq']['auth'] }
  end

  Sidekiq.configure_client do |config|
    config.redis = { url: "redis://#{Settings['sidekiq']['url']}:6379", password: Settings['sidekiq']['auth'] }
  end
end

Sidekiq::Extensions.enable_delay!
```

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#autoloading
