### ISSUE TITLE
UTF-8 Error in Job Causing Infinite Loop of Retries with Super Fetch

### ISSUE THREAD

**Issue by ToniRib** [mperham/sidekiq#3952]
**Ruby version:** 2.5.1
**Sidekiq / Pro / Enterprise version(s):**
Originally found with sidekiq 4.2.10 & sidekiq pro 3.7.1, but tried upgrading and the issue was still present with sidekiq 5.2.1 & sidekiq pro 4.0.4

**Scenario**

We have a worker that is used to import a CSV to create records in a database table. When the worker starts, it sends an email to the user notifying them that the import has begun and giving them a time estimate for when it will finish.

When the CSV has a UTF-8 error (shown in the error message below), the job dies and then retries 3 times, failing each time. Because we are using super fetch, the job gets moved to the private queue `queue:sq|worker.1:75:f7e02f046911|default`, which actually occurs a total of 4 times due to the retries.

Heroku restarts our dynos approximately every 24 hours, and upon the dyno shutdown, these jobs get moved back into our default queue from the private queue. When the dyno comes back up, all 4 of the jobs now in the default queue are attempted again, failing each time since they still have the same UTF-8 error. For this job specifically, since there is an email sent out prior to the job failing, our internal customer success managers who encountered this started getting dozens of emails per day.

I noticed that after the job fails, I see this line in the logs:
`ERROR: Unable to remove job from private queue queue:sq|worker.1:75:f7e02f046911|default: 0`
which looks like we are failing to clean up the private queue, resulting in these jobs going round and round until I manually flush them from redis.

I originally thought that this was related to https://github.com/mperham/sidekiq/issues/3294 & https://github.com/mperham/sidekiq/issues/3296, but upgrading to the latest versions didn't make any difference. I assume that's because the JSON is actually valid in this case.

So my questions are:
- Is there a way to tell why these jobs can't be removed from the private queue?
- Is the reason they get stuck in this loop due to the UTF-8 error itself? Possibly some underlying thing with how redis handles the encoding?

**Initializer as of the upgraded version:**

```ruby
include ActiveRecordConfigLogger

Sidekiq::Extensions.enable_delay!

Sidekiq.configure_server do |config|
  if Rails.env.development?
    config.redis = { url: 'redis://127.0.0.1:6379/0', size: 4 }
  else
    config.redis = { url: ENV['REDISCLOUD_URL'], size: 7 }
  end

  config.super_fetch!
  config.reliable_scheduler!
  log_active_record_config
end

Sidekiq.configure_client do |config|
  redis_url = ENV['REDISCLOUD_URL'].presence || 'redis://127.0.0.1:6379/0'
  config.redis = { url: redis_url, size: 1 }
end
```

**Error Message**

```
2018-09-06T16:56:59.434121+00:00 app[worker.1]: 75 TID-oxebuzjn7 WARN: ArgumentError: invalid byte sequence in UTF-8
2018-09-06T16:56:59.434232+00:00 app[worker.1]: 75 TID-oxebuzjn7 WARN: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1833:in `sub!'
2018-09-06T16:56:59.434235+00:00 app[worker.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1833:in `block in shift'
2018-09-06T16:56:59.434237+00:00 app[worker.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1821:in `loop'
2018-09-06T16:56:59.434238+00:00 app[worker.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1821:in `shift'
2018-09-06T16:56:59.434240+00:00 app[worker.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1763:in `each'
2018-09-06T16:56:59.434242+00:00 app[worker.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/csv.rb:1319:in `parse'
2018-09-06T16:56:59.434244+00:00 app[worker.1]: /app/app/workers/csv_contact_import_worker.rb:12:in `perform'
2018-09-06T16:56:59.434245+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:185:in `execute_job'
2018-09-06T16:56:59.434247+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'
2018-09-06T16:56:59.434249+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
2018-09-06T16:56:59.434251+00:00 app[worker.1]: /app/config/initializers/sidekiq_logger.rb:9:in `block in call'
2018-09-06T16:56:59.434252+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/logging.rb:48:in `with_context'
2018-09-06T16:56:59.434254+00:00 app[worker.1]: /app/config/initializers/sidekiq_logger.rb:5:in `call'
2018-09-06T16:56:59.434255+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2018-09-06T16:56:59.434257+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/newrelic_rpm-5.1.0.344/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
2018-09-06T16:56:59.434259+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/newrelic_rpm-5.1.0.344/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:369:in `perform_action_with_newrelic_trace'
2018-09-06T16:56:59.434261+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/newrelic_rpm-5.1.0.344/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
2018-09-06T16:56:59.434263+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2018-09-06T16:56:59.434264+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/middleware/server/active_record.rb:16:in `call'
2018-09-06T16:56:59.434266+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2018-09-06T16:56:59.434268+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-pro-4.0.4/lib/sidekiq/batch/middleware.rb:56:in `call'
2018-09-06T16:56:59.434269+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2018-09-06T16:56:59.434271+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sentry-raven-2.7.4/lib/raven/integrations/sidekiq.rb:9:in `call'
2018-09-06T16:56:59.434272+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2018-09-06T16:56:59.434274+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:133:in `invoke'
2018-09-06T16:56:59.434275+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:166:in `block in process'
2018-09-06T16:56:59.434277+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
2018-09-06T16:56:59.434279+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/job_retry.rb:98:in `local'
2018-09-06T16:56:59.434281+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
2018-09-06T16:56:59.434282+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
2018-09-06T16:56:59.434284+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
2018-09-06T16:56:59.434285+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:217:in `stats'
2018-09-06T16:56:59.434287+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
2018-09-06T16:56:59.434289+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/job_logger.rb:8:in `call'
2018-09-06T16:56:59.434290+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
2018-09-06T16:56:59.434292+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/job_retry.rb:73:in `global'
2018-09-06T16:56:59.434294+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:125:in `block in dispatch'
2018-09-06T16:56:59.434296+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/logging.rb:48:in `with_context'
2018-09-06T16:56:59.434298+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
2018-09-06T16:56:59.434299+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:124:in `dispatch'
2018-09-06T16:56:59.434301+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:165:in `process'
2018-09-06T16:56:59.434302+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:83:in `process_one'
2018-09-06T16:56:59.434310+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:71:in `run'
2018-09-06T16:56:59.434312+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:16:in `watchdog'
2018-09-06T16:56:59.434314+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:25:in `block in safe_thread'
2018-09-06T16:56:59.509388+00:00 app[worker.1]: Sending event 0123755a4e3c4e8fa809cf9d61e6b12e to Sentry
2018-09-06T16:57:00.699724+00:00 heroku[worker.1]: source=worker.1 dyno=heroku.58361383.823a656b-e24a-4c05-8012-bd1d46655c2f sample#load_avg_1m=0.23
2018-09-06T16:57:00.700018+00:00 heroku[worker.1]: source=worker.1 dyno=heroku.58361383.823a656b-e24a-4c05-8012-bd1d46655c2f sample#memory_total=239.90MB sample#memory_rss=239.74MB sample#memory_cache=0.16MB sample#memory_swap=0.00MB sample#memory_pgpgin=74460pages sample#memory_pgpgout=14068pages sample#memory_quota=1024.00MB
2018-09-06T16:56:59.905413+00:00 app[worker.1]: 75 TID-oxebuzjn7 ERROR: Unable to remove job from private queue queue:sq|worker.1:75:f7e02f046911|default: 0
```

**Worker Class**

```ruby
class CsvContactImportWorker < GscWorker

  def perform(user_id, csv_file_content)
    user_requesting_upload = User.find user_id
    current_row = 0
    success_count = 0
    @errors = []
    utf8_file_content = csv_file_content.force_encoding('UTF-8')

    # This email is getting sent every single time the jobs get picked up
    UserMailer.csv_import_started_email(user_requesting_upload, estimated_time(csv_file_content)).deliver_now

    # This is where the job fails
    CSV.parse(utf8_file_content, headers: true, converters: lambda { |f| f ? f.strip : nil }) do |row|
      current_row += 1

      all_fields_blank = row.fields.all? { |f| f.blank? }
      next if all_fields_blank

      place = Place.find row["gsc_place_id"] rescue nil
      if place.blank?
        @errors << "Row #{current_row}: Place ID is missing or invalid"
        next
      end

      contact = Contact.find row["gsc_contact_id"] rescue nil
      if contact.nil? && row["gsc_contact_id"].present?
        @errors << "Row #{current_row}: Contact ID is invalid"
        next
      end
      contact = Contact.new if contact.blank?

      if row["delete"].try(:downcase) == 'true'
        success_count += 1 if contact.destroy
        next
      end

      contact.place_id = row["gsc_place_id"]
      contact.title = row["title"]
      contact.first_name = row["first_name"]
      contact.last_name = row["last_name"]
      contact.email = row["email"]
      contact.phone_mobile = row["phone_mobile"]
      begin
        success_count += 1 if contact.save!
      rescue ActiveRecord::RecordInvalid
        @errors << "Row #{current_row}: #{contact.errors.full_messages.first}"
      end
    end

    send_results_email(user_requesting_upload, @errors, success_count)
  end
end
```

**Comment by mperham** [comment]
Please give me a small job input which triggers the behavior.  I will investigate.

**Comment by ToniRib** [comment]
The ruby string that is the `csv_file_content` is attached. Basically we just call `file.read` on the actual CSV and feed the result of that in as the 2nd argument.



`user_id` = 140051
`csv_file_content` [csv_file_content.txt](https://github.com/mperham/sidekiq/files/2358239/csv_file_content.txt)

**Comment by ToniRib** [comment]
I've been doing some additional investigation. It appears that the actual file contains strings like `San Jos�`, which, once they are read out by Ruby using File.read become `San Jos\x8E`. 

Changing the line in our worker from
`utf8_file_content = csv_file_content.force_encoding('UTF-8')`
to 
`utf8_file_content = csv_file_content.scrub.force_encoding('UTF-8')`

converts the `\x8E` back into `�` which actually allows the job to process and does not throw the ArgumentError for UTF-8 encoding. It doesn't really explain why sidekiq can't remove it from the private queue in redis, but it does at least prevent the job from failing in the first place.

I am curious though if you find out any more related to why the encoding creates these so called "poison pill" jobs that get stuck in the infinite loop.

**Comment by mperham** [comment]
Those file contents aren't CSV, but a mangled string format.  Could you please attach the actual CSV so I can reproduce it?

**Comment by mperham** [comment]
It might be possible that the JSON job payload string that comes from Redis RPOP serializes differently when calling LREM, due to the invalid bytes.

In my experience it is typical, when you get data from an untrusted external source, to use iconv or another tool to cleanse the bytes to ensure they are valid UTF8.  That would be my suggestion: cleanse the data to ensure it is well-formed before it gets to Sidekiq.

**Comment by ToniRib** [comment]
I had to save the file as `.txt` because apparently GitHub doesn't all you to upload files with the `.csv` extension, but here it is!
[Nixon_contacts.txt](https://github.com/mperham/sidekiq/files/2361337/Nixon_contacts.txt)

Anyway, thanks for the advice! I think we will definitely take the route of just sanitizing it.

**Comment by mperham** [comment]
When I try to push a job with your CSV content, I get this error:

```
source sequence is illegal/malformed utf-8
/Users/mikeperham/.rubies/ruby-2.4.2/lib/ruby/2.4.0/json/common.rb:224:in `generate'
/Users/mikeperham/.rubies/ruby-2.4.2/lib/ruby/2.4.0/json/common.rb:224:in `generate'
/Users/mikeperham/src/sidekiq/lib/sidekiq.rb:182:in `dump_json'
/Users/mikeperham/src/sidekiq/lib/sidekiq/client.rb:202:in `block in atomic_push'
/Users/mikeperham/src/sidekiq/lib/sidekiq/client.rb:200:in `map'
/Users/mikeperham/src/sidekiq/lib/sidekiq/client.rb:200:in `atomic_push'
/Users/mikeperham/src/sidekiq/lib/sidekiq/client.rb:185:in `block (2 levels) in raw_push'
/Users/mikeperham/.gem/ruby/2.4.2/gems/redis-4.0.2/lib/redis.rb:2362:in `block in multi'
/Users/mikeperham/.gem/ruby/2.4.2/gems/redis-4.0.2/lib/redis.rb:45:in `block in synchronize'
/Users/mikeperham/.rubies/ruby-2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/mikeperham/.gem/ruby/2.4.2/gems/redis-4.0.2/lib/redis.rb:45:in `synchronize'
/Users/mikeperham/.gem/ruby/2.4.2/gems/redis-4.0.2/lib/redis.rb:2355:in `multi'
/Users/mikeperham/src/sidekiq/lib/sidekiq/client.rb:184:in `block in raw_push'
/Users/mikeperham/.gem/ruby/2.4.2/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
/Users/mikeperham/.gem/ruby/2.4.2/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
/Users/mikeperham/.gem/ruby/2.4.2/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
/Users/mikeperham/.gem/ruby/2.4.2/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
/Users/mikeperham/.gem/ruby/2.4.2/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
/Users/mikeperham/src/sidekiq/lib/sidekiq/client.rb:183:in `raw_push'
/Users/mikeperham/src/pro/lib/sidekiq/batch/client.rb:41:in `raw_push'
/Users/mikeperham/src/pro/lib/sidekiq/pro/push.rb:43:in `raw_push'
/Users/mikeperham/src/sidekiq/lib/sidekiq/client.rb:74:in `push'
/Users/mikeperham/src/sidekiq/lib/sidekiq/worker.rb:143:in `client_push'
/Users/mikeperham/src/sidekiq/lib/sidekiq/worker.rb:87:in `perform_async'
/Users/mikeperham/src/pro/myapp/config/initializers/sidekiq.rb:9:in `<top (required)>'
```

Notice how it's using the basic JSON library included with Ruby.  It looks like you might have a different JSON setup in your process that is allowing illegal JSON to slip through, maybe OJ or Yajl-ruby?
