### ISSUE TITLE
Net::Http calls fail in context of job, otherwise work

### ISSUE THREAD

**Issue by jasonfine** [mperham/sidekiq#4004]
Ruby version: 2.1.4
Sidekiq version: 4.2.10 (not pro)
No initializer/default settings

Due to devops constraints I am unable to bump up ruby version to 2.2.2 to satisfy the sidekiq 5.x upgrade.

I am attempting to put a data import operation that has existed and been functional for a long time, into a sidekiq job. It hits multiple API endpoints and consumes data for local DB storage.

In our existing implementation, it runs fine. In a sidekiq job, I am seeing:

```
I, [2018-10-24T12:09:29.969453 #54328]  INFO -- : getaddrinfo: nodename nor servname provided, or not known
I, [2018-10-24T12:09:29.969618 #54328]  INFO -- : /Users/jason/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
/Users/jason/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:879:in `open'
/Users/jason/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
/Users/jason/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
/Users/jason/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:878:in `connect'
/Users/jason/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
/Users/jason/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:852:in `start'
/Users/jason/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:583:in `start'
/Users/jason/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:478:in `get_response'
/Users/jason/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:455:in `get'
/Library/WebServer/Documents/admin_app/lib/importer.rb:77:in `block (2 levels) in import'
/Users/jason/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/Users/jason/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
/Users/jason/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/timeout.rb:35:in `catch'
/Users/jason/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/timeout.rb:35:in `catch'
/Users/jason/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
/Library/WebServer/Documents/admin_app/lib/importer.rb:76:in `block in import'
/Library/WebServer/Documents/admin_app/lib/importer.rb:58:in `each'
/Library/WebServer/Documents/admin_app/lib/importer.rb:58:in `import'
/Library/WebServer/Documents/admin_app/app/workers/frameworks_import_worker.rb:13:in `perform'

Any thoughts on what leads to this?

Thank you

**Comment by mperham** [comment]
That error means it cannot DNS resolve the hostname at `admin_app/lib/importer.rb:77`.

**Comment by jasonfine** [comment]
Right, I guess I am failing to understand why calling this from a sidekiq job leads to this vs. being called from anywhere else in the app, or the rails console, works.

**Comment by mperham** [comment]
I have no idea, Sidekiq makes no changes to your network or DNS setup.

**Comment by jasonfine** [comment]
Computer restart fixed it.
