### ISSUE TITLE
Allow duplicate queue names

### ISSUE THREAD

**Issue by stanhu** [mperham/sidekiq#4022]
Ruby version: 2.5.3
Sidekiq 5.2.3

We often define duplicate queues on purpose to give more bandwidth to processing jobs in a single process. With the change in https://github.com/mperham/sidekiq/pull/3936, this is now not possible:

```
2018-11-19_21:36:16.94007 2018-11-19T21:36:16.939Z 14279 TID-oveubl9f0 INFO: A worker terminated, shutting down the cluster
2018-11-19_21:36:17.07635 2018-11-19T21:36:17.076Z 14310 TID-ox18zdg4g INFO: Starting cluster with 1 processes
2018-11-19_21:36:17.91363 queues: merge cannot be defined twice
2018-11-19_21:36:17.91366 /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.3/lib/sidekiq/cli.rb:440:in `parse_queue'
2018-11-19_21:36:17.91366 /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/sidekiq-5.2.3/lib/sidekiq/cli.rb:346:in `block (2 levels) in parse_options'
2018-11-19_21:36:17.91367 /opt/gitlab/embedded/lib/ruby/2.5.0/optparse.rb:1584:in `block in parse_in_order'
2018-11-19_21:36:17.91367 /opt/gitlab/embedded/lib/ruby/2.5.0/optparse.rb:1538:in `catch'
2018-11-19_21:36:17.91367 /opt/gitlab/embedded/lib/ruby/2.5.0/optparse.rb:1538:in `parse_in_order'
2018-11-19_21:36:17.91367 /opt/gitlab/embedded/lib/ruby/2.5.0/optparse.rb:1532:in `order!'
2018-11-19_21:36:17.91367 /opt/gitlab/embedded/lib/ruby/2.5.0/optparse.rb:1626:in `permute!'
2018-11-19_21:36:17.91368 /opt/gitlab/embedded/lib/ruby/2.5.0/optparse.rb:1648:in `parse!'
```

Are you using an old version?

This was introduced in 5.2.2.

**Comment by mperham** [comment]
I don’t understand the use case. Are weighted priorities are the solution?

**Comment by stanhu** [comment]
It could be. We currently have a Sidekiq script that launches N number of processes based on the config and the queues. For example, the config might look like:

```ruby
["process_commit,process_commit,process_commit", 
 "new_note,new_note", 
 "merge,merge,update_merge_requests"]
```

In this example, we launch 3 different Sidekiq processes with `-q <queue>` for each comma-separated entry. The concurrency is set to the number of entries in the entry.

We set the weight to each queue to 1 at the moment. But we might be able derive the weights from the list just from the count. Let me close this issue and see if that works.

Thanks!
