### ISSUE TITLE
Heroku deploy REDIS_PROVIDER returns invalid uri

### ISSUE THREAD

**Issue by fly49** [mperham/sidekiq#4048]
Ruby version: ruby-2.4.4
Sidekiq version: 5.2.3

Hi!
As it said in docs, in my heroku config vars I should set
```
REDIS_PROVIDER=REDISTOGO_URL
REDISTOGO_URL=redis://redistogo:REDACTED@soapfish.redistogo.com:10607/
```
If I do that, Sidekiq will be initialized with proper url
```
Booting Sidekiq 5.2.3 with redis options {:id=>"Sidekiq-server-PID-4", :url=>"redis://redistogo:REDACTED@soapfish.redistogo.com:10607/"}
```
But when worker is getting triggered, it tries to get redis locally
```
2018-12-09T11:13:20.154881+00:00 app[worker.1]: 4 TID-gq731pbws GetLinkTitleWorker JID-bfaa39c8bb4cde9f25598f7a INFO: start
2018-12-09T11:13:21.465317+00:00 app[worker.1]: 4 TID-gq731pbws GetLinkTitleWorker JID-bfaa39c8bb4cde9f25598f7a INFO: fail: 1.31 sec
2018-12-09T11:13:21.465424+00:00 app[worker.1]: 4 TID-gq731pbws WARN: {"context":"Job raised exception","job":{"class":"GetLinkTitleWorker","args":["tsPWjfOe"],"retry":false,"queue":"default","jid":"bfaa39c8bb4cde9f25598f7a","created_at":1544354000.1363657,"enqueued_at":1544354000.1366732},"jobstr":"{\"class\":\"GetLinkTitleWorker\",\"args\":[\"tsPWjfOe\"],\"retry\":false,\"queue\":\"default\",\"jid\":\"bfaa39c8bb4cde9f25598f7a\",\"created_at\":1544354000.1363657,\"enqueued_at\":1544354000.1366732}"}
2018-12-09T11:13:21.465479+00:00 app[worker.1]: 4 TID-gq731pbws WARN: Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
2018-12-09T11:13:21.465507+00:00 app[worker.1]: 4 TID-gq731pbws WARN: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis/client.rb:350:in `rescue in establish_connection'
2018-12-09T11:13:21.465509+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis/client.rb:333:in `establish_connection'
2018-12-09T11:13:21.465510+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis/client.rb:104:in `block in connect'
2018-12-09T11:13:21.465511+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis/client.rb:296:in `with_reconnect'
2018-12-09T11:13:21.465513+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis/client.rb:103:in `connect'
2018-12-09T11:13:21.465514+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis/client.rb:369:in `ensure_connected'
2018-12-09T11:13:21.465516+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis/client.rb:224:in `block in process'
2018-12-09T11:13:21.465517+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis/client.rb:309:in `logging'
2018-12-09T11:13:21.465518+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis/client.rb:223:in `process'
2018-12-09T11:13:21.465520+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis/client.rb:123:in `call'
2018-12-09T11:13:21.465521+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis.rb:796:in `block in set'
2018-12-09T11:13:21.465522+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis.rb:50:in `block in synchronize'
2018-12-09T11:13:21.465524+00:00 app[worker.1]: /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
2018-12-09T11:13:21.465525+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis.rb:50:in `synchronize'
2018-12-09T11:13:21.465527+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis.rb:792:in `set'
2018-12-09T11:13:21.465529+00:00 app[worker.1]: /app/app/workers/get_link_title_worker.rb:16:in `perform'
2018-12-09T11:13:21.465530+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:185:in `execute_job'
2018-12-09T11:13:21.465531+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'
2018-12-09T11:13:21.465532+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
2018-12-09T11:13:21.465534+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
2018-12-09T11:13:21.465535+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:166:in `block in process'
2018-12-09T11:13:21.465537+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
2018-12-09T11:13:21.465538+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/job_retry.rb:108:in `local'
2018-12-09T11:13:21.465539+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
2018-12-09T11:13:21.465541+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/rails.rb:42:in `block in call'
2018-12-09T11:13:21.465542+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:87:in `wrap'
2018-12-09T11:13:21.465543+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:73:in `block in wrap'
2018-12-09T11:13:21.465544+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:87:in `wrap'
2018-12-09T11:13:21.465546+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:72:in `wrap'
2018-12-09T11:13:21.465547+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/rails.rb:41:in `call'
2018-12-09T11:13:21.465548+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
2018-12-09T11:13:21.465550+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:243:in `stats'
2018-12-09T11:13:21.465551+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
2018-12-09T11:13:21.465552+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/job_logger.rb:8:in `call'
2018-12-09T11:13:21.465554+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
2018-12-09T11:13:21.465555+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/job_retry.rb:73:in `global'
2018-12-09T11:13:21.465556+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:125:in `block in dispatch'
2018-12-09T11:13:21.465558+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/logging.rb:48:in `with_context'
2018-12-09T11:13:21.465559+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
2018-12-09T11:13:21.465560+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:124:in `dispatch'
2018-12-09T11:13:21.465562+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:165:in `process'
2018-12-09T11:13:21.465563+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:83:in `process_one'
2018-12-09T11:13:21.465564+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:71:in `run'
2018-12-09T11:13:21.465571+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/util.rb:16:in `watchdog'
2018-12-09T11:13:21.465572+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
```
Okay, let's assume that it should be like that. As we don't have sidekiq initializer therefore we don't explicitly declare what redis server to use , though it is not mentioned anywhere that we have to create it before use.
So If I create an initializer
```
Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDIS_PROVIDER'] }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['REDIS_PROVIDER'] }
end
```
I will get next message
```
2018-12-09T11:53:45.804207+00:00 app[worker.1]: 4 TID-gnq29rdp8 INFO: Booting Sidekiq 5.2.3 with redis options {:url=>"REDISTOGO_URL", :id=>"Sidekiq-server-PID-4"}
2018-12-09T11:53:46.403745+00:00 heroku[worker.1]: Process exited with status 1
2018-12-09T11:53:46.245045+00:00 app[worker.1]: 4 TID-gnq29rdp8 INFO: Running in ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
2018-12-09T11:53:46.245086+00:00 app[worker.1]: 4 TID-gnq29rdp8 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2018-12-09T11:53:46.245088+00:00 app[worker.1]: 4 TID-gnq29rdp8 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2018-12-09T11:53:46.245094+00:00 app[worker.1]: invalid uri scheme ''
2018-12-09T11:53:46.245096+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis/client.rb:425:in `_parse_options'
2018-12-09T11:53:46.245097+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis/client.rb:81:in `initialize'
2018-12-09T11:53:46.245098+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis.rb:43:in `new'
2018-12-09T11:53:46.245100+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.3/lib/redis.rb:43:in `initialize'
2018-12-09T11:53:46.245101+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/redis_connection.rb:55:in `new'
2018-12-09T11:53:46.245107+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/redis_connection.rb:55:in `build_client'
2018-12-09T11:53:46.245109+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/redis_connection.rb:34:in `block in create'
2018-12-09T11:53:46.245111+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:171:in `try_create'
2018-12-09T11:53:46.245119+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:83:in `block (2 levels) in pop'
2018-12-09T11:53:46.245121+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:79:in `loop'
2018-12-09T11:53:46.245122+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:79:in `block in pop'
2018-12-09T11:53:46.245123+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:78:in `synchronize'
2018-12-09T11:53:46.245125+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:78:in `pop'
2018-12-09T11:53:46.245126+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:93:in `checkout'
2018-12-09T11:53:46.245128+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:62:in `block in with'
2018-12-09T11:53:46.245129+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
2018-12-09T11:53:46.245131+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
2018-12-09T11:53:46.245132+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq.rb:92:in `redis'
2018-12-09T11:53:46.245133+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq.rb:106:in `redis_info'
2018-12-09T11:53:46.245135+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/lib/sidekiq/cli.rb:80:in `run'
2018-12-09T11:53:46.245136+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.2.3/bin/sidekiq:12:in `<top (required)>'
2018-12-09T11:53:46.245143+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/bin/sidekiq:23:in `load'
2018-12-09T11:53:46.245144+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/bin/sidekiq:23:in `<top (required)>'
2018-12-09T11:53:46.245146+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
2018-12-09T11:53:46.245147+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
2018-12-09T11:53:46.245149+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
2018-12-09T11:53:46.245150+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
2018-12-09T11:53:46.245152+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2018-12-09T11:53:46.245153+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
2018-12-09T11:53:46.245155+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
2018-12-09T11:53:46.245156+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
2018-12-09T11:53:46.245158+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
2018-12-09T11:53:46.245159+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
2018-12-09T11:53:46.245160+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
2018-12-09T11:53:46.245162+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
2018-12-09T11:53:46.245163+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
2018-12-09T11:53:46.245164+00:00 app[worker.1]: /app/bin/bundle:3:in `load'
2018-12-09T11:53:46.245166+00:00 app[worker.1]: /app/bin/bundle:3:in `<main>'
```
I have no idea why I get `invalid uri scheme ''` because I do everything as mentioned in docs. But If I create a `REDIS_URL` with same value as `REDISTOGO_URL` everything will be alright and workers will do their job.
So why `REDIS_PROVIDER` is needed at all If it at least doen't work proper and moreover can be easily replaced by `REDIS_URL`?
Please explain me where am I wrong and how to prevent users getting stucked with this problem, because I found a bunch of stackoverflow questions about issues like that and I want to help to prevent  people spent days trying to figure out the idea of basic sidekiq usage.
Thank you!

**Comment by mperham** [comment]
You don't need an initializer at all.  Looks like your code in get_link_title_worker.rb line 16 is wrong.  Show it.

**Comment by fly49** [comment]
Sorry, you are right, it is my bad. Thank you for answer.
