### ISSUE TITLE
Sidekiq stopped working with `undefined method `to_sym' for nil:NilClass`

### ISSUE THREAD

**Issue by userrails** [mperham/sidekiq#4083]
__Ruby version:__

Sidekiq / Pro / Enterprise version(s): Sidekiq 3.4.1

__Deployment__

Heroku

__What am I doing__

```ruby
Order.find_in_batches do |orders|
	Chewy::Strategy::Sidekiq::Worker.perform_async('PurchaseOrdersIndex', orders.map(&:id))
end
```

This added around 600 workers in my queue, and process 5 workers at a time. I was completed till 110 workers, and then suddenly stopped working .

__STACK TRACE__

When I check the logs I found this, which doesn't seems to be related with my source code or database entry, because I can run same Worker in seperate review app, and it is successful.

```
2019-01-11T08:33:21.990020+00:00 app[worker.1]:  (5.4ms)  BEGIN                                                                                                                     
2019-01-11T08:33:21.992644+00:00 app[worker.1]:  (1.3ms)  ROLLBACK                                                                                                                  
2019-01-11T08:33:21.994969+00:00 app[worker.1]: 4 TID-gss3pwlm0 Chewy::Strategy::Sidekiq::Worker JID-5be215c8da5393667b1632f8 DEBUG: Failure! Retry 4 in 276 seconds                 
2019-01-11T08:33:22.007941+00:00 app[worker.1]: 4 TID-gss3pwlm0 Chewy::Strategy::Sidekiq::Worker JID-5be215c8da5393667b1632f8 INFO: fail: 0.028 sec                                 
2019-01-11T08:33:22.020102+00:00 app[worker.1]: 4 TID-gss3pwlm0 WARN: {"class"=>"Chewy::Strategy::Sidekiq::Worker", "args"=>["PurchaseOrdersIndex", [500000]], "retry"=>true, "queue"
=>"default", "jid"=>"5be215c8da5393667b1632f8", "created_at"=>1547195311.9899657, "enqueued_at"=>1547195601.9731789, "error_message"=>"undefined method `to_sym' for nil:NilClass\nDi
d you mean?  to_s", "error_class"=>"NoMethodError", "failed_at"=>1547195312.4665627, "retry_count"=>4, "retried_at"=>1547195601.9948761}                                             
2019-01-11T08:33:22.020252+00:00 app[worker.1]: 4 TID-gss3pwlm0 WARN: NoMethodError: undefined method `to_sym' for nil:NilClass                                                     
2019-01-11T08:33:22.020255+00:00 app[worker.1]: Did you mean?  to_s                                                                                                                  
2019-01-11T08:33:22.020345+00:00 app[worker.1]: 4 TID-gss3pwlm0 WARN: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/sanitization.rb:59:in `block in expand_
hash_conditions_for_aggregates'                                                                                                                                                     
2019-01-11T08:33:22.020349+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/sanitization.rb:58:in `each'                                 
2019-01-11T08:33:22.020351+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/sanitization.rb:58:in `expand_hash_conditions_for_aggregates'
2019-01-11T08:33:22.020352+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/relation/query_methods.rb:957:in `build_where'               
2019-01-11T08:33:22.020354+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/relation/query_methods.rb:584:in `where!'                   
2019-01-11T08:33:22.020356+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/relation/query_methods.rb:574:in `where'                     
2019-01-11T08:33:22.020370+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/relation.rb:82:in `_update_record'                          
2019-01-11T08:33:22.020372+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/persistence.rb:515:in `_update_record'                      
2019-01-11T08:33:22.020373+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/locking/optimistic.rb:79:in `_update_record'          
2019-01-11T08:33:22.020375+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/attribute_methods/dirty.rb:129:in `_update_record'          
2019-01-11T08:33:22.020377+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/callbacks.rb:310:in `block in _update_record'                
2019-01-11T08:33:22.020378+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:88:in `__run_callbacks__'                     
2019-01-11T08:33:22.020380+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:778:in `_run_update_callbacks'
2019-01-11T08:33:22.020381+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/callbacks.rb:310:in `_update_record'                        
2019-01-11T08:33:22.020383+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/timestamp.rb:70:in `_update_record'                          
2019-01-11T08:33:22.020384+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/persistence.rb:504:in `create_or_update'                     
2019-01-11T08:33:22.020386+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/callbacks.rb:302:in `block in create_or_update'             
2019-01-11T08:33:22.020387+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:88:in `__run_callbacks__'                     
2019-01-11T08:33:22.020389+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'                 
2019-01-11T08:33:22.020390+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/callbacks.rb:302:in `create_or_update'                       
2019-01-11T08:33:22.020392+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/persistence.rb:120:in `save' 
2019-01-11T08:38:07.112224+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/validations.rb:37:in `save'                                 
2019-01-11T08:38:07.112226+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/attribute_methods/dirty.rb:21:in `save'                     
2019-01-11T08:38:07.112227+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:286:in `block (2 levels) in save'           
2019-01-11T08:38:07.112229+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_s
tatus'
2019-01-11T08:38:07.112231+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `t
ransaction'
2019-01-11T08:38:07.112232+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:220:in `transaction'                        
2019-01-11T08:38:07.112234+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'  
2019-01-11T08:38:07.112235+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:286:in `block in save'                      
2019-01-11T08:38:07.112237+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'      
2019-01-11T08:38:07.112242+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:285:in `save'                               
2019-01-11T08:38:07.112244+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/active_record_helper.rb:26:in `block i
n save'
2019-01-11T08:38:07.112246+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent.rb:586:in `with_database_metric_name'                
2019-01-11T08:38:07.112253+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/active_record_helper.rb:25:in `save' 
2019-01-11T08:38:07.112254+00:00 app[worker.1]: /apjp/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/persistence.rb:252:in `block in update'                    
2019-01-11T08:38:07.112256+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_s
tatus'
2019-01-11T08:38:07.112258+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `b
lock in transaction'
2019-01-11T08:38:07.112260+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_ne
w_transaction'
2019-01-11T08:38:07.112261+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `t
ransaction'
2019-01-11T08:38:07.112263+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:220:in `transaction'                        
2019-01-11T08:38:07.112264+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'  
2019-01-11T08:38:07.112266+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/persistence.rb:250:in `update'                              
2019-01-11T08:38:07.112267+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq_monitor-0.1.7/lib/sidekiq/monitor/processor.rb:11:in `start'                             
2019-01-11T08:38:07.112269+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq_monitor-0.1.7/lib/sidekiq/monitor/server/middleware.rb:11:in `block in call'             
2019-01-11T08:38:07.112270+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_
connection'
2019-01-11T08:38:07.112272+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq_monitor-0.1.7/lib/sidekiq/monitor/server/middleware.rb:10:in `call'                      
2019-01-11T08:38:07.112273+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'    
2019-01-11T08:38:07.112275+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'                         
2019-01-11T08:38:07.112276+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'                           
2019-01-11T08:38:07.112278+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'                           
2019-01-11T08:38:07.112279+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'                           
2019-01-11T08:38:07.112280+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-status-1.0.1/lib/sidekiq-status/server_middleware.rb:42:in `call'                        
2019-01-11T08:38:07.112282+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'                           
2019-01-11T08:38:07.112283+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/server/logging.rb:15:in `block in call'                     
2019-01-11T08:38:07.112285+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/logging.rb:30:in `with_context'                                        
2019-01-11T08:38:07.112287+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/server/logging.rb:11:in `call'                              
2019-01-11T08:38:07.112288+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'                           
2019-01-11T08:38:07.112289+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'                                    
2019-01-11T08:38:07.112291+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/processor.rb:51:in `block in process'                                  
2019-01-11T08:38:07.112292+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/processor.rb:98:in `stats'                                             
2019-01-11T08:38:07.112294+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.4.1/lib/sidekiq/processor.rb:50:in `process'                                           
2019-01-11T08:38:07.112295+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'                                      
2019-01-11T08:38:07.112297+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'                                         
2019-01-11T08:38:07.112298+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'                                        
2019-01-11T08:38:07.112300+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'                                   
2019-01-11T08:38:07.112301+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'                                     
2019-01-11T08:38:07.112303+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'                                   
2019-01-11T08:38:07.112304+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'                              
2019-01-11T08:38:07.112306+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'          
```

**Comment by mikegee** [comment]
This is coming up out of the `update` method of some ActiveRecord class. Sidekiq wouldn't have tried to update any of your models. I don't know what Chewy is, but I suspect the issue is in there.
