### ISSUE TITLE
Sidekiq Enterprise 1.8 causes crash loop in background

### ISSUE THREAD

**Issue by goncalopereira** [mperham/sidekiq#4106]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 1.8
Works with 1.7.2

bundle exec puma -C config/puma.rb

```
[54551] Puma starting in cluster mode...
12:32:21 PM web.1 |  [54551] * Version 3.12.0 (ruby 2.4.5-p335), codename: Llamas in Pajamas
12:32:21 PM web.1 |  [54551] * Min threads: 0, max threads: 5
12:32:21 PM web.1 |  [54551] * Environment: development
12:32:21 PM web.1 |  [54551] * Process workers: 1
12:32:21 PM web.1 |  [54551] * Phased restart available
12:32:21 PM web.1 |  [54551] * Listening on tcp://0.0.0.0:5000
12:32:21 PM web.1 |  [54551] Use Ctrl-C to stop
12:32:21 PM web.1 |  Starting workers...
12:32:21 PM web.1 |  Before worker fork...
12:32:21 PM web.1 |  thread count 5
12:32:21 PM web.1 |  worker max 5
12:32:21 PM web.1 |  using replica false
12:32:21 PM web.1 |  WARNING: If you plan to load any of ActiveSupport's core extensions to Hash, be
12:32:21 PM web.1 |  sure to do so *before* loading Sinatra::Application or Sinatra::Base. If not,
12:32:21 PM web.1 |  you may disregard this warning.
12:32:21 PM web.1 |  Set SINATRA_ACTIVESUPPORT_WARNING=false in the environment to hide this warning.
12:32:21 PM web.1 |  Before worker fork...
12:32:21 PM web.1 |  /Users/gpereira/proj/vendor/ruby/2.4.0/gems/sidekiq-ent-1.8.0/lib/sidekiq-ent/metrics.rb:41:in `<class:History>': uninitialized constant Sidekiq::Enterprise::History::Singleton (NameError)
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/sidekiq-ent-1.8.0/lib/sidekiq-ent/metrics.rb:40:in `<module:Enterprise>'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/sidekiq-ent-1.8.0/lib/sidekiq-ent/metrics.rb:39:in `<module:Sidekiq>'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/sidekiq-ent-1.8.0/lib/sidekiq-ent/metrics.rb:6:in `<top (required)>'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/sidekiq-ent-1.8.0/lib/sidekiq-ent.rb:13:in `require'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/sidekiq-ent-1.8.0/lib/sidekiq-ent.rb:13:in `<top (required)>'
12:32:21 PM web.1 |  	from config.ru:7:in `require'
12:32:21 PM web.1 |  	from config.ru:7:in `block in <main>'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
12:32:21 PM web.1 |  	from config.ru:in `new'
12:32:21 PM web.1 |  	from config.ru:in `<main>'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/puma-3.12.0/lib/puma/configuration.rb:318:in `load_rackup'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/puma-3.12.0/lib/puma/configuration.rb:243:in `app'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/puma-3.12.0/lib/puma/runner.rb:155:in `app'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/puma-3.12.0/lib/puma/runner.rb:162:in `start_server'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/puma-3.12.0/lib/puma/cluster.rb:273:in `worker'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/puma-3.12.0/lib/puma/cluster.rb:137:in `block (2 levels) in spawn_workers'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/puma-3.12.0/lib/puma/cluster.rb:137:in `fork'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/puma-3.12.0/lib/puma/cluster.rb:137:in `block in spawn_workers'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/puma-3.12.0/lib/puma/cluster.rb:133:in `times'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/puma-3.12.0/lib/puma/cluster.rb:133:in `spawn_workers'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/puma-3.12.0/lib/puma/cluster.rb:466:in `run'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/puma-3.12.0/lib/puma/cli.rb:78:in `run'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/gems/puma-3.12.0/bin/puma:10:in `<top (required)>'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/bin/puma:23:in `load'
12:32:21 PM web.1 |  	from /Users/gpereira/proj/vendor/ruby/2.4.0/bin/puma:23:in `<top (required)>'
12:32:21 PM web.1 |  	from /Users/gpereira/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
12:32:21 PM web.1 |  	from /Users/gpereira/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
12:32:21 PM web.1 |  	from /Users/gpereira/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
12:32:21 PM web.1 |  	from /Users/gpereira/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
12:32:21 PM web.1 |  	from /Users/gpereira/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
12:32:21 PM web.1 |  	from /Users/gpereira/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
12:32:21 PM web.1 |  	from /Users/gpereira/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
12:32:21 PM web.1 |  	from /Users/gpereira/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
12:32:21 PM web.1 |  	from /Users/gpereira/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
12:32:21 PM web.1 |  	from /Users/gpereira/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
12:32:21 PM web.1 |  	from /Users/gpereira/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
12:32:21 PM web.1 |  	from /Users/gpereira/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
12:32:21 PM web.1 |  	from /Users/gpereira/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
12:32:21 PM web.1 |  	from /Users/gpereira/.rbenv/versions/2.4.5/bin/bundle:23:in `load'
12:32:21 PM web.1 |  	from /Users/gpereira/.rbenv/versions/2.4.5/bin/bundle:23:in `<main>'
12:32:21 PM web.1 |  thread count 5
12:32:21 PM web.1 |  worker max 5
12:32:21 PM web.1 |  using replica false
```

**Comment by mperham** [comment]
Thanks, to work around this issue, add this to the top of your initializer:

```ruby
require 'singleton'
```

I'll get this fixed in 1.8.1.
