### ISSUE TITLE
Jobs can be duplicated if failing during a Sidekiq::Shutdown

### ISSUE THREAD

**Issue by nyddogghr** [mperham/sidekiq#4112]
Ruby Version: 2.4.5p335
Sidekiq version: 5.2.5

I'm using sidekiq (neither Pro nor Enterprise) with a Rails 5.2 application and I can see jobs being duplicated sometimes on sidekiq restart (using heroku). If the job fails during restart due to Sidekiq::Shutdown, it can be sent to both retry and failed queues.
Here is for instance logs showing the issue:
```
2019-02-28T15:57:59.930830+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Running in ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux]
2019-02-28T15:57:59.931251+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2019-02-28T15:57:59.931492+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2019-02-28T15:57:59.931652+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Booting Sidekiq 5.2.5 with redis options {:id=>"Sidekiq-server-PID-4", :url=>"redis://h:REDACTED@ec2-63-32-218-34.eu-west-1.compute.amazonaws.com:6729"}
2019-02-28T15:57:59.939714+00:00 app background.1 - - 4 TID-oxr838ra4 WARN: Sidekiq 6.0 will require Redis 4.0+, you are using Redis v3.2.12
2019-02-28T15:57:59.939794+00:00 app background.1 - - 4 TID-oxr838ra4 DEBUG: Client Middleware:
2019-02-28T15:57:59.939842+00:00 app background.1 - - 4 TID-oxr838ra4 DEBUG: Server Middleware: Raven::SidekiqCleanupMiddleware, NewRelic::SidekiqInstrumentation
2019-02-28T15:57:59.939869+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Starting processing, hit Ctrl-C to stop
2019-02-28T15:57:59.939976+00:00 app background.1 - - 4 TID-oxr838ra4 DEBUG: {:queues=>["critical", "critical", "critical", "critical", "critical", "critical", "critical", "background_api", "background_api", "background_api", "default", "default", "default", "default", "default", "thumb_image", "thumb_image", "thumb_image", "thumb_image", "thumb_image", "low", "low", "low"], :labels=>[], :concurrency=>7, :require=>".", :environment=>"production", :timeout=>8, :poll_interval_average=>nil, :average_scheduled_poll_interval=>5, :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x00007ff82736b330>, #<Raven::SidekiqErrorHandler:0x00007ff814911900>, #<Proc:0x00007ff818953a90@/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/sidekiq.rb:66>], :death_handlers=>[], :lifecycle_events=>{:startup=>[], :quiet=>[], :shutdown=>[], :heartbeat=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :reloader=>#<Sidekiq::Rails::Reloader @app=HerokuService::Application>, :verbose=>true, :limits=>{:thumb_image=>4}, :strict=>false, :config_file=>"./config/sidekiq.yml", :tag=>"app", :identity=>"background.1:4:931b719f8bfd", :fetch=>Sidekiq::LimitFetch}
2019-02-28T15:58:00.001045+00:00 app background.1 - - 4 TID-oxr4317cs Api::BackgroundRequestJob JID-938441f1737c768516eb805a INFO: start
2019-02-28T15:58:19.938971+00:00 app background.1 - - 4 TID-oxr838ra4 DEBUG: Got TERM signal
2019-02-28T15:58:19.938998+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Shutting down
2019-02-28T15:58:19.939252+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Terminating quiet workers
2019-02-28T15:58:19.939255+00:00 app background.1 - - 4 TID-oxr4o5ehs INFO: Scheduler exiting...
2019-02-28T15:58:20.441705+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Pausing to allow workers to finish...
2019-02-28T15:58:27.515236+00:00 app background.1 - - 4 TID-oxr838ra4 WARN: Terminating 1 busy worker threads
2019-02-28T15:58:27.515323+00:00 app background.1 - - 4 TID-oxr838ra4 WARN: Work still in progress [#<struct Sidekiq::LimitFetch::UnitOfWork queue="queue:background_api", job="{\"class\":\"Api::BackgroundRequestJob\",\"args\":[],\"retry\":3,\"queue\":\"background_api\",\"jid\":\"938441f1737c768516eb805a\",\"created_at\":1551369418.3886776,\"enqueued_at\":1551369418.3892639}">]
2019-02-28T15:58:27.515386+00:00 app background.1 - - 4 TID-oxr838ra4 DEBUG: Re-queueing terminated jobs
2019-02-28T15:58:27.516756+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Pushed 1 jobs back to Redis
2019-02-28T15:58:27.518465+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Bye!
2019-02-28T15:58:27.614586+00:00 app background.1 - - Sending event f745ed721b36484ba521c8cc30d62cb2 to Sentry
2019-02-28T15:58:28.354806+00:00 app background.1 - -
2019-02-28T15:58:28.354825+00:00 app background.1 - - Sidekiq::Shutdown (Sidekiq::Shutdown):
2019-02-28T15:58:28.354831+00:00 app background.1 - -
2019-02-28T15:58:28.354833+00:00 app background.1 - - app/lib/api/response.rb:43:in `to_json'
2019-02-28T15:58:28.354835+00:00 app background.1 - - app/controllers/api/application_controller.rb:15:in `respond_with'
2019-02-28T15:58:28.354836+00:00 app background.1 - - app/controllers/api/v2/media_controller.rb:199:in `index'
2019-02-28T15:58:28.354838+00:00 app background.1 - - app/jobs/api/background_request_job.rb:48:in `perform'
2019-02-28T15:58:31.649134+00:00 app background.1 - - /app/vendor/bundle/ruby/2.4.0/gems/logging-1.8.2/lib/logging/appender.rb:139: warning: constant ::Fixnum is deprecated
2019-02-28T15:58:34.166322+00:00 app background.1 - - 4 TID-ou72l12ck INFO: Running in ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux]
2019-02-28T15:58:34.166344+00:00 app background.1 - - 4 TID-ou72l12ck INFO: See LICENSE and the LGPL-3.0 for licensing details.
2019-02-28T15:58:34.166346+00:00 app background.1 - - 4 TID-ou72l12ck INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2019-02-28T15:58:34.166531+00:00 app background.1 - - 4 TID-ou72l12ck INFO: Booting Sidekiq 5.2.5 with redis options {:id=>"Sidekiq-server-PID-4", :url=>"redis://h:REDACTED@ec2-63-32-218-34.eu-west-1.compute.amazonaws.com:6729"}
2019-02-28T15:58:34.173212+00:00 app background.1 - - 4 TID-ou72l12ck WARN: Sidekiq 6.0 will require Redis 4.0+, you are using Redis v3.2.12
2019-02-28T15:58:34.173309+00:00 app background.1 - - 4 TID-ou72l12ck DEBUG: Client Middleware:
2019-02-28T15:58:34.173357+00:00 app background.1 - - 4 TID-ou72l12ck DEBUG: Server Middleware: Raven::SidekiqCleanupMiddleware, NewRelic::SidekiqInstrumentation
2019-02-28T15:58:34.173385+00:00 app background.1 - - 4 TID-ou72l12ck INFO: Starting processing, hit Ctrl-C to stop
2019-02-28T15:58:34.173541+00:00 app background.1 - - 4 TID-ou72l12ck DEBUG: {:queues=>["critical", "critical", "critical", "critical", "critical", "critical", "critical", "background_api", "background_api", "background_api", "default", "default", "default", "default", "default", "thumb_image", "thumb_image", "thumb_image", "thumb_image", "thumb_image", "low", "low", "low"], :labels=>[], :concurrency=>7, :require=>".", :environment=>"production", :timeout=>8, :poll_interval_average=>nil, :average_scheduled_poll_interval=>5, :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x00007f76403fae18>, #<Raven::SidekiqErrorHandler:0x00007f7636ab2300>, #<Proc:0x00007f7636683d10@/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/sidekiq.rb:66>], :death_handlers=>[], :lifecycle_events=>{:startup=>[], :quiet=>[], :shutdown=>[], :heartbeat=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :reloader=>#<Sidekiq::Rails::Reloader @app=HerokuService::Application>, :verbose=>true, :limits=>{:thumb_image=>4}, :strict=>false, :config_file=>"./config/sidekiq.yml", :tag=>"app", :identity=>"background.1:4:a230ea8abb57", :fetch=>Sidekiq::LimitFetch}
2019-02-28T15:58:34.262481+00:00 app background.1 - - 4 TID-ou6yv8vjs Api::BackgroundRequestJob JID-938441f1737c768516eb805a INFO: start
2019-02-28T15:58:58.681202+00:00 app background.1 - - 4 TID-ou6yvb7jw DEBUG: enqueued retry: {"class":"Api::BackgroundRequestJob","args":[],"retry":3,"queue":"background_api","jid":"938441f1737c768516eb805a","created_at":1551369418.3886776,"enqueued_at":1551369418.3892639,"error_message":"Call received non OK status 500 for path '/api/v2/media.json'.","error_class":"Api::Exception::Unknown","failed_at":1551369508.460359,"retry_count":0}
2019-02-28T15:58:58.683340+00:00 app background.1 - - 4 TID-ou6yv8vtg Api::BackgroundRequestJob JID-938441f1737c768516eb805a INFO: start
```
Sometimes the error shown is indeed Sidekiq::Shutdown, but it can also be other errors that are caused by it.

This seems to be linked to https://github.com/mperham/sidekiq/issues/897, but as I understood this one was fixed some times ago already.

Would you have any recommendation to prevent this duplication?

Thanks.

**Comment by mperham** [comment]
Is your job rescueing Exception or Sidekiq::Shutdown explicitly?

Sidekiq's retry subsystem ignores Sidekiq::Shutdown so any jobs which raise Sidekiq::Shutdown should not go into the retry queue, as noted here.

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/job_retry.rb#L76

**Comment by nyddogghr** [comment]
I have a `rescue StandardError` in my job, so I can log some data, but the error is reraised as-is.
I've managed to reproduce locally, by simply hitting Ctrl+C during job process, with this simplified job (the original job simulates requests to the Rails app):
```
class Api::BackgroundRequestJob
  include Rails.application.routes.url_helpers

  sidekiq_options :queue => :background_api, :retry => 3

  def perform(path, params, job_status_id, authorization_header = nil)
    begin
      app = ActionDispatch::Integration::Session.new(Rails.application)
      app.send(:get, '/api/v2/media.json', :params => {
        :access_token => '[REDACTED]'
      })
      if app.response.status != 200
        raise Api::Exception::Unknown, 'error'
      end
    end while true

  rescue StandardError => error
    raise error
  end
end
```
Here is the exact log:
```
2019-03-01T09:31:02.952Z 12069 TID-gmuyiqjp9 INFO: Running in ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux]
2019-03-01T09:31:02.952Z 12069 TID-gmuyiqjp9 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2019-03-01T09:31:02.952Z 12069 TID-gmuyiqjp9 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2019-03-01T09:31:02.952Z 12069 TID-gmuyiqjp9 INFO: Booting Sidekiq 5.2.5 with redis options {:id=>"Sidekiq-server-PID-12069", :url=>nil}
2019-03-01T09:31:02.953Z 12069 TID-gmuyiqjp9 DEBUG: Client Middleware:
2019-03-01T09:31:02.953Z 12069 TID-gmuyiqjp9 DEBUG: Server Middleware: Raven::SidekiqCleanupMiddleware
2019-03-01T09:31:02.953Z 12069 TID-gmuyiqjp9 INFO: Starting processing, hit Ctrl-C to stop
2019-03-01T09:31:02.953Z 12069 TID-gmuyiqjp9 DEBUG: {:queues=>["critical", "critical", "critical", "critical", "critical", "critical", "critical", "background_api", "background_api", "background_api", "default", "default", "default", "default", "default", "thumb_image", "thumb_image", "thumb_image", "thumb_image", "thumb_image", "low", "low", "low"], :labels=>[], :concurrency=>7, :require=>".", :environment=>"development", :timeout=>8, :poll_interval_average=>nil, :average_scheduled_poll_interval=>5, :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x0000555d18a3bc48>, #<Raven::SidekiqErrorHandler:0x0000555d1a4c11d0>], :death_handlers=>[], :lifecycle_events=>{:startup=>[], :quiet=>[], :shutdown=>[], :heartbeat=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :reloader=>#<Sidekiq::Rails::Reloader @app=HerokuService::Application>, :verbose=>true, :limits=>{:thumb_image=>3}, :strict=>false, :config_file=>"./config/sidekiq.yml", :tag=>"ottsm", :identity=>"flof:12069:d74959bf2f2c", :fetch=>Sidekiq::LimitFetch}
2019-03-01T09:31:02.961Z 12069 TID-gmuzfa7h5 Api::BackgroundRequestJob JID-5bcfbe5406ea50290c19e752 INFO: start
^C2019-03-01T09:31:08.086Z 12069 TID-gmuyiqjp9 DEBUG: Got INT signal
2019-03-01T09:31:08.086Z 12069 TID-gmuyiqjp9 INFO: Shutting down
2019-03-01T09:31:08.086Z 12069 TID-gmuyiqjp9 INFO: Terminating quiet workers
2019-03-01T09:31:08.086Z 12069 TID-gmuzfdrz1 INFO: Scheduler exiting...
2019-03-01T09:31:08.186Z 12069 TID-gmuyiqjp9 INFO: Pausing to allow workers to finish...
2019-03-01T09:31:16.062Z 12069 TID-gmuyiqjp9 WARN: Terminating 1 busy worker threads
2019-03-01T09:31:16.062Z 12069 TID-gmuyiqjp9 WARN: Work still in progress [#<struct Sidekiq::LimitFetch::UnitOfWork queue="queue:background_api", job="{\"class\":\"Api::BackgroundRequestJob\",\"args\":[\"/api/v2/media.json\",{\"name_like\":\"ar\",\"background\":\"true\",\"controller\":\"api/v2/media\",\"action\":\"index\",\"format\":\"json\"},570964,\"bearer yyM9k3enqd1sytqmsVTCxspzcm5qNkF9dquJ7Dsdydor\"],\"retry\":3,\"queue\":\"background_api\",\"jid\":\"5bcfbe5406ea50290c19e752\",\"created_at\":1551431800.5185301,\"enqueued_at\":1551431800.5185857}">]
2019-03-01T09:31:16.062Z 12069 TID-gmuyiqjp9 DEBUG: Re-queueing terminated jobs
2019-03-01T09:31:16.062Z 12069 TID-gmuyiqjp9 INFO: Pushed 1 jobs back to Redis
2019-03-01T09:31:16.136Z 12069 TID-gmuzfa7h5 Api::BackgroundRequestJob JID-5bcfbe5406ea50290c19e752 INFO: fail: 13.176 sec
2019-03-01T09:31:16.136Z 12069 TID-gmuzfa7h5 WARN: {"context":"Job raised exception","job":{"class":"Api::BackgroundRequestJob","args":["/api/v2/media.json",{"name_like":"ar","background":"true","controller":"api/v2/media","action":"index","format":"json"},570964,"bearer yyM9k3enqd1sytqmsVTCxspzcm5qNkF9dquJ7Dsdydor"],"retry":3,"queue":"background_api","jid":"5bcfbe5406ea50290c19e752","created_at":1551431800.5185301,"enqueued_at":1551431800.5185857},"jobstr":"{\"class\":\"Api::BackgroundRequestJob\",\"args\":[\"/api/v2/media.json\",{\"name_like\":\"ar\",\"background\":\"true\",\"controller\":\"api/v2/media\",\"action\":\"index\",\"format\":\"json\"},570964,\"bearer yyM9k3enqd1sytqmsVTCxspzcm5qNkF9dquJ7Dsdydor\"],\"retry\":3,\"queue\":\"background_api\",\"jid\":\"5bcfbe5406ea50290c19e752\",\"created_at\":1551431800.5185301,\"enqueued_at\":1551431800.5185857}"}
2019-03-01T09:31:16.136Z 12069 TID-gmuzfa7h5 WARN: Api::Exception::Unknown: error
2019-03-01T09:31:16.137Z 12069 TID-gmuzfa7h5 WARN: /home/flof/Git/ottsm/app/jobs/api/background_request_job.rb:15:in `perform'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:185:in `execute_job'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sentry-raven-2.7.4/lib/raven/integrations/sidekiq.rb:9:in `call'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:166:in `block in process'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:108:in `local'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:43:in `block in call'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bundler/gems/rails-c46a33bf8d66/activesupport/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bundler/gems/rails-c46a33bf8d66/activesupport/lib/active_support/reloader.rb:73:in `block in wrap'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bundler/gems/rails-c46a33bf8d66/activesupport/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bundler/gems/rails-c46a33bf8d66/activesupport/lib/active_support/reloader.rb:72:in `wrap'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:42:in `call'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:243:in `stats'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/job_logger.rb:8:in `call'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:73:in `global'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:125:in `block in dispatch'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:48:in `with_context'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:124:in `dispatch'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:165:in `process'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:83:in `process_one'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:71:in `run'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:16:in `watchdog'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:25:in `block in safe_thread'
/home/flof/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2019-03-01T09:31:16.137Z 12069 TID-gmuyiqjp9 INFO: Bye!
```

From what I understand, this is what happens:
* Sidekiq tries to stop the job, and raises Sidekiq::Shutdown because it keeps running
* This sends the job back to the queue
* Right before it stops, this exception causes an error in the job and Api::Exception::Unknown is then raised because of the non 200 status
* This causes the job to fail and goes back to retry queue
* Sidekiq stops effectively

I've also noticed that sometimes, I just see a logging line saying the job fails without having the time to send it to retry queue:
```
2019-03-01T09:29:16.055Z 11491 TID-gn74va18n WARN: Terminating 1 busy worker threads
2019-03-01T09:29:16.056Z 11491 TID-gn74va18n WARN: Work still in progress [#<struct Sidekiq::LimitFetch::UnitOfWork queue="queue:background_api", job="{\"class\":\"Api::BackgroundRequestJob\",\"args\":[\"/api/v2/media.json\",{\"name_like\":\"ar\",\"background\":\"true\",\"controller\":\"api/v2/media\",\"action\":\"index\",\"format\":\"json\"},570964,\"bearer yyM9k3enqd1sytqmsVTCxspzcm5qNkF9dquJ7Dsdydor\"],\"retry\":3,\"queue\":\"background_api\",\"jid\":\"5bcfbe5406ea50290c19e752\",\"created_at\":1551431800.5185301,\"enqueued_at\":1551431800.5185857}">]
2019-03-01T09:29:16.056Z 11491 TID-gn74va18n DEBUG: Re-queueing terminated jobs
2019-03-01T09:29:16.057Z 11491 TID-gn74va18n INFO: Pushed 1 jobs back to Redis
2019-03-01T09:29:16.058Z 11491 TID-gn75sz9y7 Api::BackgroundRequestJob JID-5bcfbe5406ea50290c19e752 INFO: fail: 10.269 sec
2019-03-01T09:29:16.058Z 11491 TID-gn74va18n INFO: Bye!
```

Thanks for any help.

**Comment by mperham** [comment]
What is the type of Api::Exception::Unknown?

**Comment by nyddogghr** [comment]
It's an `Exception`. 
```
[14] pry(main)> Api::Exception::Unknown.superclass.superclass
=> Exception
```

**Comment by mperham** [comment]
All application errors should be subclasses of StandardError but you are calling superclass twice so maybe it is.

Possibly you are hitting a race condition in shutdown; here's my understanding:

1. See Sidekiq::Manager#hard_shutdown.
2. This method is called once we've waited for the shutdown timeout `-t`.
3. We requeue any jobs still lingering.
4. Then we raise Sidekiq::Shutdown to cancel running threads.

In between 3 and 4, your job raises and saves a retry.  Step 3 should invalidate running jobs and the retry subsystem should check to see if the job is still valid before pushing it to Redis.

Sidekiq does document that jobs can be executed more than once in rare cases and this is one such case but it might be something we can fix.

**Comment by nyddogghr** [comment]
I'm sorry I wasn't clear, my class `Api::Exception::Unknown` is in fact a subclass of `Api::Exception` which is in an `Exception`.

I confirm this seems to be pretty rare. Over 5000 thousands jobs this has seemed to happen only twice.

**Comment by mperham** [comment]
Closing this in lieu of #4112, thanks for reporting and supplying all the info.
