### ISSUE TITLE
uninitialized constant Sidekiq::Rails::Application 

### ISSUE THREAD

**Issue by brasscapon** [mperham/sidekiq#4121]
On a completely new rails app with installing sidekiq being the only action taken, I can't run any rails commands (not even `rails c`) without the the uninitialized constant error

Ruby version: 2.6.1
Sidekiq / Pro / Enterprise version(s): 5.2.5

Please include your initializer and any error message with the full backtrace.
```
sidekiq ›› rails c                                                                                              ✭ master
/home/adam/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:76:in `block in load_missing_constant': uninitialized constant Sidekiq::Rails::Application (NameError)
        from /home/adam/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
        from /home/adam/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:76:in `rescue in load_missing_constant'
        from /home/adam/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `load_missing_constant'
        from /home/adam/Desktop/sidekiq/config/application.rb:10:in `<module:Sidekiq>'
        from /home/adam/Desktop/sidekiq/config/application.rb:9:in `<top (required)>'
        from /home/adam/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
        from /home/adam/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
        from /home/adam/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
        from /home/adam/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
        from /home/adam/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
        from /home/adam/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
        from /home/adam/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /home/adam/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/adam/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'

```

Are you using an old version? no
Have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by brasscapon** [comment]
Turns out naming the project `sidekiq` caused issues. (due to naming the config/application.rb module)
