### ISSUE TITLE
undefined method `map!' for nil:NilClass

### ISSUE THREAD

**Issue by moholtzberg** [mperham/sidekiq#4130]
Ruby version: 2.5.1
Sidekiq: 5.2.5

i just deployed my app over to ubuntu 18.04 LTS from my mac and I can run the rails console and server but when i try to start up sidekiq im getting this.

```
$ sidekiq
undefined method `map!' for nil:NilClass
/var/lib/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/cache.rb:12:in `initialize'
/var/lib/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache.rb:46:in `new'
/var/lib/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache.rb:46:in `setup'
/var/lib/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap.rb:24:in `setup'
/var/lib/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/setup.rb:27:in `<top (required)>'
/home/doccontrol/projects/docontrol_app/config/boot.rb:4:in `require'
/home/doccontrol/projects/docontrol_app/config/boot.rb:4:in `<top (required)>'
/home/doccontrol/projects/docontrol_app/config/application.rb:1:in `require_relative'
/home/doccontrol/projects/docontrol_app/config/application.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/var/lib/gems/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/cli.rb:280:in `boot_system'
/var/lib/gems/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/cli.rb:46:in `run'
/var/lib/gems/2.5.0/gems/sidekiq-5.2.5/bin/sidekiq:12:in `<top (required)>'
/usr/local/bin/sidekiq:23:in `load'
/usr/local/bin/sidekiq:23:in `<main>'
```

**Comment by EDalSanto** [comment]
what does `::ActiveSupport::Dependencies.autoload_paths` return in the rails console? the nil exception is coming from here in your version of the bootsnap gem. Have you altered the autoload_paths at all in your Rails config?

**Comment by moholtzberg** [comment]
@EDalSanto this is what i get
```
["/home/doccontrol/projects/docontrol_app/app/assets", "/home/doccontrol/projects/docontrol_app/app/channels", "/home/doccontrol/projects/docontrol_app/app/controllers", "/home/doccontrol/projects/docontrol_app/app/controllers/concerns", "/home/doccontrol/projects/docontrol_app/app/helpers", "/home/doccontrol/projects/docontrol_app/app/jobs", "/home/doccontrol/projects/docontrol_app/app/mailers", "/home/doccontrol/projects/docontrol_app/app/models", "/home/doccontrol/projects/docontrol_app/app/models/concerns", 
"/var/lib/gems/2.5.0/gems/devise-4.6.1/app/controllers", 
"/var/lib/gems/2.5.0/gems/devise-4.6.1/app/helpers", 
"/var/lib/gems/2.5.0/gems/devise-4.6.1/app/mailers", 
"/var/lib/gems/2.5.0/gems/font-awesome-rails-4.7.0.4/app/assets",
"/var/lib/gems/2.5.0/gems/font-awesome-rails-4.7.0.4/app/helpers", "/var/lib/gems/2.5.0/gems/activestorage-5.2.2.1/app/assets", 
"/var/lib/gems/2.5.0/gems/activestorage-5.2.2.1/app/controllers", "/var/lib/gems/2.5.0/gems/activestorage-5.2.2.1/app/controllers/concerns", "/var/lib/gems/2.5.0/gems/activestorage-5.2.2.1/app/javascript", "/var/lib/gems/2.5.0/gems/activestorage-5.2.2.1/app/jobs", 
"/var/lib/gems/2.5.0/gems/activestorage-5.2.2.1/app/models", "/home/doccontrol/projects/docontrol_app/test/mailers/previews"]
```

**Comment by mperham** [comment]
I have no idea what the issue might be but it's deep inside Rails and Bootsnap. It's not a Sidekiq bug (Sidekiq just boots Rails) so you'll need to look elsewhere; I hope you can find some explanation.
