### ISSUE TITLE
Heroku dyno restart causing lost jobs?

### ISSUE THREAD

**Issue by bpirtle-nova** [mperham/sidekiq#4169]
Ruby version:
Sidekiq / Pro / Enterprise version(s): Sidekiq (4.2.10), sidekiq-ent (1.6.0), sidekiq-pro (3.5.2)

```
# config/initializers/sidekiq.rb

Sidekiq.hook_rails!
Sidekiq.remove_delay!

#Sidekiq.default_worker_options = { 'backtrace' => true }

Sidekiq::Client.reliable_push! unless Rails.env.test?

#Second resolution for checking for scheduled jobs, plus reliable scheduler and super fetch
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://REDACTED@nova-redis-prod-east.redis.cache.windows.net:6379', network_timeout: 5 }

  config.average_scheduled_poll_interval = 1 #seconds
  config.super_fetch!
  config.reliable_scheduler!

  config.periodic do |mgr|
    mgr.register('* * * * *', HubspotCronWorker)
    mgr.register('* * * * *', NotificationCronWorker)
    #mgr.register('* * * * *', PersonalizationCronWorker)
    mgr.register('* * * * *', SendCronWorker)
    mgr.register('* * * * *', RefreshCronWorker)
  end
end

Sidekiq::Limiter.configure do |config|
  # job is the job hash, 'overrated' is the number of times we've failed due to rate limiting
  # limiter is the associated limiter that raised the OverLimit error
  # https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting
  # https://github.com/mperham/sidekiq/issues/2168

  config.backoff = ->(limiter, job) do
    rand(80..100).to_f / 100 * (job['overrated'] ** 1.1)
  end
end
```
Here is the error w/ stacktrace on dyno shutdown:
SocketError · getaddrinfo: Name or service not known
```

vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis/connection/ruby.rb:229:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis/connection/ruby.rb:229:in `connect'
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis/connection/ruby.rb:313:in `connect'
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:336:in `establish_connection'
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:101:in `block in connect'
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:293:in `with_reconnect'
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:100:in `connect'
    from vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/redis.rb:105:in `connect'
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:364:in `ensure_connected'
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:221:in `block in process'
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:306:in `logging'
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:220:in `process'
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:120:in `call'
    from vendor/bundle/ruby/2.1.0/gems/scout_apm-2.4.4/lib/scout_apm/instruments/redis.rb:32:in `block in call_with_scout_instruments'
    from vendor/bundle/ruby/2.1.0/gems/scout_apm-2.4.4/lib/scout_apm/tracer.rb:35:in `instrument'
    from vendor/bundle/ruby/2.1.0/gems/scout_apm-2.4.4/lib/scout_apm/instruments/redis.rb:31:in `call_with_scout_instruments'
    from vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/redis.rb:69:in `call'
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis.rb:2399:in `block in _eval'
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
    from vendor/ruby-2.1.3/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis.rb:2398:in `_eval'
    from vendor/bundle/ruby/2.1.0/gems/redis-3.3.3/lib/redis.rb:2450:in `evalsha'
    from vendor/bundle/ruby/2.1.0/gems/sidekiq-ent-1.6.0/lib/sidekiq-ent/scripting.rb:23:in `block in call'
    from vendor/bundle/ruby/2.1.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
    from vendor/bundle/ruby/2.1.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
    from vendor/bundle/ruby/2.1.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
    from vendor/bundle/ruby/2.1.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
    from vendor/bundle/ruby/2.1.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
    from vendor/bundle/ruby/2.1.0/gems/sidekiq-ent-1.6.0/lib/sidekiq-ent/scripting.rb:22:in `call'
    from vendor/bundle/ruby/2.1.0/gems/sidekiq-ent-1.6.0/lib/sidekiq-ent/senate.rb:140:in `update_leader'
    from vendor/bundle/ruby/2.1.0/gems/sidekiq-ent-1.6.0/lib/sidekiq-ent/senate.rb:122:in `election'
    from vendor/bundle/ruby/2.1.0/gems/sidekiq-ent-1.6.0/lib/sidekiq-ent/senate.rb:106:in `cycle'
    from vendor/bundle/ruby/2.1.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
    from vendor/bundle/ruby/2.1.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'

```

The main problem here is that this job never came back into the queueing system and so after 3 days of waiting we just re-created it. Looks like some kind of intermittent network issue caused a redis error?

**Comment by mperham** [comment]
Two things:

1. Your versions are out of date and [several Batch bugs have been fixed](https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md) since those versions.  Please run `bundle up sidekiq-ent`.  Note especially the fix in Pro 3.7.0.
2. This hostname cannot be resolved, `nova-redis-prod-east.redis.cache.windows.net`, so the root cause might be a DNS issue in Azure.  If Redis dies and Azure promotes a replica which is out of date, those jobs won't be there.  But that's pure conjecture, I have no idea what kind of outage or issue you experienced beyond that backtrace.

**Comment by bpirtle-nova** [comment]
Thank you Mike, I have updated to the latest versions.

Our redis setup is pretty simple and there was no log of any downtime on that Azure instance when this happened (We checked), so that seems unlikely.

This event coincided exactly with a dyno reboot, so it's quite possible there was some issue with the network interface availability for a short period during the shutdown window, but there isn't much to go on (That error is all I have).

We've never seen this type of issue outside of a dyno reboot cycle.

**Comment by mperham** [comment]
When I asked about Azure downtime, I mean DNS resolution.  That's the error you saw.  Azure's DNS servers could have blipped.

Oh, and it's possible that backtrace is a red herring.  The leader election code is an endless loop which tries to take/keep leadership in Redis so any errors will be logged and ignored; it'll just retry on the next cycle.  It will have nothing to do with job persistence.  Are there any other backtraces?

That bugfix in Pro 3.7.0 was specifically triggered by shutdown but I'm not convinced it's relevant here. I still don't see a root issue.

**Comment by bpirtle-nova** [comment]
Unfortunately I haven't been able to find any more information on this and as I haven't seen this issue again since, will close this.
