### ISSUE TITLE
Sidekiq-Ent 1.8.1 incompatible with sidekiq master

### ISSUE THREAD

**Issue by betesh** [mperham/sidekiq#4171]
```
$ bundle exec sidekiq
2019-05-21T21:14:37.684Z pid=17979 tid=9vk1n INFO: Running in ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
2019-05-21T21:14:37.684Z pid=17979 tid=9vk1n INFO: Sidekiq Pro 4.0.5 / Sidekiq Enterprise 1.8.1, commercially licensed.
2019-05-21T21:14:37.684Z pid=17979 tid=9vk1n INFO: Booting Sidekiq 6.0.0.pre1 with redis options {:id=>"Sidekiq-server-PID-17979", :url=>nil}
2019-05-21T21:14:37.685Z pid=17979 tid=9vk1n WARN: Sidekiq 6.0 will require Redis 4.0+, you are using Redis v3.0.6
2019-05-21T21:14:37.687Z pid=17979 tid=9vk1n WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"startup"}
2019-05-21T21:14:37.693Z pid=17979 tid=9vk1n WARN: NameError: uninitialized constant Sidekiq::CLI::PROCTITLES
Did you mean?  Sidekiq::Process
2019-05-21T21:14:37.693Z pid=17979 tid=9vk1n WARN: 
~/.rvm/gems/ruby-2.5.5/gems/sidekiq-ent-1.8.1/lib/sidekiq-ent/election.rb:9:in `block (2 levels) in <top (required)>'
~/.rvm/gems/ruby-2.5.5/bundler/gems/sidekiq-8cf0fb111bba/lib/sidekiq/util.rb:61:in `block in fire_event'
~/.rvm/gems/ruby-2.5.5/bundler/gems/sidekiq-8cf0fb111bba/lib/sidekiq/util.rb:60:in `each'
~/.rvm/gems/ruby-2.5.5/bundler/gems/sidekiq-8cf0fb111bba/lib/sidekiq/util.rb:60:in `fire_event'
~/.rvm/gems/ruby-2.5.5/bundler/gems/sidekiq-8cf0fb111bba/lib/sidekiq/cli.rb:82:in `run'
~/.rvm/gems/ruby-2.5.5/bundler/gems/sidekiq-8cf0fb111bba/bin/sidekiq:12:in `<top (required)>'
~/.rvm/gems/ruby-2.5.5/bin/sidekiq:23:in `load'
~/.rvm/gems/ruby-2.5.5/bin/sidekiq:23:in `<main>'
~/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
~/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
```

Ruby version: 2.5.5
Sidekiq / Pro / Enterprise version(s): Enterprise 1.8.1

**Comment by mperham** [comment]
Correct, master is Sidekiq 6.0.  Please run a released version, like 5.2.7.

**Comment by olegantonyan** [comment]
6.3 is already released, but enterprise version still throws 
```
2022-01-10T18:20:46.115Z pid=11906 tid=f2a WARN: NameError: uninitialized constant Sidekiq::CLI::PROCTITLES
2022-01-10T18:20:46.115Z pid=11906 tid=f2a WARN: /home/oleg/.rbenv/versions/2.7.4/lib64/ruby/gems/2.7.0/gems/sidekiq-ent-1.8.1/lib/sidekiq-ent/election.rb:9:in `block (2 levels) in <top (required)>'
/home/oleg/.rbenv/versions/2.7.4/lib64/ruby/gems/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/util.rb:87:in `block in fire_event'
```
Is this by design or something is wrong on my end?

**Comment by mperham** [comment]
You’ve upgraded the Sidekiq gem independent of sidekiq-ent. Don’t do that.
Just run “bundle up sidekiq-ent”.

**Comment by olegantonyan** [comment]
Ok, thanks, that worked!
