### ISSUE TITLE
Failed startup: can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by npflood** [mperham/sidekiq#4189]
Ruby version: **2.4.5**
Sidekiq / Pro / Enterprise version(s): **5.2.7**

I am increasingly getting this error upon Sidekiq startup: 

```
can't add a new key into hash during iteration
```
I get this message, and the stack trace below, and the program hangs, it doesn't exit.

**NOTE:** This doesn't happen EVERY time, but it happens __more than__ 50% of the time.

## Stack Trace:
```
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/railties-5.2.3/lib/rails/application/default_middleware_stack.rb:60:in `block in build_stack'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:47:in `initialize'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/railties-5.2.3/lib/rails/application/default_middleware_stack.rb:15:in `new'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/railties-5.2.3/lib/rails/application/default_middleware_stack.rb:15:in `build_stack'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/railties-5.2.3/lib/rails/application.rb:576:in `default_middleware_stack'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/railties-5.2.3/lib/rails/engine.rb:508:in `block in app'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/railties-5.2.3/lib/rails/engine.rb:506:in `synchronize'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/railties-5.2.3/lib/rails/engine.rb:506:in `app'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/railties-5.2.3/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/share/ruby/2.4/tsort.rb:228:in `block in tsort_each'
/usr/share/ruby/2.4/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/share/ruby/2.4/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/share/ruby/2.4/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/share/ruby/2.4/tsort.rb:347:in `each'
/usr/share/ruby/2.4/tsort.rb:347:in `call'
/usr/share/ruby/2.4/tsort.rb:347:in `each_strongly_connected_component'
/usr/share/ruby/2.4/tsort.rb:226:in `tsort_each'
/usr/share/ruby/2.4/tsort.rb:205:in `tsort_each'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/srv/www/echocommunity/releases/20190607171746/config/environment.rb:5:in `<top (required)>'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/sidekiq-5.2.7/lib/sidekiq/cli.rb:288:in `require'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/sidekiq-5.2.7/lib/sidekiq/cli.rb:288:in `boot_system'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/sidekiq-5.2.7/lib/sidekiq/cli.rb:46:in `run'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/gems/sidekiq-5.2.7/bin/sidekiq:12:in `<top (required)>'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/bin/sidekiq:23:in `load'
/srv/www/echocommunity/shared/vendor/bundle/ruby/2.4/bin/sidekiq:23:in `<main>'
```

**Comment by mperham** [comment]
Looks like a problem with Rails boot, not something under Sidekiq control. Does it happen with puma or rails console?

**Comment by npflood** [comment]
Console works fine, and I'm having no problems with my unicorn processes. Any idea where in the boot it's having the problem from the error I'm getting, or how I could get a more detailed error message?

**Comment by mperham** [comment]
Post your initializer

**Comment by npflood** [comment]
I'm simply using Sidkiq  with active_job

```Ruby
class Application < Rails::Application

  config.load_defaults 5.1

  config.autoload_paths += Dir[Rails.root.join('app', 'services', '{*/}')]

  config.active_job.queue_adapter = :sidekiq

  config.i18n.available_locales = [:en, :es, :fr, :th, :zh, :km, :id, :vi, :my, :sw, :hi, :ht, :sv, :pt, :de]
  config.ui_locales = [:en, :es, :fr, :th, :zh, :km, :id, :vi, :my, :sw]

  config.i18n.fallbacks = config.i18n.available_locales

  config.exceptions_app = ->(env) { ExceptionController.action(:show).call(env) }

  config.middleware.insert_before 0, Rack::Cors, :debug => true, :logger => (-> { Rails.logger }) do
    allow do
      origins 'http://echo-redesign.site-ym.com'

      resource '*',
        :headers => :any,
        :methods => [:get, :post, :delete, :put, :options, :head],
        :max_age => 0
    end
  end
end
```

**Comment by mperham** [comment]
I meant your Sidekiq.rb initializer. Do you have one?

**Comment by npflood** [comment]
Good point, no I don't have an initializer.

**Comment by mperham** [comment]
```ruby
config.middleware.insert_before 0, Rack::Cors, :debug => true, :logger => (-> { Rails.logger }) do
    allow do
      origins 'http://echo-redesign.site-ym.com'

      resource '*',
        :headers => :any,
        :methods => [:get, :post, :delete, :put, :options, :head],
        :max_age => 0
    end
```

Remove this block and see if it helps.

**Comment by npflood** [comment]
Thank you so much for your assistance so far. I wrapped the call to `initialize!` in my environment.rb file and found the thread that was causing the issue. It looks like NewRelic is causing the problem. I'm looking in to if they have a solution. I don't know why this only manifested itself in Sidekiq, but it does not seem to be a sidekiq issue, other than the fact that the process hangs instead of exiting. When I find out an answer I will update you. Again, thank you so much for your assistance.

**Comment by mperham** [comment]
One question that struck me (I know nothing about your app): why are you setting up Rack middleware inside the Sidekiq process, which does not have a web server?  I would extract that into a puma-specific boot block.

**Comment by npflood** [comment]
This is the applications "/config/application.rb" file which in rails specifies config options for the entire application. The recommendation configure the middleware here comes from the gem documentation: https://github.com/cyu/rack-cors

There are probably several things that the Sidekiq process doesn't need since it is not a webserver. Is there documentation on how to cleanly specify if the code is running inside sidekiq or a web server process.

**Comment by mperham** [comment]
`Sidekiq.server?` will return true if you are running within the Sidekiq process itself.

```ruby
setup_middleware unless Sidekiq.server?
```

**Comment by npflood** [comment]
This is really useful. Thanks! 

And thanks again for engaging with us on this issue. 

For the record we stepped the newrelic_rpm gem back to the version 5.1.0 (the first version that supports Rails 5.2) and the problem immediately disappeared. We'll investigate further to see if we're running some thread-unsafe code that newrelic was exemplifying or if the thread-safety issue is in the gem itself.
