### ISSUE TITLE
Client Middleware configured on the Server is invoked when worker is en queued from rails 

### ISSUE THREAD

**Issue by adilw3nomad** [mperham/sidekiq#4195]
Ruby version: 2.4
Sidekiq Pro ( `sidekiq (5.1.3), sidekiq-pro (4.0.2)`) 

Initializer
``` ruby
if AppConfig.fetch(:redis, nil)
  Sidekiq.configure_server do |config|
    config.redis = {
      url: AppConfig[:redis].fetch(:url, nil),
      password: AppConfig[:redis].fetch(:auth, nil)
    }
  end

  Sidekiq.configure_client do |config|
    config.redis = {
      url: AppConfig[:redis].fetch(:url, nil),
      password: AppConfig[:redis].fetch(:auth, nil)
    }
  end
end

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add Middleware::RecordJob
    chain.add Middleware::CancelDuplicateJobs
  end
end

# The jobs running in the Sidekiq server can themselves push new jobs to Sidekiq, thus acting as clients.
Sidekiq.configure_server do |config|
  config.client_middleware do |chain|
    chain.add Middleware::Test
  end
  config.server_middleware do |chain|
    chain.add Middleware::SetJobStartTime
    chain.add Middleware::RejectCancelledJob
  end
end
```

So my question is about client middleware configured on the server, in this case `Middleware::Test`. This is the contents of that file 

``` ruby 
class Middleware::Test
  def call(worker_class, job, _queue, _redis_pool)
    binding.pry
    yield
  end
  
end
```

From your wiki; 
> The jobs running in the Sidekiq server can themselves push new jobs to Sidekiq, thus acting as clients. You must configure your client middleware within the configure_server block also in that case:

From this what I understood is that if a `WorkerFoo` enques `WorkerBar` in it's `perform` method, 
then middleware configured on the client would act on `WorkerFoo` but not on `WorkerBar`. Server middleware (in my example, `SetJobStartTime` and `RejectCancelledJob`), would act on both. Client middleware configured on the server, in this case `TestScheduledJobs`, would only act on `WorkerBar`. 

However, if I enque `WorkerFoo`, either by using `perform_async` or `perform_at`, from within the rails console, I hit the debugger point in `TestScheduledJobs`, showing that it invokes the client middleware that is on the server, despite being pushed into the redis pool by rails. Why exactly is this happening?

**Comment by mperham** [comment]
A console is a client.  Did you have Test in here and forget to restart the console when you removed it?

```
Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add Middleware::RecordJob
    chain.add Middleware::CancelDuplicateJobs
  end
end
```

**Comment by adilw3nomad** [comment]
No, I specifically made `Test` to test client middleware configured on the server. So it never appeared in the client middleware block at all.

**Comment by adilw3nomad** [comment]
Sorry, I realise i made a typo in my initial post, the class name of the test middleware is `Test` not `TestScheduledJobs`

**Comment by mperham** [comment]
I can't explain.  Get a backtrace from the pry session so I can see the current stack.

**Comment by adilw3nomad** [comment]
Here you go. If you want to to test it out yourself, be warned that you may have to wait a few seconds for the pry point to be hit. 

```
pry(#<Middleware::Test>)> caller
=> ["/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:355:in `eval'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:355:in `evaluate_ruby'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:323:in `handle_line'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:242:in `catch'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:242:in `block in eval'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:241:in `catch'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:241:in `eval'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:77:in `block in repl'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `loop'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `repl'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `block in start'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:61:in `__with_ownership'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:79:in `with_ownership'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `start'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:13:in `start'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/pry_class.rb:192:in `start'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/core_extensions.rb:43:in `pry'",
 "/home/adil/src/mwr/mammoth-v2/app/workers/middleware/test.rb:3:in `call'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-pro-4.0.2/lib/sidekiq/batch/middleware.rb:17:in `call'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/client.rb:210:in `process_single'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/client.rb:71:in `push'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/client.rb:131:in `push'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/scheduled.rb:26:in `block (2 levels) in enqueue_jobs'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/scheduled.rb:15:in `each'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/scheduled.rb:15:in `block in enqueue_jobs'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq.rb:95:in `block in redis'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq.rb:92:in `redis'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/scheduled.rb:14:in `enqueue_jobs'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/scheduled.rb:77:in `enqueue'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/scheduled.rb:68:in `block in start'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'",
 "/home/adil/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'"]
```

**Comment by mperham** [comment]
Your job is scheduled, which means the Sidekiq process enqueues it at a point in the future.  This uses the server's client middleware, which you show containing your Test middleware.  Everything is operating as expected.

**Comment by adilw3nomad** [comment]
Ah I see! So any job scheduled in the future (e.g `SomeWorker.perform_at(5.minutes.since)` will trigger the server's client middleware?

**Comment by mperham** [comment]
Yes, because it is enqueued by the server process.

**Comment by adilw3nomad** [comment]
Mind if I make a PR outlining this in the middleware documentation? Or is it something obvious that most people would understand (I'm fairly new to sidekiq)

**Comment by mperham** [comment]
Sure a PR sounds fine.
