### ISSUE TITLE
Sidekiq 6.0.0 with Enterprise crashes on boot

### ISSUE THREAD

**Issue by geoffharcourt** [mperham/sidekiq#4234]
Ruby version:
Sidekiq / Pro / Enterprise version(s):

6.0.0 / 4.0.5 / 1.8.1

Please include your initializer and any error message with the full backtrace.

Worker processes crash on boot on Heroku with Rails 5.2.3 and Sidekiq 6.0.0.
```
2019-08-30T23:48:28.169890+00:00 app[worker.2]: pid=4 tid=gq00r29a4 INFO: Managing 6 periodic jobs
2019-08-30T23:48:28.174232+00:00 app[worker.2]: I, [2019-08-30T23:48:28.174132 #4]  INFO -- : [Rollbar] Scheduling item
2019-08-30T23:48:28.174333+00:00 app[worker.2]: I, [2019-08-30T23:48:28.174256 #4]  INFO -- : [Rollbar] Sending item
2019-08-30T23:48:28.177989+00:00 app[worker.2]: pid=4 tid=gq00r29a4 INFO: Gained leadership of the cluster
2019-08-30T23:48:28.178056+00:00 app[worker.2]: pid=4 tid=gq00r29a4 DEBUG: Loading Sidekiq Enterprise Lua extensions
2019-08-30T23:48:28.178761+00:00 app[worker.2]: pid=4 tid=gq00rqyqg DEBUG: Tick: [2019-08-30 23:48:28 +0000]
2019-08-30T23:48:28.226829+00:00 app[worker.2]: I, [2019-08-30T23:48:28.226637 #4]  INFO -- : [Rollbar] Success
2019-08-30T23:48:28.226936+00:00 app[worker.2]: I, [2019-08-30T23:48:28.226855 #4]  INFO -- : [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=bf15c4e1-0b53-4613-80a1-cff278f63ff9 (only available if report was successful)
2019-08-30T23:48:28.227064+00:00 app[worker.2]: uninitialized constant Sidekiq::CLI::PROCTITLES
2019-08-30T23:48:28.227068+00:00 app[worker.2]: Did you mean?  Sidekiq::Process
2019-08-30T23:48:28.227095+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-ent-1.8.1/lib/sidekiq-ent/election.rb:9:in `block (2 levels) in <main>'
2019-08-30T23:48:28.227097+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.0/lib/sidekiq/util.rb:61:in `block in fire_event'
2019-08-30T23:48:28.227099+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.0/lib/sidekiq/util.rb:60:in `each'
2019-08-30T23:48:28.227103+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.0/lib/sidekiq/util.rb:60:in `fire_event'
2019-08-30T23:48:28.227105+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.0/lib/sidekiq/cli.rb:75:in `run'
2019-08-30T23:48:28.227107+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.0/bin/sidekiq:12:in `<top (required)>'
2019-08-30T23:48:28.227108+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/bin/sidekiq:23:in `load'
2019-08-30T23:48:28.227110+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/bin/sidekiq:23:in `<top (required)>'
2019-08-30T23:48:28.227111+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
2019-08-30T23:48:28.227113+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
2019-08-30T23:48:28.227114+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
2019-08-30T23:48:28.227116+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
2019-08-30T23:48:28.227118+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2019-08-30T23:48:28.227119+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
2019-08-30T23:48:28.227120+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
2019-08-30T23:48:28.227122+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
2019-08-30T23:48:28.227124+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
2019-08-30T23:48:28.227125+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
2019-08-30T23:48:28.227126+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
2019-08-30T23:48:28.227128+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
2019-08-30T23:48:28.227129+00:00 app[worker.2]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
2019-08-30T23:48:28.227131+00:00 app[worker.2]: /app/bin/bundle:104:in `load'
2019-08-30T23:48:28.227132+00:00 app[worker.2]: /app/bin/bundle:104:in `<main>'
```

Are you using an old version?
Have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
You need to `bundle up sidekiq-ent` and pick up Ent 2.0.
