### ISSUE TITLE
Sidekiq is not running in Heroku dyno and there are no errors in logs

### ISSUE THREAD

**Issue by JohnMerlino2** [mperham/sidekiq#4278]
I am using 4.2.8.rc1, ruby 2.4.7 and Sidekiq 4.2.3. I am using Heroku and I defined a Procfile:

release: bin/bundle exec rake db:seed
web: bin/rails server -p $PORT -e $RAILS_ENV
worker: bin/bundle exec sidekiq --queue=syncer,2 -v

During the deploy to Heroku, I do not notice any errors in the logs. The app runs, the release runs, but it seems that the worker never starts.

heroku logs --ps worker

heroku ps:type release=worker
Scaling dynos on protected-bayou-86516... !
 ▸    No such size as worker.

heroku ps | grep worker

heroku ps -a my-app
Free dyno hours quota remaining this month: 984h 28m (98%)
Free dyno usage for this app: 14h 57m (1%)
For more information on dyno sleeping and how to upgrade, see:
https://devcenter.heroku.com/articles/dyno-sleeping

=== web (Free): bin/rails server -p $PORT -e $RAILS_ENV (1)
web.1: up 2019/09/19 21:40:34 -0400 (~ 23m ago)

It only shows the web worker running. There is no worker output at all. It's as if it was never even spawned or attempted to spawn.

In addition to the Procfile, I did the following:

 heroku ps:scale worker=1
heroku config:set 
REDIS_PROVIDER=redis://h:p88f42d32f10c8508f2367796d4755308fdc3c576a52bee30210df3151ac4403d@ec2-3-215-116-159.compute-1.amazonaws.com:6639
$ heroku config:get REDIS_PROVIDER
redis://h:p88f42d32f10c8508f2367796d4755308fdc3c576a52bee30210df3151ac4403d@ec2-3-215-116-159.compute-1.amazonaws.com:6639

No logs at all from Sidekiq. The only output I get from redis is this:

$ heroku logs | grep redis
2019-09-20T02:15:10+00:00 app[heroku-redis]: source=REDIS addon=redis-fitted-24037 sample#active-connections=2 sample#load-avg-1m=0.06 sample#load-avg-5m=0.055 sample#load-avg-15m=0.07 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664216kB sample#memory-free=12707060kB sample#memory-cached=981008kB sample#memory-redis=329792bytes sample#hit-rate=0.00011444 sample#evicted-keys=0
2019-09-20T02:15:10+00:00 app[heroku-redis]: source=REDIS addon=redis-fitted-24037 sample#active-connections=2 sample#load-avg-1m=0.04 sample#load-avg-5m=0.045 sample#load-avg-15m=0.065 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664216kB sample#memory-free=12707928kB sample#memory-cached=981016kB sample#memory-redis=329792bytes sample#hit-rate=0.00011168 sample#evicted-keys=0

I look at the heroku dashboard and it says the dyno running the worker is ON:

web
bin/rails server -p $PORT -e $RAILS_ENV
ON
worker
bin/bundle exec sidekiq --queue=nylas_syncer,2 -v
ON

Yet the 'worker ps -a' command only shows the web process and not the worker. Due to the fact that there is no output in the logs for the worker, I don't know how to troubleshoot this. On Stackoverflow, some people recommend using REDISTOGO instead of heroku-redis, others recommend adding 'redis' gem manually in Gemfile, even though it is already in Gemfile.lock, others say add a redis.rb initializer file with this content:

$redis = Redis.new(url: ENV["REDIS_URL"])

But I did not have to do this for it to run on local machine. Why am I not getting errors in log?

**Comment by JohnMerlino2** [comment]
Ok, 20 minutes later, now I get errors in log:

$ heroku logs --ps worker
2019-09-20T02:25:44.625770+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:102:in `block in connect'
2019-09-20T02:25:44.625833+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:293:in `with_reconnect'
2019-09-20T02:25:44.625870+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:100:in `connect'
2019-09-20T02:25:44.625906+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:364:in `ensure_connected'
2019-09-20T02:25:44.625947+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:221:in `block in process'
2019-09-20T02:25:44.625972+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:306:in `logging'
2019-09-20T02:25:44.626023+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:220:in `process'
2019-09-20T02:25:44.626153+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:120:in `call'
2019-09-20T02:25:44.626213+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis.rb:1799:in `block in zrangebyscore'
2019-09-20T02:25:44.626246+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis.rb:58:in `block in synchronize'
2019-09-20T02:25:44.626297+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/ruby-2.4.7/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
2019-09-20T02:25:44.626303+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis.rb:58:in `synchronize'
2019-09-20T02:25:44.626350+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis.rb:1798:in `zrangebyscore'
2019-09-20T02:25:44.626387+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:20:in `block (2 levels) in enqueue_jobs'
2019-09-20T02:25:44.626425+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:15:in `each'
2019-09-20T02:25:44.626461+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:15:in `block in enqueue_jobs'
2019-09-20T02:25:44.626481+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:95:in `block in redis'
2019-09-20T02:25:44.626528+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
2019-09-20T02:25:44.626565+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
2019-09-20T02:25:44.626603+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
2019-09-20T02:25:44.626639+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
2019-09-20T02:25:44.626670+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
2019-09-20T02:25:44.626726+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:92:in `redis'
2019-09-20T02:25:44.626761+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:14:in `enqueue_jobs'
2019-09-20T02:25:44.626813+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:77:in `enqueue'
2019-09-20T02:25:44.626820+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:68:in `block in start'
2019-09-20T02:25:44.626860+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
2019-09-20T02:25:44.626918+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'
2019-09-20T02:25:44.628695+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: ERR max number of clients reached
2019-09-20T02:25:44.628732+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:121:in `call'
2019-09-20T02:25:49.248376+00:00 app[worker.1]: 4 TID-grzwv8xvw ERROR: heartbeat: ERR max number of clients reached
2019-09-20T02:25:49.632829+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: ERR max number of clients reached
2019-09-20T02:25:49.632849+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:121:in `call'
2019-09-20T02:25:49.632855+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:102:in `block in connect'
2019-09-20T02:25:49.632886+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:293:in `with_reconnect'
2019-09-20T02:25:49.633160+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:100:in `connect'
2019-09-20T02:25:49.633210+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:364:in `ensure_connected'
2019-09-20T02:25:49.633277+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:221:in `block in process'
2019-09-20T02:25:49.633520+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:306:in `logging'
2019-09-20T02:25:49.633694+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:220:in `process'
2019-09-20T02:25:49.633743+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:120:in `call'
2019-09-20T02:25:49.633806+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis.rb:1799:in `block in zrangebyscore'
2019-09-20T02:25:49.634658+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis.rb:58:in `block in synchronize'
2019-09-20T02:25:49.634708+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/ruby-2.4.7/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
2019-09-20T02:25:49.634754+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis.rb:58:in `synchronize'
2019-09-20T02:25:49.634837+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis.rb:1798:in `zrangebyscore'
2019-09-20T02:25:49.634886+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:20:in `block (2 levels) in enqueue_jobs'
2019-09-20T02:25:49.634932+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:15:in `each'
2019-09-20T02:25:49.635214+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:15:in `block in enqueue_jobs'
2019-09-20T02:25:49.635267+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:95:in `block in redis'
2019-09-20T02:25:49.635348+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
2019-09-20T02:25:49.635400+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
2019-09-20T02:25:49.635477+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
2019-09-20T02:25:49.639684+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
2019-09-20T02:25:49.639740+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
2019-09-20T02:25:49.639932+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:92:in `redis'
2019-09-20T02:25:49.639982+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:14:in `enqueue_jobs'
2019-09-20T02:25:49.640031+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:77:in `enqueue'
2019-09-20T02:25:49.640084+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:68:in `block in start'
2019-09-20T02:25:49.640133+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
2019-09-20T02:25:49.640182+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'
2019-09-20T02:25:49.642820+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: ERR max number of clients reached
2019-09-20T02:25:49.642883+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:121:in `call'
2019-09-20T02:25:54.260024+00:00 app[worker.1]: 4 TID-grzwv8xvw ERROR: heartbeat: ERR max number of clients reached
2019-09-20T02:25:54.652841+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: ERR max number of clients reached
2019-09-20T02:25:54.652963+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:121:in `call'
2019-09-20T02:25:54.653013+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:102:in `block in connect'
2019-09-20T02:25:54.653114+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:293:in `with_reconnect'
2019-09-20T02:25:54.653296+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:100:in `connect'
2019-09-20T02:25:54.653345+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:364:in `ensure_connected'
2019-09-20T02:25:54.653403+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:221:in `block in process'
2019-09-20T02:25:54.653483+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:306:in `logging'
2019-09-20T02:25:54.653540+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:220:in `process'
2019-09-20T02:25:54.653630+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:120:in `call'
2019-09-20T02:25:54.653825+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis.rb:1799:in `block in zrangebyscore'
2019-09-20T02:25:54.653872+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis.rb:58:in `block in synchronize'
2019-09-20T02:25:54.653933+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/ruby-2.4.7/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
2019-09-20T02:25:54.654000+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis.rb:58:in `synchronize'
2019-09-20T02:25:54.654062+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis.rb:1798:in `zrangebyscore'
2019-09-20T02:25:54.654162+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:20:in `block (2 levels) in enqueue_jobs'
2019-09-20T02:25:54.654210+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:15:in `each'
2019-09-20T02:25:54.654349+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:15:in `block in enqueue_jobs'
2019-09-20T02:25:54.654395+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:95:in `block in redis'
2019-09-20T02:25:54.654496+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
2019-09-20T02:25:54.654552+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
2019-09-20T02:25:54.654704+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
2019-09-20T02:25:54.654748+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
2019-09-20T02:25:54.654816+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
2019-09-20T02:25:54.654894+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:92:in `redis'
2019-09-20T02:25:54.654943+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:14:in `enqueue_jobs'
2019-09-20T02:25:54.655060+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:77:in `enqueue'
2019-09-20T02:25:54.655109+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/scheduled.rb:68:in `block in start'
2019-09-20T02:25:54.655406+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
2019-09-20T02:25:54.655471+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'
2019-09-20T02:25:54.657894+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: ERR max number of clients reached
2019-09-20T02:25:54.657953+00:00 app[worker.1]: 4 TID-grzwv8xqc ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.5/lib/redis/client.rb:121:in `call'

**Comment by JohnMerlino2** [comment]
I think because I am using the free heroku-redis, it took some time to start. That's why there were no errors until 20 minutes later.

**Comment by JohnMerlino2** [comment]
Ok so I changed the sidekiq concurrency to 1:

worker: bin/bundle exec sidekiq --queue=nylas_syncer,1 -c 1 -v

And now it seems to load sidekiq:

Starting process with command `bin/bundle exec sidekiq --queue=nylas_syncer,1 -c 1 -v`
2019-09-20T02:38:41.346300+00:00 heroku[worker.1]: State changed from starting to up
2019-09-20T02:38:48.509659+00:00 app[worker.1]: Overwriting existing field commentable_id in class Comment.
2019-09-20T02:38:49.702470+00:00 app[worker.1]: 4 TID-gr9osches INFO: Running in ruby 2.4.7p357 (2019-08-28 revision 67796) [x86_64-linux]
2019-09-20T02:38:49.702520+00:00 app[worker.1]: 4 TID-gr9osches INFO: See LICENSE and the LGPL-3.0 for licensing details.
2019-09-20T02:38:49.702523+00:00 app[worker.1]: 4 TID-gr9osches INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2019-09-20T02:38:49.702549+00:00 app[worker.1]: 4 TID-gr9osches INFO: Booting Sidekiq 4.2.10 with redis options {:url=>nil}
2019-09-20T02:38:49.709120+00:00 app[worker.1]: 4 TID-gr9osches DEBUG: Client Middleware:
2019-09-20T02:38:49.709184+00:00 app[worker.1]: 4 TID-gr9osches DEBUG: Server Middleware: Sidekiq::Middleware::Server::RetryJobs, Sidekiq::Middleware::Server::Logging, Sidekiq::Middleware::Server::ActiveRecord
2019-09-20T02:38:49.709233+00:00 app[worker.1]: 4 TID-gr9osches INFO: Starting processing, hit Ctrl-C to stop
2019-09-20T02:38:49.717828+00:00 app[worker.1]: 4 TID-gr9osches DEBUG: {:queues=>["nylas_syncer"], :labels=>[], :concurrency=>1, :require=>".", :environment=>nil, :timeout=>8, :poll_interval_average=>nil, :average_scheduled_poll_interval=>15, :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x000055fdfdee5560>], :lifecycle_events=>{:startup=>[], :quiet=>[], :shutdown=>[], :heartbeat=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :reloader=>#<Proc:0x000055fdfdf26f10@/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:35>, :executor=>#<Proc:0x000055fdfdf26ee8@/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:36>, :strict=>false, :verbose=>true, :identity=>"worker.1:4:89d211433761", :tag=>"app"}
