### ISSUE TITLE
Job 'at' must be a Numeric timestamp

### ISSUE THREAD

**Issue by OrrYakobi** [mperham/sidekiq#4321]
I am using Ruby 2.5.6, Rails 5.1.7, and Sidekiq 6.0.1

The following argument error, `ArgumentError Job 'at' must be a Numeric timestamp`, is occurring at `vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq/client.rb:225`

For convenience, here's the line that is causing the issue.
`raise(ArgumentError, "Job 'at' must be a Numeric timestamp") if item.key?("at") && !item["at"].is_a?(Numeric)`

**Comment by mperham** [comment]
I need a full backtrace.

**Comment by OrrYakobi** [comment]
```
vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq/client.rb:225:in `normalize_item': Job 'at' must be a Numeric timestamp (ArgumentError)
    from vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq/client.rb:70:in `push'
    from vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq/client.rb:136:in `push'
    from vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq/scheduled.rb:27:in `block (3 levels) in enqueue_jobs'
    from vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq/scheduled.rb:22:in `each'
    from vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq/scheduled.rb:22:in `block (2 levels) in enqueue_jobs'
    from vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq/scheduled.rb:16:in `each'
    from vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq/scheduled.rb:16:in `block in enqueue_jobs'
    from vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq.rb:97:in `block in redis'
    from vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
    from vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
    from vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
    from vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
    from vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
    from vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq.rb:94:in `redis'
    from vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq/scheduled.rb:15:in `enqueue_jobs'
    from vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq/scheduled.rb:78:in `enqueue'
    from vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq/scheduled.rb:70:in `block in start'
    from vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq/util.rb:17:in `watchdog'
    from vendor/bundle/ruby/2.5.0/gems/sidekiq-6.0.1/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

**Comment by mperham** [comment]
Unfortunately that doesn’t tell me much. You’ll need to show me how you are calling perform_in for that job. Somehow bad job data is getting scheduled.

**Comment by OrrYakobi** [comment]
From a high level, what I am doing is this: 
`
array_of_json.in_goups_of(10).each_with_index do |json_group, index|
  Worker.perform_in(index.minutes, json_group)
end
`

would calling 0.minutes pose an issue?

**Comment by fatkodima** [comment]
@OrrYakobi  Can you provide a minimal reproducible test script, which shows a problem?

**Comment by OrrYakobi** [comment]
> @OrrYakobi Can you provide a minimal reproducible test script, which shows a problem?

```
hashes = (1..25).map { |i| {value: i}}

hashes.in_groups_of(10, false).each_with_index do |hash_group, index|
  PutsWorker.perform_in(index.minutes, hash_group)
end


class PutsWorker 
  include Sidekiq::Worker
  
  def perform(hash_group)
    puts hash_group.pluck(hash_group[:value]).join(",")
  end
end
```

NOTE: Downgraded to Sidekiq 6.0.0 and problem stopped

**Comment by mperham** [comment]
```
$ bundle exec rails c
Loading development environment (Rails 6.0.0)
irb(main):001:0> hashes = (1..25).map { |i| {value: i} }
=> [{:value=>1}, {:value=>2}, {:value=>3}, {:value=>4}, {:value=>5}, {:value=>6}, {:value=>7}, {:value=>8}, {:value=>9}, {:value=>10}, {:value=>11}, {:value=>12}, {:value=>13}, {:value=>14}, {:value=>15}, {:value=>16}, {:value=>17}, {:value=>18}, {:value=>19}, {:value=>20}, {:value=>21}, {:value=>22}, {:value=>23}, {:value=>24}, {:value=>25}]
irb(main):002:0> 
irb(main):003:0> hashes.in_groups_of(10, false).each_with_index do |hash_group, index|
irb(main):004:1*   PutsWorker.perform_in(index.minutes, hash_group)
irb(main):005:1> end
Traceback (most recent call last):
        4: from (irb):3
        3: from (irb):3:in `each_with_index'
        2: from (irb):3:in `each'
        1: from (irb):4:in `block in irb_binding'
NameError (uninitialized constant PutsWorker)
Did you mean?  EmptyWorker
```

Please give me an actual working script to reproduce the problem.

**Comment by mperham** [comment]
(Yes, I flipped the code.  No, it did not reproduce the problem.)

**Comment by pharmaceutics** [comment]
Here's a script that reproduces the same problem for `push_bulk`:
https://github.com/pharmaceutics/sidekiq_601_test

The worker works fine on the first try, but raises `Job 'at' must be a Numeric timestamp` on retry.

**Comment by mperham** [comment]
The payload in question:

```
{"class"=>"HardWorker", "args"=>[], "retry"=>true, "queue"=>"default", "jid"=>"ad528f2943cf07d23c344926", "created_at"=>1571155132.64097, "at"=>nil, "enqueued_at"=>1571155132.641137, "error_message"=>"", "error_class"=>"RuntimeError", "failed_at"=>1571155132.647161, "retry_count"=>0}
```

**Comment by mperham** [comment]
First issue is that client.rb line 103 always includes an `at` key, even when the jobs are not being scheduled.

```ruby
copy = normed.merge("args" => args, "jid" => SecureRandom.hex(12), "at" => single_at, "enqueued_at" => Time.now.to_f)
```

**Comment by mperham** [comment]
Thank you @pharmaceutics, your script allowed me to reproduce, debug and verify this fix. 👍🏼
