### ISSUE TITLE
Sidekiq start fails

### ISSUE THREAD

**Issue by Nikhil-Wagh** [mperham/sidekiq#4367]
Ruby version: **`ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin19]`**
Sidekiq / Pro / Enterprise version(s): **`Sidekiq 5.0.5`**
Redis-Server version: **`Redis server v=5.0.5 sha=00000000:0 malloc=libc bits=64 build=31cd6e21ec924b46`**

Unable to start sidekiq.
Backtrace: 
```
2019-11-09T15:17:38.972Z 66523 TID-owl6zxu2c INFO: Running in ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin19]
2019-11-09T15:17:38.973Z 66523 TID-owl6zxu2c INFO: See LICENSE and the LGPL-3.0 for licensing details.
2019-11-09T15:17:38.973Z 66523 TID-owl6zxu2c INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2019-11-09T15:17:38.973Z 66523 TID-owl6zxu2c INFO: Booting Sidekiq 5.0.5 with redis options {:id=>"Sidekiq-server-PID-66523", :url=>nil}
undefined method `grep_v' for #<Array:0x007fcd91e6ddc0>
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/redis-4.1.1/lib/redis.rb:3372:in `block in <class:Redis>'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/redis-4.1.1/lib/redis.rb:288:in `call'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/redis-4.1.1/lib/redis.rb:288:in `block (2 levels) in info'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/redis-4.1.1/lib/redis/client.rb:129:in `call'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/redis-4.1.1/lib/redis.rb:286:in `block in info'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/redis-4.1.1/lib/redis.rb:52:in `block in synchronize'
/Users/xenocide/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/redis-4.1.1/lib/redis.rb:52:in `synchronize'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/redis-4.1.1/lib/redis.rb:285:in `info'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/sidekiq-5.0.5/lib/sidekiq.rb:113:in `block in redis_info'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/sidekiq-5.0.5/lib/sidekiq.rb:95:in `block in redis'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/sidekiq-5.0.5/lib/sidekiq.rb:92:in `redis'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/sidekiq-5.0.5/lib/sidekiq.rb:106:in `redis_info'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/sidekiq-5.0.5/lib/sidekiq/cli.rb:81:in `run'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/gems/sidekiq-5.0.5/bin/sidekiq:12:in `<top (required)>'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/bin/sidekiq:23:in `load'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/bin/sidekiq:23:in `<main>'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/bin/ruby_executable_hooks:24:in `eval'
/Users/xenocide/.rvm/gems/ruby-2.2.5@sample/bin/ruby_executable_hooks:24:in `<main>'
```

I also tried with sidekiq version: **`Sidekiq 5.2.7`**, but got the same error. 
I can't change my ruby version what can I do?

**Comment by nakulpathak3** [comment]
In your Gemfile, try specifying `gem 'redis', '~> 4.1.1'. Looks like the Redis gem dropped [2.2 support with 4.1.2](https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#412). If that doesn't work, try dropping that to 4.0.3. 
Sidekiq can work on 4.0.0+ so either of the above should be fine^.
