### ISSUE TITLE
Sidekiq 5.2.7 stuck on redis process

### ISSUE THREAD

**Issue by aclarembeau** [mperham/sidekiq#4406]
Ruby version:
Sidekiq / Pro / Enterprise version(s):
```
sidekiq (5.2.7)
sidekiq-pro (5.0.0)
sidekiq-throttled (0.11.0)
```

Hi sidekiq team, 

We're currently having some jobs stuck on production in the redis "select" statement. 
Did you already hear about such a similar issue? 
Following the advises of: https://gitlab.com/gitlab-org/gitlab/issues/2264, we've upgraded our redis gem, but, it does not seem to work. Any insight? 

Here is below a TTIN dump of one of our stuck workers. We've got many others in the same case, and, killing the jobs do not seem to solve the problem. 

Thanks a lot 

```
Dec 20 09:36:57 application-production app/worker_incoming.1 4 TID-ow2jw1njw WARN: /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/connection/ruby.rb:68:in `select'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/connection/ruby.rb:68:in `rescue in _read_from_socket'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/connection/ruby.rb:64:in `_read_from_socket'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/connection/ruby.rb:56:in `gets'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/connection/ruby.rb:395:in `read'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:272:in `block in read'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:260:in `io'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:271:in `read'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:141:in `block (3 levels) in call_loop'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:140:in `loop'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:140:in `block (2 levels) in call_loop'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:241:in `block (2 levels) in process'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:384:in `ensure_connected'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:231:in `block in process'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:319:in `logging'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:230:in `process'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:139:in `block in call_loop'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:292:in `with_socket_timeout'
Dec 20 09:36:57 application-production app/worker_incoming.1 /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:138:in `call_loop'
```

**Comment by aclarembeau** [comment]
My bad, I was not reading the TTIN log correctly, the bug was in another place.

**Comment by selivandex** [comment]
What is the bug was about?
