### ISSUE TITLE
user_script:1: attempt to concatenate a nil value

### ISSUE THREAD

**Issue by Hirurg103** [mperham/sidekiq#4425]
Ruby version: ruby 2.4.2p198 (2017-09-14 revision 59899) [i386-linux-gnu]
Sidekiq / Pro / Enterprise version(s): 5.1.3

```ruby
# config/initializers/sidekiq.rb
redis_connection = {
  host: Settings.redis.host,
  password: Settings.redis.password,
  driver: :hiredis,
  namespace: Rails.env
}

Sidekiq.configure_client do |config|
  config.redis = redis_connection
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware
  end
end

Sidekiq.configure_server do |config|
  MAX_RETRY_ATTEMPTS = 25

  # context['retry'] - Bool or Fixnum. http://bit.ly/1QthahG
  def retry_limit_reached(args)
    return args['retry_count'] >= args['retry'] if args['retry'].is_a?(Fixnum)
    return args['retry_count'] >= MAX_RETRY_ATTEMPTS if args['retry'] == true
    true
  end

  config.redis = redis_connection
  config.error_handlers << proc do |ex,context|
    Airbrake.notify(ex, context) if retry_limit_reached(context)
  end

  config.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware

    # Remove after https://github.com/rails/rails/pull/28867 will be merged
    chain.add Sidekiq::DisableQueryCacheMiddleware
  end
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware
  end
end
```
### Error backtrace from logs/sidekiq.log

```
2020-01-11T09:16:40.477Z 3779 TID--awk5ht ERROR: Error fetching job: ERR Error running script (call to f_0ab965f5b2899a2dec38dec41fff8c97f7a33ee9): @user_script:1: user_script:1: attempt to concatenate a nil value
2020-01-11T09:16:40.477Z 3779 TID--awk5ht WARN: Redis::CommandError: ERR Error running script (call to f_0ab965f5b2899a2dec38dec41fff8c97f7a33ee9): @user_script:1: user_script:1: attempt to concatenate a nil value
2020-01-11T09:16:40.477Z 3779 TID--awk5ht WARN: /home/username/appname/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:119:in `call'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/newrelic_rpm-5.3.0.346/lib/new_relic/agent/instrumentation/redis.rb:74:in `call'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:2448:in `block in _eval'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:2447:in `_eval'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:2499:in `evalsha'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/redis-namespace-1.6.0/lib/redis/namespace.rb:442:in `call_with_namespace'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/redis-namespace-1.6.0/lib/redis/namespace.rb:328:in `method_missing'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/sidekiq-limit_fetch-3.4.0/lib/sidekiq/limit_fetch/global/selector.rb:28:in `block in redis_eval'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq.rb:95:in `block in redis'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq.rb:92:in `redis'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/sidekiq-limit_fetch-3.4.0/lib/sidekiq/limit_fetch/global/selector.rb:26:in `redis_eval'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/sidekiq-limit_fetch-3.4.0/lib/sidekiq/limit_fetch/global/selector.rb:8:in `acquire'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/sidekiq-limit_fetch-3.4.0/lib/sidekiq/limit_fetch/queues.rb:22:in `acquire'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/sidekiq-limit_fetch-3.4.0/lib/sidekiq/limit_fetch.rb:24:in `retrieve_work'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:91:in `get_one'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:101:in `fetch'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:84:in `process_one'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
/home/username/appname/shared/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
/home/username/appname/releases/20191030134330/config/initializers/sidekiq.rb:20: warning: constant ::Fixnum is deprecated
2020-01-11T09:16:46.299Z 3779 TID--awk5ht INFO: Redis is online, 5.821642318 sec downtime
```

I searched the project issues and changelogs for a similar errors but could not find any.

Maybe the reason of this bug is a redis downtime?
Or it is caused by other gems listed in the backtrace (redis-namespace, sidekiq-limit_fetch)?

**Comment by mperham** [comment]
It is a problem with limit fetch.

**Comment by Hirurg103** [comment]
Thank you for the fast reply @mperham !
