### ISSUE TITLE
Sidekiq UI is broken with rails upgrade

### ISSUE THREAD

**Issue by ahmadhasankhan** [mperham/sidekiq#4431]
Ruby version: 2.5.7 and Rails '~> 5.0', '>= 5.0.1'
Sidekiq / Pro / Enterprise version(s):

```
    sidekiq (6.0.4)
      connection_pool (>= 2.2.2)
      rack (>= 2.0.0)
      rack-protection (>= 2.0.0)
      redis (>= 4.1.0)
    sidekiq-ent (2.0.1)
      einhorn (>= 0.7.4)
      sidekiq (>= 6.0.2)
      sidekiq-pro (>= 5.0.1)
    sidekiq-pro (5.0.1)
      concurrent-ruby (>= 1.0.5)
      sidekiq (>= 6.0.1)
```
StackTrace:

```
Started GET "/sidekiq" for 127.0.0.1 at 2020-01-14 21:45:40 +0100

NoMethodError (undefined method `transform_keys' for #<ActionDispatch::Request::Session:0x7fa16b6a15a8 not yet loaded>):

rack (2.1.1) lib/rack/session/abstract/id.rb:212:in `stringify_keys'
rack (2.1.1) lib/rack/session/abstract/id.rb:148:in `update'
rack (2.1.1) lib/rack/session/abstract/id.rb:317:in `prepare_session'
rack (2.1.1) lib/rack/session/abstract/id.rb:276:in `context'
rack (2.1.1) lib/rack/session/abstract/id.rb:271:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.1.1) lib/rack/urlmap.rb:77:in `block in call'
rack (2.1.1) lib/rack/urlmap.rb:61:in `each'
rack (2.1.1) lib/rack/urlmap.rb:61:in `call'
rack (2.1.1) lib/rack/builder.rb:176:in `call'
rollbar (2.23.1) lib/rollbar/middleware/rack/builder.rb:16:in `block in call_with_rollbar'
rollbar (2.23.1) lib/rollbar.rb:145:in `scoped'
rollbar (2.23.1) lib/rollbar/middleware/rack/builder.rb:14:in `call_with_rollbar'
sidekiq (6.0.4) lib/sidekiq/web.rb:104:in `call'
sidekiq (6.0.4) lib/sidekiq/web.rb:109:in `call'
```

I tried fixing it by monkey patching 
```
class Rack::Session::Abstract::SessionHash
  private
  def stringify_keys(other)
    hash = {}
    other = other.to_hash unless other.is_a?(Hash) # hack hack hack
    other.each do |key, value|
      hash[key.to_s] = value
    end
    hash
  end
end
```
And it fixes the `transform_keys` error, however there are many other weird issues like Retry tab is not working and enqueue tab has job counts but when you click on the tab it doesn't show any jobs.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/issues/4422
