### ISSUE TITLE
"undefined method `>' for nil:NilClass" when trying to filter failures in web UI

### ISSUE THREAD

**Issue by geeksam** [mperham/sidekiq#4478]
Ruby version: `ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]`
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.0.5, Pro 5.0.1, Ent 2.0.1

[I also did a `bundle update rack` after seeing a similar issue, which brought that gem to 2.2.2.]

Please include your initializer and any error message with the full backtrace.

Initializer:
```# Disable uniqueness in testing, this has the potential to cause much head scratching...
Sidekiq::Enterprise.unique! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDIS_URL'] }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['REDIS_URL'] }
end

Sidekiq.configure_server do |config|
  config.periodic do |mgr|
    # CRONTAB CHEAT SHEET:
    # * * * * *
    # | | | | |
    # | | | | +---- Day of the Week   (range: 1-7, 1 standing for Monday)
    # | | | +------ Month of the Year (range: 1-12)
    # | | +-------- Day of the Month  (range: 1-31)
    # | +---------- Hour              (range: 0-23)
    # +------------ Minute            (range: 0-59)

  mgr.register('*    * * * *', CronWorkers::EveryMinute,         retry: 0)

  end
end
```

Stacktrace:
```
NoMethodError: undefined method `>' for nil:NilClass
  from (erb):5:in `_erb'
  from erb.rb:901:in `eval'
  from erb.rb:901:in `result'
  from sidekiq/web/action.rb:87:in `_erb'
  from sidekiq/web/action.rb:58:in `erb'
  from sidekiq/web/action.rb:67:in `render'
  from sidekiq/failures/web_extension.rb:90:in `block in registered'
  from sidekiq/web/application.rb:296:in `instance_exec'
  from sidekiq/web/application.rb:296:in `block in call'
  from sidekiq/web/application.rb:294:in `catch'
  from sidekiq/web/application.rb:294:in `call'
  from rack/auth/basic.rb:28:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:26:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/session/abstract/id.rb:269:in `context'
  from rack/session/abstract/id.rb:263:in `call'
  from rack/urlmap.rb:77:in `block in call'
  from rack/urlmap.rb:61:in `each'
  from rack/urlmap.rb:61:in `call'
  from rack/builder.rb:177:in `call'
  from sidekiq/web.rb:104:in `call'
  from sidekiq/web.rb:109:in `call'
  from action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
  from action_dispatch/routing/mapper.rb:48:in `serve'
  from action_dispatch/journey/router.rb:49:in `block in serve'
  from action_dispatch/journey/router.rb:32:in `each'
  from action_dispatch/journey/router.rb:32:in `serve'
  from action_dispatch/routing/route_set.rb:837:in `call'
  from rack/tempfile_reaper.rb:17:in `call'
  from rack/etag.rb:27:in `call'
  from rack/conditional_get.rb:40:in `call'
  from rack/head.rb:14:in `call'
  from action_dispatch/http/content_security_policy.rb:18:in `call'
  from rack/session/abstract/id.rb:269:in `context'
  from rack/session/abstract/id.rb:263:in `call'
  from action_dispatch/middleware/cookies.rb:648:in `call'
  from action_dispatch/middleware/callbacks.rb:27:in `block in call'
  from active_support/callbacks.rb:101:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:26:in `call'
  from action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:32:in `call'
  from action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from rails/rack/logger.rb:38:in `call_app'
  from rails/rack/logger.rb:26:in `block in call'
  from active_support/tagged_logging.rb:80:in `block in tagged'
  from active_support/tagged_logging.rb:28:in `tagged'
  from active_support/tagged_logging.rb:80:in `tagged'
  from rails/rack/logger.rb:26:in `call'
  from action_dispatch/middleware/remote_ip.rb:81:in `call'
  from action_dispatch/middleware/request_id.rb:27:in `call'
  from rack/method_override.rb:24:in `call'
  from rack/runtime.rb:24:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from action_dispatch/middleware/executor.rb:14:in `call'
  from rack/sendfile.rb:113:in `call'
  from action_dispatch/middleware/host_authorization.rb:77:in `call'
  from raven/integrations/rack.rb:51:in `call'
  from rails/engine.rb:526:in `call'
  from puma/configuration.rb:228:in `call'
  from puma/server.rb:681:in `handle_request'
  from puma/server.rb:472:in `process_client'
  from puma/server.rb:328:in `block in run'
  from puma/thread_pool.rb:134:in `block in spawn_thread'
```

Are you using an old version? Nope, updated before submitting issue :)
Have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by geeksam** [comment]
In case it's relevant:  Puma is 4.3.1 and Rails is 6.0.2.1

**Comment by geeksam** [comment]
Derp. Thanks, Mike. :)

**Comment by ptorrsmith** [comment]
Hi @geeksam ... so did you figure out a way to do a fix/workaround for this issue in sidekiq-failures gem?  Having the exact same issue.  Notice sidekiq-failures gem has not had any updates for quite a while, and nothing related in issues log (https://github.com/mhfs/sidekiq-failures/issues)
![image](https://user-images.githubusercontent.com/17134063/114801494-e2a2d980-9def-11eb-9809-1ae28ddb64c1.png)

**Comment by ptorrsmith** [comment]
Ok, this is how we got around this.
The 1.0.0 version of the gem is outdated.
The master branch seems to have fixed it.
So in our gemfile we used the following instead:

`gem "sidekiq-failures", git: "https://github.com/mhfs/sidekiq-failures.git"`

Works now :-)
