### ISSUE TITLE
sidekiq 6.0.5 to 6.0.6 breaks docker/redis connection

### ISSUE THREAD

**Issue by DaveCollinsJr** [mperham/sidekiq#4514]
6.0.6 cannot connect to redis in docker

Ruby version: ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux]
Sidekiq / Pro / Enterprise version(s): 6.0.6 / 5.0.1 / NA

Works fine in 6.0.5 / 5.0.1  and 6.0.4 / 5.0.1

Please include your initializer and any error message with the full backtrace.

Sidekiq initializer:
```
require 'sidekiq/web'

sidekiq_namespace = case Rails.env
when 'production' then 'mps-prod'
else "mps-#{Rails.env}"
end

# To support Travis & docker at same time, try environment Variable first
if ENV["REDIS_URL"].present?
  puts "Setting sidekiq redis url from REDIS_URL ENVIRONMENT VARIABLE: #{ENV["REDIS_URL"]}"
  sidekiq_redis_url = ENV["REDIS_URL"]
end

if sidekiq_redis_url.blank? && Rails.application.credentials.redis_url.present?
  puts "Setting sidekiq redis url from Rails Application Credentials.redis_url: #{Rails.application.credentials.redis_url}"
  sidekiq_redis_url = Rails.application.credentials.redis_url
end

if sidekiq_redis_url.blank?
  puts "WARNING: Falling back to default sidekiq redis://localhost:6379"
  sidekiq_redis_url = 'redis://localhost:6379'
end
Sidekiq::Client.reliable_push! unless (Rails.env.test? || Rails.env.dbwhse?)

Sidekiq.configure_server do |config|
  config.redis = { url: sidekiq_redis_url, namespace: sidekiq_namespace}

  config.super_fetch!
  config.reliable_scheduler!

  config.server_middleware do |chain|
    chain.add MemoryLogger
  end

  database_configuration = Rails.application.config.database_configuration[Rails.env]
  database_configuration.merge! 'pool' => (Sidekiq.options[:concurrency] + 12)
  if ENV['SIDEKIQ_DATABASE_URL'].present?
    puts("(sidekiq.rb) !!! Have a Specified SIDEKIQ_DATABASE_URL: #{ENV['SIDEKIQ_DATABASE_URL']} (Expected only in Docker)")
    database_configuration.merge! 'url' => ENV['SIDEKIQ_DATABASE_URL']
  end
  puts("(sidekiq.rb) database_configuration: #{database_configuration}")
  ActiveRecord::Base.establish_connection(database_configuration)

  schedule_file = "config/sidekiq_schedule.yml"
  if File.exists?(schedule_file) && Sidekiq.server?
    Sidekiq::Cron::Job.load_from_hash! YAML.load_file(schedule_file)
  end
end

Sidekiq.configure_client do |config|
  config.redis = { url: sidekiq_redis_url, namespace: sidekiq_namespace }
end

Sidekiq::Web.set :sessions, false
```

Full backtrace:
```
Step 10/12 : RUN bundle exec rake assets:precompile
 ---> Running in 50a0f04ad8ad
Setting redis uri from Rails Application Credentials.redis_url: redis://redis:6379
Setting sidekiq redis url from Rails Application Credentials.redis_url: redis://redis:6379
I, [2020-03-27T17:13:21.183187 #6]  INFO -- : Writing /SentryLink/public/assets/my_payments-2e43c107f1e91593c64f50284f35f5be8a5f1ebbad81dad38ea1003346b9c71d.js
...
I, [2020-03-27T17:14:50.439435 #6]  INFO -- : Writing /SentryLink/public/assets/fontawesome-webfont-2adefcbc041e7d18fcf2d417879dc5a09997aa64d675b7a3c4b6ce33da13f3fe.woff2
/usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:343:in `establish_connection'
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:106:in `block in connect'
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:306:in `with_reconnect'
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:105:in `connect'
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:381:in `ensure_connected'
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:231:in `block in process'
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:319:in `logging'
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:230:in `process'
  from /usr/local/bundle/gems/appsignal-2.10.1/lib/appsignal/hooks/redis.rb:25:in `block in process'
  from /usr/local/bundle/gems/appsignal-2.10.1/lib/appsignal/helpers/instrumentation.rb:429:in `instrument'
  from /usr/local/bundle/gems/appsignal-2.10.1/lib/appsignal/hooks/redis.rb:24:in `process'
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:196:in `call_pipelined'
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:164:in `block in call_pipeline'
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:306:in `with_reconnect'
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:162:in `call_pipeline'
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis.rb:2416:in `block in pipelined'
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
  from /usr/local/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
  from /usr/local/bundle/gems/redis-4.1.3/lib/redis.rb:2411:in `pipelined'
  from /usr/local/bundle/gems/redis-namespace-1.7.0/lib/redis/namespace.rb:505:in `namespaced_block'
  from /usr/local/bundle/gems/redis-namespace-1.7.0/lib/redis/namespace.rb:300:in `pipelined'
  from /usr/local/bundle/gems/sidekiq-6.0.6/lib/sidekiq/launcher.rb:104:in `block in flush_stats'
  from /usr/local/bundle/gems/sidekiq-6.0.6/lib/sidekiq.rb:97:in `block in redis'
  from /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
  from /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
  from /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
  from /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
  from /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
  from /usr/local/bundle/gems/sidekiq-6.0.6/lib/sidekiq.rb:94:in `redis'
  from /usr/local/bundle/gems/sidekiq-6.0.6/lib/sidekiq/launcher.rb:103:in `flush_stats'
ERROR: Service 'sidekiq' failed to build: The command '/bin/sh -c bundle exec rake assets:precompile' returned a non-zero code: 1
```

Are you using an old version? No - trying to use latest 6.0.6
Have you checked the changelogs to see if your issue has been fixed in a later version?
Maybe fixed in head??

**Comment by mperham** [comment]
The changelog points to the issue.
