### ISSUE TITLE
Request for help with an ActionMailer crash after User is deleted: "SMTP To address may not be blank: []"

### ISSUE THREAD

**Issue by ndbroadbent** [mperham/sidekiq#4530]
Ruby version: 2.6.5
Sidekiq / Pro / Enterprise version(s): 5.2.7
Rails: 5.2.4.2

Hello! So sorry to bother you with an issue that is not really 100% related to Sidekiq per se - it's a combination of Sidekiq + ActionJob + ActionMailer.

I schedule a "welcome" email to go out 5 minutes after a new user signs up. If that user is deleted within those 5 minutes, my app starts crashing with this error (full stack trace below):

```
ArgumentError: SMTP To address may not be blank: []
  from mail/check_delivery_params.rb:21:in `check_to'
  from mail/check_delivery_params.rb:7:in `check'
  from mail/network/delivery_methods/smtp_connection.rb:52:in `deliver!'
  from mail/network/delivery_methods/smtp.rb:101:in `block in deliver!'
  from net/smtp.rb:519:in `start'
  from mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
  from mail/network/delivery_methods/smtp.rb:100:in `deliver!'
  from mail/message.rb:2159:in `do_delivery'
  from mail/message.rb:260:in `block in deliver'
  from action_mailer/base.rb:560:in `block in deliver_mail'
  from active_support/notifications.rb:168:in `block in instrument'
  from active_support/notifications/instrumenter.rb:23:in `instrument'
  from active_support/notifications.rb:168:in `instrument'
  from action_mailer/base.rb:558:in `deliver_mail'
  from mail/message.rb:260:in `deliver'
  from action_mailer/message_delivery.rb:114:in `block in deliver_now'
  from action_mailer/rescuable.rb:17:in `handle_exceptions'
  from action_mailer/message_delivery.rb:113:in `deliver_now'
  from action_mailer/delivery_job.rb:16:in `perform'
  from active_job/execution.rb:39:in `block in perform_now'
  from active_support/callbacks.rb:109:in `block in run_callbacks'
  from raven/integrations/rails/active_job.rb:18:in `capture_and_reraise_with_sentry'
  from raven/integrations/rails/active_job.rb:12:in `block (2 levels) in included'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from i18n.rb:313:in `with_locale'
  from active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
  from active_support/notifications.rb:168:in `block in instrument'
  from active_support/notifications/instrumenter.rb:23:in `instrument'
  from active_support/notifications.rb:168:in `instrument'
  from active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
  from active_job/logging.rb:46:in `block in tag_logger'
  from active_support/tagged_logging.rb:71:in `block in tagged'
  from active_support/tagged_logging.rb:28:in `tagged'
  from active_support/tagged_logging.rb:71:in `tagged'
  from active_job/logging.rb:46:in `tag_logger'
  from active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from active_support/callbacks.rb:136:in `run_callbacks'
  from active_job/execution.rb:38:in `perform_now'
  from active_job/execution.rb:24:in `block in execute'
  from active_support/callbacks.rb:109:in `block in run_callbacks'
  from active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
  from active_support/execution_wrapper.rb:87:in `wrap'
  from active_support/reloader.rb:73:in `block in wrap'
  from active_support/execution_wrapper.rb:83:in `wrap'
  from active_support/reloader.rb:72:in `wrap'
  from active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from active_support/callbacks.rb:136:in `run_callbacks'
  from active_job/execution.rb:22:in `execute'
  from active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
  from sidekiq/processor.rb:192:in `execute_job'
  from sidekiq/processor.rb:165:in `block (2 levels) in process'
  from sidekiq/middleware/chain.rb:128:in `block in invoke'
  from lib/sidekiq/middleware/server/raven_tags_context.rb:17:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/batch/middleware.rb:30:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from raven/integrations/sidekiq.rb:9:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/chain.rb:133:in `invoke'
  from sidekiq/processor.rb:164:in `block in process'
  from sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
  from sidekiq/job_retry.rb:109:in `local'
  from sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
  from sidekiq/rails.rb:43:in `block in call'
  from active_support/execution_wrapper.rb:87:in `wrap'
  from active_support/reloader.rb:73:in `block in wrap'
  from active_support/execution_wrapper.rb:87:in `wrap'
  from active_support/reloader.rb:72:in `wrap'
  from sidekiq/rails.rb:42:in `call'
  from sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
  from sidekiq/processor.rb:250:in `stats'
  from sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
  from sidekiq/job_logger.rb:8:in `call'
  from sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
  from sidekiq/job_retry.rb:74:in `global'
  from sidekiq/processor.rb:125:in `block in dispatch'
  from sidekiq/logging.rb:48:in `with_context'
  from sidekiq/logging.rb:42:in `with_job_hash_context'
  from sidekiq/processor.rb:124:in `dispatch'
  from sidekiq/processor.rb:163:in `process'
  from sidekiq/processor.rb:83:in `process_one'
  from sidekiq/processor.rb:71:in `run'
  from sidekiq/util.rb:16:in `watchdog'
  from sidekiq/util.rb:25:in `block in safe_thread'
```

Sidekiq job string:

```
{"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",
\"wrapped\":\"ActionMailer::DeliveryJob\",\"queue\":\"mailers\",
\"args\":[{\"job_class\":\"ActionMailer::DeliveryJob\",
\"job_id\":\"123\",\"provider_job_id\":null,\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"UserMailer\",\"welcome\",\"deliver_now\",
{\"_aj_globalid\":\"gid://doc-spring/User/1\"}],\"executions\":0,\"locale\":\"en\"}],\"retry\":true,\"jid\":\"123\",\"created_at\":1586859177.3388608,\"enqueued_at\":1586876025.1952877,
\"error_message\":\"SMTP To address may not be blank: []\",
\"error_class\":\"ArgumentError\",\"failed_at\":1586859488.9056344,\"retry_count\":9,
\"retried_at\":1586869187.312979}","job":{
"queue":"mailers","jid":"123","error_message":"SMTP To address may not be blank: []",
"error_class":"ArgumentError","retry_count":9,"created_at":1586859177.3388608,"args":[{"job_id":"123","locale":"en","provider_job_id":null,"queue_name":"mailers","executions":0,"priority":null,"arguments":["UserMailer","welcome","deliver_now","{\"_globalid\":\"gid://doc-spring/User/1\"}"],"job_class":"ActionMailer::DeliveryJob"}],"enqueued_at":1586876025.1952877,"failed_at":1586859488.9056344,"retried_at":1586869187.312979,"retry":true,"wrapped":"ActionMailer::DeliveryJob","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper"},"context":"Job raised exception"}
```

I have some code in my `UserMailer` that attempts to fix this, and I also try to avoid duplicate emails:

```

class UserMailer < ApplicationMailer
  default from: "Me <me@domain>"

  after_action :update_sent_emails

  def welcome(user_or_id, options = {})
    @preview = true if options[:preview]

    @user = if user_or_id.is_a?(User)
      user_or_id
    else
      User.find_by(id: user_or_id)
    end
    if @user.nil? || @user.deleted_at
      return ActionMailer::Base::NullMail.new
    end

    @user.sent_emails ||= []
    if !can_send_email? || @user.sent_emails.include?(action_name.to_s)
      return ActionMailer::Base::NullMail.new
    end

    mail(
      to: @user.email,
      subject: 'Welcome to <Service>!'
    )
  end

  private

  def can_send_email?
    @user&.account &&
      !@user.account.suspended && !@user.account.deleted?
  end

  def update_sent_emails
    return unless can_send_email?
    return if @preview || @user.sent_emails.include?(action_name.to_s)

    unless @user.sent_emails.include?(action_name.to_s)
      @user.sent_emails << action_name.to_s
    end
    @user.save!
  end
end
```

This has been happening for a really long time, and I'm really struggling to figure out how to abort the mailer job if the user can't be found. I can't return `nil` from the `#welcome` method, and I thought `ActionMailer::Base::NullMail.new` might work, but the crash is still happening. (It's also extremely difficult to reproduce with a test case.)

Do you know how I might be able to fix this? Thanks very much for your time!

**Comment by mperham** [comment]
Sidekiq is nowhere in that code or backtrace (except where the processor actually runs the job) so I don't see anything I or it can possibly do.

Mark the user as logically deleted immediately and schedule it for physical deletion 24 hours later?
