### ISSUE TITLE
Redis connection with ssl option (client certificates) errors with sidekiq 6.0.7

### ISSUE THREAD

**Issue by webandtech** [mperham/sidekiq#4535]
Everything works fine up to sidekiq 6.0.6... upgrading to 6.0.7 gives a TypeError: no _dump_data is defined for class OpenSSL::X509::Store exception.

See below for the full stack trace.

Ruby version: 2.6.6
Sidekiq / Pro / Enterprise version(s): sidekiq 6.0.7 pro 5.0.1

We are using redis labs (redis cloud) with SSL enabled (client certs)

Our sidekiq redis options look like this, for example:

```ruby
redis_ssl_ca_store = OpenSSL::X509::Store.new
redis_ssl_ca_store.add_cert(OpenSSL::X509::Certificate.new(ENV['REDIS_TRUSTED_CERT']))
Sidekiq.configure_client do |config|
  config.redis = {
    url: ENV['SIDEKIQ_REDIS_URL'],
    size: Integer(ENV['RAILS_MAX_THREADS'] || 5),
    network_timeout: 5,
    ssl: true,
    ssl_params: {
      cert_store: redis_ssl_ca_store,
      cert: OpenSSL::X509::Certificate.new(ENV['REDIS_CLIENT_CERT']),
      key: OpenSSL::PKey::RSA.new(ENV['REDIS_CLIENT_CERT_KEY'])
    }
  }
end
```

```
2020-04-19T00:24:56.911273+00:00 app[web.1]: [4] Puma starting in cluster mode...
2020-04-19T00:24:56.911288+00:00 app[web.1]: [4] * Version 4.3.3 (ruby 2.6.6-p146), codename: Mysterious Traveller
2020-04-19T00:24:56.911288+00:00 app[web.1]: [4] * Min threads: 5, max threads: 5
2020-04-19T00:24:56.911289+00:00 app[web.1]: [4] * Environment: production
2020-04-19T00:24:56.911291+00:00 app[web.1]: [4] * Process workers: 3
2020-04-19T00:24:56.911325+00:00 app[web.1]: [4] * Preloading application
2020-04-19T00:24:59.433633+00:00 app[web.1]: [4] ! Unable to load application: TypeError: no _dump_data is defined for class OpenSSL::X509::Store
2020-04-19T00:24:59.433738+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.6.0/bin/puma)
2020-04-19T00:24:59.433776+00:00 app[web.1]: TypeError: no _dump_data is defined for class OpenSSL::X509::Store
2020-04-19T00:24:59.433776+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq/redis_connection.rb:100:in `dump'
2020-04-19T00:24:59.433777+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq/redis_connection.rb:100:in `log_info'
2020-04-19T00:24:59.433777+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq/redis_connection.rb:34:in `create'
2020-04-19T00:24:59.433777+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq.rb:135:in `redis='
2020-04-19T00:24:59.433778+00:00 app[web.1]: /app/config/initializers/sidekiq.rb:7:in `block in <main>'
2020-04-19T00:24:59.433779+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq.rb:85:in `configure_client'
2020-04-19T00:24:59.433779+00:00 app[web.1]: /app/config/initializers/sidekiq.rb:7:in `<main>'
2020-04-19T00:24:59.433779+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
2020-04-19T00:24:59.433780+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
2020-04-19T00:24:59.433780+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:319:in `block in load'
2020-04-19T00:24:59.433780+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
2020-04-19T00:24:59.433781+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:319:in `load'
2020-04-19T00:24:59.433781+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/engine.rb:667:in `block in load_config_initializer'
2020-04-19T00:24:59.433781+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/notifications.rb:182:in `instrument'
2020-04-19T00:24:59.433782+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/engine.rb:666:in `load_config_initializer'
2020-04-19T00:24:59.433782+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/engine.rb:624:in `block (2 levels) in <class:Engine>'
2020-04-19T00:24:59.433782+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/engine.rb:623:in `each'
2020-04-19T00:24:59.433782+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/engine.rb:623:in `block in <class:Engine>'
2020-04-19T00:24:59.433783+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `instance_exec'
2020-04-19T00:24:59.433783+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `run'
2020-04-19T00:24:59.433783+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
2020-04-19T00:24:59.433783+00:00 app[web.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
2020-04-19T00:24:59.433783+00:00 app[web.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2020-04-19T00:24:59.433784+00:00 app[web.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
2020-04-19T00:24:59.433784+00:00 app[web.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
2020-04-19T00:24:59.433784+00:00 app[web.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
2020-04-19T00:24:59.433784+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:50:in `each'
2020-04-19T00:24:59.433784+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
2020-04-19T00:24:59.433785+00:00 app[web.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:415:in `call'
2020-04-19T00:24:59.433785+00:00 app[web.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
2020-04-19T00:24:59.433785+00:00 app[web.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
2020-04-19T00:24:59.433785+00:00 app[web.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each'
2020-04-19T00:24:59.433785+00:00 app[web.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `call'
2020-04-19T00:24:59.433786+00:00 app[web.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
2020-04-19T00:24:59.433786+00:00 app[web.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
2020-04-19T00:24:59.433786+00:00 app[web.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
2020-04-19T00:24:59.433786+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:60:in `run_initializers'
2020-04-19T00:24:59.433786+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/application.rb:363:in `initialize!'
2020-04-19T00:24:59.433787+00:00 app[web.1]: /app/config/environment.rb:7:in `<top (required)>'
2020-04-19T00:24:59.433787+00:00 app[web.1]: config.ru:5:in `require_relative'
2020-04-19T00:24:59.433787+00:00 app[web.1]: config.ru:5:in `block in <main>'
2020-04-19T00:24:59.433787+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
2020-04-19T00:24:59.433788+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
2020-04-19T00:24:59.433790+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
2020-04-19T00:24:59.433790+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
2020-04-19T00:24:59.433791+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.3/lib/puma/configuration.rb:321:in `load_rackup'
2020-04-19T00:24:59.433791+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.3/lib/puma/configuration.rb:246:in `app'
2020-04-19T00:24:59.433791+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.3/lib/puma/runner.rb:155:in `load_and_bind'
2020-04-19T00:24:59.433791+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.3/lib/puma/cluster.rb:413:in `run'
2020-04-19T00:24:59.433792+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.3/lib/puma/launcher.rb:172:in `run'
2020-04-19T00:24:59.433792+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.3/lib/puma/cli.rb:80:in `run'
2020-04-19T00:24:59.433792+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.3/bin/puma:10:in `<top (required)>'
2020-04-19T00:24:59.433792+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
2020-04-19T00:24:59.433793+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<top (required)>'
```

**Comment by mperham** [comment]
Take a look at the change log and the last closed issues.

**Comment by webandtech** [comment]
Got it. Somehow missed that in my search (probably user keyboard driver error)
