### ISSUE TITLE
Sidekiq 5.2.8 -- process disappearing / imbalanced workers

### ISSUE THREAD

**Issue by natematykiewicz** [mperham/sidekiq#4573]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.2.8

Please include your initializer and any error message with the full backtrace.
```ruby
Sidekiq.redis = begin
  Rails.env.test? || Rails.env.development? ? { db: 1 } : { url: ENV['SIDEKIQ_REDIS_URL'] }
end
```

Are you using an old version?
Yes, though it's the newest 5.x.

My problem doesn't appear to be resolved in a later change.

A few times recently I've had a problem where I have 4 servers running Sidekiq all processing the same queues. Each server is allowed 14 workers. 3 servers are bored (0 or 1 worker in use) and 1 is at 13 or 14 out of 14 used. This full server then disappears from Sidekiq admin, though looking at the processes on the server, Sidekiq is still running. Eventually, the process shows back up in the list and you see that it hasn't rebooted in a few days. After a few mins, all of the jobs completed and suddenly the servers are back down to not really having much enqueued. The jobs often finish in less than a minute, so seeing them open for multiple minutes is odd. And seeing such an imbalance between servers is especially odd to me. In this same time, I had a few of the same servers fall out of the load balancer because Unicorn (latest version) wasn't responding. I don't really know where to look to debug this. I don't have any errors logged. Load wasn't especially high on the server.

A little information on the jobs (ActiveJob) being performed. The jobs perform HTTP API calls to a web service using Faraday, to sync data to Rails 5.2.0 using ActiveRecord.

I'm not confident that the problem is necessarily Sidekiq's fault, but the imbalance in workers and the server not showing in Sidekiq admin is definitely concerning. Have you ever seen anything like this? Any ideas where to start debugging?

**Comment by mperham** [comment]
Try TTIN and see if that tells you anything.  https://github.com/mperham/sidekiq/wiki/Signals#ttin

**Comment by natematykiewicz** [comment]
@mperham Thanks. I just had a server get full again (though no Unicorns died this time). I didn't see it fall out of the Sidekiq admin page at all, but it was at 14/14 utilization while all others were 0.

Here's a log from the server that had 14/14.

```
2020-05-21T20:58:41.979Z 19615 TID-gpjbkve57 WARN: vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/connection/ruby.rb:69:in `select'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/connection/ruby.rb:69:in `rescue in _read_from_socket'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/connection/ruby.rb:65:in `_read_from_socket'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/connection/ruby.rb:57:in `gets'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/connection/ruby.rb:396:in `read'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:273:in `block in read'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:261:in `io'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:272:in `read'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:125:in `block in call'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:241:in `block (2 levels) in process'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:385:in `ensure_connected'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:231:in `block in process'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:320:in `logging'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:230:in `process'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:125:in `call'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:219:in `block in call_with_timeout'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:293:in `with_socket_timeout'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:218:in `call_with_timeout'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis.rb:1187:in `block in _bpop'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis.rb:51:in `block in synchronize'
/opt/rbenv/rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis.rb:51:in `synchronize'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis.rb:1184:in `_bpop'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis.rb:1229:in `brpop'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/fetch.rb:36:in `block in retrieve_work'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq.rb:97:in `block in redis'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq.rb:94:in `redis'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/fetch.rb:36:in `retrieve_work'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/processor.rb:89:in `get_one'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/processor.rb:99:in `fetch'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/processor.rb:82:in `process_one'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/processor.rb:71:in `run'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/util.rb:16:in `watchdog'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

Am I reading this right? Did it have troubles running a `BRPOP` from our Elasticache?

**Comment by natematykiewicz** [comment]
I was able to scroll back and find what looks like the start of it.

Right before this was successfully processed jobs (processing in 2 seconds or less usually, per the logs).

```
2020-05-21T20:58:41.972Z 19615 TID-gpjbkve57 WARN: Thread TID-gpjbkve57 
2020-05-21T20:58:41.974Z 19615 TID-gpjbkve57 WARN: vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/cli.rb:164:in `backtrace'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/cli.rb:164:in `block (2 levels) in <class:CLI>'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/cli.rb:161:in `each'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/cli.rb:161:in `block in <class:CLI>'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/cli.rb:176:in `handle_signal'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/cli.rb:111:in `launch'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/cli.rb:96:in `run'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/bin/sidekiq:12:in `<top (required)>'
vendor/bundle/ruby/2.5.0/bin/sidekiq:23:in `load'
vendor/bundle/ruby/2.5.0/bin/sidekiq:23:in `<top (required)>'
/opt/rbenv/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:74:in `load'
/opt/rbenv/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/rbenv/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:28:in `run'
/opt/rbenv/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/cli.rb:424:in `exec'
/opt/rbenv/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/rbenv/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/rbenv/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/opt/rbenv/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/cli.rb:27:in `dispatch'
/opt/rbenv/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/opt/rbenv/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/cli.rb:18:in `start'
/opt/rbenv/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/exe/bundle:30:in `block in <top (required)>'
/opt/rbenv/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/opt/rbenv/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/exe/bundle:22:in `<top (required)>'
/opt/rbenv/rbenv/versions/2.5.1/bin/bundle:23:in `load'
/opt/rbenv/rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
2020-05-21T20:58:41.974Z 19615 TID-gpjbkve57 WARN: Thread TID-gpjboonhr 
2020-05-21T20:58:41.974Z 19615 TID-gpjbkve57 WARN: vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:40:in `pop'
vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:40:in `block in <class:RubyThreadLocalVar>'
2020-05-21T20:58:41.974Z 19615 TID-gpjbkve57 WARN: Thread TID-gpjbtrf8r 
2020-05-21T20:58:41.974Z 19615 TID-gpjbkve57 WARN: vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:299:in `sleep'
vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:299:in `block (2 levels) in run'
vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:298:in `loop'
vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:298:in `block in run'
2020-05-21T20:58:41.974Z 19615 TID-gpjbkve57 WARN: Thread TID-gpjcc9gvn heartbeat
2020-05-21T20:58:41.974Z 19615 TID-gpjbkve57 WARN: vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/launcher.rb:130:in `sleep'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/launcher.rb:130:in `start_heartbeat'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/util.rb:16:in `watchdog'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/util.rb:25:in `block in safe_thread'
2020-05-21T20:58:41.974Z 19615 TID-gpjbkve57 WARN: Thread TID-gpjcc9hzv scheduler
2020-05-21T20:58:41.974Z 19615 TID-gpjbkve57 WARN: vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:88:in `sleep'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:88:in `wait'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:88:in `block (2 levels) in pop'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:79:in `loop'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:79:in `block in pop'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:78:in `synchronize'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:78:in `pop'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/scheduled.rb:89:in `wait'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/scheduled.rb:69:in `block in start'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/util.rb:16:in `watchdog'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/util.rb:25:in `block in safe_thread'
2020-05-21T20:58:41.974Z 19615 TID-gpjbkve57 WARN: Thread TID-gpjcc8ozn processor
2020-05-21T20:58:41.974Z 19615 TID-gpjbkve57 WARN: vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/connection/ruby.rb:69:in `select'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/connection/ruby.rb:69:in `rescue in _read_from_socket'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/connection/ruby.rb:65:in `_read_from_socket'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/connection/ruby.rb:57:in `gets'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/connection/ruby.rb:396:in `read'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:273:in `block in read'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:261:in `io'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:272:in `read'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:125:in `block in call'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:241:in `block (2 levels) in process'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:385:in `ensure_connected'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:231:in `block in process'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:320:in `logging'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:230:in `process'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:125:in `call'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:219:in `block in call_with_timeout'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:293:in `with_socket_timeout'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:218:in `call_with_timeout'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis.rb:1187:in `block in _bpop'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis.rb:51:in `block in synchronize'
/opt/rbenv/rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis.rb:51:in `synchronize'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis.rb:1184:in `_bpop'
vendor/bundle/ruby/2.5.0/gems/redis-4.1.4/lib/redis.rb:1229:in `brpop'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/fetch.rb:36:in `block in retrieve_work'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq.rb:97:in `block in redis'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq.rb:94:in `redis'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/fetch.rb:36:in `retrieve_work'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/processor.rb:89:in `get_one'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/processor.rb:99:in `fetch'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/processor.rb:82:in `process_one'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/processor.rb:71:in `run'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/util.rb:16:in `watchdog'
vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq/util.rb:25:in `block in safe_thread'
2020-05-21T20:58:41.975Z 19615 TID-gpjbkve57 WARN: Thread TID-gpjcc8jxj processor
```

**Comment by natematykiewicz** [comment]
We aren't on Sidekiq 6 yet because our Elasticache currently is running Redis 2.8.22. Upgrading the Elasticache (and Sidekiq) is a goal of ours. We just have to figure out how to do it without data loss.

**Comment by mperham** [comment]
That all looks normal.  Post your initializer.

**Comment by natematykiewicz** [comment]
I did in the first post. It's nothing exciting.

```ruby
Sidekiq.redis = begin
  Rails.env.test? || Rails.env.development? ? { db: 1 } : { url: ENV['SIDEKIQ_REDIS_URL'] }
end
```

**Comment by mperham** [comment]
I can't explain your behavior then.

**Comment by natematykiewicz** [comment]
Are the `BRPOP` errors expected?

**Comment by mperham** [comment]
Which error are you speaking of? The TTIN backtraces just show where each thread is stuck.  It is very very normal for a Sidekiq thread to be blocked on Redis, waiting for a job, in BRPOP.

**Comment by natematykiewicz** [comment]
Gotcha. I wasn't sure wha I was looking at. I thought the `BRPOP` lines were errors.

What causes a server to display in the sidekiq admin page. Any ideas where to dig, to find out why this server had a process running, but wasn't listed in the admin page? I feel like that's a key to my problem.

**Comment by natematykiewicz** [comment]
I should also mention, this has happened to 2 different servers today.

**Comment by mperham** [comment]
Every Sidekiq process sends a heartbeat to Redis every 5 seconds. The Busy tab shows current heartbeats. Heartbeats expire after one minute so if a Sidekiq process locks up or if the network to Redis drops for a while, the heartbeat can expire and the process disappear.

Yep, it sounds like you have Mysterious Infrastructure Problems™. I would investigate your Redis network: https://github.com/mperham/sidekiq/wiki/Using-Redis#life-in-the-cloud

**Comment by natematykiewicz** [comment]
This is helpful info. I'm going to dig into that article, and work on upgrading a few things (Ruby, Redis, Sidekiq) to see if I can get rid of this "Mysterious Infrastructure Problem". Thank you for your time! I truly appreciate it and the work you do.
