### ISSUE TITLE
Sidekiq wrong number of arguments

### ISSUE THREAD

**Issue by blaugrana17** [mperham/sidekiq#4610]
Hi all. I'm using Sidekiq for background jobs. Ruby version is 2.5.0 as well as Rails versions is 5.2.1. I'm getting very strange error saying that there's wrong number of arguments passed to the worker despite i send it all correctly. Here's what i get in logs. For database i use Mongodb

```
TakeOffStartWorker.perform_async({id: 11})

class TakeOffStartWorker
  include Sidekiq::Worker
  sidekiq_options backtrace: true, retry: false

  def perform(params)
     logger.info(params)
   end
end

2020-06-27T17:18:59.356Z pid=53729 tid=ovjmcufsd INFO: Booted Rails 5.2.4.3 application in development environment
2020-06-27T17:18:59.356Z pid=53729 tid=ovjmcufsd INFO: Running in ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
2020-06-27T17:18:59.357Z pid=53729 tid=ovjmcufsd INFO: See LICENSE and the LGPL-3.0 for licensing details.
2020-06-27T17:18:59.357Z pid=53729 tid=ovjmcufsd INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2020-06-27T17:18:59.360Z pid=53729 tid=ovjmcufsd INFO: Starting processing, hit Ctrl-C to stop
2020-06-27T17:20:01.228Z pid=53729 tid=ovjmepbtx class=TakeOffStartWorker jid=c86e8a55ecf2773329d4145e INFO: start
2020-06-27T17:20:01.257Z pid=53729 tid=ovjmepbtx class=TakeOffStartWorker jid=c86e8a55ecf2773329d4145e elapsed=0.03 INFO: fail
2020-06-27T17:20:01.258Z pid=53729 tid=ovjmepbtx WARN: {"context":"Job raised exception","job":{"retry":false,"queue":"take_off","class":"TakeOffStartWorker","args":["{\"id\":11}"],"jid":"c86e8a55ecf2773329d4145e","created_at":1593278401.222316,"enqueued_at":1593278401.2230499},"jobstr":"{\"retry\":false,\"queue\":\"take_off\",\"class\":\"TakeOffStartWorker\",\"args\":[\"{\\\"id\\\":11}\"],\"jid\":\"c86e8a55ecf2773329d4145e\",\"created_at\":1593278401.222316,\"enqueued_at\":1593278401.2230499}"}
2020-06-27T17:20:01.258Z pid=53729 tid=ovjmepbtx WARN: ArgumentError: wrong number of arguments (given 1, expected 0)
2020-06-27T17:20:01.258Z pid=53729 tid=ovjmepbtx WARN: /Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/worker.rb:144:in `logger'
/Users/admin/projects/airplan_app_takeoff/app/workers/take_off_start_worker.rb:7:in `perform'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:196:in `execute_job'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:163:in `block in process'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/job_retry.rb:111:in `local'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/rails.rb:43:in `block in call'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.4.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.4.3/lib/active_support/reloader.rb:73:in `block in wrap'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.4.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.4.3/lib/active_support/reloader.rb:72:in `wrap'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/rails.rb:42:in `call'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:257:in `stats'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/job_logger.rb:13:in `call'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/job_retry.rb:78:in `global'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:124:in `block in dispatch'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/logger.rb:10:in `with'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/job_logger.rb:33:in `prepare'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:123:in `dispatch'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:162:in `process'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:78:in `process_one'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:68:in `run'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/util.rb:15:in `watchdog'
/Users/admin/.rvm/gems/ruby-2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/util.rb:24:in `block in safe_thread'

**Comment by natematykiewicz** [comment]
Could always try `spring stop`. Whenever I have a weird unexplainable problem, I restart `spring` (usually comes installed with a Rails app), and everything suddenly works.

**Comment by mperham** [comment]
Yep, I'm not sure what the issue is but it sounds environmental: an old Sidekiq process with old worker code, spring process, etc.
