### ISSUE TITLE
Sidekiq Pro panel inaccessible after upgrading to Rails 6.0.3.2

### ISSUE THREAD

**Issue by dion-c** [mperham/sidekiq#4613]
Ruby version: 2.7.0
Sidekiq / Pro / Enterprise version(s): sidekiq-pro 5.0.1; sidekiq-ent 2.0.1

Please include your initializer and any error message with the full backtrace.
sidekiq.rb
```
# frozen_string_literal: true

require 'sidekiq'
require 'sidekiq/job_logger'
require 'sidekiq/pro/web'

# If you receive a Forbidden error when trying to submit a form
# https://github.com/mperham/sidekiq/wiki/Monitoring#forbidden
Sidekiq::Web.class_eval { use Rack::Protection, except: :http_origin }

if File.exist? Rails.root.join('config/redis.yml')
  Sidekiq.configure_server do |config|
    config.redis = {
      url: Rails.application.config_for(:redis).sidekiq_redis_url
    }
    config.super_fetch!
    config.reliable_scheduler!

    config.on(:quiet) { $shutdown_pending = true }

    config.on(:startup) do
      Sidekiq.schedule =
        YAML.load_file(Rails.root.join('config/sidekiq_scheduler.yml'))
      SidekiqScheduler::Scheduler.instance.reload_schedule!
    end
  end

  Sidekiq.configure_client do |config|
    config.redis = {
      url: Rails.application.config_for(:redis).sidekiq_redis_url
    }
  end

  unless Rails.env.test?
    Sidekiq::Client.reliable_push!
    Sidekiq::Enterprise.unique!
  end
end

Sidekiq::Extensions.enable_delay!
```

error backtrace
```
ArgumentError (unknown keywords: :path, :domain, :expire_after, :secure, :httponly, :defer, :renew, :sidbits, :secure_random, :secret, :coder, :id):
  
redis (4.2.1) lib/redis.rb:836:in `set'
redis-store (1.8.2) lib/redis/store/interface.rb:9:in `set'
redis-store (1.8.2) lib/redis/store/ttl.rb:8:in `set'
redis-store (1.8.2) lib/redis/store/serialization.rb:5:in `block in set'
redis-store (1.8.2) lib/redis/store/serialization.rb:40:in `_marshal'
redis-store (1.8.2) lib/redis/store/serialization.rb:5:in `set'
redis-store (1.8.2) lib/redis/store/namespace.rb:7:in `block in set'
redis-store (1.8.2) lib/redis/store/namespace.rb:144:in `namespace'
redis-store (1.8.2) lib/redis/store/namespace.rb:7:in `set'
redis-rack (2.1.2) lib/rack/session/redis.rb:49:in `block (2 levels) in write_session'
redis-rack (2.1.2) lib/redis/rack/connection.rb:22:in `with'
redis-rack (2.1.2) lib/rack/session/redis.rb:82:in `with'
redis-rack (2.1.2) lib/rack/session/redis.rb:49:in `block in write_session'
redis-rack (2.1.2) lib/rack/session/redis.rb:70:in `with_lock'
redis-rack (2.1.2) lib/rack/session/redis.rb:48:in `write_session'
rack (2.2.3) lib/rack/session/abstract/id.rb:388:in `commit_session'
rack (2.2.3) lib/rack/session/abstract/id.rb:268:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/cookies.rb:648:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
activerecord (6.0.3.2) lib/active_record/migration.rb:567:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
bugsnag (6.13.1) lib/bugsnag/integrations/rack.rb:49:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
web-console (4.0.3) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.3) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.3) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.3) lib/web_console/middleware.rb:17:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
secure_headers (6.3.0) lib/secure_headers/middleware.rb:11:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
webpacker (5.1.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
newrelic_rpm (6.11.0.365) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by mperham** [comment]
There's no Sidekiq code in that backtrace and the issue is not obvious to me; I'm not sure how to help. I would remove this line as this is a hack, not a supported option:

> Sidekiq::Web.class_eval { use Rack::Protection, except: :http_origin }

**Comment by arcreative** [comment]
@mperham What is the non-hack way of doing `except: :http_origin`?  I'm getting errors now that my app is behind an Elastic Load Balancer, and the except option resolved it for me on the application.  I intend to figure out how to keep the module AND have it working eventually, but I need a quick solution for the time being...

**Comment by mperham** [comment]
@arcreative Newer versions of Sidekiq do not use rack-protection at all. Upgrade.

https://github.com/mperham/sidekiq/blob/master/Changes.md#610
