### ISSUE TITLE
Error fetching job: undefined method `retrieve_work' for Sidekiq::Throttled::Fetch:Class

### ISSUE THREAD

**Issue by arent-groebner** [mperham/sidekiq#4614]
The newly released Sidekiq version does not harmonize with the latest Sidekiq-Throttled version:

```
| 19:51:22 sidekiq.1 | 2020-06-30T19:51:22.821Z pid=113 tid=gozh5tbrp INFO: Booting Sidekiq 6.1.0 with redis options {:url=>"redis://redis:6379/0"}
| 19:51:23 sidekiq.1 | 2020-06-30T19:51:23.073Z pid=113 tid=gozh5tbrp INFO: Cron Jobs - add job with name: RecalculationWorker
| 19:51:24 sidekiq.1 | 2020-06-30T19:51:24.393Z pid=113 tid=gozh5tbrp INFO: Booted Rails 5.2.4.3 application in development environment
| 19:51:24 sidekiq.1 | 2020-06-30T19:51:24.393Z pid=113 tid=gozh5tbrp INFO: Running in ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]
| 19:51:24 sidekiq.1 | 2020-06-30T19:51:24.393Z pid=113 tid=gozh5tbrp INFO: See LICENSE and the LGPL-3.0 for licensing details.
| 19:51:24 sidekiq.1 | 2020-06-30T19:51:24.393Z pid=113 tid=gozh5tbrp INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
| 19:51:24 sidekiq.1 | 2020-06-30T19:51:24.457Z pid=113 tid=gozie6889 ERROR: Error fetching job: undefined method `retrieve_work' for Sidekiq::Throttled::Fetch:Class
| 19:51:24 sidekiq.1 | 2020-06-30T19:51:24.457Z pid=113 tid=gozie6889 WARN: NoMethodError: undefined method `retrieve_work' for Sidekiq::Throttled::Fetch:Class
| 19:51:24 sidekiq.1 | 2020-06-30T19:51:24.457Z pid=113 tid=gozie6889 WARN: /usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:83:in `get_one'
| 19:51:24 sidekiq.1 | /usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:95:in `fetch'
| 19:51:24 sidekiq.1 | /usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:77:in `process_one'
| 19:51:25 sidekiq.1 | /usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:68:in `run'
| 19:51:25 sidekiq.1 | /usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/util.rb:15:in `watchdog'
| 19:51:25 sidekiq.1 | /usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Works:**

sidekiq 6.0.7
sidekiq-throttled 0.12.0

**Does not work:**

sidekiq 6.1.0
sidekiq-throttled 0.12.0

**Comment by mperham** [comment]
Correct, is this a Sidekiq issue?

**Comment by mperham** [comment]
Correct, sidekiq-throttled does not work with the new fetch API refactoring. This is their issue to resolve, internal APIs can change over time.

**Comment by arent-groebner** [comment]
OK, so we can close the issue and I will forward the problem to the sidekiq-throttled folks.
