### ISSUE TITLE
NoMethodError: undefined method `bulk_requeue' for Sidekiq::BasicFetch:Class

### ISSUE THREAD

**Issue by mateusluizfb** [mperham/sidekiq#4621]
Ruby version: 2.6.4
Sidekiq / Pro / Enterprise version(s):6.1.0

Please include your initializer and any error message with the full backtrace.

```
Interrupt: Interrupt
  from sidekiq/cli.rb:152:in `block in <class:CLI>'
  from sidekiq/cli.rb:173:in `handle_signal'
  from sidekiq/cli.rb:98:in `launch'
  from sidekiq/cli.rb:83:in `run'
  from bundle/ruby/2.6.0/gems/sidekiq-6.1.0/bin/sidekiq:31:in `<top (required)>'
  from bundle/ruby/2.6.0/bin/sidekiq:23:in `load'
  from bundle/ruby/2.6.0/bin/sidekiq:23:in `<top (required)>'
  from bundler/cli/exec.rb:74:in `load'
  from bundler/cli/exec.rb:74:in `kernel_load'
  from bundler/cli/exec.rb:28:in `run'
  from bundler/cli.rb:463:in `exec'
  from bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  from bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  from bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  from bundler/cli.rb:27:in `dispatch'
  from bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  from bundler/cli.rb:18:in `start'
  from bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
  from bundler/friendly_errors.rb:124:in `with_friendly_errors'
  from bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
  from bin/bundle:104:in `load'
  from bin/bundle:104:in `<main>'
NoMethodError: undefined method `bulk_requeue' for Sidekiq::BasicFetch:Class
  from sidekiq/limit_fetch.rb:30:in `bulk_requeue'
  from sidekiq/launcher.rb:61:in `stop'
  from sidekiq/cron/launcher.rb:36:in `stop'
  from sidekiq/cli.rb:102:in `rescue in launch'
  from sidekiq/cli.rb:93:in `launch'
  from sidekiq/cli.rb:83:in `run'
  from bundle/ruby/2.6.0/gems/sidekiq-6.1.0/bin/sidekiq:31:in `<top (required)>'
  from bundle/ruby/2.6.0/bin/sidekiq:23:in `load'
  from bundle/ruby/2.6.0/bin/sidekiq:23:in `<top (required)>'
  from bundler/cli/exec.rb:74:in `load'
  from bundler/cli/exec.rb:74:in `kernel_load'
  from bundler/cli/exec.rb:28:in `run'
  from bundler/cli.rb:463:in `exec'
  from bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  from bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  from bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  from bundler/cli.rb:27:in `dispatch'
  from bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  from bundler/cli.rb:18:in `start'
  from bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
  from bundler/friendly_errors.rb:124:in `with_friendly_errors'
  from bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
  from bin/bundle:104:in `load'
  from bin/bundle:104:in `<main>'
ADDITIONAL DATA
```

Are you using an old version? No
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mateusluizfb** [comment]
We've been getting this error since the last update

**Comment by mperham** [comment]
It’s a problem with sidekiq-limit_fetch.

**Comment by mateusluizfb** [comment]
Oh, thanks! I'll report there
