### ISSUE TITLE
NoMethodError: undefined method `new' for BigDecimal:Class

### ISSUE THREAD

**Issue by mariogmz** [mperham/sidekiq#4624]
HI! I'm using Sidekiq in a Rails 6.0.3.2 app, each time I try to send my emails using sidekiq, it throws this error, the app is in Heroku with the official redis addon.

Is there something I'm missing inside config, ruby/rails versions?

Also this happens when I go to the dasboard inside the dead section.

Any help would be great

Ruby version: 2.7.1
Sidekiq Version: 6.1.0

Please include your initializer and any error message with the full backtrace.

`config/initializers/sidekiq.rb`
```
unless Rails.env.test?
  redis_url = ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" }

  Sidekiq.configure_server do |config|
    config.redis = { url: redis_url }
  end

  Sidekiq.configure_client do |config|
    config.redis = { url: redis_url }
  end
end

```
Exception backtrace
```
2020-07-02T20:54:03.288319+00:00 app[sidekiq.1]: pid=4 tid=noc WARN: {"context":"Invalid JSON for job","jobstr":"{\"retry\":true,\"queue\":\"mailers\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::MailDeliveryJob\",\"args\":[{\"job_class\":\"ActionMailer::MailDeliveryJob\",\"job_id\":\"9f6c9268-7f91-4f59-9c35-ad4144707bc9\",\"provider_job_id\":null,\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"CreditApplicationMailer\",\"credit_rejected_email\",\"deliver_now\",{\"params\":{\"application_id\":\"f895e48e-8bbf-4280-a989-350feabb6969\",\"_aj_symbol_keys\":[\"application_id\"]},\"args\":[],\"_aj_ruby2_keywords\":[\"params\",\"args\"]}],\"executions\":0,\"exception_executions\":{},\"locale\":\"es\",\"timezone\":\"Guadalajara\",\"enqueued_at\":\"2020-07-02T20:54:03Z\"}],\"jid\":\"a412d148845e21bbb9b82fb7\",\"created_at\":1593723243.275887,\"enqueued_at\":1593723243.2759337}"}
2020-07-02T20:54:03.290534+00:00 app[sidekiq.1]: pid=4 tid=noc WARN: NoMethodError: undefined method `new' for BigDecimal:Class
2020-07-02T20:54:03.290592+00:00 app[sidekiq.1]: pid=4 tid=noc WARN: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.0/lib/sidekiq.rb:180:in `parse'
2020-07-02T20:54:03.290594+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.0/lib/sidekiq.rb:180:in `load_json'
2020-07-02T20:54:03.290594+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:152:in `process'
2020-07-02T20:54:03.290595+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:78:in `process_one'
2020-07-02T20:54:03.290595+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:68:in `run'
2020-07-02T20:54:03.290596+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.0/lib/sidekiq/util.rb:15:in `watchdog'
2020-07-02T20:54:03.290596+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.0/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by mperham** [comment]
It looks like possibly you have an old JSON extension like OJ or yajl-ruby loaded into your app. Remove it.

**Comment by mariogmz** [comment]
@mperham, unfortunately we couldn't remove OJ since one of our project's dependencies requires it, we needed to stay with Ruby 2.6.1 and downgrade to Sidekiq 5, but at the end it worked, thanks!
