### ISSUE TITLE
NotImplementedError: NotImplementedError when using sidekiq_options retry: false with ActiveJob included module

### ISSUE THREAD

**Issue by fabioxgn** [mperham/sidekiq#4665]
Ruby version: 2.6.6
Sidekiq / Pro / Enterprise version(s): 6.1.1

I'm getting this error when I try to set `sidekiq_options retry: false` in an included module. The weird thing is that it only breaks in production, I've replicated the production locally as close as I could and it works on my machine, but in the production server it crashes all jobs with: `NotImplementedError: NotImplementedError`

I've tried including the module with ActiveSupport::Concern and directly, and both crashes with the same error. I have another project that this works fine but with a class instead of a module, but in this project I have multiple classes to inherit from ao I need to use modules.

```ruby
# app/jobs/no_retry_job.rb
module NoRetryJob
  extend ActiveSupport::Concern

  included do
    sidekiq_options retry: false
   end
end

# app/jobs/all_tenants_job.rb
class AllTenantsJob < ActiveJob::Base
  around_perform :switch_tenant

  private

  def switch_tenant
    Apartment::Tenant.each do
      Rails.logger.info "Tenant: #{Apartment::Tenant.current}"
      yield
    end
  end
end

# app/jobs/my_job.rb
class MyJob < AllTenantsJob
  include NoRetryJob

  private

  def perform
     # It breaks when running this job :(
  end
end
```

Please include your initializer and any error message with the full backtrace.

```

pid=8 tid=otgocfdpk WARN: NotImplementedError: NotImplementedError
--
  | n `block (2 levels) in dispatch' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/job_retry.rb:78:in `global'
  | usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:124:in `block in dispatch' /usr/loca
  | /bundle/gems/sidekiq-6.1.1/lib/sidekiq/logger.rb:10:in `with' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidek
  | q/job_logger.rb:33:in `prepare' /usr/local/bundle/gems/sidekiq
  | 6.1.1/lib/sidekiq/processor.rb:123:in `dispatch' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:162:in `process' /
  | sr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:78:in `process_one' /usr/local/bundle/gems/sidekiq-
  | .1.1/lib/sidekiq/processor.rb:68:in `run' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/util.rb:15:in `watchdog' /u
  | r/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/util.rb:24:in `block in safe_thread' `instance_exec' /usr/local
  | bundle/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks' /usr/local/
  | undle/gems/activesupport-6.0.3.2/lib/active_support/ca
  | lbacks.rb:139:in `run_callbacks' /usr/local/bundle/ge
  | s/activejob-6.0.3.2/lib/active_job/execution.rb:23:in `execute' /usr/local/bundle/gems/activejob-6.0.3.2/lib
  | active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/pr
  | cessor.rb:196:in `execute_job' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process' /usr/local/
  | undle/gems/sidekiq-6.1.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke' /usr/local/bundle
  | gems/rollbar-2.27.0/lib/rollbar/plugins/sidekiq/plugin.rb:11:in `call' /usr/local/bundle/gems/sidekiq-6.1.1/
  | ib/sidekiq/middleware/chain.rb:140:in `block in invoke' /usr/local
  | bundle/gems/newrelic_rpm-6.12.0.367/lib/new_relic/agent/instrumentation/sidekiq.rb:35:in `block in call' /usr/local/bu
  | dle/gems/newrelic_rpm-6.12.0.367/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:
  | 76:in `perform_action_with_newrelic_trace' /usr/local/bundle/gems/newrelic_rpm-6.12.0.367/lib/new_relic/agen
  | /instrumentation/sidekiq.rb:30:in `call' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/middleware/ch
  | in.rb:140:in `block in invoke' /usr/local/bundle/gems/apartment-sidekiq-1.2.0/lib/apartment/sidekiq/middleware/ser
  | er.rb:5:in `block in call' /usr/local/bundle/bundler/gems/apartment-f266f73e5883/lib/apartment/adap
  | ers/abstract_adapter.rb:85:in `switch' /usr/local/lib/ruby/2.6.0/forwardable.rb:230:in `switch' /usr/local/b
  | ndle/gems/apartment-sidekiq-1.2.0/lib/apartment/sidekiq/middleware/server.rb:4:in `call' /usr/local/bundle/gems
  | sidekiq-6.1.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke' /usr/local/bundle/gems/sidekiq-6.1.1/l
  | b/sidekiq/middleware/chain.rb:143:in `invoke' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:163:
  | n `block in process' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:136:in `block (6
  | evels) in dispatch' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/job_retry.rb:111:in `local' /usr/local/bun
  | le/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch' /usr/loca
  | /bundle/gems/sidekiq-6.1.1/lib/sidekiq/rails.rb:14:in `block in call' /usr/local/bundle/gems/activesuppor
  | -6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap' /usr/local/bundle/gems/activesuppo
  | t-6.0.3.2/lib/active_support/reloader.rb:72:in `block in wrap' /usr/local/bundle/gems/activesupp
  | rt-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap' /usr/local/bundle/gem
  | /activesupport-6.0.3.2/lib/active_support/reloader.rb:71:in `wrap' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sid
  | kiq/rails.rb:13:in `call' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:131:in `blo
  | k (4 levels) in dispatch' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:257:in `stats' /usr/
  | ocal/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch' /usr/
  | ocal/bundle/gems/sidekiq-6.1.1/lib/sidekiq/job_logger.rb:13:in `call' /usr/local/bundle/
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dis
  | atch' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/job_retry.rb:78:in `global' /usr/local/bundle/gems/si
  | ekiq-6.1.1/lib/sidekiq/processor.rb:124:in `block in dispatch' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sideki
  | /logger.rb:10:in `with' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/job_logger.rb:33:in `pre
  | are' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:123:in `dispatch' /usr/local/b
  | ndle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:162:in `process' /usr/local/bundle/gems/sidekiq-
  | .1.1/lib/sidekiq/processor.rb:78:in `process_one' /usr/local/bundle/gems/sidekiq-6.1.1/l
  | b/sidekiq/processor.rb:68:in `run' /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/util.rb:15:in `watchdog' /
  | sr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/util.rb:24:in `block in safe_thread' `instance_exec'
  | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:139:in `run_callbacks'
  | /usr/local/bundle/gems/activejob-6.0.3.2/lib/active_job/execution.rb:23:in `execute'
  | /usr/local/bundle/gems/activejob-6.0.3.2/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:196:in `execute_job'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
  | /usr/local/bundle/gems/rollbar-2.27.0/lib/rollbar/plugins/sidekiq/plugin.rb:11:in `call'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
  | /usr/local/bundle/gems/newrelic_rpm-6.12.0.367/lib/new_relic/agent/instrumentation/sidekiq.rb:35:in `block in call'
  | /usr/local/bundle/gems/newrelic_rpm-6.12.0.367/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:376:in `perform_action_with_newrelic_trace'
  | /usr/local/bundle/gems/newrelic_rpm-6.12.0.367/lib/new_relic/agent/instrumentation/sidekiq.rb:30:in `call'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
  | /usr/local/bundle/gems/apartment-sidekiq-1.2.0/lib/apartment/sidekiq/middleware/server.rb:5:in `block in call'
  | /usr/local/bundle/bundler/gems/apartment-f266f73e5883/lib/apartment/adapters/abstract_adapter.rb:85:in `switch'
  | /usr/local/lib/ruby/2.6.0/forwardable.rb:230:in `switch'
  | /usr/local/bundle/gems/apartment-sidekiq-1.2.0/lib/apartment/sidekiq/middleware/server.rb:4:in `call'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:163:in `block in process'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/job_retry.rb:111:in `local'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/rails.rb:14:in `block in call'
  | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
  | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
  | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
  | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:71:in `wrap'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/rails.rb:13:in `call'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:257:in `stats'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/job_logger.rb:13:in `call'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/job_retry.rb:78:in `global'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/logger.rb:10:in `with'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/job_logger.rb:33:in `prepare'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:123:in `dispatch'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:162:in `process'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:78:in `process_one'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:68:in `run'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/util.rb:15:in `watchdog'
  | /usr/local/bundle/gems/sidekiq-6.1.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

Are you using an old version?
Have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
I have no clue what's wrong. I don't recall ever seeing an error like this.

**Comment by fabioxgn** [comment]
@mperham I was able to reproduce it in development. This just happens with: `config.cache_classes = true` on Rails. This error is raise by ActiveJob when there's no `perform` method defined: https://github.com/rails/rails/blob/6-0-stable/activejob/lib/active_job/execution.rb#L47

But this just happens if I call: `sidekiq_options retry: false`. I have other included modules that works just fine, but this line of code makes the `perform` not get registered. Debugging where this exception is called, the perform method of my Job is not defined:

```ruby
pry(#<S3VersionFinderJob>)> self.method(:perform).source
=> "    def perform(*)\n      fail NotImplementedError\n    end\n"
```

Any clues about what might be causing it? Maybe it is erroring silently when loading the classes on startup and not defining the methods? 🤔

**Comment by fabioxgn** [comment]
I did more tests and it appears to have nothing to do with the module itself, just adding `sidekiq_options retry: false` to an ActiveJob class causes this error when `config.cache_classes = true`. 🤔

**Comment by fabioxgn** [comment]
Sorry about multiple comments, but the more I did the deeper it gets 👀 . This issue just happens when this gem is active and loads the schedule from `.yml`: https://github.com/ondrejbartas/sidekiq-cron

If I comment this out in my initializer everything works fine.

```ruby
  Sidekiq::Cron::Job.load_from_hash YAML.load_file("config/schedule.yml")
```

**Comment by fabioxgn** [comment]
I'll close this issue as this is a Sidekiq problem, without this gem everything works as expected.

**Comment by mperham** [comment]
Starting in Rails 6 code should not load user classes inside an initializer during boot. I wonder if Sidekiq-cron is constantizing your periodic job classes, leading to issues like this. This is pure speculation on my part though.
