### ISSUE TITLE
Cannot view UI when redis memory is full

### ISSUE THREAD

**Issue by axos88** [mperham/sidekiq#4692]
Ruby version: 2.7.0
Rails version: 5.2.1
Sidekiq / Pro / Enterprise version(s): 6.0.4

If (heroku) redis fills up, it starts throwing OOM errors, which is expected behaviour in such cases.
However if one wants to go to the sidekiq ui to free some memory, by say removing tasks from the queue, the ui doesn't render due to OOM errors.

I'm not sure why sidekiq is trying to write to redis at that point, but it should handle this issue gracefully and correctly render the UI, and give the user the ability to delete stuff until the memory issue is fixed.

```
2020-09-11T17:40:34.547894+00:00 app[web.1]: Started GET "/sidekiq" for 80.98.44.75 at 2020-09-11 17:40:34 +0000
2020-09-11T17:40:34.589191+00:00 app[web.1]: Notifying https://notify.bugsnag.com of Redis::CommandError
2020-09-11T17:40:34.633404+00:00 app[web.1]: 
2020-09-11T17:40:34.633804+00:00 app[web.1]: Redis::CommandError (OOM command not allowed when used memory > 'maxmemory'.):
2020-09-11T17:40:34.633868+00:00 app[web.1]: 
2020-09-11T17:40:34.633929+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-4.1.3/lib/redis/client.rb:126:in `call'
2020-09-11T17:40:34.633930+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-4.1.3/lib/redis.rb:808:in `block in set'
2020-09-11T17:40:34.633931+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
2020-09-11T17:40:34.633931+00:00 app[web.1]: vendor/ruby-2.7.0/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
2020-09-11T17:40:34.633931+00:00 app[web.1]: vendor/ruby-2.7.0/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
2020-09-11T17:40:34.633932+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
2020-09-11T17:40:34.633932+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-4.1.3/lib/redis.rb:804:in `set'
2020-09-11T17:40:34.633933+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-store-1.8.1/lib/redis/store/interface.rb:9:in `set'
2020-09-11T17:40:34.633933+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-store-1.8.1/lib/redis/store/ttl.rb:8:in `set'
2020-09-11T17:40:34.633934+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-store-1.8.1/lib/redis/store/serialization.rb:5:in `block in set'
2020-09-11T17:40:34.633934+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-store-1.8.1/lib/redis/store/serialization.rb:40:in `_marshal'
2020-09-11T17:40:34.633935+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-store-1.8.1/lib/redis/store/serialization.rb:5:in `set'
2020-09-11T17:40:34.633935+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-store-1.8.1/lib/redis/store/namespace.rb:7:in `block in set'
2020-09-11T17:40:34.633943+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-store-1.8.1/lib/redis/store/namespace.rb:128:in `namespace'
2020-09-11T17:40:34.633944+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-store-1.8.1/lib/redis/store/namespace.rb:7:in `set'
2020-09-11T17:40:34.633946+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-rack-2.1.2/lib/rack/session/redis.rb:49:in `block (2 levels) in write_session'
2020-09-11T17:40:34.633947+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-rack-2.1.2/lib/redis/rack/connection.rb:22:in `with'
2020-09-11T17:40:34.633947+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-rack-2.1.2/lib/rack/session/redis.rb:82:in `with'
2020-09-11T17:40:34.633947+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-rack-2.1.2/lib/rack/session/redis.rb:49:in `block in write_session'
2020-09-11T17:40:34.633948+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-rack-2.1.2/lib/rack/session/redis.rb:70:in `with_lock'
2020-09-11T17:40:34.633948+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/redis-rack-2.1.2/lib/rack/session/redis.rb:48:in `write_session'
2020-09-11T17:40:34.633949+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/rack-2.2.0/lib/rack/session/abstract/id.rb:387:in `commit_session'
2020-09-11T17:40:34.633949+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/rack-2.2.0/lib/rack/session/abstract/id.rb:267:in `context'
2020-09-11T17:40:34.633949+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/rack-2.2.0/lib/rack/session/abstract/id.rb:259:in `call'
2020-09-11T17:40:34.633950+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/cookies.rb:670:in `call'
2020-09-11T17:40:34.633950+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
2020-09-11T17:40:34.633951+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
2020-09-11T17:40:34.633951+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
2020-09-11T17:40:34.633952+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/bugsnag-6.13.0/lib/bugsnag/integrations/rack.rb:49:in `call'
2020-09-11T17:40:34.633952+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
2020-09-11T17:40:34.633952+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
2020-09-11T17:40:34.633953+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.1/lib/rails/rack/logger.rb:38:in `call_app'
2020-09-11T17:40:34.633953+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.1/lib/rails/rack/logger.rb:26:in `block in call'
2020-09-11T17:40:34.633953+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
2020-09-11T17:40:34.633954+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/tagged_logging.rb:28:in `tagged'
2020-09-11T17:40:34.633954+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/tagged_logging.rb:71:in `tagged'
2020-09-11T17:40:34.633955+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.1/lib/rails/rack/logger.rb:26:in `call'
2020-09-11T17:40:34.633955+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
2020-09-11T17:40:34.633956+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
2020-09-11T17:40:34.633956+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/rack-2.2.0/lib/rack/method_override.rb:24:in `call'
2020-09-11T17:40:34.633956+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/rack-2.2.0/lib/rack/runtime.rb:22:in `call'
2020-09-11T17:40:34.633957+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
2020-09-11T17:40:34.633957+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
2020-09-11T17:40:34.633963+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/static.rb:127:in `call'
2020-09-11T17:40:34.633963+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/static.rb:127:in `call'
2020-09-11T17:40:34.633963+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/rack-2.2.0/lib/rack/sendfile.rb:110:in `call'
2020-09-11T17:40:34.633964+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/ssl.rb:74:in `call'
2020-09-11T17:40:34.633964+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.1/lib/rails/engine.rb:524:in `call'
2020-09-11T17:40:34.633965+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/puma-4.3.1/lib/puma/configuration.rb:228:in `call'
2020-09-11T17:40:34.633965+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/puma-4.3.1/lib/puma/server.rb:681:in `handle_request'
2020-09-11T17:40:34.633966+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/puma-4.3.1/lib/puma/server.rb:472:in `process_client'
2020-09-11T17:40:34.633966+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/puma-4.3.1/lib/puma/server.rb:328:in `block in run'
2020-09-11T17:40:34.633966+00:00 app[web.1]: vendor/bundle/ruby/2.7.0/gems/puma-4.3.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread'

```

**Comment by mperham** [comment]
Your Redis-backed sessions are the problem, not Sidekiq. Look at the backtrace.
