### ISSUE TITLE
Secret bag encryption

### ISSUE THREAD

**Issue by kenyav** [mperham/sidekiq#4702]
Ruby version: 2.5.0
Rails version: 5.2.1
Sidekiq / Pro / Enterprise version(s): 6.1.2/5.2.0/2.1.2

initializer:
```
Sidekiq::Enterprise::Crypto.enable(active_version: 1) do |version|
  File.open('secret.1.key', 'rb:ASCII-8BIT').read
end
```

When attempting to encrypt the last argument for a worker, `Cryto::Client::call` is invoked but the encryption seemingly does not occur. 

Subsequently, when `Crypto::Server::call` attempts to decrypt a value that hasn't undergone encryption, an error is thrown.

When making a local update to the condition that determines whether or not encryption should occur, the last argument encrypts as expected. I noticed [this](https://github.com/mperham/sidekiq/issues/3368) issue reported a while back, could the updates made there be impacting when encryption occurs?

```
unless last.is_a?(String) && last !~ NON_BASE64 --> if last.is_a?(String) && last !~ NON_BASE64
```

```
class TestWorker
  include Sidekiq::Worker
  sidekiq_options encrypt: true, retry: 1

  def perform(x, y, secret_bag)
    puts "X:#{x}"
    puts "Y:#{y}"
    puts "Secret bag:#{secret_bag}"
  end
end
```

```
2020-09-26T05:07:03.667Z pid=41238 tid=ovhhorrl2 class=TestWorker jid=cb7ec7cbb327132783ca05f3 elapsed=0.013 INFO: fail
2020-09-26T05:07:03.667Z pid=41238 tid=ovhhorrl2 WARN: {"context":"Job raised exception","job":{"retry":1,"queue":"default","encrypt":true,"class":"TestWorker","args":[1,2,"secret"],"jid":"cb7ec7cbb327132783ca05f3","created_at":1601096823.651519,"enqueued_at":1601096823.652509},"jobstr":"{\"retry\":1,\"queue\":\"default\",\"encrypt\":true,\"class\":\"TestWorker\",\"args\":[1,2,\"secret\"],\"jid\":\"cb7ec7cbb327132783ca05f3\",\"created_at\":1601096823.651519,\"enqueued_at\":1601096823.652509}"}
2020-09-26T05:07:03.667Z pid=41238 tid=ovhhorrl2 WARN: ArgumentError: invalid base64
2020-09-26T05:07:03.667Z pid=41238 tid=ovhhorrl2 WARN: /Users/keny/.rbenv/versions/2.5.0/lib/ruby/2.5.0/base64.rb:74:in `unpack1'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/2.5.0/base64.rb:74:in `strict_decode64'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/2.5.0/base64.rb:105:in `urlsafe_decode64'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-ent-2.1.2/lib/sidekiq-ent/encryption.rb:193:in `decrypt'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-ent-2.1.2/lib/sidekiq-ent/encryption.rb:181:in `call'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-pro-5.2.0/lib/sidekiq/batch/middleware.rb:54:in `call'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-ent-2.1.2/lib/sidekiq-ent/limiter/middleware.rb:38:in `call'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rollbar-2.18.0/lib/rollbar/plugins/sidekiq/plugin.rb:11:in `call'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:143:in `invoke'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:163:in `block in process'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/job_retry.rb:111:in `local'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/rails.rb:14:in `block in call'
/Users/keny.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/reloader.rb:73:in `block in wrap'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/reloader.rb:72:in `wrap'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/rails.rb:13:in `call'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:257:in `stats'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/job_logger.rb:13:in `call'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/job_retry.rb:78:in `global'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:124:in `block in dispatch'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/logger.rb:10:in `with'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/job_logger.rb:33:in `prepare'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:123:in `dispatch'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:162:in `process'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:78:in `process_one'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:68:in `run'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/util.rb:15:in `watchdog'
/Users/keny/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by mperham** [comment]
The last argument should be a Hash. That will ensure it is encrypted.

**Comment by kenyav** [comment]
@mperham I see, ok. I'll update that and see how it goes. The wiki page for encryption indicates that [anything](https://github.com/mperham/sidekiq/wiki/Ent-Encryption#configure-your-private-workers) can be passed. Since only a hash is acknowledged, is it ok if I update the wiki?

**Comment by mperham** [comment]
Thanks for the feedback, I've done so. The argument cannot look like a Base64-encoded String. "secret" does; that's why it wasn't working.
