### ISSUE TITLE
NameError: uninitialized constant Sidekiq::Rack

### ISSUE THREAD

**Issue by kjakub** [mperham/sidekiq#4711]
Ruby version: 2.6.0
Rails version: 6.0.3.3
Sidekiq / Pro / Enterprise version(s): 6.1.1 / 5.2.0 / 2.1.2

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

````
NameError: uninitialized constant Sidekiq::Rack
  config.ru:6:in `block in <main>'
  /home/deploy/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
  /home/deploy/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
  /home/deploy/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
  /home/deploy/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
  /home/deploy/bundle/ruby/2.6.0/gems/puma-5.0.0/lib/puma/configuration.rb:330:in `load_rackup'
  /home/deploy/bundle/ruby/2.6.0/gems/puma-5.0.0/lib/puma/configuration.rb:256:in `app'
  /home/deploy/bundle/ruby/2.6.0/gems/puma-5.0.0/lib/puma/runner.rb:131:in `load_and_bind'
  /home/deploy/bundle/ruby/2.6.0/gems/puma-5.0.0/lib/puma/cluster.rb:499:in `run'
  /home/deploy/bundle/ruby/2.6.0/gems/puma-5.0.0/lib/puma/launcher.rb:171:in `run'
  /home/deploy/bundle/ruby/2.6.0/gems/puma-5.0.0/lib/puma/cli.rb:80:in `run'
  /home/deploy/bundle/ruby/2.6.0/gems/puma-5.0.0/bin/puma:10:in `<top (required)>'
  /home/deploy/bundle/ruby/2.6.0/bin/puma:23:in `load'
  /home/deploy/bundle/ruby/2.6.0/bin/puma:23:in `<top (required)>'
````
````
require 'exception_notification/rails'
require 'exception_notification/sidekiq'
require 'periodic_jobs'

# WARNING: Apparently according to Best Practices we shouldn't be rescuing failures in jobs
# https://github.com/mperham/sidekiq/wiki/Error-Handling#best-practices
# and instead allowing the sidekiq error rescue mechanisms handle it
Sidekiq.configure_server do |config|
  config.redis = { url: "redis://localhost:6380/1" }

  config.error_handlers << proc do |exception, ctx_hash|
    ExceptionNotifier.notify_exception(exception, data: { message: ctx_hash })
  end

  config.periodic(&PERIODIC_JOBS)
end

Sidekiq.configure_client do |config|
  config.redis = { url: "redis://localhost:6380/1" }
end

require 'sidekiq/middleware/i18n'
````
````
development:
  :concurrency: 3
  :max_retries: 3
test:
  :concurrency: 3
  :max_retries: 3
production:
  :concurrency: 10
  :max_retries: 3
staging:
  :concurrency: 10
  :max_retries: 3
demo:
  :concurrency: 10
  :max_retries: 3
:queues:
  - ["critical", 100]
  - ["high_priority", 10]
  - ["mailers", 4]
  - ["default", 2]
  - ["low_priority", 1]
  - ["cache", 1]
````

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
Show me your `config.ru` line 6.

Note the Pro 5.2.0 changelog: `Rename Sidekiq::Rack::BatchStatus to Sidekiq::Pro::BatchStatus`

https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md#520

**Comment by kjakub** [comment]
> config.ru

that was it `Sidekiq::Pro::BatchStatus`

thank you
