### ISSUE TITLE
ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context

### ISSUE THREAD

**Issue by bheemreddy181** [mperham/sidekiq#4738]
Ruby version: ruby-2.5.1
Rails version: 5.1.7
Sidekiq / Pro / Enterprise version(s): 5.2.0
Redis version : 4.2.2

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

Initializer 

```
require 'sidekiq'
require 'sidekiq-pro'
require 'sidekiq-ent'
require 'sidekiq-ent/web'
require 'sidekiq-scheduler'
require 'sidekiq/instrument'
require 'sidekiq/middleware/run_in_staging'
require 'active_record_stats/sidekiq_server_middleware'

Sidekiq.redis = {
  driver:     :hiredis,
  url:        ENV['REDIS_HOST'],
  namespace: 'app'
}

Sidekiq::Client.reliable_push! unless Rails.env.test?

# Disable uniqueness in testing, this has the potential to cause much head scratching...
# comment above from (https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs)
Sidekiq::Enterprise.unique! unless Rails.env.test?

Sidekiq.configure_server do |c|
  c.server_middleware do |chain|
    chain.add ActiveRecordStats::SidekiqServerMiddleware
    chain.add Sidekiq::Instrument::ServerMiddleware
    chain.add Sidekiq::Middleware::RunInStaging
  end

  c.client_middleware do |chain|
    chain.add Sidekiq::Instrument::ClientMiddleware
  end

  c.super_fetch!
end

Sidekiq.configure_client do |c|
  c.client_middleware do |chain|
    chain.add Sidekiq::Instrument::ClientMiddleware
  end

  # Ensure schedule is always set in all environments, even if Sidekiq is not running
  Sidekiq.schedule = YAML.load_file(Rails.root.join('config/sidekiq.yml'))[:schedule]
  Sidekiq::Scheduler.reload_schedule!
end

Sidekiq.death_handlers << lambda do |msg, _ex|
  Sidekiq.logger.error "#{msg['class']} failed permanently with message: #{msg['error_class']} -> #{msg['error_message']}"
  Sidekiq.logger.error "Trace: #{msg['error_backtrace']}"
end

Sidekiq.options[:max_retries] = 15

Sidekiq.default_worker_options = {
  queue:           :background_unscheduled,
  # unique_until:    :success, # success is default, will hold lock for scheduled and retry jobs
  unique_for:      10.minutes,
  backtrace:       10
}

Sidekiq::Web.set :session_secret, Rails.application.config.secret_key_base
```

Post sidekiq 6 upgrade from 5 we started seeing errors like below 
```
ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
```
for mostly around sidekiq throttling 

```
  THROTTLE = Sidekiq::Limiter.concurrent('daily_accounting', 100, wait_timeout: 30, lock_timeout: 30)
 THROTTLE.within_limit do
      loan.perform_daily_accounting!(TimePeriod[time_period_id])
    end
```

**Comment by mperham** [comment]
Please include any error message **with the full backtrace**.

**Comment by bheemreddy181** [comment]
Full bactrace here 

```
020-11-16T12:31:42.788Z pid=62951 tid=1le5wn WARN: Redis::CommandError: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
2020-11-16T12:31:42.788Z pid=62951 tid=1le5wn WARN: /export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/redis-4.2.2/lib/redis/client.rb:127:in `call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/ddtrace-0.32.0/lib/ddtrace/contrib/redis/patcher.rb:45:in `block in call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/ddtrace-0.32.0/lib/ddtrace/tracer.rb:270:in `trace'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/ddtrace-0.32.0/lib/ddtrace/contrib/redis/patcher.rb:39:in `call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/redis-4.2.2/lib/redis.rb:2587:in `block in _eval'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/redis-4.2.2/lib/redis.rb:69:in `block in synchronize'
/opt/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/redis-4.2.2/lib/redis.rb:69:in `synchronize'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/redis-4.2.2/lib/redis.rb:2586:in `_eval'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/redis-4.2.2/lib/redis.rb:2638:in `evalsha'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/redis-namespace-1.8.0/lib/redis/namespace.rb:476:in `call_with_namespace'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/redis-namespace-1.8.0/lib/redis/namespace.rb:352:in `block (2 levels) in <class:Namespace>'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-ent-2.1.2/lib/sidekiq-ent/scripting.rb:22:in `block in call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:63:in `block (2 levels) in with'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:62:in `handle_interrupt'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:62:in `block in with'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:59:in `handle_interrupt'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:59:in `with'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-ent-2.1.2/lib/sidekiq-ent/scripting.rb:21:in `call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-ent-2.1.2/lib/sidekiq-ent/limiter/concurrent.rb:147:in `unlock'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-ent-2.1.2/lib/sidekiq-ent/limiter/concurrent.rb:70:in `ensure in within_limit'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-ent-2.1.2/lib/sidekiq-ent/limiter/concurrent.rb:70:in `within_limit'
/export/web/portfolio/2020-11-13--16-32-08/app/workers/notice_of_default_worker.rb:28:in `perform'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:196:in `execute_job'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
/export/web/portfolio/2020-11-13--16-32-08/lib/sidekiq/middleware/run_in_staging.rb:8:in `call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/statsd-instrument-2.0.12/lib/statsd/instrument.rb:284:in `block in measure'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/statsd-instrument-2.0.12/lib/statsd/instrument.rb:53:in `duration'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/statsd-instrument-2.0.12/lib/statsd/instrument.rb:284:in `measure'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-instrument-0.3.1/lib/sidekiq/instrument/middleware/server.rb:10:in `call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/active_record_stats-0.1.5/lib/active_record_stats/sidekiq_server_middleware.rb:16:in `call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-pro-5.2.0/lib/sidekiq/batch/middleware.rb:27:in `call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-ent-2.1.2/lib/sidekiq-ent/unique.rb:148:in `call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-ent-2.1.2/lib/sidekiq-ent/limiter/middleware.rb:38:in `call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/ddtrace-0.32.0/lib/ddtrace/contrib/sidekiq/server_tracer.rb:33:in `block in call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/ddtrace-0.32.0/lib/ddtrace/tracer.rb:270:in `trace'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/ddtrace-0.32.0/lib/ddtrace/contrib/sidekiq/server_tracer.rb:21:in `call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sentry-raven-3.1.1/lib/raven/integrations/sidekiq/cleanup_middleware.rb:7:in `call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:143:in `invoke'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:163:in `block in process'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/job_retry.rb:111:in `local'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/rails.rb:14:in `block in call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/execution_wrapper.rb:85:in `wrap'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/reloader.rb:68:in `block in wrap'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/execution_wrapper.rb:85:in `wrap'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.7/lib/active_support/reloader.rb:67:in `wrap'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/rails.rb:13:in `call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:257:in `stats'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/job_logger.rb:13:in `call'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/job_retry.rb:78:in `global'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:124:in `block in dispatch'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/logger.rb:10:in `with'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/job_logger.rb:33:in `prepare'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:123:in `dispatch'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:162:in `process'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:78:in `process_one'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:68:in `run'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/util.rb:15:in `watchdog'
/export/web/portfolio/2020-11-13--16-32-08/vendor/bundle/ruby/2.5.0/gems/sidekiq-6.1.2/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by mperham** [comment]
I don’t know what’s causing that error. I would recommend removing redis-namespace, per my blog article on mikeperham.com

**Comment by bheemreddy181** [comment]
This one https://www.mikeperham.com/2017/04/10/migrating-from-redis-namespace/ ?

**Comment by mperham** [comment]
The root problem is that a Redis connection being used for pubsub is somehow becoming available in the pool so Sidekiq is trying to use it for a normal operation, leading to Redis complaining. I don’t know how that is happening.

**Comment by mperham** [comment]
Yes.

**Comment by bheemreddy181** [comment]
How does namespace could cause this issue ?

**Comment by mperham** [comment]
I didn't say it was the cause of this issue, only recommended to simplify your system.

**Comment by mperham** [comment]
These errors "PUNSUBSCRIBE" and "can't alloc thread" are two unsolved issues in Sidekiq that people have reported before, you can search the issues. I think "can't alloc thread" is due to some sort of system resource exhaustion, e.g. memory or file handles.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/issues/4029

**Comment by rnubel** [comment]
An update on behalf of @bheemreddy181: it looks like this issue was some sort of race condition caused by Sidekiq being inadvertently hard-stopped. We were still sending `USR1` during deploys instead of the new graceful shutdown signal, `TSTP`. We changed the signal to `TSTP` and no longer see this issue 🙂
