### ISSUE TITLE
sidekiq connection jobs timeout issue

### ISSUE THREAD

**Issue by nirmalayuvasoft213** [mperham/sidekiq#4746]
2020-11-24T07:49:01.980Z 818 TID-ou7iswp26 TimeSpentWorker JID-94c5190617dca34c26937329 INFO: start
2020-11-24T07:49:02.407Z 798 TID-otk3vuz7i TimeSpentWorker JID-7a54288de6dd93c29b40a12b INFO: fail: 5.002 sec
2020-11-24T07:49:02.407Z 798 TID-otk3vuz7i WARN: {"context":"Job raised exception","job":{"class":"TimeSpentWorker","args":[1849,[{"is_moving":true,"uuid":"9aab8837-b97c-473e-81a1-60c044d04566","timestamp":"2020-11-17T18:23:24.158Z","odometer":25019768,"coords":{"latitude":29.7505606,"longitude":-98.7027163,"accuracy":16.4,"speed":1.22,"heading":25.91,"altitude":412.3},"activity":{"type":"walking","confidence":100},"battery":{"is_charging":false,"level":0.84},"extras":{}},{"is_moving":true,"uuid":"3d8bf2f0-595f-4fbc-9f85-bae233c9cd8d","timestamp":"2020-11-17T18:23:29.000Z","odometer":25019768,"coords":{"latitude":29.7506326,"longitude":-98.7026426,"accuracy":17.5,"speed":1.64,"heading":24.47,"altitude":412.9},"activity":{"type":"walking","confidence":100},"battery":{"is_charging":false,"level":0.84},"extras":{}},{"is_moving":true,"uuid":"bbe0d763-fcbc-46d1-8b3b-bb5c2e86a720","timestamp":"2020-11-17T18:23:35.432Z","odometer":25019790,"coords":{"latitude":29.7507018,"longitude":-98.7025691,"accuracy":17.3,"speed":1.24,"heading":27.77,"altitude":412.9},"activity":{"type":"walking","confidence":100},"battery":{"is_charging":false,"level":0.84},"extras":{}},{"is_moving":true,"uuid":"3bb7907b-b739-4e35-b1cb-19833ceb3b9e","timestamp":"2020-11-17T18:25:03.088Z","odometer":25019790,"coords":{"latitude":29.7506894,"longitude":-98.702508,"accuracy":17.1,"speed":1.28,"heading":46.14,"altitude":412.9},"activity":{"type":"still","confidence":100},"battery":{"is_charging":false,"level":0.84},"extras":{}},{"is_moving":true,"uuid":"62f1b49e-2680-4f58-9e2d-11f3e1e786c7","timestamp":"2020-11-17T18:27:23.130Z","odometer":25019818,"coords":{"latitude":29.75062,"longitude":-98.702304,"accuracy":14.1,"speed":1.36,"heading":96.05,"altitude":412.9},"activity":{"type":"still","confidence":100},"battery":{"is_charging":false,"level":0.84},"extras":{}}]],"retry":true,"queue":"default","jid":"7a54288de6dd93c29b40a12b","created_at":1605637645.5036702,"enqueued_at":1606204069.0425522,"error_message":"could not obtain a database connection within 5.000 seconds (waited 5.008 seconds)","error_class":"ActiveRecord::ConnectionTimeoutError","failed_at":1605637950.8471892,"retry_count":19,"retried_at":1606073416.3406177},"jobstr":"{\"class\":\"TimeSpentWorker\",\"args\":[1849,[{\"is_moving\":true,\"uuid\":\"9aab8837-b97c-473e-81a1-60c044d04566\",\"timestamp\":\"2020-11-17T18:23:24.158Z\",\"odometer\":25019768,\"coords\":{\"latitude\":29.7505606,\"longitude\":-98.7027163,\"accuracy\":16.4,\"speed\":1.22,\"heading\":25.91,\"altitude\":412.3},\"activity\":{\"type\":\"walking\",\"confidence\":100},\"battery\":{\"is_charging\":false,\"level\":0.84},\"extras\":{}},{\"is_moving\":true,\"uuid\":\"3d8bf2f0-595f-4fbc-9f85-bae233c9cd8d\",\"timestamp\":\"2020-11-17T18:23:29.000Z\",\"odometer\":25019768,\"coords\":{\"latitude\":29.7506326,\"longitude\":-98.7026426,\"accuracy\":17.5,\"speed\":1.64,\"heading\":24.47,\"altitude\":412.9},\"activity\":{\"type\":\"walking\",\"confidence\":100},\"battery\":{\"is_charging\":false,\"level\":0.84},\"extras\":{}},{\"is_moving\":true,\"uuid\":\"bbe0d763-fcbc-46d1-8b3b-bb5c2e86a720\",\"timestamp\":\"2020-11-17T18:23:35.432Z\",\"odometer\":25019790,\"coords\":{\"latitude\":29.7507018,\"longitude\":-98.7025691,\"accuracy\":17.3,\"speed\":1.24,\"heading\":27.77,\"altitude\":412.9},\"activity\":{\"type\":\"walking\",\"confidence\":100},\"battery\":{\"is_charging\":false,\"level\":0.84},\"extras\":{}},{\"is_moving\":true,\"uuid\":\"3bb7907b-b739-4e35-b1cb-19833ceb3b9e\",\"timestamp\":\"2020-11-17T18:25:03.088Z\",\"odometer\":25019790,\"coords\":{\"latitude\":29.7506894,\"longitude\":-98.702508,\"accuracy\":17.1,\"speed\":1.28,\"heading\":46.14,\"altitude\":412.9},\"activity\":{\"type\":\"still\",\"confidence\":100},\"battery\":{\"is_charging\":false,\"level\":0.84},\"extras\":{}},{\"is_moving\":true,\"uuid\":\"62f1b49e-2680-4f58-9e2d-11f3e1e786c7\",\"timestamp\":\"2020-11-17T18:27:23.130Z\",\"odometer\":25019818,\"coords\":{\"latitude\":29.75062,\"longitude\":-98.702304,\"accuracy\":14.1,\"speed\":1.36,\"heading\":96.05,\"altitude\":412.9},\"activity\":{\"type\":\"still\",\"confidence\":100},\"battery\":{\"is_charging\":false,\"level\":0.84},\"extras\":{}}]],\"retry\":true,\"queue\":\"default\",\"jid\":\"7a54288de6dd93c29b40a12b\",\"created_at\":1605637645.5036702,\"enqueued_at\":1606204069.0425522,\"error_message\":\"could not obtain a database connection within 5.000 seconds (waited 5.008 seconds)\",\"error_class\":\"ActiveRecord::ConnectionTimeoutError\",\"failed_at\":1605637950.8471892,\"retry_count\":19,\"retried_at\":1606073416.3406177}"}
2020-11-24T07:49:02.407Z 798 TID-otk3vuz7i WARN: ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
2020-11-24T07:49:02.407Z 798 TID-otk3vuz7i WARN: /home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:189:in `block in wait_poll'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `loop'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `wait_poll'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:135:in `block in poll'
/home/deploy/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:145:in `synchronize'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:133:in `poll'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:425:in `acquire_connection'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/home/deploy/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/home/deploy/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_handling.rb:87:in `connection'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/core.rb:187:in `find_by'
/home/deploy/cleantrac/psychtrac/releases/20200825063455/app/workers/time_spent_worker.rb:5:in `perform'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.8/lib/sidekiq/processor.rb:192:in `execute_job'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.8/lib/sidekiq/processor.rb:165:in `block (2 levels) in process'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/sidekiq-5.2.8/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/sidekiq.rb:32:in `block in call'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:376:in `perform_action_with_newrelic_trace'
/home/deploy/cleantrac/psychtrac/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/sidekiq.rb:28:in `call'

![image](https://user-images.githubusercontent.com/45894592/100063532-5fd8ac80-2e57-11eb-92fb-32d2d8d29dc6.png)

**Comment by nirmalayuvasoft213** [comment]
@mperham Please let me know I am using rails 
Rails 4.2.11.1

**Comment by mperham** [comment]
Use sidekiq -c 5
