### ISSUE TITLE
uninitialized constant Rails

### ISSUE THREAD

**Issue by tdelam** [mperham/sidekiq#4757]
Ruby version: 2.5.0
Rails version: 5.2.0
Sidekiq / Pro / Enterprise version(s): 6.1.2

I am trying to run Sidekiq using systemd but receive the following error:

```
/bin/bash -lc "bundle exec sidekiq -e production -C config/sidekiq.yml -L log/sidekiq.log"
uninitialized constant Rails
(erb):2:in `<main>'
/home/trevor/.rbenv/versions/2.5.0/lib/ruby/2.5.0/erb.rb:885:in `eval'
/home/trevor/.rbenv/versions/2.5.0/lib/ruby/2.5.0/erb.rb:885:in `result'
/home/trevor/apps/ih_crm/production/shared/bundle/ruby/2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/cli.rb:362:in `parse_config'
/home/trevor/apps/ih_crm/production/shared/bundle/ruby/2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/cli.rb:228:in `setup_options'
/home/trevor/apps/ih_crm/production/shared/bundle/ruby/2.5.0/gems/sidekiq-6.0.7/lib/sidekiq/cli.rb:24:in `parse'
/home/trevor/apps/ih_crm/production/shared/bundle/ruby/2.5.0/gems/sidekiq-6.0.7/bin/sidekiq:27:in `<top (required)>'
/home/trevor/apps/ih_crm/production/shared/bundle/ruby/2.5.0/bin/sidekiq:23:in `load'
/home/trevor/apps/ih_crm/production/shared/bundle/ruby/2.5.0/bin/sidekiq:23:in `<top (required)>'
/home/trevor/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:63:in `load'
/home/trevor/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:63:in `kernel_load'
/home/trevor/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'
/home/trevor/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:476:in `exec'
/home/trevor/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/trevor/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/trevor/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/home/trevor/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:30:in `dispatch'
/home/trevor/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/home/trevor/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:24:in `start'
/home/trevor/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/home/trevor/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/home/trevor/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/home/trevor/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
/home/trevor/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
```
I do have Rails installed on the server. It's an app that has been running for a few years.

Here is my sidekiq.yml...

`:concurrency: 10
:pidfile: <%= Rails.root.join("tmp/pids/sidekiq.pid") %>
:logfile: <%= Rails.root.join("log/sidekiq.log") %>
staging:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - [critical, 2]
  - default
  - low
`

And here is my sidekiq.service in `/lib/systemd/system/sidekiq.service`...

```
#
# This file tells systemd how to run Sidekiq as a 24/7 long-running daemon.
#
# Customize this file based on your bundler location, app directory, etc.
# Customize and copy this into /usr/lib/systemd/system (CentOS) or /lib/systemd/system (Ubuntu).
# Then run:
#   - systemctl enable sidekiq
#   - systemctl {start,stop,restart} sidekiq
#
# This file corresponds to a single Sidekiq process.  Add multiple copies
# to run multiple processes (sidekiq-1, sidekiq-2, etc).
#
# Use `journalctl -u sidekiq -rn 100` to view the last 100 lines of log output.
#
[Unit]
Description=sidekiq
# start us only once the network and logging subsystems are available,
# consider adding redis-server.service if Redis is local and systemd-managed.
After=syslog.target network.target

# See these pages for lots of options:
#
#   https://www.freedesktop.org/software/systemd/man/systemd.service.html
#   https://www.freedesktop.org/software/systemd/man/systemd.exec.html
#
# THOSE PAGES ARE CRITICAL FOR ANY LINUX DEVOPS WORK; read them multiple
# times! systemd is a critical tool for all developers to know and understand.
#
[Service]
#
#      !!!!  !!!!  !!!!
#
# As of v6.0.6, Sidekiq automatically supports systemd's `Type=notify` and watchdog service
# monitoring. If you are using an earlier version of Sidekiq, change this to `Type=simple`
# and remove the `WatchdogSec` line.
#
#      !!!!  !!!!  !!!!
#
Type=notify
# If your Sidekiq process locks up, systemd's watchdog will restart it within seconds.
WatchdogSec=10

WorkingDirectory=/home/trevor/apps/ih_crm/production/current
# If you use rbenv:
ExecStart=/bin/bash -lc 'exec /home/trevor/.rbenv/shims/bundle exec sidekiq -e production'
# If you use the system's ruby:
# ExecStart=/usr/local/bin/bundle exec sidekiq -e production
# If you use rvm in production without gemset and your ruby version is 2.6.5
# ExecStart=/home/trevor/.rvm/gems/ruby-2.6.5/wrappers/bundle exec sidekiq -e production
# If you use rvm in production wit gemset and your ruby version is 2.6.5

# Use `systemctl kill -s TSTP sidekiq` to quiet the Sidekiq process

# !!! Change this to your trevor user account !!!
User=trevor
Group=trevor
UMask=0002

# Greatly reduce Ruby memory fragmentation and heap usage
# https://www.mikeperham.com/2018/04/25/taming-rails-memory-bloat/
Environment=MALLOC_ARENA_MAX=2

# if we crash, restart
RestartSec=1
Restart=on-failure

# output goes to /var/log/syslog (Ubuntu) or /var/log/messages (CentOS)
StandardOutput=syslog
StandardError=syslog

# This will default to "bundler" if we don't specify it
SyslogIdentifier=sidekiq

[Install]
WantedBy=multi-user.target
```

Is this a known issue or are there any workarounds?

**Comment by mperham** [comment]
Good news, you can remove those two lines from your config file and the problem goes away. Sidekiq 6.0 does not support those options anymore.

```
:pidfile: <%= Rails.root.join("tmp/pids/sidekiq.pid") %>
:logfile: <%= Rails.root.join("log/sidekiq.log") %>
```
