### ISSUE TITLE
Wrong number of arguments error when invoking perform_async on ruby 3

### ISSUE THREAD

**Issue by philreindl** [mperham/sidekiq#4780]
Ruby version: 3.0.0
Rails version: 6.0.3.4
Sidekiq / Pro / Enterprise version(s): 6.1.2 / 5.2.0 / 2.2.0

initializer
```
require 'performance_tracker'

# Tracks sidekiq errors, retries and job latency based on sidekiq meta job
# values
class JobStatsMiddleware
  KEY = :worker_stats

  def initialize(options = nil); end

  def self.worker_stats
    (Thread.current[KEY] || {}).dup
  end

  def call(_worker, msg, _queue)
    Thread.current[KEY] = {
      enqueued_at: msg['enqueued_at'],
      failed_at: msg['failed_at'],
      retry_count: msg['retry_count'],
      retried_at: msg['retried_at']
    }

    yield
  ensure
    Thread.current[KEY] = nil
  end
end

class TaskMetadataMiddleware
  def initialize(options = nil); end

  def call(_worker, _msg, _queue, &block)
    Sidekiq::Context.with('aws': TASK_METADATA,
                          'commit': ENV['GIT_REVISION'],
                          'build_date': ENV['BUILD_DATE'], &block)
  end
end

class LogTaskIdMiddleware
  def initialize(options = nil); end

  def call(_worker_class, job, _queue, _redis_pool)
    jid = job['jid']
    Thread.current[:scheduled_jobs]&.push(jid)

    yield
  end
end

class LogClearcutMiddleware
  def initialize(options = nil); end

  def call(_worker, _msg, _queue)
    Thread.current[:clearcut_event] = {}
    yield
    Sidekiq.logger.info LogClearcutMiddleware.log_event unless Thread.current[:clearcut_event].empty?
  end

  def self.subscribe
    ActiveSupport::Notifications.subscribe(/\.clearcut$/) do |name, _start, _finish, _id, payload|
      event_path = to_path(name)
      payload_value = payload[:value]
      combine(event_path, payload_value)
    end
  end

  def self.to_path(name)
    name.split('.').slice(0...-1).reverse.join('.') # trim .clearcut from the end
  end

  def self.combine(event_path, payload_value)
    existing_value = event(event_path)
    if existing_value.nil?
      set_event(event_path, payload_value)
    elsif existing_value.is_a?(String) && payload_value.is_a?(String)
      set_event(event_path, "#{existing_value},#{payload_value}")
    elsif existing_value.respond_to?(:concat) && payload_value.respond_to?(:concat)
      set_event(event_path, existing_value.concat(payload_value))
    else
      set_event(event_path, payload_value)
    end
  end

  def self.log_event
    Thread.current[:clearcut_event]
  end

  def self.event(event_path)
    Thread.current[:clearcut_event][event_path]
  end

  def self.set_event(event_path, value)
    Thread.current[:clearcut_event][event_path] = value
  end
end

class PerformanceTrackingMiddleware
  def initialize(options = nil); end

  def call(_worker_class, _job, _queue, _redis_pool)
    PerformanceTracker.clear!
    yield
  end
end

Sidekiq::Enterprise.unique! unless Rails.env.test?

Sidekiq.configure_server do |config|
  unless APP_CONFIG['sidekiq']['url'].blank?
    config.redis = {
      url: APP_CONFIG['sidekiq']['url'],
      namespace: APP_CONFIG['sidekiq']['namespace']
    }
    config.server_middleware do |chain|
      chain.add JobStatsMiddleware
      chain.add TaskMetadataMiddleware
      chain.add LogClearcutMiddleware
    end

    LogClearcutMiddleware.subscribe
    config.log_formatter = Sidekiq::Logger::Formatters::JSON.new

    config.periodic do |mgr|
      # https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs
      # see any crontab reference for the first argument
      # e.g. http://www.adminschoice.com/crontab-quick-reference
      # or   https://crontab.guru/
      mgr.register('0 * * * *', 'PollRemoteSystemWorker')

      # 7 AM and 8 AM UTC statistical aggregation.
      mgr.register('0 7 * * *', 'StatisticsFailuresWorker')
      mgr.register('0 7 * * *', 'CustomerAggregationBatchWorker')
      mgr.register('0 8 * * *', 'UserAggregationBatchWorker')
    end
  end
end

Sidekiq.configure_client do |config|
  unless APP_CONFIG['sidekiq']['url'].blank?
    config.redis = {
      url: APP_CONFIG['sidekiq']['url'],
      namespace: APP_CONFIG['sidekiq']['namespace']
    }

    config.client_middleware do |chain|
      chain.add LogTaskIdMiddleware
    end

  end
end

```

sidekiq.yml
```
defaults: &side_defaults
  url: "<%= ENV['SIDEKIQ_REDIS'] %>"

development:
  <<: *side_defaults
  namespace: floplan_dev

test:
  <<: *side_defaults
  namespace: floplan_test

production:
  <<: *side_defaults
  namespace: floplan_prod
```

An example sidekiq worker is as follows
```
require 'sidekiq'
require 'notifications/foo_notifier'

class FooNotificationWorker
  include NotificationWorker

  ##
  # @param [Symbol] type The type of notification to send.
  # @param [Integer] user_id The user_id of the account holder.
  # @param [Integer] foo_id The Foo id we're sending a notification about
  def perform(type, user_id, foo_id)
    notifier = Notifications::FooNotifier.new type, user_id, Foo_id
    notifier.notify!
  end
end
```

When connecting my dev machine to the dev test environment I am able to reproduce the error as follows
```
[1] pry(main)> fp = Foo.find(4430)
=> #<Foo:0x000055bfe036c360
 foo_id: 4430,
 owner_user_id: 2,
 <snip>,
 lock_version: 1>
[2] pry(main)> FooNotificationWorker.perform_async :foo_ready_agent, fp.owner_user_id, fp.foo_id
ArgumentError: wrong number of arguments (given 3, expected 2)
from /usr/local/bundle/gems/redis-4.2.5/lib/redis.rb:836:in `set'
```

Attempting to reproduce this issue in the automated tests, I set our test environment up with a docker image of redis and created the following unit test, which passes
```
test 'perform_async' do
  Sidekiq::Testing.disable!
  assert_difference 'Sidekiq::Queue.new.size', +1 do
    FooNotificationWorker.perform_async :foo_ready_agent, @foo.owner_user_id, @foo.foo_id
  end
ensure
  Sidekiq::Queue.new.clear
  Sidekiq::Testing.fake!
end
```

Looking for any thoughts/suggestions as to what might be going on.  This is working fine under ruby 2.7.0.  

Thanks
Phil

**Comment by mperham** [comment]
I've installed redis-4.2.5 and ruby-3.0.0 and the test suite runs fine. Shut down Spring to make sure it's not an old process?

**Comment by philreindl** [comment]
Unfortunately that is the entirety of the stacktrace I'm getting.

**Comment by mperham** [comment]
The only red flag I see is redis-namespace. I would remove that if possible. Here's my thoughts on redis-namespace:

https://www.mikeperham.com/2015/09/24/storing-data-with-redis/

https://www.mikeperham.com/2017/04/10/migrating-from-redis-namespace/

**Comment by philreindl** [comment]
I removed the name space and that seems to have taken care of the issue.  I'll work on a migration plan.  Thanks!

**Comment by philreindl** [comment]
After getting the migration code in place, the configuration code looks like so

```
Sidekiq.configure_server do |config|
  unless APP_CONFIG['sidekiq']['url'].blank?
    config.redis = if ENV['SIDEKIQ_OLD']
                     {
                       url: APP_CONFIG['sidekiq']['url'],
                       namespace: APP_CONFIG['sidekiq']['namespace']
                     }
                   else
                     {
                       url: APP_CONFIG['sidekiq']['url'],
                       db: APP_CONFIG['sidekiq']['db']
                     }
                   end
    config.server_middleware do |chain|
      chain.add JobStatsMiddleware
      chain.add TaskMetadataMiddleware
      chain.add LogClearcutMiddleware
    end

    LogClearcutMiddleware.subscribe
    config.log_formatter = Sidekiq::Logger::Formatters::JSON.new

    unless ENV['SIDEKIQ_OLD']
      config.periodic do |mgr|
        # https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs
        # see any crontab reference for the first argument
        # e.g. http://www.adminschoice.com/crontab-quick-reference
        # or   https://crontab.guru/
        mgr.register('0 * * * *', 'PollCubicasaWorker')

        # 7 AM and 8 AM UTC statistical aggregation.
        mgr.register('0 7 * * *', 'StatisticsFailuresWorker')
      end
    end
  end
end

Sidekiq.configure_client do |config|
  unless APP_CONFIG['sidekiq']['url'].blank?
    config.redis = {
      url: APP_CONFIG['sidekiq']['url'],
      db: APP_CONFIG['sidekiq']['db']
    }

    config.client_middleware do |chain|
      chain.add LogTaskIdMiddleware
    end

  end
end
```

The server that is running with the SIDEKIQ_OLD flag enabled is generating errors in the logs.  Unfortunately, the message is coming separately from the stacktraces, but hopefully this is useful.

```
ArgumentError: wrong number of arguments (given 4, expected 3)
```

```
Passing 'exists?' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/launcher.rb:161:in `block (2 levels) in ❤')
```

```
Passing 'unlink' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/launcher.rb:148:in `block (2 levels) in ❤')
```

```
/usr/local/bundle/gems/redis-4.2.5/lib/redis.rb:1961:in `zrangebyscore'
 /usr/local/bundle/gems/redis-namespace-1.6.0/lib/redis/namespace.rb:442:in `call_with_namespace'
 /usr/local/bundle/gems/redis-namespace-1.6.0/lib/redis/namespace.rb:328:in `method_missing'
 /usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/scheduled.rb:18:in `block (2 levels) in enqueue_jobs'
 /usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/scheduled.rb:16:in `each'
 /usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/scheduled.rb:16:in `block in enqueue_jobs'
 /usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq.rb:98:in `block in redis'
 /usr/local/bundle/gems/connection_pool-2.2.3/lib/connection_pool.rb:63:in `block (2 levels) in with'
 /usr/local/bundle/gems/connection_pool-2.2.3/lib/connection_pool.rb:62:in `handle_interrupt'
 /usr/local/bundle/gems/connection_pool-2.2.3/lib/connection_pool.rb:62:in `block in with'
 /usr/local/bundle/gems/connection_pool-2.2.3/lib/connection_pool.rb:59:in `handle_interrupt'
 /usr/local/bundle/gems/connection_pool-2.2.3/lib/connection_pool.rb:59:in `with'
 /usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq.rb:95:in `redis'
 /usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/scheduled.rb:15:in `enqueue_jobs'
 /usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/scheduled.rb:78:in `enqueue'
 /usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/scheduled.rb:70:in `block in start'
 /usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/util.rb:15:in `watchdog'
 /usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/util.rb:24:in `block in safe_thread'
 ```

**Comment by mperham** [comment]
That's a really old version of redis-namespace. You'll need to use their master branch.
