### ISSUE TITLE
[Sidekiq UI] TypeError in  "/sidekiq/queues" - String can't be coerced into Float

### ISSUE THREAD

**Issue by berkos** [mperham/sidekiq#4781]
👋 Thanks for the great work in Sidekiq! 🙏 
I am getting some intermittent errors that are happening on `sidekiq/queues` and are related with `Sidekiq::Queue#latency`. 

Ruby version: 2.7.2
Rails version: 6.1.1
Sidekiq / Pro / Enterprise version(s): sidekiq (6.1.2)/  sidekiq-pro (5.2.0)  / sidekiq-ent (2.2.0)
Redis 6.0.9

Part of initializer `sidekiq.rb`

```ruby
Sidekiq.configure_server do |config|
  # https://github.com/mperham/sidekiq/wiki/Reliability
  config.reliable_scheduler!
  config.super_fetch!

  config.redis = ConnectionPool.new(size: Sidekiq.options[:concurrency] + 5, timeout: timeout, &redis_conn)

  config.death_handlers << lambda do |job, error|
    ApplicationWorker::Error.new(job: job, original_error: error) if job['retry']
  end
end

Sidekiq.configure_client do |config|
  max_threads = Rails.configuration.x.app_info.max_threads
  config.redis = ConnectionPool.new(size: max_threads, timeout: timeout, &redis_conn)
end

```

Backtrace:

```bash
TypeError: String can't be coerced into Float
  from sidekiq (6.1.2) lib/sidekiq/api.rb:240:in `-'
  from sidekiq (6.1.2) lib/sidekiq/api.rb:240:in `latency'
  from sidekiq (6.1.2) lib/sidekiq/web/action.rb:68:in `block in _erb_queues'
  from sidekiq (6.1.2) lib/sidekiq/web/action.rb:59:in `each'
  from sidekiq (6.1.2) lib/sidekiq/web/action.rb:59:in `_erb_queues'
  from sidekiq (6.1.2) lib/sidekiq/web/action.rb:89:in `_erb'
  from sidekiq (6.1.2) lib/sidekiq/web/action.rb:58:in `erb'
  from sidekiq (6.1.2) lib/sidekiq/web/application.rb:76:in `block in <class:WebApplication>'
  from sidekiq (6.1.2) lib/sidekiq/web/application.rb:296:in `instance_exec'
  from sidekiq (6.1.2) lib/sidekiq/web/application.rb:296:in `block in call'
  from sidekiq (6.1.2) lib/sidekiq/web/application.rb:294:in `catch'
  from sidekiq (6.1.2) lib/sidekiq/web/application.rb:294:in `call'
  from rack (2.2.3) lib/rack/auth/basic.rb:28:in `call'
  from sidekiq (6.1.2) lib/sidekiq/web/csrf_protection.rb:52:in `admit'
  from sidekiq (6.1.2) lib/sidekiq/web/csrf_protection.rb:41:in `call'
  from rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
  from rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
  from rack (2.2.3) lib/rack/content_length.rb:17:in `call'
  from rack (2.2.3) lib/rack/urlmap.rb:74:in `block in call'
  from rack (2.2.3) lib/rack/urlmap.rb:58:in `each'
  from rack (2.2.3) lib/rack/urlmap.rb:58:in `call'
  from rack (2.2.3) lib/rack/builder.rb:244:in `call'
  from sidekiq (6.1.2) lib/sidekiq/web.rb:105:in `call'
  from sidekiq (6.1.2) lib/sidekiq/web.rb:110:in `call'
  from actionpack (6.1.1) lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'
  from actionpack (6.1.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
  from actionpack (6.1.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
  from actionpack (6.1.1) lib/action_dispatch/journey/router.rb:32:in `each'
  from actionpack (6.1.1) lib/action_dispatch/journey/router.rb:32:in `serve'
  from actionpack (6.1.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
...
  from railties (6.1.1) lib/rails/engine.rb:539:in `call'
  from puma (5.1.1) lib/puma/configuration.rb:246:in `call'
  from puma (5.1.1) lib/puma/request.rb:76:in `block in handle_request'
  from puma (5.1.1) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
  from puma (5.1.1) lib/puma/request.rb:75:in `handle_request'
  from puma (5.1.1) lib/puma/server.rb:431:in `process_client'
  from puma (5.1.1) lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

After some investigation:
The issue occurs within the `#latency` method [here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L237-L240).

More specific when it tries to pick the first job of the list jobs on a specfic queue the "signature" (Hash represenation) of a job sometimes is incosistent between queues.

Below you can see 2 examples for the output of `job` variant in [line 237](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L237) for different jobs/queues.

Working variant "job" :

```ruby
{"retry"=>true,
 "queue"=>"queue_a",
 "backtrace"=>5,
 "unique_for"=>2629746,
 "class"=>"FooWorker",
 "args"=>[{"id"=>"a8b60c7d-b5c1-47e4-b280"}],
 "jid"=>"1659978e1da21800d7cd0443",
 "created_at"=>1610633987.060398,
 "unique_token"=>"e198925940fd96c62bdf21a4553c2ed192bf3fcc",
 "unlocks_at"=>"1613263733.0604281",
 "enqueued_at"=>1610633987.061718 # Is a decimal as expected
 }
```
variant "job" that raises an error:

```ruby
{"retry"=>258,
 "queue"=>"qeueue_b",
 "backtrace"=>5,
 "unique_for"=>2629746,
 "class"=>"FooWorker",
 "args"=>[{"id"=>"bg39fc46-2bbg-457a-990d"}],
 "jid"=>"3a5673261fcb4f2a55e5ab10",
 "created_at"=>1610582415.316693,
 "unique_token"=>"87ce33149624b163d69838dad5f407853f4bb6cd",
 "unlocks_at"=>"1613212161.316716",
 "bid"=>"k9H-Ir69dmPhNA",
 "enqueued_at"=>"1610583054.6868343",   # Here you can see that is surrounded in quotes, which is causing the issue
 "error_message"=>"ApplicationWorker::RetryError",
 "error_class"=>"ApplicationWorker::RetryError",
 "failed_at"=>1610582425.253277,
 "retry_count"=>82,
 "error_backtrace"=>
  "eJyljkFOAzEMRa9SZtMNHcOoVUWvUqGQZExrTRIHO6Hi9kwzXSDUBRILS9az\n" +
  "9f4/dmBzbnNhmVAUsnBmtaFtHlWNFluqGn9GP5nlrRd3GF4OlFZvCxZUDrUQ\n" +
  "p4d19/gf63OzZpR3lnjX5Tl5lKSQbMTRWDnViKnozWJu96tt/3eZ2IImUKRy\n" +
  "/aTQclFamyoyo2vqbttSL1TOlJZu6+71G+u4oEA=\n",
 "retried_at"=>1610633602.025782}
```

If you notice on the second example the "enqueued_at" attribute is wrapped in quotes. When it tries to do the substraction in [line 240 ](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L240) It ends up in a `Float - String` which fails.

Also you can notice there is some type incosistency between other keys too. E.g: `unlocks_at`.
The same tyoe of job/queue that is "problematic" above can sometimes come with the expected type of arugments so it's not always raising an error.

**Comment by jeffblake** [comment]
OJ gem. Remove it.

**Comment by berkos** [comment]
Thanks for you response @jeffblake. Adding a link to [unsfafe gems](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#thread-unsafe-gems-do-not-use) in case someone has a similar error.
