### ISSUE TITLE
periodic job: NoMethodError: undefined method `jid=' with ActiveJob

### ISSUE THREAD

**Issue by stereosupersonic** [mperham/sidekiq#4808]
Ruby version: 2.6.3
Rails version: 6.0.3.4
Sidekiq / Pro / Enterprise version(s):  sidekiq (6.1.3),   sidekiq-pro (5.2.1),  sidekiq-ent (2.2.2)

periodic jobs don't work with ActiveJob

## initializer
```

redis_config = { host: Rails.configuration.redis_host, port: Rails.configuration.redis_port }

Sidekiq.configure_server do |config|
  config.redis = redis_config

  config.periodic do |mgr|
    mgr.register "*/1 * * * *", "TestJob", retry: 1
  end

  config.death_handlers << lambda { |_job, error|
    Rails.logger.error("Uh oh, just died with error #{ex.message}.")
  }
end

Sidekiq.configure_client do |config|
  config.redis = redis_config
end

Sidekiq.default_worker_options = { "backtrace" => 10 }
```

## sidekiq.yml
```
---
:concurrency: 5

production:
  :concurrency: 10
:queues:
  - [critical, 3]
  - [notifications, 2]
  - [default, 2]
  - low

```

## TestJob
```
class TestJob < ActiveJob::Base
  self.queue_adapter = :sidekiq # override application setting

  def perform
    puts "HELLO WORLD"
    Rails.logger.info "************************** YES ***************"
  end
end
```

## backtrace

```
2021-02-10T07:49:00.011Z pid=85579 tid=oxa4mgby7 class=TestJob jid=d23ab240ba4f637904706cb8 INFO: start
2021-02-10T07:49:00.012Z pid=85579 tid=oxa4mgby7 class=TestJob jid=d23ab240ba4f637904706cb8 elapsed=0.001 INFO: fail
2021-02-10T07:49:00.014Z pid=85579 tid=oxa4i0b53 INFO: Enqueued periodic job TestJob with JID d23ab240ba4f637904706cb8 for 2021-02-10 08:49:00 +0100
2021-02-10T07:49:00.016Z pid=85579 tid=oxa4mgby7 WARN: {"context":"Job raised exception","job":{"retry":1,"queue":"default","backtrace":10,"class":"TestJob","args":[],"jid":"d23ab240ba4f637904706cb8","created_at":1612943340.006592,"enqueued_at":1612943340.00669},"jobstr":"{\"retry\":1,\"queue\":\"default\",\"backtrace\":10,\"class\":\"TestJob\",\"args\":[],\"jid\":\"d23ab240ba4f637904706cb8\",\"created_at\":1612943340.006592,\"enqueued_at\":1612943340.00669}"}
2021-02-10T07:49:00.016Z pid=85579 tid=oxa4mgby7 WARN: NoMethodError: undefined method `jid=' for #<TestJob:0x00007fe6cd635900>
2021-02-10T07:49:00.016Z pid=85579 tid=oxa4mgby7 WARN: /Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:134:in `block (5 levels) in dispatch'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/rails.rb:14:in `block in call'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/reloader.rb:72:in `block in wrap'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/reloader.rb:71:in `wrap'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/rails.rb:13:in `call'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:257:in `stats'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/job_logger.rb:13:in `call'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/job_retry.rb:79:in `global'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:124:in `block in dispatch'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/logger.rb:11:in `with'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/job_logger.rb:33:in `prepare'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:123:in `dispatch'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:162:in `process'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:78:in `process_one'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:68:in `run'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/util.rb:15:in `watchdog'
/Users/deimel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/util.rb:24:in `block in safe_thread'
2021-02-10T07:49:40.297Z pid=85579 tid=oxa3lt5uz class=TestJob jid=d23ab240ba4f637904706cb8 INFO: start
2021-02-10T07:49:40.301Z pid=85579 tid=oxa3lt5uz class=TestJob jid=d23ab240ba4f637904706cb8 elapsed=0.004 INFO: fail
2021-02-10T07:49:40.302Z pid=85579 tid=oxa3lt5uz class=TestJob jid=d23ab240ba4f637904706cb8 INFO: Adding dead TestJob job d23ab240ba4f637904706cb8
```

if i trigger this Job manually then it works , and it also works for the periodic jobs when  i don't use ActiveJob
like here
```
class TestJob
  include Sidekiq::Worker
  
  def perform
    puts "HELLO WORLD"
    Rails.logger.info "************************** YES ***************"
  end
end

**Comment by mperham** [comment]
That is correct. Some features do not work with AJ.

**Comment by stereosupersonic** [comment]
Ok, thank you. Would be good if you could update your wiki https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs
That would save others a lot of debugging time.

**Comment by kojikojikojikoji** [comment]
I have the same error. Can anyone please tell me what I should do? @mperham @stereosupersonic

**Comment by mperham** [comment]
@kojikojikojikoji this is not your issue. If you have a problem, open your own issue.

**Comment by christopheragnus** [comment]
Hey - is there going to be a fix to this?
