### ISSUE TITLE
Safe way to eject failing code

### ISSUE THREAD

**Issue by jnarowski** [mperham/sidekiq#4811]
I have workers that are getting stuck on this line:
```
  def company_from
    from = Mail::Address.new @company.email
    from.display_name = @company.name.dup
    from
  end
```

I can run the code safely returning the proper result in the console, but when run through workers, sometimes the job just gets "stuck" for no apparent reason. 

AFAIK, the backtrace doesn't really show me anything useful other than it's in that method:
```
/app/app/mailers/auto_track_mailer.rb:83:in `company_from'
/app/app/mailers/auto_track_mailer.rb:27:in `email'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.0.7.1/lib/abstract_controller/base.rb:188:in `process_action'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.0.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.0.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.0.7.1/lib/abstract_controller/base.rb:126:in `process'
/app/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.0.7.1/lib/action_mailer/rescuable.rb:23:in `block in process'
/app/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.0.7.1/lib/action_mailer/rescuable.rb:15:in `handle_exceptions'
/app/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.0.7.1/lib/action_mailer/rescuable.rb:22:in `process'
/app/vendor/bundle/ruby/2.6.0/gems/actionview-5.0.7.1/lib/action_view/rendering.rb:30:in `process'
/app/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.0.7.1/lib/action_mailer/base.rb:595:in `block in process'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/notifications.rb:164:in `instrument'
/app/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.0.7.1/lib/action_mailer/base.rb:594:in `process'
/app/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.0.7.1/lib/action_mailer/message_delivery.rb:105:in `block in processed_mailer'
/app/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.0.7.1/lib/action_mailer/message_delivery.rb:104:in `tap'
/app/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.0.7.1/lib/action_mailer/message_delivery.rb:104:in `processed_mailer'
/app/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.0.7.1/lib/action_mailer/message_delivery.rb:27:in `__getobj__'
/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/delegate.rb:80:in `method_missing'
/app/lib/classes/auto_action/send_email.rb:142:in `perform'
/app/app/models/auto_track_run.rb:373:in `perform'
/app/app/jobs/auto_tracks/auto_track_run_job.rb:8:in `perform'
/app/vendor/bundle/ruby/2.6.0/gems/activejob-5.0.7.1/lib/active_job/execution.rb:34:in `block in perform_now'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:126:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:455:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/app/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.5/lib/i18n.rb:313:in `with_locale'
/app/vendor/bundle/ruby/2.6.0/gems/activejob-5.0.7.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:285:in `block in halting'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:447:in `block in around'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:455:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/app/vendor/bundle/ruby/2.6.0/gems/activejob-5.0.7.1/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/notifications.rb:164:in `instrument'
/app/vendor/bundle/ruby/2.6.0/gems/activejob-5.0.7.1/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.6.0/gems/activejob-5.0.7.1/lib/active_job/logging.rb:44:in `block in tag_logger'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/app/vendor/bundle/ruby/2.6.0/gems/activejob-5.0.7.1/lib/active_job/logging.rb:44:in `tag_logger'
/app/vendor/bundle/ruby/2.6.0/gems/activejob-5.0.7.1/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:285:in `block in halting'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:447:in `block in around'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:455:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:750:in `_run_perform_callbacks'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/app/vendor/bundle/ruby/2.6.0/gems/activejob-5.0.7.1/lib/active_job/execution.rb:33:in `perform_now'
/app/vendor/bundle/ruby/2.6.0/gems/activejob-5.0.7.1/lib/active_job/execution.rb:22:in `block in execute'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:126:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:455:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/app/vendor/bundle/ruby/2.6.0/gems/activejob-5.0.7.1/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/reloader.rb:68:in `block in wrap'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/execution_wrapper.rb:81:in `wrap'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/reloader.rb:67:in `wrap'
/app/vendor/bundle/ruby/2.6.0/gems/activejob-5.0.7.1/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:285:in `block in halting'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:447:in `block in around'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:455:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:750:in `_run_execute_callbacks'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/app/vendor/bundle/ruby/2.6.0/gems/activejob-5.0.7.1/lib/active_job/execution.rb:20:in `execute'
/app/vendor/bundle/ruby/2.6.0/gems/activejob-5.0.7.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:40:in `perform'
/app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:196:in `execute_job'
/app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
/app/app/support/spectora_sidekiq.rb:115:in `block in call'
/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.27.0/lib/rollbar.rb:145:in `scoped'
/app/app/support/spectora_sidekiq.rb:114:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.27.0/lib/rollbar/plugins/sidekiq/plugin.rb:11:in
```

I am really having a hard time understanding how to take action on these stuck processes. If there was a way to safely add a blanket timeout wrapper that exited / failed the job properly, that might help me apply this system to all my stuck jobs.

**Comment by mperham** [comment]
You can add this to your emailer code to ensure the Thread doesn't get stuck.

```ruby
Timeout.timeout(5) do
  do all the email stuff...
end
```

I don't encourage the use of Timeout but sometimes it's a necessary evil.

**Comment by jnarowski** [comment]
Ok great, I might try that.

I thought Timeout wasn't thread safe and a big nono? 
https://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/

**Comment by mperham** [comment]
Like all complex things, it's complicated. You don't want to use it around every single job or request, like rack-timeout.

**Comment by jnarowski** [comment]
So something like this:

```
class AutoTrackRunJob < ApplicationJob
  queue_as :communications

  def perform(auto_track_run_id:)
    return if cancelled?

    run = AutoTrackRun.find_by(id: auto_track_run_id)
    return if run.blank?

    Timeout.timeout(60) do
      run.perform if run.should_perform?

      if run.lock_on_completion && (run.is_fulfilled || run.is_failed)
        run.update_column(:is_locked, true)
      end
    end

    run
  end
end
```

**Comment by mperham** [comment]
I would make the Timeout block as small as possible but yeah, you've got the idea. Let us know how that works out for your stuck jobs.

```ruby
    Timeout.timeout(60) do
      run.perform 
    end if run.should_perform?

    if run.lock_on_completion && (run.is_fulfilled || run.is_failed)
      run.update_column(:is_locked, true)
    end
```

**Comment by jnarowski** [comment]
Thanks! I'll add it to a few key jobs and will let you know how it goes.

**Comment by jnarowski** [comment]
BTW, This did not fix the ActiveMailer stuck jobs:

```
Mail::SMTP::DEFAULTS[:read_timeout] = 5
Mail::SMTP::DEFAULTS[:open_timeout] = 5
```

We still have at least 5 like this:
https://share.getcloudapp.com/wbu9K1by

**Comment by jnarowski** [comment]
Should I make a separate issue for that, or is that too specific to my situation?

**Comment by mperham** [comment]
At a higher level, is it a Sidekiq issue? Sidekiq has no control over executing Ruby code beyond the few APIs Ruby makes available, e.g. `Thread#kill`. If some code in your app locks up for some reason, Sidekiq can't do anything about it. I'm trying to help you configure your app code so it doesn't stick but beyond that, I'm not sure what I can do.

**Comment by jnarowski** [comment]
I understand what you are saying, but this is just core Rails 5.0.7.1 + ActionMailer + Sidekiq. AFAIK nothing specific to our setup. 

The thought is, if I am experiencing this, I am sure others are too. 

The other jobs for sure, that's very specific to us, but how can we make it safe to use ActionMailer + Sidekiq without the worry of stuck jobs.

**Comment by mperham** [comment]
And about 100 other gems. I don’t like that this is a relatively common problem but I have to draw a line in the sand for support somewhere. If you can track down a common source of the issue using backtraces I’m happy to look and help figure out the root cause.

**Comment by jnarowski** [comment]
Ok np. Thanks. You've been awesome with all of this and your support is much appreciated.
