### ISSUE TITLE
undefined method `before_filter' for SidekiqSandboxController:Class

### ISSUE THREAD

**Issue by izghitu** [mperham/sidekiq#4830]
Ruby version: 2.6.2p47
Rails version: 5.2.4.2
Sidekiq / Pro / Enterprise version(s): 5.2.9

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
```[ E 2021-03-02 11:07:10.1989 27720/T5 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-3] Cannot checkout session because a spawning error occurred. The identifier of the error is b6d33be1. Please see earlier logs for details about the error.
App 31313 output: [dry-types] Dry::Types.module is deprecated and will be removed in the next major version
App 31313 output: Use Dry.Types() instead. Beware, it exports strict types by default, for old behavior use Dry.Types(default: :nominal). See more options in the changelog
App 31313 output: /vol/www/sites/redmine.site.com/config/application.rb:18:in `<top (required)>'
App 31313 output: Error: The application encountered the following error: undefined method `before_filter' for SidekiqSandboxController:Class
App 31313 output: Did you mean?  before_action (NoMethodError)
App 31313 output:     /vol/www/sites/redmine.site.com/plugins/redmine_sidekiq/app/controllers/sidekiq_sandbox_controller.rb:3:in `<class:SidekiqSandboxController>'
App 31313 output:     /vol/www/sites/redmine.site.com/plugins/redmine_sidekiq/app/controllers/sidekiq_sandbox_controller.rb:1:in `<top (required)>'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:378:in `block in require_or_load'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:37:in `load_interlock'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:356:in `require_or_load'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:334:in `depend_on'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:246:in `require_dependency'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/railties-5.2.4.2/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `each'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `block in eager_load!'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `each'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `eager_load!'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/railties-5.2.4.2/lib/rails/engine.rb:356:in `eager_load!'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `each'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/ruby/tsort.rb:228:in `block in tsort_each'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/ruby/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/ruby/tsort.rb:431:in `each_strongly_connected_component_from'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/ruby/tsort.rb:349:in `block in each_strongly_connected_component'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/ruby/tsort.rb:347:in `each'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/ruby/tsort.rb:347:in `call'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/ruby/tsort.rb:347:in `each_strongly_connected_component'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/ruby/tsort.rb:226:in `tsort_each'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/ruby/tsort.rb:205:in `tsort_each'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
App 31313 output:     /vol/www/sites/redmine.site.com/config/environment.rb:16:in `<top (required)>'
App 31313 output:     config.ru:3:in `require'
App 31313 output:     config.ru:3:in `block in <main>'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/share/gems/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 31313 output:     config.ru:1:in `new'
App 31313 output:     config.ru:1:in `<main>'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/local/share/gems/gems/passenger-6.0.7/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/local/share/gems/gems/passenger-6.0.7/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/local/share/gems/gems/passenger-6.0.7/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/local/share/gems/gems/passenger-6.0.7/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:382:in `run_block_and_record_step_progress'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/local/share/gems/gems/passenger-6.0.7/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/local/share/gems/gems/passenger-6.0.7/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 31313 output:     /opt/rh/rh-ruby26/root/usr/local/share/gems/gems/passenger-6.0.7/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-03-02 11:56:30.6082 27720/Tr age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /vol/www/sites/redmine.site.com: The application encountered the following error: undefined method `before_filter' for SidekiqSandboxController:Class
Did you mean?  before_action (NoMethodError)
  Error ID: 01ddbae4
  Error details saved to: /tmp/passenger-error-L6dx1g.html

[ E 2021-03-02 11:56:30.6112 27720/T5 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-4] Cannot checkout session because a spawning error occurred. The identifier of the error is 01ddbae4. Please see earlier logs for details about the error.
```

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?
Yes

I am trying to setup this redmine plugin https://github.com/southbridgeio/redmine_sidekiq which depends on Sidekiq. I use this on CentOS 7 with Apache 2.4 and mod_passenger 6.0.7.

I ran bundle install and it went through properly but when I try to open the redmine install in my browser I get that error.

Is there anything I need to do to make it work?
Please let me know. Thanks in advance.

**Comment by izghitu** [comment]
issue was with outdated redmine_sidekiq plugin
