### ISSUE TITLE
unique_for is not holding a unique lock

### ISSUE THREAD

**Issue by csmith-tj** [mperham/sidekiq#4831]
After recently upgrading some of our sidekiq gems, we started encountering the following error in any job that uses `unique_for`.

Some, possibly relevant, details about the system:

ruby (2.6.6)
rails (5.2.4.3)
sidekiq (6.1.3)
sidekiq-ent (2.2.2)
sidekiq-pro (5.2.1)
sidekiq-throttled (0.13.0)
concurrent-ruby (1.1.8)

And the full trace:

```
$ SIDEKIQ_CONCURRENCY=5 bundle exec sidekiq -v -C config/sidekiq.yml

2021-03-03T19:58:37.216Z pid=83439 tid=owvqfekdf INFO: Booted Rails 5.2.4.3 application in development environment
2021-03-03T19:58:37.217Z pid=83439 tid=owvqfekdf INFO: Running in ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
2021-03-03T19:58:37.217Z pid=83439 tid=owvqfekdf INFO: Sidekiq Pro 5.2.1 / Sidekiq Enterprise 2.2.2, commercially licensed.
2021-03-03T19:58:37.217Z pid=83439 tid=owvqfekdf INFO: Booting Sidekiq 6.1.3 with redis options {:url=>"redis://127.0.0.1:6379/2"}
2021-03-03T19:58:37.230Z pid=83439 tid=owvqfekdf DEBUG: Client Middleware: Sidekiq::Enterprise::Unique::Client, Sidekiq::Batch::Client
2021-03-03T19:58:37.231Z pid=83439 tid=owvqfekdf DEBUG: Server Middleware: Honeybadger::Plugins::Sidekiq::Middleware, Sidekiq::Limiter::Middleware, Sidekiq::Enterprise::Unique::Server, Sidekiq::Batch::Server, NewRelic::SidekiqInstrumentation, Sidekiq::Throttled::Middleware
2021-03-03T19:58:37.231Z pid=83439 tid=owvqfekdf INFO: Starting processing, hit Ctrl-C to stop

2021-03-03T19:58:37.232Z pid=83439 tid=owvqfekdf DEBUG: {:queues=>["async_api_requests", "default"], :labels=>[], :concurrency=>5, :require=>".", :strict=>true, :environment=>nil, :timeout=>25, :poll_interval_average=>nil, :average_scheduled_poll_interval=>5, :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x00007fd8418c0728>, #<Proc:0x00007fd84ab47ee8@/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/newrelic_rpm-5.4.0.347/lib/new_relic/agent/instrumentation/sidekiq.rb:66>, #<Proc:0x00007fd84894c8e8@/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/honeybadger-4.6.0/lib/honeybadger/plugins/sidekiq.rb:26 (lambda)>], :death_handlers=>[#<Proc:0x00007fd848af2df0@/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-pro-5.2.1/lib/sidekiq/batch/death.rb:58 (lambda)>, #<Proc:0x00007fd8471e2108@/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/unique.rb:180 (lambda)>], :lifecycle_events=>{:startup=>[], :quiet=>[#<Proc:0x00007fd848ab7598@/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-pro-5.2.1/lib/sidekiq/pro/config.rb:88>, #<Proc:0x00007fd83ef65810@/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-throttled-0.13.0/lib/sidekiq/throttled/communicator.rb:68>, #<Proc:0x00007fd83ef64910@/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-throttled-0.13.0/lib/sidekiq/throttled/queues_pauser.rb:55>], :shutdown=>[#<Proc:0x00007fd848b02de0@/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/election.rb:12>, #<Proc:0x00007fd848b92f58@/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic.rb:88>], :heartbeat=>[], :leader=>[#<Proc:0x00007fd848b92f80@/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic.rb:77>, #<Proc:0x00007fd848bc9b70@/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/census.rb:180>], :fork=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :reloader=>#<Sidekiq::Rails::Reloader @app=FilingApi::Application>, :verbose=>true, :config_file=>"config/sidekiq.yml", :backup_limit=>1000, :fetch=>#<Sidekiq::Throttled::Fetch:0x00007fd847036980 @paused=#<Sidekiq::Throttled::ExpirableList:0x00007fd847036958 @ttl=2.0, @arr=[], @mon=#<Monitor:0x00007fd847036548 @mon_mutex=#<Thread::Mutex:0x00007fd8470360c0>, @mon_mutex_owner_object_id=70283440534180, @mon_owner=nil, @mon_count=0>>, @strict=true, @queues=["queue:async_api_requests", "queue:default"]>, :tag=>"my_app_name", :identity=>"this identifies me"}

2021-03-03T19:58:37.282Z pid=83439 tid=owvrvm86n INFO: Gained leadership of the cluster
2021-03-03T19:58:37.282Z pid=83439 tid=owvrvm86n DEBUG: Loading Sidekiq Enterprise Lua extensions
2021-03-03T19:59:00.590Z pid=83439 tid=owvs4l6iz class=SomeJobClass jid=7f815049087c86a1609ea6bd INFO: start
2021-03-03T19:59:02.286Z pid=83439 tid=owvs4l6iz class=SomeJobClass jid=7f815049087c86a1609ea6bd elapsed=1.696 INFO: fail
2021-03-03T19:59:02.286Z pid=83439 tid=owvs4l6iz WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","unique_for":"600","class":"SomeJobClass","args":[178],"jid":"7f815049087c86a1609ea6bd","created_at":1614801540.581354,"enqueued_at":1614801540.581694},"jobstr":"{\"retry\":true,\"queue\":\"default\",\"unique_for\":\"600\",\"class\":\"SomeJobClass\",\"args\":[178],\"jid\":\"7f815049087c86a1609ea6bd\",\"created_at\":1614801540.581354,\"enqueued_at\":1614801540.581694}"}
2021-03-03T19:59:02.286Z pid=83439 tid=owvs4l6iz WARN: ArgumentError: 7f815049087c86a1609ea6bd is not holding a unique lock
2021-03-03T19:59:02.286Z pid=83439 tid=owvs4l6iz WARN: /Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/unique.rb:138:in `unlock'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/unique.rb:152:in `call'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/limiter/middleware.rb:38:in `call'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/honeybadger-4.6.0/lib/honeybadger/plugins/sidekiq.rb:10:in `call'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/middleware/chain.rb:143:in `invoke'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:163:in `block in process'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/job_retry.rb:112:in `local'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/rails.rb:14:in `block in call'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/reloader.rb:73:in `block in wrap'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/reloader.rb:72:in `wrap'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/rails.rb:13:in `call'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:257:in `stats'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/job_logger.rb:13:in `call'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/job_retry.rb:79:in `global'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:124:in `block in dispatch'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/logger.rb:11:in `with'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/job_logger.rb:33:in `prepare'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:123:in `dispatch'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:162:in `process'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:78:in `process_one'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/processor.rb:68:in `run'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/util.rb:15:in `watchdog'
/Users/username/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.3/lib/sidekiq/util.rb:24:in `block in safe_thread'

```

I dropped in a `binding.pry` at around line 135 of the `sidekiq-ent/unique.rb` class. Just to see what I was getting.

```
{"retry"=>true,
 "queue"=>"default",
 "unique_for"=>"600",
 "class"=>"MyJobClass",
 "args"=>[176],
 "jid"=>"df3129ab0bd172010bf4deda",
 "created_at"=>1614785566.767193,
 "enqueued_at"=>1614785566.768137}
```

Maybe that's fine... but, the job fails, then retries. And when it retries it contains the `unlocks_at` and `unique_token`. I haven't dug around in the Sidekiq source code enough to see if that's typical.

```
{"retry"=>true,
 "queue"=>"default",
 "unique_for"=>"600",
 "class"=>"MyJobClass",
 "args"=>[176],
 "jid"=>"df3129ab0bd172010bf4deda",
 "created_at"=>1614785566.767193,
 "enqueued_at"=>1614785629.462237,
 "error_message"=>"df3129ab0bd172010bf4deda is not holding a unique lock",
 "error_class"=>"ArgumentError",
 "failed_at"=>1614785609.482462,
 "retry_count"=>0,
 "unique_token"=>"3feefb073f7a21732307eb593d47a017da0c272c",
 "unlocks_at"=>"1614786229.4619572"}
 ```

The job(s) in question are using the following unique for option: `sidekiq_options unique_for: 10.minutes`. So, nothing too crazy.

**Comment by mperham** [comment]
Here's a way I can see this happening:

1. You add `sidekiq_options unique_for: 600.seconds`.
2. You **forget** to activate the feature in the initializer.
3. You deploy (1) and create a job.
4. You activate the feature and deploy again.

That sequence will get you a "unique" job without a unique lock and crash exactly like that. There's no easy workaround but you can monkeypatch `Unique.unlock` line 138 to be this so the job will run:

        return nil unless hash && timestamp

And you should be able to remove the monkeypatch once the "bad" jobs created between (1) and (4) are cleared out.

**Comment by csmith-tj** [comment]
You said something there that got me thinking. We were enabling the feature in our initializer, but I moved it up to the top of the file, before some other things we were doing with `throttle` and outside of the `Sidekiq.configure_server` block and now things are working. Not sure what changed between upgrades that caused it stop working, but still. The solution was easy.

Issue is resolved. Thanks!

**Comment by sealabcore** [comment]
The fix for us was to remove `Sidekiq::Enterprise.unique! unless Rails.env.test?` outside of the `Sidekiq.configure_server` block. Thanks!
