### ISSUE TITLE
Rails test environment can't find Sidekiq

### ISSUE THREAD

**Issue by caonUlisses** [mperham/sidekiq#4834]
### What is happening

Just installed Sidekiq, mounted the WebUI and everything is working great (Web and Console) but Sidekiq is not being located when `RAILS_ENV=test`.
If I run `RAILS_ENV=development bundle exec rails console` and try to call `Sidekiq`, it prints `Sidekiq`, but `RAILS_ENV=test bundle exec rails console` and then `Sidekiq` results on `uninitialized constant Sidekiq (NameError)`;

I have zero workers, just installed and hooked the WebUI. Sidekiq is my only custom initializer as well.

I saw a lot of people trying to load Workers with the wrong path/namespace (which is not the case, as I have no workers yet), but none with this particular situation.

If I comment out the router, initializer and log the gems on the console (with `RAILS_ENV=test`), I get: ``` [..., "sidekiq-6.1.3", ...]```. Also, `Gem.loaded_specs['sidekiq']` returns the gem info.

I restarted `spring`, rebuilt the Docker image with a clean cache and tried installing another gem (CanCanCan) just to see if I was doing something out of the ordinary, but I can load CanCanCan on both development and test environments.

This would be OK by me, but I can't run any tests due to this error.

### Version information

Ruby version: 3.0.0
Rails version: 6.1.3
Sidekiq version: 6.1.3

### Sidekiq initializer:

```ruby
Sidekiq.configure_server do |config|
  config.redis = {
    host: ENV['REDIS_HOST'],
    port: ENV['REDIS_PORT'] || '6379',
  }
end

Sidekiq.configure_client do |config|
  config.redis = {
    host: ENV['REDIS_HOST'],
    port: ENV['REDIS_PORT'] || '6379',
  }
end
```

### Error and backtrace:

```
/app/config/initializers/sidekiq.rb:1:in `<main>': uninitialized constant Sidekiq (NameError)
        from /usr/local/bundle/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        from /usr/local/bundle/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        from /usr/local/bundle/gems/railties-6.1.3/lib/rails/engine.rb:681:in `block in load_config_initializer'
        from /usr/local/bundle/gems/activesupport-6.1.3/lib/active_support/notifications.rb:205:in `instrument'
        from /usr/local/bundle/gems/railties-6.1.3/lib/rails/engine.rb:680:in `load_config_initializer'
        from /usr/local/bundle/gems/railties-6.1.3/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
        from /usr/local/bundle/gems/railties-6.1.3/lib/rails/engine.rb:633:in `each'
        from /usr/local/bundle/gems/railties-6.1.3/lib/rails/engine.rb:633:in `block in <class:Engine>'
        from /usr/local/bundle/gems/railties-6.1.3/lib/rails/initializable.rb:32:in `instance_exec'
        from /usr/local/bundle/gems/railties-6.1.3/lib/rails/initializable.rb:32:in `run'
        from /usr/local/bundle/gems/railties-6.1.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /usr/local/bundle/gems/railties-6.1.3/lib/rails/initializable.rb:50:in `each'
        from /usr/local/bundle/gems/railties-6.1.3/lib/rails/initializable.rb:50:in `tsort_each_child'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:415:in `call'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /usr/local/bundle/gems/railties-6.1.3/lib/rails/initializable.rb:60:in `run_initializers'
        from /usr/local/bundle/gems/railties-6.1.3/lib/rails/application.rb:384:in `initialize!'
        from /app/config/environment.rb:7:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /usr/local/bundle/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /usr/local/bundle/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /usr/local/bundle/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application.rb:106:in `preload'
        from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
        from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
        from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
        from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
        from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from -e:1:in `<main>'
```

Gem.loaded_specs['sidekiq'] result:
```
#<Bundler::StubSpecification:0x00007f024f33f920 @name="sidekiq", @version=#<Gem::Version "6.1.3">, @platform="ruby", @spec_fetcher=nil, @dependencies=[<Gem::Dependency type=:runtime name="connection_pool" requirements=">= 2.2.2">, <Gem::Dependency type=:runtime name="rack" requirements="~> 2.0">, <Gem::Dependency type=:runtime name="redis" requirements=">= 4.2.0">], @stub=#<Gem::StubSpecification:0x00007f02500cd600 @extension_dir=nil, @full_gem_path="/usr/local/bundle/gems/sidekiq-6.1.3", @gem_dir=nil, @ignored=nil, @loaded_from="/usr/local/bundle/specifications/sidekiq-6.1.3.gemspec", @data=#<Gem::StubSpecification::StubLine:0x00007f024f540170 @name="sidekiq", @version=#<Gem::Version "6.1.3">, @platform="ruby", @extensions=[], @full_name="sidekiq-6.1.3", @require_paths=["lib"]>, @name=nil, @spec=#<Gem::Specification:0x00007f024718ae98 @extension_dir=nil, @full_gem_path=nil, @gem_dir=nil, @ignored=nil, @bin_dir=nil, @cache_dir=nil, @cache_file=nil, @doc_dir=nil, @ri_dir=nil, @spec_dir=nil, @spec_file=nil, @gems_dir="/usr/local/bundle/gems", @base_dir="/usr/local/bundle", @loaded=false, @activated=false, @loaded_from="/usr/local/bundle/specifications/sidekiq-6.1.3.gemspec", @original_platform=nil, @installed_by_version=#<Gem::Version "3.2.3">, @autorequire=nil, @date=2021-01-21 00:00:00 UTC, @description="Simple, efficient background processing for Ruby.", @email=["mperham@gmail.com"], @homepage="https://sidekiq.org", @name="sidekiq", @post_install_message=nil, @signing_key=nil, @summary="Simple, efficient background processing for Ruby", @version=#<Gem::Version "6.1.3">, @authors=["Mike Perham"], @bindir="bin", @cert_chain=[], @dependencies=[<Gem::Dependency type=:runtime name="redis" requirements=">= 4.2.0">, <Gem::Dependency type=:runtime name="connection_pool" requirements=">= 2.2.2">, <Gem::Dependency type=:runtime name="rack" requirements="~> 2.0">], @executables=["sidekiq", "sidekiqmon"], @extensions=[], @extra_rdoc_files=[], @files=["bin/sidekiq", "bin/sidekiqmon"], @licenses=["LGPL-3.0"], @metadata={}, @platform="ruby", @rdoc_options=[], @require_paths=["lib"], @required_ruby_version=#<Gem::Requirement:0x00007f024718a768 @requirements=[[">=", #<Gem::Version "2.5.0">]]>, @required_rubygems_version=#<Gem::Requirement:0xsion=4, @test_files=[], @new_platform="ruby", @full_name="sidekiq-6.1.3", @source=#<Bundler::Source::Rubygems:0x17140 rubygems repository https://rubygems.org/ or installed locally> sidekiq-6.1.3>, @base_dir="/usr/local/bundle", @gems_dir="/usr/local/bundle/gems", @default_gem=false, @activated=true, @full_require_paths=["/usr/local/bundle/gems/sidekiq-6.1.3/lib"]>, @source=#<Bundler::Source::Rubygems:0x17140 rubygems repository https://rubygems.org/ or installed locally>, @_remote_specification=#<Gem::Specification:0x00007f024718ae98 @extension_dir=nil, @full_gem_path=nil, @gem_dir=nil, @ignored=nil, @bin_dir=nil, @cache_dir=nil, @cache_file=nil, @doc_dir=nil, @ri_dir=nil, @spec_dir=nil, @spec_file=nil, @gems_dir="/usr/local/bundle/gems", @base_dir="/usr/local/bundle", @loaded=false, @activated=false, @loaded_from="/usr/local/bundle/specifications/sidekiq-6.1.3.gemspec", @original_platform=nil, @installed_by_version=#<Gem::Version "3.2.3">, @autorequire=nil, @date=2021-01-21 00:00:00 UTC, @description="Simple, efficient background processing for Ruby.", @email=["mperham@gmail.com"], @homepage="https://sidekiq.org", @name="sidekiq", @post_install_message=nil, @signing_key=nil, @summary="Simple, efficient background processing for Ruby", @version=#<Gem::Version "6.1.3">, @authors=["Mike Perham"], @bindir="bin", @cert_chain=[], @dependencies=[<Gem::Dependency type=:runtime name="redis" requirements=">= 4.2.0">, <Gem::Dependency type=:runtime name="connection_pool" requirements=">= 2.2.2">, <Gem::Dependency type=:runtime name="rack" requirements="~> 2.0">], @executables=["sidekiq", "sidekiqmon"], @extensions=[], @extra_rdoc_files=[], @files=["bin/sidekiq", "bin/sidekiqmon"], @licenses=["LGPL-3.0"], @metadata={}, @platform="ruby", @rdoc_options=[], @require_paths=["lib"], @required_ruby_version=#<Gem::Requirement:0x00007f024718a768 @requirements=[[">=", #<Gem::Version "2.5.0">]]>, @required_rubygems_version=#<Gem::Requirement:0x00007f024718ab78 @requirements=[[">=", #<Gem::Version "0">]]>, @requirements=[], @rubygems_version="3.2.3", @specification_version=4, @test_files=[], @new_platform="ruby", @full_name="sidekiq-6.1.3", @source=#<Bundler::Source::Rubygems:0x17140 rubygems repository https://rubygems.org/ or installed locally> sidekiq-6.1.3>, @ignored=nil>
```

**Comment by mperham** [comment]
Post your Gemfile.

**Comment by caonUlisses** [comment]
I'm suspecting `dotenv-rails` has something to do with it, but can't confirm

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'bootstrap_form', '~> 4.0'
gem 'cancancan'
gem 'devise'
gem 'haml-rails', '~> 2.0'
gem 'http_accept_language'
gem 'jbuilder', '~> 2.7'
gem 'maxmind-db'
gem 'octicons'
gem 'octicons_helper'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rails', '~> 6.1.3'
gem 'rails-i18n', '~> 6.0.0'
gem 'redis', '~> 4.0'
gem 'sass-rails', '>= 6'
gem 'sidekiq'
gem 'turbo-rails'
gem 'webpacker', '~> 5.0'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails'
end

group :development do
  gem 'brakeman'
  gem 'haml_lint', require: false
  gem 'listen', '~> 3.3'
  gem 'rack-mini-profiler'
  gem 'rubocop'
  gem 'rubycritic'
  gem 'solargraph'
  gem 'spring'
  gem 'web-console', '>= 4.1.0'
end

group :test do
  gem 'faker'
end
```

**Comment by caonUlisses** [comment]
Yep. `dotenv-rails` being listed after sidekiq messed things up. Moving `gem dotenv-rails` to the top fixed the issue.
