### ISSUE TITLE
No such file or directory - getcwd

### ISSUE THREAD

**Issue by vishalzambre** [mperham/sidekiq#4867]
Ruby version: 2.6.5
Rails version: 5.2.4.5
Sidekiq / Pro / Enterprise version(s): Pro (Sidekiq v6.0.7 / Sidekiq Pro v5.0.1)

We just upgrade to pro and after upgrade started this problem to upload image through Sidekiq

`Sidekiq.yml`

```
:dynamic: true

:queues:
  - ['critical', 3]
  - ['default', 3]
  - ['high', 3]
  - ['mailers', 2]
  - ['searchkick', 2]
  - ['reviews', 2]
  - ['low', 1]
  - ['ahoy', 1]
development:
  :concurrency: 15
staging:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] %>
production:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] %>
:schedule:
```

Deployment env is ElasticBeanstalk AWS

Here is the backtrace `No such file or directory - getcwd`

```
/var/app/current/vendor/bundle/gems/netrc-0.11.0/lib/netrc.rb:26:in `pwd'
/var/app/current/vendor/bundle/gems/netrc-0.11.0/lib/netrc.rb:26:in `rescue in home_path'
/var/app/current/vendor/bundle/gems/netrc-0.11.0/lib/netrc.rb:14:in `home_path'
/var/app/current/vendor/bundle/gems/netrc-0.11.0/lib/netrc.rb:11:in `default_path'
/var/app/current/vendor/bundle/gems/netrc-0.11.0/lib/netrc.rb:51:in `read'
/var/app/current/vendor/bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:606:in `parse_url_with_auth!'
/var/app/current/vendor/bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:72:in `initialize'
/var/app/current/vendor/bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `new'
/var/app/current/vendor/bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/var/app/current/vendor/bundle/gems/cloudinary-1.9.1/lib/cloudinary/uploader.rb:324:in `call_api'
/var/app/current/vendor/bundle/gems/cloudinary-1.9.1/lib/cloudinary/uploader.rb:73:in `upload'
/var/app/current/vendor/bundle/gems/cloudinary-1.9.1/lib/cloudinary/carrier_wave/storage.rb:38:in `store!'
/var/app/current/vendor/bundle/gems/carrierwave-1.3.2/lib/carrierwave/uploader/store.rb:66:in `block in store!'
/var/app/current/vendor/bundle/gems/carrierwave-1.3.2/lib/carrierwave/uploader/callbacks.rb:15:in `with_callbacks'
/var/app/current/vendor/bundle/gems/carrierwave-1.3.2/lib/carrierwave/uploader/store.rb:65:in `store!'
/var/app/current/vendor/bundle/gems/carrierwave-1.3.2/lib/carrierwave/mounter.rb:100:in `each'
/var/app/current/vendor/bundle/gems/carrierwave-1.3.2/lib/carrierwave/mounter.rb:100:in `store!'
/var/app/current/vendor/bundle/gems/carrierwave-1.3.2/lib/carrierwave/mount.rb:395:in `store_featured_image!'
/var/app/current/vendor/bundle/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/var/app/current/vendor/bundle/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:236:in `block in halting_and_conditional'
/var/app/current/vendor/bundle/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:517:in `block in invoke_after'
/var/app/current/vendor/bundle/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:517:in `each'
/var/app/current/vendor/bundle/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:517:in `invoke_after'
/var/app/current/vendor/bundle/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:133:in `run_callbacks'
/var/app/current/vendor/bundle/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/callbacks.rb:342:in `create_or_update'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/persistence.rb:275:in `save'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/validations.rb:46:in `save'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:212:in `transaction'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:310:in `block in save'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:309:in `save'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/suppressor.rb:44:in `save'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/persistence.rb:428:in `block in update'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/opt/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:212:in `transaction'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/var/app/current/vendor/bundle/gems/activerecord-5.2.4.5/lib/active_record/persistence.rb:426:in `update'
/var/app/current/vendor/bundle/gems/active_interaction-3.6.2/lib/active_interaction/concerns/runnable.rb:79:in `block in run'
/var/app/current/vendor/bundle/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:98:in `run_callbacks'
/var/app/current/vendor/bundle/gems/active_interaction-3.6.2/lib/active_interaction/concerns/runnable.rb:77:in `run'
/var/app/current/vendor/bundle/gems/active_interaction-3.6.2/lib/active_interaction/concerns/runnable.rb:124:in `block in run'
/var/app/current/vendor/bundle/gems/active_interaction-3.6.2/lib/active_interaction/concerns/runnable.rb:124:in `tap'
/var/app/current/vendor/bundle/gems/active_interaction-3.6.2/lib/active_interaction/concerns/runnable.rb:124:in `run'
/var/app/current/vendor/bundle/gems/searchkick-3.1.2/lib/searchkick.rb:143:in `callbacks'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:196:in `execute_job'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
/var/app/current/vendor/bundle/gems/sidekiq-throttled-0.13.0/lib/sidekiq/throttled/middleware.rb:14:in `call'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/var/app/current/vendor/bundle/gems/sentry-sidekiq-4.3.0/lib/sentry/sidekiq/sentry_context_middleware.rb:20:in `call'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/var/app/current/vendor/bundle/gems/sidekiq-pro-5.0.1/lib/sidekiq/batch/middleware.rb:54:in `call'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:143:in `invoke'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:163:in `block in process'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/job_retry.rb:111:in `local'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/rails.rb:43:in `block in call'
/var/app/current/vendor/bundle/gems/activesupport-5.2.4.5/lib/active_support/execution_wrapper.rb:87:in `wrap'
/var/app/current/vendor/bundle/gems/activesupport-5.2.4.5/lib/active_support/reloader.rb:73:in `block in wrap'
/var/app/current/vendor/bundle/gems/activesupport-5.2.4.5/lib/active_support/execution_wrapper.rb:87:in `wrap'
/var/app/current/vendor/bundle/gems/activesupport-5.2.4.5/lib/active_support/reloader.rb:72:in `wrap'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/rails.rb:42:in `call'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:257:in `stats'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/job_logger.rb:13:in `call'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/job_retry.rb:78:in `global'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:124:in `block in dispatch'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/logger.rb:10:in `with'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/job_logger.rb:33:in `prepare'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:123:in `dispatch'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:162:in `process'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:78:in `process_one'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:68:in `run'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/util.rb:15:in `watchdog'
/var/app/current/vendor/bundle/gems/sidekiq-6.0.7/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by mperham** [comment]
Something is very wrong with your Ruby. `Dir.pwd` is raising that error. I'm not sure of the cause.
