### ISSUE TITLE
Issue while bundling: argument error malformed string 

### ISSUE THREAD

**Issue by rodrigohanuch** [mperham/sidekiq#4868]
Ruby version: 2.5.5 (rbenv)
Rails version: 6.0.3.1
Sidekiq / Pro / Enterprise version(s): Pro

I am currently having issues while bundling with `Bundler version 2.2.15`  while installing only since today. On Tuesday bundling worked correctly (I assume that is has to do with the recent update).

Something I noticed is that it happens to me and a co-worker, and we have the same OS, while others do not, and they do not present the same problem.

OS: macOS Big Sur v11.2.3 (20D91)

## Environment
``` 
Bundler       2.2.15
  Platforms   ruby, x86_64-darwin-20
Ruby          2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin20]
  Full Path   /Users/rodrigo/.rbenv/versions/2.5.5/bin/ruby
  Config Dir  /Users/rodrigo/.rbenv/versions/2.5.5/etc
RubyGems      2.7.6.2
  Gem Home    /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0
  Gem Path    /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0:/Users/rodrigo/.gem/ruby/2.5.0
  User Home   /Users/rodrigo
  User Path   /Users/rodrigo/.gem/ruby/2.5.0
  Bin Dir     /Users/rodrigo/.rbenv/versions/2.5.5/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1j  16 Feb 2021
  Loaded      OpenSSL 1.1.1j  16 Feb 2021
  Cert File   /Users/rodrigo/.rbenv/versions/2.5.5/openssl/ssl/cert.pem
  Cert Dir    /Users/rodrigo/.rbenv/versions/2.5.5/openssl/ssl/certs
Tools         
  Git         2.24.3 (Apple Git-128)
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

The output while bundling looks like this:
```shell
Fetching gem metadata from https://gems.contribsys.com/..
Retrying fetcher due to error (2/4): ArgumentError Malformed version number string 094f9263457e5ee1594396eb82a0906e77d10
..
Retrying fetcher due to error (3/4): ArgumentError Malformed version number string 094f9263457e5ee1594396eb82a0906e77d10
..
Retrying fetcher due to error (4/4): ArgumentError Malformed version number string 094f9263457e5ee1594396eb82a0906e77d10
..

## Backtrace
ArgumentError: Malformed version number string 094f9263457e5ee1594396eb82a0906e77d10
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/version.rb:208:in `initialize'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/version.rb:199:in `new'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/version.rb:199:in `new'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/version.rb:190:in `create'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/endpoint_specification.rb:15:in `initialize'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/fetcher.rb:141:in `new'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/fetcher.rb:141:in `block in specs'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/fetcher.rb:139:in `each'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/fetcher.rb:139:in `specs'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/fetcher.rb:117:in `block in specs_with_retry'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/retry.rb:40:in `run'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/retry.rb:30:in `attempt'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/fetcher.rb:116:in `specs_with_retry'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:427:in `block in fetch_names'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:424:in `each'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:424:in `fetch_names'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:419:in `block in remote_specs'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/index.rb:9:in `build'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:406:in `remote_specs'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:104:in `specs'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/lazy_specification.rb:72:in `__materialize__'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/spec_set.rb:86:in `block in materialize'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/spec_set.rb:82:in `map!'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/spec_set.rb:82:in `materialize'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/definition.rb:185:in `specs'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/definition.rb:173:in `resolve_remotely!'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/installer.rb:291:in `resolve_if_needed'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/installer.rb:83:in `block in run'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/process_lock.rb:12:in `block in lock'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/process_lock.rb:9:in `open'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/process_lock.rb:9:in `lock'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/installer.rb:72:in `run'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/installer.rb:24:in `install'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/cli/install.rb:64:in `run'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/cli.rb:259:in `block in install'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/settings.rb:115:in `temporary'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/cli.rb:258:in `install'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/cli.rb:30:in `dispatch'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/cli.rb:24:in `start'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/exe/bundle:49:in `block in <top (required)>'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
  /Users/rodrigo/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-2.2.15/exe/bundle:37:in `<top (required)>'
  /Users/rodrigo/.rbenv/versions/2.5.5/bin/bundle:23:in `load'
  /Users/rodrigo/.rbenv/versions/2.5.5/bin/bundle:23:in `<main>'
```

## Bundler settings

```
gems.contribsys.com
  Set for the current user (/Users/rodrigo/.bundle/config): "SECRET"
build.thin
  Set for the current user (/Users/rodrigo/.bundle/config): "--with-cflags=-Wno-error=implicit-function-declaration"
build.eventmachine
  Set for the current user (/Users/rodrigo/.bundle/config): "--with-cppflags=-I/usr/local/opt/openssl/include"
build.mysql2
  Set for the current user (/Users/rodrigo/.bundle/config): "--with-opt-dir=/usr/local/opt/openssl@1.1"
```

## Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
# git_source(:github) { |repo| "git@github.com:#{repo}.git" }

ruby '2.5.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '6.0.3.1'
# Use mysql2 as database
gem 'mysql2'
# Use pg as adapter for planner database
gem 'pg'
# Use elasticsearch for search engine capabilities
gem 'elasticsearch-model'
# Use webpacker for react
gem 'webpacker'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# uuid generator
gem 'uuid'

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', github: 'rails/jbuilder', branch: 'master'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# Null database adapter
gem 'activerecord-nulldb-adapter'

# Validate real mime type
gem 'terrapin'

# Streaming JSON parse
gem 'yajl-ruby', require: 'yajl'

# Middlewares
gem 'rack-attack'

group :development, :test do
  gem 'allocation_stats'
  gem 'bullet'
  gem 'faker'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  gem 'reek'
  gem 'rspec-rails', '~> 3.8'
  gem 'timecop'
end

group :development do
  # Static security vulnerability scan
  gem 'brakeman'
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'skunk'
  gem 'sql_tracker'
end

group :test do
  gem 'codecov', '>= 0.2.6'
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'json-schema'
  gem 'rspec-sidekiq'
  gem 'simplecov', '0.17.1', require: false
  gem 'test-prof'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# for permissions
gem 'pundit'

gem 'jsonapi-serializer'
gem 'oj'

gem 'rubocop', require: false
gem 'rubocop-faker', require: false
gem 'rubocop-performance', require: false

gem 'countries'

gem 'aws-sdk-s3'

gem 'rest-client'
# Spreadsheet support
gem 'caxlsx'
gem 'down', '~> 5.0'
gem 'fast-polylines'
gem 'rubyzip', '~> 1.2'
gem 'zip-zip'

source 'https://gems.contribsys.com/' do
  gem 'sidekiq-pro'
end

gem 'redis'
gem 'redis-namespace'
gem 'redis-rails'

# bunny as rabbitMQ ruby implementation
gem 'bunny', '>= 2.14.4'

gem 'sentry-raven'

gem 'ddtrace', '>= 0.27.0'
gem 'elasticsearch-persistence'

gem 'scout_apm'

gem 'active_model_serializers'
gem 'redis-objects'

gem 'rgeo'
gem 'rgeo-geojson'
```

Thanks! 😄

**Comment by mperham** [comment]
First thing to do:

```
rm -rf ~/.bundle/cache/compact_index/*contribsys*
```

Bundler has a bug caching the contribsys server metadata. I don't recognize that error so I'm not sure what might be causing it.

**Comment by rodrigohanuch** [comment]
Thanks! That solved it!
