### ISSUE TITLE
Error ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/job_retry.rb:79:in

### ISSUE THREAD

**Issue by cassiompf** [mperham/sidekiq#4889]
Ruby version: 3.0.1
Rails version:  Rails 6.1.3.1
Sidekiq / Pro / Enterprise version(s): 6.2.1

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

I am currently having a lot of problems with sidekiq on my vps server. Every time I deploy to my Ruby on Rails application, I stop and start the sidekiq service. At first it looks like it starts well, but then some errors appear on the "systemctl status sidekiq" screen, like these: https://i.imgur.com/Ku7SQi5.png

```
Apr 30 20:01:17 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/job_retry.rb:79:in `global'
Apr 30 20:01:17 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
Apr 30 20:01:17 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/logger.rb:11:in `with'
Apr 30 20:01:17 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/job_logger.rb:33:in `prepare'
Apr 30 20:01:17 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:123:in `dispatch'
Apr 30 20:01:17 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:162:in `process'
Apr 30 20:01:17 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:78:in `process_one'
Apr 30 20:01:17 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:68:in `run'
Apr 30 20:01:17 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:43:in `watchdog'
Apr 30 20:01:17 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:52:in `block in safe_thread'
```

The most interesting thing is that he tries to use the folder using ruby in version 3.0.0 and I specified in Capfile to use 3.0.1 when deploying and also in the service file is 3.0.1. Is it necessary to restart sidekiq when the rails application is rebuilt? Is it necessary to restart sidekiq when the rails application is rebuilt?

In my capfile file I left:

```
set: rvm_type,: system
set: rvm_ruby_version, '3.0.1'
```

My sidekiq.service service

```
#
# This file tells systemd how to run Sidekiq as a 24/7 long-running daemon.
#
# Customize this file based on your bundler location, app directory, etc.
# Customize and copy this into /usr/lib/systemd/system (CentOS) or /lib/systemd/system (Ubuntu).
# Then run:
#   - systemctl enable sidekiq
#   - systemctl {start,stop,restart} sidekiq
#
# This file corresponds to a single Sidekiq process.  Add multiple copies
# to run multiple processes (sidekiq-1, sidekiq-2, etc).
#
# Use `journalctl -u sidekiq -rn 100` to view the last 100 lines of log output.
#
[Unit]
Description=sidekiq
# start us only once the network and logging subsystems are available,
# consider adding redis-server.service if Redis is local and systemd-managed.
After=syslog.target network.target

# See these pages for lots of options:
#
#   https://www.freedesktop.org/software/systemd/man/systemd.service.html
#   https://www.freedesktop.org/software/systemd/man/systemd.exec.html
#
# THOSE PAGES ARE CRITICAL FOR ANY LINUX DEVOPS WORK; read them multiple
# times! systemd is a critical tool for all developers to know and understand.
#
[Service]
#
#      !!!!  !!!!  !!!!
#
# As of v6.0.6, Sidekiq automatically supports systemd's `Type=notify` and watchdog service
# monitoring. If you are using an earlier version of Sidekiq, change this to `Type=simple`
# and remove the `WatchdogSec` line.
#
#      !!!!  !!!!  !!!!
#
Type=notify
# If your Sidekiq process locks up, systemd's watchdog will restart it within seconds.
WatchdogSec=10

WorkingDirectory=/var/www/myserver/current
# If you use rbenv:
# ExecStart=/bin/bash -lc 'exec /home/deploy/.rbenv/shims/bundle exec sidekiq -e production'
# If you use the system's ruby:
# ExecStart=/usr/local/bin/bundle exec sidekiq -e production
# If you use rvm in production without gemset and your ruby version is 2.6.5
# ExecStart=/home/deploy/.rvm/gems/ruby-2.6.5/wrappers/bundle exec sidekiq -e production
# If you use rvm in production with gemset and your ruby version is 2.6.5
ExecStart=/usr/local/rvm/gems/ruby-3.0.1/wrappers/bundle exec sidekiq

# Use `systemctl kill -s TSTP sidekiq` to quiet the Sidekiq process

# !!! Change this to your deploy user account !!!
#User=root
#Group=root
#UMask=0002

# Greatly reduce Ruby memory fragmentation and heap usage
# https://www.mikeperham.com/2018/04/25/taming-rails-memory-bloat/
Environment=MALLOC_ARENA_MAX=2

# if we crash, restart
RestartSec=1
Restart=on-failure

# output goes to /var/log/syslog (Ubuntu) or /var/log/messages (CentOS)
StandardOutput=syslog
StandardError=syslog

# This will default to "bundler" if we don't specify it
SyslogIdentifier=sidekiq

[Install]
WantedBy=multi-user.target
```

When i execute `journalctl -u sidekiq -rn 100`
```
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:52:in `block in safe_thread'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:43:in `watchdog'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:68:in `run'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:78:in `process_one'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:162:in `process'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:123:in `dispatch'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/job_logger.rb:33:in `prepare'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/logger.rb:11:in `with'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/job_retry.rb:79:in `global'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/job_logger.rb:13:in `call'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:257:in `stats'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/rails.rb:13:in `call'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/reloader.rb:71:in `wrap'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/reloader.rb:72:in `block in wrap'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/rails.rb:14:in `block in call'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/job_retry.rb:112:in `local'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:163:in `block in process'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:133:in `invoke'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:196:in `execute_job'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activejob-6.1.3.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activejob-6.1.3.1/lib/active_job/execution.rb:23:in `execute'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `instance_exec'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activejob-6.1.3.1/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/reloader.rb:71:in `wrap'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/execution_wrapper.rb:84:in `wrap'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/reloader.rb:72:in `block in wrap'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activejob-6.1.3.1/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activejob-6.1.3.1/lib/active_job/execution.rb:25:in `block in execute'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activejob-6.1.3.1/lib/active_job/execution.rb:47:in `perform_now'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `instance_exec'
Apr 30 20:07:15 myserver.com.br sidekiq[78538]: /var/www/myserver/shared/bundle/ruby/3.0.0/gems/activejob-6.1.3.1/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
```

NOTE: I'm using sidekiq and the sidekiq/cron gem, all in the default queue. My jobs are all in the default queue. I also configured the actionMailer to use the default queue and the perform_later method still doesn't work. 

my config/sidekiq.yml

```
:concurrency: 2
:queues:
  - default
```

In my application.rb I added:
```
config.active_job.queue_adapter = :sidekiq
config.action_mailer.deliver_later_queue_name = 'default'
```

If anyone can help me I am very grateful.

**Comment by mperham** [comment]
Everything looks ok. Neither of your backtraces are the "full" backtrace with error message so I can't tell what's wrong.

**Comment by cassiompf** [comment]
I will try to switch to rbenv to see what happens :/

**Comment by cassiompf** [comment]
I updated to rbenv and the error continues.  :/

**Comment by mperham** [comment]
If you can run the process manually and reproduce the error, that would be easiest.

**Comment by cassiompf** [comment]
I managed to solve it here, I had to look at the logs in "/var/log/syslog". It was an error in my code. Sorry for the trouble there
