### ISSUE TITLE
redis connection error log is repeating on heroku after I removed worker(sidekiq)...

### ISSUE THREAD

**Issue by kikikiblue** [mperham/sidekiq#4890]
* redis (4.2.2)
* sidekiq (6.2.1)
* my initilaizer sidekiq.rb
```
redis_conn = proc {
  if ENV["REDISCLOUD_URL"]
    Redis.new(:url => ENV["REDISCLOUD_URL"])
  else
    Redis.new
  end
}

Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(size: 5, &redis_conn)
end

Sidekiq.configure_server do |config|
  config.redis = ConnectionPool.new(size: 10, &redis_conn)
end

#https://github.com/mperham/sidekiq/blob/master/5.0-Upgrade.md
Sidekiq::Extensions.enable_delay!
```
 
on heroku, this error is repeating. 
I changed my redis add-on from heroku-redis to rediscloud, 
and I tested connection to rediscloud, and it was ok. 
```
$ heroku run rails console
Running rails console on ⬢ myapp... up, run.4809 (Standard-1X)
Loading production environment (Rails 5.2.4.3)
irb(main):001:0> $redis = Redis.new(:url => ENV["REDISCLOUD_URL"])
=> #<Redis client v4.2.2 for redis://redis-address-blabla>
irb(main):002:0> $redis.set("mykey", "hello world")
=> "OK"
irb(main):003:0> $redis.get("mykey")
=> "hello world"
```
so I removed worker.1 for making problem clear, but worker.1 error log is still repeating.
Now there is no sidekiq process but the log is still repeating... 
Please check this logs...
```
2021-04-30T15:40:40.016419+00:00 app[worker.1]: pid=4 tid=gsrcm38fk ERROR: heartbeat: Error connecting to Redis on some-aws-ec2-address:28179 (Redis::TimeoutError)
2021-04-30T15:40:52.306618+00:00 app[worker.1]: pid=4 tid=gsrcm38as ERROR: Error connecting to Redis on some-aws-ec2-address:28179 (Redis::TimeoutError)
2021-04-30T15:40:52.306635+00:00 app[worker.1]: pid=4 tid=gsrcm38as WARN: Redis::CannotConnectError: Error connecting to Redis on some-aws-ec2-address:28179 (Redis::TimeoutError)
2021-04-30T15:40:52.306689+00:00 app[worker.1]: pid=4 tid=gsrcm38as WARN: /app/vendor/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis/client.rb:362:in `rescue in establish_connection'
2021-04-30T15:40:52.306691+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis/client.rb:343:in `establish_connection'
2021-04-30T15:40:52.306692+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis/client.rb:107:in `block in connect'
2021-04-30T15:40:52.306692+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis/client.rb:308:in `with_reconnect'
2021-04-30T15:40:52.306693+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis/client.rb:106:in `connect'
2021-04-30T15:40:52.306693+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.13.0/lib/new_relic/agent/instrumentation/redis.rb:181:in `block in connect'
2021-04-30T15:40:52.306694+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.13.0/lib/new_relic/agent/tracer.rb:371:in `capture_segment_error'
2021-04-30T15:40:52.306694+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.13.0/lib/new_relic/agent/instrumentation/redis.rb:180:in `connect'
2021-04-30T15:40:52.306694+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis/client.rb:381:in `ensure_connected'
2021-04-30T15:40:52.306695+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis/client.rb:233:in `block in process'
2021-04-30T15:40:52.306695+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis/client.rb:320:in `logging'
2021-04-30T15:40:52.306696+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis/client.rb:232:in `process'
2021-04-30T15:40:52.306696+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis/client.rb:126:in `call'
2021-04-30T15:40:52.306697+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.13.0/lib/new_relic/agent/instrumentation/redis.rb:76:in `block in call'
2021-04-30T15:40:52.306697+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.13.0/lib/new_relic/agent/tracer.rb:371:in `capture_segment_error'
2021-04-30T15:40:52.306697+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.13.0/lib/new_relic/agent/instrumentation/redis.rb:75:in `call'
2021-04-30T15:40:52.306698+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis.rb:1975:in `block in zrangebyscore'
2021-04-30T15:40:52.306698+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis.rb:69:in `block in synchronize'
2021-04-30T15:40:52.306699+00:00 app[worker.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
2021-04-30T15:40:52.306699+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis.rb:69:in `synchronize'
2021-04-30T15:40:52.306700+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis.rb:1974:in `zrangebyscore'
2021-04-30T15:40:52.306700+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.1.2/lib/sidekiq/scheduled.rb:18:in `block (2 levels) in enqueue_jobs'
2021-04-30T15:40:52.306701+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.1.2/lib/sidekiq/scheduled.rb:16:in `each'
2021-04-30T15:40:52.306701+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.1.2/lib/sidekiq/scheduled.rb:16:in `block in enqueue_jobs'
2021-04-30T15:40:52.306702+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.1.2/lib/sidekiq.rb:98:in `block in redis'
2021-04-30T15:40:52.306702+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:63:in `block (2 levels) in with'
2021-04-30T15:40:52.306702+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:62:in `handle_interrupt'
2021-04-30T15:40:52.306703+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:62:in `block in with'
2021-04-30T15:40:52.306703+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:59:in `handle_interrupt'
2021-04-30T15:40:52.306704+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:59:in `with'
2021-04-30T15:40:52.306704+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.1.2/lib/sidekiq.rb:95:in `redis'
2021-04-30T15:40:52.306705+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.1.2/lib/sidekiq/scheduled.rb:15:in `enqueue_jobs'
2021-04-30T15:40:52.306705+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.1.2/lib/sidekiq/scheduled.rb:78:in `enqueue'
2021-04-30T15:40:52.306705+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.1.2/lib/sidekiq/scheduled.rb:70:in `block in start'
2021-04-30T15:40:52.306706+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.1.2/lib/sidekiq/util.rb:15:in `watchdog'
2021-04-30T15:40:52.306706+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.1.2/lib/sidekiq/util.rb:24:in `block in safe_thread'
2021-04-30T15:40:52.307011+00:00 app[worker.1]: Cache read: exception:3989005630
2021-04-30T15:40:52.308506+00:00 app[worker.1]: Cache write: exception:3989005630 ({:expires_in=>5 minutes})
```
I am sorry for this kind of sudden and looked-not-connected with sidekiq question, but any tips or experiece will be helpful. 
why this heartbeat connection error is repeating even though there is no worker on heroku?

**Comment by kikikiblue** [comment]
It was heroku's issue.
Sorry for issuing.

**Comment by dchun** [comment]
How did you fix the issue?

**Comment by kikikiblue** [comment]
> How did you fix the issue?

I opened a ticket at Heroku.com and They resolved their system's problem. I remember tt was an cloud(amazon) network issue.
