### ISSUE TITLE
Rubydocs for Sidekiq Pro

### ISSUE THREAD

**Issue by mollerhoj** [mperham/sidekiq#4898]
To better understand how Sidekiq Pros Batches work I'd like to read their documentation. (Besides the wiki)

However, https://www.rubydoc.info/gems/sidekiq/5.2.3 does not cover the Pro features.

Installing the documentation locally could be an option, but unfortunately

`gem install sidekiq-pro --document --source "https://gems.contribsys.com/"`

Defaults to installing some fake gem:

```
Fetching sidekiq-pro-0.0.3.gem
/!\ ಠ‿ಠ Watch out ! This is not the real sidekiq-pro gem. /!\
Successfully installed sidekiq-pro-0.0.3
Parsing documentation for sidekiq-pro-0.0.3
Installing ri documentation for sidekiq-pro-0.0.3
Done installing documentation for sidekiq-pro after 0 seconds
1 gem installed
```
By changing the sources setting in .gemrc file I managed to get to:

```
#<Thread:0x00007fa02a8cb7f8@/Users/mollerhoj/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	6: from /Users/mollerhoj/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
	5: from /Users/mollerhoj/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
	4: from /Users/mollerhoj/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/source.rb:206:in `download'
	3: from /Users/mollerhoj/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:158:in `download'
	2: from /Users/mollerhoj/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:298:in `cache_update_path'
	1: from /Users/mollerhoj/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:262:in `fetch_path'
/Users/mollerhoj/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:244:in `fetch_http': bad response Unauthorized 401 (https://gems.contribsys.com/gems/sidekiq-pro-5.2.2.gem) (Gem::RemoteFetcher::FetchError)
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Unauthorized 401 (https://gems.contribsys.com/gems/sidekiq-pro-5.2.2.gem)
 ```
 
 As `https://gems.contribsys.com/gems/sidekiq-pro-5.2.2.gem` requires as username and password

**Comment by mperham** [comment]
The wiki is the only official documentation for Batches because it's a private gem. Of course you can build and view the rdoc locally:

```
rdoc sidekiq-pro
open http://localhost:8214
ri --server
# now refresh the browser page to connect
```
