### ISSUE TITLE
ArgumentError: Bad Vixie-style specification 1/6 with crontab: "1/6 * * * *"

### ISSUE THREAD

**Issue by pboling** [mperham/sidekiq#4901]
Ruby version: 2.7.3
grape version: 1.5.3
actionpack, actionview, activemodel, activerecord, activesupport versions: 5.2.6
Sidekiq / Pro / Enterprise version(s): sidekiq 6.2.1, sidekiq-pro 5.2.2, sidekiq-ent 2.2.2

I want to stagger my jobs by having them not all start at the 0th minute of the hour.  As such I have my crotabs set to start some jobs on the 1st minute, 16th minute, or 6th minute:
```
        mgr.register("1/6 * * * *", "MonitorSentEmailsWorker", queue: "ms_graph")
        mgr.register("16/30 * * * *", "MonitorInboxEmailsWorker", queue: "ms_graph")
        mgr.register("6/30 * * * *", "MonitorEmailFolderSyncWorker", queue: "ms_graph")
```

These configurations are declared to be Bad Vixie by `sidekiq-ent/periodic/cron.rb`. 🗡️ Help!

*Initializer*
```
# frozen_string_literal: true

require "sidekiq"
require "sidekiq-ent" # also loads sidekiq/pro
require "sidekiq/pro/expiry"
require "sidekiq-statistic"

Sidekiq::Enterprise.unique! unless RACK_ENV == "test"

Sidekiq.configure_server do |config|
  config.redis = { url: REDIS_URL, db: REDIS_DB_NUM }
  config.logger.level = LOG_SEVERITY

  config.periodic do |mgr|
    pacific_time_zone = ActiveSupport::TimeZone.new("America/Los_Angeles")
    mgr.tz = ActiveSupport::TimeZone.new("UTC")

    # ONCE A MONTH
    mgr.register("0 0 1 * *", "UpdateOldTagRelationsWorker", queue: "bulk")

    # ONCE A WEEK
    mgr.register("0 0 * * 0", "CleanupClientCompaniesWorker", queue: "bulk")
    mgr.register("0 0 * * 0", "UpdateCompanyCurrentEmploymentsWorker", queue: "bulk")
    mgr.register("0 3 * * 0", "UpdateTitleRelationsCountWorker", queue: "bulk")
    mgr.register("0 19 * * 6", "UpdateAllCompanyXrayAnalyticsWorker", queue: "bulk")

    # WEEKDAYS
    mgr.register("0 22 * * 1-5", "ApplicationAutoRejectWorker", queue: "bulk") unless IS_HOLIDAYS

    # ONCE A DAY
    mgr.register("0 2 * * *", "SetGeocodeWorker", queue: "bulk")
    mgr.register("0 2 * * *", "UpdateCompanyStatusWorker", queue: "api")
    mgr.register("0 3 * * *", "CleanPeopleCategoriesWorker", queue: "bulk")
    mgr.register("0 3 * * *", "CleanupDupeMachineCodedRatingsWorker", queue: "bulk")
    mgr.register("0 3 * * *", "UpdatePeopleTrendingWorker", queue: "bulk")
    mgr.register("0 4 * * *", "ClientJobStatsWorker", queue: "api")
    mgr.register("0 4 * * *", "DNCJobsWorker", queue: "api")
    mgr.register("0 4 * * *", "DestroyDupeEmailAddressesWorker", queue: "merge")
    mgr.register("0 4 * * *", "DestroyEmptyChangelogActivityWorker", queue: "bulk")
    mgr.register("0 4 * * *", "ExpireCandidatesMatchesWorker", queue: "api")
    mgr.register("0 4 * * *", "ExpireClientMatchesWorker", queue: "api")
    mgr.register("0 4 * * *", "FixNullRejectReasonWorker", queue: "bulk")
    mgr.register("0 4 * * *", "S3BulkImportWorker", queue: "api")
    mgr.register("0 4 * * *", "SetSourcerToNullWorker", queue: "api")
    mgr.register("0 4 * * *", "UpdateJobLifecycleWorker", queue: "api")
    mgr.register("0 5 * * *", "MergeDupeLinkedinIdsCompaniesWorker", queue: "bulk")
    mgr.register("0 5 * * *", "S3BulkImportMonitoringWorker", queue: "api")
    mgr.register("0 7 * * *", "UpdateExternalApplicationCandidatesWorker", queue: "bulk")
    mgr.register("0 9 * * *", "UpdateAllAnalyticsWorker", queue: "bulk")
    mgr.register("0 9 * * *", "UpdateAllJobStatsWorker", queue: "bulk")
    mgr.register("0 9 * * *", "UpdateAllUserJobStatsWorker", queue: "bulk")
    unless IS_HOLIDAYS
      mgr.register("0 3 * * *", "UpdatePeopleStatusWorker", queue: "bulk")
      mgr.register("0 5 * * *", "SnoozeLeadsWorker", queue: "bulk")
    end
    mgr.register("01 10 * * *", "EmailAutomation::RetainedQueueAggregatorWorker", queue: "ms_graph", tz: pacific_time_zone)

    # HOURLY
    # Queue up every mail folder, to be synced.
    #   Sent Items folders will run every six minutes at:
    #     0:01, 0:07, 0:13, 0:19, 0:25, 0:31, 0:37, 0:43, 0:49, 0:55
    #   Inbox folders will run at:
    #     0:16, 0:46
    #   Other folders (not Sent Items, not Inbox) will run at:
    #     12am, 6am, 12pm, 6pm
    # The Email Folder Sync (determining which folders an account has that should be synced) will run:
    #     0:06, 0:36
    mgr.register("1/6 * * * *", "MonitorSentEmailsWorker", queue: "ms_graph")
    mgr.register("16/30 * * * *", "MonitorInboxEmailsWorker", queue: "ms_graph")
    mgr.register("0 */6 * * *", "MonitorOtherEmailsWorker", queue: "ms_graph")
    mgr.register("6/30 * * * *", "MonitorEmailFolderSyncWorker", queue: "ms_graph")
  end
  ActiveRecord::Base.establish_connection(DATABASE_URL)

  config.server_middleware do |chain|
    chain.add CurrentUserMiddleware, user_id: 192
  end
end

Sidekiq.configure_client do |config|
  config.redis = { url: REDIS_URL, db: REDIS_DB_NUM }
end

Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  if RACK_ENV == "production" || RACK_ENV == "staging"
    user == SIDEKIQ_USER && password == SIDEKIQ_PWD
  else
    true
  end
end

Sidekiq::Statistic.configuration do |config|
  config.max_timelist_length = 100_000
end
```

*sidekiq.yml*
```
# When choosing a queue, make sure that we know that critical must be sent right away regardless
# of the line in api, for example. We should send emails and anything client-related notification-wise
# through "critical" if it potentially needs to get there in the moment. We should queue with "bulk" when we
# run any large importing tasks or entire database record updates task.
# There's also a queue order, which is top down in importance in the list below.
---
:logfile: log/sidekiq.log
:pidfile: tmp/pids/sidekiq.pid
:timeout: 30
:queues:
  - default
  - chewy
  - [critical, 5]
  - [api, 4]
  - [ms_graph, 3]
  - bulk
  - ds
  - merge

production:
  :verbose: false
sutro-demo:
  :verbose: false
staging:
  :verbose: false
development:
  :concurrency: 6
  :verbose: true
```

debug:
```
2021-05-13T22:28:19.611Z pid=77963 tid=2hlv DEBUG: {:queues=>["default", "chewy", "critical", "critical", "critical", "critical", "critical", "api", "api", "api", "api", "ms_graph", "ms_graph", "ms_graph", "bulk", "ds", "merge"], :labels=>[], :concurrency=>6, :require=>"./config/environment.rb", :strict=>false, :environment=>nil, :timeout=>30, :poll_interval_average=>nil, :average_scheduled_poll_interval=>5, :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x00007f88a5cadae8>, #<Proc:0x00007f88a5f14638 /Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/sidekiq.rb:90>], :death_handlers=>[#<Proc:0x00007f88a175c9d0 /Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-pro-5.2.2/lib/sidekiq/batch/death.rb:58 (lambda)>, #<Proc:0x00007f88af248cb0 /Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/unique.rb:180 (lambda)>], :lifecycle_events=>{:startup=>[], :quiet=>[#<Proc:0x00007f88a7a33ec8 /Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-pro-5.2.2/lib/sidekiq/pro/config.rb:88>], :shutdown=>[#<Proc:0x00007f88a17603f0 /Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/election.rb:12>, #<Proc:0x00007f88ab9965c0 /Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic.rb:89>], :heartbeat=>[], :leader=>[#<Proc:0x00007f88ab9965e8 /Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic.rb:77>, #<Proc:0x00007f88afe05ff8 /Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/census.rb:180>], :fork=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :reloader=>#<Proc:0x00007f88a11136f0 /Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq.rb:38>, :logfile=>"log/sidekiq.log", :pidfile=>"tmp/pids/sidekiq.pid", :production=>{:verbose=>false}, :"sutro-demo"=>{:verbose=>false}, :staging=>{:verbose=>false}, :verbose=>true, :config_file=>"./config/sidekiq/sidekiq.yml", :backup_limit=>1000, :identity=>"CrunchyRiver.local:77963:70fe801fa6c4", :fetch=>#<Sidekiq::BasicFetch:0x00007f88afc93b98 @paused=#<Set: {}>, @changed=true, @original=["default", "chewy", "critical", "critical", "critical", "critical", "critical", "api", "api", "api", "api", "ms_graph", "ms_graph", "ms_graph", "bulk", "ds", "merge"], @options={...}, @strictly_ordered_queues=false, @queues=["queue:default", "queue:chewy", "queue:critical", "queue:critical", "queue:critical", "queue:critical", "queue:critical", "queue:api", "queue:api", "queue:api", "queue:api", "queue:ms_graph", "queue:ms_graph", "queue:ms_graph", "queue:bulk", "queue:ds", "queue:merge"]>}
2021-05-13T22:28:19.618Z pid=77963 tid=2hwj WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"leader"}
```

Backtrace:
```
2021-05-13T22:46:46.321Z pid=79450 tid=2gvm WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"leader"}
2021-05-13T22:46:46.321Z pid=79450 tid=2gvm WARN: ArgumentError: Bad Vixie-style specification 1/6
2021-05-13T22:46:46.322Z pid=79450 tid=2gvm WARN: /Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/cron.rb:178:in `block in parse_element'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/cron.rb:164:in `map'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/cron.rb:164:in `parse_element'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/cron.rb:274:in `time_specs'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/cron.rb:108:in `next'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/static_loop.rb:22:in `next_occurrence'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/config.rb:104:in `block in queue_for'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/config.rb:103:in `each'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/config.rb:103:in `queue_for'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/config.rb:96:in `finish!'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/manager.rb:60:in `persist'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic.rb:82:in `block (2 levels) in <top (required)>'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:87:in `block in fire_event'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:86:in `each'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:86:in `fire_event'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/senate.rb:93:in `stage_coup!'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/senate.rb:101:in `cycle'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:43:in `watchdog'
/Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:52:in `block in safe_thread'
2021-05-13T22:46:46.322Z pid=79450 tid=2gvm DEBUG: Licensed user: ********
2021-05-13T22:46:46.323Z pid=79450 tid=2gvm INFO: Gained leadership of the cluster
2021-05-13T22:46:46.323Z pid=79450 tid=2gvm DEBUG: Loading Sidekiq Enterprise Lua extensions
```

**Comment by pboling** [comment]
<img width="902" alt="Screen Shot 2021-05-13 at 3 30 52 PM" src="https://user-images.githubusercontent.com/19505/118197263-6fe34900-b403-11eb-8bcb-ae009fe7393e.png">
What I'm hoping to do ☝️

**Comment by pboling** [comment]
Of note, the crontab parser [gem `fugit`](https://github.com/floraison/fugit) is able to parse this crontab, so there may be value in leveraging that work:
```
[1] pry(main)> Fugit.parse('1/6 * * * *')
=> #<Fugit::Cron:0x00007fa8d4226008 @cron_s=nil, @hours=nil, @minutes=[1], @monthdays=nil, @months=nil, @original="1/6 * * * *", @seconds=[0], @timezone=nil, @weekdays=nil, @zone=nil>
```

**Comment by mperham** [comment]
Interesting, I’ve never seen that syntax before; you can use “1,7,13,19,25,31,37,43,49,55 …” as a workaround today. Adding support would be low priority but that cron parsing code is open source if you want to hack on a PR which adds support. The original URL of the source should be at the top of lib/Sidekiq-ent/periodic/cron.rb.

**Comment by pboling** [comment]
I looked for the source, but I was not able to find it.  Is it in this repo?

**Comment by mperham** [comment]
No, `bundle open sidekiq-ent`
