### ISSUE TITLE
Sentinel failover causes 'Redis::CommandError: NOREPLICAS'

### ISSUE THREAD

**Issue by harmjanblok** [mperham/sidekiq#4940]
We use sidekiq with a redis sentinel setup (three instances) and we're trying to do a graceful failover to another instance using `sentinel failover redis-master`. However during failover we get a `Redis::CommandError: NOREPLICAS` error (see stacktrace below).

The change in 267b4cc601460f23d127a336fcf86f5be44ccce5 seems however to catch this exact case. Could it be that this error is catched for the first retry, but raised for the second 'retry'. Should maybe the retry interval and maximum number of retries be defined?

```bash
sidekiq-queue-779f764659-gbvw7 sidekiq-queue 2021-07-09T15:28:09.255Z pid=1 tid=119 class=Worker jid=4e0196a9a1e20e47bb8c5696 INFO: start
sidekiq-queue-779f764659-gbvw7 sidekiq-queue Start 4e0196a9a1e20e47bb8c5696
sidekiq-queue-779f764659-gbvw7 sidekiq-queue Done 4e0196a9a1e20e47bb8c5696
sidekiq-queue-779f764659-gbvw7 sidekiq-queue 2021-07-09T15:28:11.256Z pid=1 tid=119 class=Worker jid=4e0196a9a1e20e47bb8c5696 elapsed=2.0 INFO: done
sidekiq-queue-779f764659-gbvw7 sidekiq-queue 2021-07-09T15:28:11.261Z pid=1 tid=119 ERROR: Error fetching job: NOREPLICAS Not enough good replicas to write.
sidekiq-queue-779f764659-gbvw7 sidekiq-queue 2021-07-09T15:28:11.261Z pid=1 tid=119 WARN: Redis::CommandError: NOREPLICAS Not enough good replicas to write.
sidekiq-queue-779f764659-gbvw7 sidekiq-queue 2021-07-09T15:28:11.261Z pid=1 tid=119 WARN: /usr/local/bundle/gems/redis-4.3.1/lib/redis/client.rb:147:in `call'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/redis-4.3.1/lib/redis/client.rb:241:in `block in call_with_timeout'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/redis-4.3.1/lib/redis/client.rb:315:in `with_socket_timeout'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/redis-4.3.1/lib/redis/client.rb:240:in `call_with_timeout'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/redis-4.3.1/lib/redis.rb:1232:in `block in _bpop'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/redis-4.3.1/lib/redis.rb:70:in `block in synchronize'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/lib/ruby/3.0.0/monitor.rb:202:in `synchronize'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/lib/ruby/3.0.0/monitor.rb:202:in `mon_synchronize'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/redis-4.3.1/lib/redis.rb:70:in `synchronize'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/redis-4.3.1/lib/redis.rb:1229:in `_bpop'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/redis-4.3.1/lib/redis.rb:1274:in `brpop'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/sidekiq-6.2.1/lib/sidekiq/fetch.rb:47:in `block in retrieve_work'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/sidekiq-6.2.1/lib/sidekiq.rb:98:in `block in redis'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/sidekiq-6.2.1/lib/sidekiq.rb:95:in `redis'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/sidekiq-6.2.1/lib/sidekiq/fetch.rb:47:in `retrieve_work'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:83:in `get_one'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:95:in `fetch'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:77:in `process_one'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:68:in `run'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:43:in `watchdog'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue /usr/local/bundle/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:52:in `block in safe_thread'
sidekiq-queue-779f764659-gbvw7 sidekiq-queue 2021-07-09T15:28:13.259Z pid=1 tid=12d ERROR: heartbeat: NOREPLICAS Not enough good replicas to write.
sidekiq-queue-779f764659-gbvw7 sidekiq-queue 2021-07-09T15:28:18.300Z pid=1 tid=119 INFO: Redis is online, 7.03908027196303 sec downtime
```

**Comment by mperham** [comment]
I don't think there is a good reason for Sidekiq to handle this error. I wonder if this should be handled internally to the redis client. Do you want to open an issue here and ask?

https://github.com/redis/redis-rb/issues/new

**Comment by harmjanblok** [comment]
Thanks @mperham for your quick reply. I'll open an issue at redis-rb to see if/how this can be handled in the redis client.
