### ISSUE TITLE
Redis ECONNRESET

### ISSUE THREAD

**Issue by pankajmt** [mperham/sidekiq#4942]
Ruby version: 2.7.3
Rails version: 6.1.3.2
Sidekiq / Pro / Enterprise version(s): Pro 5.2.2

We see the following from time to time in our application logs. Could this be idle connection timeouts related? Going by the docs, I do not see a setting for idle connection timeout!

Initializer

```
redis_conn = proc {
  RedisBuilder.build_sidekiq
}

Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(size: 5, &redis_conn)
end

Sidekiq.configure_server do |config|
  config.redis = ConnectionPool.new(size: 25, &redis_conn)
end
```

Error
```
"2021-07-14T22:47:45.854Z pid=1 tid=1j6l9 WARN: Redis::ConnectionError: Connection lost (ECONNRESET)",
```

Stacktrace

```
"2021-07-14T22:47:45.854Z pid=1 tid=1j6l9 WARN: /opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:275:in `rescue in io'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:267:in `io'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:279:in `read'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:147:in `block (3 levels) in call_loop'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:146:in `loop'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:146:in `block (2 levels) in call_loop'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:248:in `block (2 levels) in process'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:389:in `ensure_connected'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:238:in `block in process'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:325:in `logging'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:237:in `process'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:145:in `block in call_loop'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:300:in `with_socket_timeout'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:144:in `call_loop'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/subscribe.rb:44:in `subscription'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/subscribe.rb:22:in `psubscribe'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:3507:in `_subscription'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:2350:in `block in psubscribe'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:69:in `block in synchronize'
/usr/local/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
/usr/local/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:69:in `synchronize'
/opt/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:2349:in `psubscribe'
/opt/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-pro-5.2.2/lib/sidekiq/pro/config.rb:63:in `block in listen'
/opt/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq.rb:98:in `block in redis'
/opt/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
/opt/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
/opt/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
/opt/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
/opt/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
/opt/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq.rb:95:in `redis'
/opt/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-pro-5.2.2/lib/sidekiq/pro/config.rb:62:in `listen'
/opt/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:43:in `watchdog'
/opt/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:52:in `block in safe_thread'
/opt/app/vendor/bundle/ruby/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
{"timestamp":"2021-07-14T22:47:45.864053+00:00","log_level":"INFO","progname":"sentry","message":"Sending envelope [event] 2e9c3cd0c25f4fd6bb1da9437270a373 to Sentry"}",
```

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
That error is from the persistent connection which monitors queue pausing. It looks like you might have a firewall config which terminates quiet TCP connections. Use Redis-rb's keepalive feature to keep your connection "loud".

https://github.com/redis/redis-rb/blob/master/lib/redis/client.rb#L25

```ruby
config.redis = { tcp_keepalive: 60 }
```

**Comment by pankajmt** [comment]
this suggestion has not helped. and our infra has confirmed there is no such timeout on outbound. any other thoughts? not sure if I am able to re-open this issue, but hoping this comment gets to you!

**Comment by mperham** [comment]
No one else is having the problem. I’m not sure how else to help?

**Comment by pankajmt** [comment]
Thanks. We see it happens once every 4 hours per sidekiq pod. Nothing rings a bell yet. We will keep a tap if it happens more freq!
