### ISSUE TITLE
Redis::ConnectionError with { reconnect_attempts: 0 } caused (?) the leader to miss cron jobs

### ISSUE THREAD

**Issue by isaacbowen** [mperham/sidekiq#4950]
Our leader missed a couple of cron jobs in a row (solved by restarting that Heroku process to reassign the leader). Rollbar caught a "Redis::ConnectionError: Connection lost (ECONNRESET)" error for the leader, and my guess is that this ended up being a permanent error condition due to our use of { reconnect_attempts: 0 } for Redis. For context, we're using that option to avoid duplicate jobs being enqueued (#3303).

---

Ruby version: 2.7.3

Rails version: 6.1.4

Sidekiq / Pro / Enterprise version(s):
* sidekiq (6.2.1)
* sidekiq-pro (5.2.2)
* sidekiq-ent (2.2.2)

**Comment by isaacbowen** [comment]
Backtrace! :D

```
Errno::ECONNRESET: Connection reset by peer
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/connection/ruby.rb", line 63, in block in _read_from_socket
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/connection/ruby.rb", line 52, in loop
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/connection/ruby.rb", line 52, in _read_from_socket
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/connection/ruby.rb", line 45, in gets
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/connection/ruby.rb", line 378, in read
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 280, in block in read
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 268, in io
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 279, in read
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 208, in block (2 levels) in call_pipelined
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 204, in each
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 204, in each_with_index
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 204, in block in call_pipelined
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 248, in block (2 levels) in process
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 389, in ensure_connected
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 238, in block in process
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 325, in logging
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 237, in process
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 203, in call_pipelined
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 170, in block in call_pipeline
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 313, in with_reconnect
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 168, in call_pipeline
  File "/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/redis.rb", line 102, in block in call_pipeline
  File "/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/tracer.rb", line 371, in capture_segment_error
  File "/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/redis.rb", line 101, in call_pipeline
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb", line 2445, in block in pipelined
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb", line 69, in block in synchronize
  File "/app/vendor/ruby-2.7.3/lib/ruby/2.7.0/monitor.rb", line 202, in synchronize
  File "/app/vendor/ruby-2.7.3/lib/ruby/2.7.0/monitor.rb", line 202, in mon_synchronize
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb", line 69, in synchronize
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb", line 2441, in pipelined
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/config.rb", line 67, in block in persist
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq.rb", line 98, in block in redis
  File "/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb", line 63, in block (2 levels) in with
  File "/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb", line 62, in handle_interrupt
  File "/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb", line 62, in block in with
  File "/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb", line 59, in handle_interrupt
  File "/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb", line 59, in with
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq.rb", line 95, in redis
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/config.rb", line 66, in persist
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/manager.rb", line 65, in persist
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic.rb", line 81, in block (2 levels) in <top (required)>
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb", line 87, in block in fire_event
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb", line 86, in each
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb", line 86, in fire_event
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/senate.rb", line 93, in stage_coup!
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/senate.rb", line 135, in election
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/senate.rb", line 108, in cycle
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb", line 43, in watchdog
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb", line 52, in block in safe_thread
Redis::ConnectionError: Connection lost (ECONNRESET)
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 275, in rescue in io
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 267, in io
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 279, in read
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 208, in block (2 levels) in call_pipelined
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 204, in each
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 204, in each_with_index
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 204, in block in call_pipelined
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 248, in block (2 levels) in process
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 389, in ensure_connected
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 238, in block in process
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 325, in logging
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 237, in process
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 203, in call_pipelined
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 170, in block in call_pipeline
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 313, in with_reconnect
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb", line 168, in call_pipeline
  File "/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/redis.rb", line 102, in block in call_pipeline
  File "/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/tracer.rb", line 371, in capture_segment_error
  File "/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/redis.rb", line 101, in call_pipeline
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb", line 2445, in block in pipelined
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb", line 69, in block in synchronize
  File "/app/vendor/ruby-2.7.3/lib/ruby/2.7.0/monitor.rb", line 202, in synchronize
  File "/app/vendor/ruby-2.7.3/lib/ruby/2.7.0/monitor.rb", line 202, in mon_synchronize
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb", line 69, in synchronize
  File "/app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb", line 2441, in pipelined
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/config.rb", line 67, in block in persist
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq.rb", line 98, in block in redis
  File "/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb", line 63, in block (2 levels) in with
  File "/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb", line 62, in handle_interrupt
  File "/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb", line 62, in block in with
  File "/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb", line 59, in handle_interrupt
  File "/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb", line 59, in with
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq.rb", line 95, in redis
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/config.rb", line 66, in persist
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic/manager.rb", line 65, in persist
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/periodic.rb", line 81, in block (2 levels) in <top (required)>
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb", line 87, in block in fire_event
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb", line 86, in each
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb", line 86, in fire_event
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/senate.rb", line 93, in stage_coup!
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/senate.rb", line 135, in election
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/senate.rb", line 108, in cycle
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb", line 43, in watchdog
  File "/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb", line 52, in block in safe_thread
```

**Comment by isaacbowen** [comment]
@mperham We just got bit by this again. Can you release the fix?

**Comment by mperham** [comment]
Yes. I have one more Pro fix I need to get in. Hopefully today or tomorrow.

**Comment by isaacbowen** [comment]
I'm not sure how to reproduce this at will, _but_, looking back at the logs, here's some surrounding context from the error we're discussing, pointing to Redis performance:

```
pid=3 tid=2713 INFO: Managing 17 periodic jobs
pid=3 tid=2713 WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"leader"}
pid=3 tid=2713 WARN: Redis::ConnectionError: Connection lost (ECONNRESET)
pid=3 tid=2713 WARN: /app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:292:in `rescue in io'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:284:in `io'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:296:in `read'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:225:in `block (2 levels) in call_pipelined'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:221:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:221:in `each_with_index'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:221:in `block in call_pipelined'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:265:in `block (2 levels) in process'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:406:in `ensure_connected'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:255:in `block in process'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:342:in `logging'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:254:in `process'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:220:in `call_pipelined'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:187:in `block in call_pipeline'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:330:in `with_reconnect'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis/client.rb:185:in `call_pipeline'
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/instrumentation/redis/prepend.rb:16:in `block in call_pipeline'
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:26:in `block in call_pipeline_with_tracing'
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:45:in `block in with_tracing'
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/tracer.rb:371:in `capture_segment_error'
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:45:in `with_tracing'
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:26:in `call_pipeline_with_tracing'
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-7.2.0/lib/new_relic/agent/instrumentation/redis/prepend.rb:16:in `call_pipeline'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis.rb:2495:in `block in pipelined'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis.rb:70:in `block in synchronize'
/app/vendor/ruby-2.7.4/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
/app/vendor/ruby-2.7.4/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis.rb:70:in `synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.4.0/lib/redis.rb:2491:in `pipelined'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.3/lib/sidekiq-ent/periodic/config.rb:67:in `block in persist'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq.rb:98:in `block in redis'
/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq.rb:95:in `redis'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.3/lib/sidekiq-ent/periodic/config.rb:66:in `persist'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.3/lib/sidekiq-ent/periodic/manager.rb:65:in `persist'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.3/lib/sidekiq-ent/periodic.rb:89:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/util.rb:87:in `block in fire_event'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/util.rb:86:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/util.rb:86:in `fire_event'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.3/lib/sidekiq-ent/senate.rb:93:in `stage_coup!'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.3/lib/sidekiq-ent/senate.rb:140:in `election'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.3/lib/sidekiq-ent/senate.rb:108:in `cycle'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/util.rb:43:in `watchdog'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.2/lib/sidekiq/util.rb:52:in `block in safe_thread'
pid=3 tid=1ri7 WARN: Your Redis network connection is performing extremely poorly.
Last RTT readings were [97190, 99928, 99907, 99892, 99908], ideally these should be < 1000.
Ensure Redis is running in the same AZ or datacenter as Sidekiq.
```

I just had the same ECONNRESET show up in a staging environment (resulting in the leader ceasing to schedule cron jobs); the stack trace was identical to [the one from earlier](https://github.com/mperham/sidekiq/issues/4950#issuecomment-951050013). We don't keep logs in that environment, so I don't have those to look at.

Is this useful to you?

**Comment by mperham** [comment]
The RTT warning typically appears if your Sidekiq processes are extremely CPU saturated. What is your concurrency? Do not set it higher than 10.

**Comment by isaacbowen** [comment]
`-c 1`. :D But, this worker process _is_ reserved for high-memory, high-cpu jobs, so I wouldn't be surprised to find out this was related.

**Comment by mperham** [comment]
Yeah, you should throw some `Thread.pass` calls into your inner loop to give the VM time for housekeeping chores. Otherwise MRI will give it the full 100ms timeslice and trigger that warning. https://github.com/redis/hiredis-rb/issues/74
