### ISSUE TITLE
object allocation during garbage collection phase

### ISSUE THREAD

**Issue by humblewolf** [mperham/sidekiq#4993]
Ruby version: 2.7.2
Rails version: 6.1.3.2
Sidekiq / Pro / Enterprise version(s): 6.2.1 open-source

error >>
```
/gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:404: [BUG] object allocation during garbage collection phase
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-musl]

```
 sidekiq.yml >>

```
:verbose: false
:concurrency: 5
:timeout: 25
:max_retries: 2

:queues:
  - [low, 1]
  - [scheduled_jobs, 1]
  - [webhooks, 1]
  - [active_storage_analysis, 1]
  - [action_mailbox_incineration, 1]
  - [integrations, 2]
  - [default, 2]
  - [mailers, 2]
  - [bots, 3]
  - [medium, 3]
  - [events, 3]
  - [action_mailbox_routing, 3]
  - [high, 5]
  - [critical, 10]
  
# you can override concurrency based on environment
production:
  :concurrency: 10
staging:
  :concurrency: 5
```
backtrace >>

```
-- Control frame information -----------------------------------------------
c:0033 p:0110 s:0159 e:000158 RESCUE /gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:404
c:0032 p:0074 s:0155 e:000154 METHOD /gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:375
c:0031 p:0005 s:0149 e:000148 BLOCK  /gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:238
c:0030 p:0012 s:0146 e:000145 METHOD /gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:325
c:0029 p:0006 s:0140 e:000139 METHOD /gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:237
c:0028 p:0008 s:0135 e:000134 METHOD /gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:131
c:0027 p:0010 s:0129 e:000128 BLOCK  /gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:226
c:0026 p:0038 s:0126 e:000125 METHOD /gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:300
c:0025 p:0006 s:0120 e:000119 METHOD /gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:225
c:0024 p:0040 s:0113 e:000112 BLOCK  /gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:1224
c:0023 p:0006 s:0108 e:000107 BLOCK  /gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:69 [FINISH]
c:0022 p:---- s:0105 e:000104 CFUNC  :synchronize
c:0021 p:0009 s:0101 e:000100 METHOD /usr/local/lib/ruby/2.7.0/monitor.rb:202
c:0020 p:0004 s:0096 e:000095 METHOD /gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:69
c:0019 p:0082 s:0092 e:000091 METHOD /gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:1221
c:0018 p:0007 s:0082 e:000081 METHOD /gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:1266
c:0017 p:0009 s:0077 e:000076 BLOCK  /gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/fetch.rb:47
c:0016 p:0009 s:0073 e:000072 BLOCK  /gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq.rb:98
c:0015 p:0005 s:0067 e:000066 BLOCK  /gems/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63 [FINISH]
c:0014 p:---- s:0064 e:000063 CFUNC  :handle_interrupt
c:0013 p:0033 s:0059 e:000058 BLOCK  /gems/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62 [FINISH]
c:0012 p:---- s:0055 e:000054 CFUNC  :handle_interrupt
c:0011 p:0029 s:0050 e:000049 METHOD /gems/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59
c:0010 p:0026 s:0045 e:000044 METHOD /gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq.rb:95
c:0009 p:0034 s:0041 e:000040 METHOD /gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/fetch.rb:47
c:0008 p:0005 s:0035 e:000034 METHOD /gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:83
c:0007 p:0003 s:0029 e:000028 METHOD /gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:95
c:0006 p:0003 s:0024 e:000023 METHOD /gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:77
c:0005 p:0009 s:0020 e:000019 METHOD /gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:68 [FINISH]
c:0004 p:---- s:0015 e:000014 IFUNC 
c:0003 p:0002 s:0012 e:000011 METHOD /gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:43
c:0002 p:0026 s:0006 e:000005 BLOCK  /gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:52 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:52:in `block in safe_thread'
/gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:43:in `watchdog'
/gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:68:in `run'
/gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:77:in `process_one'
/gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:95:in `fetch'
/gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:83:in `get_one'
/gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/fetch.rb:47:in `retrieve_work'
/gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq.rb:95:in `redis'
/gems/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
/gems/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
/gems/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
/gems/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
/gems/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
/gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq.rb:98:in `block in redis'
/gems/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/fetch.rb:47:in `block in retrieve_work'
/gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:1266:in `brpop'
/gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:1221:in `_bpop'
/gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:69:in `synchronize'
/usr/local/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
/usr/local/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
/gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:69:in `block in synchronize'
/gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis.rb:1224:in `block in _bpop'
/gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:225:in `call_with_timeout'
/gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:300:in `with_socket_timeout'
/gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:226:in `block in call_with_timeout'
/gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:131:in `call'
/gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:237:in `process'
/gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:325:in `logging'
/gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:238:in `block in process'
/gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:375:in `ensure_connected'
/gems/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:404:in `rescue in ensure_connected'

```

**Comment by humblewolf** [comment]
we use sentry for log collection, can it be connected in any way like this https://discuss.newrelic.com/t/new-relic-agent-causes-garbage-collection-error/27623/3

**Comment by mperham** [comment]
Upgrade to ruby 2.7.4.

**Comment by humblewolf** [comment]
hey @mperham is this also connected ?

**Comment by mperham** [comment]
I don't know.

**Comment by mperham** [comment]
These are Ruby VM crashes. The Troubleshooting wiki page tells you what to do:

* Upgrade Ruby to the latest point release (i.e. 2.7.x)
* Upgrade all of your gems with native extensions to the latest versions to pick up any bugfixes

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#my-sidekiq-process-is-crashing-what-do-i-do
