### ISSUE TITLE
Upgrade from Sidekiq Pro 5.2.1 -> 5.2.4 getting super_fetch timeout

### ISSUE THREAD

**Issue by jkhulme** [mperham/sidekiq#5045]
Ruby version: 3.0.2
Rails version: 6.1.4.1
Sidekiq / Pro / Enterprise version(s): Pro: 5.2.4, Sidekiq: 6.2.2 (last tested working versions 5.2.1, 6.1.2).
Sidekiq unique jobs version(s): 7.1.8 (last tested working version 6.0.24)

Initializer:
```
# Ensure locale is passed to sidekiq workers
require 'sidekiq/middleware/i18n'
# Enable killswitch features
require 'sidekiq/killswitch/middleware/load_all'

Sidekiq::Extensions.enable_delay!
if ENV["RAILS_LOG_TO_STDOUT"].present?
  Sidekiq.logger = ActiveSupport::Logger.new(STDOUT)
  Sidekiq.logger.formatter = Sidekiq::Logger::Formatters::Pretty.new
end
Sidekiq.logger.level = Logger.const_get(Settings.sidekiq.log_level || Settings.log_level)

Sidekiq.configure_server do |config|
  config.on(:startup) do
    if Sidekiq.options[:concurrency] > ActiveRecord::Base.connection.pool.size ||
       (Settings.options.use_redshift && Sidekiq.options[:concurrency] > RedshiftDB.connection.pool.size)
      Sidekiq.logger.error "Sidekiq concurrency (worker) count (#{Sidekiq.options[:concurrency]}) exceeds connecton pool for primary (ActiveRecord::Base) or RedshiftDB database, add pool=#{Sidekiq.options[:concurrency]} option to DATABASE_URL and REDSHIFT_URL environment variable. Shutting down Sidekiq!"
      Process.kill('TERM', Process.pid)
    end
  end

  config.redis = { url: Settings.sidekiq_redis_url, size: Settings.redis.pool_size }

  config.super_fetch! if defined?(::Sidekiq::Pro)

  config.death_handlers << ->(job, ex) do
    digest = job['unique_digest']
    Sidekiq.logger.warn("Job: #{job['class']} JID: #{job["jid"]} Digest: #{digest} just died with error #{ex.message}.")
    SidekiqUniqueJobs::Digests.delete_by_digest(digest) if digest
  end

  #   config.client_middleware do |chain|
  #     chain.add SidekiqUniqueJobs::Middleware::Client
  #   end

  #   config.server_middleware do |chain|
  #     chain.add SidekiqUniqueJobs::Middleware::Server
  #   end

  #   SidekiqUniqueJobs::Server.configure(config)
  # end

  # Sidekiq.configure_client do |config|
  #   config.redis = { url: Settings.sidekiq_redis_url, size: Settings.redis.pool_size }

  #   config.client_middleware do |chain|
  #     chain.add SidekiqUniqueJobs::Middleware::Client
  #   end
end

Sidekiq::Client.reliable_push! if defined?(::Sidekiq::Pro)

# Patch Sidekiq logging so that it shows class and method for delayed methods
module Sidekiq
  module Middleware
    module Server
      class Logging
        def call(_worker, item, _queue)
          extra_info = if item['class'] == "Sidekiq::Extensions::DelayedClass"
                         (target, method_name) = YAML.load(item['args'].first)
                         " #{target}##{method_name}"
                       end
          begin
            start = Time.now
            logger.info("start#{extra_info}".freeze)
            yield
            logger.info("done#{extra_info}: #{elapsed(start)} sec")
          rescue StandardError => e
            logger.info("fail#{extra_info}: (message: #{e.message}) #{elapsed(start)} sec")
            raise
          end
        end
      end
    end
  end
end
```
(sidekiq unique jobs config is commented out because it is config for version 7)

sidekiq.yml:
```
:concurrency: 6
:queues:
  - critical
  - mailer
  - default
  - low
:dead_max_jobs: 10_000_000
```

Error message:
```
2021-11-01T15:05:29.841685+00:00 app[sidekiq.11]: 2021-11-01T15:05:29.841Z pid=4 tid=24m8 WARN: {"context":"SuperFetch#startup"}
2021-11-01T15:05:29.841870+00:00 app[sidekiq.11]: 2021-11-01T15:05:29.841Z pid=4 tid=24m8 WARN: RuntimeError: Did not find our own heartbeat within 10 seconds, that's bad
2021-11-01T15:05:29.841898+00:00 app[sidekiq.11]: 2021-11-01T15:05:29.841Z pid=4 tid=24m8 WARN: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-pro-5.2.4/lib/sidekiq/pro/super_fetch.rb:262:in `wait_for_heartbeat'
2021-11-01T15:05:29.841899+00:00 app[sidekiq.11]: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-pro-5.2.4/lib/sidekiq/pro/super_fetch.rb:77:in `block in startup'
2021-11-01T15:05:29.841899+00:00 app[sidekiq.11]: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.2.2/lib/sidekiq/util.rb:43:in `watchdog'
2021-11-01T15:05:29.841900+00:00 app[sidekiq.11]: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-pro-5.2.4/lib/sidekiq/pro/super_fetch.rb:72:in `startup'
2021-11-01T15:05:29.841900+00:00 app[sidekiq.11]: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-pro-5.2.4/lib/sidekiq/pro/super_fetch.rb:61:in `block (2 levels) in setup'
2021-11-01T15:05:29.843220+00:00 app[sidekiq.11]: I, [2021-11-01T15:05:29.843149 #4]  INFO -- [Bugsnag]: Notifying https://notify.bugsnag.com of RuntimeError
2021-11-01T15:05:29.848469+00:00 app[sidekiq.11]: I, [2021-11-01T15:05:29.848411 #4]  INFO -- sentry: Sending envelope [event] ded4b81ad6ff4854938e81b92a16995a to Sentry
2021-11-01T15:05:30.180750+00:00 app[sidekiq.11]: #<Thread:0x00005579bc46efc0 /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-pro-5.2.4/lib/sidekiq/pro/super_fetch.rb:61 run> terminated with exception (report_on_exception is true):
2021-11-01T15:05:30.180762+00:00 app[sidekiq.11]: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-pro-5.2.4/lib/sidekiq/pro/super_fetch.rb:262:in `wait_for_heartbeat': Did not find our own heartbeat within 10 seconds, that's bad (RuntimeError)
2021-11-01T15:05:30.180764+00:00 app[sidekiq.11]: from /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-pro-5.2.4/lib/sidekiq/pro/super_fetch.rb:77:in `block in startup'
2021-11-01T15:05:30.180764+00:00 app[sidekiq.11]: from /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.2.2/lib/sidekiq/util.rb:43:in `watchdog'
2021-11-01T15:05:30.180765+00:00 app[sidekiq.11]: from /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-pro-5.2.4/lib/sidekiq/pro/super_fetch.rb:72:in `startup'
2021-11-01T15:05:30.180765+00:00 app[sidekiq.11]: from /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-pro-5.2.4/lib/sidekiq/pro/super_fetch.rb:61:in `block (2 levels) in setup'
2021-11-01T15:05:30.435283+00:00 app[sidekiq.8]: 2021-11-01T15:05:30.435Z pid=4 tid=24m8 WARN: {"context":"SuperFetch#startup"}
2021-11-01T15:05:30.435297+00:00 app[sidekiq.8]: 2021-11-01T15:05:30.435Z pid=4 tid=24m8 WARN: RuntimeError: Did not find our own heartbeat within 10 seconds, that's bad
2021-11-01T15:05:30.435326+00:00 app[sidekiq.8]: 2021-11-01T15:05:30.435Z pid=4 tid=24m8 WARN: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-pro-5.2.4/lib/sidekiq/pro/super_fetch.rb:262:in `wait_for_heartbeat'
2021-11-01T15:05:30.435327+00:00 app[sidekiq.8]: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-pro-5.2.4/lib/sidekiq/pro/super_fetch.rb:77:in `block in startup'
2021-11-01T15:05:30.435327+00:00 app[sidekiq.8]: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.2.2/lib/sidekiq/util.rb:43:in `watchdog'
2021-11-01T15:05:30.435328+00:00 app[sidekiq.8]: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-pro-5.2.4/lib/sidekiq/pro/super_fetch.rb:72:in `startup'
2021-11-01T15:05:30.435328+00:00 app[sidekiq.8]: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-pro-5.2.4/lib/sidekiq/pro/super_fetch.rb:61:in `block (2 levels) in setup'
2021-11-01T15:05:30.436579+00:00 app[sidekiq.8]: I, [2021-11-01T15:05:30.436502 #4]  INFO -- [Bugsnag]: Notifying https://notify.bugsnag.com of RuntimeError
2021-11-01T15:05:30.441821+00:00 app[sidekiq.8]: I, [2021-11-01T15:05:30.441772 #4]  INFO -- sentry: Sending envelope [event] 7db15b5b08b94db2945cd1f5d6379778 to Sentry
2021-11-01T15:05:30.758610+00:00 heroku[sidekiq.5]: Error R12 (Exit timeout) -> At least one process failed to exit within 30 seconds of SIGTERM
2021-11-01T15:05:30.805335+00:00 heroku[sidekiq.5]: Stopping remaining processes with SIGKILL
```

Slow log:
```
127
11/1/2021 3:08 PM
14
O(log(N)) for each item added, where N is the number of elements in the sorted set.
ZADD uniquejobs:digests 1583260809.5926049 uniquejobs:e8cdb5662b79f8ce26bfbddfca2ba7e3

126
11/1/2021 3:03 PM
19
O(N) where N is the number of fields being set.
HMSET uniquejobs:b31e53145a69bce58c22747d2735a788:locked 97bfd84af11f8f3b2349b689 1582732452.4833019

125
11/1/2021 3:01 PM
10
O(log(N)) for each item added, where N is the number of elements in the sorted set.
ZADD uniquejobs:digests 1583324928.0908291 
```

We recently tried to update to more recent sidekiq / pro versions.  This also meant we needed to update sidekiq unique jobs.
Our sidekiq process does not start up, it fails on `SuperFetch#startup` with `RuntimeError: Did not find our own heartbeat within 10 seconds, that's bad`
From my understanding this likely due to a very large number of keys in Redis.  And from the slowlog I think that could be related to sidekiq-unique jobs.

I'm unable to test newer sidekiq pro without updating sidekiq uniq jobs, and I can't update sidekiq unique jobs with updating sidekiq.  Which is annoying.

Have there been any changes to the implementation of super_fetch that could have made performance worse?

**Comment by mperham** [comment]
It would be helpful to see your Redis info.

The major change to super_fetch since v5.2.1 was polishing of automatic detection of poison pills feature. This should not have added any significant performance overhead and I've received no complaints about it.

**Comment by maxrosecollins** [comment]
I'm experiencing this issue too.

**Comment by mperham** [comment]
@maxrosecollins > It would be helpful to see your Redis info.

**Comment by mperham** [comment]
This error is a sign that something is very wrong with your app/environment. You will need to give me a LOT more context and info if you want to debug it.

**Comment by jkhulme** [comment]
```
# Server
redis_version:6.0.9
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:0000000000000000000000000000000000000000
redis_mode:standalone
os:Linux 5.4.0-1051-aws x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:7.5.0
process_id:7959110
run_id:fa500ab5264cc055bf84b16bdfe1b1eab4abe600
tcp_port:14536
uptime_in_seconds:166318291
uptime_in_days:1924
hz:10
lru_clock:0
config_file:

# Clients
connected_clients:51
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:2

# Memory
used_memory:16522851984
used_memory_human:15.38G
used_memory_rss:16522851984
used_memory_peak:17697121312
used_memory_peak_human:16.48G
used_memory_lua:192512
mem_fragmentation_ratio:1
mem_allocator:jemalloc-5.1.0

# Persistence
loading:0
rdb_changes_since_last_save:2850507790
rdb_bgsave_in_progress:0
rdb_last_save_time:1625389911
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:1718119
total_commands_processed:6787349766
instantaneous_ops_per_sec:67
total_net_input_bytes:2396409751894
total_net_output_bytes:9062166338756
instantaneous_input_kbps:6.71
instantaneous_output_kbps:21.34
rejected_connections:0
sync_full:2
sync_partial_ok:0
sync_partial_err:0
expired_keys:212791201
evicted_keys:0
keyspace_hits:2896795720
keyspace_misses:3514806750
pubsub_channels:10
pubsub_patterns:1
latest_fork_usec:0
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:1
slave0:ip=0.0.0.0,port=0,state=online,offset=0,lag=0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.00
used_cpu_user:0.00
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=28711765,expires=2409054,avg_ttl=46422792
```

We're using redislabs, and currently we do use the same instance for the Rails cache and sidekiq.  I see from other answers on this topic that that is not something you recommend.  So we will be switching to separate instances.  
It was just odd to me that it had been working fine, and then only stopped working when we updated.

**Comment by mperham** [comment]
> keys=28711765

I'd bet that's it. You have a redis keyspace with 28m keys due to its usage as a cache. super_fetch can't scan that keyspace within 10s upon startup.

There was a super_fetch bugfix which might have exposed the timing issue. Timing and side effects can be hard to predict.

**Comment by maxrosecollins** [comment]
@mperham 

This is my INFO as of now. I am running a sidekiq instance and another for my cache.

```
# Server
redis_version:6.2.5
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:db553b25fce9f39f
redis_mode:standalone
os:Linux 4.15.0-161-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:7.5.0
process_id:959
process_supervised:no
run_id:cc8e184e7721433d473261efdab0c4d8d9853b22
tcp_port:6379
server_time_usec:1636043974096133
uptime_in_seconds:550653
uptime_in_days:6
hz:10
configured_hz:10
lru_clock:8654022
executable:/opt/redis/src/redis-server
config_file:/opt/redis/redis.conf
io_threads_active:0

# Clients
connected_clients:1597
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:186
client_recent_max_output_buffer:20504
blocked_clients:89
tracking_clients:0
clients_in_timeout_table:89

# Memory
used_memory:282331336
used_memory_human:269.25M
used_memory_rss:774381568
used_memory_rss_human:738.51M
used_memory_peak:5259086496
used_memory_peak_human:4.90G
used_memory_peak_perc:5.37%
used_memory_overhead:42287664
used_memory_startup:809944
used_memory_dataset:240043672
used_memory_dataset_perc:85.27%
allocator_allocated:282536168
allocator_active:681938944
allocator_resident:789065728
total_system_memory:8368631808
total_system_memory_human:7.79G
used_memory_lua:248832
used_memory_lua_human:243.00K
used_memory_scripts:31064
used_memory_scripts_human:30.34K
number_of_cached_scripts:11
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:2.41
allocator_frag_bytes:399402776
allocator_rss_ratio:1.16
allocator_rss_bytes:107126784
rss_overhead_ratio:0.98
rss_overhead_bytes:-14684160
mem_fragmentation_ratio:2.74
mem_fragmentation_bytes:492125896
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:32782040
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:7

# Persistence
loading:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:16880
rdb_bgsave_in_progress:0
rdb_last_save_time:1636043960
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:17637376
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:26683
total_commands_processed:10559578701
instantaneous_ops_per_sec:18106
total_net_input_bytes:949509054957
total_net_output_bytes:16738797251214
instantaneous_input_kbps:1614.46
instantaneous_output_kbps:58162.94
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:66494905
expired_stale_perc:0.02
expired_time_cap_reached_count:14
expire_cycle_cpu_milliseconds:468797
evicted_keys:0
keyspace_hits:6045576018
keyspace_misses:824886803
pubsub_channels:0
pubsub_patterns:1
latest_fork_usec:30209
total_forks:6805
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:4
dump_payload_sanitizations:0
total_reads_processed:6614136207
total_writes_processed:6614202669
io_threaded_reads_processed:0
io_threaded_writes_processed:0

# Replication
role:master
connected_slaves:0
master_failover_state:no-failover
master_replid:6b435477655d85fed9f958fefc371dd7ab04bb64
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:95911.819971
used_cpu_user:364387.463663
used_cpu_sys_children:11543.031474
used_cpu_user_children:113935.171382
used_cpu_sys_main_thread:95789.763517
used_cpu_user_main_thread:364356.589599

# Modules

# Errorstats
errorstat_LOADING:count=4

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=145597,expires=20060,avg_ttl=6862786772
```

**Comment by mperham** [comment]
@maxrosecollins I suspect your issue is here:

> connected_clients:1597
> instantaneous_output_kbps:58162.94

You've got an very busy Redis. It might be overloaded and need to be scaled up or sharded. Double check your CPU usage % and other ops metrics.
