### ISSUE TITLE
Psych::DisallowedClass: Tried to load unspecified class on Ruby 3.1.0-preview1 due to upstream Psych/Yaml change

### ISSUE THREAD

**Issue by ivoanjo** [mperham/sidekiq#5064]
Ruby version: 3.1.0-preview1
Rails version: N/A
Sidekiq / Pro / Enterprise version(s): 6.3.1

Hey! I work for @Datadog on our [`ddtrace`](https://github.com/DataDog/dd-trace-rb) gem, which includes support for tracing Sidekiq.

I was doing a few experiments with Ruby 3.1.0-preview1, and found that some of our sidekiq integration tests were failing with an exception.

I believe the issue is caused by https://github.com/ruby/psych/pull/487 . I include a testcase below, that works on Ruby 2.7 and 3.0, but fails on 3.1.0-preview1:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'sidekiq'
end

puts RUBY_DESCRIPTION

require 'sidekiq/testing'

class MyClass
  def self.do_something
  end
end

Sidekiq::Testing.inline!
Sidekiq::Extensions.enable_delay!

MyClass.delay.do_something

puts "Success!"
```

And the output:

```
ruby 3.1.0preview1 (2021-11-09 master 5a3b2e6141) [x86_64-darwin19]
ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: MyClass (Psych::DisallowedClass)
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/class_loader.rb:28:in `load'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:424:in `resolve_class'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:93:in `deserialize'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:128:in `visit_Psych_Nodes_Scalar'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `block in register_empty'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `each'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `register_empty'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:146:in `visit_Psych_Nodes_Sequence'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
  from ruby-3.1.0-preview1/lib/ruby/3.1.0/psych.rb:370:in `load'
  from ruby-3.1.0-preview1/gems/sidekiq-6.3.1/lib/sidekiq/extensions/class_methods.rb:19:in `perform'
  from ruby-3.1.0-preview1/gems/sidekiq-6.3.1/lib/sidekiq/testing.rb:300:in `execute_job'
  from ruby-3.1.0-preview1/gems/sidekiq-6.3.1/lib/sidekiq/testing.rb:295:in `block in process_job'
  from ruby-3.1.0-preview1/gems/sidekiq-6.3.1/lib/sidekiq/middleware/chain.rb:133:in `invoke'
  from ruby-3.1.0-preview1/gems/sidekiq-6.3.1/lib/sidekiq/testing.rb:294:in `process_job'
  from ruby-3.1.0-preview1/gems/sidekiq-6.3.1/lib/sidekiq/testing.rb:89:in `block in raw_push'
  from ruby-3.1.0-preview1/gems/sidekiq-6.3.1/lib/sidekiq/testing.rb:85:in `each'
  from ruby-3.1.0-preview1/gems/sidekiq-6.3.1/lib/sidekiq/testing.rb:85:in `raw_push'
  from ruby-3.1.0-preview1/gems/sidekiq-6.3.1/lib/sidekiq/client.rb:74:in `push'
  from ruby-3.1.0-preview1/gems/sidekiq-6.3.1/lib/sidekiq/worker.rb:307:in `client_push'
  from ruby-3.1.0-preview1/gems/sidekiq-6.3.1/lib/sidekiq/extensions/generic_proxy.rb:27:in `method_missing'
  from testcase.rb:20:in `<main>'
```

I believe the fix is to use `Psych.unsafe_load` in most places where `YAML.load` is being used.

As always, thanks for Sidekiq -- it's an awesome piece of kit :)

**Comment by mperham** [comment]
The Delayed extensions have been deprecated since Sidekiq 5.0. It might be time to remove them entirely. The community can always package them in a 3rd party gem and document this gotcha.

**Comment by sergiobayona** [comment]
if anyone is still running into this issue, I put together as tiny patch to fix this issue. It's meant as a temporary fix while a more permanent solution is introduced. 

https://gist.github.com/sergiobayona/b0b62385fc4c1bf0073709b71149edca
