### ISSUE TITLE
Sidekiq::Pro::Web documentation issue

### ISSUE THREAD

**Issue by Bartlebyy** [mperham/sidekiq#5074]
Ruby version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
Rails version: Rails 6.0.4.1
Sidekiq: 6.2.2
Sidekiq Pro: 5.2.4
Sidekiq Enterprise version(s): 2.2.3

There seems to be an error with your Pro Web UI sharding documentation.

I added the following to my routes file 
```
require 'sidekiq/pro/version'
require 'sidekiq/pro/web'
require 'sidekiq-ent/web'

mount Sidekiq::Pro::Web => '/sidekiq' # default
```

And when I tried to run `rails s` I got the following error:
```
Traceback (most recent call last):
        60: from bin/rails:7:in `<main>'
        59: from bin/rails:7:in `require'
        58: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/commands.rb:18:in `<top (required)>'
        57: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/command.rb:46:in `invoke'
        56: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/command/base.rb:69:in `perform'
        55: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        54: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        53: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        52: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/server/server_command.rb:138:in `perform'
        51: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/server/server_command.rb:138:in `tap'
        50: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        49: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/server/server_command.rb:37:in `start'
        48: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
        47: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
        46: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
        45: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        44: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
        43: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
        42: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
        41: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
        40: from config.ru:3:in `block in <main>'
        39: from config.ru:3:in `require_relative'
        38: from /Users/d.medina/Projects/calendly/config/environment.rb:5:in `<top (required)>'
        37: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/application.rb:363:in `initialize!'
        36: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:60:in `run_initializers'
        35: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
        34: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
        33: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
        32: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
        31: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
        30: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
        29: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
        28: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        27: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
        26: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
        25: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:32:in `run'
        24: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:32:in `instance_exec'
        23: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/application/finisher.rb:184:in `block in <module:Finisher>'
        22: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/application/routes_reloader.rb:10:in `execute'
        21: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/file_update_checker.rb:83:in `execute'
        20: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/application/routes_reloader.rb:29:in `block in updater'
        19: from /Users/d.medina/Projects/calendly/gems/modular_routes/lib/extensions/routes_reloader.rb:6:in `reload!'
        18: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/application/routes_reloader.rb:20:in `reload!'
        17: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
        16: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/application/routes_reloader.rb:40:in `each'
        15: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
        14: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/application/routes_reloader.rb:40:in `load'
        13: from /Users/d.medina/Projects/calendly/config/routes.rb:5:in `<top (required)>'
        12: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.0.4.1/lib/action_dispatch/routing/route_set.rb:408:in `draw'
        11: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.0.4.1/lib/action_dispatch/routing/route_set.rb:426:in `eval_block'
        10: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.0.4.1/lib/action_dispatch/routing/route_set.rb:426:in `instance_exec'
         9: from /Users/d.medina/Projects/calendly/config/routes.rb:164:in `block in <top (required)>'
         8: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/devise-4.7.1/lib/devise/rails/routes.rb:315:in `authenticated'
         7: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/devise-4.7.1/lib/devise/rails/routes.rb:483:in `constraints_for'
         6: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.0.4.1/lib/action_dispatch/routing/mapper.rb:1016:in `constraints'
         5: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.0.4.1/lib/action_dispatch/routing/mapper.rb:887:in `scope'
         4: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.0.4.1/lib/action_dispatch/routing/mapper.rb:1016:in `block in constraints'
         3: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/devise-4.7.1/lib/devise/rails/routes.rb:484:in `block in constraints_for'
         2: from /Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/devise-4.7.1/lib/devise/rails/routes.rb:316:in `block in authenticated'
         1: from /Users/d.medina/Projects/calendly/config/routes.rb:165:in `block (2 levels) in <top (required)>'
/Users/d.medina/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.0.4.1/lib/action_dispatch/routing/mapper.rb:621:in `mount': A rack application must be specified (ArgumentError)
```

Upon further debugging it seems that `Sidekiq::Pro::Web` does not respond to the `call` method, which causes it to error out.
![image](https://user-images.githubusercontent.com/6975256/144124760-684cdbe5-2261-457e-b197-d769d8e629cd.png)
![image](https://user-images.githubusercontent.com/6975256/144124641-c68de12f-f1ad-4b9d-bbfb-5c3cdd5b9481.png)

But this does: `mount Sidekiq::Pro::Web.with(redis_pool: $redis), at: '/apps/sidekiq', as: 'sidekiq'`

**Comment by mperham** [comment]
I suspect someone updated the page incorrectly. You never mount Sidekiq::Pro::Web directly. Fixed:

https://github.com/mperham/sidekiq/wiki/Pro-Web-UI#sharding
