### ISSUE TITLE
Namespace issue with Datadog::Statsd

### ISSUE THREAD

**Issue by smasry** [mperham/sidekiq#5094]
## Ruby version:
3.0.2

## Rails version:
6.0.4.1

## Sidekiq / Pro / Enterprise version(s):
  * sidekiq-ent (2.2.3)
  * sidekiq-pro (5.3.0)
  * sidekiq (6.3.1)
  * sidekiq-datadog (0.6.0) 

## Initializer
```
...
  Sidekiq::Pro.dogstatsd = -> { ::Datadog::Statsd.new('localhost', 8125, namespace: 'sidekiq') }
...
```

## Backtrace
```
.../gems/ruby-3.0.2@swoop/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant': uninitialized constant Sidekiq::Datadog::Statsd (NameError)
	from ...gems/ruby-3.0.2@swoop/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
	from ...gems/ruby-3.0.2@swoop/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
	from ...gems/ruby-3.0.2@swoop/gems/sidekiq-pro-5.3.0/lib/sidekiq/pro/metrics.rb:130:in `initialize'
	from ...gems/ruby-3.0.2@swoop/gems/sidekiq-pro-5.3.0/lib/sidekiq/pro/metrics.rb:20:in `new'
	from ...gems/ruby-3.0.2@swoop/gems/sidekiq-pro-5.3.0/lib/sidekiq/pro/metrics.rb:20:in `dogstatsd='
	from .../config/initializers/sidekiq.rb:159:in `<top (required)>'
```

It appears the namespace is being added onto the `Datadog::Statsd` reference only when using Ruby 3.

**Comment by mperham** [comment]
Do you get the same error if you remove sidekiq-datadog?

**Comment by smasry** [comment]
Yes we see this with the removal of `sidekiq-datadog` as well.  We're currently seeing this when switching from 2.7.4 -> 3.0.2

**Comment by mperham** [comment]
Ok, simple enough fix. Thanks for the pointer.
