### ISSUE TITLE
Ruby 3.1 and missing net-pop & net-imap

### ISSUE THREAD

**Issue by jozefvaclavik** [mperham/sidekiq#5105]
Ruby version: 3.1.0
Rails version: 7.0.0
Sidekiq / Pro / Enterprise version(s): sidekiq 6.3.1, sidekiq-pro 5.3.0, sidekiq-ent 2.3.0

Bunch of gems has been removed from ruby 3.1 core into separate gems. Looks like sidekiq depends on `mail` and require `net-pop`, `net-imap` and possibly `net-smtp`. I had to add `net-smtp` into my rails app, so I'm not sure if sidekiq depends on it too, but without adding `net-pop` and `net-imap`, my sidekiq wasnt booting up.

This happens only in Production environment. In Development environment sidekiq is booting just fine.

```
The following default gems are now bundled gems. You need to add the following libraries to Gemfile under the bundler environment.
   net-ftp 0.1.3
   net-imap 0.2.2
   net-pop 0.1.1
   net-smtp 0.3.1
   matrix 0.4.2
   prime 0.1.2
   debug 1.4.0
```
https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

Here is my log trace.

```
ERROR: Logfile redirection was removed in Sidekiq 6.0, Sidekiq will only log to STDOUT
2021-12-28T16:33:18.263Z pid=441 tid=47d INFO: Booting Sidekiq 6.3.1 with redis options {:url=>"redis://...:6379"}
{"ts":"2021-12-28T16:33:18.264Z","pid":441,"tid":"47d","lvl":"INFO","msg":"Booting Sidekiq 6.3.1 with redis options {:url=>\"redis://...6379\", :password=>nil}"}
bundler: failed to load command: sidekiq (/app/vendor/bundle/ruby/3.1.0/bin/sidekiq)
/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require': cannot load such file -- net/imap (LoadError)
        from /app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/network/retriever_methods/imap.rb:40:in `<class:IMAP>'
        from /app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/network/retriever_methods/imap.rb:39:in `<module:Mail>'
        from /app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/network/retriever_methods/imap.rb:4:in `<main>'
        from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        from /app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
        from /app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail.rb:54:in `block in eager_autoload!'
        from /app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail.rb:54:in `each'
        from /app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail.rb:54:in `eager_autoload!'
        from /app/vendor/bundle/ruby/3.1.0/bundler/gems/rails-80256751581c/actionmailer/lib/action_mailer.rb:60:in `eager_load!'
        from /app/vendor/bundle/ruby/3.1.0/bundler/gems/rails-80256751581c/railties/lib/rails/application/finisher.rb:80:in `each'
        from /app/vendor/bundle/ruby/3.1.0/bundler/gems/rails-80256751581c/railties/lib/rails/application/finisher.rb:80:in `block in <module:Finisher>'
        from /app/vendor/bundle/ruby/3.1.0/bundler/gems/rails-80256751581c/railties/lib/rails/initializable.rb:32:in `instance_exec'
        from /app/vendor/bundle/ruby/3.1.0/bundler/gems/rails-80256751581c/railties/lib/rails/initializable.rb:32:in `run'
        from /app/vendor/bundle/ruby/3.1.0/bundler/gems/rails-80256751581c/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /root/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
        from /root/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /root/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /root/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /root/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `each'
        from /root/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `call'
        from /root/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
        from /root/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
        from /root/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
        from /app/vendor/bundle/ruby/3.1.0/bundler/gems/rails-80256751581c/railties/lib/rails/initializable.rb:60:in `run_initializers'
        from /app/vendor/bundle/ruby/3.1.0/bundler/gems/rails-80256751581c/railties/lib/rails/application.rb:369:in `initialize!'
        from /app/config/environment.rb:5:in `<top (required)>'
        from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        from /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.3.1/lib/sidekiq/cli.rb:273:in `boot_application'
        from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.3.1/lib/sidekiq/cli.rb:37:in `run'
        from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.3.1/bin/sidekiq:31:in `<top (required)>'
        from /app/vendor/bundle/ruby/3.1.0/bin/sidekiq:25:in `load'
        from /app/vendor/bundle/ruby/3.1.0/bin/sidekiq:25:in `<top (required)>'
        from /app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.21/lib/bundler/cli/exec.rb:63:in `load'
        from /app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.21/lib/bundler/cli/exec.rb:63:in `kernel_load'
        from /app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.21/lib/bundler/cli/exec.rb:28:in `run'
        from /app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.21/lib/bundler/cli.rb:474:in `exec'
        from /app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.21/lib/bundler/cli.rb:30:in `dispatch'
        from /app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.21/lib/bundler/cli.rb:24:in `start'
        from /app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.21/exe/bundle:49:in `block in <top (required)>'
        from /app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.21/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
        from /app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.21/exe/bundle:37:in `<top (required)>'
        from /root/.asdf/installs/ruby/3.1.0/bin/bundle:25:in `load'
        from /root/.asdf/installs/ruby/3.1.0/bin/bundle:25:in `<main>'
```

**Comment by mperham** [comment]
Sidekiq does not depend on mail, Rails does.

**Comment by jozefvaclavik** [comment]
Any idea why puma was working fine but sidekiq was crashing without those gems?

**Comment by mperham** [comment]
I assume your Sidekiq.rb initializer eager loads the mail gem?

**Comment by jozefvaclavik** [comment]
I do lots of middleware stuff in my sidekiq initializer, so it is pretty complicated. If I would clean that up and remove periodic jobs, this is what remains:
```ruby
# frozen_string_literal: true

Sidekiq::Web.app_url = '/admin'
Sidekiq::Enterprise.unique! unless Rails.env.test?
Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  # config.super_fetch!
  config.reliable_scheduler!
  config.log_formatter = Sidekiq::Logger::Formatters::JSON.new

  config.redis = {
    url: (ENV['REDIS_URL'] || 'redis://localhost:6379'),
    password: ENV['REDIS_PASSWORD']
  }
end

Sidekiq.configure_client do |config|
  config.redis = {
    url: (ENV['REDIS_URL'] || 'redis://localhost:6379'),
    password: ENV['REDIS_PASSWORD']
  }
end
```

My app doesnt have emails configured in a first place. I understand if `rails` depends on `mail` that depends on those gems. I'm just bit mind-blown that puma was working fine without those two gems (not without `net-smtp`).

**Comment by mperham** [comment]
Your backtrack shows an initializer running Mail.eager_autoload. Grep your
code base for that method call or start spelunking through the Rails code
base.

**Comment by thoraxe** [comment]
Just hit this myself. You won't find `Mail.eager_autoload` anywhere in the codebase. However, you will find:

```
  # Eager load code on boot. This eager loads most of Rails and
  # your application in memory, allowing both threaded web servers
  # and those relying on copy on write to perform better.
  # Rake tasks automatically ignore this option for performance.
  config.eager_load = true
```

And, in his/my backtrace:

```
        from /app/vendor/bundle/ruby/3.1.0/bundler/gems/rails-80256751581c/actionmailer/lib/action_mailer.rb:60:in `eager_load!'
```

I happen to have ActionMailer configured for SMTP settings in `environment.rb`. So, I'm wondering if, in production mode, when things are eager loaded, that this is what causes it.

However, I'm in the same boat as @jozefvaclavik -- I don't understand why Puma happily runs without blowing up but Sidekiq does blow up.

My Sidekiq initializer is extremely simple:

```
# https://stackoverflow.com/questions/12265421/how-can-i-password-protect-my-sidekiq-route-i-e-require-authentication-for-th/13409418#13409418
require 'sidekiq'
require 'sidekiq/web'

Sidekiq.configure_server do |config|
  config.logger.level = Rails.logger.level
end

Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  # Protect against timing attacks:
  # - See https://codahale.com/a-lesson-in-timing-attacks/
  # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
  # - Use & (do not use &&) so that it doesn't short circuit.
  # - Use digests to stop length information leaking
  Rack::Utils.secure_compare(::Digest::SHA256.hexdigest(user), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_USER'])) &
    Rack::Utils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_PASSWORD']))
end
```

That's the entire file. So, is anything in the above obviously causing Mail to be eager loaded in production? 🤷

**Comment by mperham** [comment]
@thoraxe The only thing I can suppose is that your puma environment is not set to production or it somehow has `net-imap` already in the environment. Below is how Sidekiq boots a Rails app. There's no use of the `mail` or any `net-*` gems anywhere in Sidekiq.

https://github.com/mperham/sidekiq/blob/b2b23bfee413f0efac822d03b5fc1c75bd9066fb/lib/sidekiq/cli.rb#L269-L274
