### ISSUE TITLE
Psych 4 included in Ruby 3.1 complains when using aliases in config

### ISSUE THREAD

**Issue by nickjer** [mperham/sidekiq#5140]
Ruby version: 3.1.0
Rails version: 7.0.1
Sidekiq / Pro / Enterprise version(s): 6.4.0

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

```yaml
# sidekiq.yml
---
:verbose: false
:concurrency: 10
:timeout: 25
:queues:
  - critical
  - mailers
  - default
  - active_storage_analysis
  - active_storage_purge
  - low

production: &production
  :verbose: true
staging:
  <<: *production
```

```
2022-01-24T18:10:07.924Z pid=79634 tid=1mxq WARN: Psych::BadAlias: Unknown alias: production
2022-01-24T18:10:07.924Z pid=79634 tid=1mxq WARN: ruby/3.1.0/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias'
ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
ruby/3.1.0/psych.rb:335:in `safe_load'
ruby/3.1.0/psych.rb:370:in `load'
sidekiq-6.4.0/lib/sidekiq/cli.rb:385:in `parse_config'
sidekiq-6.4.0/lib/sidekiq/cli.rb:250:in `setup_options'
sidekiq-6.4.0/lib/sidekiq/cli.rb:24:in `parse'
sidekiq-6.4.0/bin/sidekiq:27:in `<top (required)>'
Development/carrier-engine/vendor/bundle/ruby/3.1.0/bin/sidekiq:25:in `load'
Development/carrier-engine/vendor/bundle/ruby/3.1.0/bin/sidekiq:25:in `<top (required)>'
bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `load'
bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `kernel_load'
bundler-2.2.32/lib/bundler/cli/exec.rb:23:in `run'
bundler-2.2.32/lib/bundler/cli.rb:478:in `exec'
bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
bundler-2.2.32/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
bundler-2.2.32/lib/bundler/cli.rb:31:in `dispatch'
bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
bundler-2.2.32/lib/bundler/cli.rb:25:in `start'
bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
bundler-2.2.32/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
bundler-2.2.32/exe/bundle:37:in `<top (required)>'
.rubies/ruby-3.1.0/bin/bundle:25:in `load'
.rubies/ruby-3.1.0/bin/bundle:25:in `<main>'
```

I think this happened because Psych 4 change `YAML.load` to alias `YAML.safe_load` instead of its previous behavior of `YAML.unsafe_load`.

Changing this line:

https://github.com/mperham/sidekiq/blob/c792342753e24e6471b6e7ab79de09814c1d5573/lib/sidekiq/cli.rb#L385

To use `YAML.unsafe_load` fixes it.

**Comment by mperham** [comment]
We are definitely not reverting to unsafe. You will need to fix your YAML.

**Comment by petergoldstein** [comment]
@mperham There's an alternative to reverting to unsafe.  If you feel aliases here are acceptable, then you can do something like:

    opts = if Psych::VERSION > '4.0'
      YAML.safe_load(erb.result, aliases: true)
    else
      YAML.safe_load(erb.result, [], [], true)
    end

That will still restrict you to 'safe' classes, but allow aliases in the YAML file.  I think that's probably desirable in this case.

**Comment by nickjer** [comment]
Would another option possibly be adding the keyword `aliases: true`, e.g.,

```ruby
YAML.load(erb.result, aliases: true)
```

Note, Rails 7 has gone forward with `YAML.unsafe_load` (https://github.com/rails/rails/pull/42257).

**Comment by mperham** [comment]
Thanks for the background; I'm obviously a bit ignorant here. `aliases: true` sounds like a good thing to enable.

**Comment by petergoldstein** [comment]
I just opened a PR that addresses this and includes an alias test.
