### ISSUE TITLE
Pro Web UI with multiple redis instances and rack

### ISSUE THREAD

**Issue by afterdesign** [mperham/sidekiq#5153]
Ruby version: ruby 3.1.0p0
Rails version: -
Sidekiq / Pro / Enterprise version(s): Pro

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

I want to decouple UI from app and run it as separate service so I stareted with simple rack app and pro web like this:
```
require 'sidekiq/pro/web'
require 'securerandom'

POOL1 = ConnectionPool.new(size: 5, timeout: 5) { Redis.new(url: 'redis://redis_1:6379/0') }
use Rack::Session::Cookie, secret: SecureRandom.hex(32), same_site: true, max_age: 86_400

map '/sidekiq' do
  run Sidekiq::Pro::Web.with(redis_pool: POOL1)
end
```

based on this doc: https://github.com/mperham/sidekiq/wiki/Pro-Web-UI#sharding

but it looks like `redis_pool` is not propagated everywhere and I get only exception that sidekiq tried to connect to `127.0.0.1:6379`. Full backtrace:

```
Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
        /usr/local/bundle/gems/redis-4.5.1/lib/redis/client.rb:398:in `rescue in establish_connection'
        /usr/local/bundle/gems/redis-4.5.1/lib/redis/client.rb:379:in `establish_connection'
        /usr/local/bundle/gems/redis-4.5.1/lib/redis/client.rb:117:in `block in connect'
        /usr/local/bundle/gems/redis-4.5.1/lib/redis/client.rb:344:in `with_reconnect'
        /usr/local/bundle/gems/redis-4.5.1/lib/redis/client.rb:116:in `connect'
        /usr/local/bundle/gems/redis-4.5.1/lib/redis/client.rb:417:in `ensure_connected'
        /usr/local/bundle/gems/redis-4.5.1/lib/redis/client.rb:269:in `block in process'
        /usr/local/bundle/gems/redis-4.5.1/lib/redis/client.rb:356:in `logging'
        /usr/local/bundle/gems/redis-4.5.1/lib/redis/client.rb:268:in `process'
        /usr/local/bundle/gems/redis-4.5.1/lib/redis/client.rb:162:in `call'
        /usr/local/bundle/gems/redis-4.5.1/lib/redis.rb:309:in `block in info'
        /usr/local/bundle/gems/redis-4.5.1/lib/redis.rb:72:in `block in synchronize'
        /usr/local/lib/ruby/3.1.0/monitor.rb:202:in `synchronize'
        /usr/local/lib/ruby/3.1.0/monitor.rb:202:in `mon_synchronize'
        /usr/local/bundle/gems/redis-4.5.1/lib/redis.rb:72:in `synchronize'
        /usr/local/bundle/gems/redis-4.5.1/lib/redis.rb:308:in `info'
        /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq.rb:123:in `block in redis_info'
        /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq.rb:100:in `block in redis'
        /usr/local/bundle/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
        /usr/local/bundle/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
        /usr/local/bundle/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
        /usr/local/bundle/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
        /usr/local/bundle/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
        /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq.rb:97:in `redis'
        /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq.rb:117:in `redis_info'
        /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq/web/helpers.rb:166:in `redis_info'
        /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq/web/application.rb:52:in `block in <class:WebApplication>'
        /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq/web/application.rb:307:in `instance_exec'
        /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq/web/application.rb:307:in `block in call'
        /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq/web/application.rb:305:in `catch'
        /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq/web/application.rb:305:in `call'
        /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq/web/csrf_protection.rb:52:in `admit'
        /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq/web/csrf_protection.rb:41:in `call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/static.rb:161:in `call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
        /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq/web.rb:108:in `call'
        /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq/web.rb:113:in `call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/lint.rb:50:in `_call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/lint.rb:38:in `call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/show_exceptions.rb:23:in `call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/content_length.rb:17:in `call'
        /usr/local/bundle/gems/puma-5.6.1/lib/puma/configuration.rb:252:in `call'
        /usr/local/bundle/gems/puma-5.6.1/lib/puma/request.rb:77:in `block in handle_request'
        /usr/local/bundle/gems/puma-5.6.1/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
        /usr/local/bundle/gems/puma-5.6.1/lib/puma/request.rb:76:in `handle_request'
        /usr/local/bundle/gems/puma-5.6.1/lib/puma/server.rb:441:in `process_client'
        /usr/local/bundle/gems/puma-5.6.1/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by mperham** [comment]
I think you just need to set REDIS_URL. You don’t any of the sharding
stuff.

**Comment by afterdesign** [comment]
OK. So let me explain what I want to do here. I want to use single UI to monitor multiple redis instances used with sidekiq.
From my understanding

**Comment by afterdesign** [comment]
aOK. So let me explain what I want to do here. I want to use single UI to monitor multiple redis instances used with sidekiq.
From my understanding of example ([from here](https://github.com/mperham/sidekiq/wiki/Pro-Web-UI#sharding)) I should be able to get info on different redis instances:
```
POOL1 = ConnectionPool.new { Redis.new(:url => "redis://localhost:6379/0") }
POOL2 = ConnectionPool.new { Redis.new(:url => "redis://localhost:6378/0") }

mount Sidekiq::Web => '/sidekiq' # default
mount Sidekiq::Pro::Web.with(redis_pool: POOL1), at: '/sidekiq1', as: 'sidekiq1' # shard1
mount Sidekiq::Pro::Web.with(redis_pool: POOL2), at: '/sidekiq2', as: 'sidekiq2' # shard2
```

So I've booted 2 different sidekiq instances. One is v6 and the other one is v5.
With normal `configure_client` I can get to first or second (or by setting `REDIS_URL`) but when I'm setting up `POOL1` and `POOL2` I only get to the one that is configured by `REDIS_URL`. Route `/sidekiq2` does not switch to `POOL2` redis.
Also if I don't set REDIS_URL at all I'm getting `Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)`.

Is this the expected behavior or I'm doing something wrong here ?

**Comment by mperham** [comment]
You cannot have v6 Web monitor v5 Sidekiq and vice versa. Any web UI process must be using the same Sidekiq version as its shards. If you want to monitor v5 and v6, you must set up separate web UI processes for v5 and v6.

Your routes look ok. /sidekiq will go to REDIS_URL, /sidekiq1 to POOL1 and /sidekiq2 to POOL2.

**Comment by afterdesign** [comment]
I have created this repository to show the problem: https://github.com/afterdesign/sidekiq-pro-ui-bug

Also as you can see on screenshots `/sidekiq1` and `/sidekiq2` are showing the same redis address
![sidekiq1](https://user-images.githubusercontent.com/672767/151938943-a45f6397-db26-49d1-b6a9-ed7367a146d4.png)
![sidekiq2](https://user-images.githubusercontent.com/672767/151938951-25bd7512-9000-45e0-86a3-c946c0472275.png)

And I even pushed task to `redis_1` and when I was switching URLs I still had info that there was task in redis queue.

**Comment by mperham** [comment]
It's because you never called `require 'sidekiq-pro'` which I thought Bundler does for you?!? I tested it with this code, as I believe you're only supposed to call `run` once.

```ruby
require 'sidekiq-pro'
require 'sidekiq/pro/web'
require 'securerandom'
require 'rack/urlmap'

POOL1 = ConnectionPool.new(size: 5, timeout: 5) { Redis.new(url: 'redis://redis_2:6379/0') }
POOL2 = ConnectionPool.new(size: 5, timeout: 5) { Redis.new(url: 'redis://redis_3:6379/0') }
use Rack::Session::Cookie, secret: SecureRandom.hex(32), same_site: true, max_age: 86_400
run Rack::URLMap.new(
  '/sidekiq' => Sidekiq::Web,
  '/sidekiq1' => Sidekiq::Pro::Web.with(redis_pool: POOL1),
  '/sidekiq2' => Sidekiq::Pro::Web.with(redis_pool: POOL2),
)
```

**Comment by afterdesign** [comment]
@mperham OMG 🤦 Thanks for the wiki update ! ❤️
