### ISSUE TITLE
Job is not a class (TypeError) while upgrading from 6.2.2 to 6.4.0

### ISSUE THREAD

**Issue by Mansh05** [mperham/sidekiq#5156]
Ruby version: 2.7.4
Rails version: 6.1.4.1
Sidekiq / Pro / Enterprise version(s): Sidekiq

Rails application initializer looks for Sidekiq::Job class to initialize the app but in Sidekiq 6.4.0 Job is just a constant which is directly initialized to the Worker Class. While upgrading from 6.2.2 to 6.4.0, This error throws while trying to run the server.

Full Backtrace

```ruby
Traceback (most recent call last):
	51: from bin/rails:4:in `<main>'
	50: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	49: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	48: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	47: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	46: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	45: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/railties-6.1.4.1/lib/rails/commands.rb:18:in `<top (required)>'
	44: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/railties-6.1.4.1/lib/rails/command.rb:48:in `invoke'
	43: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/railties-6.1.4.1/lib/rails/command/base.rb:69:in `perform'
	42: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	41: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	40: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	39: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/railties-6.1.4.1/lib/rails/commands/console/console_command.rb:101:in `perform'
	38: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/railties-6.1.4.1/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	37: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/railties-6.1.4.1/lib/rails/command/actions.rb:22:in `require_application!'
	36: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	35: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	34: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	33: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	32: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	31: from /Users/manish/my_projects/ecko/config/application.rb:22:in `<top (required)>'
	30: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.4/lib/bundler.rb:176:in `require'
	29: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.4/lib/bundler/runtime.rb:44:in `require'
	28: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.4/lib/bundler/runtime.rb:44:in `each'
	27: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.4/lib/bundler/runtime.rb:55:in `block in require'
	26: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.4/lib/bundler/runtime.rb:55:in `each'
	25: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.4/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	24: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	23: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	22: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	21: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	20: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	19: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/sidekiq-unique-jobs-7.1.5/lib/sidekiq-unique-jobs.rb:3:in `<top (required)>'
	18: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
	17: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	16: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
	15: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	14: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	13: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	12: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	11: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	10: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/sidekiq-unique-jobs-7.1.5/lib/sidekiq_unique_jobs.rb:71:in `<top (required)>'
	 9: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
	 8: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	 7: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
	 6: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	 5: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 4: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 3: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 2: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 1: from /Users/manish/.rvm/gems/ruby-2.7.4/gems/sidekiq-unique-jobs-7.1.5/lib/sidekiq_unique_jobs/sidekiq_unique_ext.rb:8:in `<top (required)>'
/Users/manish/.rvm/gems/ruby-2.7.4/gems/sidekiq-unique-jobs-7.1.5/lib/sidekiq_unique_jobs/sidekiq_unique_ext.rb:72:in `<module:Sidekiq>': Job is not a class (TypeError)
/Users/manish/.rvm/gems/ruby-2.7.4/gems/sidekiq-6.4.0/lib/sidekiq/job.rb:12: previous definition of Job was here
```

**Comment by adamniedzielski** [comment]
Hey, it looks like you’re using an extension to Sidekiq called sidekiq-
unique-jobs. Best to check there, maybe they need to release a new version
or you need to upgrade.

**Comment by Mansh05** [comment]
thanks upgrade of sidekiq-unique-jobs from 7.1.5 to 7.1.12 fixed it.
