### ISSUE TITLE
NoMethodError: private method `gets' called for true:TrueClass

### ISSUE THREAD

**Issue by krauseup** [mperham/sidekiq#5190]
Ruby version: 2.7.2
Rails version: 6.0.4.4
Sidekiq / Pro / Enterprise version(s): 6.4.1 / 5.3.1

```
gems/sidekiq-6.4.1/lib/sidekiq/cli.rb:119:in `launch': private method `gets' called for true:TrueClass (NoMethodError)
    from gems/sidekiq-6.4.1/lib/sidekiq/cli.rb:105:in `run'
    from gems/sidekiq-6.4.1/bin/sidekiq:31:in `<top (required)>'
    from bin/sidekiq:23:in `load'
    from bin/sidekiq:23:in `<top (required)>'
    from /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
    from /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
    from /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
    from /usr/local/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
    from /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    from /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
    from /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
    from /usr/local/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
    from /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
    from /usr/local/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
    from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
    from /usr/local/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
    from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
    from bin/bundle:3:in `load'
    from bin/bundle:3:in `<main>'
 ```
 
![Bugsnag screenshot](https://user-images.githubusercontent.com/13872744/153096393-d5723f6a-f24e-44ec-ac5a-585fcdb1614b.png)

 

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/main/Changes.md
https://github.com/mperham/sidekiq/blob/main/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/main/Ent-Changes.md

**Comment by anark** [comment]
When did you run into this issue?  Should this prevent us from updating to 6.4.1 and instead wait for 6.4.2?

**Comment by mperham** [comment]
It should be a rare issue, which is why no one else has reported it yet. I
believe it’s a signal handling race condition. I don’t plan on rushing
6.4.2 out, you can also run main if you hit the issue.
