### ISSUE TITLE
Sidekiq trying to connect to Redis while running tests

### ISSUE THREAD

**Issue by bgvo** [mperham/sidekiq#5198]
### Context
Ruby version: 3.0.0
Rails version: 6.1.4
Sidekiq / Pro / Enterprise version(s): Sidekiq

* Initilizer: [sidekiq.rb](https://gist.github.com/bgvo/ab2bc3103be92cccec3fe5d541ccdae2)
* [sidekiq.yml](https://gist.github.com/bgvo/a89aa1b630879aa775ec6c987afc67bc)

### Issue
Tests are failing because Rails cannot connect to Redis. The URL for Redis as env variable is incorrect on purpose. Before, when the URL is set correctly tests pass without errors. 

### Expected behavior
Since fake is the default mode when requiring "sidekiq/testing", I don't expect the app to try to connect to Redis. However, it is.

#### Source code

```ruby
require "rails_helper"

RSpec.describe Salesforce::CreatePersonAccountJob do
  context "Given a new person to connect to Salesforce" do
    setup do
      @assessment = create(:assessment)
      @person = create(:person)
      @person.emails.create(address: Faker::Internet.email)
      @person.phones.create(number: "6667778888")
      @person.interests.create(assessment: @assessment, interest_type: "Daughter")

      $salesforce = double("Salesforce", create: "SALESFORCEID", query: [Hashie::Mash.new(Id: 1)]).as_null_object
      allow(Salesforce::PersonAccount).to receive(:where).and_return(nil)
      allow(Salesforce::PersonAccount).to receive(:find_by_phone_number).and_return(nil)
      allow($salesforce).to receive(:query).with(/Account\.OwnerId/).and_return([Hashie::Mash.new(Account: { OwnerId: 1 })])
    end

    after(:each) do
      Salesforce::CreatePersonAccountJob.perform_synch(@person.id)
    end

    it "searches Salesforce for Person" do
      expect(Salesforce::PersonAccount).to receive(:where).with(PersonEmail: @person.emails.first.address)
      expect(Salesforce::PersonAccount).to receive(:find_by_phone_number).with("6667778888")
    end
end
```

Relevant source code for on [rails_helper.rb](https://gist.github.com/bgvo/83a8f772db668ca7e942c2ec10ad693b) and [person.rb](https://gist.github.com/bgvo/6ef545915d4541802594441047468a9d)

#### Backtrace

```
Failures:

  1) Salesforce::CreatePersonAccountJob Given a new person to connect to Salesforce searches Salesforce for Person
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: Salesforce::CreatePersonAccountJob.set(wait: 5.minutes).perform_async(self.id)

          Redis::CannotConnectError:
            Error connecting to Redis on localhost:6371 (Errno::ECONNREFUSED)
          # ./app/models/person.rb:246:in `send_to_salesforce'
          # <internal:kernel>:90:in `tap'
          # ./spec/jobs/salesforce/create_person_account_job_spec.rb:7:in `block (3 levels) in <top (required)>'
          # ------------------
          # --- Caused by: ---
          # IO::EINPROGRESSWaitWritable:
          #   Operation now in progress - connect(2) would block
          #   ./app/models/person.rb:246:in `send_to_salesforce'
```

**Comment by bgvo** [comment]
@mperham sure

```
bundle exec rspec .
/Users/borjagvo/.rbenv/versions/3.0.0/lib/ruby/3.0.0/digest.rb:6: warning: already initialized constant Digest::REQUIRE_MUTEX
/Users/borjagvo/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/digest-3.1.0/lib/digest.rb:20: warning: previous definition of REQUIRE_MUTEX was here
.......F....................................................

Failures:

  1) Salesforce::CreatePersonAccountJob Given a new person to connect to Salesforce searches Salesforce for Person
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: Salesforce::CreatePersonAccountJob.set(wait: 5.minutes).perform_async(self.id)

          Redis::CannotConnectError:
            Error connecting to Redis on localhost:6371 (Errno::ECONNREFUSED)
          # ./app/models/person.rb:246:in `send_to_salesforce'
          # <internal:kernel>:90:in `tap'
          # ./spec/jobs/salesforce/create_person_account_job_spec.rb:7:in `block (3 levels) in <top (required)>'
          # ------------------
          # --- Caused by: ---
          # IO::EINPROGRESSWaitWritable:
          #   Operation now in progress - connect(2) would block
          #   ./app/models/person.rb:246:in `send_to_salesforce'

     1.2) Failure/Error: Salesforce::CreatePersonAccountJob.perform_synch(@person.id)

          NoMethodError:
            undefined method `id' for nil:NilClass
          # ./spec/jobs/salesforce/create_person_account_job_spec.rb:19:in `block (3 levels) in <top (required)>'

Finished in 2.73 seconds (files took 9.61 seconds to load)
60 examples, 1 failure

Failed examples:

rspec ./spec/jobs/salesforce/create_person_account_job_spec.rb:22 # Salesforce::CreatePersonAccountJob Given a new person to connect to Salesforce searches Salesforce for Person

Coverage report generated for RSpec to /Users/borjagvo/Work/project/coverage. 1468 / 2015 LOC (72.85%) covered.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
```

**Comment by mperham** [comment]
That’s not the whole backtrace. Try BACKTRACE=1 in front of that command.

**Comment by bgvo** [comment]
@mperham, I get the same output:

```
➜  jukebox git:(dependabot/bundler/puma-5.6.2) ✗ BACKTRACE=1 bundle exec rspec .
/Users/borjagvo/.rbenv/versions/3.0.0/lib/ruby/3.0.0/digest.rb:6: warning: already initialized constant Digest::REQUIRE_MUTEX
/Users/borjagvo/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/digest-3.1.0/lib/digest.rb:20: warning: previous definition of REQUIRE_MUTEX was here
.......F....................................................

Failures:

  1) Salesforce::CreatePersonAccountJob Given a new person to connect to Salesforce searches Salesforce for Person
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: Salesforce::CreatePersonAccountJob.set(wait: 5.minutes).perform_async(self.id)

          Redis::CannotConnectError:
            Error connecting to Redis on localhost:6371 (Errno::ECONNREFUSED)
          # ./app/models/person.rb:246:in `send_to_salesforce'
          # <internal:kernel>:90:in `tap'
          # ./spec/jobs/salesforce/create_person_account_job_spec.rb:7:in `block (3 levels) in <top (required)>'
          # ------------------
          # --- Caused by: ---
          # IO::EINPROGRESSWaitWritable:
          #   Operation now in progress - connect(2) would block
          #   ./app/models/person.rb:246:in `send_to_salesforce'

     1.2) Failure/Error: Salesforce::CreatePersonAccountJob.perform_synch(@person.id)

          NoMethodError:
            undefined method `id' for nil:NilClass
          # ./spec/jobs/salesforce/create_person_account_job_spec.rb:19:in `block (3 levels) in <top (required)>'

Finished in 2.04 seconds (files took 6 seconds to load)
60 examples, 1 failure

Failed examples:

rspec ./spec/jobs/salesforce/create_person_account_job_spec.rb:22 # Salesforce::CreatePersonAccountJob Given a new person to connect to Salesforce searches Salesforce for Person

Coverage report generated for RSpec to /Users/borjagvo/Work/project/coverage. 1468 / 2015 LOC (72.85%) covered.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
```

Maybe some config is avoiding throwing out the whole backtrace?  🤔

**Comment by mperham** [comment]
If you can't give me a backtrace, I can't determine why its connecting to Redis. Maybe it's another Sidekiq plugin, who knows?

**Comment by bgvo** [comment]
For anyone that has this problem, check plugins as @mperham suggested. In my case, the problem was caused by `sidekiq-unique-jobs` gem.

**Comment by ciscou** [comment]
👋 We've stumbled upon the same issue after upgrading to Sidekiq 7.x, and after digging into the code, looks like the only difference is that 6.x does `logger.debug` (resulting in a no-op) here: https://github.com/sidekiq/sidekiq/blob/ad0f13cac5138b891d54ef2f2df3460d5151e34c/lib/sidekiq/redis_connection.rb#L146, while 7.x does `logger.info`, adding a line in the middle of the `rspec` output, here: https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/redis_connection.rb#L15

We've solved it by adding this to `config/initializers/sidekiq.rb`

```
Sidekiq.configure_client do |config|
  config.logger = nil if Rails.env.test?
end
```

**Comment by heaven** [comment]
After upgrading to v7, I started seeing this message while running tests:
```
2025-03-23T11:33:41.578Z pid=33829 tid=r05 INFO: Sidekiq 7.3.9 connecting to Redis with options {size: 10, pool_name: "internal", url: "redis://127.0.0.1:6379/1"}
```

However, the actual connection doesn't happen and the test succeeds even with Redis stopped. So the message is a bit misleading, made me worry.

**Comment by testflyjets** [comment]
I'm seeing the same behavior. More troubling is the fact that the test seems to pause for at least 5 seconds while Sidekiq is doing something internally with the Redis connection with Sidekiq::Testing.inline! set. 

@mperham Anything we can do to help diagnose this? The only other Sidekiq-related gem I'm using is sidekiq-cron. This is in Rails 7.1.5.1 and Ruby 3.4.4.

**Comment by mperham** [comment]
A backtrace would help immensely. You can add code to your test suite to dump a backtrace every second.
