### ISSUE TITLE
HTTP read timeouts cause dead jobs, retrying does not fix them

### ISSUE THREAD

**Issue by pelargir** [mperham/sidekiq#5264]
Ruby version: 2.7.5p203
Rails version: 6.0.4.7
Sidekiq / Pro / Enterprise version(s): 6.4.1

We're experiencing a baffling problem with workers that call a USPS API to get a shipping rate back. Most of these workers finish successfully, however, a few end up in the morgue after repeatedly experiencing HTTP read timeouts.

The problem is, these same workers can be executed from the Heroku console successfully. An identical raw API request can also be sent successfully from the command line with a `curl` command.

The workers are using an HTTP read timeout of 60 seconds. Each time we retry these failed workers from the morgue, I can observe the worker processing on the "Busy" page as the started timer counts up to 60 seconds. Meanwhile, other workers are getting kicked off by our customers, appearing on the "Busy" page, and finishing immediately. As soon as the timer gets to 60 seconds, the problem worker ends up in the morgue again, the same read timeout error having occurred.

We're reporting the underlying exception (`RestClient::Exceptions::ReadTimeout`) to Bugsnag. Here is the stack trace:

```
vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:751:in `rescue in transmit': Timed out reading data from server (RestClient::Exceptions::ReadTimeout)
    from vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
    from vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
    from vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
    from app/services/cs/shipping/http_client.rb:38:in `execute'
    from app/services/cs/shipping/http_client.rb:22:in `post'
    from vendor/bundle/ruby/2.7.0/gems/friendly_shipping-0.6.4/lib/friendly_shipping/services/usps.rb:63:in `rate_estimates'
    from app/models/spree/calculator/shipping/api_calculator.rb:80:in `rates_result'
    from app/models/spree/calculator/shipping/api_calculator.rb:32:in `rate_for'
    from app/services/cs/shipping/rate_discrepancy_checker.rb:89:in `api_result'
    from app/services/cs/shipping/rate_discrepancy_checker.rb:38:in `api_result?'
    from app/services/cs/shipping/rate_discrepancy_checker.rb:17:in `check_rate'
    from app/workers/cs/rate_discrepancy_worker.rb:11:in `block in perform'
    from vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.7/lib/active_record/relation/delegation.rb:88:in `each'
    from vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.7/lib/active_record/relation/delegation.rb:88:in `each'
    from app/workers/cs/rate_discrepancy_worker.rb:10:in `perform'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:196:in `execute_job'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-status-2.1.3/lib/sidekiq-status/server_middleware.rb:42:in `call'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
    from vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.5.0/lib/new_relic/agent/instrumentation/sidekiq.rb:35:in `block in call'
    from vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.5.0/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:377:in `perform_action_with_newrelic_trace'
    from vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.5.0/lib/new_relic/agent/instrumentation/sidekiq.rb:30:in `call'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
    from vendor/bundle/ruby/2.7.0/gems/bugsnag-6.24.2/lib/bugsnag/integrations/sidekiq.rb:24:in `call'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:163:in `block in process'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/job_retry.rb:114:in `local'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/rails.rb:14:in `block in call'
    from vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/execution_wrapper.rb:91:in `wrap'
    from vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/reloader.rb:72:in `block in wrap'
    from vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/execution_wrapper.rb:91:in `wrap'
    from vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/reloader.rb:71:in `wrap'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/rails.rb:13:in `call'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:257:in `stats'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/job_logger.rb:13:in `call'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/job_retry.rb:81:in `global'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/job_logger.rb:39:in `prepare'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:123:in `dispatch'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:162:in `process'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:78:in `process_one'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:68:in `run'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/util.rb:56:in `watchdog'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/util.rb:65:in `block in safe_thread'

Caused by: vendor/ruby-2.7.5/lib/ruby/2.7.0/net/protocol.rb:217:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
    from vendor/ruby-2.7.5/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
    from vendor/ruby-2.7.5/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'
    from vendor/ruby-2.7.5/lib/ruby/2.7.0/net/http/response.rb:42:in `read_status_line'
    from vendor/ruby-2.7.5/lib/ruby/2.7.0/net/http/response.rb:31:in `read_new'
    from vendor/ruby-2.7.5/lib/ruby/2.7.0/net/http.rb:1528:in `block in transport_request'
    from vendor/ruby-2.7.5/lib/ruby/2.7.0/net/http.rb:1519:in `catch'
    from vendor/ruby-2.7.5/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request'
    from vendor/ruby-2.7.5/lib/ruby/2.7.0/net/http.rb:1492:in `request'
    from vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.5.0/lib/new_relic/agent/instrumentation/net_http/chain.rb:15:in `block in request_with_newrelic_trace'
    from vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.5.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:26:in `block (2 levels) in request_with_tracing'
    from vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.5.0/lib/new_relic/agent/tracer.rb:351:in `capture_segment_error'
    from vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.5.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:25:in `block in request_with_tracing'
    from vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.5.0/lib/new_relic/agent.rb:502:in `disable_all_tracing'
    from vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.5.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:24:in `request_with_tracing'
    from vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.5.0/lib/new_relic/agent/instrumentation/net_http/chain.rb:15:in `request_with_newrelic_trace'
    from vendor/bundle/ruby/2.7.0/gems/rack-mini-profiler-3.0.0/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler'
    from vendor/bundle/ruby/2.7.0/gems/rack-mini-profiler-3.0.0/lib/mini_profiler/profiling_methods.rb:46:in `step'
    from vendor/bundle/ruby/2.7.0/gems/rack-mini-profiler-3.0.0/lib/patches/net_patches.rb:18:in `request_with_mini_profiler'
    from vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:471:in `net_http_do_request'
    from vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:733:in `block in transmit'
    from vendor/ruby-2.7.5/lib/ruby/2.7.0/net/http.rb:933:in `start'
    from vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
    from vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
    from vendor/bundle/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
    from app/services/cs/shipping/http_client.rb:38:in `execute'
    from app/services/cs/shipping/http_client.rb:22:in `post'
    from vendor/bundle/ruby/2.7.0/gems/friendly_shipping-0.6.4/lib/friendly_shipping/services/usps.rb:63:in `rate_estimates'
    from app/models/spree/calculator/shipping/api_calculator.rb:80:in `rates_result'
    from app/models/spree/calculator/shipping/api_calculator.rb:32:in `rate_for'
    from app/services/cs/shipping/rate_discrepancy_checker.rb:89:in `api_result'
    from app/services/cs/shipping/rate_discrepancy_checker.rb:38:in `api_result?'
    from app/services/cs/shipping/rate_discrepancy_checker.rb:17:in `check_rate'
    from app/workers/cs/rate_discrepancy_worker.rb:11:in `block in perform'
    from vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.7/lib/active_record/relation/delegation.rb:88:in `each'
    from vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.7/lib/active_record/relation/delegation.rb:88:in `each'
    from app/workers/cs/rate_discrepancy_worker.rb:10:in `perform'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:196:in `execute_job'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-status-2.1.3/lib/sidekiq-status/server_middleware.rb:42:in `call'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
    from vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.5.0/lib/new_relic/agent/instrumentation/sidekiq.rb:35:in `block in call'
    from vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.5.0/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:377:in `perform_action_with_newrelic_trace'
    from vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.5.0/lib/new_relic/agent/instrumentation/sidekiq.rb:30:in `call'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
    from vendor/bundle/ruby/2.7.0/gems/bugsnag-6.24.2/lib/bugsnag/integrations/sidekiq.rb:24:in `call'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:163:in `block in process'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/job_retry.rb:114:in `local'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/rails.rb:14:in `block in call'
    from vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/execution_wrapper.rb:91:in `wrap'
    from vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/reloader.rb:72:in `block in wrap'
    from vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/execution_wrapper.rb:91:in `wrap'
    from vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/reloader.rb:71:in `wrap'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/rails.rb:13:in `call'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:257:in `stats'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/job_logger.rb:13:in `call'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/job_retry.rb:81:in `global'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/job_logger.rb:39:in `prepare'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:123:in `dispatch'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:162:in `process'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:78:in `process_one'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:68:in `run'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/util.rb:56:in `watchdog'
    from vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/util.rb:65:in `block in safe_thread'
```

We can't determine why these workers **only** fail in Sidekiq and **only** in our production environment. Running these same workers locally with the same arguments works fine. Running the worker synchronously from the Heroku console works fine. And running the worker asynchronously from the Heroku console _**also**_ works fine. For example:

`[1] pry(main)> Cs::RateDiscrepancyWorker.perform_async(123)`

This queues the worker in Sidekiq _and it succeeds almost instantly._ No timeout errors.

We thought perhaps the API request body was malformed or had strange characters that were causing the USPS API to spin. But if this was the case, why does our `curl` command succeed and why can the worker be queued from the Heroku console and succeed?

Another theory was that the IP address the request was originating from was somehow blocklisted by USPS. But if that were the case, why is this only happening for a small minority of workers? Shouldn't they all be failing similarly? And why does the worker succeed when queued in Sidekiq from the Heroku console?

I'm opening this issue because we're totally out of theories as to why this could be happening. Any ideas?

Here are our config and initializer files:

`sidekiq.yml`
```yml
:concurrency: 1
:max_retries: 7
```

`sidekiq.rb`
```ruby
# frozen_string_literal: true

require 'sidekiq'
require 'sidekiq-status'
require 'cs/bugsnag_sidekiq_death_handler'

redis_db_index = ENV.fetch('REDIS_SIDEKIQ_DB_INDEX')
redis_url = ENV.fetch('REDIS_SIDEKIQ_URL', 'redis://127.0.0.1:6379') + "/#{redis_db_index}/sidekiq"

Sidekiq.configure_server do |config|
  config.log_formatter = Sidekiq::Logger::Formatters::JSON.new unless Rails.env.development?
  config.redis = { url: redis_url, id: nil }
  config.server_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes # default
  end

  config.client_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes # default
  end

  config.death_handlers << Cs::BugsnagSidekiqDeathHandler.handler
end

Sidekiq.configure_client do |config|
  config.redis = { url: redis_url, id: nil }
  config.client_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes # default
  end
end
```

`Procfile`
```
web: jemalloc.sh bundle exec puma -C config/puma.rb
worker: jemalloc.sh bundle exec sidekiq -q default -q algoliasearch -q warehouse -q mailers -q low -C config/sidekiq.yml
```

**Comment by adamniedzielski** [comment]
🤔 IMO the odds are 99.9% something weird with the API, 0.1% something with Sidekiq. My bet is on rate limiting from the API. https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting could help you.

**Comment by pelargir** [comment]
> 🤔 IMO the odds are 99.9% something weird with the API, 0.1% something with Sidekiq. My bet is on rate limiting from the API. https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting could help you.

That possibility had occurred to me as well, but if rate limiting is responsible why does the _same_ job fail over and over again while other jobs running at the same time succeed?

If rate limiting was a factor, I'd expect jobs to fail intermittently and for failed jobs to sometimes succeed and sometimes fail when retried. But once a job fails, it continues failing on every retry... seemingly forever.

**Comment by adamniedzielski** [comment]
Great question! I don't know. The advantage of Sidekiq being open source is that you can read its code and see if you find something that might cause your bug. You can't do the same with the external API. That's why my bets remain on the external API 😉

**Comment by mperham** [comment]
I can't imagine how Sidekiq could cause this. 🤔
