### ISSUE TITLE
READONLY You can't write against a read only slave

### ISSUE THREAD

**Issue by justin808** [mperham/sidekiq#5271]
Any information on the odd error that is shown below?

Ruby version: 2.7.5
Rails version: 7
Sidekiq / Pro / Enterprise version(s):

 sidekiq (6.4.1)
    sidekiq-ent (2.3.1)
      einhorn (>= 0.7.4)
      sidekiq (>= 6.3.0)
      sidekiq-pro (>= 5.3.0)
    sidekiq-pro (5.3.1)
      sidekiq (>= 6.3.0)

Error:
```
Encountered error: "ERR Error running script (call to f_3aac19a3ba78708896fe4397957b506773e3259f): @user_script:1: @user_script: 1: -READONLY You can't write against a read only slave."
```

Stack:

```
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:163:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.5.1/lib/redis.rb:2811:in `block in _eval'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.5.1/lib/redis.rb:72:in `block in synchronize'
/app/vendor/ruby-2.7.5/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
/app/vendor/ruby-2.7.5/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.5.1/lib/redis.rb:72:in `synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.5.1/lib/redis.rb:2810:in `_eval'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.5.1/lib/redis.rb:2862:in `evalsha'
/app/vendor/bundle/ruby/2.7.0/gems/redis-namespace-1.8.2/lib/redis/namespace.rb:476:in `call_with_namespace'
/app/vendor/bundle/ruby/2.7.0/gems/redis-namespace-1.8.2/lib/redis/namespace.rb:352:in `block (2 levels) in <class:Namespace>'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.3.1/lib/sidekiq-ent/scripting.rb:22:in `block in call'
/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.3.1/lib/sidekiq-ent/scripting.rb:21:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.3.1/lib/sidekiq-ent/limiter/concurrent.rb:140:in `unlock'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.3.1/lib/sidekiq-ent/limiter/concurrent.rb:63:in `ensure in within_limit'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.3.1/lib/sidekiq-ent/limiter/concurrent.rb:63:in `within_limit'
```

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/blob/c1b8eba18f6f943416f26f78310f4785d0e5d680/lib/sidekiq.rb#L102

**Comment by justin808** [comment]
I updated the description:

```
 sidekiq (6.4.1)
```

What sort of action item should we take? Or should we be put in a catch to retry? Or is retry happening already and we should just ignore the sentry errors?

**Comment by mperham** [comment]
I will research tomorrow. I just noticed the error comes from the limiter subsystem, maybe there’s an issue with Lua failover there.

**Comment by mperham** [comment]
Note the logic in the block above. If we see a READONLY error, we'll retry the operation once by disconnecting the client and re-establishing a new socket, assuming that the new primary is ready. But it will raise the error if it happens again. I'm guessing that it didn't connect to the new primary due to DNS issues, possibly a stale cache entry. Anyways, I can't tell more than that, I'd contact your Redis SaaS provider and ask if their logs give any more clues.
