### ISSUE TITLE
Few jobs are not processed by sidekiq

### ISSUE THREAD

**Issue by venkatac-ayla** [mperham/sidekiq#5307]
Ruby version - 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
Rails version - 3.2.13
Sidekiq version -2.17.7

Few jobs are pending for ever in sidekiq. 

Backtrace after running kill -TTIN <PID>
```
2022-05-01T01:46:54Z 12 TID-ma51w INFO: ReliableFetch activated
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: Thread TID-43ek4
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: /usr/local/bundle/gems/sidekiq-2.17.7/lib/sidekiq/cli.rb:121:in `block in handle_signal'
/usr/local/bundle/gems/sidekiq-2.17.7/lib/sidekiq/cli.rb:118:in `each'
/usr/local/bundle/gems/sidekiq-2.17.7/lib/sidekiq/cli.rb:118:in `handle_signal'
/usr/local/bundle/gems/sidekiq-2.17.7/lib/sidekiq/cli.rb:79:in `run'
/usr/local/bundle/gems/sidekiq-2.17.7/bin/sidekiq:8:in `<top (required)>'
/usr/local/bundle/bin/sidekiq:29:in `load'
/usr/local/bundle/bin/sidekiq:29:in `<top (required)>'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.16.5/lib/bundler/cli.rb:424:in `exec'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.16.5/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.16.5/lib/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.16.5/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.16.5/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.16.5/exe/bundle:22:in `<top (required)>'
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: Thread TID-82d0c
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: /usr/local/lib/ruby/1.9.1/thread.rb:71:in `wait'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/mailbox.rb:69:in `receive'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:173:in `run'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:157:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: Thread TID-4026s
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: /usr/local/lib/ruby/1.9.1/thread.rb:71:in `wait'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/mailbox.rb:69:in `receive'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:173:in `run'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:157:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: Thread TID-4ph54
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: /usr/local/lib/ruby/1.9.1/thread.rb:71:in `wait'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/mailbox.rb:69:in `receive'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:173:in `run'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:157:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: Thread TID-4mt50
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: /usr/local/lib/ruby/1.9.1/thread.rb:71:in `wait'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/mailbox.rb:69:in `receive'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:173:in `run'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:157:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: Thread TID-ko04w
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: /usr/local/lib/ruby/1.9.1/webrick/server.rb:98:in `block in start'
/usr/local/lib/ruby/1.9.1/webrick/server.rb:22:in `start'
/usr/local/lib/ruby/1.9.1/webrick/server.rb:89:in `start'
/ayla/factoryservice/config/initializers/sidekiq.rb:24:in `block (2 levels) in <top (required)>'
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: Thread TID-scmps
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: /usr/local/lib/ruby/1.9.1/thread.rb:71:in `wait'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/mailbox.rb:69:in `receive'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:173:in `run'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:157:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: Thread TID-75aas
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: /usr/local/lib/ruby/1.9.1/thread.rb:71:in `wait'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/mailbox.rb:69:in `receive'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:173:in `run'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:157:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: Thread TID-hhv7s
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: /usr/local/lib/ruby/1.9.1/thread.rb:71:in `wait'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/mailbox.rb:69:in `receive'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:173:in `run'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:157:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: Thread TID-ix0ig
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: /usr/local/lib/ruby/1.9.1/thread.rb:71:in `wait'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/mailbox.rb:69:in `receive'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:173:in `run'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:157:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: Thread TID-losy8
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: /usr/local/lib/ruby/1.9.1/thread.rb:71:in `wait'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/mailbox.rb:69:in `receive'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:173:in `run'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:157:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: Thread TID-oue0e59g8
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: /usr/local/lib/ruby/1.9.1/thread.rb:71:in `wait'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/mailbox.rb:69:in `receive'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:173:in `run'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:157:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: Thread TID-oue0e56gg
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: /usr/local/lib/ruby/1.9.1/thread.rb:71:in `wait'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/mailbox.rb:69:in `receive'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:173:in `run'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:157:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: Thread TID-7w60k
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: /usr/local/lib/ruby/1.9.1/thread.rb:71:in `wait'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/mailbox.rb:69:in `receive'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:173:in `run'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:157:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: Thread TID-ma51w
2022-05-01T01:56:17Z 12 TID-43ek4 INFO: /usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:87:in `rescue in _read_from_socket'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:83:in `_read_from_socket'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:75:in `gets'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:380:in `read'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:262:in `block in read'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:250:in `io'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:261:in `read'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:120:in `block in call'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:231:in `block (2 levels) in process'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:367:in `ensure_connected'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:221:in `block in process'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:306:in `logging'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:220:in `process'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:120:in `call'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:209:in `block in call_with_timeout'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:280:in `with_socket_timeout'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:208:in `call_with_timeout'
/usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:1205:in `block in brpoplpush'
/usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:58:in `block in synchronize'
/usr/local/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:58:in `synchronize'
/usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:1202:in `brpoplpush'
/usr/local/bundle/gems/sidekiq-pro-1.5.1/lib/sidekiq/pro/reliable_fetch.rb:107:in `block (2 levels) in <class:ReliableFetch>'
/usr/local/bundle/gems/connection_pool-1.1.0/lib/connection_pool.rb:49:in `with'
/usr/local/bundle/gems/sidekiq-2.17.7/lib/sidekiq.rb:67:in `redis'
/usr/local/bundle/gems/sidekiq-pro-1.5.1/lib/sidekiq/pro/reliable_fetch.rb:99:in `block in <class:ReliableFetch>'
/usr/local/bundle/gems/sidekiq-pro-1.5.1/lib/sidekiq/pro/reliable_fetch.rb:46:in `call'
/usr/local/bundle/gems/sidekiq-pro-1.5.1/lib/sidekiq/pro/reliable_fetch.rb:46:in `retrieve_work'
/usr/local/bundle/gems/sidekiq-2.17.7/lib/sidekiq/fetch.rb:36:in `block in fetch'
/usr/local/bundle/gems/sidekiq-2.17.7/lib/sidekiq/util.rb:15:in `watchdog'
/usr/local/bundle/gems/sidekiq-2.17.7/lib/sidekiq/fetch.rb:32:in `fetch'
/usr/local/bundle/gems/sidekiq-2.17.7/lib/sidekiq/fetch.rb:43:in `block (2 levels) in fetch'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```

Please find the redis details below. This behaviour is seen on many occasions but here job details of one of them
`keys *
 1) "stat:processed:2022-04-15"
 2) "stat:processed:2022-04-19"
 3) "stat:failed:2022-04-11"
 4) "stat:processed:2022-04-17"
 5) "queue:default_afs-sidekiq-58989dbb8f-bpvwl_0"
 6) "stat:processed:2022-04-23"
 7) "stat:processed:2022-04-25"
 8) "stat:processed:2022-04-07"
 9) "stat:processed:2022-04-13"
10) "queue:default_afs-sidekiq-68dbd8b48c-7564r_0"
11) "queue:default_afs-sidekiq-8f46bf8bf-8hfbd_0"
12) "stat:processed:2022-04-04"
13) "stat:processed:2022-04-20"
14) "stat:failed:2022-04-08"
15) "queue:default_afs-sidekiq-7f4d988545-6n7pt_0"
16) "stat:processed:2022-04-30"
17) "queue:default_afs-sidekiq-846c8dbc5b-znssx_0"
18) "stat:failed:2022-04-14"
19) "workers"
20) "stat:processed:2022-04-22"
21) "queue:default_afs-sidekiq-7f4d988545-c4877_0"
22) "queue:default_afs-sidekiq-79c6b69d8f-gkbh9_0"
23) "stat:failed:2022-04-25"
24) "stat:failed:2022-04-26"
25) "stat:failed"
26) "stat:failed:2022-04-22"
27) "stat:processed:2022-04-27"
28) "stat:processed"
29) "stat:failed:2022-04-06"
30) "stat:processed:2022-04-06"
31) "stat:failed:2022-04-13"
32) "stat:processed:2022-04-14"
33) "stat:processed:2022-04-28"
34) "queue:default_afs-sidekiq-5448dc56f5-8z4mm_0"
35) "stat:processed:2022-04-21"
36) "queue:default_afs-sidekiq-79c6b69d8f-55k5d_0"
37) "stat:failed:2022-04-05"
38) "queue:default_afs-sidekiq-6fcf977c49-j862k_0"
39) "stat:processed:2022-04-05"
40) "queue:default_afs-sidekiq-69779b98f9-lvzdv_0"
41) "queue:default_afs-sidekiq-867b774567-fhbs5_0"
42) "queues"
43) "stat:processed:2022-04-29"
44) "stat:failed:2022-04-19"
45) "stat:processed:2022-04-08"
46) "stat:processed:2022-04-16"
47) "stat:processed:2022-05-01"
48) "stat:failed:2022-04-29"
49) "stat:processed:2022-04-26"
50) "stat:failed:2022-04-12"
51) "queue:default_afs-sidekiq-58989dbb8f-t8k2l_0"
52) "stat:processed:2022-04-12"
53) "stat:processed:2022-04-09"
54) "stat:processed:2022-04-11"
55) "stat:failed:2022-04-09"
56) "stat:processed:2022-04-18"
57) "stat:processed:2022-04-24"
58) "stat:failed:2022-04-27"
59) "stat:failed:2022-04-07"

 lrange "queue:default_afs-sidekiq-58989dbb8f-bpvwl_0" 0 8
1) "{\"retry\":true,\"queue\":\"default\",\"backtrace\":true,\"backtrace\":true,\"class\":\"Jobs::RunProcessJobWorker\",\"args\":[4768],\"jid\":\"15e5566e4e6bc9b273e2923a\",\"enqueued_at\":1651233805.2714403}"`

Above job is pending from 29th Apr 2022. 

Please let us know how to resolve this issue.

**Comment by mperham** [comment]
I haven’t supported Sidekiq 2.x for years. Sidekiq 5.x is the minimum supported version.

**Comment by sathishkumar-ayla** [comment]
@mperham Does Sidekiq version -5.0.0 will resolve the issue?
