### ISSUE TITLE
Question: Sidekiqswarm vs Sidekiq Boot

### ISSUE THREAD

**Issue by xenyal** [mperham/sidekiq#5310]
I'm running Sidekiq 5.2.9 (Enterprise) on Ruby 2.6.0, and I've recently tried to use `sidekiqswarm`, however am getting stuck trying to resolve various Gem-level errors (`uninitialized constant (NameError)`). However, none of the errors occur when using `sidekiq`. Might you know of any gem requiring or boot-related differences between `sidekiq` and `sidekiqswarm` that needs to be taken into account during setup?

An example of the error:
```
~ $ bundle exec sidekiqswarm -C config/sidekiq.yml

[swarm] Preloading Bundler groups ["default"]
bundler: failed to load command: sidekiqswarm (/app/vendor/bundle/ruby/2.6.0/bin/sidekiqswarm)
30 TID-otxxxdpwy INFO: Booting Sidekiq 5.2.9 with redis options {:id=>"[REDACTED]", :url=>"[REDACTED]"}

/app/vendor/bundle/ruby/2.6.0/gems/shopify_app-12.0.7/lib/shopify_app/jobs/webhooks_manager_job.rb:2:in `<module:ShopifyApp>': uninitialized constant ShopifyApp::ActiveJob (NameError)
        from /app/vendor/bundle/ruby/2.6.0/gems/shopify_app-12.0.7/lib/shopify_app/jobs/webhooks_manager_job.rb:1:in `<top (required)>'
        from /app/vendor/bundle/ruby/2.6.0/gems/shopify_app-12.0.7/lib/shopify_app.rb:36:in `<module:ShopifyApp>'
        from /app/vendor/bundle/ruby/2.6.0/gems/shopify_app-12.0.7/lib/shopify_app.rb:7:in `<top (required)>'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60:in `require'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `each'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `block in require'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `each'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `require'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler.rb:176:in `require'
        from /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-ent-1.8.1/bin/sidekiqswarm:42:in `<top (required)>'
        from /app/vendor/bundle/ruby/2.6.0/bin/sidekiqswarm:23:in `load'
        from /app/vendor/bundle/ruby/2.6.0/bin/sidekiqswarm:23:in `<top (required)>'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `load'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:23:in `run'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/cli.rb:483:in `exec'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/cli.rb:31:in `dispatch'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /app/vendor/bundle/ruby/2.6.0/gems/bundler-2.3.10/lib/bundler/cli.rb:25:in `start'
```

And how I've been using Sidekiq:
```
~ $ bundle exec sidekiq -C config/sidekiq.yml

I, [2022-05-03T22:59:49.858747 #91]  INFO -- : [Integrations::Shopify::Fetch] [shop.myshopify.com] 1 orders found
I, [2022-05-03T22:59:49.866750 #91]  INFO -- : [Integrations::Shopify::Fetch] [shop.myshopify.com] 1 orders found
I, [2022-05-03T22:59:49.870699 #91]  INFO -- : [Integrations::Shopify::Fetch] [shop.myshopify.com] 1 orders found
I, [2022-05-03T22:59:49.874792 #91]  INFO -- : [Integrations::Shopify::Fetch] [shop.myshopify.com] 1 orders found
```

**Comment by mperham** [comment]
This is covered n the preload sections here: https://github.com/mperham/sidekiq/wiki/Ent-Multi-Process#bundler-preload

**Comment by xenyal** [comment]
Thanks @mperham, I’ll give that a shot!
