### ISSUE TITLE
LoadError: cannot load such file -- sidekiq/util

### ISSUE THREAD

**Issue by kapso** [mperham/sidekiq#5372]
Ruby version: 3.1.2
Rails version: 7.0.3
Sidekiq / Pro / Enterprise version(s): Pro

This happened after Pro upgrade - `sidekiq-pro (5.5.0)`

Error
```
/Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require': cannot load such file -- sidekiq/util (LoadError)
```

sidekiq.rb
```rb
require 'sidekiq/pro/web'
require 'sidekiq-scheduler'
require 'sidekiq-scheduler/web'

Sidekiq.logger.level = Rails.env.development? ? Logger::INFO : Logger::WARN

Sidekiq.configure_client do |config|
  config.redis = { url: Settings.redis.url }
end

Sidekiq.configure_server do |config|
  config.redis = { url: Settings.redis.url }

  config.on(:startup) do
    Sidekiq.schedule = YAML.safe_load(ERB.new(File.read(Rails.root.join('config/schedule.yml'))).result)
    SidekiqScheduler::Scheduler.instance.reload_schedule!
  end
end

if Rails.env.staging? || Rails.env.production?
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Settings.sidekiq.admin.username && password == Settings.sidekiq.admin.password
  end
end

Sidekiq.strict_args!
```

**Comment by mperham** [comment]
I need the full backtrace. That .rb file does not exist in Sidekiq 6.5.

**Comment by kapso** [comment]
@mperham 

```
/Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require': cannot load such file -- sidekiq/util (LoadError)
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.0/lib/sidekiq-scheduler/scheduler.rb:2:in `<main>'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.0/lib/sidekiq/scheduler.rb:1:in `<main>'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.0/lib/sidekiq-scheduler.rb:4:in `require_relative'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.0/lib/sidekiq-scheduler.rb:4:in `<main>'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `each'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `block in require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `each'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler.rb:176:in `require'
	from /Users/kapil/projects/tradespace/config/application.rb:7:in `<main>'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:137:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/command/base.rb:87:in `perform'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/command.rb:48:in `invoke'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<main>'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by egeek** [comment]
It's coming from sidekiq-scheduler I believe, without bootsnap it's

```
17:38:38 payments_calculator_worker.1 | /home/steve/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- sidekiq/util (LoadError)
17:38:38 payments_calculator_worker.1 | 	from /home/steve/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
17:38:38 payments_calculator_worker.1 | 	from /home/steve/.rvm/gems/ruby-3.1.2/gems/sidekiq-scheduler-4.0.0/lib/sidekiq-scheduler/scheduler.rb:2:in `<top (required)>'
17:38:38 payments_calculator_worker.1 | 	from /home/steve/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
17:38:38 payments_calculator_worker.1 | 	from /home/steve/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
17:38:38 payments_calculator_worker.1 | 	from /home/steve/.rvm/gems/ruby-3.1.2/gems/sidekiq-scheduler-4.0.0/lib/sidekiq/scheduler.rb:1:in `<top (required)>'
17:38:38 payments_calculator_worker.1 | 	from /home/steve/.rvm/gems/ruby-3.1.2/gems/sidekiq-scheduler-4.0.0/lib/sidekiq-scheduler.rb:4:in `require_relative'
17:38:38 payments_calculator_worker.1 | 	from /home/steve/.rvm/gems/ruby-3.1.2/gems/sidekiq-scheduler-4.0.0/lib/sidekiq-scheduler.rb:4:in `<top (required)>'
17:38:38 payments_calculator_worker.1 | 	from /home/steve/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
17:38:38 payments_calculator_worker.1 | 	from /home/steve/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
17:38:38 payments_calculator_worker.1 | 	from /home/steve/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.13/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
17:38:38 payments_calculator_worker.1 | 	from /home/steve/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.13/lib/bundler/runtime.rb:55:in `each'
17:38:38 payments_calculator_worker.1 | 	from /home/steve/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.13/lib/bundler/runtime.rb:55:in `block in require'
17:38:38 payments_calculator_worker.1 | 	from /home/steve/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.13/lib/bundler/runtime.rb:44:in `each'
17:38:38 payments_calculator_worker.1 | 	from /home/steve/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.13/lib/bundler/runtime.rb:44:in `require'
17:38:38 payments_calculator_worker.1 | 	from /home/steve/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.13/lib/bundler.rb:176:in `require'
```

**Comment by oluosiname** [comment]
Having this same issue, as @mperham pointed out, the file no longer exists. Looks like sidekiq-scheduler and sidekiq-cron are requiring that file. See https://github.com/ondrejbartas/sidekiq-cron/blob/33ec31e33815c6c475a193f18a815529cb0ca238/lib/sidekiq/cron/poller.rb#L2

**Comment by marcelolx** [comment]
`sidekiq-scheduler` has been fixed, `v4.0.1` & `v3.2.2` support Sidekiq 6.5!

thanks for the report.

**Comment by kapso** [comment]
Thanks all, I will close the issue.

**Comment by sealabcore** [comment]
I was having this same issue as well and it seemed related to bootsnap based on the stacktrace. Once I did these steps the error went away.

1. Comment out sidekiq-ent / sidekiq-pro
2. Run bundle
3. Run rails test
4. Add back sidekiq-ent / sidekiq-pro
5. run bundle

After I did these steps the error on app boot went away. Must have been related to bootsnap caching something locally.

**Comment by sealabcore** [comment]
Ran into this as well and I had to do `bundle update sidekiq sidekiq-pro sidekiq-ent` as opposed to just `bundle update sidekiq`.

**Comment by joshua-v-jones** [comment]
Ran into this problem as well. Thanks @sealabcore that was the solution for me. Though just in-case there are other users of ```sidekiq-cron```, make sure to update that one as well.
