### ISSUE TITLE
LocalJumpError if no periodic jobs are defined

### ISSUE THREAD

**Issue by aliismayilov** [mperham/sidekiq#5374]
Ruby version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
Rails version: 7.0.3
Sidekiq / Pro / Enterprise version(s): 6.5.0 / 5.5.0 / 2.5.0

`LocalJumpError` error is raised if no period jobs are defined:
```
2022-06-08T09:40:41.109Z pid=56066 tid=136q INFO: Booting Sidekiq 6.5.0 with Sidekiq::RedisConnection::RedisAdapter options {}
2022-06-08T09:40:42.063Z pid=56066 tid=136q INFO: Booting Sidekiq 6.5.0 with Sidekiq::RedisConnection::RedisAdapter options {:url=>"redis://127.0.0.1:6379/0", :network_timeout=>10, :reconnect_attempts=>4, :reconnect_delay=>1.5, :reconnect_delay_max=>10.0}
2022-06-08T09:40:42.064Z pid=56066 tid=136q INFO: Booting Sidekiq 6.5.0 with Sidekiq::RedisConnection::RedisAdapter options {:url=>"redis://127.0.0.1:6379/0", :network_timeout=>10, :reconnect_attempts=>4, :reconnect_delay=>1.5, :reconnect_delay_max=>10.0}
2022-06-08T09:40:42.337Z pid=56066 tid=136q INFO: ** [Honeybadger] Initializing Honeybadger Error Tracker for Ruby. Ship it! version=4.12.1 framework=rails level=1 pid=56066
2022-06-08T09:40:42.339Z pid=56066 tid=136q WARN: ** [Honeybadger] Development mode is enabled. Data will not be reported until you deploy your app. level=2 pid=56066

                                   /\.                            /\
        L -      --- -- ---,,-.  ./.: 8.    .-----8p--.  .---.s,-'.:`--+
 ,8b  8i     ,F.oSSS"Sbo.o.s8 .\/.:'.oD \  /.:::.dS8b .\/ .: o8o ::::::|
 `4P,oP   ,o8;(88(`.:.4Y8 `"'::'.:."8DD:`\/ `:::.`888 :.db.::`P' `:'  `:
   o8P, .o8P   48bo.`:."`.dS`:'.oSSbDD8.`.oSSbo.`.888::oOOo oooo `.oSSbo o/
  d888Ld8P'  `:."88888o.``888 d88',`488 d8('.`88b:88( .8P'.:`888 d88P `88P
  88 8P8P     .`.:.`"Y88b 888 888 O 84P 888bod8P'.888o88 .:::888 88( O 888
 dP'`Y8P      db .:::.)8P 888 888 " 888b888'....: 888`.88b.::888 88b " 88(
T   ;88i      4P"888888P'o888o.Y8bod88P"`Y8bod8P d888b..488od888b V8bod888o
     88'                  48P::`odb.dSo,, ."P'.roy<sac>` ""'.`.o.`.."S"888.
     `8                    ".:'d888P'."S8b.`.::... ...' `.:::.d8b ::'  dP'
     .8                    `  '"888 ::.)88\odbo d8b`.odSso.::.888.::."488"
     .8                       `:888bod88P'.`888P"8Pd88'`488b::888::::.`8\
     P                        .:888 "P'..:::88(.:."88( O )88::48P::'/'/\ \
                             /\ 888`::./\`::888:::,888.".888::.o./\<:<  > >
 -   -  -- --- ------.  .---'  d888bo./  `-d888b.`:`Y8SbS8P'--48P'  \ \/ /
                      \/       `8P':/        "   \/   """      "     \/\/
                                P'\/                                    /<>\

2022-06-08T09:40:42.805Z pid=56066 tid=136q INFO: Booted Rails 7.0.3 application in development environment
2022-06-08T09:40:42.805Z pid=56066 tid=136q INFO: Running in ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
2022-06-08T09:40:42.805Z pid=56066 tid=136q INFO: Sidekiq Pro 5.5.0 / Sidekiq Enterprise 2.5.0, commercially licensed.
2022-06-08T09:40:42.808Z pid=56066 tid=136q INFO: Starting processing, hit Ctrl-C to stop
2022-06-08T09:40:42.809Z pid=56066 tid=2rsa INFO: SuperFetch activated
2022-06-08T09:40:42.811Z pid=56066 tid=2rv2 WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"leader"}
2022-06-08T09:40:42.812Z pid=56066 tid=2rv2 WARN: LocalJumpError: break from proc-closure
2022-06-08T09:40:42.812Z pid=56066 tid=2rv2 WARN: -/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-ent-2.5.0/lib/sidekiq-ent/periodic.rb:91:in `block (2 levels) in <main>'
-/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:56:in `block in fire_event'
-/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:55:in `each'
-/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:55:in `fire_event'
-/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-ent-2.5.0/lib/sidekiq-ent/senate.rb:85:in `stage_coup!'
-/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-ent-2.5.0/lib/sidekiq-ent/senate.rb:93:in `cycle'
-/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:8:in `watchdog'
-/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:17:in `block in safe_thread'
2022-06-08T09:40:42.940Z pid=56066 tid=2rv2 ERROR: ** [Honeybadger] Unable to send error report: API key is missing. id=0c3bb5b2-c8af-4a52-889f-504065b93f8d level=3 pid=56066
2022-06-08T09:40:42.940Z pid=56066 tid=2rv2 INFO: Gained leadership of the cluster
```

sidekiq continues to function properly even if no periodic jobs are defined. Adding the following lines in the sidekiq.rb file makes the error disappear:
```ruby
Sidekiq.configure_server do |config|
  config.periodic do |mgr|
    # noop
  end
end
```

**Comment by mockdeep** [comment]
This caused some pretty major breakage in production for us. Rolling back to a previous version allowed the jobs to run.

**Comment by mockdeep** [comment]
We've also discovered that it caused several thousand duplicate jobs.

**Comment by mperham** [comment]
Those jobs were likely orphans recovered by super_fetch. Mark them with an expiration if you don't want them recovered after some time. https://github.com/mperham/sidekiq/wiki/Pro-Expiring-Jobs

**Comment by mockdeep** [comment]
We're not using super fetch because it caused us a whole bunch of pain a couple of years ago with duplicate jobs.

**Comment by mperham** [comment]
Sidekiq Best Practice #2: your jobs may be executed more than once. This is the reality of a distributed system. We all do our best but errors will happen.

https://github.com/mperham/sidekiq/wiki/Best-Practices#2-make-your-job-idempotent-and-transactional

**Comment by mockdeep** [comment]
I'm well aware of that. It's easier said than done though, especially when you're trying to bulk import records and send out thousands of emails. Even harder when you're trying to retrofit an existing system that is under heavy use. It would be nice if the queueing system at least did a little work to try and keep duplicates from happening. We had over 1000 jobs with the same JID. We'd basically need to wrap Sidekiq in an entirely separate queuing layer in order to make it transactional and idempotent.

**Comment by mperham** [comment]
2.5.1 is out with the fix.
