### ISSUE TITLE
Error on sidekiq shutdown

### ISSUE THREAD

**Issue by aliismayilov** [mperham/sidekiq#5375]
Ruby version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-musl]
Rails version: 7.0.3
Sidekiq / Pro / Enterprise version(s): 6.5.0 / 5.5.0 / 2.5.0
Environment: alpine based docker container running on Heroku [base image](https://hub.docker.com/layers/ruby/library/ruby/3.1.2-alpine/images/sha256-19ccd9a3321253cbe968636f7b840a5e6e4cdad92bf9010e2978df82aac9435d?context=explore)

The following error keeps continuously happening when scaling down any of heroku worker dynos:
```
2022-06-08T10:46:26.774762+00:00 host heroku worker.6 - State changed from up to down   production/app-production
2022-06-08T10:46:27.233933+00:00 host heroku worker.6 - Stopping all processes with SIGTERM   production/app-production
2022-06-08T10:46:27.307602+00:00 host app worker.6 - pid=3 tid=5v7 INFO: Shutting down    production/app-production
2022-06-08T10:46:27.307613+00:00 host app worker.6 - pid=3 tid=5v7 INFO: Terminating quiet threads   production/app-production
2022-06-08T10:46:27.307764+00:00 host app worker.6 - pid=3 tid=37bnj INFO: Scheduler exiting...    production/app-production
2022-06-08T10:46:27.308729+00:00 host app worker.6 - pid=3 tid=530z WARN: {"context":"processor"}    production/app-production
2022-06-08T10:46:27.308959+00:00 host app worker.6 - pid=3 tid=53h3 WARN: {"context":"processor"}    production/app-production
2022-06-08T10:46:27.309164+00:00 host app worker.6 - pid=3 tid=547r WARN: {"context":"processor"}    production/app-production
2022-06-08T10:46:27.311698+00:00 host app worker.6 - pid=3 tid=534v WARN: {"context":"processor"}    production/app-production
2022-06-08T10:46:27.313402+00:00 host app worker.6 - pid=3 tid=53jb WARN: {"context":"processor"}    production/app-production
2022-06-08T10:46:27.314019+00:00 host app worker.6 - pid=3 tid=547r WARN: NoMethodError: undefined method `call' for nil:NilClass    production/app-production
2022-06-08T10:46:27.314019+00:00 host app worker.6 -    production/app-production
2022-06-08T10:46:27.31402+00:00 host app worker.6 -       @callback.call(self, ex)    production/app-production
2022-06-08T10:46:27.31402+00:00 host app worker.6 -                ^^^^^    production/app-production
2022-06-08T10:46:27.315078+00:00 host app worker.6 - pid=3 tid=547r WARN: /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:73:in `rescue in run'   production/app-production
2022-06-08T10:46:27.315079+00:00 host app worker.6 - /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:67:in `run'    production/app-production
2022-06-08T10:46:27.315079+00:00 host app worker.6 - /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:8:in `watchdog'    production/app-production
2022-06-08T10:46:27.31508+00:00 host app worker.6 - /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:17:in `block in safe_thread'    production/app-production
2022-06-08T10:46:27.31645+00:00 host app worker.6 - pid=3 tid=53jb WARN: NoMethodError: undefined method `call' for nil:NilClass   production/app-production
2022-06-08T10:46:27.31645+00:00 host app worker.6 -   production/app-production
2022-06-08T10:46:27.316451+00:00 host app worker.6 -       @callback.call(self, ex)   production/app-production
2022-06-08T10:46:27.316451+00:00 host app worker.6 -                ^^^^^   production/app-production
2022-06-08T10:46:27.316626+00:00 host app worker.6 - pid=3 tid=53jb WARN: /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:73:in `rescue in run'   production/app-production
2022-06-08T10:46:27.316627+00:00 host app worker.6 - /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:67:in `run'    production/app-production
2022-06-08T10:46:27.316627+00:00 host app worker.6 - /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:8:in `watchdog'    production/app-production
2022-06-08T10:46:27.316627+00:00 host app worker.6 - /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:17:in `block in safe_thread'   production/app-production
2022-06-08T10:46:27.31726+00:00 host app worker.6 - pid=3 tid=534b WARN: {"context":"processor"}   production/app-production
2022-06-08T10:46:27.318405+00:00 host app worker.6 - pid=3 tid=53vj WARN: {"context":"processor"}    production/app-production
2022-06-08T10:46:27.319641+00:00 host app worker.6 - pid=3 tid=534b WARN: NoMethodError: undefined method `call' for nil:NilClass    production/app-production
2022-06-08T10:46:27.319642+00:00 host app worker.6 -    production/app-production
2022-06-08T10:46:27.319642+00:00 host app worker.6 -       @callback.call(self, ex)   production/app-production
2022-06-08T10:46:27.319642+00:00 host app worker.6 -                ^^^^^   production/app-production
2022-06-08T10:46:27.319848+00:00 host app worker.6 - pid=3 tid=534b WARN: /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:73:in `rescue in run'   production/app-production
2022-06-08T10:46:27.319848+00:00 host app worker.6 - /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:67:in `run'    production/app-production
2022-06-08T10:46:27.319848+00:00 host app worker.6 - /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:8:in `watchdog'    production/app-production
2022-06-08T10:46:27.319849+00:00 host app worker.6 - /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:17:in `block in safe_thread'   production/app-production
2022-06-08T10:46:27.32179+00:00 host app worker.6 - pid=3 tid=5413 WARN: {"context":"processor"}   production/app-production
2022-06-08T10:46:27.321831+00:00 host app worker.6 - pid=3 tid=53lj WARN: {"context":"processor"}    production/app-production
2022-06-08T10:46:27.322023+00:00 host app worker.6 - pid=3 tid=534v WARN: NoMethodError: undefined method `call' for nil:NilClass    production/app-production
2022-06-08T10:46:27.322023+00:00 host app worker.6 -    production/app-production
2022-06-08T10:46:27.322023+00:00 host app worker.6 -       @callback.call(self, ex)   production/app-production
2022-06-08T10:46:27.322024+00:00 host app worker.6 -                ^^^^^   production/app-production
2022-06-08T10:46:27.324985+00:00 host app worker.6 - pid=3 tid=534v WARN: /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:73:in `rescue in run'   production/app-production
2022-06-08T10:46:27.324986+00:00 host app worker.6 - /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:67:in `run'    production/app-production
2022-06-08T10:46:27.324987+00:00 host app worker.6 - /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:8:in `watchdog'    production/app-production
2022-06-08T10:46:27.324987+00:00 host app worker.6 - /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:17:in `block in safe_thread'   production/app-production
2022-06-08T10:46:27.325547+00:00 host app worker.6 - #<Thread:0x00007f1d524ad708@processor /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:15 run> terminated with exception (report_on_exception is true):   production/app-production
2022-06-08T10:46:27.325746+00:00 host app worker.6 - pid=3 tid=53af WARN: {"context":"processor"}    production/app-production
2022-06-08T10:46:27.329791+00:00 host app worker.6 - #<Thread:0x00007f1d524a8938@processor /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/component.rb:15 run> terminated with exception (report_on_exception is true):   production/app-production
2022-06-08T10:46:27.329861+00:00 host app worker.6 - pid=3 tid=536j WARN: {"context":"processor"}    production/app-production
2022-06-08T10:46:27.330174+00:00 host app worker.6 - /vendor/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/processor.rb:73:in `rescue in run': undefined method `call' for nil:NilClass (NoMethodError)    production/app-production
2022-06-08T10:46:27.330174+00:00 host app worker.6 -    production/app-production
```

**Comment by mperham** [comment]
This will happen if someone is calling `Sidekiq::Processor.new` without a block. Sidekiq only does this in two places and both pass a block. There must be some monkeypatches or plugins which are breaking due to the 6.5 refactoring.

**Comment by PikachuEXE** [comment]
One possible monkey patch found
https://github.com/scoutapp/scout_apm_ruby/blob/v5.1.1/lib/scout_apm/background_job_integrations/sidekiq.rb#L39-L53

**Comment by mperham** [comment]
🎯 I have no idea why they aren’t just using an on(:startup) hook.

**Comment by aliismayilov** [comment]
> You've got some sort of Sidekiq monkeypatch or plugin which is breaking. I can't tell what, please post your initializer.

thanks @PikachuEXE for the find! We also use `scout_apm` gem.

**Comment by PikachuEXE** [comment]
@mperham When was `on(:startup)` first introduced? (in terms of version)
From https://github.com/scoutapp/scout_apm_ruby/pull/450#issuecomment-1153077569
> We maintain backwards compatibility with older versions of sidekiq and I do not know when the `on(:startup)` hook was introduced but we need to confirm that this change will be handled gracefully for older versions.

**Comment by amilligan** [comment]
@PikachuEXE I know I'm a little late to this, but this was some solid sleuthing.  You saved me a bunch of time, so thank you.

**Comment by onedanshow** [comment]
Agreed! Thank you @PikachuEXE
