### ISSUE TITLE
`Sidekiq::Client.push_bulk` with `at` broken in 6.5.0

### ISSUE THREAD

**Issue by christos** [mperham/sidekiq#5381]
Ruby version: `3.1.2`
Rails version: - 
Sidekiq / Pro / Enterprise version(s): `Sidekiq 6.5.0`

Since upgrading to version `6.5.0` the following code fails:

```ruby
#!/usr/bin/env ruby

require "sidekiq"

class MyJob
  include Sidekiq::Worker
end

Sidekiq::Client.push_bulk(
  "class" => MyJob,
  "args" => [[1], [2], [3]],
  "at" => [Time.now.to_i, Time.now.to_i, Time.now.to_i]
)
```

with 

```
/Users/christos/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.6.0/lib/redis/commands/sorted_sets.rb:69:in `zadd': wrong number of arguments (ArgumentError)
from /Users/christos/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/client.rb:223:in `atomic_push'
```

The `at` argument for `push_bulk` is not documented clearly but it is indeed supported, right? 

https://github.com/mperham/sidekiq/blob/f38cf3050cf62e34a38ef47cd5d812108e7308cf/lib/sidekiq/client.rb#L102-L104

I believe the root cause to be the addition of the splat here: 

https://github.com/mperham/sidekiq/commit/aaac999c6de54bfa21f09cf29c5473dadf9355fd#diff-ee2515b430eefbe153698ed9aaa4d6850e7404c2648ddef85586fcfd096062e1R223

Weirdly enough, with only two items `args`/`at` arrays  the error doesn't happen. It needs to have 3 or more to manifest itself.

**Comment by byroot** [comment]
> I believe the root cause to be the addition of the splat here

Yes you are right. In `redis-rb` the argument handling is a bit finicky:

https://github.com/redis/redis-rb/blob/4e76b035a98ce2c7bd7666a1553fc4394279ca83/lib/redis/commands/sorted_sets.rb#L62-L69

I think we can just drop the splat. 

cc @casperisfine (assigning myself as first think to look at when I get back to work on Monday).
