### ISSUE TITLE
ThreadError: can't alloc thread in `block in safe_thread'

### ISSUE THREAD

**Issue by ts-3156** [mperham/sidekiq#5414]
Hi,

Should applications that use Sidekiq fundamentally stop creating threads in the worker?

I have already read https://github.com/mperham/sidekiq/issues/4029 . I don't think Sidekiq is wrong. Calling `Parallel.each_with_index` in a Sidekiq worker will cause this exception with very low probability.

I don't expect you to debug my application, I would like to know if Sidekiq's design philosophy allows to creating threads in workers.

Ruby version:
2.7.2p137

Rails version:
6.1.4.1

Sidekiq / Pro / Enterprise version(s):
6.4.2

Backtrace:
```
2022-07-04T03:45:39.535Z pid=19403 tid=t2j class=MyWorker jid=4b04af4ba5dd033d749c0cbd WARN: #<ThreadError: can't alloc thread>
2022-07-04T03:45:39.547Z pid=19403 tid=t2j class=MyWorker jid=4b04af4ba5dd033d749c0cbd INFO: /var/my_app/.bundle/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:211:in `new'
/var/my_app/.bundle/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:211:in `block (3 levels) in in_threads'
/var/my_app/.bundle/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:210:in `times'
/var/my_app/.bundle/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:210:in `block (2 levels) in in_threads'
/var/my_app/.bundle/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:209:in `handle_interrupt'
/var/my_app/.bundle/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:209:in `block in in_threads'
/var/my_app/.bundle/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:207:in `handle_interrupt'
/var/my_app/.bundle/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:207:in `in_threads'
/var/my_app/.bundle/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:354:in `work_in_threads'
/var/my_app/.bundle/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:276:in `map'
/var/my_app/.bundle/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:228:in `each'
/var/my_app/.bundle/ruby/2.7.0/gems/parallel-1.19.2/lib/parallel.rb:242:in `each_with_index'
[my application code]
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:196:in `execute_job'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/var/my_app/.bundle/ruby/2.7.0/gems/ddtrace-0.54.0/lib/ddtrace/contrib/sidekiq/server_tracer.rb:43:in `block in call'
/var/my_app/.bundle/ruby/2.7.0/gems/ddtrace-0.54.0/lib/ddtrace/tracer.rb:283:in `trace'
/var/my_app/.bundle/ruby/2.7.0/gems/ddtrace-0.54.0/lib/ddtrace/contrib/sidekiq/server_tracer.rb:24:in `call'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/middleware/chain.rb:143:in `invoke'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:163:in `block in process'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/job_retry.rb:114:in `local'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/rails.rb:14:in `block in call'
/var/my_app/.bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/var/my_app/.bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/reloader.rb:72:in `block in wrap'
/var/my_app/.bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/var/my_app/.bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/reloader.rb:71:in `wrap'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/rails.rb:13:in `call'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:257:in `stats'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/job_logger.rb:13:in `call'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/job_retry.rb:81:in `global'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:124:in `block in dispatch'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/job_logger.rb:39:in `prepare'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:123:in `dispatch'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:162:in `process'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:78:in `process_one'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:68:in `run'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/util.rb:56:in `watchdog'
/var/my_app/.bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/util.rb:65:in `block in safe_thread'
```

**Comment by mperham** [comment]
If you want jobs to spawn threads, you should probably be using a shared
thread pool. I believe the parallel gem supports a shared thread pool.

**Comment by mperham** [comment]
It's ok for workers to spawn threads but know that threads are inherently tricky and really limited by MRI's GIL. You'll need to set up and manage any thread local state and resources, e.g. database connections. This is non-trivial for something like Rails. And if you spawn too many, you'll get errors like above.
