### ISSUE TITLE
Batch death callback causes error

### ISSUE THREAD

**Issue by FraDim** [mperham/sidekiq#5417]
Some batches raise the following error:

```
TypeError: no implicit conversion of nil into String
```

When I use `Sidekiq::Batch::Status.new(batch_id)` to look at the data for the batch that raised an error, I get:

```
 #<Sidekiq::Batch::Status:0x00007f170ffa4c18
 @bid="4Vi0VhvXwXfO9w",
 @completed=0,
 @failures=1,
 @pending=0,
 @props=
  {"pending"=>"0",
   "kids"=>"0",
   "cbdeath"=>"1"},
 @total=0>
```

I noticed that all the batches that raise the error, were created more than a month ago.

In a recent batch I get the following

```
#<Sidekiq::Batch::Status:0x00007f687f1d4810                                                                            
 @bid="hbV4CaLV7VDlkg",                                                                                                
 @completed=0,                                                                                                         
 @failures=0,                                                                                                          
 @pending=1,                                                                                                           
 @props=                                                                                                               
  {"total"=>"4",                                                                                                       
   "kids"=>"0",                                                                                                        
   "created_at"=>"1657039253.5277588",                                                                                 
   "pending"=>"1",                                                                                                     
   "description"=>"Processing something",
   "callbacks"=>"{\"success\":[{\"SidekiqBatchCallbackHandler\":{\"worker_class\":\"NotificationWorker\"}}}]}"},
 @total=4>  
```

The `props` look significantly more scarce in the older batch.

I have managed to reproduce the error locally, making the batched jobs fail and changing (with monkey patching) the expiry of the batch to a value less than the retry period of those jobs.

-----
Ruby version: 3.1
Rails version: 7.0.3
Sidekiq / Pro / Enterprise version(s): 6.5.1 / 5.5.1 / 2.5.1

Error:
```
TypeError: no implicit conversion of nil into String
```

Backtrace:
```
/gems/json-2.6.2/lib/json/common.rb:216:in `initialize'
/gems/json-2.6.2/lib/json/common.rb:216:in `new'
/gems/json-2.6.2/lib/json/common.rb:216:in `parse'
/gems/sidekiq-6.5.1/lib/sidekiq.rb:247:in `load_json'
/gems/sidekiq-pro-5.5.1/lib/sidekiq/batch/status.rb:74:in `callbacks'
/gems/sidekiq-pro-5.5.1/lib/sidekiq/batch/callback.rb:45:in `death'
/gems/sidekiq-pro-5.5.1/lib/sidekiq/batch/callback.rb:15:in `perform'
/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:196:in `execute_job'
/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/gems/sidekiq-6.5.1/lib/sidekiq/middleware/chain.rb:144:in `block in invoke'
/gems/sentry-sidekiq-5.3.1/lib/sentry/sidekiq/sentry_context_middleware.rb:24:in `call'
/gems/sidekiq-6.5.1/lib/sidekiq/middleware/chain.rb:146:in `block in invoke'
/gems/sidekiq-pro-5.5.1/lib/sidekiq/batch/middleware.rb:58:in `call'
/gems/sidekiq-6.5.1/lib/sidekiq/middleware/chain.rb:146:in `block in invoke'
/gems/sidekiq-ent-2.5.1/lib/sidekiq-ent/unique.rb:154:in `call'
/gems/sidekiq-6.5.1/lib/sidekiq/middleware/chain.rb:146:in `block in invoke'
/gems/sidekiq-ent-2.5.1/lib/sidekiq-ent/limiter/middleware.rb:39:in `call'
/gems/sidekiq-6.5.1/lib/sidekiq/middleware/chain.rb:146:in `block in invoke'
/gems/sidekiq-6.5.1/lib/sidekiq/middleware/chain.rb:149:in `invoke'
/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:163:in `block in process'
/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/gems/sidekiq-6.5.1/lib/sidekiq/job_retry.rb:115:in `local'
/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/gems/sidekiq-6.5.1/lib/sidekiq/rails.rb:14:in `block in call'
/gems/activesupport-7.0.3/lib/active_support/execution_wrapper.rb:92:in `wrap'
/gems/activesupport-7.0.3/lib/active_support/reloader.rb:72:in `block in wrap'
/gems/activesupport-7.0.3/lib/active_support/execution_wrapper.rb:92:in `wrap'
/gems/activesupport-7.0.3/lib/active_support/reloader.rb:71:in `wrap'
/gems/sidekiq-6.5.1/lib/sidekiq/rails.rb:13:in `call'
/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:257:in `stats'
/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/gems/sidekiq-6.5.1/lib/sidekiq/job_logger.rb:13:in `call'
/gems/semantic_logger-4.11.0/lib/semantic_logger/base.rb:190:in `block in tagged'
/gems/semantic_logger-4.11.0/lib/semantic_logger/semantic_logger.rb:395:in `named_tagged'
/gems/semantic_logger-4.11.0/lib/semantic_logger/base.rb:197:in `tagged'
/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/gems/sidekiq-6.5.1/lib/sidekiq/job_retry.rb:82:in `global'
/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
/gems/sidekiq-6.5.1/lib/sidekiq/job_logger.rb:39:in `prepare'
/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:123:in `dispatch'
/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:162:in `process'
/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:78:in `process_one'
/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:68:in `run'
/gems/sidekiq-6.5.1/lib/sidekiq/component.rb:8:in `watchdog'
/gems/sidekiq-6.5.1/lib/sidekiq/component.rb:17:in `block in safe_thread'
```

**Comment by mperham** [comment]
The batch has expired. There’s nothing you can do, the batch data is gone.

**Comment by mperham** [comment]
Taking too long to process is considered an app issue. Silently ignoring
the error would not be a good idea IMO. Your app needs to ensure the batch
jobs are processed within 30 days.

**Comment by jakeonfire** [comment]
we also ran into this issue when our redis was temporarily out of memory
