### ISSUE TITLE
Sidekiq v6.5.3 is unexpectedly dependent on concurrent-ruby

### ISSUE THREAD

**Issue by fallwith** [mperham/sidekiq#5457]
#5456 and https://github.com/mperham/sidekiq/commit/44c2e7a8a348a57e70ce777e53076b42772da06e (released with v6.5.3) addressed one of the ways in which Sidekiq is unexpectedly requiring `concurrent-ruby`, but there appears to be at least one more way that needs a similar fix.

From our stack trace, it looks like `api.rb` pulls in `metrics/query.rb`, which in turns brings in `metrics/shared.rb` where the `require "concurrent"` line lives.

```shell
gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/metrics/shared.rb:1:in `require': cannot load such file -- concurrent (LoadError)	
  from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/metrics/shared.rb:1:in `<top (required)>'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/metrics/query.rb:5:in `require'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/metrics/query.rb:5:in `<top (required)>'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/api.rb:9:in `require'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/api.rb:9:in `<top (required)>'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/scheduled.rb:4:in `require'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/scheduled.rb:4:in `<top (required)>'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/job_retry.rb:3:in `require'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/job_retry.rb:3:in `<top (required)>'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/processor.rb:5:in `require'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/processor.rb:5:in `<top (required)>'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/manager.rb:3:in `require'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/manager.rb:3:in `<top (required)>'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/launcher.rb:3:in `require'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/launcher.rb:3:in `<top (required)>'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/cli.rb:13:in `require'
	from gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/cli.rb:13:in `<top (required)>'
  from our_code.rb:7:in `require'
```

**Comment by mperham** [comment]
Can you run `main` and see if it works for you now?

**Comment by fallwith** [comment]
> Can you run `main` and see if it works for you now?

@mperham thank you very much! `main@345ba00` works great for us.

**Comment by mperham** [comment]
Good, that also fixes a few code dependency issues so it was a very good commit. 😁
