### ISSUE TITLE
uninitialized constant Sidekiq::Component in job_retry in 3.5.4

### ISSUE THREAD

**Issue by noctivityinc** [mperham/sidekiq#5471]
Ruby version: 3.1.2p20
Rails version: 7.0.3.1
Sidekiq / Pro / Enterprise version(s): 6.5.4

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

Sidekiq.yml
```
development:
  :concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 10
```

Sidekiq.rb
```
if ENV['REDIS_URL'].present?
  Sidekiq.configure_client do |config|
    config.redis = { url: ENV.fetch('REDIS_URL'), size: 1, network_timeout: 5, ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }  }
  end

  Sidekiq.configure_server do |config|
    config.redis = { url: ENV.fetch('REDIS_URL'), size: 12, network_timeout: 5, ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }  }
  end

  # Sidekiq::Extensions.enable_delay!
end
```

Backtrace:

```
/Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/sidekiq-6.5.4/lib/sidekiq/job_retry.rb:66:in `<class:JobRetry>': uninitialized constant Sidekiq::Component (NameError)

    include Sidekiq::Component
                   ^^^^^^^^^^^
Did you mean?  Complex
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/sidekiq-6.5.4/lib/sidekiq/job_retry.rb:61:in `<module:Sidekiq>'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/sidekiq-6.5.4/lib/sidekiq/job_retry.rb:6:in `<main>'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/airbrake-13.0.2/lib/airbrake/sidekiq/retryable_jobs_filter.rb:14:in `<class:RetryableJobsFilter>'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/airbrake-13.0.2/lib/airbrake/sidekiq/retryable_jobs_filter.rb:8:in `<module:Sidekiq>'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/airbrake-13.0.2/lib/airbrake/sidekiq/retryable_jobs_filter.rb:4:in `<module:Airbrake>'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/airbrake-13.0.2/lib/airbrake/sidekiq/retryable_jobs_filter.rb:3:in `<main>'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/airbrake-13.0.2/lib/airbrake/sidekiq.rb:3:in `<main>'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/airbrake-13.0.2/lib/airbrake.rb:21:in `<main>'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/jlippiner/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/jlippiner/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/runtime.rb:55:in `each'
	from /Users/jlippiner/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/runtime.rb:55:in `block in require'
	from /Users/jlippiner/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/runtime.rb:44:in `each'
	from /Users/jlippiner/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/runtime.rb:44:in `require'
	from /Users/jlippiner/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler.rb:176:in `require'
	from /Users/jlippiner/Projects/dmv/dmvsg/config/application.rb:8:in `<main>'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/railties-7.0.3.1/lib/rails/commands/server/server_command.rb:137:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/railties-7.0.3.1/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/railties-7.0.3.1/lib/rails/command/base.rb:87:in `perform'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/railties-7.0.3.1/lib/rails/command.rb:48:in `invoke'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/railties-7.0.3.1/lib/rails/commands.rb:18:in `<main>'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/jlippiner/.rvm/gems/ruby-3.1.2@dmvsg/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
```

**Comment by mperham** [comment]
Looks like airbrake is requiring it. Stick with 6.5.1 until 6.5.5 is out.

**Comment by noctivityinc** [comment]
@mperham ok.  Thanks.

**Comment by benoittgt** [comment]
Same issue with Sidekiq status it seems

```
rails aborted!
NameError: uninitialized constant Sidekiq::Component

    include Sidekiq::Component
                   ^^^^^^^^^^^
Did you mean?  Complex
/home/circleci/project/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/job_retry.rb:66:in `<class:JobRetry>'
/home/circleci/project/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/job_retry.rb:61:in `<module:Sidekiq>'
/home/circleci/project/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/job_retry.rb:6:in `<main>'
/home/circleci/project/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/project/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/project/vendor/bundle/ruby/3.1.0/gems/sidekiq-status-2.1.3/lib/sidekiq-status/server_middleware.rb:2:in `<main>'
/home/circleci/project/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/project/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/project/vendor/bundle/ruby/3.1.0/gems/sidekiq-status-2.1.3/lib/sidekiq-status.rb:6:in `<main>'
/home/circleci/project/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/project/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
```

**Comment by davidwessman** [comment]
6.5.5 is out!

**Comment by Skulli** [comment]
6.5.5 fixed it for me
