### ISSUE TITLE
Sidekiq.config raise error

### ISSUE THREAD

**Issue by brlo** [mperham/sidekiq#5491]
Ruby version: 3.1.2p20
Rails version: 6.1.6

error:
```ruby
app error: "undefined method `config' for Sidekiq:Module\n\n      Sidekiq.logger.warn \"Unable to load YAML: \#{ex.message}\" unless Sidekiq.config[:environment] == \"development\"\n                                                                             ^^^^^^^\nDid you mean?  concerning" (NoMethodError)
 /gems/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/api.rb:489:in `rescue in safe_load'
/gems/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/api.rb:483:in `safe_load'
/gems/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/api.rb:403:in `display_args'
```

Hello. Shouldn't there be just `Sidekiq[:environment]` instead of `Sidekiq.config[:environment]`?

**Comment by mperham** [comment]
`Sidekiq.config` has never worked. I'm not sure what you are talking about.


```
> Sidekiq::VERSION
=> "6.4.1"
irb(main):002:0> Sidekiq.config
(irb):2:in `<main>': undefined method `config' for Sidekiq:Module (NoMethodError)
```

**Comment by brlo** [comment]
it's in Sidekiq code, here: https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/api.rb#L489

**Comment by mperham** [comment]
Ah, thank you. I did not understand your initial description.
