### ISSUE TITLE
NoMethodError: undefined method `drivers'

### ISSUE THREAD

**Issue by mhenrixon** [mperham/sidekiq#5498]
Ruby version: 3.1.2
Rails version: 7.0.3.1
Sidekiq / Pro / Enterprise version(s): 6.5.5
RedisRB version: 5.0.0

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

```
worker | 2022-08-29T07:38:33.325Z pid=5512 tid=f8 WARN: NoMethodError: undefined method `drivers' for Redis::Commands::Connection:Module
worker |
worker |         opts[:driver] ||= Redis::Connection.drivers.last || "ruby"
worker |                                            ^^^^^^^^
worker | 2022-08-29T07:38:33.325Z pid=5512 tid=f8 WARN: /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/redis_connection.rb:49:in `client_opts'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/redis_connection.rb:21:in `new_client'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/redis_connection.rb:109:in `block in create'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:169:in `try_create'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:73:in `block (2 levels) in pop'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:69:in `loop'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:69:in `block in pop'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:68:in `synchronize'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:68:in `pop'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:78:in `checkout'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:60:in `block in with'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq.rb:161:in `redis'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq.rb:182:in `redis_info'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/cli.rb:75:in `run'
worker | /Users/mhenrixon/Code/mhenrixon/consulting/vendor/ruby/3.1.0/gems/sidekiq-6.5.5/bin/sidekiq:31:in `<top (required)>'
```

**Comment by nateberkopec** [comment]
See also #5489

**Comment by nateberkopec** [comment]
In the meantime, users should probably lock Sidekiq 6.x installations to Redis < 5.

`gem 'redis', '< 5.0'`

**Comment by nateberkopec** [comment]
This is [already fixed](https://github.com/mperham/sidekiq/blob/b666a6d67f341bb6253d3f181efd5bd7454c628a/sidekiq.gemspec#L25) on master, so the above will a workaround until Mike can release something today.

**Comment by nateberkopec** [comment]
Or, upgrade to Redis 5.0.1 which should also fix the issue. Thanks for the fast fix @casperisfine.

**Comment by mhenrixon** [comment]
Lovely! Cheers @nateberkopec and @casperisfine
