### ISSUE TITLE
`super_fetch` passing timeout as third argument (deprecated)

### ISSUE THREAD

**Issue by martinvium** [mperham/sidekiq#5518]
WARNING this requires `redis-namespace` fixes as well:
https://github.com/resque/redis-namespace/pull/210

Ruby version: 3.0.4
Rails version:  7.0.3.1
Sidekiq / Pro / Enterprise version(s):
```
    sidekiq-pro (5.5.2)
    sidekiq-ent (2.5.2)
    redis (5.0.3)
    redis-client (0.8.0)
    redis-namespace (1.9.0)
```

```
result = conn.brpoplpush(queue, working_queue, timeout: config[:fetch_timeout] || 1)
```

Suggestion:

```
result = conn.brpoplpush(queue, working_queue, timeout: config[:fetch_timeout] || 1)
```

Backtrace:
```
2022-09-09T11:43:55.466Z pid=25196 tid=1y78 WARN: /Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/redis-5.0.3/lib/redis/commands/lists.rb:181:in `brpoplpush'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/redis-namespace-1.9.0/lib/redis/namespace.rb:479:in `call_with_namespace'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/redis-namespace-1.9.0/lib/redis/namespace.rb:354:in `block (2 levels) in <class:Namespace>'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-pro-5.5.2/lib/sidekiq/pro/super_fetch.rb:355:in `block in strict'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.5/lib/sidekiq.rb:164:in `block in redis'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.5/lib/sidekiq.rb:161:in `redis'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.5/lib/sidekiq/component.rb:26:in `redis'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-pro-5.5.2/lib/sidekiq/pro/super_fetch.rb:341:in `strict'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-pro-5.5.2/lib/sidekiq/pro/super_fetch.rb:317:in `call'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-pro-5.5.2/lib/sidekiq/pro/super_fetch.rb:317:in `get_job'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-pro-5.5.2/lib/sidekiq/pro/super_fetch.rb:305:in `block in retrieve_work'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-pro-5.5.2/lib/sidekiq/pro/super_fetch.rb:304:in `retrieve_work'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.5/lib/sidekiq/processor.rb:83:in `get_one'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.5/lib/sidekiq/processor.rb:95:in `fetch'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.5/lib/sidekiq/processor.rb:77:in `process_one'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.5/lib/sidekiq/processor.rb:68:in `run'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.5/lib/sidekiq/component.rb:8:in `watchdog'
/Users/u0157541/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.5/lib/sidekiq/component.rb:17:in `block in safe_thread'
```

**Comment by davidwessman** [comment]
https://github.com/mperham/sidekiq/blob/main/sidekiq.gemspec#L25
Sidekiq recommends redis < 5.0, that must apply for Pro and Enterprise as well right?

And in Sidekiq 7 it will use the new redis client instead.

**Comment by mperham** [comment]
6.5.6 is already out with fixes.
