### ISSUE TITLE
Redis::CommandError during startup: ERR Error running script ... attempt to concatenate field 'jid' (a nil value)

### ISSUE THREAD

**Issue by jakeonfire** [mperham/sidekiq#5520]
Ruby version: 2.6.10
Rails version: 5.2.8
Sidekiq / Pro / Enterprise version(s): sidekiq 6.4.2, sidekiq-pro 5.3.1

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
`initializers/sidekiq.rb`:
```ruby
require "sidekiq/job_logger"

Sidekiq.strict_args! unless Rails.env.production?

redis_conn = -> {
  # Sidekiq uses all of the slots in the ConnectionPool and then deadlocks if the client is memoized
  # requires redis-namespace and the 'resque' prefix since our historical data was kept inside the same
  # Redis instance used by Resque
  tag = prefix = "resque"
  Ifttt::RedisClients.get(tag, memoize: false, namespace: prefix, skip_connection_pool: true)
}

Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(&redis_conn)
  config.client_middleware do |chain|
    chain.add SidekiqMiddlewares::Client::Instrumenter
  end
end

class JobLogger < Sidekiq::JobLogger
  def call(item, _queue)
    Sidekiq.logger.debug item.awesome_inspect
    yield
  end
end

Sidekiq.configure_server do |config|
  config.super_fetch! # ensure jobs aren't lost when things go horribly wrong. see: https://github.com/mperham/sidekiq/wiki/Pro-Reliability-Server#super_fetch

  config.logger.level = Rails.application.config.logger.level
  config.log_formatter = Sidekiq::Logger::Formatters::JSON.new if Rails.env.production?

  # Replaces uninformative Sidekiq::JobLogger:
  config.options[:job_logger] = JobLogger

  size = SIDEKIQ_CONCURRENCY + SIDEKIQ_CONNECTION_POOL_EXTRA
  config.redis = ConnectionPool.new(size: size, &redis_conn)

  if config.options[:queues].include?("critical")
    config.average_scheduled_poll_interval = 2 # default is 5
  end

  config.server_middleware do |chain|
    chain.add SidekiqMiddlewares::Server::Instrumenter
  end

  config.on(:startup) do
    Ifttt::Util::SigquitFlag.install_signal_handler
    ActiveRecord::Base.clear_active_connections!
    Ifttt::RedisClients.reset!
  end
end
```
`sidekiq.yml`:
```yaml
---
:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 1).to_i %>
:queues:
<%
  queue_str = ENV.fetch('QUEUES', '')
  begin
    # e.g. '["default", ["prioritized", 2], ["critical", 10]]'
    queues = JSON.parse(queue_str)
  rescue JSON::ParserError
    # csv
    queues = queue_str.split(',')
  end
  queues.each do |queue, priority = nil|
    if priority
      line = "- [#{queue},#{priority}]"
    else
      line = "- #{queue}"
    end
%>
  <%= line %>
<% end %>
```
Error:
```
Redis::CommandError: ERR Error running script (call to f_d7bb225e1c5751eeaaa4bfb8fe9383a6d2e898ba): @user_script:10: user_script:10: attempt to concatenate field 'jid' (a nil value) 
  from redis/client.rb:149:in `call'
  from new_relic/agent/instrumentation/redis/prepend.rb:12:in `block in call'
  from new_relic/agent/instrumentation/redis/instrumentation.rb:19:in `block in call_with_tracing'
  from new_relic/agent/instrumentation/redis/instrumentation.rb:45:in `block in with_tracing'
  from new_relic/agent/tracer.rb:371:in `capture_segment_error'
  from new_relic/agent/instrumentation/redis/instrumentation.rb:45:in `with_tracing'
  from new_relic/agent/instrumentation/redis/instrumentation.rb:19:in `call_with_tracing'
  from new_relic/agent/instrumentation/redis/prepend.rb:12:in `call'
  from redis.rb:2635:in `block in _eval'
  from redis.rb:70:in `block in synchronize'
  from monitor.rb:235:in `mon_synchronize'
  from redis.rb:70:in `synchronize'
  from redis.rb:2634:in `_eval'
  from redis.rb:2686:in `evalsha'
  from redis/namespace.rb:476:in `call_with_namespace'
  from redis/namespace.rb:352:in `block (2 levels) in <class:Namespace>'
  from sidekiq/pro/scripting.rb:128:in `call'
  from sidekiq/pro/super_fetch.rb:175:in `recover_orphan'
  from sidekiq/pro/super_fetch.rb:235:in `block (4 levels) in cleanup_the_dead'
  from sidekiq/pro/super_fetch.rb:234:in `loop'
  from sidekiq/pro/super_fetch.rb:234:in `block (3 levels) in cleanup_the_dead'
  from sidekiq/pro/super_fetch.rb:231:in `each'
  from sidekiq/pro/super_fetch.rb:231:in `block (2 levels) in cleanup_the_dead'
  from redis.rb:2867:in `each'
  from redis.rb:2867:in `block in sscan_each'
  from redis.rb:2865:in `loop'
  from redis.rb:2865:in `sscan_each'
  from redis/namespace.rb:476:in `call_with_namespace'
  from redis/namespace.rb:352:in `block (2 levels) in <class:Namespace>'
  from sidekiq/pro/super_fetch.rb:224:in `block in cleanup_the_dead'
  from sidekiq.rb:95:in `block in redis'
  from connection_pool.rb:63:in `block (2 levels) in with'
  from connection_pool.rb:62:in `handle_interrupt'
  from connection_pool.rb:62:in `block in with'
  from connection_pool.rb:59:in `handle_interrupt'
  from connection_pool.rb:59:in `with'
  from sidekiq.rb:92:in `redis'
  from sidekiq/pro/super_fetch.rb:223:in `cleanup_the_dead'
  from sidekiq/pro/super_fetch.rb:76:in `block in startup'
  from sidekiq/util.rb:56:in `watchdog'
  from sidekiq/pro/super_fetch.rb:72:in `startup'
  from sidekiq/pro/super_fetch.rb:61:in `block (2 levels) in setup'
```
If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/main/Changes.md
https://github.com/mperham/sidekiq/blob/main/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/main/Ent-Changes.md

**Comment by jakeonfire** [comment]
after upgrading to sidekiq 6.5.1 / sidekiq-pro 5.5.2 this problem has gone away

**Comment by mperham** [comment]
That would indicate you have a job in Redis which JSON can decode but does not have a JID. Are you manually creating and injecting jobs into Redis somewhere?

**Comment by jakeonfire** [comment]
tried running this in a console and it just prints lots of `.`s:
```ruby
Sidekiq.redis do |conn|
  conn.sscan_each("super_processes") do |x|
    next if conn.exists(x) > 0

    print "."

    qs = conn.smembers("#{x}:super_queues")
    qs.each do |priv|
      working_queue = priv
      jobstr = conn.lindex(working_queue, -1)
      break unless jobstr
      job = JSON.parse(jobstr)
      puts %(\n==> job: #{job.ai}) unless job.key?("jid")
    end
  end
end
```
any suggestions for how to find the problematic jobs?

**Comment by jakeonfire** [comment]
@mperham how would i remove the bad data now that i've fixed the underlying issue? would it be safe to run:
```ruby
Sidekiq.redis do |conn|
  conn.sscan_each("super_processes") do |x|
    next if conn.exists(x) > 0

    conn.del("#{x}:super_queues")
    conn.srem("super_processes", x)
  end
end
```
?

**Comment by mperham** [comment]
You want to shut down Sidekiq and then delete all keys matching `queue:sq|*`. This will purge all orphaned jobs from existing super queues.

**Comment by jakeonfire** [comment]
hmm... what if i can't shut down sidekiq?

**Comment by jakeonfire** [comment]
can i disable `super_fetch!` and then delete all keys matching `queue:sq|*`?

**Comment by mperham** [comment]
That would work.
