### ISSUE TITLE
sidekiq failing when it tries to read environment file mailer settings

### ISSUE THREAD

**Issue by JosephProxLearn** [mperham/sidekiq#5542]
Ruby version: 3.1
Rails version: 7.0.2
Sidekiq / Pro / Enterprise version(s):  6.5.3

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

**Contents of config/initializers/sidekiq.rb**

```
redis_url = 'redis://localhost:6379/1'
redis_url = 'redis://127.0.0.1:6379/1' if ENV['RAILS_ENV'] != 'development'
Sidekiq.configure_server do |config|
  config.redis = { url: redis_url }
  schedule_file = "config/schedule.yml"
  if File.exists?(schedule_file)
    Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)
  end
end
Sidekiq.configure_client do |config|
  config.redis = { url: redis_url }
end
```
**Contents of config/sidekiq.yml:**
```
development:
  :concurrency: 5
test:
  :concurrency: 5
staging:
  :concurrency: 5
hotfix:
  :concurrency: 5
production:
  :concurrency: 10
:max_retries: 1
:queues:
  - default
```

**Contents of  /home/deploy/.config/systemd/user/sidekiq.service:**
```
[Unit]
Description=sidekiq
After=syslog.target network.target redis-server.service
[Service]
Type=notify
WatchdogSec=10
WorkingDirectory=/home/deploy/current
ExecStart=/bin/bash -lc 'exec /home/deploy/.rbenv/shims/bundle exec sidekiq -C /home/deploy/current/config/sidekiq.yml -e test'
ExecReload=/usr/bin/kill -TSTP $MAINPID
Environment=MALLOC_ARENA_MAX=2
RestartSec=1
Restart=always
StandardOutput=file:/home/deploy/current/log/sidekiq.log
StandardError=file:/home/deploy/current/log/sidekiq.error
SyslogIdentifier=''
[Install]
WantedBy=multi-user.target
```
**Contents of my deployment script: /home/deploy/deploy.sh**
```
systemctl --user daemon-reload
systemctl --user stop sidekiq
sudo rm -Rf /home/deploy/current/
git clone -b test git@xxxxxxxxxxxxxxxxx.git /home/deploy/current
cd /home/deploy/current/
bundle install
rake db:migrate
rake db:seed
rails tailwindcss:build
bundle exec rake assets:precompile
bundle binstubs puma
sudo systemctl stop puma
sudo systemctl start puma
sudo service nginx restart
systemctl --user start sidekiq
```
When deploy.sh is done, I see the following message at the end:
```
Job for sidekiq.service failed because the control process exited with error code.
See "systemctl --user status sidekiq.service" and "journalctl --user -xeu sidekiq.service" for details.
```
**In /home/deploy/current/log/sidekiq.log, I now have:**

```
2022-09-23T23:21:29.606Z pid=14724 tid=4hg INFO: Enabling systemd notification integration
2022-09-23T23:21:29.606Z pid=14724 tid=4hg INFO: Pinging systemd watchdog every 5.0 sec
2022-09-23T23:21:31.851Z pid=14724 tid=4hg WARN: NoMethodError: undefined method `[]' for nil:NilClass

  config.action_mailer.default_url_options = { :host => Rails.application.credentials.app_absolute_urls[:test] }
                                                                                                       ^^^^^^^
2022-09-23T23:21:31.851Z pid=14724 tid=4hg WARN: /home/deploy/current/config/environments/test.rb:42:in `block in <main>'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/railtie.rb:251:in `instance_eval'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/railtie.rb:251:in `configure'
/home/deploy/current/config/environments/test.rb:8:in `<main>'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/engine.rb:562:in `block (2 levels) in <class:Engine>'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/engine.rb:561:in `each'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/engine.rb:561:in `block in <class:Engine>'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/initializable.rb:32:in `instance_exec'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/initializable.rb:32:in `run'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/initializable.rb:50:in `each'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:415:in `call'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `each'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `call'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/initializable.rb:60:in `run_initializers'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/application.rb:372:in `initialize!'
/home/deploy/current/config/environment.rb:5:in `<top (required)>'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/cli.rb:274:in `require'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/cli.rb:274:in `boot_application'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.3/lib/sidekiq/cli.rb:42:in `run'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.3/bin/sidekiq:31:in `<top (required)>'
/home/deploy/.rbenv/versions/3.1.0/bin/sidekiq:25:in `load'
/home/deploy/.rbenv/versions/3.1.0/bin/sidekiq:25:in `<top (required)>'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:58:in `load'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:23:in `run'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/cli.rb:484:in `exec'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/cli.rb:31:in `dispatch'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/cli.rb:25:in `start'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/exe/bundle:48:in `block in <top (required)>'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/home/deploy/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/exe/bundle:36:in `<top (required)>'
/home/deploy/.rbenv/versions/3.1.0/bin/bundle:25:in `load'
/home/deploy/.rbenv/versions/3.1.0/bin/bundle:25:in `<main>'
```

If go into a rails console: **rails c** and do:
```
Rails.application.credentials.app_absolute_urls[:test]
```
I get a valid result

Doing  **systemctl --user status sidekiq.service**, I get:
```
● sidekiq.service - sidekiq
     Loaded: loaded (/home/deploy/.config/systemd/user/sidekiq.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2022-09-23 23:44:50 UTC; 379ms ago
    Process: 23843 ExecStart=/bin/bash -lc exec /home/deploy/.rbenv/shims/bundle exec sidekiq -C /home/deploy/current/config/sidekiq.yml -e test (code=exited, status=1/FAILURE)
   Main PID: 23843 (code=exited, status=1/FAILURE)
        CPU: 5.735s
```

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/main/Changes.md
https://github.com/mperham/sidekiq/blob/main/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/main/Ent-Changes.md

**Comment by seuros** [comment]
Not a sidekiq bug
seem like `credentials.app_absolute_urls ` is not defined, check that your test can decode the credentials or move them the configuration  a config file `config_for`

**Comment by JosephProxLearn** [comment]
> Not a sidekiq bug seem like `credentials.app_absolute_urls ` is not defined, check that your test can decode the credentials or move them the configuration a config file `config_for`

 `credentials.app_absolute_urls ` is definitely there. Please see the issue description. They are used in multiple places in the code, and all the tests run fine. I am not sure what you mean by moving the functionality to a config file `config_for`
