### ISSUE TITLE
Sidekiq.redis is missing some methods in 7.0.0.beta1

### ISSUE THREAD

**Issue by radamanthus** [mperham/sidekiq#5545]
`sidekiq-scheduler` won't start when paired with Sidekiq 7.0.0.beta1

```
2022-09-28T11:53:02.770Z pid=2959858 tid=1rk26 WARN: RedisClient::CommandError: ERR unknown command 'exists?', with args beginning with: 'schedules' 
```

The error happens [here](https://github.com/sidekiq-scheduler/sidekiq-scheduler/blob/02fc716588601d92fa667a8b310f4f91e6119763/lib/sidekiq-scheduler/redis_manager.rb#L99) when sidekiq-scheduler tries to check if the 'schedule' key exists:

It looks like `.exists?` is not yet implemented in `Sidekiq::RedisClientAdapter::CompatClient`.
Is it upcoming, or should we no longer rely on `Sidekiq.redis` to get a handle to the Redis client?

---
_NOTE: To replicate the error, you'll need to make some changes to sidekiq-scheduler - see below._

This line complains about converting `Sidekiq::Config` to `Hash`:
https://github.com/sidekiq-scheduler/sidekiq-scheduler/blob/master/lib/sidekiq-scheduler/manager.rb#L40

I think the code change for this one needs to be done in `sidekiq-scheduler`. 
To get around it, I changed the line above to
```
scheduler_options = DEFAULT_SCHEDULER_OPTIONS.merge(options.options)
```

After I made this change, I encountered the ERR unknown command error:
```
2022-09-28T11:53:02.770Z pid=2959858 tid=1rk26 WARN: RedisClient::CommandError: ERR unknown command 'exists?', with args beginning with: 'schedules' 
```
---

Ruby version: 3.0.4p208
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 7.0.0.beta1

initializer:
```
Sidekiq.configure_server do |config|
  config.redis = { url: ENV["REDIS_URL"] }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV["REDIS_URL"] }
end
```

sidekiq.yml:
```
:queues:
  - default

:schedule:
  import_users:
    cron: '0 0 * * * *' # Runs every hour
    class: ImportUsersFromGoogleSheetsWorker
```

Error message:
```
2022-09-28T11:53:02.770Z pid=2959858 tid=1rk26 WARN: RedisClient::CommandError: ERR unknown command 'exists?', with args beginning with: 'schedules' 
```

Full backtrace:
```
2022-09-28T11:53:02.768Z pid=2959858 tid=1rk26 INFO: Booted Rails 7.0.4 application in development environment
2022-09-28T11:53:02.768Z pid=2959858 tid=1rk26 INFO: Running in ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]
2022-09-28T11:53:02.768Z pid=2959858 tid=1rk26 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2022-09-28T11:53:02.768Z pid=2959858 tid=1rk26 INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2022-09-28T11:53:02.768Z pid=2959858 tid=1rk26 INFO: Sidekiq 7.0.0.beta1 connecting to Redis with options {:url=>nil, :size=>5, :pool_name=>"internal"}
2022-09-28T11:53:02.770Z pid=2959858 tid=1rk26 INFO: Sidekiq 7.0.0.beta1 connecting to Redis with options {:url=>nil, :size=>5, :pool_name=>"default"}
2022-09-28T11:53:02.770Z pid=2959858 tid=1rk26 WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"startup"}
2022-09-28T11:53:02.770Z pid=2959858 tid=1rk26 WARN: RedisClient::CommandError: ERR unknown command 'exists?', with args beginning with: 'schedules' 
2022-09-28T11:53:02.770Z pid=2959858 tid=1rk26 WARN: /home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/redis-client-0.9.0/lib/redis_client/connection_mixin.rb:22:in `call'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/redis-client-0.9.0/lib/redis_client.rb:199:in `block (2 levels) in call'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/redis-client-0.9.0/lib/redis_client/middlewares.rb:12:in `call'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/redis-client-0.9.0/lib/redis_client.rb:198:in `block in call'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/redis-client-0.9.0/lib/redis_client.rb:615:in `ensure_connected'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/redis-client-0.9.0/lib/redis_client.rb:197:in `call'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/redis_client_adapter.rb:25:in `method_missing'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/redis_manager.rb:99:in `block in schedule_exist?'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/config.rb:156:in `block in redis'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/config.rb:153:in `redis'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq.rb:49:in `redis'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/redis_manager.rb:99:in `schedule_exist?'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/schedule.rb:84:in `get_all_schedules'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/schedule.rb:43:in `schedule='
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/manager.rb:25:in `initialize'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler.rb:21:in `new'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler.rb:21:in `block (2 levels) in <main>'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/component.rb:58:in `block in fire_event'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/component.rb:57:in `each'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/component.rb:57:in `fire_event'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/cli.rb:105:in `run'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/bin/sidekiq:31:in `<top (required)>'
/home/rad/.asdf/installs/ruby/3.0.4/bin/sidekiq:25:in `load'
/home/rad/.asdf/installs/ruby/3.0.4/bin/sidekiq:25:in `<main>'
ERR unknown command 'exists?', with args beginning with: 'schedules' 
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/redis-client-0.9.0/lib/redis_client/connection_mixin.rb:22:in `call'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/redis-client-0.9.0/lib/redis_client.rb:199:in `block (2 levels) in call'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/redis-client-0.9.0/lib/redis_client/middlewares.rb:12:in `call'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/redis-client-0.9.0/lib/redis_client.rb:198:in `block in call'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/redis-client-0.9.0/lib/redis_client.rb:615:in `ensure_connected'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/redis-client-0.9.0/lib/redis_client.rb:197:in `call'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/redis_client_adapter.rb:25:in `method_missing'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/redis_manager.rb:99:in `block in schedule_exist?'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/config.rb:156:in `block in redis'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/config.rb:153:in `redis'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq.rb:49:in `redis'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/redis_manager.rb:99:in `schedule_exist?'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/schedule.rb:84:in `get_all_schedules'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/schedule.rb:43:in `schedule='
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/manager.rb:25:in `initialize'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler.rb:21:in `new'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler.rb:21:in `block (2 levels) in <main>'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/component.rb:58:in `block in fire_event'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/component.rb:57:in `each'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/component.rb:57:in `fire_event'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/cli.rb:105:in `run'
/home/rad/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.0.beta1/bin/sidekiq:31:in `<top (required)>'
/home/rad/.asdf/installs/ruby/3.0.4/bin/sidekiq:25:in `load'
/home/rad/.asdf/installs/ruby/3.0.4/bin/sidekiq:25:in `<main>'
```

**Comment by mperham** [comment]
`exists?(key)` is not implemented by redis-client. You can change your code to use to `exists(key) == 1`

**Comment by mperham** [comment]
Sidekiq internals were greatly refactored in order to support Capsules and Embedding. Most Sidekiq plugins will require some amount of maintenance. I've offered to help any plugin author:

https://twitter.com/getajobmike/status/1570530115255439360?s=20&t=n5m5ffyosyRhqZov6NqGFw

**Comment by radamanthus** [comment]
Awesome! I'm not a maintainer of sidekiq-scheduler, but I use it and having it work with Sidekiq 7 is the only way I can get my hands on Sidekiq 7 in production, so I'll do what I can to help them out with the upgrade.
