### ISSUE TITLE
Sidekiq 7.0.0.beta1, unable to start, undefined method  `[]=' for Sidekiq:Module (NoMethodError)

### ISSUE THREAD

**Issue by BobbyMcWho** [mperham/sidekiq#5549]
Ruby version: 2.7.6
Rails version: 6.1.7
Sidekiq / Pro / Enterprise version(s): 7.0.0.beta1 / 5.5.4 / 2.5.3

I can't start up sidekiqswarm due to the following, I haven't included initializers since this looks to be failing at the loading of the Sidekiq classes. 

```sh
[swarm] Preloading Bundler groups ["default"]
bundler: failed to load command: sidekiqswarm (/usr/local/bundle/bin/sidekiqswarm)
/usr/local/bundle/gems/sidekiq-pro-5.5.4/lib/sidekiq/pro/push.rb:6:in `<module:Sidekiq>': undefined method `[]=' for Sidekiq:Module (NoMethodError)
     from /usr/local/bundle/gems/sidekiq-pro-5.5.4/lib/sidekiq/pro/push.rb:1:in `<top (required)>'
     from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
     from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
     from /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
     from /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
     from /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
     from /usr/local/bundle/gems/sidekiq-pro-5.5.4/lib/sidekiq-pro.rb:7:in `<top (required)>'
     from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
     from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/runtime.rb:55:in `each'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/runtime.rb:55:in `block in require'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/runtime.rb:44:in `each'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/runtime.rb:44:in `require'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler.rb:187:in `require'
     from /usr/local/bundle/gems/sidekiq-ent-2.5.3/bin/sidekiqswarm:40:in `<top (required)>'
     from /usr/local/bundle/bin/sidekiqswarm:25:in `load'
     from /usr/local/bundle/bin/sidekiqswarm:25:in `<top (required)>'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:58:in `load'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:23:in `run'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli.rb:486:in `exec'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli.rb:31:in `dispatch'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli.rb:25:in `start'
     from /usr/local/bundle/gems/bundler-2.3.22/exe/bundle:48:in `block in <top (required)>'
     from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
     from /usr/local/bundle/gems/bundler-2.3.22/exe/bundle:36:in `<top (required)>'
     from /usr/local/bundle/bin/bundle:25:in `load'
     from /usr/local/bundle/bin/bundle:25:in `<main>'
backend_sidekiq_1 exited with code 1
```

**Comment by BobbyMcWho** [comment]
Per https://github.com/mperham/sidekiq/pull/5080, it seems like you're planning a pro 6.0.0, and ent 3.0.0, but I don't see any 6.0.0.beta1 or 3.0.0.beta1 betas in the release channels via our ent subscription.

**Comment by mperham** [comment]
Pro 5.5.5 was released earlier this week which locks it to Sidekiq 6.x. Sidekiq Pro 6.x is required for Sidekiq 7.x. No commercial extensions are available for Sidekiq 7.x just yet.

https://github.com/mperham/sidekiq/blob/main/Pro-Changes.md#555

**Comment by BobbyMcWho** [comment]
Ah okay, if betas of those do open up, please let me know, as I'm willing to help see if anything breaks in one of our staging envs
