### ISSUE TITLE
NoMethodError: undefined method `[]=' for Sidekiq:Module

### ISSUE THREAD

**Issue by rafaelxy** [mperham/sidekiq#5570]
Ruby version: 3.1.1
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s):
sidekiq (7.0.0.beta1)
sidekiq-pro (5.5.4)

I am not sure if I can share the initializer, so I am skipping it.

Running a simple rake command, or pretty much any rake/rails operation:
```
$ rake db
rake aborted!
NoMethodError: undefined method `[]=' for Sidekiq:Module

  self[:backup_limit] = 1_000
      ^^^^^^^^^^^^^^^^^
/Users/rafaelxy/.gem/ruby/3.1.1/gems/sidekiq-pro-5.5.4/lib/sidekiq/pro/push.rb:6:in `<module:Sidekiq>'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/sidekiq-pro-5.5.4/lib/sidekiq/pro/push.rb:1:in `<main>'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/sidekiq-pro-5.5.4/lib/sidekiq-pro.rb:7:in `<main>'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/sidekiq-ent-2.5.3/lib/sidekiq-ent.rb:3:in `<main>'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bundler-2.3.16/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bundler-2.3.16/lib/bundler/runtime.rb:55:in `each'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bundler-2.3.16/lib/bundler/runtime.rb:55:in `block in require'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bundler-2.3.16/lib/bundler/runtime.rb:44:in `each'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bundler-2.3.16/lib/bundler/runtime.rb:44:in `require'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bundler-2.3.16/lib/bundler.rb:187:in `require'
/Users/rafaelxy/src/github.com/Shopify/bloodhound/config/application.rb:12:in `<top (required)>'
/Users/rafaelxy/src/github.com/Shopify/bloodhound/Rakefile:6:in `require_relative'
/Users/rafaelxy/src/github.com/Shopify/bloodhound/Rakefile:6:in `<top (required)>'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
```

This started after a gem bump from:
    redis (4.8.0) to (5.0.5)
that pushed the dependency on:
    sidekiq (6.5.7) to (7.0.0.beta1)
weirdly it pushed back the dependency on:
    sidekiq-pro (5.5.5) to (5.5.4)

I tried to force `sidekiq-pro` to (5.5.5) and got:
```
$ rake db
rake aborted!
NoMethodError: undefined method `[]' for Sidekiq:Module

Sidekiq[:lifecycle_events][:leader] = []
       ^^^^^^^^^^^^^^^^^^^
/Users/rafaelxy/.gem/ruby/3.1.1/gems/sidekiq-ent-2.5.3/lib/sidekiq-ent.rb:5:in `<main>'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bundler-2.3.16/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bundler-2.3.16/lib/bundler/runtime.rb:55:in `each'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bundler-2.3.16/lib/bundler/runtime.rb:55:in `block in require'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bundler-2.3.16/lib/bundler/runtime.rb:44:in `each'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bundler-2.3.16/lib/bundler/runtime.rb:44:in `require'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/bundler-2.3.16/lib/bundler.rb:187:in `require'
/Users/rafaelxy/src/github.com/Shopify/bloodhound/config/application.rb:12:in `<top (required)>'
/Users/rafaelxy/src/github.com/Shopify/bloodhound/Rakefile:6:in `require_relative'
/Users/rafaelxy/src/github.com/Shopify/bloodhound/Rakefile:6:in `<top (required)>'
/Users/rafaelxy/.gem/ruby/3.1.1/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
```

**Comment by mperham** [comment]
Pro 5 does not work with Sidekiq 7.

**Comment by mperham** [comment]
You need Pro 6b1.

**Comment by rafaelxy** [comment]
@mperham Thanks!
fixing the sidekiq-pro (6.0.0.beta1) and sidekiq-ent (3.0.0.beta1) apparently resolve the issue!

**Comment by mperham** [comment]
Thank you for trying the beta releases. Please let me know how your testing goes even if it's just "works great for us".
