### ISSUE TITLE
Note redis-client ssl_params are handled differently on Sidekiq 7 than Sidekiq 6

### ISSUE THREAD

**Issue by bf4** [mperham/sidekiq#5591]
Ruby version: 3.0.3
Rails version: 7.0.4
Sidekiq / Pro version(s): 7.0.0.beta1 / 6.0.0.beta1  ( testing upgrade from 6.5.7 / 5.5.5 )

It looks like redis-client supports the ssl_params option https://github.com/redis-rb/redis-client/blob/v0.10.0/lib/redis_client/config.rb#L15 and we are using it on sidekiq 6 per `Sidekiq::RedisConnection.adapter = :redis_client`. I'm not yet sure what may have changed.  I've looked through the changes in the code and checked for other issues.

code

```ruby
  if RedisConnection.ok?
    $stderr.puts "Telling Sidekiq not to process any new jobs (TSTP)"
    require "sidekiq/api"
    Sidekiq::ProcessSet.new.each(&:quiet!)
```

where

```ruby
module RedisConnection
  extend self

  def redis_config
    @redis_config ||= Rails.application.config_for(:redis).merge(
      # per https://devcenter.heroku.com/articles/securing-heroku-redis
      ssl_params: {verify_mode: OpenSSL::SSL::VERIFY_NONE},
    )
  end
```

and in the initializer

```ruby
redis_config = RedisConnection.redis_config

Sidekiq.configure_client do |config|
  config.redis = redis_config
end

Sidekiq.configure_server do |config|
  # NOTE(BF) https://github.com/mperham/sidekiq/issues/5441
  # will crash if Sidekiq.redis_pool.size < Sidekiq[:concurrency] + 2
  config.redis = redis_config
end
```

backtrace

```
remote: RedisClient::CannotConnectError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)
remote: /app/vendor/bundle/ruby/3.0.0/gems/redis-client-0.10.0/lib/redis_client/ruby_connection.rb:62:in `connect_nonblock'
remote: /app/vendor/bundle/ruby/3.0.0/gems/redis-client-0.10.0/lib/redis_client/ruby_connection.rb:62:in `block in initialize'
remote: /app/vendor/bundle/ruby/3.0.0/gems/redis-client-0.10.0/lib/redis_client/ruby_connection.rb:61:in `loop'
remote: /app/vendor/bundle/ruby/3.0.0/gems/redis-client-0.10.0/lib/redis_client/ruby_connection.rb:61:in `initialize'
remote: /app/vendor/bundle/ruby/3.0.0/gems/redis-client-0.10.0/lib/redis_client.rb:654:in `new'
remote: /app/vendor/bundle/ruby/3.0.0/gems/redis-client-0.10.0/lib/redis_client.rb:654:in `block in connect'
remote: /app/vendor/bundle/ruby/3.0.0/gems/redis-client-0.10.0/lib/redis_client/middlewares.rb:12:in `connect'
remote: /app/vendor/bundle/ruby/3.0.0/gems/redis-client-0.10.0/lib/redis_client.rb:653:in `connect'
remote: /app/vendor/bundle/ruby/3.0.0/gems/redis-client-0.10.0/lib/redis_client.rb:647:in `raw_connection'
remote: /app/vendor/bundle/ruby/3.0.0/gems/redis-client-0.10.0/lib/redis_client.rb:614:in `ensure_connected'
remote: /app/vendor/bundle/ruby/3.0.0/gems/redis-client-0.10.0/lib/redis_client.rb:198:in `call'
remote: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/redis_client_adapter.rb:25:in `method_missing'
remote: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/api.rb:839:in `block in cleanup'
remote: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/config.rb:156:in `block in redis'
remote: /app/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
remote: /app/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
remote: /app/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
remote: /app/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
remote: /app/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
remote: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/config.rb:153:in `redis'
remote: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq.rb:49:in `redis'
remote: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/api.rb:839:in `cleanup'
remote: /app/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.0.beta1/lib/sidekiq/api.rb:830:in `initialize'
remote: /app/lib/tasks/release.rake:45:in `new'
```

**Comment by mperham** [comment]
Is your rake task actually booting the rails environment so the initializer is run before the API calls?

**Comment by bf4** [comment]
Yes, it does

```ruby
desc "Run this task on release. (See Procfile)"
task release: :environment do
  release!
end
```

Also, nothing obvious changed in the PR to upgrade the Sidekiq. I've extracted all backward-compatible changes prompted by the upgrade into our main deploy. I'll try the non-beta release and report back what happens.

**Comment by mscrivo** [comment]
Seeing the same issue here

**Comment by bf4** [comment]
Ah, figured out the core issue

I recommend you set all your defaults in Sidekiq 7 on the `Sidekiq.default_configuration` object

e.g.

```diff
+ Sidekiq.default_configuration.redis = redis_config
+ Sidekiq.default_configuration.logger = sidekiq_logger
- Sidekiq.configure_client do |config|
-   config.redis = redis_config
-   config.logger = sidekiq_logger
- end
- Sidekiq.configure_server do |config|
-   config.redis = redis_config
-   config.logger = sidekiq_logger
- end
```

That way your default sidekiq config, such as used in `Sidekiq::Deploy.mark!(application_version)` is the same as what's configured for the server and client.

(You don't have to remove the Sidekiq.configure_client/Sidekiq.configure_server in the above diff, but you'll likely need to add the `Sidekiq.default_configuration.redis = redis_config` for  your `Sidekiq::Deploy` to work since that will just look at the REDIS_URL or whatever and not see, say `ssl_params: {verify_mode: OpenSSL::SSL::VERIFY_NONE}`
