### ISSUE TITLE
RedisClient::ConnectionError: Not connected with hiredis-client 0.10.0

### ISSUE THREAD

**Issue by doersf** [mperham/sidekiq#5597]
Ruby version: 3.1.2
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 7.0.0
Redis version: 7.0.5

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

$ bundle exec sidekiq -e production -q default

No sidekiq.yml.

```
2022-10-28T23:44:08.277Z pid=2465 tid=52x INFO: Booted Rails 7.0.4 application in production environment
2022-10-28T23:44:08.277Z pid=2465 tid=52x INFO: Running in ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
2022-10-28T23:44:08.277Z pid=2465 tid=52x INFO: Sidekiq Pro 7.0.0, commercially licensed. Thanks for your support!
2022-10-28T23:44:08.277Z pid=2465 tid=52x INFO: Sidekiq 7.0.0 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>nil}
2022-10-28T23:44:08.279Z pid=2465 tid=52x INFO: Sidekiq 7.0.0 connecting to Redis with options {:size=>5, :pool_name=>"default", :url=>nil}
2022-10-28T23:44:09.287Z pid=2465 tid=kax WARN: {"_config":"#<Sidekiq::Config:0x00007fd4aaf6ea88>"}
2022-10-28T23:44:09.287Z pid=2465 tid=kax WARN: RedisClient::ConnectionError: Not connected
2022-10-28T23:44:09.287Z pid=2465 tid=kax WARN: /home/<dir>/vendor/cache/ruby/3.1.0/gems/hiredis-client-0.10.0/lib/redis_client/hiredis_connection.rb:74:in `_read'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/hiredis-client-0.10.0/lib/redis_client/hiredis_connection.rb:74:in `read'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/redis-client-0.10.0/lib/redis_client.rb:431:in `next_event'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/sidekiq-7.0.0/lib/sidekiq/redis_client_adapter.rb:58:in `block in subscribe'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/sidekiq-7.0.0/lib/sidekiq/redis_client_adapter.rb:57:in `loop'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/sidekiq-7.0.0/lib/sidekiq/redis_client_adapter.rb:57:in `subscribe'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/sidekiq-pro-7.0.0/lib/sidekiq/pro/config.rb:65:in `block in listen'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/sidekiq-7.0.0/lib/sidekiq/config.rb:156:in `block in redis'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/sidekiq-7.0.0/lib/sidekiq/config.rb:153:in `redis'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/sidekiq-7.0.0/lib/sidekiq/component.rb:26:in `redis'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/sidekiq-pro-7.0.0/lib/sidekiq/pro/config.rb:64:in `listen'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/sidekiq-7.0.0/lib/sidekiq/component.rb:8:in `watchdog'
/home/<dir>/vendor/cache/ruby/3.1.0/gems/sidekiq-7.0.0/lib/sidekiq/component.rb:17:in `block in safe_thread'
^C2022-10-28T23:44:10.435Z pid=2465 tid=52x INFO: Shutting down
2022-10-28T23:44:10.435Z pid=2465 tid=52x INFO: Terminating quiet threads for default capsule
2022-10-28T23:44:10.435Z pid=2465 tid=k7p INFO: Scheduler exiting...
```

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/main/Changes.md
https://github.com/mperham/sidekiq/blob/main/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/main/Ent-Changes.md

**Comment by mperham** [comment]
@casperisfine ?

**Comment by byroot** [comment]
Looking at the backtrace, it look like the hiredis connection adapter doesn't handle a specific error when listening to events.

I'll have a look tomorrow. Just out of curiosity, @doersf have you tried without `hiredis-client`? (Might be a bug in both)

**Comment by doersf** [comment]
Works fine without hiredis-client, @byroot

**Comment by doersf** [comment]
Resolved in https://github.com/redis-rb/redis-client/pull/56.
