### ISSUE TITLE
Update redis-client and Redis Sentinel instructions in the wiki

### ISSUE THREAD

**Issue by moenodedev** [mperham/sidekiq#5603]
Ruby version: 3.1.2
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 7.0.0, 7.0.0, 7.0.0

* Remove beta testing section
* Add example rails initializer for sidekiq that uses redis-client
* Add configuration instructions for Redis Sentinel

https://github.com/mperham/sidekiq/wiki/Using-redis-client

**Comment by moenodedev** [comment]
I'll submit a PR if we figure out how to make Sidekiq 7.0.0 work with our Rails app.

**Comment by mperham** [comment]
I'll remove that wiki page. It was more for the transition period from 6.4 -> 7.0. Sidekiq configuration should be backwards compatible, we can point to any redis-client docs on changes due to the transition.

**Comment by moenodedev** [comment]
@mperham We still can't get Sidekiq 7.0.0 working with redis-client and Redis Sentinel following the instructions at https://github.com/mperham/sidekiq/wiki/Using-Redis#complete-control and https://github.com/redis-rb/redis-client#sentinel-support.

Here's our initializer:

```rb
redis_conn = proc {
  RedisClient.sentinel(
    name: "main",
    sentinels: [
      {host: "198.51.100.2", port: 26380, password: "password"},
      {host: "198.51.100.3", port: 26381, password: "password"}
    ],
    role: :master
  )
}

Sidekiq.configure_client do |config|
  config.redis = redis_conn
end

Sidekiq.configure_server do |config|
  config.redis = redis_conn
end
```

**Comment by moenodedev** [comment]
We were missing the ConnectionPool call but there's still an error.

The rails initializer for sidekiq:
```ruby
redis_conn = proc {
  RedisClient.sentinel(
    name: "main",
    sentinels: [
      {host: "198.51.100.2", port: 26380, password: "password"},
      {host: "198.51.100.3", port: 26381, password: "password"}
    ],
    role: :master
  )
}

Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(size: 5, &redis_conn)
end

Sidekiq.configure_server do |config|
  config.redis = ConnectionPool.new(size: 5, &redis_conn)
end
```

The error message is:
```
Sidekiq 7.0.0 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>nil}                                       │
no implicit conversion of ConnectionPool into Hash
```

**Comment by moenodedev** [comment]
We also tried assigning `RedisClient.sentinel` directly to `config.redis`.

The rails initializer for sidekiq:
```ruby
Sidekiq.configure_client do |config|
  config.redis = RedisClient.sentinel(
    name: "main",
    sentinels: [
      {host: "198.51.100.2", port: 26380, password: "password"},
      {host: "198.51.100.3", port: 26381, password: "password"}
    ],
    role: :master
  )
end

Sidekiq.configure_server do |config|
  config.redis = RedisClient.sentinel(
    name: "main",
    sentinels: [
      {host: "198.51.100.2", port: 26380, password: "password"},
      {host: "198.51.100.3", port: 26381, password: "password"}
    ],
    role: :master
  )
end
```

The error message is:
```
Sidekiq 7.0.0 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>nil}                                       │
no implicit conversion of RedisClient::SentinelConfig into Hash
```

**Comment by moenodedev** [comment]
We tried [https://github.com/mperham/sidekiq/blob/ad9442f116086424948d60ec059755f9168a6bc8/test/redis_connection.rb#L145-L154](the example config in the tests) but that didn't work either.

The rails initializer for sidekiq:
```ruby
redis_config = {
  name: "mymaster",
  role: "master",
  sentinels: [
    {host: "198.51.100.2", port: 26380, password: "password"},
    {host: "198.51.100.3", port: 26381, password: "password"}
  ],
  password: "password"
}

Sidekiq.configure_client do |config|
  config.redis = redis_config
end

Sidekiq.configure_server do |config|
  config.redis = redis_config
end
```

The error message is:
```
Sidekiq 7.0.0 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>nil}
Address not available - connect(2) for [::1]:6379
```

**Comment by mperham** [comment]
Sidekiq 7.0.0 does not allow you to pass a ConnectionPool anymore. You must let Sidekiq create the pool.

Your last comment is correct, you just pass the sentinel config as part of the standard hash:

```ruby
redis_config = {
  name: "mymaster",
  role: "master",
  sentinels: [
    {host: "198.51.100.2", port: 26380, password: "password"},
    {host: "198.51.100.3", port: 26381, password: "password"}
  ],
  password: "password"
}
```

The backtrace you are seeing is the bug. I need the backtrace.

**Comment by moenodedev** [comment]
```ruby
# config/initializers/sidekiq.rb

Sidekiq::Client.reliable_push! unless Rails.env.test?
Sidekiq::Enterprise.unique! unless Rails.env.test?

redis_config = {
  name: "mymaster",
  role: "master",
  sentinels: [
    {host: "198.51.100.2", port: 26380, password: "password"},
    {host: "198.51.100.3", port: 26381, password: "password"}
  ],
  password: "password"
}

Sidekiq.configure_client do |config|
  config.redis = redis_config
end

Sidekiq.configure_server do |config|
  config.redis = redis_config

  config.super_fetch!
  config.reliable_scheduler!
end
```

Here's the backtrace:

```
$ bundle exec sidekiq -q default
2022-11-03T05:04:24.579Z pid=15391 tid=8nf INFO: Sidekiq 7.0.0 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>nil}

                                   /\.                            /\
        L -      --- -- ---,,-.  ./.: 8.    .-----8p--.  .---.s,-'.:`--+
 ,8b  8i     ,F.oSSS"Sbo.o.s8 .\/.:'.oD \  /.:::.dS8b .\/ .: o8o ::::::|
 `4P,oP   ,o8;(88(`.:.4Y8 `"'::'.:."8DD:`\/ `:::.`888 :.db.::`P' `:'  `:
   o8P, .o8P   48bo.`:."`.dS`:'.oSSbDD8.`.oSSbo.`.888::oOOo oooo `.oSSbo o/
  d888Ld8P'  `:."88888o.``888 d88',`488 d8('.`88b:88( .8P'.:`888 d88P `88P
  88 8P8P     .`.:.`"Y88b 888 888 O 84P 888bod8P'.888o88 .:::888 88( O 888
 dP'`Y8P      db .:::.)8P 888 888 " 888b888'....: 888`.88b.::888 88b " 88(
T   ;88i      4P"888888P'o888o.Y8bod88P"`Y8bod8P d888b..488od888b V8bod888o
     88'                  48P::`odb.dSo,, ."P'.roy<sac>` ""'.`.o.`.."S"888.
     `8                    ".:'d888P'."S8b.`.::... ...' `.:::.d8b ::'  dP'
     .8                    `  '"888 ::.)88\odbo d8b`.odSso.::.888.::."488"
     .8                       `:888bod88P'.`888P"8Pd88'`488b::888::::.`8\
     P                        .:888 "P'..:::88(.:."88( O )88::48P::'/'/\ \
                             /\ 888`::./\`::888:::,888.".888::.o./\<:<  > >
 -   -  -- --- ------.  .---'  d888bo./  `-d888b.`:`Y8SbS8P'--48P'  \ \/ /
                      \/       `8P':/        "   \/   """      "     \/\/
                                P'\/                                    /<>\

2022-11-03T05:04:26.734Z pid=15391 tid=8nf INFO: Booted Rails 7.0.4 application in development environment
2022-11-03T05:04:26.734Z pid=15391 tid=8nf INFO: Running in ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [aarch64-linux]
2022-11-03T05:04:26.734Z pid=15391 tid=8nf INFO: Sidekiq Pro 7.0.0 / Sidekiq Enterprise 7.0.0, commercially licensed.
Connection refused - connect(2) for 127.0.0.1:6379
/usr/local/ruby/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock'
/usr/local/ruby/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1214:in `connect_nonblock'
/usr/local/ruby/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:56:in `connect_internal'
/usr/local/ruby/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:137:in `connect'
/usr/local/ruby/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:642:in `block in tcp'
/usr/local/ruby/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:227:in `each'
/usr/local/ruby/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:227:in `foreach'
/usr/local/ruby/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:632:in `tcp'
/usr/local/ruby/gem/gems/redis-client-0.11.0/lib/redis_client/ruby_connection.rb:49:in `initialize'
/usr/local/ruby/gem/gems/redis-client-0.11.0/lib/redis_client.rb:654:in `new'
/usr/local/ruby/gem/gems/redis-client-0.11.0/lib/redis_client.rb:654:in `block in connect'
/usr/local/ruby/gem/gems/redis-client-0.11.0/lib/redis_client/middlewares.rb:12:in `connect'
/usr/local/ruby/gem/gems/redis-client-0.11.0/lib/redis_client.rb:653:in `connect'
/usr/local/ruby/gem/gems/redis-client-0.11.0/lib/redis_client.rb:647:in `raw_connection'
/usr/local/ruby/gem/gems/redis-client-0.11.0/lib/redis_client.rb:614:in `ensure_connected'
/usr/local/ruby/gem/gems/redis-client-0.11.0/lib/redis_client.rb:198:in `call'
/usr/local/ruby/gem/gems/sidekiq-7.0.0/lib/sidekiq/redis_client_adapter.rb:13:in `info'
/usr/local/ruby/gem/gems/sidekiq-7.0.0/lib/sidekiq/config.rb:137:in `block in redis_info'
/usr/local/ruby/gem/gems/sidekiq-7.0.0/lib/sidekiq/config.rb:156:in `block in redis'
/usr/local/ruby/gem/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
/usr/local/ruby/gem/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
/usr/local/ruby/gem/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
/usr/local/ruby/gem/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
/usr/local/ruby/gem/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
/usr/local/ruby/gem/gems/sidekiq-7.0.0/lib/sidekiq/config.rb:153:in `redis'
/usr/local/ruby/gem/gems/sidekiq-7.0.0/lib/sidekiq/config.rb:136:in `redis_info'
/usr/local/ruby/gem/gems/sidekiq-7.0.0/lib/sidekiq/cli.rb:75:in `run'
/usr/local/ruby/gem/gems/sidekiq-7.0.0/bin/sidekiq:31:in `<top (required)>'
/usr/local/ruby/gem/bin/sidekiq:25:in `load'
/usr/local/ruby/gem/bin/sidekiq:25:in `<top (required)>'
/usr/local/ruby/gem/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/ruby/gem/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/ruby/gem/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/ruby/gem/gems/bundler-2.3.25/lib/bundler/cli.rb:486:in `exec'
/usr/local/ruby/gem/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/ruby/gem/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/ruby/gem/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/ruby/gem/gems/bundler-2.3.25/lib/bundler/cli.rb:31:in `dispatch'
/usr/local/ruby/gem/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/ruby/gem/gems/bundler-2.3.25/lib/bundler/cli.rb:25:in `start'
/usr/local/ruby/gem/gems/bundler-2.3.25/exe/bundle:48:in `block in <top (required)>'
/usr/local/ruby/gem/gems/bundler-2.3.25/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
/usr/local/ruby/gem/gems/bundler-2.3.25/exe/bundle:36:in `<top (required)>'
/usr/local/ruby/rubies/ruby-3.1.2/bin/bundle:25:in `load'
/usr/local/ruby/rubies/ruby-3.1.2/bin/bundle:25:in `<main>'
```

**Comment by mperham** [comment]
You’re referencing Sidekiq features before configuring Redis. Move those top two lines below the configure blocks.

**Comment by moenodedev** [comment]
#5606 seemed to be the issue.

This configuration worked for us:

Gemfile
```diff
-  gem "sidekiq-ent"
-  gem "sidekiq-pro"
+  gem "sidekiq-ent", require: false
+  gem "sidekiq-pro", require: false
```

```ruby
# config/initializers/sidekiq.rb

redis_config = {
  name: "mymaster",
  role: "master",
  sentinels: [
    {host: "198.51.100.2", port: 26380, password: "password"},
    {host: "198.51.100.3", port: 26381, password: "password"}
  ],
  password: "password"
}

Sidekiq.configure_client do |config|
  config.redis = redis_config
end

Sidekiq.configure_server do |config|
  config.redis = redis_config
end

require "sidekiq-pro"
require "sidekiq-ent"
Sidekiq::Client.reliable_push! unless Rails.env.test?
Sidekiq::Enterprise.unique! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!
end
```
