### ISSUE TITLE
sidekiq-ent 7 connects to redis as soon as it's required

### ISSUE THREAD

**Issue by jdelStrother** [mperham/sidekiq#5606]
By default it seems like sidekiq-ent connects to redis as soon as it's required. In Rails apps this is typically in application.rb (`Bundler.require(*Rails.groups)`), which occurs before we've had change to configure redis in config/initializers/sidekiq.rb

Here's the stack from where it's about to start a redis connection following a `bundle exec sidekiq`, 

```
$GEMS/sidekiq-7.0.0/lib/sidekiq/config.rb:132:in `new_redis_pool'
$GEMS/sidekiq-7.0.0/lib/sidekiq/config.rb:126:in `local_redis_pool'
$GEMS/sidekiq-7.0.0/lib/sidekiq/config.rb:120:in `redis_pool'
$GEMS/sidekiq-ent-7.0.0/lib/sidekiq-ent/scripting.rb:9:in `bootstrap'
$GEMS/sidekiq-ent-7.0.0/lib/sidekiq-ent/scripting.rb:37:in `block in <main>'
$GEMS/sidekiq-7.0.0/lib/sidekiq.rb:98:in `configure_server'
$GEMS/sidekiq-ent-7.0.0/lib/sidekiq-ent/scripting.rb:36:in `<main>'
$GEMS/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
$GEMS/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'
$GEMS/sidekiq-ent-7.0.0/lib/sidekiq-ent.rb:9:in `<main>'
$GEMS/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
$GEMS/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'
$GEMS/bundler-2.3.14/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
$GEMS/bundler-2.3.14/lib/bundler/runtime.rb:55:in `each'
$GEMS/bundler-2.3.14/lib/bundler/runtime.rb:55:in `block in require'
$GEMS/bundler-2.3.14/lib/bundler/runtime.rb:44:in `each'
$GEMS/bundler-2.3.14/lib/bundler/runtime.rb:44:in `require'
$GEMS/bundler-2.3.14/lib/bundler.rb:176:in `require'
config/application.rb:42:in `<top (required)>'
config/environment.rb:4:in `require_relative'
config/environment.rb:4:in `<top (required)>'
$GEMS/sidekiq-7.0.0/lib/sidekiq/cli.rb:301:in `require'
$GEMS/sidekiq-7.0.0/lib/sidekiq/cli.rb:301:in `boot_application'
$GEMS/sidekiq-7.0.0/lib/sidekiq/cli.rb:42:in `run'
$GEMS/sidekiq-7.0.0/bin/sidekiq:31:in `<top (required)>'
bin/sidekiq:25:in `load'
bin/sidekiq:25:in `<top (required)>'
$GEMS/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `load'
$GEMS/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `kernel_load'
$GEMS/bundler-2.3.14/lib/bundler/cli/exec.rb:23:in `run'
$GEMS/bundler-2.3.14/lib/bundler/cli.rb:483:in `exec'
$GEMS/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
$GEMS/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
$GEMS/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
$GEMS/bundler-2.3.14/lib/bundler/cli.rb:31:in `dispatch'
$GEMS/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
$GEMS/bundler-2.3.14/lib/bundler/cli.rb:25:in `start'
$GEMS/bundler-2.3.14/exe/bundle:48:in `block in <top (required)>'
$GEMS/bundler-2.3.14/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
$GEMS/bundler-2.3.14/exe/bundle:36:in `<top (required)>'
bin/bundle:25:in `load'
bin/bundle:25:in `<main>'
```

I think that connection config is maybe getting cached somewhere - when I later try to set `Sidekiq.configure_server { |config| config.redis = ... }` it still seems to be trying to connect to redis on the default localhost:6379. Let me know if it's not immediately obvious & I'll try to narrow down the reproduction.

Ruby version: 3.1.2
Rails version: 7.0
Sidekiq / Pro / Enterprise version(s): 7.0

sidekiq.yml:

```
---
# make concurrency match rails' setting by default, to ensure we don't keep hitting connection pool limits.
:concurrency: <%= ENV["RAILS_MAX_THREADS"]&.to_i || 5 %>
:queues:
  - high
  - default
  - low
```

**Comment by mperham** [comment]
Thanks, this will be in 7.0.1.

**Comment by mperham** [comment]
BTW the "fix" is the comment out the 3 lines at the bottom of `lib/sidekiq-ent/scripting.rb`. If that works for you, please let me know as I don't have a good way to test this change.

**Comment by jdelStrother** [comment]
> BTW the "fix" is to comment out the 3 lines at the bottom of `lib/sidekiq-ent/scripting.rb`. If that works for you, please let me know as I don't have a good way to test this change.

Yep, that works.


---

One maybe-related behaviour change in 7.x - I notice that `Sidekiq::Client.reliable_push!` now sets up a redis connection immediately, from the following stack:

```
Nov 01 09:05:59 staging1-3 sidekiq[37423]: Connecting to redis: /sidekiq-7.0.0/lib/sidekiq/config.rb:132:in `new_redis_pool'
Nov 01 09:05:59 staging1-3 sidekiq[37423]: Connecting to redis: /sidekiq-7.0.0/lib/sidekiq/config.rb:126:in `local_redis_pool'
Nov 01 09:05:59 staging1-3 sidekiq[37423]: Connecting to redis: /sidekiq-7.0.0/lib/sidekiq/config.rb:120:in `redis_pool'
Nov 01 09:05:59 staging1-3 sidekiq[37423]: Connecting to redis: /sidekiq-7.0.0/lib/sidekiq/client.rb:55:in `initialize'
Nov 01 09:05:59 staging1-3 sidekiq[37423]: Connecting to redis: /sidekiq-pro-7.0.0/lib/sidekiq/pro/push.rb:91:in `new'
Nov 01 09:05:59 staging1-3 sidekiq[37423]: Connecting to redis: /sidekiq-pro-7.0.0/lib/sidekiq/pro/push.rb:91:in `reliable_push!'
```


Our sidekiq initializer used to look like:

```ruby
Sidekiq::Client.reliable_push! unless Rails.env.test?
Sidekiq::Enterprise.unique! unless Rails.env.test?

Sidekiq.configure_client do |config|
  config.redis = redis_config
end

Sidekiq.configure_server do |config|
  config.redis = redis_config

  # ... bunch of other config
end
```

but in 7.x, `reliable_push!` would try to connect to redis before it's been configured. I've moved the redis configuration to the very top of the file to avoid it.

**Comment by jules-w2** [comment]
Hey,

I'm not sur if it's the same issue but with some specific gems update, the restart process doesn't work

````
[2062625] + Gemfile in context: /srv/apps/production/myapp/releases/20221117151740/Gemfile
2022-11-17T15:47:08.841Z pid=2062625 tid=18875 INFO: Running in ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
2022-11-17T15:47:08.841Z pid=2062625 tid=18875 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2022-11-17T15:47:08.841Z pid=2062625 tid=18875 INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2022-11-17T15:47:08.841Z pid=2062625 tid=18875 INFO: Sidekiq 7.0.1 connecting to Redis with options {:db=>21, :size=>5, :pool_name=>"internal", :url=>nil}
2022-11-17T15:47:08.843Z pid=2062625 tid=188px INFO: Sidekiq 7.0.1 connecting to Redis with options {:db=>21, :size=>2, :pool_name=>"default", :url=>nil}
2022-11-17T15:47:08.843Z pid=2062625 tid=188qh INFO: Sidekiq 7.0.1 connecting to Redis with options {:db=>21, :size=>2, :pool_name=>"default", :url=>nil}
2022-11-17T15:47:09.043Z pid=2062625 tid=18875 INFO: Sidekiq running embedded, total process thread count: 6
[2062625] ! Unable to start worker
[2062625] You have already activated timeout 0.1.0, but your Gemfile requires timeout 0.3.0. Since timeout is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports timeout as a default gem.
````
