### ISSUE TITLE
Sidekiq 7 + Semantic Logger Errors in Test Suite

### ISSUE THREAD

**Issue by Petercopter** [mperham/sidekiq#5607]
When running Sidekiq 7 + Semantic Logger, the Rspec test suite errors.

Ruby version: 3.1.2
Rails version: 7.0.4
Sidekiq version: 7.0

### initializer
```
Sidekiq.configure_client do |config|
  config.redis = { ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } }
end

Sidekiq.configure_server do |config|
  config.redis = { ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } }
end
```

Getting this error when running the test suite:
```
❯ bundle exec rspec

An error occurred while loading ./spec/channels/customers/notifications_channel_spec.rb.
Failure/Error: require File.expand_path('../config/environment', __dir__)

NoMethodError:
  undefined method `logger=' for Sidekiq:Module

        Sidekiq.logger       = SemanticLogger[Sidekiq] if defined?(Sidekiq)
               ^^^^^^^^^^^^^^^
  Did you mean?  logger
# ./config/environment.rb:5:in `<top (required)>'
# ./spec/rails_helper.rb:5:in `require'
# ./spec/rails_helper.rb:5:in `<top (required)>'
# ./spec/channels/customers/notifications_channel_spec.rb:1:in `require'
# ./spec/channels/customers/notifications_channel_spec.rb:1:in `<top (required)>'
```

I've also submitted a ticket on the semantic_logger repo: https://github.com/reidmorrison/semantic_logger/issues/243

**Comment by mperham** [comment]
semantic_logger needs to adjust their code to support Sidekiq 7.0. You can find the default logger at `Sidekiq.default_configuration.logger` or 

```ruby
Sidekiq.configure_{client,server,embed} do |config|
  config.logger = ...
```

**Comment by Petercopter** [comment]
Thank you! 👍
