### ISSUE TITLE
Sidekiq 7.0 - no implicit conversion of ConnectionPool into Hash

### ISSUE THREAD

**Issue by spenrose** [mperham/sidekiq#5608]
Getting `no implicit conversion of ConnectionPool into Hash` exception when trying to use a ConnectionPool with redis. We have been using the setup below for past versions and the documentation looks like this should work. https://github.com/mperham/sidekiq/wiki/Using-Redis#complete-control. There is probably something simple I am missing in a change in how this is configured.

Ruby version: 3.1.2
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 7.0.0

```yml
# sidekiq.yml

:concurrency: 10
:queues:
  - ["default", 2]

staging: &staging
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 20 %>

production:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 20 %>
```

```ruby
# config/initializers/sidekiq.rb

redis_conn = proc {
  Redis.new(url: ENV.fetch('REDIS_URL', nil), network_timeout: 5, namespace: 'sidekiq')
}

Sidekiq.configure_server do |config|
  config.redis = ConnectionPool.new(size: Sidekiq.default_configuration[:concurrency] + 5, &redis_conn)
end

Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(size: 5, &redis_conn)
end
```

backtrace
```
2022-10-31T18:24:21.281Z pid=1 tid=3gh INFO: Sidekiq 7.0.0 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>nil}
no implicit conversion of ConnectionPool into Hash
/usr/local/bundle/gems/sidekiq-7.0.0/lib/sidekiq/config.rb:116:in `merge'
/usr/local/bundle/gems/sidekiq-7.0.0/lib/sidekiq/config.rb:116:in `redis='
/app/config/initializers/sidekiq.rb:10:in `block in <main>'
/usr/local/bundle/gems/sidekiq-7.0.0/lib/sidekiq.rb:98:in `configure_server'
/app/config/initializers/sidekiq.rb:9:in `<main>'
/usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:667:in `load'
/usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:667:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/notifications.rb:208:in `instrument'
/usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:666:in `load_config_initializer'
/usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:619:in `each'
/usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:619:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/3.1.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/3.1.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:50:in `each'
/usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/local/lib/ruby/3.1.0/tsort.rb:415:in `call'
/usr/local/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
/usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-7.0.4/lib/rails/application.rb:372:in `initialize!'
/app/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/sidekiq-7.0.0/lib/sidekiq/cli.rb:301:in `require'
/usr/local/bundle/gems/sidekiq-7.0.0/lib/sidekiq/cli.rb:301:in `boot_application'
/usr/local/bundle/gems/sidekiq-7.0.0/lib/sidekiq/cli.rb:42:in `run'
/usr/local/bundle/gems/sidekiq-7.0.0/bin/sidekiq:31:in `<top (required)>'
/usr/local/bundle/bin/sidekiq:25:in `load'
/usr/local/bundle/bin/sidekiq:25:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli.rb:486:in `exec'
/usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli.rb:31:in `dispatch'
/usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli.rb:25:in `start'
/usr/local/bundle/gems/bundler-2.3.22/exe/bundle:48:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.3.22/exe/bundle:36:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
```

**Comment by mperham** [comment]
You can completely remove your initializer and it should just work.

**Comment by spenrose** [comment]
@mperham Awesome, got it working. Thanks for the advice.
