### ISSUE TITLE
Configuring Redis on Sidekiq 7.0 falls back to localhost

### ISSUE THREAD

**Issue by leifg** [mperham/sidekiq#5609]
Just upgraded to Sidekiq 7.0 and it seems like my redis configuration gets ignored.

This is the initializer that I am using:

```ruby
# config/initializers/sidekiq.rb
require "sidekiq"
redis = { url: "redis://redis:6379/1" }

Sidekiq.configure_server do |config|
  config.redis = redis
end

Sidekiq.configure_client do |config|
  config.redis = redis
end
```

On startup I get this error:

```shell
2022-10-31T18:42:40.145Z pid=1 tid=59h INFO: Sidekiq 7.0.0 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>nil}
2022-10-31T18:42:43.875Z pid=1 tid=59h INFO: Booted Rails 7.0.4 application in development environment
2022-10-31T18:42:43.876Z pid=1 tid=59h INFO: Running in ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
2022-10-31T18:42:43.876Z pid=1 tid=59h INFO: Sidekiq Pro 7.0.0 / Sidekiq Enterprise 7.0.0, commercially licensed.
Cannot assign requested address - connect(2) for [::1]:6379
/usr/local/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock'
/usr/local/lib/ruby/3.1.0/socket.rb:1214:in `connect_nonblock'
/usr/local/lib/ruby/3.1.0/socket.rb:56:in `connect_internal'
/usr/local/lib/ruby/3.1.0/socket.rb:137:in `connect'
/usr/local/lib/ruby/3.1.0/socket.rb:642:in `block in tcp'
/usr/local/lib/ruby/3.1.0/socket.rb:227:in `each'
/usr/local/lib/ruby/3.1.0/socket.rb:227:in `foreach'
/usr/local/lib/ruby/3.1.0/socket.rb:632:in `tcp'
/gems/ruby/3.1.0/gems/redis-client-0.10.0/lib/redis_client/ruby_connection.rb:49:in `initialize'
/gems/ruby/3.1.0/gems/redis-client-0.10.0/lib/redis_client.rb:654:in `new'
/gems/ruby/3.1.0/gems/redis-client-0.10.0/lib/redis_client.rb:654:in `block in connect'
/gems/ruby/3.1.0/gems/redis-client-0.10.0/lib/redis_client/middlewares.rb:12:in `connect'
/gems/ruby/3.1.0/gems/redis-client-0.10.0/lib/redis_client.rb:653:in `connect'
/gems/ruby/3.1.0/gems/redis-client-0.10.0/lib/redis_client.rb:647:in `raw_connection'
/gems/ruby/3.1.0/gems/redis-client-0.10.0/lib/redis_client.rb:614:in `ensure_connected'
/gems/ruby/3.1.0/gems/redis-client-0.10.0/lib/redis_client.rb:198:in `call'
/gems/ruby/3.1.0/gems/sidekiq-7.0.0/lib/sidekiq/redis_client_adapter.rb:13:in `info'
/gems/ruby/3.1.0/gems/sidekiq-7.0.0/lib/sidekiq/config.rb:137:in `block in redis_info'
/gems/ruby/3.1.0/gems/sidekiq-7.0.0/lib/sidekiq/config.rb:156:in `block in redis'
/gems/ruby/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
/gems/ruby/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
/gems/ruby/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
/gems/ruby/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
/gems/ruby/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
/gems/ruby/3.1.0/gems/sidekiq-7.0.0/lib/sidekiq/config.rb:153:in `redis'
/gems/ruby/3.1.0/gems/sidekiq-7.0.0/lib/sidekiq/config.rb:136:in `redis_info' 
/gems/ruby/3.1.0/gems/sidekiq-7.0.0/lib/sidekiq/cli.rb:75:in `run'
/gems/ruby/3.1.0/gems/sidekiq-7.0.0/bin/sidekiq:31:in `<top (required)>'
/gems/ruby/3.1.0/bin/sidekiq:25:in `load'
/gems/ruby/3.1.0/bin/sidekiq:25:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.3.16/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.3.16/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.3.16/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.3.16/lib/bundler/cli.rb:479:in `exec'
/usr/local/bundle/gems/bundler-2.3.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.3.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.3.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.3.16/lib/bundler/cli.rb:31:in `dispatch'
/usr/local/bundle/gems/bundler-2.3.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.3.16/lib/bundler/cli.rb:25:in `start'
/usr/local/bundle/gems/bundler-2.3.16/exe/bundle:48:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.3.16/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.3.16/exe/bundle:36:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
```

It seems like on startup the url is set to `nil` and therefore assuming localhost.

Ruby version: 3.1.2
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): Enterprise

**Comment by mperham** [comment]
See #5606 I think?

**Comment by leifg** [comment]
Makes sense. Thank you!
