### ISSUE TITLE
Sidekiq::Limiter raises RedisClient::ReadTimeoutError in 7.x

### ISSUE THREAD

**Issue by jdelStrother** [mperham/sidekiq#5611]
Ruby version: 3.1.2
Rails version: 7.0
Sidekiq / Pro / Enterprise version(s): 7.0.0

In 7.x (presumably due to differences in redis-rb vs redis-client), Sidekiq::Limiter can raise RedisClient::ReadTimeoutErrors instead of Sidekiq::Limiter::OverLimit.

In one process:

```ruby
l = Sidekiq::Limiter.concurrent("bucket-test", 1, wait_timeout: 5)
l.within_limiter { sleep 500 }
```

and another:

```ruby
l = Sidekiq::Limiter.concurrent("bucket-test", 1, wait_timeout: 5)
l.within_limiter {  }
```

the latter will raise in brpoplpush- 

```
#<RedisClient::ReadTimeoutError: RedisClient::ReadTimeoutError>
$GEMS/redis-client-0.10.0/lib/redis_client/ruby_connection/buffered_io.rb:140:in `block in fill_buffer'
$GEMS/redis-client-0.10.0/lib/redis_client/ruby_connection/buffered_io.rb:122:in `loop'
$GEMS/redis-client-0.10.0/lib/redis_client/ruby_connection/buffered_io.rb:122:in `fill_buffer'
$GEMS/redis-client-0.10.0/lib/redis_client/ruby_connection/buffered_io.rb:114:in `ensure_remaining'
$GEMS/redis-client-0.10.0/lib/redis_client/ruby_connection/buffered_io.rb:85:in `getbyte'
$GEMS/redis-client-0.10.0/lib/redis_client/ruby_connection/resp3.rb:113:in `parse'
$GEMS/redis-client-0.10.0/lib/redis_client/ruby_connection/resp3.rb:50:in `load'
$GEMS/redis-client-0.10.0/lib/redis_client/ruby_connection.rb:123:in `read'
$GEMS/redis-client-0.10.0/lib/redis_client/connection_mixin.rb:18:in `call'
$GEMS/redis-client-0.10.0/lib/redis_client.rb:200:in `block (2 levels) in call'
$GEMS/redis-client-0.10.0/lib/redis_client/middlewares.rb:16:in `call'
$GEMS/redis-client-0.10.0/lib/redis_client.rb:199:in `block in call'
$GEMS/redis-client-0.10.0/lib/redis_client.rb:616:in `ensure_connected'
$GEMS/redis-client-0.10.0/lib/redis_client.rb:198:in `call'
$GEMS/sidekiq-7.0.0/lib/sidekiq/redis_client_adapter.rb:25:in `method_missing'
$GEMS/sidekiq-ent-7.0.0/lib/sidekiq-ent/limiter/concurrent.rb:199:in `block in lock'
$GEMS/sidekiq-ent-7.0.0/lib/sidekiq-ent/limiter.rb:90:in `block in redis'
$GEMS/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
$GEMS/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
$GEMS/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
$GEMS/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
$GEMS/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
$GEMS/sidekiq-ent-7.0.0/lib/sidekiq-ent/limiter.rb:87:in `redis'
$GEMS/sidekiq-ent-7.0.0/lib/sidekiq-ent/limiter/concurrent.rb:194:in `lock'
$GEMS/sidekiq-ent-7.0.0/lib/sidekiq-ent/limiter/concurrent.rb:61:in `within_limit'
 "(irb):6:in `<main>'
```

In 6.x, this would be a Sidekiq::Limiter::OverLimit exception, which is useful for filtering out of error-reporting.

**Comment by mperham** [comment]
thank you, will be fixed in 7.0.1.

**Comment by moenodedev** [comment]
Is this bug in sidekiq core or enterprise?

Until 7.0.1 is released would it work to use `gem 'sidekiq', git: 'https://github.com/mperham/sidekiq'` in Gemfile?

**Comment by mperham** [comment]
It’s in Ent. 701 tomorrow morning.

**Comment by moenodedev** [comment]
Thanks!

We downgraded sidekiq for now.

```ruby
source "https://enterprise.contribsys.com" do
  gem "sidekiq-ent", "~> 2.5"
  gem "sidekiq-pro", "~> 5.5"
end

gem "sidekiq", "~> 6.0"
```
