### ISSUE TITLE
Sidekiq 7 with Documented Redis Config throws error

### ISSUE THREAD

**Issue by adampal** [mperham/sidekiq#5627]
Ruby version: ruby 3.0.3p157
Rails version: Rails 7.0.4
Sidekiq / Pro / Enterprise version(s): sidekiq 7.0.1

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

I'm trying to use the Redis config method documented here:
https://github.com/mperham/sidekiq/wiki/Using-Redis#complete-control

But getting the error: `no implicit conversion of ConnectionPool into Hash` when I try to start Sidekiq.

It only happens when using Sidekq 7.  Sidekiq 6 works perfectly.

initializers/sidekiq.rb
```
class ScoutApmSampling
  def call(worker, job, queue)
    sample_rate = 0.5
    random_number = rand
    if random_number > sample_rate
      req = ScoutApm::RequestManager.lookup
      req.start_layer(ScoutApm::Layer.new("invalid-layer", "should-ignore"))
      Rails.logger.info("Dropping the Sidekiq transaction for Scout because #{random_number} > #{sample_rate}")
    else
      Rails.logger.info("Sending the Sidekiq transaction to Scout because #{random_number} < #{sample_rate}")
    end
    yield
    req&.ignore_request!
  end
end

redis_conn = proc {
  Redis.new(
    url: ENV["REDIS_URL"] || "redis://localhost:6379",
    driver: :ruby,
    ssl_params: {verify_mode: OpenSSL::SSL::VERIFY_NONE}
  )
}

Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(size: 5, &redis_conn)
end

Sidekiq.configure_server do |config|
  config.redis = ConnectionPool.new(size: 25, &redis_conn)
  config.server_middleware do |chain|
    chain.insert_after ScoutApm::BackgroundJobIntegrations::SidekiqMiddleware, ScoutApmSampling
  end
end
```

config/sidekiq.yml
```
:concurrency: 5
staging:
  :concurrency: 5
production:
  :concurrency: 5
:queues:
  - critical
  - default
  - mailers
  - low
  - action_mailbox_routing

```

Full stack trace when starting Sidekiq:

```
no implicit conversion of ConnectionPool into Hash
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.1/lib/sidekiq/config.rb:116:in `merge'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.1/lib/sidekiq/config.rb:116:in `redis='
/Users/adampallozzi/Code/cpap/sleephq/config/initializers/sidekiq.rb:32:in `block in <main>'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.1/lib/sidekiq.rb:98:in `configure_server'
/Users/adampallozzi/Code/cpap/sleephq/config/initializers/sidekiq.rb:30:in `<main>'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/engine.rb:667:in `load'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/engine.rb:667:in `block in load_config_initializer'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:208:in `instrument'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/engine.rb:666:in `load_config_initializer'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/engine.rb:619:in `each'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/engine.rb:619:in `block in <class:Engine>'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `instance_exec'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `run'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/initializable.rb:50:in `each'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/initializable.rb:50:in `tsort_each_child'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:415:in `call'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:415:in `each_strongly_connected_component_from'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `each'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `call'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/initializable.rb:60:in `run_initializers'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/application.rb:372:in `initialize!'
/Users/adampallozzi/Code/cpap/sleephq/config/environment.rb:5:in `<top (required)>'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.1/lib/sidekiq/cli.rb:301:in `require'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.1/lib/sidekiq/cli.rb:301:in `boot_application'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.1/lib/sidekiq/cli.rb:42:in `run'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sidekiq-7.0.1/bin/sidekiq:31:in `<top (required)>'
/Users/adampallozzi/.rbenv/versions/3.0.3/bin/sidekiq:25:in `load'
/Users/adampallozzi/.rbenv/versions/3.0.3/bin/sidekiq:25:in `<top (required)>'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:478:in `exec'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:25:in `start'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:49:in `block in <top (required)>'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/Users/adampallozzi/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:37:in `<top (required)>'
/Users/adampallozzi/.rbenv/versions/3.0.3/bin/bundle:23:in `load'
/Users/adampallozzi/.rbenv/versions/3.0.3/bin/bundle:23:in `<main>'
```

**Comment by mperham** [comment]
Yep. 7 no longer allows you to supply a connection pool. Need to update the wiki.

**Comment by adampal** [comment]
Thanks @mperham. Is there an equivalent way to set the connection pool size in 7?

**Comment by mperham** [comment]
Nope, Sidekiq auto sizes pools for you.

**Comment by bf4** [comment]
Close as invalid?

Side note, I recommend you set all your defaults in Sidekiq 7 on the `Sidekiq.default_configuration` object

e.g.

```diff
+ Sidekiq.default_configuration.redis = redis_config
+ Sidekiq.default_configuration.logger = sidekiq_logger
- Sidekiq.configure_client do |config|
-   config.redis = redis_config
-   config.logger = sidekiq_logger
- end
- Sidekiq.configure_server do |config|
-   config.redis = redis_config
-   config.logger = sidekiq_logger
- end
```

That way your default sidekiq config, such as used in `Sidekiq::Deploy.mark!(application_version)` is the same as what's configured for the server and client.

(You don't have to remove the Sidekiq.configure_client/Sidekiq.configure_server in the above diff, but you'll likely need to add the `Sidekiq.default_configuration.redis = redis_config` for  your `Sidekiq::Deploy` to work since that will just look at the REDIS_URL or whatever and not see, say `ssl_params: {verify_mode: OpenSSL::SSL::VERIFY_NONE}`

**Comment by adampal** [comment]
@bf4 could you elaborate on 
> but you'll likely need to add the Sidekiq.default_configuration.redis = redis_config for your Sidekiq::Deploy to work

I'm not sure what the `Sidekiq::Deploy` class is or why this would be an issue.

**Comment by bf4** [comment]
I think that misses the point. 1) Mike said not to https://github.com/mperham/sidekiq/wiki/Using-Redis#complete-control any more 2) I said, when you do that, make sure you set your redis on the Sidekiq.default_configuration in addition to the configure blocks.

**Comment by abdul-wahab-qbatch** [comment]
Will it affect my sidekiq performance means how it is going to pick the poolsize

**Comment by wahabmangat** [comment]
Will it affect my sidekiq performance means how it is going to pick the poolsize? I have deployed the sidekiq on kubernetes pods and have various thread sizes for each pod.
