### ISSUE TITLE
TypeError: no _dump_data is defined for class Proc when using ConnectionPool

### ISSUE THREAD

**Issue by IanVaughan** [mperham/sidekiq#5670]
Ruby version: `3.1.2p20`
Rails version: `6.1.6.1`
Sidekiq / Pro / Enterprise version(s): `6.5.8`

When using a `ConnectionPool` as per the example https://github.com/mperham/sidekiq/wiki/Using-Redis#complete-control

```
redis_conn = proc {
  Redis.new # do anything you want here
}

Sidekiq.configure_client do |config|
  config.redis = { url: ConnectionPool.new(size: 5, &redis_conn) }
end

Sidekiq.configure_server do |config|
  config.redis = { url: ConnectionPool.new(size: 25, &redis_conn) }
end
```

I get this error:
```
2022-11-28T10:55:42.864Z pid=18528 tid=k0s WARN: TypeError: no _dump_data is defined for class Proc
2022-11-28T10:55:42.864Z pid=18528 tid=k0s WARN: /Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/redis_connection.rb:132:in `dump'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/redis_connection.rb:132:in `log_info'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/redis_connection.rb:103:in `create'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq.rb:205:in `redis='
/Users/ian/out-fund/core-app/config/initializers/sidekiq.rb:20:in `block in <main>'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq.rb:142:in `configure_server'
/Users/ian/out-fund/core-app/config/initializers/sidekiq.rb:12:in `<main>'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:326:in `load'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:326:in `block in load'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:326:in `load'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-6.1.6.1/lib/rails/engine.rb:681:in `block in load_config_initializer'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:205:in `instrument'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-6.1.6.1/lib/rails/engine.rb:680:in `load_config_initializer'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-6.1.6.1/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-6.1.6.1/lib/rails/engine.rb:633:in `each'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-6.1.6.1/lib/rails/engine.rb:633:in `block in <class:Engine>'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `instance_exec'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `run'
/Users/ian/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:61:in `block in run_initializers'

```

**Comment by mperham** [comment]
Someone edited that sample incorrectly. A ConnectionPool is not a URL. I've removed that section entirely as it doesn't work in Sidekiq 7.0 either.
