### ISSUE TITLE
Sidekiq Middleware Show Error Instead Actual Worker

### ISSUE THREAD

**Issue by dalezak** [mperham/sidekiq#5679]
I have a Sidekiq middleware to log the execution time of a worker, however if a worker has an exception, it shows the middleware was the class with the exception, not the actual worker.

```ruby
class SidekiqExecutionTime
  
  def call(worker, job, queue)
    start_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
    yield
    end_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
    queue_name = job['queue'].to_s
    worker_name = job['class'].to_s
    job_args = job['args'].to_a.join(", ")
    Sidekiq.logger.debug "Sidekiq worker #{worker_name} queue #{queue_name} time #{seconds_to_sentence(end_time - start_time)} args [#{job_args}]"
  end

  def seconds_to_sentence(secs)
    if secs > 1.0
      [[60, :seconds], [60, :minutes], [24, :hours], [1000, :days]].each_with_object([]){ |(count, name), s|
        if secs.positive?
          secs, n = secs.divmod(count)
          s.unshift "#{n.to_i} #{name}" if n.to_i.positive?
        end
      }.join(' ')
    else
      "#{secs.round(4)} seconds"
    end  
  end
end
```

How do you handle exceptions inside your middleware class, so they are not included at the top of the stacktrace?

**Comment by mperham** [comment]
I don't understand. Show me the error.

**Comment by dalezak** [comment]
Since the middleware is using `yield` to execute the worker, it shows the middleware as class having the exception.

<img width="548" alt="Screen Shot 2022-11-30 at 2 31 54 PM" src="https://user-images.githubusercontent.com/91811/204901959-0d78a82f-7c96-488f-b5b9-1d91c72ceb16.png">

So initially I thought the middleware was causing the problem, but its a network error but still confusing.

**Comment by mperham** [comment]
I don't want a screenshot. Cut and paste the full backtrace here.

**Comment by dalezak** [comment]
Ok, here's the full stack trace

```
gems/rest-client-2.1.0/lib/restclient/request.rb:749:in `rescue in transmit': Timed out connecting to server (RestClient::Exceptions::OpenTimeout)
    from gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
    from gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
    from gems/ddtrace-0.54.1/lib/ddtrace/contrib/rest_client/request_patch.rb:29:in `block in execute'
    from gems/ddtrace-0.54.1/lib/ddtrace/contrib/rest_client/request_patch.rb:55:in `datadog_trace_request'
    from gems/ddtrace-0.54.1/lib/ddtrace/contrib/rest_client/request_patch.rb:24:in `execute'
    from gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
    from gems/rest-client-2.1.0/lib/restclient.rb:70:in `post'
    from gems/vero-0.10.0/lib/vero/api/events/track_api.rb:13:in `request'
    from gems/vero-0.10.0/lib/vero/api/base_api.rb:26:in `perform'
    from gems/vero-0.10.0/lib/vero/senders/sidekiq.rb:11:in `perform'
    from gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:185:in `execute_job'
    from gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'
    from gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
    from gems/sidekiq-throttled-0.13.0/lib/sidekiq/throttled/middleware.rb:14:in `call'
    from gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from gems/core/config/initializers/sidekiq_bullet_profiler.rb:8:in `call'
    from gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from gems/core/config/initializers/sidekiq_execution_time.rb:5:in `call'
    from gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from gems/ddtrace-0.54.1/lib/ddtrace/contrib/sidekiq/server_tracer.rb:43:in `block in call'
    from gems/ddtrace-0.54.1/lib/ddtrace/tracer.rb:283:in `trace'
    from gems/ddtrace-0.54.1/lib/ddtrace/contrib/sidekiq/server_tracer.rb:24:in `call'
    from gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from gems/bugsnag-6.17.0/lib/bugsnag/integrations/sidekiq.rb:24:in `call'
    from gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from gems/sidekiq-unique-jobs-6.0.25/lib/sidekiq_unique_jobs/server/middleware.rb:29:in `call'
    from gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:133:in `invoke'
    from gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:166:in `block in process'
    from gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
    from gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:108:in `local'
    from gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
    from gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:43:in `block in call'
    from gems/activesupport-6.0.3.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
    from gems/activesupport-6.0.3.4/lib/active_support/reloader.rb:72:in `block in wrap'
    from gems/activesupport-6.0.3.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
    from gems/activesupport-6.0.3.4/lib/active_support/reloader.rb:71:in `wrap'
    from gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:42:in `call'
    from gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
    from gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:243:in `stats'
    from gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
    from gems/sidekiq-5.2.5/lib/sidekiq/job_logger.rb:8:in `call'
    from gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
    from gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:73:in `global'
    from gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:125:in `block in dispatch'
    from gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:48:in `with_context'
    from gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
    from gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:124:in `dispatch'
    from gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:165:in `process'
    from gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:83:in `process_one'
    from gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:71:in `run'
    from gems/sidekiq-5.2.5/lib/sidekiq/util.rb:16:in `watchdog'
    from gems/sidekiq-5.2.5/lib/sidekiq/util.rb:25:in `block in safe_thread'
  ```

**Comment by mperham** [comment]
I think your issue is poor DX in that page. It's showing you the code for the first line in the stacktrace that is *in your codebase*. Which happens to be a middleware since the job at fault is actually from a gem here: `gems/vero-0.10.0/lib/vero/senders/sidekiq.rb:11:in `perform'`

**Comment by mperham** [comment]
BTW Sidekiq 5 is no longer supported. You should upgrade ASAP.
