### ISSUE TITLE
ConnectionPool::TimeoutError possibly related to rate-limiting

### ISSUE THREAD

**Issue by geoffharcourt** [mperham/sidekiq#5685]
Ruby version: 3.1.3
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): Pro 7.0.3 / Sidekiq/Enterprise 7.0.2

This looks like it might be related to #5684. After the fix in Sidekiq 7.0.3 for the metrics connection pool, we stopped seeing exceptions in that location. However, we did see a smaller chunk of exceptions the night after the 7.0.3 patch where calling `within_limit` results in a `ConnectionPool::TimeoutError` where the timeout time and pool size again don't line up with our network timeout or concurrency settings. We're seeing this exception pop up in multiple different places, but always when we call `within_limit`. It's happening on bucket and concurrent rate limits.

We're using network timeout of 2s and a concurrency of 15, but the timeout says 1s and 0/5 threads.

**Please include your initializer, sidekiq.yml, and any error message with the full backtrace.**

Likely relevant parts of our initializer:

```ruby
shared_redis_config = {
  db: ENV["REDIS_DATABASE_NUMBER"].to_i,
  network_timeout: REDIS_NETWORK_TIMEOUT_SECONDS,
  ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE },
  url: ENV["REDIS_URL"],
}

Sidekiq::Limiter.configure do |config|
  config.redis = shared_redis_config
```

Backtrace:

```
ConnectionPool::TimeoutError: Waited 1 sec, 0/5 available
  from connection_pool (2.3.0) lib/connection_pool/timed_stack.rb:77:in `block (2 levels) in pop'
  from connection_pool (2.3.0) lib/connection_pool/timed_stack.rb:69:in `loop'
  from connection_pool (2.3.0) lib/connection_pool/timed_stack.rb:69:in `block in pop'
  from connection_pool (2.3.0) lib/connection_pool/timed_stack.rb:68:in `synchronize'
  from connection_pool (2.3.0) lib/connection_pool/timed_stack.rb:68:in `pop'
  from connection_pool (2.3.0) lib/connection_pool.rb:80:in `checkout'
  from connection_pool (2.3.0) lib/connection_pool.rb:62:in `block in with'
  from connection_pool (2.3.0) lib/connection_pool.rb:61:in `handle_interrupt'
  from connection_pool (2.3.0) lib/connection_pool.rb:61:in `with'
  from sidekiq-ent (7.0.2) lib/sidekiq-ent/scripting.rb:20:in `call'
  from sidekiq-ent (7.0.2) lib/sidekiq-ent/limiter/concurrent.rb:188:in `lock'
  from sidekiq-ent (7.0.2) lib/sidekiq-ent/limiter/concurrent.rb:61:in `within_limit'
  from app/services/translate.rb:12:in `process'
  from app/workers/translate_workers/lesson_template_worker.rb:22:in `translate_content'
  from app/workers/translate_workers/lesson_template_worker.rb:11:in `perform'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:206:in `execute_job'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:174:in `block (2 levels) in process'
  from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:175:in `block in invoke'
  from prometheus_exporter (2.0.6) lib/prometheus_exporter/instrumentation/sidekiq.rb:53:in `call'
  from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
  from sidekiq-pro (7.0.3) lib/sidekiq/middleware/server/statsd.rb:40:in `call'
  from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
  from sidekiq-pro (7.0.3) lib/sidekiq/pro/expiry.rb:37:in `call'
  from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
  from ddtrace (1.7.0) lib/datadog/tracing/contrib/sidekiq/server_tracer.rb:69:in `block in call'
  from ddtrace (1.7.0) lib/datadog/tracing/trace_operation.rb:193:in `block in measure'
  from ddtrace (1.7.0) lib/datadog/tracing/span_operation.rb:151:in `measure'
  from ddtrace (1.7.0) lib/datadog/tracing/trace_operation.rb:193:in `measure'
  from ddtrace (1.7.0) lib/datadog/tracing/tracer.rb:382:in `start_span'
  from ddtrace (1.7.0) lib/datadog/tracing/tracer.rb:162:in `block in trace'
  from ddtrace (1.7.0) lib/datadog/tracing/context.rb:45:in `activate!'
  from ddtrace (1.7.0) lib/datadog/tracing/tracer.rb:161:in `trace'
  from ddtrace (1.7.0) lib/datadog/tracing.rb:18:in `trace'
  from ddtrace (1.7.0) lib/datadog/tracing/contrib/sidekiq/server_tracer.rb:32:in `call'
  from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
  from sentry-sidekiq (5.7.0) lib/sentry/sidekiq/sentry_context_middleware.rb:26:in `call'
  from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
  from sidekiq-pro (7.0.3) lib/sidekiq/batch/middleware.rb:58:in `call'
  from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
  from sidekiq-ent (7.0.2) lib/sidekiq-ent/unique.rb:154:in `call'
  from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
  from sidekiq-ent (7.0.2) lib/sidekiq-ent/limiter/middleware.rb:39:in `call'
  from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
  from sidekiq (7.0.2) lib/sidekiq/metrics/tracking.rb:24:in `track'
  from sidekiq (7.0.2) lib/sidekiq/metrics/tracking.rb:120:in `call'
  from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
  from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:180:in `invoke'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:173:in `block in process'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
  from sidekiq (7.0.2) lib/sidekiq/job_retry.rb:113:in `local'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
  from sidekiq (7.0.2) lib/sidekiq/rails.rb:15:in `block in call'
  from activesupport (7.0.4) lib/active_support/execution_wrapper.rb:92:in `wrap'
  from activesupport (7.0.4) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (7.0.4) lib/active_support/execution_wrapper.rb:92:in `wrap'
  from activesupport (7.0.4) lib/active_support/reloader.rb:71:in `wrap'
  from sidekiq (7.0.2) lib/sidekiq/rails.rb:14:in `call'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:267:in `stats'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
  from sidekiq (7.0.2) lib/sidekiq/job_logger.rb:13:in `call'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
  from sidekiq (7.0.2) lib/sidekiq/job_retry.rb:80:in `global'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:128:in `block in dispatch'
  from sidekiq (7.0.2) lib/sidekiq/job_logger.rb:39:in `prepare'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:127:in `dispatch'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:172:in `process'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:82:in `process_one'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:72:in `run'
  from sidekiq (7.0.2) lib/sidekiq/component.rb:8:in `watchdog'
  from sidekiq (7.0.2) lib/sidekiq/component.rb:17:in `block in safe_thread'
```

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version? - We are on the newest releases of Sidekiq libraries.

**Comment by BobbyMcWho** [comment]
It looks like w/ the rate limiter, when you call `config.redis =`, it creates a new `Sidekiq::RedisConnection` (lib/sidekiq-ent/limiter.rb:81), and passes your shared_redis_config in as the options to `.create` [ref](https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/redis_connection.rb#L10). 

sidekiq-ent should _probably_ be aware of the configured capsule config when creating its connection pool, but for now, you could pass `:pool_timeout` and `size` keys in your config block

```ruby
Sidekiq::Limiter.configure do |config|
  config.redis = shared_redis_config.merge(pool_timeout: 2, size: Sidekiq.total_concurrency) # all capsules vs Sidekiq.concurrency which is only default capsule
   # ...
 end
```

**Comment by geoffharcourt** [comment]
Removing the distinct setting of Redis for the server/client/limiter blocks and setting `Sidekiq.default_configuration.redis` appeared to make this issue go away with the limiter. Thanks everyone for the help!
