### ISSUE TITLE
Reliable push local queueing not working within a Sidekiq Job

### ISSUE THREAD

**Issue by gmcabrita** [mperham/sidekiq#5698]
Ruby version: 3.1.3
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): Sidekiq 7.0.2 / Pro 7.0.4

It seems that local queueing is not working correctly when pushing a job from within a Sidekiq job. It appears `:backup_limit` is not automatically configured.

This works without issue when doing it from the Rails side as the default of `1_000` is applied correctly there.

Backtrace:
```
error: comparison of Integer with nil failed
  /usr/local/bundle/gems/sidekiq-pro-7.0.4/lib/sidekiq/pro/push.rb:78:in `>'
  /usr/local/bundle/gems/sidekiq-pro-7.0.4/lib/sidekiq/pro/push.rb:78:in `save_locally'
  /usr/local/bundle/gems/sidekiq-pro-7.0.4/lib/sidekiq/pro/push.rb:48:in `rescue in raw_push'
  /usr/local/bundle/gems/sidekiq-pro-7.0.4/lib/sidekiq/pro/push.rb:39:in `raw_push'
  /usr/local/bundle/gems/sidekiq-7.0.2/lib/sidekiq/client.rb:92:in `push'
  /usr/local/bundle/gems/sidekiq-7.0.2/lib/sidekiq/job.rb:365:in `client_push'
  /usr/local/bundle/gems/sidekiq-7.0.2/lib/sidekiq/job.rb:198:in `perform_async'
  /usr/local/bundle/gems/sidekiq-7.0.2/lib/sidekiq/job.rb:290:in `perform_async'
```

**Comment by mperham** [comment]
To work around, try adding this to your initializer:

```ruby
Sidekiq.default_configuration[:backup_limit] = 1_000
```

I'll get this fixed in the next patch release.
