### ISSUE TITLE
NameError: uninitialized constant Fire::PushJob

### ISSUE THREAD

**Issue by rttll** [mperham/sidekiq#5710]
Ruby version: 3.0.4
Rails version: '~> 7.0'
Sidekiq / Pro / Enterprise version(s): 6.5.7

Hey guys, cannot figure this out. 
This is a development-only bug. Everything works fine in production.

Running this in a controller:

`Fire::PushJob.perform_async(type, show_id)`

The job is created, but throws this error:

`NameError: uninitialized constant Fire::PushJob`

This happens for all jobs in the app, in development only.

After a few retries it will eventually work. 
There is no trace, not even sure where the error is coming from. Is this Sidekiq not finding the job?

I don't have an initializer or anything in dev. Is this part of the issue? I don't see anything about config in the docs except for the redis server...

Thanks

edit:  I enabled the backtrace: 

```
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:282:in `block in constantize'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:279:in `each'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:279:in `inject'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:279:in `constantize'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:132:in `block (5 levels) in dispatch'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/rails.rb:14:in `block in call'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-7.0.4/lib/active_support/reloader.rb:72:in `block in wrap'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-7.0.4/lib/active_support/reloader.rb:71:in `wrap'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/rails.rb:13:in `call'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:263:in `stats'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/job_logger.rb:13:in `call'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/job_retry.rb:80:in `global'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:124:in `block in dispatch'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/job_logger.rb:39:in `prepare'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:123:in `dispatch'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:168:in `process'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:78:in `process_one'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:68:in `run'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/component.rb:8:in `watchdog'
.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/component.rb:17:in `block in safe_thread'

```

**Comment by liijunwei** [comment]
just a clue: check whether you started multiple sidekiq processes, there is a chance that you started more than one sidekiq process, and forgot about the old ones, which are running the outdated code

**Comment by rttll** [comment]
@liijunwei 

The output is expected, only one process. 

I do often run two sites in dev at the same time, which both run sidekiq.
