### ISSUE TITLE
deliver_later ActionMailer's method throws a `No passed or active session` error

### ISSUE THREAD

**Issue by BaggioGiacomo** [mperham/sidekiq#5750]
Ruby version: 3.1.2p20
Rails version: 7.0.3
Sidekiq / Pro / Enterprise version(s): 6.5.7

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

```
 //sidekiq.yml 

:queues:
  - default

```

I'm creating a Shopify app using the rails template and using Sidekiq as queue manager.
I have a Rake task that foreach shop enqueues a job. This job, after some checks, will sent an email to the merchant.
Here's my rake task:

```
desc 'Check customers count near to exceed the limit'

task check_customers_limits: :environment do
  Shop.find_each do |shop|
    CheckCustomersCountLimitJob.perform_later(shop: shop)
  end
end
```

Here's the job:
```
class CheckCustomersCountLimitJob < ApplicationJob
  queue_as :default

  def perform(shop:)
    shop.verify_billing_status
  end
end
```

This is the `verify_billing_status` method:
```
def verify_billing_status
    self.with_shopify_session do
      should_notify_merchant =
        plan.present? && !plan.unlimited? &&
          customers_count >=
            (plan.max_customers_count * CUSTOMER_COUNT_WARNING_THRESHOLD) &&
          self.billing_status_ok?

      if should_notify_merchant
        begin
          BillingMailer.customers_count_approaching_plan_limit(shop: self)
            .deliver_now
        rescue => e
          puts "Cannot send customers_count_approaching_plan_limit email for shop: #{self.shopify_domain}. \n\nError: #{e.message}"
        end
      end
    end
  end
```

What happens here? 
Using `deliver_now` works fine.
If I switch it with `deliver_later` i get the `No passed or active session` error.
Backtrace:
```
2023-01-27T13:49:16.322Z pid=66407 tid=4kb class=ActionMailer::MailDeliveryJob jid=010c9a1891da62f4bc00b751 INFO: start
2023-01-27T13:49:16.388Z pid=66407 tid=4kb class=ActionMailer::MailDeliveryJob jid=010c9a1891da62f4bc00b751 INFO: Performing ActionMailer::MailDeliveryJob (Job ID: 5a616621-2e88-4dcc-9f61-e02bf4b9e47f) from Sidekiq(default) enqueued at 2023-01-27T13:40:35Z with arguments: "BillingMailer", "customers_count_approaching_plan_limit", "deliver_now", {:args=>[{:shop=>#<GlobalID:0x000000010933a680 @uri=#<URI::GID gid://shopify-app-template-ruby/Shop/10>>}]}
2023-01-27T13:49:17.229Z pid=66407 tid=4kb class=ActionMailer::MailDeliveryJob jid=010c9a1891da62f4bc00b751 INFO:   Rendered billing_mailer/customers_count_approaching_plan_limit.html.erb within layouts/mailer (Duration: 430.6ms | Allocations: 16747)
2023-01-27T13:49:17.229Z pid=66407 tid=4kb class=ActionMailer::MailDeliveryJob jid=010c9a1891da62f4bc00b751 INFO:   Rendered layout layouts/mailer.html.erb (Duration: 430.8ms | Allocations: 16850)
2023-01-27T13:49:17.229Z pid=66407 tid=4kb class=ActionMailer::MailDeliveryJob jid=010c9a1891da62f4bc00b751 ERROR: Error performing ActionMailer::MailDeliveryJob (Job ID: 5a616621-2e88-4dcc-9f61-e02bf4b9e47f) from Sidekiq(default) in 887.5ms: ActionView::Template::Error (No passed or active session):
/Users/jack/.rvm/gems/ruby-3.1.2/gems/shopify_api-12.2.1/lib/shopify_api/clients/http_client.rb:14:in `initialize'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sorbet-runtime-0.5.10520/lib/types/private/methods/call_validation.rb:153:in `bind_call'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sorbet-runtime-0.5.10520/lib/types/private/methods/call_validation.rb:153:in `validate_call_skip_block_type'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sorbet-runtime-0.5.10520/lib/types/private/methods/call_validation.rb:95:in `block in create_validator_slow_skip_block_type'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/shopify_api-12.2.1/lib/shopify_api/clients/rest/admin.rb:12:in `initialize'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sorbet-runtime-0.5.10520/lib/types/private/methods/call_validation.rb:153:in `bind_call'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sorbet-runtime-0.5.10520/lib/types/private/methods/call_validation.rb:153:in `validate_call_skip_block_type'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sorbet-runtime-0.5.10520/lib/types/private/methods/call_validation.rb:95:in `block in create_validator_slow_skip_block_type'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/shopify_api-12.2.1/lib/shopify_api/rest/base.rb:184:in `new'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/shopify_api-12.2.1/lib/shopify_api/rest/base.rb:184:in `request'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sorbet-runtime-0.5.10520/lib/types/private/methods/call_validation.rb:153:in `bind_call'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sorbet-runtime-0.5.10520/lib/types/private/methods/call_validation.rb:153:in `validate_call_skip_block_type'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sorbet-runtime-0.5.10520/lib/types/private/methods/call_validation.rb:95:in `block in create_validator_slow_skip_block_type'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/shopify_api-12.2.1/lib/shopify_api/rest/resources/2022_10/customer.rb:211:in `count'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sorbet-runtime-0.5.10520/lib/types/private/methods/call_validation.rb:256:in `bind_call'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sorbet-runtime-0.5.10520/lib/types/private/methods/call_validation.rb:256:in `validate_call'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sorbet-runtime-0.5.10520/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/Users/jack/Documents/GitHub/amplius/web/app/models/shop.rb:47:in `rescue in customers_count'
/Users/jack/Documents/GitHub/amplius/web/app/models/shop.rb:40:in `customers_count'
/Users/jack/Documents/GitHub/amplius/web/app/views/billing_mailer/customers_count_approaching_plan_limit.html.erb:10:in `_app_views_billing_mailer_customers_count_approaching_plan_limit_html_erb___3306958506192865131_67380'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/base.rb:244:in `public_send'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/base.rb:244:in `_run'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/template.rb:157:in `block in render'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/notifications.rb:208:in `instrument'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/template.rb:361:in `instrument_render_template'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/template.rb:155:in `render'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:65:in `block (2 levels) in render_template'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:75:in `block in render_with_layout'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:74:in `render_with_layout'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:59:in `render_template'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:11:in `render'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/rendering.rb:117:in `block in _render_template'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/base.rb:270:in `in_rendering_context'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/rendering.rb:116:in `_render_template'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/rendering.rb:103:in `render_to_body'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionpack-7.0.3/lib/abstract_controller/rendering.rb:25:in `render'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/base.rb:992:in `block in collect_responses_from_templates'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/base.rb:989:in `each'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/base.rb:989:in `each'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/base.rb:989:in `map'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/base.rb:989:in `collect_responses_from_templates'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/base.rb:967:in `collect_responses'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/base.rb:875:in `mail'
/Users/jack/Documents/GitHub/amplius/web/app/mailers/billing_mailer.rb:4:in `customers_count_approaching_plan_limit'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionpack-7.0.3/lib/abstract_controller/base.rb:215:in `process_action'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionpack-7.0.3/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actiontext-7.0.3/lib/action_text/rendering.rb:20:in `with_renderer'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actiontext-7.0.3/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionpack-7.0.3/lib/abstract_controller/callbacks.rb:233:in `process_action'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionpack-7.0.3/lib/abstract_controller/base.rb:151:in `process'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/rescuable.rb:25:in `block in process'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/rescuable.rb:24:in `process'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionview-7.0.3/lib/action_view/rendering.rb:39:in `process'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/base.rb:646:in `block in process'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/base.rb:645:in `process'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/message_delivery.rb:128:in `block in processed_mailer'
<internal:kernel>:90:in `tap'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/message_delivery.rb:127:in `processed_mailer'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/actionmailer-7.0.3/lib/action_mailer/mail_delivery_job.rb:23:in `perform'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/execution.rb:59:in `block in _perform_job'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/Users/jack/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/i18n-1.12.0/lib/i18n.rb:322:in `with_locale'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/execution.rb:58:in `_perform_job'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/instrumentation.rb:20:in `_perform_job'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/execution.rb:46:in `perform_now'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/instrumentation.rb:14:in `block in perform_now'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/instrumentation.rb:25:in `block in instrument'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/instrumentation.rb:35:in `instrument'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/instrumentation.rb:14:in `perform_now'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/logging.rb:18:in `block in perform_now'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/tagged_logging.rb:114:in `block in tagged'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/tagged_logging.rb:38:in `tagged'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/tagged_logging.rb:114:in `tagged'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/logging.rb:25:in `tag_logger'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/logging.rb:18:in `perform_now'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/execution.rb:24:in `block in execute'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/execution_wrapper.rb:92:in `wrap'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/reloader.rb:72:in `block in wrap'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/execution_wrapper.rb:88:in `wrap'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/reloader.rb:71:in `wrap'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/execution.rb:22:in `execute'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activejob-7.0.3/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:202:in `execute_job'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/middleware/chain.rb:172:in `invoke'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:169:in `block in process'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/job_retry.rb:113:in `local'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/rails.rb:14:in `block in call'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/execution_wrapper.rb:92:in `wrap'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/reloader.rb:72:in `block in wrap'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/execution_wrapper.rb:92:in `wrap'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/reloader.rb:71:in `wrap'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/rails.rb:13:in `call'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:263:in `stats'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/job_logger.rb:13:in `call'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/job_retry.rb:80:in `global'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:124:in `block in dispatch'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/job_logger.rb:39:in `prepare'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:123:in `dispatch'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:168:in `process'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:78:in `process_one'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:68:in `run'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/component.rb:8:in `watchdog'
/Users/jack/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.7/lib/sidekiq/component.rb:17:in `block in safe_thread
```

What can be the cause of this?

Tell me if you need more details. 
Thanks in advance.

**Comment by BaggioGiacomo** [comment]
Bug founded!

The problem here was that the email layouts call a model method that fetches something from the Shopify API. Since we're in another thread, the session doesn't exist

How I have fixed?
I've wrapped the mailer like this:
```

shop.with_shopify_session do
  mail(to: ...., subject: ...)
end
```
