### ISSUE TITLE
Error running multiple rails apps on the same redis instance 

### ISSUE THREAD

**Issue by alexwebgr** [mperham/sidekiq#5753]
Ruby version: 3.1.2 (A), 3.2.0 (B) 
Rails version: 7.0
Sidekiq / Pro / Enterprise version(s): Free

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
```
Sidekiq.configure_server do |config|
  config.redis = { url: ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } }
end
```
```
---
:max_retries: 0
:concurrency: 5

production:
  :concurrency: 5
:queues:
  - critical
  - default
  - low
```
Procfile A
```
web: bundle exec rails server -p 7000
worker: bundle exec sidekiq -c 5 -v
```
Procfile B
```
web: bundle exec rails server -p 8000
worker: bundle exec sidekiq -c 5 -v
```

i have two apps running on sidekiq on a signle redis instance everything seems to be working fine but i am getting this error on the sidekiq dashboard and i am also getting NameError unitialized constant Classname errors from even though job finishes 
 
i start app A with foreman i navigate to /sidekiq all good
i start app B with foreman i navigate to /sidekiq all good and i see two process now one for the current app and one for app A
when i go back to app A /sidekiq/busy i get this error 
`undefined method 'join' for {"critical"=>0, "default"=>0, "low"=>0}:Hash`

if i start app B first and then app A i get the same error on app A sidekiq dashboard. it happens both locally and on the production server

```
Rails.root: unset
[Application Trace](http://localhost:7000/admin/sidekiq/busy#) | [Framework Trace](http://localhost:7000/admin/sidekiq/busy#) | [Full Trace](http://localhost:7000/admin/sidekiq/busy#)
sidekiq (7.0.2) lib/sidekiq/web/action.rb:122:in `block (2 levels) in _erb_busy'
sidekiq (7.0.2) lib/sidekiq/web/action.rb:122:in `map'
sidekiq (7.0.2) lib/sidekiq/web/action.rb:122:in `block in _erb_busy'
sidekiq (7.0.2) lib/sidekiq/web/action.rb:105:in `each'
sidekiq (7.0.2) lib/sidekiq/web/action.rb:105:in `_erb_busy'
sidekiq (7.0.2) lib/sidekiq/web/action.rb:89:in `_erb'
sidekiq (7.0.2) lib/sidekiq/web/action.rb:58:in `erb'
sidekiq (7.0.2) lib/sidekiq/web/application.rb:80:in `block in <class:WebApplication>'
sidekiq (7.0.2) lib/sidekiq/web/application.rb:323:in `instance_exec'
sidekiq (7.0.2) lib/sidekiq/web/application.rb:323:in `block in call'
sidekiq (7.0.2) lib/sidekiq/web/application.rb:321:in `catch'
sidekiq (7.0.2) lib/sidekiq/web/application.rb:321:in `call'
sidekiq (7.0.2) lib/sidekiq/web/csrf_protection.rb:52:in `admit'
sidekiq (7.0.2) lib/sidekiq/web/csrf_protection.rb:41:in `call'
rack (2.2.4) lib/rack/auth/basic.rb:28:in `call'
rack (2.2.4) lib/rack/static.rb:161:in `call'
rack (2.2.4) lib/rack/builder.rb:244:in `call'
sidekiq (7.0.2) lib/sidekiq/web.rb:105:in `call'
sidekiq (7.0.2) lib/sidekiq/web.rb:110:in `call'
actionpack (7.0.4) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (7.0.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (7.0.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:852:in `call'
rack (2.2.4) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.4) lib/rack/etag.rb:27:in `call'
rack (2.2.4) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.4) lib/rack/head.rb:12:in `call'
actionpack (7.0.4) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/cookies.rb:696:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.4) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.4) lib/rails/rack/logger.rb:40:in `call_app'
railties (7.0.4) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (7.0.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (7.0.4) lib/rails/rack/logger.rb:25:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.4) lib/rack/method_override.rb:24:in `call'
rack (2.2.4) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
honeybadger (4.12.2) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
honeybadger (4.12.2) lib/honeybadger/agent.rb:426:in `with_rack_env'
honeybadger (4.12.2) lib/honeybadger/rack/error_notifier.rb:30:in `call'
honeybadger (4.12.2) lib/honeybadger/rack/user_feedback.rb:31:in `call'
honeybadger (4.12.2) lib/honeybadger/rack/user_informer.rb:21:in `call'
railties (7.0.4) lib/rails/engine.rb:530:in `call'
puma (5.6.5) lib/puma/configuration.rb:252:in `call'
puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
puma (5.6.5) lib/puma/server.rb:443:in `process_client'
puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by mperham** [comment]
Upgrade.
