### ISSUE TITLE
TypeError: Unsupported command argument type: ActiveSupport::Duration

### ISSUE THREAD

**Issue by mcedrone** [mperham/sidekiq#5759]
getting this after upgrading, works with previous versions

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/4095860/216104178-a4b4495c-ca92-4a98-8c9c-1ca566409cb8.png">

redis (5.0.6)
sidekiq (7.0.3)

Is there an incompatibility? Or something I'm missing?

```
From: /Users/repos/app/models/export_documents_task.rb:46 ExportDocumentsTask#process_export_task_async:

    40: def process_export_task_async
    41:   binding.pry
    42:   begin
    43:     AsyncTasks::AsyncTaskWorker.perform_async(self.id)
    44:   rescue => e
    45:     puts e.backtrace
 => 46:     binding.pry
    47:   end
    48:   self.push_event(status: :queued, progress: 0.1)
    49: end
```

```
[1] pry(#<ExportDocumentsPdfTask>)> e
#<TypeError: Unsupported command argument type: ActiveSupport::Duration>
[2] pry(#<ExportDocumentsPdfTask>)> e.backtrace
[
  [  0] "/Users/.rvm/gems/ruby-3.0.5/gems/redis-client-0.12.1/lib/redis_client/command_builder.rb:37:in `block in generate'",
  [  1] "/Users/.rvm/gems/ruby-3.0.5/gems/redis-client-0.12.1/lib/redis_client/command_builder.rb:28:in `map!'",
  [  2] "/Users/.rvm/gems/ruby-3.0.5/gems/redis-client-0.12.1/lib/redis_client/command_builder.rb:28:in `generate'",
  [  3] "/Users/.rvm/gems/ruby-3.0.5/gems/redis-client-0.12.1/lib/redis_client.rb:461:in `call'",
  [  4] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-7.0.3/lib/sidekiq/redis_client_adapter.rb:27:in `method_missing'",
  [  5] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-status-2.1.3/lib/sidekiq-status/storage.rb:18:in `block (2 levels) in store_for_id'",
  [  6] "/Users/.rvm/gems/ruby-3.0.5/gems/redis-client-0.12.1/lib/redis_client/decorator.rb:55:in `block in multi'",
  [  7] "/Users/.rvm/gems/ruby-3.0.5/gems/redis-client-0.12.1/lib/redis_client.rb:580:in `build_transaction'",
  [  8] "/Users/.rvm/gems/ruby-3.0.5/gems/redis-client-0.12.1/lib/redis_client.rb:394:in `multi'",
  [  9] "/Users/.rvm/gems/ruby-3.0.5/gems/redis-client-0.12.1/lib/redis_client/decorator.rb:55:in `multi'",
  [ 10] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-status-2.1.3/lib/sidekiq-status/storage.rb:16:in `block in store_for_id'",
  [ 11] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-status-2.1.3/lib/sidekiq-status/storage.rb:111:in `block in redis_connection'",
  [ 12] "/Users/.rvm/gems/ruby-3.0.5/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'",
  [ 13] "/Users/.rvm/gems/ruby-3.0.5/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'",
  [ 14] "/Users/.rvm/gems/ruby-3.0.5/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'",
  [ 15] "/Users/.rvm/gems/ruby-3.0.5/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'",
  [ 16] "/Users/.rvm/gems/ruby-3.0.5/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'",
  [ 17] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-status-2.1.3/lib/sidekiq-status/storage.rb:110:in `redis_connection'",
  [ 18] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-status-2.1.3/lib/sidekiq-status/storage.rb:15:in `store_for_id'",
  [ 19] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-status-2.1.3/lib/sidekiq-status/client_middleware.rb:42:in `call'",
  [ 20] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-7.0.3/lib/sidekiq/middleware/chain.rb:177:in `block in invoke'",
  [ 21] "/Users/.rvm/gems/ruby-3.0.5/gems/ddtrace-1.9.0/lib/datadog/tracing/contrib/sidekiq/client_tracer.rb:44:in `block in call'",
  [ 22] "/Users/.rvm/gems/ruby-3.0.5/gems/ddtrace-1.9.0/lib/datadog/tracing/trace_operation.rb:194:in `block in measure'",
  [ 23] "/Users/.rvm/gems/ruby-3.0.5/gems/ddtrace-1.9.0/lib/datadog/tracing/span_operation.rb:152:in `measure'",
  [ 24] "/Users/.rvm/gems/ruby-3.0.5/gems/ddtrace-1.9.0/lib/datadog/tracing/trace_operation.rb:194:in `measure'",
  [ 25] "/Users/.rvm/gems/ruby-3.0.5/gems/ddtrace-1.9.0/lib/datadog/tracing/tracer.rb:382:in `start_span'",
  [ 26] "/Users/.rvm/gems/ruby-3.0.5/gems/ddtrace-1.9.0/lib/datadog/tracing/tracer.rb:162:in `block in trace'",
  [ 27] "/Users/.rvm/gems/ruby-3.0.5/gems/ddtrace-1.9.0/lib/datadog/tracing/context.rb:45:in `activate!'",
  [ 28] "/Users/.rvm/gems/ruby-3.0.5/gems/ddtrace-1.9.0/lib/datadog/tracing/tracer.rb:161:in `trace'",
  [ 29] "/Users/.rvm/gems/ruby-3.0.5/gems/ddtrace-1.9.0/lib/datadog/tracing.rb:18:in `trace'",
  [ 30] "/Users/.rvm/gems/ruby-3.0.5/gems/ddtrace-1.9.0/lib/datadog/tracing/contrib/sidekiq/client_tracer.rb:25:in `call'",
  [ 31] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-7.0.3/lib/sidekiq/middleware/chain.rb:177:in `block in invoke'",
  [ 32] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-pro-7.0.6/lib/sidekiq/batch/middleware.rb:18:in `call'",
  [ 33] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-7.0.3/lib/sidekiq/middleware/chain.rb:177:in `block in invoke'",
  [ 34] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-7.0.3/lib/sidekiq/middleware/chain.rb:180:in `invoke'",
  [ 35] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-7.0.3/lib/sidekiq/client.rb:87:in `push'",
  [ 36] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-7.0.3/lib/sidekiq/job.rb:365:in `client_push'",
  [ 37] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-7.0.3/lib/sidekiq/job.rb:198:in `perform_async'",
  [ 38] "/Users/.rvm/gems/ruby-3.0.5/gems/sidekiq-7.0.3/lib/sidekiq/job.rb:290:in `perform_async'",
  [ 39] "/Users/repos/app/models/export_documents_task.rb:43:in `process_export_task_async'",
  [ 40] "/Users/repos/app/controllers/api/export_documents_pdf_tasks_controller.rb:33:in `process_export_task'",
  [ 41] "/Users/.rvm/gems/ruby-3.0.5/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:427:in `block in make_lambda'",
  [ 42] "/Users/.rvm/gems/ruby-3.0.5/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:246:in `block in halting'",
  [ 43] "/Users/.rvm/gems/ruby-3.0.5/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:516:in `block in invoke_after'",
  [ 44] "/Users/.rvm/gems/ruby-3.0.5/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:516:in `each'",
  [ 45] "/Users/.rvm/gems/ruby-3.0.5/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:516:in `invoke_after'",
  [ 46] "/Users/.rvm/gems/ruby-3.0.5/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:131:in `block in run_callbacks'",
  [ 47] "/Users/.rvm/gems/ruby-3.0.5/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:137:in `run_callbacks'",
  [ 48] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/abstract_controller/callbacks.rb:41:in `process_action'",
  [ 49] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_controller/metal/rescue.rb:22:in `process_action'",
  [ 50] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'",
  [ 51] "/Users/.rvm/gems/ruby-3.0.5/gems/activesupport-6.1.7.2/lib/active_support/notifications.rb:203:in `block in instrument'",
  [ 52] "/Users/.rvm/gems/ruby-3.0.5/gems/activesupport-6.1.7.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'",
  [ 53] "/Users/.rvm/gems/ruby-3.0.5/gems/activesupport-6.1.7.2/lib/active_support/notifications.rb:203:in `instrument'",
  [ 54] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_controller/metal/instrumentation.rb:33:in `process_action'",
  [ 55] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'",
  [ 56] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/railties/controller_runtime.rb:27:in `process_action'",
  [ 57] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/abstract_controller/base.rb:165:in `process'",
  [ 58] "/Users/.rvm/gems/ruby-3.0.5/gems/actionview-6.1.7.2/lib/action_view/rendering.rb:39:in `process'",
  [ 59] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_controller/metal.rb:190:in `dispatch'",
  [ 60] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_controller/metal.rb:254:in `dispatch'",
  [ 61] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'",
  [ 62] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/routing/route_set.rb:33:in `serve'",
  [ 63] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/journey/router.rb:50:in `block in serve'",
  [ 64] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/journey/router.rb:32:in `each'",
  [ 65] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/journey/router.rb:32:in `serve'",
  [ 66] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/routing/route_set.rb:842:in `call'",
  [ 67] "/Users/.rvm/gems/ruby-3.0.5/gems/turnout-2.5.0/lib/rack/turnout.rb:25:in `call'",
  [ 68] "/Users/.rvm/gems/ruby-3.0.5/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:470:in `call_app!'",
  [ 69] "/Users/.rvm/gems/ruby-3.0.5/gems/omniauth-saml-2.1.0/lib/omniauth/strategies/saml.rb:86:in `other_phase'",
  [ 70] "/Users/.rvm/gems/ruby-3.0.5/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:195:in `call!'",
  [ 71] "/Users/.rvm/gems/ruby-3.0.5/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:169:in `call'",
  [ 72] "/Users/.rvm/gems/ruby-3.0.5/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:202:in `call!'",
  [ 73] "/Users/.rvm/gems/ruby-3.0.5/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:169:in `call'",
  [ 74] "/Users/.rvm/gems/ruby-3.0.5/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:202:in `call!'",
  [ 75] "/Users/.rvm/gems/ruby-3.0.5/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:169:in `call'",
  [ 76] "/Users/.rvm/gems/ruby-3.0.5/gems/omniauth-2.1.1/lib/omniauth/builder.rb:44:in `call'",
  [ 77] "/Users/.rvm/gems/ruby-3.0.5/gems/rack-attack-6.6.1/lib/rack/attack.rb:103:in `call'",
  [ 78] "/Users/.rvm/gems/ruby-3.0.5/gems/meta_request-0.7.3/lib/meta_request/middlewares/app_request_handler.rb:15:in `call'",
  [ 79] "/Users/.rvm/gems/ruby-3.0.5/gems/meta_request-0.7.3/lib/meta_request/middlewares/meta_request_handler.rb:15:in `call'",
  [ 80] "/Users/.rvm/gems/ruby-3.0.5/gems/htmlcompressor-0.4.0/lib/htmlcompressor/rack.rb:36:in `call'",
  [ 81] "/Users/.rvm/gems/ruby-3.0.5/gems/rack-2.2.6.2/lib/rack/deflater.rb:44:in `call'",
  [ 82] "/Users/.rvm/gems/ruby-3.0.5/gems/rack-attack-6.6.1/lib/rack/attack.rb:127:in `call'",
  [ 83] "/Users/repos/app/middleware/strip_x_forwarded_host.rb:12:in `call'",
  [ 84] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/middleware/database_selector.rb:53:in `block in call'",
  [ 85] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/middleware/database_selector/resolver.rb:71:in `block (2 levels) in write_to_primary'",
  [ 86] "/Users/.rvm/gems/ruby-3.0.5/gems/activesupport-6.1.7.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'",
  [ 87] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/middleware/database_selector/resolver.rb:70:in `block in write_to_primary'",
  [ 88] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/connection_handling.rb:383:in `block (2 levels) in with_role_and_shard'",
  [ 89] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1025:in `while_preventing_writes'",
  [ 90] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/connection_handling.rb:381:in `block in with_role_and_shard'",
  [ 91] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/connection_handling.rb:398:in `swap_connection_handler'",
  [ 92] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/connection_handling.rb:373:in `with_handler'",
  [ 93] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/connection_handling.rb:380:in `with_role_and_shard'",
  [ 94] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/connection_handling.rb:175:in `connected_to'",
  [ 95] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/middleware/database_selector/resolver.rb:69:in `write_to_primary'",
  [ 96] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/middleware/database_selector/resolver.rb:44:in `write'",
  [ 97] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/middleware/database_selector.rb:65:in `select_database'",
  [ 98] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/middleware/database_selector.rb:52:in `call'",
  [ 99] "/Users/.rvm/gems/ruby-3.0.5/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'",
  [100] "/Users/.rvm/gems/ruby-3.0.5/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'",
  [101] "/Users/.rvm/gems/ruby-3.0.5/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'",
  [102] "/Users/.rvm/gems/ruby-3.0.5/gems/rack-2.2.6.2/lib/rack/tempfile_reaper.rb:15:in `call'",
  [103] "/Users/.rvm/gems/ruby-3.0.5/gems/rack-2.2.6.2/lib/rack/etag.rb:27:in `call'",
  [104] "/Users/.rvm/gems/ruby-3.0.5/gems/rack-2.2.6.2/lib/rack/conditional_get.rb:40:in `call'",
  [105] "/Users/.rvm/gems/ruby-3.0.5/gems/rack-2.2.6.2/lib/rack/head.rb:12:in `call'",
  [106] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/http/permissions_policy.rb:22:in `call'",
  [107] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/http/content_security_policy.rb:19:in `call'",
  [108] "/Users/.rvm/gems/ruby-3.0.5/gems/rack-2.2.6.2/lib/rack/session/abstract/id.rb:266:in `context'",
  [109] "/Users/.rvm/gems/ruby-3.0.5/gems/rack-2.2.6.2/lib/rack/session/abstract/id.rb:260:in `call'",
  [110] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/middleware/cookies.rb:697:in `call'",
  [111] "/Users/.rvm/gems/ruby-3.0.5/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:601:in `call'",
  [112] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'",
  [113] "/Users/.rvm/gems/ruby-3.0.5/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:98:in `run_callbacks'",
  [114] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'",
  [115] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/middleware/executor.rb:14:in `call'",
  [116] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'",
  [117] "/Users/.rvm/gems/ruby-3.0.5/gems/ddtrace-1.9.0/lib/datadog/tracing/contrib/rails/middlewares.rb:19:in `call'",
  [118] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'",
  [119] "/Users/.rvm/gems/ruby-3.0.5/gems/web-console-4.2.0/lib/web_console/middleware.rb:132:in `call_app'",
  [120] "/Users/.rvm/gems/ruby-3.0.5/gems/web-console-4.2.0/lib/web_console/middleware.rb:28:in `block in call'",
  [121] "/Users/.rvm/gems/ruby-3.0.5/gems/web-console-4.2.0/lib/web_console/middleware.rb:17:in `catch'",
  [122] "/Users/.rvm/gems/ruby-3.0.5/gems/web-console-4.2.0/lib/web_console/middleware.rb:17:in `call'",
  [123] "/Users/.rvm/gems/ruby-3.0.5/gems/rack-contrib-2.3.0/lib/rack/contrib/response_headers.rb:19:in `call'",
  [124] "/Users/.rvm/gems/ruby-3.0.5/gems/meta_request-0.7.3/lib/meta_request/middlewares/headers.rb:18:in `call'",
  [125] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'",
  [126] "/Users/.rvm/gems/ruby-3.0.5/gems/lograge-0.12.0/lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'",
  [127] "/Users/.rvm/gems/ruby-3.0.5/gems/railties-6.1.7.2/lib/rails/rack/logger.rb:28:in `call'",
  [128] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'",
  [129] "/Users/.rvm/gems/ruby-3.0.5/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'",
  [130] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/middleware/request_id.rb:26:in `call'",
  [131] "/Users/.rvm/gems/ruby-3.0.5/gems/rack-2.2.6.2/lib/rack/method_override.rb:24:in `call'",
  [132] "/Users/.rvm/gems/ruby-3.0.5/gems/rack-2.2.6.2/lib/rack/runtime.rb:22:in `call'",
  [133] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/middleware/executor.rb:14:in `call'",
  [134] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/middleware/static.rb:24:in `call'",
  [135] "/Users/.rvm/gems/ruby-3.0.5/gems/rack-2.2.6.2/lib/rack/sendfile.rb:110:in `call'",
  [136] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/middleware/ssl.rb:77:in `call'",
  [137] "/Users/.rvm/gems/ruby-3.0.5/gems/actionpack-6.1.7.2/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'",
  [138] "/Users/.rvm/gems/ruby-3.0.5/gems/ddtrace-1.9.0/lib/datadog/tracing/contrib/rack/middlewares.rb:88:in `call'",
  [139] "/Users/.rvm/gems/ruby-3.0.5/gems/secure_headers-6.5.0/lib/secure_headers/middleware.rb:11:in `call'",
  [140] "/Users/.rvm/gems/ruby-3.0.5/gems/utf8-cleaner-1.0.0/lib/utf8-cleaner/middleware.rb:21:in `call'",
  [141] "/Users/.rvm/gems/ruby-3.0.5/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'",
  [142] "/Users/.rvm/gems/ruby-3.0.5/gems/railties-6.1.7.2/lib/rails/engine.rb:539:in `call'",
  [143] "/Users/.rvm/gems/ruby-3.0.5/gems/puma-6.0.2/lib/puma/configuration.rb:268:in `call'",
  [144] "/Users/.rvm/gems/ruby-3.0.5/gems/puma-6.0.2/lib/puma/request.rb:93:in `block in handle_request'",
  [145] "/Users/.rvm/gems/ruby-3.0.5/gems/puma-6.0.2/lib/puma/thread_pool.rb:340:in `with_force_shutdown'",
  [146] "/Users/.rvm/gems/ruby-3.0.5/gems/puma-6.0.2/lib/puma/request.rb:92:in `handle_request'",
  [147] "/Users/.rvm/gems/ruby-3.0.5/gems/puma-6.0.2/lib/puma/server.rb:429:in `process_client'",
  [148] "/Users/.rvm/gems/ruby-3.0.5/gems/puma-6.0.2/lib/puma/server.rb:232:in `block in run'",
  [149] "/Users/.rvm/gems/ruby-3.0.5/gems/puma-6.0.2/lib/puma/thread_pool.rb:147:in `block in spawn_thread'"
]

```

**Comment by mperham** [comment]
If you look closely at that backtrace, there's several lines for sidekiq-status.

https://github.com/kenaniah/sidekiq-status/pull/23#issuecomment-1351755924
