### ISSUE TITLE
Sidekiq stops polling jobs showing 0 of N busy and a full queue

### ISSUE THREAD

**Issue by fenelon** [mperham/sidekiq#636]
After solving the issue with Sidekiq process dying with proper monitoring, I found out that it sometimes just stops polling new jobs. `ps ax` shows it's running and 0 of N are busy. Any idea what could be causing it? I have network operations in my workers. This one, for instance, uses Net::HTTP. The other uses Typhoeus. 

Here is what I found in `sidekiq.log`:

**2013-01-22T06:25:24Z 4547 TID-otmrcvtpg WARN: {:context=>"scheduling poller thread died!"}**

```
2013-01-22T06:25:22Z 4547 TID-15suoc WARN: {"retry"=>3, "queue"=>"default", "timeout"=>60, "class"=>"HotelImageLoader", "args"=>[9000369, "http://tezpoisk.ru/images/all_hotels/9000369/ic_hotels_residence_12.jpg"], "jid"=>"8ae9a54798057a3b36515bd3", "error_message"=>"getaddrinfo: Temporary failure in name resolution", "error_class"=>"SocketError", "failed_at"=>2013-01-22 06:25:22 UTC, "retry_count"=>0}
2013-01-22T06:25:22Z 4547 TID-15suoc WARN: getaddrinfo: Name or service not known
2013-01-22T06:25:22Z 4547 TID-15suoc WARN: /home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/connection/ruby.rb:112:in `getaddrinfo'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/connection/ruby.rb:112:in `connect'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/connection/ruby.rb:174:in `connect'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:263:in `establish_connection'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:69:in `connect'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:282:in `ensure_connected'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:173:in `block in process'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:248:in `logging'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:172:in `process'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:147:in `call_pipelined'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:121:in `block in call_pipeline'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:235:in `with_reconnect'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:119:in `call_pipeline'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis.rb:2020:in `block in multi'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis.rb:36:in `block in synchronize'
/home/deployer/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis.rb:36:in `synchronize'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis.rb:2012:in `multi'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-namespace-1.2.1/lib/redis/namespace.rb:220:in `method_missing'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/sidekiq-2.6.5/lib/sidekiq/processor.rb:91:in `block in stats'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/connection_pool-1.0.0/lib/connection_pool.rb:48:in `with'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/sidekiq-2.6.5/lib/sidekiq.rb:66:in `redis'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/sidekiq-2.6.5/lib/sidekiq/util.rb:25:in `redis'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/sidekiq-2.6.5/lib/sidekiq/processor.rb:90:in `ensure in stats'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/sidekiq-2.6.5/lib/sidekiq/processor.rb:90:in `stats'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/sidekiq-2.6.5/lib/sidekiq/processor.rb:43:in `block in process'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb:23:in `call'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb:23:in `public_send'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/calls.rb:23:in `dispatch'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/future.rb:18:in `block in initialize'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create'
2013-01-22T06:25:24Z 4547 TID-otmrcvtpg WARN: {:context=>"scheduling poller thread died!"}
2013-01-22T06:25:24Z 4547 TID-otmrcvtpg WARN: getaddrinfo: Name or service not known
2013-01-22T06:25:24Z 4547 TID-otmrcvtpg WARN: /home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/connection/ruby.rb:112:in `getaddrinfo'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/connection/ruby.rb:112:in `connect'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/connection/ruby.rb:174:in `connect'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:263:in `establish_connection'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:69:in `connect'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:282:in `ensure_connected'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:173:in `block in process'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:248:in `logging'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:172:in `process'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:147:in `call_pipelined'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:121:in `block in call_pipeline'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:235:in `with_reconnect'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:119:in `call_pipeline'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis.rb:2020:in `block in multi'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis.rb:36:in `block in synchronize'
/home/deployer/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis.rb:36:in `synchronize'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis.rb:2012:in `multi'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/redis-namespace-1.2.1/lib/redis/namespace.rb:220:in `method_missing'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/sidekiq-2.6.5/lib/sidekiq/scheduled.rb:31:in `block (3 levels) in poll'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/sidekiq-2.6.5/lib/sidekiq/scheduled.rb:30:in `each'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/sidekiq-2.6.5/lib/sidekiq/scheduled.rb:30:in `block (2 levels) in poll'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/connection_pool-1.0.0/lib/connection_pool.rb:48:in `with'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/sidekiq-2.6.5/lib/sidekiq.rb:66:in `redis'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/sidekiq-2.6.5/lib/sidekiq/scheduled.rb:29:in `block in poll'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/sidekiq-2.6.5/lib/sidekiq/util.rb:15:in `watchdog'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/sidekiq-2.6.5/lib/sidekiq/scheduled.rb:22:in `poll'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/sidekiq-2.6.5/lib/sidekiq/scheduled.rb:52:in `block (2 levels) in poll'
/home/deployer/apps/leveltravel/shared/bundle/ruby/1.9.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:24:in `block in initialize'
```

**Comment by amitsaxena** [comment]
We also start seeing the "getaddrinfo: Name or service not known" errors randomly, and they don't go away until we restart the sidekiq process.

**Comment by heaven** [comment]
Just had the same problem. Figured out it was Mechanize (lots of CLOSE_WAIT tcp connections in netstat).
