### ISSUE TITLE
undefined method `activating' for an instance of ActiveJob::QueueAdapters::SidekiqAdapter

### ISSUE THREAD

**Issue by tomaszwojcik** [mperham/sidekiq#6511]
Ruby version: 3.3.5
Rails version: 7.1.4
Sidekiq / Pro / Enterprise version(s): 7.3.6 (tried also older versions)

In `application.rb`:
```
    config.active_job.queue_adapter = :sidekiq
```

`sidekiq.yml`:
```
---
:concurrency: 5
:queues:
  - default
  - mailers
  - sentry
  - active_storage_analysis
  - spree_stock_location_stock_items
  - spree_webhooks
:redis:
  url: <%= ENV.fetch("REDIS_URL") %>
```

Error, on every command (even `exit`) in the rails console:
```
irb(main):003>
/usr/local/bundle/ruby/3.3.0/gems/irb-1.14.1/lib/irb.rb:1260:in `full_message': undefined method `activating' for an instance of ActiveJob::QueueAdapters::SidekiqAdapter (NoMethodError)

    queue_adapter.activating(&block)
                 ^^^^^^^^^^^
```

**Comment by mperham** [comment]
Please show the full backtrace.

**Comment by tomaszwojcik** [comment]
@mperham sadly this is all I got, from launching rails console to error. I might add that I'm using this in a Spree (https://spreecommerce.org/) project.

```
rails@12f0587e1080:/rails$ ./bin/rails c
/usr/local/lib/ruby/3.3.0/bundled_gems.rb:75: warning: /usr/local/lib/ruby/3.3.0/ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
Also please contact the author of jbuilder-2.12.0 to request adding ostruct into its gemspec.
/usr/local/bundle/ruby/3.3.0/gems/spree_i18n-5.3.0/lib/spree_i18n/locale.rb:1: warning: /usr/local/lib/ruby/3.3.0/csv.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
You can add csv to your Gemfile or gemspec to silence this warning.
Also please contact the author of spree_i18n-5.3.0 to request adding csv into its gemspec.


Type 'jobs_help' to see how to connect to the available job servers to manage jobs

Loading development environment (Rails 7.1.4)
irb(main):001>
/usr/local/bundle/ruby/3.3.0/gems/irb-1.14.1/lib/irb.rb:1260:in `full_message': undefined method `activating' for an instance of ActiveJob::QueueAdapters::SidekiqAdapter (NoMethodError)

    queue_adapter.activating(&block)
                 ^^^^^^^^^^^
irb(main):002>
```

If you have any idea how can I provide more verbose information I will do that.

**Comment by mperham** [comment]
Try:

> % BACKTRACE=1 bin/rails c

**Comment by tomaszwojcik** [comment]
Output is the same :/

```
rails@12f0587e1080:/rails$ BACKTRACE=1 bin/rails c
/usr/local/lib/ruby/3.3.0/bundled_gems.rb:75: warning: /usr/local/lib/ruby/3.3.0/ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
Also please contact the author of jbuilder-2.12.0 to request adding ostruct into its gemspec.
/usr/local/bundle/ruby/3.3.0/gems/spree_i18n-5.3.0/lib/spree_i18n/locale.rb:1: warning: /usr/local/lib/ruby/3.3.0/csv.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
You can add csv to your Gemfile or gemspec to silence this warning.
Also please contact the author of spree_i18n-5.3.0 to request adding csv into its gemspec.


Type 'jobs_help' to see how to connect to the available job servers to manage jobs

Loading development environment (Rails 7.1.4)
irb(main):001>
/usr/local/bundle/ruby/3.3.0/gems/irb-1.14.1/lib/irb.rb:1260:in `full_message': undefined method `activating' for an instance of ActiveJob::QueueAdapters::SidekiqAdapter (NoMethodError)

    queue_adapter.activating(&block)
                 ^^^^^^^^^^^
irb(main):002>
```

**Comment by nflorentin** [comment]
I have the same error on a ruby 3.3.5 / rails 7.1 app, no matter adapter I use (Test, Inline, ...), only in test environment.

I did not found any solution for now... except to not use rails console in test env.

**Comment by nflorentin** [comment]
Do you have the gem mission_control-jobs installed ?
If yes, update it or uninstall it.

Just found that this gem was the problem.

It seems unrelated to Sidekiq.

For info, the trace was:
```
["/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/mission_control-jobs-0.3.1/lib/mission_control/jobs/server.rb:18:in `activating'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/mission_control-jobs-0.3.1/lib/mission_control/jobs/console/context.rb:6:in `evaluate'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/irb-1.14.1/lib/irb.rb:1051:in `block (2 levels) in eval_input'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/irb-1.14.1/lib/irb.rb:1373:in `signal_status'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/irb-1.14.1/lib/irb.rb:1043:in `block in eval_input'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/irb-1.14.1/lib/irb.rb:1122:in `block in each_top_level_statement'",
 "<internal:kernel>:187:in `loop'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/irb-1.14.1/lib/irb.rb:1119:in `each_top_level_statement'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/irb-1.14.1/lib/irb.rb:1042:in `eval_input'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/irb-1.14.1/lib/irb.rb:1023:in `block in run'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/irb-1.14.1/lib/irb.rb:1022:in `catch'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/irb-1.14.1/lib/irb.rb:1022:in `run'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/railties-7.2.1/lib/rails/commands/console/irb_console.rb:119:in `start'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/railties-7.2.1/lib/rails/commands/console/console_command.rb:59:in `start'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/railties-7.2.1/lib/rails/commands/console/console_command.rb:8:in `start'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/railties-7.2.1/lib/rails/commands/console/console_command.rb:87:in `perform'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/railties-7.2.1/lib/rails/command/base.rb:178:in `invoke_command'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/railties-7.2.1/lib/rails/command/base.rb:73:in `perform'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/railties-7.2.1/lib/rails/command.rb:71:in `block in invoke'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/railties-7.2.1/lib/rails/command.rb:149:in `with_argv'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/railties-7.2.1/lib/rails/command.rb:69:in `invoke'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/railties-7.2.1/lib/rails/commands.rb:18:in `<main>'",
 "/Users/nicolas/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'",
 "/Users/nicolas/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'",
 "/Users/nicolas/.rvm/gems/ruby-3.3.5/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'",
 "bin/rails:8:in `<main>'"]
```

**Comment by rosa** [comment]
Oh, yes, this is expected if you're trying to use [Mission Control  – Jobs](ission-control--jobs
) with Sidekiq. Right now, it supports only Rescue and Solid Queue.
