### ISSUE TITLE
Stuck Threads Issue

### ISSUE THREAD

**Issue by marclennox** [mperham/sidekiq#702]
I've been struggling for the past 2 months trying to get Sidekiq working reliably with our worker pool and looking for some suggestion on how to debug.

I'm running 4 worker processes each with 100 threads, across 2 machines.  The worker profile is typically long running (1 to 30 minutes) with several external API calls and a lot of database updates.

What I'm seeing as time progresses is an increasing number of what appear to  be "stuck" threads, until eventually all 100 threads are effectively dead and no work is being done.  I've tried sending SIGTTIN to the running process to get a backtrace, but the process does not respond to it.  In fact once I've got stuck threads, the only thing that works is kill -9.

In order to keep things working, I have a cron job that kills all the worker processes every 2 hours and restarts it.  This is obviously not a good solutions and results in a lot of cleanup operations, but it keeps things limping along for now.

I'm running on top of Heroku Postgres and I've been monitoring the pg_stat_activity table as these stuck threads accumulate.  There a appears to be a 1-to-1 correlation between stuck threads and "<IDLE> in transaction" postgres processes, which also accumulate over time.  The transaction blocks inside of the workers is very tight and does not span external network calls, which would indicate that the threads are not hanging on the network calls but in the database updates.

I've seen in other discussions that these types of problems are likely due to non-threadsafe gems.  I've include below my current Gemfile.lock.  Would really appreciate some help on how to further diagnosse this...  really don't want to switch back to Resque unless I have to.

``` ruby
DEPENDENCIES
  aasm
  activeadmin
  acts-as-taggable-on
  airbrake
  annotate
  awesome_print
  aws-sdk
  box-api!
  box-api-v1!
  cancan
  capistrano
  certified
  chameleon
  clockwork
  coffee-rails
  colored
  colortail
  connection_pool
  contextio!
  country_select
  databasedotcom
  devise
  devise-async
  dropbox-sdk
  evernote-thrift
  fabrication
  fakeweb
  foreman!
  gchartrb
  gmail!
  google-api-client
  growl
  guard
  guard-minitest
  guard-spork
  guard-test
  has_scope
  httparty
  insensitive_hash
  jquery-rails (= 2.1.4)
  kaminari
  lograge
  mime-types
  mimetype-fu
  mini_magick
  minitest
  mocha (= 0.12.1)
  newrelic_rpm
  numbers_and_words
  oauth
  oauth2
  papertrail-cli
  pg
  puma
  quiet_assets
  rabl
  rails (~> 3.2)
  rb-fsevent
  redis
  redis-namespace
  responders
  roadie
  ruby-prof
  ruby_gntp
  sass-rails
  sidekiq
  signet
  simple_form
  sinatra
  single_test
  slim
  spork
  spork-testunit
  stripe (~> 1.7.9)
  strong_parameters
  thin
  tire
  turbo-sprockets-rails3
  uglifier
  unicorn
  uuidtools
  webrat
  yajl-ruby
```

**Comment by jonhyman** [comment]
@lastomato / @Mysrt - did you ever figure out a solution here? We started encountering this with S3 image uploads around the same time as we upgraded to Ruby 2.2.2. Our stack trace looks like everyone else's:

```
Jun 29 11:48:35 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:326:in `do_write'
Jun 29 11:48:35 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:344:in `write'
Jun 29 11:48:35 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `copy_stream'
Jun 29 11:48:35 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `send_request_with_body_stream'
Jun 29 11:48:35 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:122:in `exec'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:27:in `block in new_transport_request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:26:in `catch'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:26:in `new_transport_request'
Jun 29 11:48:35 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1384:in `request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/net.rb:27:in `block (2 levels) in request_with_newrelic_trace'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent.rb:426:in `disable_all_tracing'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/net.rb:26:in `block in request_with_newrelic_trace'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/cross_app_tracing.rb:48:in `tl_trace_http_request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/net.rb:23:in `request_with_newrelic_trace'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/connection_pool.rb:356:in `request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/net_http_handler.rb:64:in `block in handle'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/connection_pool.rb:131:in `session_for'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/net_http_handler.rb:56:in `handle'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:253:in `block in make_sync_request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:282:in `retry_server_errors'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/s3/region_detection.rb:11:in `retry_server_errors'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:249:in `make_sync_request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:511:in `block (2 levels) in client_request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:391:in `log_client_request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:477:in `block in client_request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:373:in `return_or_raise'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:476:in `client_request'
Jun 29 11:48:35 :worker production.log:  (eval):3:in `put_object'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/s3/s3_object.rb:1765:in `write_with_put_object'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-
```

We're on Ruby 2.2.2, Celluloid 0.16.0.

**Comment by lastomato** [comment]
@jonhyman No, we did spend some time investigating it, but didn't find anything.

**Comment by mperham** [comment]
OpenSSL strikes again.  :-/

**Comment by jonhyman** [comment]
I tried upgrading openssl by doing an `apt-get upgrade`, but still no dice. Also attempted upgrading restclient, which removes monkey patches in http, still having the issue. New stacktrace below for anyone who sees this thread.

```
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  [ 5:57:08.222245954] (26900) [WARN] /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:326:in `syswrite'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:326:in `do_write'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:344:in `write'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `copy_stream'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `send_request_with_body_stream'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:122:in `exec'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:27:in `block in new_transport_request'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:26:in `catch'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:26:in `new_transport_request'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1384:in `request'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/net.rb:27:in `block (2 levels) in request_with_newrelic_trace'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent.rb:431:in `disable_all_tracing'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/net.rb:26:in `block in request_with_newrelic_trace'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/cross_app_tracing.rb:48:in `tl_trace_http_request'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/net.rb:23:in `request_with_newrelic_trace'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/connection_pool.rb:356:in `request'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/net_http_handler.rb:64:in `block in handle'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/connection_pool.rb:131:in `session_for'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/net_http_handler.rb:56:in `handle'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:253:in `block in make_sync_request'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:282:in `retry_server_errors'
Jul 17 13:57:08 worker-st-iad-cld-03 staging.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/s3/region_detection.rb:11:in 
```

**Comment by jonhyman** [comment]
It may not be related to sidekiq, even though I can't repro it on our servers outside of sidekiq. https://github.com/mailman/mailman/issues/106 and https://github.com/markevans/dragonfly/issues/233 have similar stacktraces.

**Comment by mperham** [comment]
MRI's OpenSSL bindings are notorious for evil bugs.  If you upgraded MRI and this started, that would be the first place I'd start investigating.

**Comment by jonhyman** [comment]
Hm. Yeah we started doing a lot of upgrades at once, which is bad for this sort of stuff. Honestly, based on the timeline, it looks like for us, it was upgrading from Rails 3.2.11 to Rails 4.2.1 that did it. A week after upgrading, we started seeing this at least once per day every single day. When we upgraded to Ruby 2.2.2, we had already been seeing it every day for 10 days. Tons of gems changed in the upgrade from 3.2.11 to 4.2.1... I wonder if something there happened. I'll check back and update this thread if I find something.

**Comment by sloops77** [comment]
I also am enountering this issue with 6 threads on our production server: we run rails 4.1.9, ruby 2.2.3, restclient 1.8. Any updates on workarounds peeps?

**Comment by mperham** [comment]
@sloops77 Please don't resurrect old issues.  Open a new issue for your problem.

**Comment by mperham** [comment]
I recently learned that if you upgrade MRI with RVM, RVM can link the old OpenSSL binding with the new Ruby.  Meaning an OpenSSL binding compiled against Ruby 2.0 could be loaded by Ruby 2.2, causing a crash.

If you are seeing OpenSSL issues and you use RVM: 1) stop using RVM in production; 2) rebuild MRI from scratch and see if that fixes any crashes.
