### ISSUE TITLE
Rails Helper Method Within SideKiq

### ISSUE THREAD

**Issue by Miniconi** [mperham/sidekiq#798]
Hi, 

I am generating a pdf through a worker. Is there any way to access Rails Helper Method such as number_to_currency within the worker, in other words getting a rails context in a worker? 

thanks for your time, 

Ben.

**Comment by anbublacky** [comment]
@alexandremagro Do you remember how you fixed this error

**Comment by altjx** [comment]
> Hi,
> 
> I am generating a pdf through a worker. Is there any way to access Rails Helper Method such as number_to_currency within the worker, in other words getting a rails context in a worker?
> 
> thanks for your time,
> 
> Ben.

Just ran into this myself with trying to use:

```
include NumberHelper
```

This caused the following error when running a sidekiq worker that used it:

```
2021-02-22T22:17:32.330Z pid=25106 tid=gn5k75z2q WARN: NameError: uninitialized constant MyWorkerName::NumberHelper                                                                                                                                                                                                                                  2021-02-22T22:17:32.330Z pid=25106 tid=gn5k75z2q WARN: /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
/usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'   
/usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'                                                                                                                                                                                                                              
/usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'           
/myapp/app/workers/my_worker_name.rb:3:in `<class:MyWorkerName>' 
/myapp/app/workers/my_worker_name.rb:1:in `<top (required)>'                               
```

This worked for me instead:

```
include ActionView::Helpers::NumberHelper
```

Feels bad using this for some reason, but it works, for anyone else that may be looking for a similar solution.
