### ISSUE TITLE
Sidekiq::Shutdown duplicates jobs after sidekiq:stop/sidekiq:start

### ISSUE THREAD

**Issue by SergeyKishenin** [mperham/sidekiq#897]
During every deploy stopping Sidekiq's workers with `sidekiq:stop` makes all the running jobs fail with `Sidekiq::Shutdown` error and go to retries, also theese jobs go back to queue waiting until Sidekiq starts.

When Sidekiq is being started with `sidekiq:start` command jobs run again but duplicated. I guess this happens because of two origins: retries and queues.

**Comment by nyddogghr** [comment]
Hi,

I'm sorry to bump this old issue, but this seems to be exactly what I'm having right now.
If you wish me to create another issue, just tell me.

I'm using sidekiq 5.2.5 (neither Pro nor Enterprise) and I can see jobs being duplicated sometimes on sidekiq restart (using heroku). If the job fails during restart due to Sidekiq::Shutdown, it can be sent to both retry and failed queues.
Here is for instance logs showing the issue:
```
2019-02-28T15:57:59.930830+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Running in ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux]
2019-02-28T15:57:59.931251+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2019-02-28T15:57:59.931492+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2019-02-28T15:57:59.931652+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Booting Sidekiq 5.2.5 with redis options {:id=>"Sidekiq-server-PID-4", :url=>"redis://h:REDACTED@ec2-63-32-218-34.eu-west-1.compute.amazonaws.com:6729"}
2019-02-28T15:57:59.939714+00:00 app background.1 - - 4 TID-oxr838ra4 WARN: Sidekiq 6.0 will require Redis 4.0+, you are using Redis v3.2.12
2019-02-28T15:57:59.939794+00:00 app background.1 - - 4 TID-oxr838ra4 DEBUG: Client Middleware:
2019-02-28T15:57:59.939842+00:00 app background.1 - - 4 TID-oxr838ra4 DEBUG: Server Middleware: Raven::SidekiqCleanupMiddleware, NewRelic::SidekiqInstrumentation
2019-02-28T15:57:59.939869+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Starting processing, hit Ctrl-C to stop
2019-02-28T15:57:59.939976+00:00 app background.1 - - 4 TID-oxr838ra4 DEBUG: {:queues=>["critical", "critical", "critical", "critical", "critical", "critical", "critical", "background_api", "background_api", "background_api", "default", "default", "default", "default", "default", "thumb_image", "thumb_image", "thumb_image", "thumb_image", "thumb_image", "low", "low", "low"], :labels=>[], :concurrency=>7, :require=>".", :environment=>"production", :timeout=>8, :poll_interval_average=>nil, :average_scheduled_poll_interval=>5, :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x00007ff82736b330>, #<Raven::SidekiqErrorHandler:0x00007ff814911900>, #<Proc:0x00007ff818953a90@/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/sidekiq.rb:66>], :death_handlers=>[], :lifecycle_events=>{:startup=>[], :quiet=>[], :shutdown=>[], :heartbeat=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :reloader=>#<Sidekiq::Rails::Reloader @app=HerokuService::Application>, :verbose=>true, :limits=>{:thumb_image=>4}, :strict=>false, :config_file=>"./config/sidekiq.yml", :tag=>"app", :identity=>"background.1:4:931b719f8bfd", :fetch=>Sidekiq::LimitFetch}
2019-02-28T15:58:00.001045+00:00 app background.1 - - 4 TID-oxr4317cs Api::BackgroundRequestJob JID-938441f1737c768516eb805a INFO: start
2019-02-28T15:58:19.938971+00:00 app background.1 - - 4 TID-oxr838ra4 DEBUG: Got TERM signal
2019-02-28T15:58:19.938998+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Shutting down
2019-02-28T15:58:19.939252+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Terminating quiet workers
2019-02-28T15:58:19.939255+00:00 app background.1 - - 4 TID-oxr4o5ehs INFO: Scheduler exiting...
2019-02-28T15:58:20.441705+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Pausing to allow workers to finish...
2019-02-28T15:58:27.515236+00:00 app background.1 - - 4 TID-oxr838ra4 WARN: Terminating 1 busy worker threads
2019-02-28T15:58:27.515323+00:00 app background.1 - - 4 TID-oxr838ra4 WARN: Work still in progress [#<struct Sidekiq::LimitFetch::UnitOfWork queue="queue:background_api", job="{\"class\":\"Api::BackgroundRequestJob\",\"args\":[],\"retry\":3,\"queue\":\"background_api\",\"jid\":\"938441f1737c768516eb805a\",\"created_at\":1551369418.3886776,\"enqueued_at\":1551369418.3892639}">]
2019-02-28T15:58:27.515386+00:00 app background.1 - - 4 TID-oxr838ra4 DEBUG: Re-queueing terminated jobs
2019-02-28T15:58:27.516756+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Pushed 1 jobs back to Redis
2019-02-28T15:58:27.518465+00:00 app background.1 - - 4 TID-oxr838ra4 INFO: Bye!
2019-02-28T15:58:27.614586+00:00 app background.1 - - Sending event f745ed721b36484ba521c8cc30d62cb2 to Sentry
2019-02-28T15:58:28.354806+00:00 app background.1 - -
2019-02-28T15:58:28.354825+00:00 app background.1 - - Sidekiq::Shutdown (Sidekiq::Shutdown):
2019-02-28T15:58:28.354831+00:00 app background.1 - -
2019-02-28T15:58:28.354833+00:00 app background.1 - - app/lib/api/response.rb:43:in `to_json'
2019-02-28T15:58:28.354835+00:00 app background.1 - - app/controllers/api/application_controller.rb:15:in `respond_with'
2019-02-28T15:58:28.354836+00:00 app background.1 - - app/controllers/api/v2/media_controller.rb:199:in `index'
2019-02-28T15:58:28.354838+00:00 app background.1 - - app/jobs/api/background_request_job.rb:48:in `perform'
2019-02-28T15:58:31.649134+00:00 app background.1 - - /app/vendor/bundle/ruby/2.4.0/gems/logging-1.8.2/lib/logging/appender.rb:139: warning: constant ::Fixnum is deprecated
2019-02-28T15:58:34.166322+00:00 app background.1 - - 4 TID-ou72l12ck INFO: Running in ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux]
2019-02-28T15:58:34.166344+00:00 app background.1 - - 4 TID-ou72l12ck INFO: See LICENSE and the LGPL-3.0 for licensing details.
2019-02-28T15:58:34.166346+00:00 app background.1 - - 4 TID-ou72l12ck INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2019-02-28T15:58:34.166531+00:00 app background.1 - - 4 TID-ou72l12ck INFO: Booting Sidekiq 5.2.5 with redis options {:id=>"Sidekiq-server-PID-4", :url=>"redis://h:REDACTED@ec2-63-32-218-34.eu-west-1.compute.amazonaws.com:6729"}
2019-02-28T15:58:34.173212+00:00 app background.1 - - 4 TID-ou72l12ck WARN: Sidekiq 6.0 will require Redis 4.0+, you are using Redis v3.2.12
2019-02-28T15:58:34.173309+00:00 app background.1 - - 4 TID-ou72l12ck DEBUG: Client Middleware:
2019-02-28T15:58:34.173357+00:00 app background.1 - - 4 TID-ou72l12ck DEBUG: Server Middleware: Raven::SidekiqCleanupMiddleware, NewRelic::SidekiqInstrumentation
2019-02-28T15:58:34.173385+00:00 app background.1 - - 4 TID-ou72l12ck INFO: Starting processing, hit Ctrl-C to stop
2019-02-28T15:58:34.173541+00:00 app background.1 - - 4 TID-ou72l12ck DEBUG: {:queues=>["critical", "critical", "critical", "critical", "critical", "critical", "critical", "background_api", "background_api", "background_api", "default", "default", "default", "default", "default", "thumb_image", "thumb_image", "thumb_image", "thumb_image", "thumb_image", "low", "low", "low"], :labels=>[], :concurrency=>7, :require=>".", :environment=>"production", :timeout=>8, :poll_interval_average=>nil, :average_scheduled_poll_interval=>5, :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x00007f76403fae18>, #<Raven::SidekiqErrorHandler:0x00007f7636ab2300>, #<Proc:0x00007f7636683d10@/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/sidekiq.rb:66>], :death_handlers=>[], :lifecycle_events=>{:startup=>[], :quiet=>[], :shutdown=>[], :heartbeat=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :reloader=>#<Sidekiq::Rails::Reloader @app=HerokuService::Application>, :verbose=>true, :limits=>{:thumb_image=>4}, :strict=>false, :config_file=>"./config/sidekiq.yml", :tag=>"app", :identity=>"background.1:4:a230ea8abb57", :fetch=>Sidekiq::LimitFetch}
2019-02-28T15:58:34.262481+00:00 app background.1 - - 4 TID-ou6yv8vjs Api::BackgroundRequestJob JID-938441f1737c768516eb805a INFO: start
2019-02-28T15:58:58.681202+00:00 app background.1 - - 4 TID-ou6yvb7jw DEBUG: enqueued retry: {"class":"Api::BackgroundRequestJob","args":[],"retry":3,"queue":"background_api","jid":"938441f1737c768516eb805a","created_at":1551369418.3886776,"enqueued_at":1551369418.3892639,"error_message":"Call received non OK status 500 for path '/api/v2/media.json'.","error_class":"Api::Exception::Unknown","failed_at":1551369508.460359,"retry_count":0}
2019-02-28T15:58:58.683340+00:00 app background.1 - - 4 TID-ou6yv8vtg Api::BackgroundRequestJob JID-938441f1737c768516eb805a INFO: start
```
Sometimes the error shown is indeed Sidekiq::Shutdown, but it can also be other errors that are caused by it.

Is this indeed the same issue? Would you have any recommendation to prevent it?

Thanks.

**Comment by mperham** [comment]
Please open a new issue, don’t reuse years old issues.
